### ISSUE TITLE
Exercise feedback option after exercise completion

### ISSUE THREAD

**Issue by pminten** [exercism/exercism.io#1081]
After exercise completion you end up in a page saying that the next exercise has been unlocked with a lot of whitespace on the right side.

Maybe we could have some simple optional survey questions there to let the users give feedback on exercises. For example 5 fields, all optional:

1. Did you like the exercise?
  * Liked
  * Neutral
  * Disliked
2. What do you think of the difficulty level?
  * Too high
  * High, but quite doable
  * Average
  * Low, a bit simple
  * Too low, trivial
3. Did you learn something from the exercise and feedback?
  * Yes, a lot.
  * Yes, a little.
  * No.
4. How much time did this exercise take you, approximately?
  * 0-10 minutes
  * 10-30 minutes
  * 30-60 minutes
  * 1-3 hours
  * more than 3 hours
5. Freeform comment field

Obviously if lots of people say they don't like an exercise that's a good indication it needs to be rewritten or taken out. Similarly exercises for which the difficulty level is either too high or too low could be put in a different spot in the track or taken out entirely. The other questions help get a feel for the educational value and complexity of an exercise.

**Comment by kytrinyx** [comment]
I've opened https://github.com/exercism/discussions/issues/86 to discuss this.
