### ISSUE TITLE
Allow deletion of submission

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#135]
1) if no comments
b) within {n} minutes of submitting, for example 3 or 5.

I don't want people to be able to delete stuff where there's already a discussion.

**Comment by metalim** [comment]
AFAIU it is not complete. Maybe backend is there, but `unsubmit` command does not work.

**Comment by iHiD** [comment]
Hey. This is 5yr old issue for a different version of the site. I recommend checking for newer issues or opening one if you can't find one. Thanks! :)
