### ISSUE TITLE
Add SETUP.md to each language repository with helpful instructions

### ISSUE THREAD

**Issue by bunnymatic** [exercism/exercism.io#1364]
Hey there

I'm a ruby developer by trade and thought I'd try to run through your clojure exercises.  I know I'm probably kind of dumb but I didn't think to look in the "Help" menu to figure out how to get clojure setup until way late in the game.  I wonder if it might be worth sticking a note in the README's for all projects - something like 

    If you're having trouble figuring out where to start, check the Help menu on http://exercism.io

Food for thought.

I'm hoping to contribute to the project in the future.  Keep up the good work.

Cheers
Mr Rogers

**Comment by kytrinyx** [comment]
I've opened an issue in each of the related language repositories.
