### ISSUE TITLE
General Question:  if you had a developer's time, what do you want/need?

### ISSUE THREAD

**Issue by bunnymatic** [exercism/exercism.io#1370]
I'm doing the clojure track and was playing on the ruby track (though I'm a ruby developer so that side is less about learning and more about seeing how the system works).  I noticed the first exercise is the same for all.   Do you want the ruby exercises ported to all exercises?  If I put some time in, where do you want it?  Your [contributing guide](https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md) doesn't really say what you *need*?  I think i really want to see a Pivotal Tracker list of issues that I could just start working on from the top.

Let me know.  Might be fun to help out.  So far, i'm digging the exercises and learning clojure.

**Comment by roseaboveit** [comment]
@bunnymatic Thank you for your interest in contributing. 

Were you able to find the answers you seek or are there questions we can answer more fully? 

Sorry if it is awkward checking back on this after so long. We just want to make sure that we answer any other questions you have before we close this issue.

**Comment by bunnymatic** [comment]
You could close this up.  If I end up finding time to work on things, I'll
check in with you guys at that point.

Cheers
Jon
