### ISSUE TITLE
Idea: Display the number of nits received

### ISSUE THREAD

**Issue by patbl** [exercism/exercism.io#1384]
I can see how many nits I've left on my account page, but there doesn't seem to be any easy way of finding out how many nits I've received. I don't know whether I'm a giver, a taker, or a matcher. Displaying the two figures side-by-side might lead to more nitpicking, since people tend to overestimate their contributions to group efforts. 

There might be a downside to doing this, however: people who give more nitpicks than they receive might nitpick less. This effect might be mitigated if you put a smiley face next to the figures of diligent nitpickers. My reasoning is base on a study utility bills, which you can read about [here](http://www.nytimes.com/2009/01/31/science/earth/31compete.html?_r=0).

A more extreme, complicated solution would be to take into account users' nitpick ratios in the ordering of the pending-submissions page. People who nitpick a lot would be given priority. This might not make sense given the number of users, but it could be something to consider in the future.

I bring up this issue because I've submitted about twenty exercises that haven't received any nits. This suggests to me that there may be a shortage of nitpicking, and that users should be encouraged to nitpick more. I'm not blaming anybody, though: I may well be part of the problem. :)

**Comment by jtigger** [comment]
This discussion is more than 2 years old.  If we need to revive it, we'll reopen (or create a new issue).
