### ISSUE TITLE
Optionally specify submission key in unsubmit API endpoint

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#1385]
The usual restrictions would still apply (window of opportunity, no nits, etc).

**Comment by kytrinyx** [comment]
This has a CLI component, and an API component (exercism API, not problem API).

CLI: https://github.com/exercism/cli/blob/master/cmd/unsubmit.go
API: DELETE /user/assignments (lives in `lib/api/routes/iterations.rb` at the moment)

**Comment by petertseng** [comment]
since [unsubmit is no more](https://github.com/exercism/cli/commit/43c03450132b379896bdf58db4c54e63562d84b6) , I suppose this could go

**Comment by kytrinyx** [comment]
Haha, yes. Thank you!
