### ISSUE TITLE
Number of nits per track in the nitpick menu

### ISSUE THREAD

**Issue by pminten** [exercism/exercism.io#1389]
I have access to a fair amount of tracks but to see the list of submissions that need nitpicks I need to look at the tracks one by one. It would be nice if the "Nitpick" dropdown menu would have the number of unnitpicked submissions in a track next to the track name. For example "Elixir (5)", "Haskell (10)", "OCaml (0)", "Ruby (25)".

**Comment by sguermond** [comment]
This is taken care of by the new inbox feature #2503.

**Comment by kytrinyx** [comment]
Oh, that's right. Thanks. Closing.

**Comment by kytrinyx** [comment]
Well... on second thoughts, kind of. It doesn't show how many don't have nitpicks at all. @pminten have you checked out the inbox feature? Do you still feel like there's a filter missing or a count of how many people don't have any comments at all?

**Comment by pminten** [comment]
Looks good to me now.
