### ISSUE TITLE
Sort submissions list by number of nitpicks by the submitter

### ISSUE THREAD

**Issue by Gaelan** [exercism/exercism.io#1512]
So, if you nitpick more, your submissions appear higher on the nitpick list. This makes it so that users are motivated to nitpick, since it means they get nitpicks faster themselves.

**Comment by kytrinyx** [comment]
Over the past few months I've been thinking a lot about how we present the solutions waiting to be nitpicked, and I've decided to replace the current "pending list" feature with an activity stream and granular subscriptions.

There are a lot of things we're going to need to do to encourage more nitpicking, but I suspect that the activity stream will make it much less overwhelming and will filter out a bunch of noise.

Here's the issue where we're starting to work on the activity stream: https://github.com/exercism/exercism.io/issues/1899
