### ISSUE TITLE
Error with "exercism fetch"

### ISSUE THREAD

**Issue by johngb** [exercism/exercism.io#1583]
Up until now the `exercism fetch` command has worked without a problem.  After completing the binary-search-tree problem in Go, I now get the following error when using `exercism fetch`:

`Error parsing API response: [invalid character '<' looking for beginning of value]`

**Comment by smbsimon** [comment]
Hey Katrina, I'm getting the same error after submitting Bob on the Python track. Hopefully it should be an easy metadata fix now that the cause of the bug is already discovered? Thanks!
