### ISSUE TITLE
Access from FP Complete's Community Edition?

### ISSUE THREAD

**Issue by fpcomplete-support** [exercism/exercism.io#1584]
FP Complete has a web-based IDE for writing and executing Haskell. That includes a free version with features designed to let people write and share Haskell programs with each other.

It would be great if there were some way to pull a solution to an exercise out of FPHC into exercism.io. Even access from the Personal Edition (not free, but cheap and allows pushing to git repositories and supports the fpco-api) would improve things.

**Comment by kytrinyx** [comment]
I'm going to close this as we've not managed to make any progress on it.

/cc @rbasso in case you have any sudden insights about how we could do this integration.
