### ISSUE TITLE
Gamify contributions to encourage more timely review times

### ISSUE THREAD

**Issue by zenspider** [exercism/exercism.io#1617]
I think if you added something as simple as "Top 10 Nitpickers" for all time and current month, you'd encourage people to review more.

If you took it a step further, and made it so submissions were pushed to the top of the review lists based on number of nitpicks, it'd incentivize people to review more so they get their own feedback quicker.

**Comment by jeffreybaird** [comment]
I've just restarted doing exercism since @kytrinyx's appearance on the Bike Shed podcast.

I think gamification would be a technical solution to what is a people problem. I would like to see a tutorial helping people get used to both sides of the review process. Maybe, there could be an interactive tutorial that guides you through your first review?

I love the idea of being able to give appreciation to those that review my solutions. I would be hesitant of any feature that ventures into a karma-type reward system. It runs the risk of people (especially newer coders) taking feedback as gospel from people with higher ratings.

**Comment by kytrinyx** [comment]
> Maybe, there could be an interactive tutorial that guides you through your first review?

I would love to figure out how to do this!

> I love the idea of being able to give appreciation to those that review my solutions.

Yeah, there's a difference between karma points and a friendly "thanks", but we also don't want to litter the conversation with something that is only really valuable to the two people that it's aimed at, when the conversation is potentially interesting to dozens or hundreds of people.

**Comment by jwood803** [comment]
> ...there's a difference between karma points and a friendly "thanks", but we also don't want to litter the conversation...

Random thought, but would reactions help with that?

**Comment by kytrinyx** [comment]
Yeah, I think it probably could.

**Comment by kytrinyx** [comment]
I'm going to close this, as I really don't want to go down the path of gamification. I still think there are things we could do to increase and improve interactions.

**Comment by zenspider** [comment]
Fair.... I do think there is some interesting things going on per-language. It'd be interesting to see some stats per language to see if there was something we could learn from some and inject into others.

**Comment by jtigger** [comment]
@kytrinyx this topic comes up so frequently and persistently, I'd almost want to pin this issue! :)  I think in the contribution documentation rework, we'll reference this issue directly.

**Comment by kytrinyx** [comment]
@zenspider yeah, there's definitely good stuff going on that we should learn from.

@jtigger It might be worth extracting the relevant stuff into a separate document. At some point. maybe.

**Comment by jtigger** [comment]
@kytrinyx agreed.  This topic has been pretty hammered out — not to say it can't be revisited — so it's a good candidate for being culled into something more succinct that references the instances.

I'm taking this thread to exercism/discussions#96 to get feedback on how that should look.

**Comment by iHiD** [comment]
@jeffreybaird 
> Maybe, there could be an interactive tutorial that guides you through your first review?

This, 1000 times this. (cc @kytrinyx @nicolechalmers)
