### ISSUE TITLE
Figure out heroku buildpack / lineman thing

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#1650]
Right now the hack is to copy & commit the generated stylesheets, which is pretty awful.

It would be awesome to figure out how to do this the right way.

I put a call out to @theotherzach (since he's helped me with this sort of thing before), and @fluxusfrequency and @jwood803  have both indicated that they might have a go at it.

I've put it on my TODO list to dig into if nobody gets to it before me.

If you're interested or have thoughts/comments/suggestions, or if you can think of any useful things I should stick in this issue to make it easier to tackle the issue, please speak up!

**Comment by mhelmetag** [comment]
There's a rake task that can get run automatically by Heroku `rake assets:precompile` that we might be able to use...

**Comment by kytrinyx** [comment]
Oooh. That would be lovely. Eventually I want to rewrite everything to just use gulp or grunt straight-up with no extra frame-work-y stuff, but it's not exactly next on my list.

**Comment by kgrz** [comment]
> Right now the hack is to copy & commit the generated stylesheets, 

I'm curious, what's the step where we need to manually copy the stylesheets? I ran `compass compile` and the compiled file gets saved as `public/css/application.css` which is already in the source tree.

**Comment by mhelmetag** [comment]
I think just adding those files compiled css files and committing them.

The next steps would be to have the compilation process kick off during deploy so that we wouldn't be checking in compiled assets (I could be wrong but that's what I think is best practice).

**Comment by kytrinyx** [comment]
Oh, yeah, we don't need to manually copy, just manually commit, which is dirty.

> The next steps would be to have the compilation process kick off during deploy so that we wouldn't be checking in compiled assets (I could be wrong but that's what I think is best practice).

Yepp, agreed.

**Comment by tejasbubane** [comment]
Fixed via #2949
