### ISSUE TITLE
What do you want to see on your dashboard?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#1654]
The dashboard has been pretty useless. What would be helpful to see there?

**Comment by swalberg** [comment]
What about putting the graph in "nit stats" on the dash? Gives people some incentive to keep active without turning to gamification. Or, failing that, some of the "streak" stats like GitHub does -- you've provided feedback every day for a week or something like that.

**Comment by kytrinyx** [comment]
I would *love* to have a streak on the dashboard! Nitstats could work too, but a streak would be fantastic.

**Comment by thesmallboys113** [comment]
Or a personalized background!

**Comment by Marinlemaignan** [comment]
sorry i couldn't read the entire thread...
i'd love something that'd show others answers to the same exercise on a single page
maybe coupled with the up(&down?) voting system so that you could easily see which are the community's prefered way of solving the problem, cause some of us here are damn good, and i've seen some really good stuff... but god i had to click so muuuch i couldn't even play a point and click game

**Comment by kotp** [comment]
:+1:  on the single page ranked listing of a completed exercism.

But, this shouldn't detract from having a list of un-actioned solutions as well.

**Comment by kytrinyx** [comment]
Yeah, it would be great to see existing answers to completed problems. I do apologize for all the clicking :/ I don't have any design chops and that's not something that people tend to contribute to open source.

**Comment by cjchallis** [comment]
It would be great to see your current exercise (not solution submitted yet).  For those of us that can't find time for a while, it can take a minute to even figure out which exercise you need to return to.

**Comment by tejasbubane** [comment]
This could be helpful @cjchallis :+1:

**Comment by IanVS** [comment]
If a way to favorite items such as iterations or comments is implemented (see https://github.com/exercism/exercism.io/issues/2080), I would want to see those on my dashboard.

**Comment by gkolok** [comment]
+1 for following people.
When I browse solutions of others, would be nice to filter down to those having likes (marked by 'Looks great!')

**Comment by h-core** [comment]
@cjchallis If you just run ```exercism fetch``` again you will get a list of the active problem for each language.

As for dashboard improvements it would be great to see some of the following for the latest problems you've solved:
* Top rated submissions
* The quickest executing solutions
* The shortest solutions

**Comment by chesterl** [comment]
The notifications should remain after you've checked them in chronological order.

 Right now they disappear and you have to dig through either the nit area to find them. 

I would love to contribute to this project but have no idea where to begin since I'm a newer dev and I've haven't contributed to OS (yet) :)

**Comment by kytrinyx** [comment]
Hi @chesterl -- Yeah, the notifications thing is definitely not there yet. We're working towards implementing an ActivityStream where the notifications would remain. What language(s) do you work in? I might have some things that don't require wrapping your brain around the entire project at once.

**Comment by bmulvihill** [comment]
In regards to the activity tracker idea from above you can use a javascript library like highcharts to create a heat map, I attached a sample image from my fork using dummy data. 
![screen shot 2015-05-24 at 8 28 17 am](https://cloud.githubusercontent.com/assets/3128920/7787842/e8196dc8-01ee-11e5-8cab-e55b0bc38345.png)

**Comment by desmondnzuza** [comment]
I think showing teams that are working on the same problem set that you are, working on would be nice, because it would make it easy for people like me who are looking to join teams

**Comment by kytrinyx** [comment]
That's really neat!

**Comment by hicksca** [comment]
+1 @bmulvihill

**Comment by Lswith** [comment]
share buttons everywhere! I was trying to get my colleagues into exercism and I had to be a pleb and email them a link. Also it would be super nice to invite people through an email so that I can add them to my team.

**Comment by carl-parrish** [comment]
Mozilla Open Badges / scoring system for how often you've made nitpics how many solutions and what your current streak is (sort of like Free Boot Camp http://www.freecodecamp.com/cparrish)

**Comment by kytrinyx** [comment]
Yeah, I really like the streak idea. (btw, congrats on your current 5 day streak, @carl-parrish :) )

**Comment by davidpbrown** [comment]
Persistent login would be useful.

Colour of dropdown menu - dark grey text on black, makes those less obvious on some screens.

Some sense of the depth would be good.. relative to the users interest. So, I've started Rust and an indicator of progress relative to the total number of exercises would be interesting.

**Comment by kytrinyx** [comment]
I'll see of someone with front-end-y skills can help out with the dropdown. The login piece would require some proper security, so I've been putting that off.

The content relative to the user's interest is a really important one. Thanks.

**Comment by carl-parrish** [comment]
Perhaps a graph of top languages and Interests (sort of like https://coderbits.com/cparrish817) Speaking of.... I would really, **really** like it if exercises I passed on exercism was pushed up to CoderBits.

**Comment by carl-parrish** [comment]
[CodeEval](https://www.codeeval.com/profile/carl-parrish/) is another good example of a dashboard I think.

**Comment by kytrinyx** [comment]
Thanks for the suggestions, looking at them now.

**Comment by sguermond** [comment]
Here's a quick rearranging of the dashboard from existing content (making it more visible, minor tweaks etc.) Didn't change any CSS so some parts are kind of wonky.

![exercism dashboard](https://github.com/sguermond/images/blob/master/exercism_proposed_dashboard.png?raw=true)

Opinions?

**Comment by kytrinyx** [comment]
It works for me. I don't know how this would perform for people who are very active. We'd need to test that out.

**Comment by kendriu** [comment]
+1 for integration with [CoderBits](https://coderbits.com/kendriu)

**Comment by kytrinyx** [comment]
Thanks for the vote, @kendriu.

**Comment by kytrinyx** [comment]
ref: https://github.com/exercism/exercism.io/issues/2711

**Comment by kytrinyx** [comment]
Thank you, everyone, for participating in this discussion. We have an open issue for some UX changes here: https://github.com/exercism/discussions/issues/33, and I'm going to close this one.
