### ISSUE TITLE
Develop a tiny "Operation Inbox Zero"

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#1661]
I'd like to try an experiment where we choose one overwhelmingly backlogged exercise and encourage people to nitpick ONE thing off that backlog.

Any ideas about how this might be done? What is the smallest thing that we can do that might help clear a backlog (and then what could we do to keep it flowing)?

**Comment by daveyarwood** [comment]
I would personally enjoy having a button I could click that would give me a random solution for me to nitpick. If we had something like that, especially in combination with some sort of incentivization/gamification of nitpicking (i.e. #1617, #1978), I think that could make short work of the backlog.

**Comment by kytrinyx** [comment]
I used to have a random solution on the dashboard, but it seemed like it was mostly getting ignored. I've been dealing with onboarding issues over the past months, and am just about to start looking at how to close the feedback loop, so I'll bring this idea back up for some thought.

**Comment by kytrinyx** [comment]
I failed to make progress on this. I'm going to table the idea.
