### ISSUE TITLE
No explanation of teams in the help

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#1673]
...or maybe I just couldn't find it.

I don't understand what the "Dismiss" button does on the team page.

**Comment by mandel01** [comment]
I am familiar with Exercism but curious about teams. Before imposing this on people in my lab group I'd like to know what a team involves! My guess is below... Do I have it right? I think this would be great info to have on the [teams sign-up page](http://exercism.io/teams).

```
What is a team?

Team members get notifications when anyone on the team submits a new iteration of an exercise.
```


My additional questions:

- Are team members notified if I submit feedback on another team member's exercise?
- Are team members notified if I submit feedback on a general Exercism user's exercise?

**Comment by NobbZ** [comment]
As it is now, there are no team related notifications :-( all you get is an
activity stream filtered by the members of your team.

Mark Mandel <notifications@github.com> schrieb am Mi., 8. Juni 2016 23:54:

**Comment by mandel01** [comment]
@NobbZ thanks for the information. How about this to provide basic info on the sign-up page?

```
By setting up a team you will be able to view a separate activity stream for your team members' submissions.
```

**Comment by kytrinyx** [comment]
> By setting up a team you will be able to view a separate activity stream for your team members' submissions.

Yeah, this is good, @mandel01! The activity stream can be filtered by language or language/problem (like the track streams under "Activity Streams" in the top menu), and also by user or user/language. If you're on the same team, you don't have to have submitted a solution for the exercise—you still get to see what the others wrote.

You only get notifications if you have commented on a solution, or if you subscribe to the conversation.

**Comment by mandel01** [comment]
@kytrinyx Sounds good. I see the [`new.erb`](https://github.com/exercism/exercism.io/blob/master/app/views/teams/new.erb) but am not familiar enough with the Ruby / HTML to propose a PR without screwing it up! If this is still open in a few weeks I'll work through the steps in the [Contributing Guide](https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md) to add a brief note on the team sign up page.

**Comment by bernardoamc** [comment]
Is this still an issue?

**Comment by kytrinyx** [comment]
I think we're good here.
