### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by cdroulers** [exercism/exercism.io#1675]
Allowing the web site and the problem descriptions to be in other languages would be a plus for certain teams!

I guess that requires changing a lot of the code to support locales!

It also requires a community for translating strings, which I'm ready to contribute French to! (Transifex is a great tool and it's free for open-source).

**Comment by LegalizeAdulthood** [comment]
I think this vision issue would be helped by a checklist of everything that needs to change to support a language.  Let's pick a language that has the most translation volunteers as the 2nd language we support.

**Comment by kytrinyx** [comment]
Like I said earlier, I don't think the prototype is ready for this, as it would add a huge amount of complexity into something that already isn't designed (well or at all).

There are several important things that I think need to be solved before adding support for a second language. The main three being

a) an onboarding/installation process that isn't acutely painful
b) swapping over from the current haphazard workload/notification/mutes/pending/needs-input list to an activity stream where people can tune the stream to be relevant to their interests
c) bottlenecks: in most languages many people submit assignments, few people provide feedback. I have some ideas about how to fix that, but it's not just a matter of coding up something over a weekend.

I'm very, very excited about the idea of localization, I just don't see it as more important than bottlenecks and activity stream (core feature), and I don't really want to be concentrating on onboarding a bunch of people until the core stuff is solved.


Off the top of my head, here are some of the things that would need to happen:

- in x-common, provide metadata in multiple languages (e.g. hamming.en.md, and keys per language in the yaml.
- in x-api, be able to request problems in a given human language in addition to programming language
- in exercism, we would need to know what someone's language preferences were
- in exercism all of the text/content would need to live outside of the views
- in the CLI, all of the output needs to be language-specific, and we need to know which language someone is using
- all of the error messages everywhere (x-api, exercism, cli) would need to be handled correctly
- rikki's comments need to be translated
- rikki needs to know which language to submit the comments in
- notification emails need to be translated (right now emails are completely hacky, and this should also be addressed before adding complexity of multiple languages. Also we need to make emails something you can opt out of in a granular way. Right now it's all or nothing: you delete your email address, and you do't receive emails).
- when displaying things to nitpick, you should only nitpick something if you speak the submitter's human language, so we would need to filter what you see to be appropriate.

I'm sure there's more, but like I said above, I really would like to address the core usability problems before trying to add this feature.

**Comment by kytrinyx** [comment]
I've decided to close some of the issues that I would like to get to, but that aren't about getting the basics of exercism right (onboarding, rich conversations, quality feedback).

I'm adding the tag "future roadmap" so that we can find all of these great ideas when we're ready for them.

https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#future-roadmap
