### ISSUE TITLE
Team members: mentors

### ISSUE THREAD

**Issue by novohispano** [exercism/exercism.io#1685]
Currently, in a team we have **members** (who are the students), and **admins** (who are the instructors). However, we don't have a team membership that includes **mentors**. 

In my opinion, mentors should be able to,

1. See the students work.
2. Don't have privileges to delete or add members.
3. Be distinctively (visually) separated from the students.
4. Decide whether they can be nitpicked or not by the students.

Thanks!

**Comment by kytrinyx** [comment]
We now have support for this, as we've changed the format to managers / members, and everyone can see everything in the team activity stream. There are no notifications anymore specifically for teams.
