### ISSUE TITLE
[docs repo] Gray on white text is too low contrast making it hard to read

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#1688]
The help styling has the normal text in gray on a white background.  This is very low contrast, making it hard to read the text.  A high-contrast color scheme should always be used for text to aid legibility.
![reading](https://cloud.githubusercontent.com/assets/4270863/3920752/e345f00a-23b9-11e4-987f-1c516505c0be.png)

**Comment by kytrinyx** [comment]
I darkened the text.

Incidentally, the docs repo needs a complete overhaul. There's a redesign in progress, but I need to do a new backend.
