### ISSUE TITLE
Clarify concept 'track' throughout the codebase

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#1699]
Right now the domain concepts are a jumble.

Currently a submission and user_exercise have a field or method `language`, which is actually the `track_id` (per the x-api repository, see http://x.exercism.io/tracks).

A track is a collection of problems, and it is in a single language. The language and track id are similar, but not identical, and there is no algorithmic translation between the two:

- ruby—Ruby
- javascript—JavaScript
- objective-c—Objective-C
- fsharp—F#
- cpp—C++
- ...

It is therefore better to simply separate these two concepts and not try to get the language name from the track id in some automated way.

The trickiest part in clarifying the concepts is migrating the columns in the database without taking the site down.

This is the suggested path:

- [x] create a method `track_id` on `Submission` and `UserExercise`
- [x] use this method everywhere in the code base
- [ ] create a db migration that adds the `track_id` field to both tables, without removing the old one
- [ ] create an after-save hook on both models that populates the `track_id` field
- [ ] create a rake task (data migration) to populate all old `track_id` fields
- [ ] deploy and migrate
- [ ] change the models to write to the `track_id` field instead of the language field
- [ ] delete the after-save hook
- [ ] write a migration that drops the `language` field on both tables
- [ ] deploy and migrate

**Comment by adamnbowen** [comment]
@kytrinyx A lot can change in a year and a half—are you still okay with deploying and migrating all at once, or would you prefer a solution for this go forward that does the multi-stage deploy you mentioned at the top of this issue?  Also, since it's been so long—are you still interested in seeing this get pushed forward?

**Comment by kytrinyx** [comment]
I've done a bunch of migrations like this in the past 18 months, and I've done all of them in multiple steps. It really makes me uncomfortable to consider doing it in one fell swoop.

I do want to move forward with this change (it's on one of my "if I have a spare day" lists... haven't had a spare day for a while).

**Comment by kytrinyx** [comment]
I'm going to close this, as there are a number of larger-scale refactorings that need to be done, and we should probably tackle them in a more coordinated way.
