### ISSUE TITLE
Wishful Thinking: Windows Installer

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#1706]
Here's what I think would be absolutely lovely:

A download button that puts a thingy in your downloads folder (or whatever it's called), that you can double-click on to install exercism, and it would set up the path and everything. Maybe it could give you a shortcut that would open your terminal or console or whatever and put you in the correct directory.

/cc @jwood803 @LegalizeAdulthood - do either of you know anything about making installers for windows? Any idea what I should be searching for to figure out whether or not this is doable?

**Comment by iamharshit** [comment]
@Dangthrimble machaya be

**Comment by iamharshit** [comment]
while doing `exercism fetch python` on windows i am getting an error that 'No connection could be made because the target machine actively rerfused it ' , ANY HELP.....

**Comment by tejasbubane** [comment]
Hi @iamharshit, please [open a new issue](https://github.com/exercism/exercism.io/issues/new) with your query. Also include the output of running `exercism debug` so that it will be easy for people to debug the issue.

**Comment by iamharshit** [comment]
@tejasbubane as you asked, open the issue **UNABLE TO FETCH ON WINDOWS #2853**
