### ISSUE TITLE
Explore good solutions after completing an exercise

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#1709]
When you're done with feedback on an exercise, I think it would be useful to allow the person to see the "example" solution that is checked into the language track repository.  As near as I can tell, these example solutions are checked in but aren't ever visible to a student unless they browse the repositories on github.  Thoughts?

**Comment by kytrinyx** [comment]
I think the most promising direction we've got going is the discussion about using machine learning / AI to create heatmaps of solutions: https://github.com/exercism/discussions/issues/65

I'm going to go ahead and close this, but please add ideas to that discussion if you think there are important things here that are not reflected there.
