### ISSUE TITLE
Weird spacing on the team page for my first open exercise

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#1711]
Not sure where this is coming from... It's a JavaScript exercise, so I can't blame it on C++ new-ness :-)

![spacey](https://cloud.githubusercontent.com/assets/4270863/3975530/117a90f2-280b-11e4-95ad-781dddb47326.png)

**Comment by kytrinyx** [comment]
I think this got fixed at one point. @LegalizeAdulthood are you still seeing the weird spacing issue?

**Comment by mfrost** [comment]
I'm not seeing this locally on the `/teams/:name` page. Is that the correct location to exercise this bug?

**Comment by kytrinyx** [comment]
Yeah, that's the correct location. Thanks!
