### ISSUE TITLE
Display exercises available for nitpick in language track order

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#1720]
OK, maybe this is a little unusual, but right now I have a whole bunch of C++ exercises submitted but not yet done, which means I can view a whole bunch of exercises by other people in C++ available for me to nitpick.

However, when I browse the nitpick for C++ page, the exercises seem to be presented in some sort of semi-random order, perhaps by timestamp of submission?  I think it would make more sense if they were presented in language-track order according to the `config.json`.

![nitpick](https://cloud.githubusercontent.com/assets/4270863/4097795/7133c67c-2fe4-11e4-8c6e-f911b152a771.png)

**Comment by kytrinyx** [comment]
This was fixed when we ditched the old "pending" lists and moved to the new inbox model.
