### ISSUE TITLE
Feedback notification email gives link to "find out more", but feedback isn't there.

### ISSUE THREAD

**Issue by houhoulis** [exercism/exercism.io#1736]
I received an email from exercism:

```
Your submission on Raindrops in Ruby has received the following feedback from [redacted]!

If you require help with finding the prime factors take a look at the Prime class in Ruby.

www.ruby-doc.org/stdlib-1.9.3/libdoc/prime/rdoc/Prime.html

Visit http://exercism.io//submissions/829ae337a2a987c56a46ce16 to find out more.
```

However, when I click the link, I go to the page of my submission, but there is no feedback.

@kytrinyx suggested this might be due to the sender deleting their feedback after submitting it:

  > It's not intentional that you can't respond to it in any way....
  > This is confusing and should definitely be addressed in some way.

I'm not sure what the right approach is, but @kytrinyx asked I file an Issue.

In general, I'd like to be able to respond to feedback, even if the sender wants to disavow what they wrote.  Perhaps the UI could appropriate the diff view in GitHub, where "outdated diffs" get hidden but can be expanded?  I think discussion is core to exercism, but opening yourself to potshots with no chance to respond is not.

**Comment by kytrinyx** [comment]
I'm going to close this, since I can't think of a way to address it directly, however there are a number of other efforts in place that might make this a non-issue. In particular, the activity streams will improve notifications dramatically, I think: #1899
