### ISSUE TITLE
Trying to debug exercise using Xcode

### ISSUE THREAD

**Issue by EricRFMA** [exercism/exercism.io#1762]
Wow... this forum is busy!
Just to add to the fun... It's difficult (impossible?) to debug an exercise on the Mac using Xcode.

The problem is that the tests are run automatically as part of the build (not a bad thing in principle), but that happens "outside" of Xcode.  So there's no automatic way to try to debug the exercise code you've written if you build it in Xcode.

There may be a workaround, I'll see if I can find one.

**Comment by kytrinyx** [comment]
@EricRFMA Did this ever get resolved? Should I try pulling in someone else to help figure it out?

**Comment by kytrinyx** [comment]
I'm going to close this, but if you are still having trouble, please feel free to reopen it.
