### ISSUE TITLE
Document how to move your exercism working folder

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#1778]
We should document how to move your exercism working folder to a new location.  I think all that is necessary is to delete the `.exercism.json` file and run the necessary exercism command in the new location, but I am not certain.

**Comment by tejasbubane** [comment]
As @EricRFMA said, even I edited the json file on one of my linux machines to change the directory path and it works. Is it recommended the edit the json file?

**Comment by tejasbubane** [comment]
Currently configuring API key is documented under the [fetching exercises section](http://help.exercism.io/fetching-exercises.html). If we are going to add this one, I think it would be better to create a separate section for "Configure Exercism" between installation and fetching exercises rather than pushing it in fetching section.

**Comment by kytrinyx** [comment]
> Is it recommended the edit the json file

I think that's fine.

> If we are going to add this one, I think it would be better to create a separate section for "Configure Exercism" between installation and fetching exercises rather than pushing it in fetching section.

Agreed, it should go in a separate section.

**Comment by cross5464** [comment]
i just changed mine. it's "exercism configure -w C:\your\work\directory" i use windows 64-bit

**Comment by ashwinvidiyala** [comment]
>In command line if you type in "exercism configuration --dir=/path/to/project" it'll change your directory. However, if you type in "exercism configuration" without any parameters, it seems to just reset the configuration file to the default and write the .json file in the default location.

Worked like a charm. Thanks @pavel3!

**Comment by frunks** [comment]
Thank you, I was wondering about this as well!

**Comment by jonakirke94** [comment]
Seems their is a new naming convention as the command is now 

> exercism configure --workspace="/path/to/project"

**Comment by scostanzo** [comment]
> Seems their is a new naming convention as the command is now
> 
> > exercism configure --workspace="/path/to/project"

it worked for me, thanks

**Comment by Avik1993** [comment]
> > Seems their is a new naming convention as the command is now
> > > exercism configure --workspace="/path/to/project"
> 
> it worked for me, thanks

This worked for me

**Comment by Naxos84** [comment]
Not matter what the correct solution is. It should also be stated here: https://exercism.io/cli

**Comment by mahbub-ul-islam** [comment]
If you wanna go through the process and understand exercism cli, Follow through,
on cmd
~exercism --help
which will show you all available commands
~exercism configure
which will show you the current configuration
~exercism configure --workspace=C:\path\to\the\dir
which will change your current working directory.

**Comment by hanisntsolo** [comment]
how to you upload custom file from a path?

**Comment by kotp** [comment]
@hanisntsolo this is not the issue for that question, the question was how to move the exercism working folder.

You are very welcome to ask at the [support channel] for interactive help for what it is you are trying to do.  Please do show what you have done, what you expected to happen, what happened and we will be able to understand better how to help you.

If you prefer, you could also open an issue for the problem you are having, if you think it is related to Exercism tooling or the website.  I do not think it is that issue though.  I suspect it is something that you are personally trying to do in a custom way.  In any case, the support channel will be definitely direct you back if that is needed to create a new issue.

[support channel]: https://gitter.im/exercism/support

**Comment by Peter-Immanuel** [comment]
For the initial problems i did main using this command to change the workspace "exercism configure -w /path/to/new/work/space/

**Comment by tombohub** [comment]
If you want to make current directory as workspace use `exercism configure -w .`

**Comment by belgoros** [comment]
> > > Seems there is a new naming convention, as the command is now
> > > > exercism configure --workspace="/path/to/project"
> > 
> > 
> > it worked for me, thanks
> 
> This worked for me

This creates a directory inside the existing one. In my case, when using GitBash on a Windows PC, I already have the directory `/c/Users/my-user-name/projects/elixir`, and after running ` exercism configure -w /c/Users/my-user-name/projects/elixir`  and cloning an exercise with: `exercism download --track=elixir --exercise=killer-sudoku-helper`, it created it in `"C:\Users\my-user-name\projects\elixir\elixir"`.
Here is the output after modifying the workspace:
```
$ exercism configure -w /c/Users/my-user-name/projects/elixir

You have configured the Exercism command-line client:

Config dir:                       C:\Users\my-user-name\AppData\Roaming\exercism
Token:         (-t, --token)      XXXXXXXXX
Workspace:     (-w, --workspace)  C:\Users\my-user-name\projects\elixir
API Base URL:  (-a, --api)        https://api.exercism.org/v1
```

**Comment by glennj** [comment]
@belgoros yes, that's how it works: exercises you download are put into a "track" directory. You'll want to set `C:\Users\my-user-name\projects` as your workspace.

**Comment by belgoros** [comment]
> [@belgoros](https://github.com/belgoros) yes, that's how it works: exercises you download are put into a "track" directory. You'll want to set `C:\Users\my-user-name\projects` as your workspace.

Oh, yeah , I see, it's clear now, - `elixir` was added to the track. In my case the existing directory  was also named as `elixir`, that's where the confusion came ;). Thank you.
