### ISSUE TITLE
Can we use StackOverflow for support questions?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#1838]
Is it feasible/allowed to use StackOverflow with a tag #exercism for the non-bug type support questions?

In other words -- can't figure out how to install CLI, or fetch, or whatever (on the one hand), and "trying to do this thing in Haskell/Python/whatever" on the other.

It seems like Joel Spolsky thinks this is fine (not abusive): http://meta.stackexchange.com/questions/133522/encyclopedia-stack-exchange-vs-commercial-products

Thoughts?

**Comment by kytrinyx** [comment]
Update: This turns out to (a) not have worked at all, and (b) not have been a good idea in the first place. I suspect that had I used stackoverflow more consistently I would have known that, and in the future I would highly recommend just asking questions about use cases in the "meta" section there. They're very active, and very responsive.

I've had help from the stackoverflow community clearing out the tag, and I've deleted the documentation/links/suggestions to use stackoverflow for asking for help. If anyone sees any leftover references, please either submit a PR or let me know so I can clean it up.

So far GitHub issues have been the most useful support channel, I'd like to keep figuring out how to do that better.

**Comment by jwood803** [comment]
I feel bad it didn't work out but it does seem that it does work out better for folks to come here for the first line of support.

**Comment by jwood803** [comment]
Just a thought, would it be better to replace this with the Gitter link?

**Comment by kytrinyx** [comment]
Do we have a gitter link? I haven't even tried gitter out yet, though I think it seems like it would be a good idea.

**Comment by jwood803** [comment]
It should be [here](https://gitter.im/exercism). I've been in and out of it for a bit, but hopefully it can get some use after some advertising.

**Comment by kytrinyx** [comment]
OK, cool. There's a README badge available for these, right?

**Comment by jwood803** [comment]
I can search for it. If I find one I'll just update it. :)

-----Original Message-----

**Comment by kytrinyx** [comment]
Awesome!

**Comment by jwood803** [comment]
[Found it](http://blog.gitter.im/badgers/)! Just update the README in the main exercism.io repository?

**Comment by kytrinyx** [comment]
Yeah, replace the hacked in version that I put in :) (I went and found someone else's badge and then made a good guess).

**Comment by jwood803** [comment]
Heh, I figured you just beat me to it. I think that can work, though.

**Comment by jwood803** [comment]
Just a thought, as well...should we put this on different places in the site as well? Maybe the main page and the help?

**Comment by kytrinyx** [comment]
Yeah, we should. Would you open an issue for it?

**Comment by jwood803** [comment]
Sure! I'll probably do a PR for it, as well.
