### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#1843]
Sometimes the API encounters an error and returns an error message in HTML format rather than JSON format. The CLI is unable to handle this, and the user gets a completely unhelpful error message:

`error parsing API response - invalid character '<' looking for beginning of value`

I do not yet know what is causing this.

It would be helpful to know:
- where on the filesystem were you when this happened? (what does `cwd` or `pwd` say?)
- what command you called (e.g. `exercism submit Year.cs`)
- what the output of `exercism debug` is (remember to delete the API key).

Some things to try:
1. Make sure that the ExercismDir in `exercism debug` is where you expect it to be. If you say `exercism fetch`, then it will put problems inside of that directory, organized by language.
2. If you are unable to submit using the `full/path/to/file.ext`, then try to `cd` into the problem directory and submit using `exercism submit file.ext`, to see if that changes anything.
3. Open up the `~/.exercism.json`. The configuration could be broken. To reconfigure from scratch delete the file and call `exercism configure --key=MY_KEY`.

**Comment by finder518** [comment]
@kytrinyx 您好，我也碰到同样的问题，请问你的这个问题解决了吗？用得什么办法解决的，能分享一下吗？我的邮箱finder-fa@qq.com，谢谢

**Comment by kytrinyx** [comment]
@finder518 你好，你使用哪个命令？这是什么`exercism --version` 产生?

**Comment by javadev** [comment]
In may case the error message

> Your organization has selected Zscaler to protect you from internet threats.

**Comment by codeinabox** [comment]
> In may case the error message
> 
> > Your organization has selected Zscaler to protect you from internet threats.

Is there a way to get Exercism to work with ZScaler? For Node, I was able to set the root certificate eg `export NODE_EXTRA_CA_CERTS=~/certs/ZscalerRootCertificate-2048-SHA256.pem`

**Comment by iHiD** [comment]
> Is there a way to get Exercism to work with ZScaler? For Node, I was able to set the root certificate eg export NODE_EXTRA_CA_CERTS=~/certs/ZscalerRootCertificate-2048-SHA256.pem

You're best asking this on the forum (https://forum.exercism.org). This thread is a decade old and unlikely to have anyone watching it that will help.
