### ISSUE TITLE
Write documentation about FAIL - FIX - REFACTOR

### ISSUE THREAD

**Issue by stonemirror** [exercism/exercism.io#1869]
First off, Exercism is a terrific idea.

One issue I've run into is some initial difficulty/frustration in getting to the point where I could simply run a unit test and have it fail, working along the "FAIL, FIX, REFACTOR" model.

Specifically, I spent a lot of time scratching my head over why I couldn't get my Javascript "Bob" submission to work with the test spec at all. It turns out that the spec is written in such a way that I was required to name the file with my own code in it "bob" rather than "bob.js".

For another example, I know a little bit of Perl, but getting your fingernails under the first exercise requires that you know how to correctly set up a Perl module, something I had to research a little to get started on that.

Would it be contrary to the spirit of things to include "skeleton" files for submissions in at least the very first examples? For instance, here's my (completely non-working) "bob.pm" file:

=====
package Bob;

use strict;
use Exporter;
use vars qw($VERSION @ISA @EXPORT @EXPORT_OK %EXPORT_TAGS);

$VERSION     = 1.00;
@ISA         = qw(Exporter);
@EXPORT      = ();
@EXPORT_OK   = qw(hey);
%EXPORT_TAGS = ( DEFAULT => [qw(&hey)],
                );

sub hey {
	# YOUR CODE GOES HERE
}

1;
=====

Similarly, a Javascript skeleton for the "Bob" exercise could be a) correctly-named to work with the test spec, and b) might contain something like:

=====
var Bob = function() {};

Bob.prototype.hey = function(input) {
	// YOUR CODE GOES HERE
};

module.exports = Bob;
=====

Thoughts?

**Comment by kytrinyx** [comment]
I think the ideal solution to this would be to find articles out in the world about test driven development, and link to them from the track documentation.

I'm closing this in favor of the discussion in https://github.com/exercism/discussions/issues/87
