### ISSUE TITLE
Update Lua docs to describe installation with Chocolatey (for Windows)

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#1878]
This arrived in my email inbox from a kind fellow named Travis:

---------------

Hey there, I am a windows user and I wanted to take the Lua course but was
at odds and ends with the idea of homebrew being just an OSX library. Like
any good techie I found a workaround and was wondering if you could maybe
update the tutorial to work with it. I would do it myself on a GIT fork but
I have bad internet and can't download much right now. Here is the solution
I'm using --- I

Click "Start"

Type "cmd" --right click an run as administrator

Paste this code into cmd @powershell -NoProfile -ExecutionPolicy

```plain
> unrestricted -Command "iex ((new-object net.webclient).DownloadString('
> https://chocolatey.org/install.ps1'))" && SET
> PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
```

This installs the Chocolatey framework which is VERY similar to homebrew.

from there out replace  all "brew" commands with "choco"

http://chocolatey.org/

**Comment by jtigger** [comment]
Moved to the xlua repo.

**Comment by kytrinyx** [comment]
Thank you, @jtigger!
