### ISSUE TITLE
Nitpickability of initial solutions

### ISSUE THREAD

**Issue by dal-exer** [exercism/exercism.io#1893]
Like the site, but one thing I've noticed about how I use it is that I'll generally submit a solution, then immediately look at what other people have done in their solutions and compare before revising my own. Had a couple of occasions now like this http://exercism.io/submissions/77ac25fc6a92e70ca47d8575 where the process is:

1) Submit a solution
2) Look at other people's answers and find better ways of completing the task
3) Submit a second solution incorporating the best of what I've found
4) Notice that someone took the time to comment on my initial solution, telling me about the things I already found in step 2).

Being as it is that there is only so much time people are going to spend commenting on other's code I wonder if perhaps having the default status of first solutions set to non-browseable (i.e. they don't appear in the nitpick listing) would be worthwhile (with the option of the author changing that status for the first submission from the submissions page or making a second submission which would be automatically nitpickable as all submissions are at the moment)? 

This would let people who are going to do what I do and look around at other people's code before making another revision do so, and save the set amount of effort that people are going to spend commenting on others' code for those who can't/won't improve their code based on what they see in existing solutions (or those who already have and have still missed something).

Perhaps a setting could be added to the account settings to toggle this off on a global/per language scale (i.e. 'automatically mark all first drafts as viewable' or something). Alternatively the 'first draft non-viewable' option could be an opt-in instead of opt-out, although I wonder if all that many people would be aware of it if that were the case.

I know this wouldn't be a small or effortless change, just thought it might help concentrate the help people are willing to give where it would be most needed.

**Comment by kytrinyx** [comment]
I've spent a fair amount of time over the past few weeks doing an audit of the exercism issues.

It's become clear that there are some core issues that need to be solved before we can an evaluation about optimisations like this one. The most important things in the near term are making sure that the conversations are rich and useful, and that everyone who submits code gets feedback. Then, once we have a handle on that, we can look at optimising when that feedback happens (first solution vs second solution).

Thanks so much for bringing this up.
