### ISSUE TITLE
fetch to not fetch previous exercises

### ISSUE THREAD

**Issue by SquireLabs** [exercism/exercism.io#1895]
I recently got started and to avoid the hassle of finding the new fetched exercise I deleted all the old exercises. I noticed that with fetch, it fetched the old exercises again (but without my code). I'd prefer only getting the last exercise. Perhaps one could build in a switch to only fetch the next exercise, instead of the whole bunch?

**Comment by kytrinyx** [comment]
We've updated the CLI to not fetch previous exercises by default.
