### ISSUE TITLE
Activity Streams (to replace pending lists and notifications)

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#1899]
Right now the pending lists are completely unweildy, and the notifications are a firehose.

Let's explore what an activity stream would look like in terms of exercism.

I'd like to have subscriptions that make it possible to follow

* a language track
* a problem in a language
* a person
* an exercise (a problem being solved by a particular person and the conversation that belongs to it)

That way it should be possible to tune what you're seeing to be more relevant to you.

On the front-end I think that it should be an activity stream with the newest stuff at the top, and endless scroll.

I'd be interested in seeing ideas for the UI/UX (just napkin-level drawings, nothing fancy), and hearing suggestions for the backend. I'd like to build the backend as a completely stand-alone thing in order to make it easier to make good choices without being influenced by the existing prototype code.

**Comment by kytrinyx** [comment]
OK, so I've finally had some time to think about this feature. As I see it there are a number of pieces:

**subscription UX**

This is the interface where a user would be able to subscribe or unsubscribe to:

* Users (search for users to follow, and follow/unfollow)
* Teams (each team that they're a member of would be listed, we need to think about what types of subscriptions we want within the team: everything, only in a particular language, only particular problems)
* Exercises (this is a problem that is being solved by a particular user, it will be nice to unsubscribe from conversations that you got pulled into but don't have any particular interest in)
* Problems (subscribe to the "leap" exercises in Ruby or the "bob" exercises in JavaScript, etc)
* Welcome (be notified whenever someone who is completely new to exercism submits their very first exercise, provided that it is in one of the languages that you've listed)

**Subscriptions API**

This would have GET/POST/PATCH/DELETE endpoints that the front-end would make requests to in order to update and display the user's subscriptions. I'd like this to be completely stand-alone, since that will make it much easier to contribute to (and once we know how it needs to work we can implement it in any language that makes sense depending on the requirements).

**Migrations**

Based on the existing users, conversations, problems, etc, we would need to set some sort of default subscriptions as a starting point. Probably something like:
* For people who are mentors on a track, subscribe to all the problems in that track.
* Subscribe to all the problems that you've submitted solutions to
* Subscribe to all the problems on teams that you're a member of
* Subscribe to all the exercises where you've participated in the conversation
* Subscribe to the "welcome" queue for each language that you've provided nitpicks on

**Enqueuing submissions/comments**

Every time a new submission or comment gets posted, we need to enqueue it so that it can get processed into all the relevant activity streams.

**Processing Queue**

For each new event, we need to figure out who is subscribed to the event and stick the event on their activity stream.

**Comment by pminten** [comment]
This may be somewhat unrelated but "activity streams" make me think of the [activity streams](http://activitystrea.ms/) standards.

Pie-in-the-sky: a twitter-like client where exercism notifications would come in along with other kinds of posts (like the latest cat picture).

More to the point, it would be nice if the activity streams of exercism would be defined in such a way that it would be possible to make standard activity streams out of them. My gut feeling is that this shouldn't require any real changes.

**Comment by kytrinyx** [comment]
I didn't realize that there's a standard. We should definitely adhere to that.

**Comment by pminten** [comment]
It's a kind of standard-in-progress. I don't think there are many clients yet but the W3C social WG is actively working on this.

**Comment by kytrinyx** [comment]
I've created a repository for the JSON API. For the first implementation, it will also include the job queue and workers to process the queue to fan out entries into people's streams:

https://github.com/exercism/rivulet/issues

I've broken the issues into milestones. I have some initial setup to do before the work can progress in earnest.

**Comment by NobbZ** [comment]
> and endless scroll.

Please don't, or at least provide a paginated alternative, I'm often using my mobile when nitpicking and looking for the messages. Endless scrolling is feeling very bad on mobiles.

**Comment by kytrinyx** [comment]
OK, yeah. Good point.

**Comment by chezwicker** [comment]
Not sure how current this issue is, I hope this is the right place to add the following.

It would be good to be able to subscribe to **any** movement on a track, but particularly to a user submitting a solution on a track that is new to them. Particularly with new / rare languages, it's a shame to miss a new user's submission. Something like github's subscription feature would be great, giving a user the possibility to get notified by email as well as in an activity stream on their dashboard.

**Comment by kytrinyx** [comment]
> a user submitting a solution on a track that is new to them.

Yes, this would be fantastic.

**Comment by kytrinyx** [comment]
I've implemented the basic activity stream both for the tracks and for teams.
