### ISSUE TITLE
python bob_test.py umlauts shouting/calmly both end with exclamation mark

### ISSUE THREAD

**Issue by jsr6720** [exercism/exercism.io#1915]
def test_shouting_with_umlauts(self):
        self.assertEqual(
            'Woah, chill out!', bob.hey('ÜMLÄÜTS!')
        )

```
def test_calmly_speaking_with_umlauts(self):
    self.assertEqual(
        'Whatever.', bob.hey('ÜMLäÜTS!')
    )
```

When running python test on this I see exclamation mark as shouting. Is the lower case "a" supposed to delineate shouting vs not shouting?

**Comment by jdar** [comment]
Potential Solution:

@jsr6720 Will you re-consider, if I add a pull request in the readme explaining that "Bob will react with indifference to shouting a single word that is not in all caps, since that is just nonsense. All-caps on the other hand, would indicate a higher degree of urgency and elicits a different response."

I think this is a good solution, since it otherwise people are going to be 'nitpicking' other people's interpretations of the problem, rather than the deep thought that goes into the implementation of a solution.

**Comment by jsr6720** [comment]
Since now one else seemed to have a preference please do as you feel is best.

**Comment by kytrinyx** [comment]
One of the reasons the Bob problem is interesting is that it has some ambiguity. The spec itself just says "shouting", but the tests have made decisions beyond that ("e.g. it's only shouting if the entire word is all caps, and only if there are actual letters").

I think that it might be worth adding something to the README about ambiguity / human language / consider the test cases as being the requirements. https://github.com/exercism/x-common/blob/master/bob.md

The test cases have evolved over time as people saw solutions that had made decisions about things and the test cases didn't cover them. There have been really interesting discussions that have come out of these questions of ambiguity.

**Comment by jdar** [comment]
I think this would be an appropriate lesson a few exercises later... not
the first exercise!

I'm pretty test-oriented, but a noob to python. Not knowing about a special
method that checks uppercase-ness, I spent way too long spinning wheels. My
experience would have been more enjoyable if I had gotten a straight-up
hint on this one. :) I was trying to roll my own unicode regex until I
clued in.

Regards,

Darius

{name    : "Darius Roberts",
 mobile   : "202.630.5327",
 email     : "darius.roberts@gmail.com",
 media    : ["@jdar <https://plus.google.com/u/0/112900549848917795112>","
linkedin <http://www.linkedin.com/profile/view?id=3452355>"] }

**Comment by kytrinyx** [comment]
Yeah, in other languages we've moved bob to a later exercise. I think both "leap" and "hamming" are simpler. @sjakobi what do you think? Should we move 'bob' a bit farther down?

**Comment by Dog** [comment]
I think it'd make sense to put bob a bit farther into the track.

**Comment by Dog** [comment]
The bob exercise was moved back in https://github.com/exercism/xpython/pull/182
