### ISSUE TITLE
More friendly editor interface

### ISSUE THREAD

**Issue by wei2912** [exercism/exercism.io#1926]
The editor interface could be improved tremendously; here are a few of my suggestions to make it much easier to use.

1. Code and Nitpicks should be in two columns, both independent of each other, so that we can scroll through the code while remaining on the same Nitpick and vice versa.
2. Write should display the text in `monospace` so that we can easily align columns.
3. When editing a nitpick, use the same interface instead of going to a new page.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, since we'll be tackling UX more globally in the future. Thanks!
