### ISSUE TITLE
On-boarding readme.md in root of each language directory

### ISSUE THREAD

**Issue by ismaild** [exercism/exercism.io#1931]
Going through the issues here, there are quite a number of issues labeled 'support'.  see: #1908

Some of the reasons:
* New users having issues getting started with their language of choice
* Not having the tooling setup for running tests 
* Not understanding the process.

There is currently a help at: http://help.exercism.io/ which has on-boarding help per a language.

However, the primary interaction (initially) is via CLI. For e.g i did not even bother looking at the help. 

The suggestion is:

When doing the first ```exercism fetch``` a readme.md is included in the root of the directory, which could be the same content from the help section, and also includes FAQ (per a language) to reduce the issues logged on github. 

This way, the on-boarding information is available locally without having to visit the site.

**Comment by kytrinyx** [comment]
UPDATE: Let's use the language-specific documentation to create this README. See https://github.com/exercism/x-common/issues/69

**Comment by Insti** [comment]
#2324 is general and not specific to this issue.

https://github.com/exercism/x-common/issues/69 is closed.
https://github.com/exercism/x-api/issues/31 has a cyclic dependency on this issue.

I suggest we close https://github.com/exercism/x-api/issues/31 and this issue.

**Comment by Insti** [comment]
This issue is now being handled by: https://github.com/exercism/x-api/issues/31
