### ISSUE TITLE
Is there a way to bind the submissions to the Github profile of user?

### ISSUE THREAD

**Issue by AlexVPopov** [exercism/exercism.io#1934]
Is there any sort of GitHub integration. Something along the lines that `exercism fetch` does something like `git pull upstream master` and `exercism s` does something like `git push origin master`? Or perhaps the only thing I can do currently is initiate the exercism folder as a git repo and then push it to GitHub?

**Comment by kytrinyx** [comment]
I've not made progress on this, and don't see how to approach it without a huge restructuring of how Exercism works. I'm going to go ahead and close this.
