### ISSUE TITLE
Things to keep in mind

### ISSUE THREAD

**Issue by constcrist** [exercism/exercism.io#1946]
complexity of the code does not mean anything any longer?

currently, the following "things" are listed:

What do you like about the code?
How does the code make use of C++?
Does the code make appropriate use of Object-Oriented or Functional principles?
How readable is the code? How well does it tell its story?
What software design patterns or principles (could) inform the code?

otoh, any serious job interview requires a time/memory complexity analysis of some code/algorithm.

why not adding a new bullet:

Is the implementation performing optimal in time? How about memory used by the code?

**Comment by kytrinyx** [comment]
We've changed the user interface of the page, so these things are no longer showing.
