### ISSUE TITLE
Idea: "Labelvoting"

### ISSUE THREAD

**Issue by MadcapJake** [exercism/exercism.io#1957]
### Idea

Think slashdot, you can assign a label to what you think of the nit:

Positive | Neutral | Negative
---------- | ---------- | ------------
Helpful  | Informative | Nonconstructive
Kind      | Respectful | Rude
Sharp   | Interesting | Dull

### Napkin

It could even be displayed on the dashboard with a bar for each row that shifts up or down (with zero in the middle) as you your nits get labeled.  The positive column could provide +2 and neutral +1 and negative -2. 

Or if the bar charts aren't in the cards, then at least a tally on the dashboard of how many nits labeled for each (maybe only displaying the negative ones if the number reaches a certain ratio compared to the positive or neutral categories).

### Thoughts

This, to me, would encourage more nits, give some power to the community to moderate itself, and provide resume building stats.  Also, using less labels than I have listed could be beneficial as per analysis paralysis.

**Comment by kytrinyx** [comment]
I've opened an issue to discuss various high-level approaches to improving the quantity/quality of feedback: https://github.com/exercism/discussions/issues/88 I'm closing this issue in favor of that discussion.
