### ISSUE TITLE
Runtime error: "ReferenceError: describe is not defined"

### ISSUE THREAD

**Issue by tomulcahy** [exercism/exercism.io#1959]
I am running the JavaScript version of Bob, using Eclipse.  I have set up node.js on my local machine, to run the script "native", rather than using html.  I have set up an external tool config in Eclipse to run the test script with node, via a dos cmd command.

This is the error I get:
C:\Users\USX25436\exercism\javascript\bob\bob_test.spec.js:3
describe("Bob", function() {
^
ReferenceError: describe is not defined
    at Object.<anonymous> (C:\Users\USX25436\exercism\javascript\bob\bob_test.spec.js:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

I have included Jasmine as a JavaScript resource in the Eclipse project, but it's like node.js doesn't know where to find the reference.

I probably have a case of crano-rectal syndrome going on here...

Ideas?

**Comment by merlihan** [comment]
Sorry to bring this one back to life, but I am having the same issue that @tomulcahy was having. 
I have installed jasmine with npm install -g jasmine-node on both my local machine (using webstorm) and on Cloud9 (following the instructions here: https://gist.github.com/jcdavison/eaa6756472552214ac16) with no avail. 

@tomulcahy, did you end up doing anything else to get debugging sorted?

Cheers

**Comment by merlihan** [comment]
Update - I installed karma and initialized it with jasmine. It's now running in the browser but I get this error:

Uncaught Error: Module name "bob.js" has not been loaded yet for context: _. Use require([])

Any ideas?

**Comment by unused** [comment]
Hi @merlihan - did you create a bob.js file in this directory and put a node module in there? You can find some help on creating this module in the [javascript help of exercism](http://help.exercism.io/getting-started-with-javascript.html).

I also tried to reproduce your problem in cloud9 but everything workes fine. I choose custom, install and setup exercism, fetch the problems, install jasmine-node and test the examples. If you need some details feel free to contact me.

**Comment by merlihan** [comment]
Hi @unused - Thanks for the reply! And thanks for trying to reproduce my issue!
I am up and running! Wahoo! Just wondering at this point, if I wanted to debug the code (set breakpoints and watch values) before (or concurrently) with the jasmine tests, do i need to install anything else? Currently if I run the code in debug mode, it stops on line 2 of bob_test.spec.js stating that describe is not defined.

Please see screenshots for reference:

Running Jasmine tests (working)
![image](https://cloud.githubusercontent.com/assets/4990374/7474766/6314a94e-f311-11e4-87aa-786843f9a258.png)

Debugging (Describe is not defined)
![image](https://cloud.githubusercontent.com/assets/4990374/7475129/b90f9abe-f313-11e4-87ab-df44518f807f.png)

**Comment by unused** [comment]
That's because you execute the test script with a Node.js runner instead of executing jasmine-node. You may create a new runner (on the default template just replace ls command with jasmin-node), but I'd recommend you to switch to CLI. An IDE may be convenient in some ways but as you have seen, exercism comes with so many different languages that one can explore. (Compiling and) Executing them right from the shell is a way you also get comfortable with all those different environments.

If you need any further help feel free to contact me. I'd suggest to stop cloud9 how to here and keep this issue closed ;)
