### ISSUE TITLE
Problem on submit: exercism thinks the file is in a wrong place

### ISSUE THREAD

**Issue by rreimche** [exercism/exercism.io#1965]
a pair of days ago everything worked like a charm but yesterday I was not able to submit my solutions to exercism. I've read troubleshooting on exercism and then reinstalled the client. However that didn't help:

Roman-Reimche-3:exercism rreimche$ exercism -v
exercism version 1.7.5
Roman-Reimche-3:exercism rreimche$ exercism submit ruby/hamming/hamming.ext 
2014/10/10 22:10:17 Cannot submit - unable to identify track and problem.

Please leave the solution within the problem directory that was created by 'exercism fetch'
Roman-Reimche-3:exercism rreimche$ exercism submit haskell/sublist/sublist.ext
2014/10/10 22:12:38 Cannot submit - unable to identify track and problem.

Please leave the solution within the problem directory that was created by 'exercism fetch'
Roman-Reimche-3:exercism rreimche$ cat ../.exercism.json 
{"apiKey":"myKeYmyKeYmyKeYmyKeYmyKeY","exercismDirectory":"/Users/rreimche/exercism","hostname":"http://exercism.io"}

(I'm on Mac OS X Mountain Lion and the files are in the folders that were created automatically during fetch)

**Comment by compwron** [comment]
I think that I am having this problem. I have tried regenerating my .exercism.json using the exercism configure command, but the problem remains the same. 

```
compwron:~/repositories/exercism/ruby/space-age$ exercism s space_age.rb
2015/03/09 11:17:15 Cannot submit - unable to identify track and problem.

Please leave the solution within the problem directory that was created by 'exercism fetch'
compwron:~/repositories/exercism/ruby/space-age$ exercism debug

**** Debug Information ****
Exercism CLI Version: 2.0.0
OS/Architecture: darwin/amd64
Home Dir: /Users/compwron
Config file: /Users/compwron/.exercism.json
API Key: <secret>
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/compwron/exercism

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).
compwron:~/repositories/exercism/ruby/space-age$ pwd
/Users/compwron/repositories/exercism/ruby/space-age
compwron:~/repositories/exercism/ruby/space-age$ cat ~/.exercism.json 
{"apiKey":"<secret>","exercismDirectory":"/Users/compwron/repositories/exercism/","hostname":"http://exercism.io"}
compwron:~/repositories/exercism/ruby/space-age$ 
```

**Comment by kytrinyx** [comment]
You have your problems at `~/repositories/exercism`, but the configuration says that it's at `/Users/compwron/repositories/exercism/`

What happens if you say `exercism configure --dir=~/repositories/exercism`?

**Comment by compwron** [comment]
It fixed it! I thought that those were equivalent, whoops. Thanks for the help :)

**Comment by kytrinyx** [comment]
It seems like they should be. So strange!

**Comment by steffencrespo** [comment]
I just had this problem and figured that the problem was because I was trying to submit the /hello-world folder instead of the hello-world.js file.
That said, the error message is misleading. It took me some time to realize what I was doing wrong, but that was because I was pretty sure that my directory was right and the configs were also fine.

```
Unable to submit - Bad path to exercise file.

You're trying to submit a solution file from inside your exercises directory,
but **it looks like the directory structure is something that exercism doesn't
recognize as a valid file path**.
First, make a copy of your solution file and save it outside of
<dir>

Then, run "exercism fetch". Move your solution file back to the correct
exercise directory for the problem you're working on. It should be somewhere
inside /Users/lsteffen/Dev/personal/exercism
```

Maybe before the 'First' try adding a question asking if the person is trying to submit the whole folder instead of only the file - that would have saved me a few minutes :)

**Comment by kytrinyx** [comment]
@steffencrespo we just merged a fix for this four days ago: https://github.com/exercism/cli/pull/302

I'll release a new version of the CLI this weekend. Sorry we didn't get it fixed in time to save you those minutes!

**Comment by mhelmetag** [comment]
I think the newest version of the exercism-cli will prevent checking in whole folders/directories because of this fix https://github.com/exercism/cli/pull/302

**Comment by symplutz** [comment]
E:\exercism>exercism submit HelloWorld.java
2017/06/11 02:21:54 unable to submit - Bad path to exercise file.

You're trying to submit a solution file from inside your exercises directory,
but it looks like the directory structure is something that exercism doesn't
recognize as a valid file path.

First, make a copy of your solution file and save it outside of
E:\exercism

Then, run "exercism fetch". Move your solution file back to the correct
exercise directory for the problem you're working on. It should be somewhere
inside E:\exercism

If you are having trouble, you can file a GitHub issue at (https://github.com/exercism/exercism.io/issues)

// My file is there and is called HelloWorld and have de .java extension
and this is my exercism debug 
E:\exercism>exercism debug

**** Debug Information ****
Exercism CLI Version: 2.4.0
Exercism CLI Latest Release: 2.4.0
OS/Architecture: windows/amd64
Build OS/Architecture windows/amd64
Home Dir: C:\Users\Iulian
Config File: C:\Users\Iulian\.exercism.json
API Key: cd35*************************94f
Exercises Directory: E:\exercism
Testing API endpoints reachability
        * GitHub API: https://api.github.com/ [connected] 145.5317ms
        * XAPI: http://x.exercism.io [connected] 313.9905ms
        * API: http://exercism.io [connected] 387.1048ms

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).

**Comment by kytrinyx** [comment]
@symplutz If you say `exercism fetch java hello-world`, then the exercise should end up in `E:\Exercism\java\hello-world`, and your solution should be somewhere inside of that hello-world directory.

**Comment by symplutz** [comment]
i did submit from created folder. Thank you!

**Comment by kytrinyx** [comment]
> E:\exercism>exercism submit HelloWorld.java
> 2017/06/11 02:21:54 unable to submit - Bad path to exercise file.

It doesn't look like it. From this it looks like `HelloWorld.java` is directly inside of E:\exercism

If you change directory into E:\exercism\java\hello-world and submit the full path\to\HelloWorld.java this should work.

**Comment by kytrinyx** [comment]
If you want help in realtime, @symplutz, feel free to jump into the chat: https://gitter.im/exercism/support

There are often people hanging out there.
