### ISSUE TITLE
Proposal: Install jasmine-node Locally

### ISSUE THREAD

**Issue by Havvy** [exercism/exercism.io#1976]
Currently, testing JavaScript involves globally installing the jasmine-node executable. This is bad, because globally installing usually requires root, and if other projects need an incompatible version of jasmine-node, you can't use this. It also requires adding another step before getting to the exercises, which 

So, instead of requesting that we install yet another program globally, why not install the package locally to `%exercism%/javascript/jasmine` and then in each problem, add a package.json that has has the following scripts property:

````javascript
"scripts": {
    "test": "../jasmine/bin/jasmine test.js"
}
````

You could also set the author of the test and some other metadata if you'd like.

You should also set `"private": true` to make sure people don't publish their solutions to npmjs.org.

Then, to actually test the code, the user would just have to do `npm test` in the test directory, and wouldn't need to install jasmine-node globally.

If you're fetch system doesn't handle fetching tooling directories, you could also put jasmine-node in the node_modules directory, and change the script to "jasmine test.js". Make sure you install jasmine normally though, since the executable gets a symlink put into `/node_modules/.bin/` which is added to the path for any npm scripts. The drawback here though, is downloading jasmine for every test...

If you accept this proposal, and tell me which way you are going to install jasmine-node, I can pass you a PR that adds the package.json files to each test.

**Comment by Havvy** [comment]
It's been three months, so I'm just checking up - any progress on the vendored stuff?

**Comment by kytrinyx** [comment]
I got completely side-tracked, and then it fell off my radar.

In terms of JavaScript, what would be the best way to serve up the dependencies? Download a zipped archive and unzip it into the root of the javascript problems directory? Or a subdirectory?

**Comment by Havvy** [comment]
(Assuming you are sticking with Jasmine, not Mocha or Tape; switch command names around as appropriate if false assumption)

If you don't mind being a little non-standard, `./exercism/javascript/node_modules/jasmine-node`  (via `npm install jasmine-node` in `./exercism/javascript/` and then have the `package.json`s for each project have in their `"scripts"` property `"test": "../node_modules/.bin/jasmine test.js"`.

Note: When installing a package with binary parts, the executables are symlinked into `./node_modules/.bin/`.

As an optimization, you can totally just zip up `./node_modules` after you've installed it the first time on a dev machine.

The "proper" way to install would be to have `"jasmine-node"` in the `"devDependencies"` of each project, and the `"test"` script would just be `"jasmine test.js"`, but that involves installing jasmine-node once per project instead of just once, and I personally feel like eschewing that would be okay for this.

Note though, that the user would still need to have Node.js (or IO.js now...) installed (which brings in `npm`) and they'd just have to type `npm test` to test their code once everything is set up properly.

**Comment by kytrinyx** [comment]
> but that involves installing jasmine-node once per project instead of just once, and I personally feel like eschewing that would be okay for this.

Yeah, that seems overkill.

> Note though, that the user would still need to have Node.js (or IO.js now...) installed

So how would this be better than what we currently have? Don't they have to `npm install` node and jasmine-node?

**Comment by Havvy** [comment]
They'd be more likely to `sudo npm install -g jasmine-node`. Node.js and npm come bundled together in most (all?) distributions, so they wouldn't need to learn how to use `npm install` AND `jasmine test.js` nor be installing global stuff outside their package manager. They'd just need to do `npm test` which is easier to teach than the installation + new global command thing that currently happens.

**Comment by kytrinyx** [comment]
Sorry, I think I'm a bit slow. Would you mind typing out the list of commands before/after?

**Comment by Havvy** [comment]
Before:

```
nix-env -i node.js # Assuming Nix package manager, replace with yum, apt-get, building from source, ect.
sudo npm install -g jasmine-node
# Exercism stuff, cd into javascript/bob
jasmine test.js
```

after

```
nix-env -i node.js
# Exercism stuff, cd into javascript/bob
npm test
```

**Comment by kytrinyx** [comment]
Ah! Yes, this would be better.

Cool, thanks for patiently helping me understanding this.

**Comment by kytrinyx** [comment]
We never made progress on this, unfortunately, though we've been working on other things to try to improve the frontend workflow. I'm going to close this in favor of the overhaul we're investigating here: https://github.com/exercism/exercism.io/issues/3166
