### ISSUE TITLE
palindrome exercise description is vague and test suites are confusing

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#1979]
The problem description [palindrome-products.md](https://github.com/exercism/x-common/blob/master/palindrome-products.md) and [palindrome-products.yml](https://github.com/exercism/x-common/blob/master/palindrome-products.yml) is amazingly terse for what is actually being required by the typical test suite (see [javascript](https://github.com/exercism/xjavascript/blob/master/palindrome-products/palindrome-products_test.spec.js)).

The [original cited problem](https://projecteuler.net/problem=4) inspiring this exercise is quite clear:

 > A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
>
> Find the largest palindrome made from the product of two 3-digit numbers.

Yet somehow that mutated into the javascript exercise requiring passing this sort of test:

```javascript
it("largest palindrome from single digit factors", function() {
    var palindromes = new Palindromes({maxFactor: 9});
    palindromes.generate();

    var largest = palindromes.largest();
    expect(largest.value).toEqual(9);
    expect([[[3, 3], [1, 9]], [[1, 9], [3, 3]]]).toContain(largest.factors);
});
```

I look at that last expectation and I'm truly baffled.  There is nothing mentioned anywhere in the original problem statement about what this array of arrays of arrays is supposed to mean.  From the problem description, the largest palindrome between 1 and 9 is obviously 9.  I can also see quite clearly that 9 has two sets of factors from single digit numbers: [3, 3] and [1, 9].

What is totally confusing is why these factors appear twice as arrays where the order is different and why this needs to be a 3-deep nesting of arrays at all.  The test suite doesn't have enough tests to make it obvious via [tests as documentation](http://xunitpatterns.com/Goals%20of%20Test%20Automation.html#Tests as Documentation) why there needs to be three levels of nesting and why the factors need to be repeated twice in different order.  Similarly, the example solution is pretty confusing and this triply-nested structure and repetition of factors seems merely to be an artifact of the example solution and not something intrinsic to the problem.

I tried looking at some other languages that had solutions and they also seem to suffer from this artifact without illuminating why this is a necessary element to the problem.  This makes me think that one language's solution was used as the inspiration for the solution in other languages.

**Comment by kytrinyx** [comment]
This is being discussed in the x-common repository: https://github.com/exercism/x-common/issues/208

I'm going to close this issue in favor of the other one.
