### ISSUE TITLE
Allergies - Not sure what this test is for - test_ignore_non_allergen_score_parts

### ISSUE THREAD

**Issue by muthazhagu** [exercism/exercism.io#1984]
In the allergies_test.py file, there is a test - 
```
def test_ignore_non_allergen_score_parts(self):
        self.assertEqual(['eggs'], Allergies(257).list)
```

This test is failing saying - 
```
Traceback (most recent call last):
  File "allergies_test.py", line 36, in test_ignore_non_allergen_score_parts
    self.assertEqual(['eggs'], Allergies(257).list)
AssertionError: Lists differ: ['eggs'] != ['eggs', 'peanuts', 'shellfish...
```

I understand the assertion itself, but not why the code is expecting only ```['eggs']```.
I am thinking that with an allergy score of 257, all allergens must be listed, and not just ```['eggs']```.

What am I missing?

Thank you, and very much appreciate your time!

Muthu

**Comment by kytrinyx** [comment]
Closing, since this has been inactive for a few months. If you are still having trouble, please reopen the issue with more information.
