### ISSUE TITLE
How do I actually start once I follow the installs (want to learn javascript on windows)?

### ISSUE THREAD

**Issue by stegemang** [exercism/exercism.io#1986]
I am on windows, I have installed exercism to the command line interface, I have installed and used chocolatey to install node.js. I want to learn Javascript but I do not understand the next step.

The Javascript help page (http://help.exercism.io/getting-started-with-javascript.html) does not give much help other than telling me to install node.js. What is the next step? How do I get and do an exercise? What do I do with bob.js or bob_test.js? "...not recognized as an internal or external command, operable program or batch file"

Part of the problem might be that I have no idea what any of this should look like, am I writing code in the command prompt? What is exercism? Am I just going to use notepad++ in the end? I guess I am expecting interactive coding exercises similar to codeacademy, is exercism even for beginners?

Which language is most supported at this point? Should I switch to python (I couldn't choose between 2 vs 3 and gave up)?

**Comment by kytrinyx** [comment]
Closing, as it seems like this is resolved. If you are still having trouble, please reopen the issue with more information.
