### ISSUE TITLE
Improve tests in Clojure Robot name exercise

### ISSUE THREAD

**Issue by pdej** [exercism/exercism.io#1994]
Seems like these tests could be improved. The execution of `(robot-name/reset-name robbie)` is done before any tests are run, which would make all tests pass by simply hard coding a name when initializing a new robot, and hard coding another one for reset. 

A better way would be to create a robot, save the original name, reset it and then test against a new robot or the original name, all in the same test. Instead of having a global definition of the robots. Or have I misunderstood the tests?

**Comment by kytrinyx** [comment]
Moved to the Clojure track repo.
