### ISSUE TITLE
Closing over very old and "Awesome" Submission

### ISSUE THREAD

**Issue by thebillywayne** [exercism/exercism.io#1998]
As a nitpicker, I'm often asked to nitpick on submission that are fairly old (on the order of months). Many of these have been marked 'awesome'. Could these older submissions with more than two "awesome's" be closed so that nitpickers can see relatively newer submissions?

**Comment by mtakac** [comment]
I find closing a submission without user inducing the action strange. IMO the better way to go would be to order the submissions which are presented for nitpicking, so that older and and 'awesome' submissions would move to the bottom of the list.

**Comment by kytrinyx** [comment]
It's not the same as closing it, it's a variant of hibernation, but you have a point.

What if we add a notification in the user's notification stream that it happened, and ask them to add a comment or a new iteration if they'd like to try for fresh feedback?

**Comment by mtakac** [comment]
That's better but still, I personally don't like the idea of the application manipulating user's data in this way without direct user's action. 

Another question is if we really want to stream notifications like this to users. Again, just my personal opinion, but I find it a little bit annoying: "We closed your submission, but you can re-open it" - I just don't really see any added value in this. Especially if we can solve the problem simply by reordering the list of submissions presented to users for nitpicking. But maybe I am missing something else here...

**Comment by kytrinyx** [comment]
I'm in the process of getting rid of the whole pending list and turning it into an activity stream (#1899) which will remove this whole problem. I just don't quite know what to do in the meantime (it's going to take a little while to get this done).

Sorting things lower is definitely a better choice, but the pending list is already incredibly awful in terms of complexity and performance and I'm a little bit worried about touching it at the moment.

**Comment by mtakac** [comment]
Actually now when I look at the pending list I am not really sure where is the problem. The submissions are by default sorted by submission date, the recent ones are on top. May be that filters could behave more user friendly and submissions without any nitpick could be moved to the top of the list (this should be quick & easy to implement), but otherwise it's OK. Could it be that this issue is outdated and no longer relevant?

**Comment by kytrinyx** [comment]
That's a possibility!

Filters would be awesome. I'll close this one, since it seems like it's probably outdated.
