### ISSUE TITLE
Under current model, "nits" are far more likely to come from beginners than from experts

### ISSUE THREAD

**Issue by kynnjo** [exercism/exercism.io#2016]
It would be nice if there were a way for those with expertise in a language (let me call them "experts" here) to comment on the code written by learners without having to submit answers to the exercises themselves.

(Unless I'm mistaken, this is not possible, or at least not easy to do, within the exercism.io's current rules.)

I, for example, have a lot of experience with a few of the languages that exercism.io supports, and would love to comment on the code of those who are learning those languages, but not so much that I'd want to do the corresponding exercises in those languages.

Conversely, given the choice of having beginners (i.e. my co-learners) and experts commenting on my code, I'd much prefer the latter, but this seems extremely unlikely at the moment.  (This is not to say that comments from other learners would be of no value at all; it's just that, as a rule, comments from experts give my learning a much bigger boost.)

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/exercism.io/issues/2711

**Comment by kytrinyx** [comment]
I've opened a high-level issue to discuss how to generally improve the quantity and quality of feedback: https://github.com/exercism/discussions/issues/88
