### ISSUE TITLE
Allow skipping ahead in language tracks

### ISSUE THREAD

**Issue by amalloy** [exercism/exercism.io#2023]
In [#2016](https://github.com/exercism/exercism.io/issues/2016#issuecomment-62330081), I suggested that one way to get more nitpicking from experts (rather than mostly from other people learning the language) would be to allow skipping ahead in the track for a language you're already an expert in: once you've solved some late problems, you'd be allowed to comment on the early ones you skipped. For example, as a Clojure expert myself, I am not interested in tediously going through the beginning exercises, but I would be happy to try some hard ones, and to provide feedback for newcomers on the easy problems.

**Comment by kytrinyx** [comment]
This has been implemented.

**Comment by rubberduck203** [comment]
> This has been implemented.

Cool.

... but how do you actually skip an exercise?
This and #1949 are the top google hits for `exercism skip exercise`.

**Comment by amitiuttarwar** [comment]
@rubberduck203 - `exercism skip [track ID] [problem slug]`
track ID is the name of the language 
problem slug is the name of the challenge 
eg. `exercism skip ruby hamming`

**Comment by devth** [comment]
Looks like this is no longer an available command :(

**Comment by SleeplessByte** [comment]
@devth that's because progression is no longer blocked. You can switch between learning mode and free to pick whatever you want at will.

Please note that this issue is over 8 years old. If you are running into an issue, open a post on [the forum](https://forum.exercism.org/).
