### ISSUE TITLE
Invitation to those not registered yet.

### ISSUE THREAD

**Issue by kotp** [exercism/exercism.io#2027]
I keep trying to invite students to the site, specifically to a team.

They have a valid github.com id, which I submit to the invitation for the team.

But it does not show an invitation until they finally sign up.  This is almost OK, as it tells me they haven't signed up yet.  But it is not good in that there is no listing that says they were invited but do not have an account.

It appears that invitations to a team require a registration on the site first.

**Comment by purezen** [comment]
So, how are we going to deal with it? 
In case the invited github id is not registered on exercism, we will be sending them a mail (in case they have a publicly accessible mail id) and also provide the ability to invite users via email?

**Comment by kytrinyx** [comment]
I think I'd like to make it one or the other, and email would be more valuable, since not everyone has a GitHub account.

We could provide a sign-up link that includes a token so that we can connect their github user to the invitation once they've finished signing up. It would require some design work to make the process painless and to clarify what is happening / will happen next.

**Comment by kytrinyx** [comment]
I think this got fixed. @kotp would you have a moment to verify?

**Comment by kotp** [comment]
The wording may be awkward on invite... "Invitation sent to team YourTeamNameHere" where "YourTeamNameHere" is simply a placeholder, it does show the actual team name.  I would probably expect the invitation to be sent to the folks invited.

But yes, it seems to be working.

Would love to send to be able to invite via e-mail address though, as well, and get people started using github as an option <a href="" title="DVCS/SCM">Distributed Version Control/Software Control Management</a>.  New programmers as an audience are often not to have this in their tool box.

**Comment by kytrinyx** [comment]
We don't have any email capabilities at the moment, but I agree that we should eventually get that sorted out so we can invite via email (and send people other updates via email).

**Comment by kotp** [comment]
The alternative might be to create a link that we can share, rather than relying on the "e-mail system" (whether it exists or not).  This link could direct them to the login page, where they would then login using github (that is a requirement) and I think it does most of the right things for them.  Perhaps a "pre wormhole" page to describe what will happen before they get thrown to Github.  This is a topic for another issue though... and may help to delay any thoughts of an e-mail requirement or urgency.

**Comment by kytrinyx** [comment]
@kotp Yeah, those are great ideas. I think a pre-wormhole thing would help a lot.
