### ISSUE TITLE
I responded to an exercise in hibernation but it still indicates that it is in hibernation.

### ISSUE THREAD

**Issue by veswill3** [exercism/exercism.io#2030]
I have an exercise that was in hibernation. At the top it says 
> This exercise is hibernating. To take the submission back out of hibernation either respond to the nitpicks, or submit a new version.

I responded and it appears to have become discoverable to others, but that message is still showing at the top.

The exercise in question as an example: http://exercism.io/submissions/6de7b8b0e75dbd78076d5f75

**Comment by kytrinyx** [comment]
I believe this was fixed in https://github.com/exercism/exercism.io/pull/2230
