### ISSUE TITLE
current exercises should maybe have a scroll bar

### ISSUE THREAD

**Issue by dalexj** [exercism/exercism.io#2032]
I've done too many exercises and now I can't see all my exercises when I click on "current exercises" at the top
![screen shot 2014-11-13 at 12 30 16 pm](https://cloud.githubusercontent.com/assets/2790993/5034999/e9b2f5dc-6b30-11e4-9624-fee0c9092dd5.png)

**Comment by alexclarkofficial** [comment]
I'd love to help on this, just want to confirm before I dig in. Is the idea to put them in the dashboard above 'History'? With a link like 'History' or just inline?

**Comment by kytrinyx** [comment]
I think we should have them inline on the dashboard. I don't know where on the dashboard (if you have any ideas, go for it!)
