### ISSUE TITLE
Add Language: PHP

### ISSUE THREAD

**Issue by ksolo** [exercism/exercism.io#2036]
I'm teaching one of my friends how to code, and he works with a lot of php developers and would like to learn this in hopes of transferring to the dev team. 

I've started a repo following the x<language> pattern (https://github.com/ksolo/xphp). Can you create a exercism/xphp repo for pull requests?

**Comment by Dog** [comment]
I've gone through half of them. I read through the source code for all of them though.

This is what I thought of the exercises I had not finished personally.

Probably need function conversion:
* Wordy
* Trinary
* Roman-Numerals

Seem okay at a glance:
* Bowling
* Clock
* Robot-Name

**Comment by kytrinyx** [comment]
That sounds about right. We've done the function conversion in a couple languages for those exercises, if I recall correctly.

**Comment by arcdigital** [comment]
I'm happy to be a "nitpicker" for PHP as well.

**Comment by kytrinyx** [comment]
Sweet, thanks!

**Comment by segmentationfaulter** [comment]
so any developments regarding the launch of PHP? Thanks

**Comment by kytrinyx** [comment]
Someone who does PHP development would need to write the "getting started" page for PHP, and ideally we would convert the three problems @Dog mentioned so that they're pure functions.

Here's the launch checklist:
https://github.com/exercism/xphp/issues/41

**Comment by kytrinyx** [comment]
The PHP track has gone live :sparkles:
