### ISSUE TITLE
[idea] Live markdown preview for nitpick box

### ISSUE THREAD

**Issue by lccro** [exercism/exercism.io#2041]
Live preview of markdown in comments. Instant feedback - just like in tdd.
I find editing and switching tabs to have feedback unnecessary and time consuming.

**Comment by tejasbubane** [comment]
[Coderwall](https://coderwall.com/) has a beautiful markdown preview while writing protips. They use [marked](https://github.com/chjj/marked) as seen [here](https://github.com/assemblymade/coderwall/blob/master/vendor/assets/javascripts/marked.js#L4). Also see [benchmarks in the readme](https://github.com/chjj/marked#benchmarks).

**Comment by kytrinyx** [comment]
Since this has not received any more comments in the past two years, I'm going to go ahead and close it.

If this feels very important, then please reopen the issue.
