### ISSUE TITLE
Add ability to respond to nitpicks via email

### ISSUE THREAD

**Issue by killtheliterate** [exercism/exercism.io#2046]
It would be nice to be able to respond to nitpicks when they arrive as email. The story is that, in my usage of exercism thus far, I have wanted to shoot off quick responses to some nitpicks. It might even be nice to have the code in question appear in the email, though formatting would be pretty difficult.

**Comment by mtakac** [comment]
This should be actually pretty simple to implement. Heroku has even plugin for this: https://devcenter.heroku.com/articles/cloudmailin. Alternatively we could just use our own mail server and some ruby gem (there are plenty of them for this).

**Comment by kytrinyx** [comment]
We're going to do some work to get the basic UX right on Exercism. Once the basics are improved, I think we can consider things like this. In the meanwhile I'm going to close it.
