### ISSUE TITLE
Styling of comment box is sometimes broken

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2057]
![screen shot 2014-11-23 at 10 00 37](https://cloud.githubusercontent.com/assets/276834/5158620/5c5c9ec0-72f8-11e4-9404-6cf98d111a25.png)

I don't know what causes it, but occasionally the comment box is tiny and the nitpick button ends up next to it instead of underneath it.

**Comment by KaoruDev** [comment]
@kytrinyx what's the url for this page?

**Comment by kytrinyx** [comment]
@KaoruDev I can't remember, but if I see it again I'll grab the URL as well as the exact comments and see if I can reproduce locally.

**Comment by kytrinyx** [comment]
Closing, cannot reproduce.
