### ISSUE TITLE
Add a comment/summary that is shared across all iterations of a solution.

### ISSUE THREAD

**Issue by EricGebhart** [exercism/exercism.io#2077]
It would be nice to have a single comment or summary that is shared across all iterations of a problem so that a general description can be given for all the iterations.

Given enough iterations it is common to have solutions that are related to each other, this would allow them to be more easily connected and discussed as a whole.

As an example my bob solutions has, so far, 3 distinct families of solutions.  Each family was not necessarily sequential in the iteration index.   Some solutions stand out for one reason or another. It would be nice to have a central place for this type of description to happen.

**Comment by kytrinyx** [comment]
I've moved this suggestion into the discussions repo: https://github.com/exercism/discussions/issues/89
