### ISSUE TITLE
favorite iterations indicator

### ISSUE THREAD

**Issue by EricGebhart** [exercism/exercism.io#2080]
It would be nice to be able to indicate which iterations were favorites of the author.  Maybe a little exercism symbol in the tab, a heart in flames...

**Comment by IanVS** [comment]
+1.  It would be great to have a way to favorite someone's solution so that I can go back and study it in depth later on.

**Comment by kytrinyx** [comment]
I'm going to close this in favor of the discussion opened here: https://github.com/exercism/discussions/issues/89

I think that a broader approach to this would make more sense (people could say something in their meta-commentary about which solution they like the best).
