### ISSUE TITLE
Save Submissions

### ISSUE THREAD

**Issue by Dog** [exercism/exercism.io#2084]
Sometimes I find I come across a submission I want to comment on, but for various reasons (I'm on my iPad, I'm at work, I don't have time) I can't leave a response right away. I find in these situations I'm prone to forget to leave any comment, or I at least leave a quick comment and will try to come back later.

I also sometimes leave a long response to a submission that would be relevant to another. Currently its very difficult to keep track of which submission have these types of comments so I can pull them up again later. If I could save submissions, I could save them to find again later.

I've tried to flag submissions myself with @Dog, but no notification is given since I view the page again immediately afterwards. I'd like a way to save submissions so I remember to come back to/find them later.

**Comment by kytrinyx** [comment]
Moving this to the discussions repo.
