### ISSUE TITLE
Describe the basic structure of the project in the CONTRIBUTING document

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2094]
See Issue #2092 for an overview of operation welcome contributors.

-----------------------

From the [OpenHatch guide](http://opensource-events.com/#project-setup):

> Describe the basic structure of your project. What are the biggest pieces and where are they located? How do those pieces interact? Then break each piece down.

I've done part of this, specifically focusing on the problems api (that delivers test suites, READMEs, etc in the various languages): https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

What's missing is the overall description of the entire exercism ecosystem, and the description of the exercism.io codebase.

**Comment by mhelmetag** [comment]
@kytrinyx , I could try to take a first crack at this... I've seen at least a little bit of exercism so far. Time to write some docs?

**Comment by kytrinyx** [comment]
That would be fantastic. Once you have a draft I would be able to say "ooh, yeah this gotcha and that thingy over there", whereas right now my brain is kind of blind to all the problems with it.

**Comment by kytrinyx** [comment]
Completed in #2774
