### ISSUE TITLE
Describe how to contribute changes

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2096]
See Issue #2092 for an overview of operation welcome contributors.

-----------------------

In the CONTRIBUTING.md document, we should note that use use pull requests for all parts of the project, but that security patches should be sent via email to kytrinyx@exercism.io.

Let's also talk about atomic commits, good commit messages, and how to squash commits and edit commit messages.

Often people will submit a pull request, and then when asked for changes, close the pull request and open a new one. Let's make it clear that all commits to the same branch will automatically go to the pull request, and that a `--force` push will also update the pull request.

We can link to existing guides and blog posts.

* good commit messages e.g. http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html, http://www.confreaks.com/videos/744-rockymtnruby2011-lightning-talk-do-your-commit-messages-suck (video)
* how to squash, e.g. http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request
* atomic commits, e.g. http://www.freshconsulting.com/atomic-commits/

OpenHatch also has an interesting concept of "training missions", where people can practice some of the behaviors related to contributing to open source. E.g. https://openhatch.org/missions/git

It would probably be useful to mention that we understand that git is intimidating, and we are happy to help guide, explain, and sometimes even pair on getting the pull request accepted.

**Comment by tejasbubane** [comment]
I would also like to see github-specific pages like https://help.github.com/articles/using-pull-requests/ and https://guides.github.com/introduction/flow/.
Maybe useful if someone is not familiar with github.

**Comment by kytrinyx** [comment]
Yeah, that's a good point. Also the GitHub documentation is really nice in general.

**Comment by kytrinyx** [comment]
We've rewritten the contributing guide, I'm going to go ahead and close this.
