### ISSUE TITLE
[synopsis] link each language header to the stats page for that language

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#2097]
I was thinking it would be nice to show how many submissions have been made for each problem in each language on the synopsis page.  The number would be a link that would take you to the submissions for that problem in that particular language.

First, I'm interested in hearing whether or not this is a dumb idea :smile_cat:.  If we think this is a good idea, then my next question is how can I obtain the data?  I believe that there is a URL for a page that lists all the submissions for a single problem in a particular language.

This could be done in two steps: first, show a number as plain text.  Second, make the number link to a page listing submissions.

**Comment by tejasbubane** [comment]
I did not know a stats page existed, can't see link anywhere in my UI.

**Comment by kytrinyx** [comment]
There's no link in the UI. They're not really designed, it was just put together quickly so that language maintainers could get an idea of what's going on. What we really want is to decide on some interesting stats and put them on the dashboard.

**Comment by sguermond** [comment]
@kytrinyx What is the order of the problems in the stats? Is it the order in which they are supposed to be done, a random order, or according to a stat?

**Comment by LegalizeAdulthood** [comment]
The problems are in the order you would solve them when proceeding through the language track.  At least that's what I infer from looking at the C++ stats.

**Comment by kytrinyx** [comment]
Yeah, I believe that they're ordered the way they'd be ordered when you fetch them.

**Comment by kytrinyx** [comment]
I really don't know what to do about the stats at the moment.

I'm going to close this. I think that if we're going to do anything about them at all we should open issues in the discussions repo (https://github.com/exercism/discussions/issues) and talk about what we're trying to achieve with the change.
