### ISSUE TITLE
Add ability to alter submissions and run against test suite in the browser

### ISSUE THREAD

**Issue by justinleveck** [exercism/exercism.io#2107]
This would allow nitpickers to go through more submissions in less time, thereby increasing the impact of the time volunteered by nitpickers.

As a nitpicker one could (without leaving the browser):
  - Run the submission against the test suite
  - Easily explore possible improvements to the code and immediately verify it still passes the test suite

**Comment by kytrinyx** [comment]
I've spent some time thinking about this, and it's partly a workflow thing--make it easier to nitpick, and partly about lowering the barrier to entry: make it easier to submit from the browser and run the tests.

I think that it could be very interesting and useful, but I simply don't have the resources to make it happen. Before I even start working on solving this, I need to make sure that the core problem of exercism is solved: The conversations need to be rich and useful, and everyone who submits code needs to get high quality feedback.

I've added this suggestion to the topic that discusses ways of lowering the barrier to entry, and once we've solved the core issues we can look at the various suggestions again.

Thanks for contributing!
