### ISSUE TITLE
Add GitHub users to team, even though they have never signed in

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#2124]
I have a whole bunch of github usernames that I tried to add to the team gdislc.

When I enter their usernames, either as a comma-separated list or individually, into the invite box and submit the form, no error message is displayed, but they aren't added to the team either.

**Comment by csgavino** [comment]
Hi @code-R , are you still working on this?

**Comment by code-R** [comment]
@csgavino you can pick this task, I havent done much work on this..

**Comment by csgavino** [comment]
@code-R alright I'll take a stab at it.

**Comment by csgavino** [comment]
@kytrinyx if I were to implement your simple solution we would end up with a ton of User records that only have usernames in it, is that something you want? Also, I would have to change from_github to handle username only Users but GitHub usernames are editable so that's another issue as well.

**Comment by kytrinyx** [comment]
I don't mind having user records with just usernames in them.

If someone edits their username on GitHub before they join, then they won't be attached to the team, but I think that's fine. They can be invited again.
