### ISSUE TITLE
Tried to run exercism but responds with command not found...

### ISSUE THREAD

**Issue by wcswanson** [exercism/exercism.io#2137]
![exercism](https://cloud.githubusercontent.com/assets/7052319/5551187/369cd660-8b8e-11e4-9668-2939b9250910.png)

Running Linux Mint 17 on 64 bit.

Looking forward to getting started. 

Thanks,
Bill

**Comment by Shreyanshnit19** [comment]
Try putting` export PATH=~/bin:$PATH` line to both .bashrc and .bash_profile files. 
Hope that helps anyone facing problem running exercism command !
