### ISSUE TITLE
Suggestion: allow to "follow" experts

### ISSUE THREAD

**Issue by fernandezpablo85** [exercism/exercism.io#2148]
Hi,

First of all thanks for creating this site, it's fantastic. I'd like to tell you about the way I use the application, which perhaps is "usual", but very effective.

After submitting an exercise, it's useful to get feedback. Obviously you can wait for Nipticks, but in my experience these are rare (with the exception of @etrepum in haskell, that guy is awesome). A different, more proactive way is to see how other users have solved the problem and learn from them (it's great that you CANT see the solution before submitting yours, kudos!).

I often check for who I consider the **"experts"** of a given language (again, @etrepum in haskell, for example) to see how they solved the problem. This is invaluable. To see how a more language-capable coder solves the same problem.

What I'd like is a way to encourage this. To be able to identify these "experts" and "follow" them somehow so when they solve a new problem, or niptick one, you get notified. That way they don't have to be nipticking many similar errors in different exercises, and proactive users can speed up their pace without waiting for a niptick.

Thanks again for the fantastic application.

**Comment by kytrinyx** [comment]
This is something that I've been thinking about a lot, and my next big push is to implement activity streams (https://github.com/exercism/exercism.io/issues/1899) which will allow following individuals.

**Comment by Dog** [comment]
This is a nice idea, especially since not all users get a response to their code. It can be difficult to find the excellent solutions in the sea of other users. How do you solve the discovery problem? How do you identify someone is an expert, then suggest that other people look at their solutions?

You also could run into an issue where established users are more likely to be classified as experts due to seniority, not knowledge.

It seems like it could work well with the activity streams, and may encourage people to leave more detailed explanations - knowing that people other than the one user who wrote the solution may read it.

**Comment by fernandezpablo85** [comment]
Identifying 'experts' would be cool, right know I'm just looking at the commit history of exercism `xLanguage` repositories on github, or start nipticking until I see a codestyle that I really like and then remember that user.

**Comment by carlisia** [comment]
We need to be careful in not discouraging people from nit-picking thinking that if they are not considered experts then their suggestion will be ignored, especially if someone considered an expert has commented on it. A major component of learning is in trying to teach.

Nevertheless, :+1:  for this.

**Comment by etrepum** [comment]
I like how there's no ranking for people, comments should be considered on their own merit.

**Comment by kytrinyx** [comment]
Yes, absolutely, there would be no visible ranking, only a way to be allowed to follow interesting people that you come acress. My thinking is that you would discover these people when they give you good feedback, or when you're giving someone else feedback and see other interesting comments.

**Comment by kytrinyx** [comment]
This feature "follow users" has been added to the list of features for the activity stream: https://github.com/exercism/rivulet/milestones/v1.0

I'm going to close this in favour of the new issues. Thanks for discussing it!
