### ISSUE TITLE
unable to submit (HTTP: 400) - unknown problem

### ISSUE THREAD

**Issue by morphatic** [exercism/exercism.io#2149]
Hello.  I LOVE exercism and I've been working on setting up a clone that I can populate with my own problem sets to use with my undergraduate introductory programming class.  I am NOT a ruby programmer but I know enough to be dangerous.  I've gotten everything set up on my server, except that I'm not able to submit an exercise successfully.  My clones are at:

* http://exercism.umatter2.us (after I get things working I'll rebrand to avoid confusion with the official site)
* http://x-api.umatter2.us

(NOTE: below where it says "mykey" I've replaced the actual key, which I confirmed to be correct.)

Here's the output of `exercism debug`:

```
**** Debug Information ****
Exercism CLI Version: 1.9.0
OS/Architecture: darwin/amd64
Home Dir: /Users/bentonmc
Config file: /Users/bentonmc/.exercism.json
API Key: mykey
API: http://exercism.umatter2.us
Exercises Directory: /Users/bentonmc/Documents/development/exercism
```

And here's the content of my actual `~/.exercsim.json` file (I prettified the formatting):

```
{
	"apiKey":"mykey",
	"dir":"/Users/bentonmc/Documents/development/exercism",
	"api":"http://exercism.umatter2.us",
	"xapi":"http://x-api.umatter2.us"
}
```

So far I've set up one language track (PHP) with a single problem: http://x-api.umatter2.us/problems/php/hello-world

I am able to `fetch` the exercise from terminal, and I wrote a solution and verified that it passes the included test.  The problem comes when I try to submit my code.  From the `/Users/bentonmc/Documents/development/exercism/php/hello-world/` directory if I run `exercism submit hello-world.php` I get the following output in the terminal:

```
Morgan-Bentons-Mac-Pro:hello-world bentonmc$ exercism submit hello-world.php 
2015/01/05 02:28:33 unable to submit (HTTP: 400) - unknown problem (track: php, slug: hello-world, path: /php/hello-world/hello-world.php)
```

I used [Wireshark](http://www.wireshark.org) to confirm that the HTTP request from the terminal was indeed going to my exercism clone.  The content of the HTTP request is as follows:

```
POST /api/v1/user/assignments HTTP/1.1..Host: exercism.umatter2.us..User-Agent: github.com/exercism/cli v1.9.0 (darwin/amd64)..Content-Length: 182..Content-Type: application/json..Accept-Encoding: gzip....{"key":"mykey","code":"\u003c?php\necho 'Hello, World!';","path":"/php/hello-world/hello-world.php","dir":"/Users/bentonmc/Documents/development/exercism"}
```

It's pretty clear from the output that the problem is [around here](https://github.com/exercism/exercism.io/blob/master/lib/api/routes/iterations.rb#L29) but I'm not sure what's causing it.

Any ideas?

Just for sanity's sake, I actually used the `bin/console` program on the server to recreate the steps and verify that it seems to be working on the server.  The output of that is below.  It appears to work, from the console, but still won't work when I submit my answer using the CLI.  Thank you for your help and all of the effort that has gone into creating this amazing tool!!!

```
[1] pry(main)> ENV.fetch('EXERCISES_API_URL') { "http://x.exercism.io" }
=> http://x-api.umatter2.us=> nil
[2] pry(main)> Xapi.exists?('php','hello-world')
I, [2015-01-04T22:51:47.531499 #28802]  INFO -- : get http://x-api.umatter2.us/problems/php/hello-world
D, [2015-01-04T22:51:47.531695 #28802] DEBUG -- request: User-Agent: "github.com/exercism/exercism.io"
I, [2015-01-04T22:51:47.635122 #28802]  INFO -- Status: 200
D, [2015-01-04T22:51:47.635268 #28802] DEBUG -- response: date: "Mon, 05 Jan 2015 06:51:47 GMT"
server: "Apache"
x-powered-by: "Phusion Passenger (mod_rails/mod_rack) 3.0.17"
x-content-type-options: "nosniff"
content-length: "1911"
status: "200"
connection: "close"
content-type: "application/json;charset=utf-8"
=> true
[3] pry(main)> solution = { '/php/hello-world/hello-world.php' => "\u003c?php\necho 'Hello, World!';" }
=> {"/php/hello-world/hello-world.php"=>"<?php\necho 'Hello, World!';"}
[4] pry(main)> i = Iteration.new(solution)
=> #<Iteration:0x000321b7cf8718 @solution={"/php/hello-world/hello-world.php"=>"<?php\necho 'Hello, World!';"}>
[5] pry(main)> i.track_id
=> "php"
[6] pry(main)> i.slug
=> "hello-world"
[7] pry(main)> i.paths
=> [#<Code:0x000321b7c6b160
  @path="/php/hello-world/hello-world.php",
  @path_segments=["php", "hello-world", "hello-world.php"]>]
[8] pry(main)> user = User.where( key: 'mykey' ).first
=> #<User id: 50, username: "morphatic", email: "morgan.benton@gmail.com", avatar_url: "https://avatars.githubusercontent.com/u/467980", github_id: 467980, key: "mykey", mastery: [], created_at: "2015-01-04 01:40:20", updated_at: "2015-01-04 01:40:20", onboarded_at: nil>
[9] pry(main)> att = Attempt.new( user, i )
=> #<Attempt:0x000321b4b04798
 @code="<?php\necho 'Hello, World!';",
 @filename="/php/hello-world/hello-world.php",
 @iteration=
  #<Iteration:0x000321b7cf8718
   @paths=
    [#<Code:0x000321b7c6b160
      @path="/php/hello-world/hello-world.php",
      @path_segments=["php", "hello-world", "hello-world.php"]>],
   @solution={"/php/hello-world/hello-world.php"=>"<?php\necho 'Hello, World!';"}>,
 @slug="hello-world",
 @track="php",
 @user=
  #<User id: 50, username: "morphatic", email: "morgan.benton@gmail.com", avatar_url: "https://avatars.githubusercontent.com/u/467980", github_id: 467980, key: "mykey", mastery: [], created_at: "2015-01-04 01:40:20", updated_at: "2015-01-04 01:40:20", onboarded_at: nil>>
[10] pry(main)> att.valid?
I, [2015-01-04T22:59:29.645557 #28802]  INFO -- : get http://x-api.umatter2.us/problems/php/hello-world
D, [2015-01-04T22:59:29.645704 #28802] DEBUG -- request: User-Agent: "github.com/exercism/exercism.io"
I, [2015-01-04T22:59:29.678409 #28802]  INFO -- Status: 200
D, [2015-01-04T22:59:29.678499 #28802] DEBUG -- response: date: "Mon, 05 Jan 2015 06:59:29 GMT"
server: "Apache"
x-powered-by: "Phusion Passenger (mod_rails/mod_rack) 3.0.17"
x-content-type-options: "nosniff"
content-length: "1911"
status: "200"
connection: "close"
content-type: "application/json;charset=utf-8"
=> true
```

**Comment by kytrinyx** [comment]
This is very, very strange! The error message you're getting means that `attempt.valid?` is returning false, but as your output proves, the same attempt from the console is listed as valid.

The only thing I can think of is that the `EXERCISES_API_URL` environment variable might be set in the environment where you are starting the console, but not the one where you're running the app. That would cause it to call `x.exercism.io` rather than `http://x-api.umatter2.us`.

I don't think the problem is on line 29 of the `iterations.rb` route. Currently the CLI submits the path and code, not the solution, so line 31 kicks in and everything is fine.

Could you add some logging to the running app to find the value of `ENV.fetch('EXERCISES_API_URL')`?

**Comment by morphatic** [comment]
Good call.  It appears that none of the variables in `.env` have been set.  I've submitted a pull request #2151 to fix this.

[It works now!](http://exercism.umatter2.us/submissions/dfee559e28f245c5978db945fe839154)

Like I said, I am NOT a ruby/sinatra developer, so I guess it's possible that if you're using `foreman` or the like that `.env` gets read automatically.  Or perhaps since most of the development/testing in production environments that has been done so far has been at the actual exercism.io server this issue hasn't come up.  At any rate, I'm hosting my clone on a dedicated server at Dreamhost and I've had to do some hacks to get this thing up and running.  It's currently running through Phusion passenger.

My spring classes start a week from today, so I've got A LOT of work to do to create problem sets to keep them going for the first few weeks.  Now that I seem to have a full instance up and running, I think the rest should be straightforward.  I'll be sure to submit bug fixes when and if I find them.  Love this project!!!

**Comment by kytrinyx** [comment]
I completely missed the dotenv thing. I don't use foreman (others convinced me to add it to the stack because they felt it was easier). I always run the app with `. .env && rackup -p4567`, and never noticed that this piece was missing.

Thanks so much for submitting the fix, and good luck getting your class prepped!

I'd love to hear how things go with your custom installation, and if you have any ideas of simplifications/improvements do holler. The current codebase happened by accident in many ways, and so there's no real architecture and the code is a mess.

Feel free to use any of the existing problems, if they seem relevant (only a handful got ported to PHP so far, but there are probably about 60 or 70 problems in the exercism ecosystem at the moment).

**Comment by kytrinyx** [comment]
@morphatic I just realized that the exercism CLI doesn't expose the config value for setting the problems host :/ I'll try to get this fixed this week so that your students don't have to open up the config file and set it manually.

**Comment by morphatic** [comment]
@kytrinyx ooh! thanks for pointing this out.  I couldn't resist the chance to play with a new language (go) and take a stab at making this work.  I got it to work on my local system (64bit OSX 10.9.5).  Don't have a testing setup for other platforms.  See pull request in the `cli` package.

**Comment by kytrinyx** [comment]
That was fast :) I'm impressed that you found your way around so quickly (though to be fair the Go codebase is probably a great deal better than the ruby codebase at this point).
