### ISSUE TITLE
The submit and delete button are too close to each other and not the same size.

### ISSUE THREAD

**Issue by trayo** [exercism/exercism.io#2152]
![screen shot 2015-01-05 at 3 15 34 pm](https://cloud.githubusercontent.com/assets/6809782/5620975/232f5eb8-94ee-11e4-9397-42f5a5f4617a.png)

I used 
```
padding-left: 14px;
padding-right: 15px;
margin-top: 10px;
margin-top: 10px;
```
in chrome and it looked much nicer.

![screen shot 2015-01-05 at 3 29 50 pm](https://cloud.githubusercontent.com/assets/6809782/5621142/bf262864-94ef-11e4-8292-6b47d4f8eab1.png)

**Comment by tejasbubane** [comment]
Shouldn't these be on the same line?

**Comment by trayo** [comment]
Making them on the same line would also be acceptable and I think it's as simple as adding btn-group to the div class that surrounds the buttons.
