### ISSUE TITLE
Proposal: Sorting Submissions by Popularity

### ISSUE THREAD

**Issue by stere0id** [exercism/exercism.io#2153]
Hi,

I stumbled over exercism.io a few days ago and have enjoyed it so far.
After making my first submissions and coming to an iteration where I was satisfied, I was wondering what solutions to the exercise were approved most by the community in terms of likes.
If there isn't a way to sort in this order which I have overseen, I'd like to propose adding such a feature.
This way good solutions submitted a while ago don't simply vanish and one might be able to see that the solutions to a certain problem converge to a few solutions with the best trade-offs.

Thanks for your time.

edit: It might be also interesting to have an order not only respecting likes but rather likes in relation to views, such that good solutions with less views still get attention.

**Comment by kytrinyx** [comment]
Yeah, at the moment there's simply no good way to explore existing solutions, and that's a very frustrating lack in the system.

There's an open issue that discusses this (#1709), so I'm going to close this as a duplicate. Thanks so much for thinking out loud—that's the only way this project is going to get any better! :heart:

**Comment by stere0id** [comment]
You're very welcome!
Keep up the good work. I really like the project, allthough it has a few rough edges here and there in its current state. And the design is just pure awesomeness! <3
