### ISSUE TITLE
404 after logging in with github to submit a nitpick

### ISSUE THREAD

**Issue by dmoney** [exercism/exercism.io#2154]
Went to this code submission: http://exercism.io/submissions/df092b7311e44613b298bf6abee49d38
Entered text for a nitpick.  Clicked "Nitpick" and then logged in with my github account.  When I had logged in, it took me to a 404 page that said "we don't have that".  When I went back to the code submission, the text of my nitpick was gone.  Entered a new nitpick, and was able to submit it successfully.

Browser: Safari on OSX mavericks.

This was also the first time I had used github to log in to anything else, and the first time ever logging into Exercism.

**Comment by kytrinyx** [comment]
Ouch, so sorry about losing your data. Thanks for reporting this.

**Comment by dmoney** [comment]
No big. Gave me a
Chance to revise.  Welcome :)

On Tuesday, January 6, 2015, Katrina Owen <notifications@github.com> wrote:

> Ouch, so sorry about losing your data. Thanks for reporting this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/exercism.io/issues/2154#issuecomment-68959951>
> .
>


-- 
Sent from my thumbs.
