### ISSUE TITLE
End of all problem in a track 

### ISSUE THREAD

**Issue by masters3d** [exercism/exercism.io#2156]
When a students finishes all the problems in a track, the command line like should say so. Almost the website should say or suggest new problems.

**Comment by kytrinyx** [comment]
yeah, I agree -- it's abrupt and unhelpful right now.

**Comment by kytrinyx** [comment]
Notes: I think this needs to be solved in both CLI and x-api.

**Comment by kytrinyx** [comment]
This issue is not yet solved, and it's going to require some discussion about the user experience. Which actions on the CLI are affected, and how should they respond? What should the web site say and where should it say it?

**Comment by masters3d** [comment]
Something to this effect with out brackets : "You reached the end of this [computer] language track. Congrats! [Achievement unlocked.] Please consider [using your new super-power by ] implementing new problems into this track. Go to <link-to-remaining-problems> to learn more."

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/exercism.io/issues/2711

**Comment by kytrinyx** [comment]
We've implemented something in the profile page, but not in the CLI.

**Comment by kytrinyx** [comment]
We are digging into the broader topic of "what does it mean to complete an exercise" and "what does it mean to complete a track" as one of the core questions for the redesign. I'm going to go ahead and close this, and when we've hashed out some of the basic thoughts, we'll be sharing them.
