### ISSUE TITLE
Can't fetch new Python exercises

### ISSUE THREAD

**Issue by patrickbeeson** [exercism/exercism.io#2160]
I just finished the third Python exercise. After submitting it to exercism, I tried to fetch another exercise, but was unable to do so. Here's what I got from the CLI:

tinylappy:leap patrickbeeson$ exercism fetch python
  python - bob
  python - leap
  python - word-count
Exercises written to /Users/patrickbeeson/exercism

Basically, the same exercises I had before issuing a fetch.

**Comment by kytrinyx** [comment]
That's odd.

What directories are available in your python exercism dir?
What does your account page (http://exercism.io/account) say about which exercises you've submitted?

Are there any exercises in your python dir that are not listed on the site? If so then if you submit the missing problem, it will fetch a new exercise for you automatically.

**Comment by patrickbeeson** [comment]
Doh. My bad. I was looking a submitted exercise of another language with the same name. Thanks for the response though!

**Comment by kytrinyx** [comment]
It's definitely a UX fail, I've opened a ticket on the CLI to discuss ways of making it clearer. Glad it got sorted.
