### ISSUE TITLE
Allow language filtering on account page

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism.io#2161]
If I go to http://exercism.io/account, I get a table showing all my submissions. I'd love to be able to click on a language and go to a page that lists my submissions for that language only.

**Comment by kytrinyx** [comment]
Yes, this would be useful!

**Comment by alexclarkofficial** [comment]
Is anyone working on this? Thinking I might make a go at it this week.

**Comment by kytrinyx** [comment]
Nobody has snatched this up -- it's all yours :)

**Comment by alexclarkofficial** [comment]
I took a good hard look at this and think I might punt, at least for the time being.  I could definitely make this work using jQuery, but feel this would leave the app in a more disheveled state then when I came into it.  Perhaps this could be addressed as part of a bigger rewrite to create this table client side with Angular rather than erb.  Is there anything like that in the works?

**Comment by kytrinyx** [comment]
That is not in the works, but it would be lovely to make it happen. I can create the API endpoint for it if someone wants to take on the front-end piece.

**Comment by alexclarkofficial** [comment]
Okay, you've inspired me.  I'm going to try to take another try in the next week or so.

**Comment by kytrinyx** [comment]
In that case I'll have the API endpoint ready for you in the next couple of days.

**Comment by alexclarkofficial** [comment]
Awesome - thanks!

**Comment by kytrinyx** [comment]
OK, I have an endpoint for you. It's not very fancy, and it might not do what you need, but it's a starting point. Once we lock it down, I'll add tests for it.

http://localhost:4567/api/v1/problems?key=USERS_API_KEY

We also need to implement some session sharing between the front-end and the backend so we don't expose the key like this.

**Comment by kytrinyx** [comment]
We're working on a profile activity stream to replace the table of exercises: https://github.com/exercism/exercism.io/issues/2059
