### ISSUE TITLE
[you can help] Make the README work for you!

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2163]
I have a couple of goals for exercism. One is about the site itself: practice + mentorship. The second is about open source: I want exercism to be a place where people feel welcome and where people can get their feet wet in open source without feeling overwhelmed and intimidated.

At the moment there are several things that make exercism intimidating.

* The main codebase is a mess (it's a prototype, it happened by accident, it will get better... slowly)
* The documentation is sorely lacking
* The issues are pretty disorganized and they lack context

I do my best to counteract all of that by helping people figure out git and pull requests, and whatever else I can to make this a friendly, worthwhile place to contribute.

One of the things that would be very, very helpful is if you would pick one of the repositories and try to get the development environment running locally... and then make sure that the README reflects your situation.

I've stolen the following suggestions from @daguar:

> * Improve the installation/local setup instructions so that they're approachable to someone with little knowledge of the language/framework
> * Add examples of usage
> * Make sure the overall "README experience" makes sense — were all your questions answered? did you know how to find out more? if not, PR away!

This project has about 25 different READMEs in about as many languages.

The main site is in **Ruby**: https://github.com/exercism/exercism.io/blob/master/README.md - this is probably the most complex project to get running out of everything in the exercism organisation.

There is also an API in **Ruby** that doesn't have any complex dependencies (no database, no seed data). That said, it does use git submodules, which is considered to be, if not hell, then the major seaport to hell. https://github.com/exercism/x-api/blob/master/README.md - this is the API that delivers all of the test suites and READMEs when someone says `exercism fetch` on the command-line.

The command-line app is in **Go**: https://github.com/exercism/cli/blob/master/README.md - this codebase is fairly well organised, and the code is pretty straight-forward to read and navigate.

There's a small **JavaScript** app that delivers an [overview](http://synopsis.exercism.io/) of all the problems in all the available languages: https://github.com/exercism/synopsis/blob/master/README.md

Finally, there are all the problem repositories, linked to from this page: https://github.com/exercism/x-api/tree/master/problems - here the README should make it clear how to get the code running locally, how to run the tests (individually as well as for everything, if available), and ideally it should probably link to the useful parts of the [contributing document](https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md#contributing-to-existing-problems) about existing and new exercises/problems.

**Comment by maclover7** [comment]
@kytrinyx Is the eventual plan to rebuild the codebase from scratch using something like Rails? I've heard a couple of times that the current Sinatra codebase is just a prototype. I'd be more than willing to start working on a Rails rebuild.

**Comment by kytrinyx** [comment]
I won't be building it in Rails, no. I'll most likely rebuild the backend as an API in Go, with a pure-javascript front-end.

**Comment by venelrene** [comment]
Reading this README, I don't know where to honestly start?

**Comment by kytrinyx** [comment]
Hi @venelrene That's exactly what I was afraid of. I don't know what's missing, but I'm very eager to figure that out and correct it.

When you say "this README" do you mean the main README for the exercism/exercism.io repository?

In terms of _where to start_, do you mean a more high-level overview of things, for example what exercism is about, and what kind of contributions we're looking for, and the various technical pieces of the project? Or is it more that the steps in the README don't make sense, or there seem to be missing steps before step 1?

**Comment by venelrene** [comment]
@kytrinyx all of the above

**Comment by kytrinyx** [comment]
OK, I'll work on writing up all of the above, and I'll ping you for feedback. Thank you!

**Comment by venelrene** [comment]
Thank you

**Comment by kytrinyx** [comment]
@venelrene I've made some changes to the README and the CONTRIBUTING.md document. Would you give this a read-through and see if any of it makes more sense? I expect that I'll need to do more work on it, but I'd like your feedback on what's there, if possible.

**Comment by venelrene** [comment]
@kytrinyx I want to help debug some issues. I am trying to figure out where do I start first. I am guessing I fork this exercism repositories and create a pull request, right? Next thing I am trying to figure out is, how do I get this to run locally? If i debug an issue, does it have to be in that language necessary because I will be trying to get it up and running locally on ROR. I hope my questions are making sense.

**Comment by kytrinyx** [comment]
Cool!

> I am guessing I fork this exercism repositories and create a pull request, right?

Yeah, fork this repository, and follow the instructions in the README to get this running locally: https://github.com/exercism/exercism.io/blob/master/README.md#contributing

The app is in Sinatra, not Rails, but Ruby is Ruby, and it does use ActiveRecord, so many things will be familiar.

> If i debug an issue, does it have to be in that language necessary

Most of the issues that you'll find will be either Ruby or JavaScript. A few might be related to the specific language tracks, but usually those will be posted in separate repositories.

Once you get it running, here's a small issue that might give you a reason to poke around in the code base and get familiar: https://github.com/exercism/exercism.io/issues/2171

Let me know if you get stuck.

**Comment by kytrinyx** [comment]
Update: #2171 has been resolved.

**Comment by IanVS** [comment]
> I'll most likely rebuild the backend as an API in Go, with a pure-javascript front-end.

Have you decided on a JavaScript framework?

**Comment by kytrinyx** [comment]
I've been back and forth a few times, but AngularJS is widely adopted and will let us do a piecemeal transition, which is more and more important to me. Check out #2296

**Comment by tigershen23** [comment]
Just went through the `exercism.io` `README.md` and `CONTRIBUTING.md` to get set up on my local machine, and have a few thoughts from it:

* The organization between the README and CONTRIBUTING documents was a bit confusing, causing me to hop between the two more than should be necessary. 
    * The README directed me to CONTRIBUTING, but the second line in CONTRIBUTING bounces me right back. 
    * To me, the project setup stuff should be in CONTRIBUTING. I don't think that this would make anyone any less likely to contribute, while making it so that everything you need to get started is in one document.
    * With the documents set up the way they are, it can be easy to miss the `Pull Requests` and `Workflow` sections of CONTRIBUTING, which I'd say (especially the first few steps of workflow) are part of getting set up with the app.
* I had to do a couple of minor things to get set up on Vagrant - maybe these could be in a wiki doc or something?
* Couple of nits  - linking to tools and libraries that people may not be familiar with, explanation of some of these tools, etc. 
* Some personal preference things around wording/clarity, but these are minor.

WDYT? I'm happy to submit a patch for this stuff, with https://github.com/exercism/exercism.io/issues/2096 as a bonus.

**Comment by kytrinyx** [comment]
All of these things sound like good suggestions.

How about if the README turns into a high-level overview of what exercism is about and what types of contributions are typical, and then the CONTRIBUTING doc gets into all the specifics?

**Comment by tigershen23** [comment]
Cool, I'll PR something for discussion

**Comment by dogweather** [comment]
Hmm - I'm getting this config/database error, following the contribute instructions:

```
$ bin/setup
The Gemfile's dependencies are satisfied
rake aborted!
PG::ConnectionBad: FATAL:  database "robb" does not exist
/Users/robb/src/exercism.io/lib/db/connection.rb:10:in `initialize'
/Users/robb/src/exercism.io/lib/db/connection.rb:10:in `new'
/Users/robb/src/exercism.io/lib/db/connection.rb:10:in `escape'
/Users/robb/src/exercism.io/lib/tasks/db.rake:29:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:from_scratch => db:setup
(See full trace by running task with --trace)
```

It looks to me like the database config isn't being properly set.

**Comment by johnpaulashenfelter** [comment]
@kytrinyx no prob!

@dogweather i'm guessing that you're terminal login is "robb" -- there's some documentation about how to deal with this in the CONTRIBUTING.md, but I want to make sure things do work smoothly since I added these tasks :smile: 

Do you have a config/database.yml? The `db:setup` task tries to use that -- and it should probably be the hardcoded values checked into the repo the first time through this.

Depending on your configuration of *Postgresql*, you might need to pass in your PGUSER -- maybe you want `PGUSER=postgres rake db:from_scratch`?

Just @ me with more info.

**Comment by dogweather** [comment]
Thanks @johnpaulashenfelter I was able to get the dev environment up & running fine by running the individual rake tasks myself in dev & test mode, manually supplying `RACK_ENV`, etc.

So the smaller, lower-level tasks do work and can yield a good environment in which all tests pass. So it seems to be something to do with `db:from_scratch`. This is for a fresh clone from master, so yes, it has a config/database.yml.

**Comment by dogweather** [comment]
FYI, I'm working on this little by little. Here's a recipe I've found that works reliably, and should help debug it:

1. fork
2. clone
3. `$ bin/setup` until it crashes with the message above
4. `$ createuser --superuser exercism`
5. `$ bundle exec rake db:create db:migrate db:seeds:fetch db:seed`
6. `$ RAKE_ENV=test bundle exec rake db:create db:migrate`

**Comment by dogweather** [comment]
I submitted a fix on #2657

**Comment by dogweather** [comment]
Idea: user-oriented navigation section in the Readme.

Currently, the Readme is project-oriented, e.g., **The Ecosystem** section, which explains the project's way of looking at its world.

But I think it'd help with onboarding devs to additionally have a user-oriented section, form the perspective of someone who wants to help. Essentially, it'd be organized like this:

### I'd like to contribute by coding (or learning to code)...
#### Ruby
Sub-projects X, Y, and Z are all Ruby-based, and Z incorporates many Rails libraries.

### Go
Sub-projects A, and B are in Go, and C is a Go app currently in design stage.

#### HTML & CSS
[etc.]

Along with this, it'd be nice to tag the Ecosystem items with languages in use.

**Comment by kytrinyx** [comment]
This is a great idea. We absolutely should do this.

I've actually started to do that for one of the contributing documents, though it could be improved: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md

Each section is "I want to accomplish X".

**Comment by kytrinyx** [comment]
I've gotten feedback that the documentation is good. I'm going to close this, even though it can surely always become better.
