### ISSUE TITLE
Try to nitpick when not logged in loses text

### ISSUE THREAD

**Issue by biinari** [exercism/exercism.io#2166]
Given you are not currently logged in, when trying to nitpick on a submission it takes you to a login page, losing the comment you just crafted. There is a flash message that suggests you "Go back, copy the text, log in, and try again", however the comment is not present when you go back. Perhaps going back keeps the text there in some browsers / setups but evidently not for me.

Tried in Google Chrome (39.0.2171.95) and Firefox (35.0) on archlinux.

This gets irritating, especially if you followed the link to your own submission, where you feel like you are already in the flow so don't think to log in first.

I think it would help if the input were disabled when not logged in to prevent losing your comments.
Alternatively:

1. Replace the nitpick input with a message instructing to login first
2. Keep the comment through the login process (likely not to be a favourable solution)

**Comment by kytrinyx** [comment]
Yeah, this is frustrating. I think (1) is the quickest fix, but (2) would be a much nicer experience. I'm not a front-end developer, but I'm guessing we could use local storage in javascript.

Thanks for taking the time to write it up.

**Comment by monkbroc** [comment]
I ran into this today too.

I have another suggestion for a quick fix: Add target="_blank" to the form when the user is not logged in. The log in page will open in another tab. After you log in, you can go back to your nitpick and hit submit again.

You'd need to re-enable the nitpick Submit button (or just don't disable it on click if not user is logged in).

**Comment by kytrinyx** [comment]
@monkbroc that's a great workaround, thanks!

**Comment by kytrinyx** [comment]
We did a complete audit of the issues today, and this is the only really high priority bug that we have at the moment. I've tweeted it out, since my javascript skills are dismal: https://twitter.com/exercism_io/status/581889402290315264

I will, of course, be around to help providing context or deal with setup issues. Also, if there's a backend component to this, I'm happy to fix that.

**Comment by sublimecoder** [comment]
An alternative solution is to pop up a login modal and log the user in using Ajax. Then you can resubmit the form using callbacks after a success returns. But this also requires the form to submit via Ajax in order to kick off these events.

**Comment by makenova** [comment]
Would saving the comment to local storage be a viable option?

**Comment by ismaelga** [comment]
I think the local storage would be perfect for this. With the implementation I'm thinking of it would actually help if you close the browser tab accidentally. Like, keeping every comments for offline.

Also it should be pretty simple to implement.

**Comment by billautomata** [comment]
[sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) is probably better, have the nitpick to go to storage when the user clicks submit.

This would require javascript to check if there is a cached nitpick and if so re-populate the page with the nitpick.  How old is this cached nitpick?  What would qualify as criteria to clear it?  How do you keep old nitpicks from reappearing forever, and new nitpicks from disappearing wrongfully?

I vote login modal.  Correct the problem in place, have the session bits be set by the server, and then when the user clicks submit again, the new POST request will be correctly authenticated.

**Comment by sublimecoder** [comment]
Possibly but from a UX perspective keeping them in the same context and providing actions without a page reload would be my preferred method. Local storage could be used in either situation. Using Ajax is allows the programmer to execute the action otherwise just using local storage you'd need to have them submit it twice essentially.

**Comment by kytrinyx** [comment]
Could we store it with a reference to the submission uuid that is in the url? We could put the uuid in the page as a data attribute if that would help. Then the nitpick would only need to be put back into the comment box if it's the same problem.

Also, I'm thinking it's probably only relevant within about a day (that's actually probably very long).

**Comment by ismaelga** [comment]
@sublimecoder Good point. But I have to add that modals are not that easy to get right for good mobile UX.

**Comment by sublimecoder** [comment]
@ismaelga very true.

**Comment by kytrinyx** [comment]
Yeah, modals are painful; so far I think we've managed to avoid them.

**Comment by trueheart78** [comment]
After thinking about this, is there a reason why we couldn't solve it just using server-side sessions variables? Perhaps a 'comment-url' and a 'comment-body'?

When the user submits a comment, have the login page redirect detect if certain data was provided in a POST that matches the comment structure (might just check the endpoint & method, really) and store the relevant data (url + body) in the session. When the user gets back to the page, we can verify that they are on the proper 'comment-url' and preload the it with the 'comment-body' field. On submission of the form and after saving the comment to the database, wipe both of the session variables.

**Comment by daviscabral** [comment]
Why not just a "Sign in with GitHub to provide feedback" button?

Not a fix, but since it's using a third part auth system, it will allow the user to know before hands that he is going to be redirect to Github before actually adding the comment.

**Comment by kytrinyx** [comment]
@trueheart78 that's very simple and doable. I kept thinking that it had to be solved client-side, and didn't stop to think. Thanks!

@daviscabral That could work, too, but those pages are already pretty messy and complicated, and I suspect that we'd forget edge cases. Also, there's the thing where a session seems to time out, but you're still on the page. It doesn't happen often, but in those cases it looks like you're logged in, but then the comment is lost.

**Comment by ksolo** [comment]
@kytrinyx I threw together a JS example of what this may look like in a pull request. We can explore this or throw it out, I'm not married to it and won't take offense :)

**Comment by kytrinyx** [comment]
That fixes it, thanks. At the moment I'm most interested in a stop-gap. I'm in the process of reworking the whole site, and this will eventually get some proper attention, but the most important thing is that I don't want people losing their work.
