### ISSUE TITLE
CLI autocomplete

### ISSUE THREAD

**Issue by jdar** [exercism/exercism.io#2167]
Please do let me know:

1) how stable you think the current CLI-tool API is  (i.e., can I hardcode against existing behavior?)
2) whether this is something you've already started // anyone has already taken a stab at this (in any language)?

**Comment by kytrinyx** [comment]
There's a bash completion script: http://cli.exercism.io/exercism_completion.bash

The api is fairly stable. There are a couple of deprecated commands (they'll be removed in the next release), and there are probably a couple of more commands in the pipeline, but no huge changes that I foresee.

**Comment by jdar** [comment]
ok, great. I'll probably have some time after the 30th to flesh this out a bit.

**Comment by jdar** [comment]
maybe this should be labeled 'vision' or something.

**Comment by kytrinyx** [comment]
Vision is for long-term stuff that we haven't decided how to do yet :) I've added the code label. Thanks!

**Comment by pbhandari** [comment]
Hi, 

So I got annoyed by having no completion for my zsh and decided to write my own system.  The file is [here](http://pbhandari.ca/exercism_completion.zsh) and only needs to be sourced from a zsh file to work.

I need to fix it so that it works dynamically, but I thinkt for now it'll do.

**Comment by kytrinyx** [comment]
Nice! If you have time, would you submit it to https://github.com/exercism/cli-www ?

We have a bash completion script, but a zsh script would be a great addition.

**Comment by kytrinyx** [comment]
Added in https://github.com/exercism/cli-www/pull/25
