### ISSUE TITLE
How do I test the C++ program?

### ISSUE THREAD

**Issue by simej** [exercism/exercism.io#2169]
Hello,

I downloaded exercism and I have some problems. I successfully inserted my API key, fetched the exercises and I started with the Bob C++ program. I opened the bob_test.cpp file which contains some kind of tests with which I am not familiar.

I am not very skilled programmer, I am sure my code won't be the most efficient, but I had just a few problems writing the code, however I have absolutely no idea how I am supposed to run the tests. I develop under Windows in Visual Studio Community.

Could you, please, help me, or is there FAQ I missed? I would like to move to another task.

Thank you for answers.

**Comment by kytrinyx** [comment]
There's a help page for C++ here: http://help.exercism.io/getting-started-with-cpp.html

It should get you started. If you're still stuck, then ping back here and we'll get you sorted!

**Comment by simej** [comment]
Katrina, thank you for the reply. I read the article, installed CMake and the Boost library, but how to I implement it now?

I have the bob work folder containing my solution in the header file...
![bob](https://cloud.githubusercontent.com/assets/8894995/5800294/fe292096-9fdc-11e4-9b95-e1f8063a7979.png)

Afaik the implementation works, it's a basic header file http://pastebin.com/s24MVxAf but I just don't know how to setup the cmake using the GUI. Which folders to select etc. I downloaded CMake 3.1.0 and I have never worked with that application before.

**Comment by LegalizeAdulthood** [comment]
The section labelled "Working the Exercise" in the getting started with C++ instructions shows you how to run CMake to generate a build for your environment (in this case, your environment appears to be Windows from the screenshot, so you'd generate a Visual Studio solution and project using the appropriate generator with CMake).

Once you have the VS solution generated, you can use Visual Studio to edit your code and build the solution.  Building the solution automatically runs the tests and fails the build if any unit tests fail.  The instructions for each exercise contain a section named "Passing the Tests" that give you guidance on how to proceed from test case to test case as you work your solution.

Here's how you can help us:
- How can we improve the documentation?   Was this information difficult to find or confusing?
- What would have helped you before asking this question to discover this information on your own?

Ideally we'd like things to be as obvious as possible, so if this was difficult for you to find it was probably difficult for someone else too and we'd like to smooth out those bumps :smile_cat:.

**Comment by simej** [comment]
Guys, thank you very much for the replies. The problem here is, when I open the CMake GUI, I am not really sure what I am supposed to set as "Where is the source code:" and "Where to build binaries", I know how to make a red-black tree in C++ but I don't know how to use compiler :D.

Perhaps something with my CMake is entirely wrong, this is how I have it setup along with the errors I get when I hit either Configure or Generate.

![cmake](https://cloud.githubusercontent.com/assets/8894995/5804831/b68680d0-a009-11e4-86dc-1cff5b51c718.png)

Now, as I have already mentioned, I am completely new to CMake and Boost. @LegalizeAdulthood You asked, how I think you could improve the documentation. Perhaps a step by step solution of installing CMake, Boost library, how installation folders of those two elements affect the settings of Cmake and Boost (if you need to specifiy the installation folders somewhere)?

I personally think the whole concept of exorcism.io is perfect, but quite difficult to get into. I am sure once you have the Cmake set up, it will be quite easy, but if you don't and are new to Cmake like me, setting up the environment is really stressful. :(

**Comment by LegalizeAdulthood** [comment]
I didn't include instructions on how to use CMake with the GUI because I am not sure if it is available on all platforms.  I included instructions for how to invoke cmake from the command-line, since you already have to use the command-line to invoke the exercism tool.  Did you try the command-line instructions?

**Comment by kytrinyx** [comment]
Closing, since this has been inactive for a couple of months. @simej, if you are still having trouble, please reopen the issue with more information.
