### ISSUE TITLE
Please grade my score on this program written in 1993

### ISSUE THREAD

**Issue by YoshiyukiMukudai** [exercism/exercism.io#2172]
#!/bin/csh -f

### Compact wise program that extracts user's first name only from result of "finger" command on UNIX without any Admin rights ###

set who = `finger -m $user`echo -n ' Hi '"$who[7]" echo '\!' (= Hi YOURNAME!)

# First name comes at 7th place divided by spaces (on my Unix system at the time)

**Comment by kytrinyx** [comment]
Hi @YoshiyukiMukudai, we don't currently do nitpicks on code outside of the provided exercises (see http://synopsis.exercism.io).

We have been asked to add a couple of shell scripting tracks ([bash](https://github.com/exercism/xbash) and [powershell](https://github.com/exercism/xpowershell)), but the interest has not been very high, and so we have not received many submissions.

Please checkout the "review my code" subreddit, though: http://www.reddit.com/r/reviewmycode/

**Comment by YoshiyukiMukudai** [comment]
But, don't you think mine was unique for its age?
Regards,
YM

On Thu, Jan 22, 2015 at 12:29 AM, Katrina Owen <notifications@github.com>
wrote:

> Hi @YoshiyukiMukudai <https://github.com/YoshiyukiMukudai>, we don't
> currently do nitpicks on code outside of the provided exercises (see
> http://synopsis.exercism.io).
>
> We have been asked to add a couple of shell scripting tracks (bash
> <https://github.com/exercism/xbash> and powershell
> <https://github.com/exercism/xpowershell>), but the interest has not been
> very high, and so we have not received many submissions.
>
> Please checkout the "review my code" subreddit, though:
> http://www.reddit.com/r/reviewmycode/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/exercism.io/issues/2172#issuecomment-70857442>
> .
>



-- 
---
Yoshiyuki Mukudai
יוֹשִׁיוּכִ
http://www.eonet.ne.jp/~michelangeli/index.html
