### ISSUE TITLE
Pending submissions page orders backwards

### ISSUE THREAD

**Issue by dalexj** [exercism/exercism.io#2173]
When I visit `/nitpick/:language/recent`, I can see the top x most recent, but they're ordered in opposite order, as in most recent at the bottom

**Comment by kytrinyx** [comment]
That was done deliberately a long time ago, but I've come to believe that it really should order with the most recent first. Thanks!

**Comment by kytrinyx** [comment]
Fixed in 911f466d868fa1c0de0556278058f06e1b6b4de6
