### ISSUE TITLE
trying to run test $ ./gradlew check (mac)

### ISSUE THREAD

**Issue by sinistaE** [exercism/exercism.io#2175]
I keep getting "No such file or directory" when I input that command. I've installed and config'd exercism and am trying to get started with Java. What am I doing wrong?

**Comment by kytrinyx** [comment]
We haven't launched java yet, I'm still trying to get help figuring out the final details: https://github.com/exercism/xjava/issues/3

/cc @chelseakomlo

**Comment by kytrinyx** [comment]
Do you have homebrew? If so, I think you can say `brew install gradle`

**Comment by kytrinyx** [comment]
Update: We've launched! Check out the documentation for getting started here: http://help.exercism.io/getting-started-with-java.html

**Comment by chelseakomlo** [comment]
Hey Katrina- do you need to add us to an admin list? I don't see Java as an option to Nitpick...

**Comment by kytrinyx** [comment]
I thought I had added you, let me double-check that!

**Comment by kytrinyx** [comment]
I've added @brmenchl and @chelseakomlo to the admin list for Java. I can't add the others until they log in.
