### ISSUE TITLE
Feature: Make travis run the test for each uploaded problem

### ISSUE THREAD

**Issue by masters3d** [exercism/exercism.io#2177]
In this way travis can give feedback to the submitter to make sure test are passing:

Example travis script for an ios mac xcode project
https://github.com/masters3d/SwiftGraphics/blob/develop/.travis.yml

I am sure this can be done with most tracks? Couldn't it?

**Comment by wobh** [comment]
What would Travis say differently than running the tests locally? What if you've made local adaptations to the tests for exploratory or to take on an additional challenge?

**Comment by masters3d** [comment]
Somebody giving a nickpick needs to run each problem implementation locally in order to give know if if the implementation is passing the tests. My thinking is that by having travis run the pre-set of tests and confirming to reviewer that the test passed, then said reviewer could give better informed feedback. 

I think local adaptation of tests is not a good idea to be uploaded as part of the problem for somebody trying to learn a new language. The temptation would be to change the test to make them pass. 

A better approach would be to use something like Behaviour Driven Development to create every possible edge case out there. But that would be very involved I imagine. 
https://github.com/rspec/rspec
https://github.com/onsi/ginkgo
https://github.com/Quick/Quick

**Comment by kytrinyx** [comment]
I think this is a duplicate of #1710 and/or #1757 -- could you elaborate if it differs from the existing issues?

**Comment by masters3d** [comment]
yep. dup. https://drone.io/ looks cool too. Thanks

**Comment by kytrinyx** [comment]
cool, it's definitely on the list of things we'd like to figure out eventually, it's just not at the top of the list.
