### ISSUE TITLE
Saying it cannot find exercism, i gave it a new path like the video said

### ISSUE THREAD

**Issue by cordovbt** [exercism/exercism.io#2178]
Breannas-MacBook-Air:~ breanna$ echo 'export PATH=~/bin:$PATH' >> .bash_profile
Breannas-MacBook-Air:~ breanna$ source .bash_profile
Breannas-MacBook-Air:~ breanna$ exercism -v
-bash: exercism: command not found
Breannas-MacBook-Air:~ breanna$

**Comment by kytrinyx** [comment]
What does `ls ~/bin` say?

**Comment by cordovbt** [comment]
Breannas-MacBook-Air:~ breanna$ ls~/bin
-bash: ls~/bin: No such file or directory

does this mean bin was never created?

**Comment by cordovbt** [comment]
Breannas-MacBook-Air:~ breanna$ ls~/bin
-bash: ls~/bin: No such file or directory

Does this mean bin wasn't properly made?

**Comment by kytrinyx** [comment]
No, you need a space between `ls` and `~/bin`:

```
ls ~/bin
```

**Comment by cordovbt** [comment]
Breannas-MacBook-Air:~ breanna$ ls~/bin
-bash: ls~/bin: No such file or directory

I tried that and it said this again, I'm new to the programming world sorry if this is confusing

**Comment by kytrinyx** [comment]
Try copy and pasting the command that I gave you. What you're showing me doesn't have a space between the `ls` and the `~`.

> I'm new to the programming world sorry if this is confusing

No, don't worry about it. The terminal is incredibly confusing at first.

**Comment by cordovbt** [comment]
I got help from my professor turns out i was using my Downloads instead of mv Downloads. Thanks for your help, I appreciate it!

**Comment by kytrinyx** [comment]
Glad you got it sorted!
