### ISSUE TITLE
Does not correctly bring submissions out of hibernation?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2179]
I got an email this morning about a submission that had gone into hibernation. They commented on it, as did someone else, and it was still in hibernation afterwards.

Is this reproducible?

**Comment by csgavino** [comment]
@kytrinyx you're using `exercise_hibernating?` in `app/views/submissions/alerts.html.erb:7` instead of `hibernating?` is this intentional?

**Comment by kytrinyx** [comment]
Oh, no that's probably not intentional at all.

**Comment by csgavino** [comment]
@kytrinyx will changing that to `hibernating?` resolve this issue? If so I can submit a patch. And I did notice that commenting toggles Submission's state to pending but it doesn't change the state of Submission's UserExercise. So, that might be another issue as well?

**Comment by kytrinyx** [comment]
It looks like calling `hibernating?` instead of `exercise_hibernating?` will resolve this issue, however it would be more consistent to also make sure that commenting updates the state of the submissions `UserExercise` as well.

**Comment by csgavino** [comment]
Alright I'll take care of it.

**Comment by kytrinyx** [comment]
Thanks :)
