### ISSUE TITLE
Giving Feedback on where you are in each language

### ISSUE THREAD

**Issue by thomas-lange-smf** [exercism/exercism.io#2181]
Is there a indicator on where - percentage of completion and which exercise - you currently are with your submissions?

The % thing might be interesting while the "current exercise" (that is, not the last submission, but the one that is currently open) would make navigation a bit easier.

To me this seems to be missing.

**Comment by kytrinyx** [comment]
Yes, this would be very nice to have.

**Comment by ErikSchierboom** [comment]
I would love this!

**Comment by thomas-lange-smf** [comment]
Well if I get the json correctly, why not render a page with the started tracks like a "bus line" plan:

http://x.exercism.io/tracks/javascript for instance gives a array of problems in the correct order.

So indicating submission (number of) for each langauge and maybe comments would actually result in a pretty good overview. Actually exercism already has a templater for that (with a few modifications):
![selection_014](https://cloud.githubusercontent.com/assets/4717890/6194565/de95e4a6-b3c5-11e4-93c6-b18fe5bbef65.jpg)

**Comment by kytrinyx** [comment]
Yepp, that would work. People are allowed to submit things out of order, but we could just move everything that they've submitted ahead of everything they haven't.

**Comment by kytrinyx** [comment]
That said... the bus-line thing is great for anything under ~10 but there are several tracks that have 70 problems.

Maybe something like the github streak, with hover data about which problem each square represents?

**Comment by petertseng** [comment]
I have a suspicion that https://github.com/exercism/exercism.io/commit/eb78407b953ecc7cf16d6e0e1f856ce09ee88eeb has done this? At least the percentage part is done. Current exercise isn't, but that's a bit of a tricky thing since it's possibly to jump around non-linearly (I say this being very aware that I do this a lot)

**Comment by kytrinyx** [comment]
Yeah, this is the progression bar that was just added.
