### ISSUE TITLE
Notify people when new problems are added to track

### ISSUE THREAD

**Issue by masters3d** [exercism/exercism.io#2184]
Notify people who have finished a track when more problems are available in their track.

**Comment by kytrinyx** [comment]
Yes, that would be lovely.

I think that this could be a part of the [activity streams](https://github.com/exercism/exercism.io/issues/1899) feature.

By default, anyone who submits a solution to any problem on a language track, would be subscribed to new problems in that track.

On a regular basis, some service could check with x-api (http://x.exercism.io/tracks) what problems are available. It would keep track of problems that it knows about, and for each problem that is new, it would notify the activity stream service that there is a new problem. The activity stream service could then process this in the same way as all the other events based on subscriptions and type of event.

This would also make it possible for people to unsubscribe from tracks that they're no longer interested in.

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/discussions/issues/34

**Comment by kytrinyx** [comment]
Closing in favor of the somewhat higher-level discussion here: https://github.com/exercism/exercism.io/issues/2184
