### ISSUE TITLE
Add instruction to install node-jasmin in bob readme

### ISSUE THREAD

**Issue by morenoh149** [exercism/exercism.io#2186]
I couldn't find this particular problems' source on github so I'll just report it here. The docs I see for the `bob` problem in javascript is
```markdown

## Making the Test Suite Pass

Execute the tests with:

`bash
$ jasmine-node .
`

In many test suites all but the first test have been skipped.
```

mentioning that you should perform `npm install -g jasmine-node` would be more clear to the reader. In my case I didn't have this program installed and I was confused.

**Comment by kytrinyx** [comment]
Yes, you're right, we should link to the "getting started with javascript" page: http://help.exercism.io/getting-started-with-javascript.html

Thanks!

**Comment by kytrinyx** [comment]
I'm deploying the change now. Thanks for bringing it up!
