### ISSUE TITLE
Sidebar on help section of website is broken

### ISSUE THREAD

**Issue by OisinMoran** [exercism/exercism.io#2188]
(In Google Chrome at least) The navigational sidebar at http://help.exercism.io/ appears only for a fraction of a second and thus makes navigating the help section very difficult.

**Comment by kytrinyx** [comment]
I am unable to reproduce this in chrome on my machine. What version of Chrome are you using? Does it change if you use an incognito window?

**Comment by OisinMoran** [comment]
I'm using Version 40.0.2214.93 m and the problem persists in an incognito window. Just updated to Version 40.0.2214.94 m and same behaviour in both situations.

**Comment by kytrinyx** [comment]
Ok, thanks! I'll dig into it and see what's going on.

**Comment by OisinMoran** [comment]
Okay just downloaded Firefox and from the 3 places to click to bring up the side bar across both browsers this is what's happening for me.

**Chrome:** 
*Top left menu button - No effect
*Help Menu button - No effect
*Exercism logo  - Causes the sidebar to pop out then back in again.

**Firefox:** 
*Top left menu button - Works perfectly
*Help Menu button - Works perfectly
*Exercism logo  - Causes the sidebar to pop out then back in again.

**Comment by kytrinyx** [comment]
So weird! Ok, thanks for the details. Are you getting any errors in your javascript console in chrome?

**Comment by OisinMoran** [comment]
No errors. The two that have no effect don't display anything in the console and the Exercism logo just gives "Navigated to http://help.exercism.io/"

**Comment by kytrinyx** [comment]
Ok, thanks!

**Comment by lpbearden** [comment]
I'm still seeing this issue as well.

**Comment by kytrinyx** [comment]
We're working on a redesign which should make the whole thing obsolete. It got stalled a bit (my fault), I'll try to get this rolling again.
