### ISSUE TITLE
Changing skeleton file makes no difference

### ISSUE THREAD

**Issue by OisinMoran** [exercism/exercism.io#2189]
I am new to Exercism and am trying to solve the first Python problem. Any changes I make to the bob.py file seem to make no change whatsoever to failing all 20 tests. I have even tried copying some answers just to see if it would work but nothing. I feel like I'm missing something very basic but I am editing the bob.py file in Sublime text, saving it, then running *python bob_test.py* in Powershell. Any help would be greatly appreciated, Thanks!

**Comment by joshua87simmons** [comment]
Hi OisinMoran,

Have you checked to see if the name of your file and the names of your functions in that file match the names supplied in the test files?

**Comment by OisinMoran** [comment]
Thanks for the reply Joshua!
I just checked them there and there was one small mistake but changing that still had no effect.

**Comment by joshua87simmons** [comment]
Sorry if you've already done this, just covering the basics:

And you've saved bob.py in the same directory as the tests?

**Comment by OisinMoran** [comment]
No apologies needed! Yes I've done that too. Perhaps I haven't set something up correctly

**Comment by kytrinyx** [comment]
Could you show the directory contents of the folder that contains the `bob_test.py` (screenshot or copy/paste so that there's no chance of typos)?

Is there an equivalent to the unix `cat` command to show the contents of a file on Windows? Can you make sure that the file that you're saving in Sublime is actually saving to the file that you think it is on the file system?

**Comment by OisinMoran** [comment]
Ah interesting yes `cat` works in Powershell and indicates that the file hasn't been changed at all from the skeleton file. Okay fixed the problem: I had two sets of the files saved in different folders and I was editing the wrong one! Thanks for your help! (now on to the actual programming part :) )

**Comment by kytrinyx** [comment]
Yay! Glad you got it sorted!
