### ISSUE TITLE
Online Editor for Iteration Submissions

### ISSUE THREAD

**Issue by chezwicker** [exercism/exercism.io#2191]
It would be great if iterations could be created directly in the web interface. This would also allow to directly solve a problem online. As a first step, a very simple editor could be provided, possibly reusing the syntax highlighting from the iteration view.

If the test code and the readme were to be displayed in different tabs on the same page, the user could easily switch between them.

The workflow for a user could then be the following:
* Select a track from the new _Exercise_ menu (next to _Nitpick_). This would open an overview page with different sections:
  * _Current Exercises_ - same as on the _Account_ page
  * _Next Exercise_ - a link to the exercise _CLI fetch_ would serve next
  * _Completed Exercises_ - same as on the _Account_ page
* Clicking on the exercise offered in _Next Exercise_, the user would get to a page initially showing different tabs, with _Problem Description_ (showing _README.md_) active:

Editor | Test Cases | Problem Description | Getting Started
------ | ---------- | ------------------- | ---------------

In the _Editor_ tab, a normal source editor (see e.g. http://www.tutorialspoint.com/execute_ruby_online.php) could be used to add code and a _Submit_ button would allow to submit the exercise.

**Comment by kytrinyx** [comment]
This has come up a couple of times. I think that it would be a useful feature to have (I used to not think so, and I've changed my mind).

**Comment by kytrinyx** [comment]
OK, I've been thinking about this quite a lot, and I have come to the realisation that even though I think that it would really solve the problem for making it easier for beginners to get started with exercism, I simply do not have the resources to make it happen.

If we make it possible to submit the code in an online editor we need to solve syntax highlighting as well as sandboxing in order to run the tests.

I've included this suggestion in the list of things that could help lower the barrier to entry on exercism, and once we have solved the core issues we can look at this problem and all the suggestions again.

Thanks so much for taking the time to think about this!

**Comment by chezwicker** [comment]
I'm not sure we'd need most if what you mention at first / at all. To simply give an alternative to the CLI, we'd only have to offer the CLI's functionality - and in addition maybe syntax highlighting. Even here the existing ones would do if the use case we consider at first is simply submitting iterations (and frankly, most of the highlighters don't really parse the code but simply tokenize and identify keywords, so they should work quite nicely even for inline editing).

If we (later) actually wanted to run the tests on submission, generically configured Travis builds might do the trick - not sure what the usage terms are, though.

Maybe have a quick look at ace.io for a very quick way to get started - would mean switching highlighter to be consistent, I guess, but that may be acceptable.

**Comment by kytrinyx** [comment]
Yeah, I'm not tied to any one highlighter.

When you say online editor you mean a text box with syntax highlighting? How would people run the tests?

**Comment by chezwicker** [comment]
I would say they run them as they do today (locally on their machines or on an online service like http://www.tutorialspoint.com/codingground.htm).

If we only aim at replacing the CLI, everything would work the same, but people would not need to download anything, but they could download / upload exercises through the web interface. I think this will remove a lot of the hassle of getting started.

If we *do* want them to run tests from within the web interface later on, one option might indeed be configuring travis builds and treating submissions like pull requests - that would mean we need one build per language or one build per exercise (that would allow making sure API is respected), but I think this can be left to later as it would add a lot of complexity and would not be easily done for some languages...

My suggestion is to (for now) simply allow inline editing and submission in the web interface. When one exercise is submitted, the next one will be made available (as in the CLI).

**Comment by kytrinyx** [comment]
As long as we're not adding the complexity of having to run the tests for them, I think this is fine. I'm adding it to the list of ideas/suggestions for reducing the friction of getting started, and marking it as the easiest to implement.

Thanks!
