### ISSUE TITLE
Where do I input code in the Java exercises?

### ISSUE THREAD

**Issue by Zunon** [exercism/exercism.io#2198]
Doesn't seem to be clear where should I put the code (etl exercise) for Java

**Comment by kytrinyx** [comment]
You need to use the exercism command-line client to submit the code. Check out the help page here: http://help.exercism.io/submitting-exercises.html

**Comment by Zunon** [comment]
@kytrinyx 
I didn't mean 'how to use the CLI to submit code?'
I meant 'where can i put my .class or .java file so it can be checked by gradle using the gradle tests'

**Comment by kytrinyx** [comment]
Oh, sorry, I misunderstood. I believe that the file needs to go into `src/main/java/`

**Comment by tejasbubane** [comment]
This should be documented somewhere.

Also, I think README of the first exercise of every language should have instructions on setting up the environment (usually link to help.exercism.io/getting_started_with_<lang>.html should suffice), getting started with `coding` as well as `testing`. Recently I found them in javascript's bob, but not in golang's leap.

**Comment by kytrinyx** [comment]
Agreed.

In each of the language repositories we can optionally put a `SETUP.md` file ([javascript has it](https://github.com/exercism/xjavascript/blob/master/SETUP.md), [go does not](https://github.com/exercism/xgo)). Whatever is in this file will get included into each README for each problem in the track.

I think this would be a good place for this.

**Comment by kytrinyx** [comment]
I've opened issues for each of the language tracks about documenting this sort of thing.
