### ISSUE TITLE
Email Notifications. 

### ISSUE THREAD

**Issue by t0nyshier** [exercism/exercism.io#2203]
I tend to go on the site often enough because it escapes my memory.  I am constantly reading my email.  It would be nice if I can get notifications that someone messaged me about my code and/or the nitpicks I've made.

**Comment by kytrinyx** [comment]
There's a section on the account page that lets you set your email address in order to get notifications. I think you may have discovered this on your own, since you closed this issue :)

**Comment by t0nyshier** [comment]
I thought I closed this issue cause I found it after I typed it.  Sorry.

**Comment by kytrinyx** [comment]
No need to apologize, you did close it. I just wanted to make sure you had found the information, and hadn't closed it by accident.
