### ISSUE TITLE
Markdown renderer misrendering readme's containing code blocks.

### ISSUE THREAD

**Issue by wobh** [exercism/exercism.io#2204]
Example: http://exercism.io/exercises/ruby/leap/readme

I'm pretty sure the problem lies here: 

https://github.com/exercism/exercism.io/blob/0b0b3bfb2ce47e472c9820c4e33d68d029157412/lib/app/helpers/markdown.rb#L11

where the markdown body gets wrapped in markdown code blocks. We could probably just sub in `pre` element there, but it seems to me that the "better" solution would be to wrap it in the views, however the "best" solution might be found in the redcarpet gem--we should be able to make the renderer do this.

**Comment by kytrinyx** [comment]
Yes, I think you're right.

The ternary statement on line 11 doesn't make any sense, because language defaults to an empty string (which is truthy).

**Comment by wobh** [comment]
Hah! I didn't even notice that!
