### ISSUE TITLE
Pagination on history page broken

### ISSUE THREAD

**Issue by alexclarkofficial** [exercism/exercism.io#2205]
The 'Next' button never becomes disabled and the buttons show even if there is no pagination necessary.
http://cl.ly/image/0W3d0A2t1u0Y
http://cl.ly/image/2y462Y363e1a

I can submit a PR with a fix but I'm not sure about testing. Are there integration tests for these things? Does my PR need them?

**Comment by kytrinyx** [comment]
We don't write integration tests for the view, except for the occasional smoke test. No need for that here.

Thanks!
