### ISSUE TITLE
"View All" link in the notifications email

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism.io#2209]
In the email about pending notifications, there are links pointing to submissions of the notifications. I think there should also be a [http://exercism.io/notifications](http://exercism.io/notifications) link somewhere so that all notifications can be viewed directly.

**Comment by kytrinyx** [comment]
Good call, that would be very helpful.

**Comment by kytrinyx** [comment]
The notification email lives in `lib/services/notification_message.rb` and `lib/services/email/notifications.erb`/`lib/services/email/notifications.html.erb`.
