### ISSUE TITLE
Not sure how to install to path?

### ISSUE THREAD

**Issue by oluoluoxenfree** [exercism/exercism.io#2210]
Read this http://help.exercism.io/understanding-path.html still not completely sure what I'd have to do in linux as I assume one of the PATHs written is a placeholder?

Thanks for any advice!

**Comment by kytrinyx** [comment]
The most important thing is that you need to add the location of the `exercism` binary into your path.

Assuming that the binary is at `~/bin/exercism`, this line will accomplish that:

```
export PATH=~/bin:$PATH
```

In order to not have to type this every time you open a new shell window, it's common to write that into your shell configuration (e.g. `.bashrc`, or `.bash_profile`, or `.zshrc`, or similar).

Let me know if you're still confused, I'll try explaining in a different way.

**Comment by oluoluoxenfree** [comment]
I think I've actually gotten stuck before my question implies, I've downloaded the tar ball and gotten an executable that doesn't execute on clicking, is that what I should be moving to path?

I didn't understand much of what you wrote, but I'll google some terms and come back to you.

I assume the shell configuration is written in a hidden file?

**Comment by kytrinyx** [comment]
Ah, yeah, that makes sense. The binary doesn't work by clicking, it's one of those run-on-the-command-line things.

Here are the steps you need:

Make sure that you have a ~/bin directory:

```bash
mkdir -p ~/bin
```

Then move the exercism binary that you got out of the tarball into the `~/bin` directory. I don't know where the binary is on your system right now, but let's pretend it's in `~/Desktop/exercism`:

```bash
mv ~/Desktop/exercism ~/bin/
```

> I assume the shell configuration is written in a hidden file?

Yeah, usually in your home directory. See what you can find with `ls -a | grep "^\."`

There's a video that shows the install process for mac, which is similar enough to linux that it would probably help: https://www.youtube.com/watch?v=TCT4eHGwfaE

**Comment by oluoluoxenfree** [comment]
Thanks the video really helped (as well as explainshell.com, ha ha), thank you.

**Comment by kytrinyx** [comment]
explainshell.com is great :)

**Comment by gitgis42o** [comment]
I set up the bin folder. After reloading the session I still get the result:

"me >>>exercism -v
-bash: /Users/me/bin/exercism: cannot execute binary file"

I've navigated to the bin folder through the command line and exercism is there. I'm not quite sure what error couldn't have occurred. Any help? Searches lead me to a thread on here that doesn't address the error (or at least I haven't found it). 

Thank you!

**Comment by kotp** [comment]
`chmod +x ~/bin/exercism` may be the thing you need to do...

**Comment by kytrinyx** [comment]
@gitgis42o What operating system do you use? How did you download the executable?

**Comment by gitgis42o** [comment]
Katrina,

I use OS X El Capitan on my Mac. I downloaded the latest release via Github. That's when I moved the executable into the newly created bin folder.

**Comment by kytrinyx** [comment]
@gitgis42o Which one did you download? Would you try with this one just to be sure? https://github.com/exercism/cli/releases/download/v2.2.6/exercism-mac-64bit.tgz

**Comment by gitgis42o** [comment]
I ended up searching around long enough to find something that worked. I believe the file I downloaded was correct. 

I ended up using the commands 
  $ curl -O https://raw.githubusercontent.com/exercism/cli-www/master/public/install
  $ chmod +x install
  $ ./install

from http://cli.exercism.io/

I just submitted my hello_world.py! 

Thank you for writing this stuff. I'm happy to finally get this going after having it on the docket for so long.

**Comment by kytrinyx** [comment]
Yay! So glad you got it sorted, and so sorry that it was so painful getting started.

**Comment by iHiD** [comment]
@leorawe FYI. This discussion is two years old and that repository (and probably scripts) are deprecated and probably don't work. The [walkthrough on the exercism website](https://exercism.io/cli-walkthrough) has instructions both with and without Brew.
