### ISSUE TITLE
$ export in terminal after install

### ISSUE THREAD

**Issue by SoxFace** [exercism/exercism.io#2211]
Hi there, 

I just followed your video (which is super helpful, thank you) to install the cli on a MAC.

But now my terminal reads "$ export" and I don't know a) what this means and b) how to get back to just $. Any ideas?

**** Debug Information ****
Exercism CLI Version: 1.9.2
OS/Architecture: darwin/amd64
Home Dir: /Users/sonyacorcoran
Config file: /Users/sonyacorcoran/.exercism.json
API Key: ###############################
API: http://exercism.io
Exercises Directory: /Users/sonyacorcoran/exercism

Thanks again, really looking forward to working through these problems.

**Comment by kytrinyx** [comment]
It sounds like perhaps you changed your PS1.

What does the output of `tail -n 5 ~/.bash_profile` give you?

**Comment by SoxFace** [comment]
Thanks for he response Katrina, 

That outputs: 

tail: illegal offset -- 5-/.bash_profile

**Comment by SoxFace** [comment]
Thanks for the hint that it was the PS1 - I'm back to normal now after running:

export PS1="\W: "

**Comment by kytrinyx** [comment]
Ah, sorry -- my bash config is so long that running `cat ~/.bash_profile` would be unhelpful. I should have offered you the `cat` suggestion.

Glad you got it sorted!

**Comment by SoxFace** [comment]
Yeah - I don't know how I did what I did but I followed this post to reedit and save my bash_profile so it's all back on track. Thank you so much for the support and response, can't wait to get stuck into the exercises.
