### ISSUE TITLE
.exercism.json should be stored in $XDG_CONFIG_HOME on linux systems.

### ISSUE THREAD

**Issue by JulianAndrews** [exercism/exercism.io#2212]
The [XDG specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) is widely supported by linux systems. Storing config files directly in the home directory creates unecessary clutter.

I'm sure there's a ruby gem for xdg support to handle most the work.

**Comment by kytrinyx** [comment]
The exercism client is in Go, not ruby. It's trivial to support, I'll open an issue.

**Comment by kytrinyx** [comment]
Ok, I'm going to close this as a duplicate, since https://github.com/exercism/cli/issues/161 is where the action will be.

Thanks for bringing it up.
