### ISSUE TITLE
Add link to contributing guide in dashboard

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2213]
(the problems contributing guide) along with a call to action to help submit more problems in languages that you've done.

**Comment by tejasbubane** [comment]
Where on dashboard do you think would be a proper place to add this?

**Comment by kytrinyx** [comment]
At the moment? Anywhere :) The dashboard is such a mess, than it seems like anything would be better than it is.

**Comment by kytrinyx** [comment]
Let's put it at the bottom.

We'll need a helpful call to action / some good link copy. Suggestions?

**Comment by tejasbubane** [comment]
Are we talking about this? https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

**Comment by kytrinyx** [comment]
Good question, as there are two. Yes, I think that one would be good to link to.
