### ISSUE TITLE
⌘+Enter double submits comment (doesn't disable 'submit' button)

### ISSUE THREAD

**Issue by trayo** [exercism/exercism.io#2221]
I seem to have this problem more often when I comment on my own exercism than I've commenting on other users exercisms.

![image](https://cloud.githubusercontent.com/assets/6809782/6320650/ac22de0c-baa0-11e4-91e3-165a930ca43c.png)

Manually deleting the duplicate will remove the duplicate and leave the extra.

![image](https://cloud.githubusercontent.com/assets/6809782/6320656/d79b9d12-baa0-11e4-8fd5-bebc9a0a4aee.png)

**Comment by kytrinyx** [comment]
Weird, thanks for reporting this. I've not experienced it myself. Have you noticed a pattern in terms of when you see this?

**Comment by trayo** [comment]
It appears to be sporadic. I'd blame my internet, but I'm on a  < 20mbps connection. I noticed issue #2208 on improving performance and it might be solved as a result of solving that issue. I'll post again the next time it happens and leave both so they can be confirmed in the database.

**Comment by trayo** [comment]
I just had a comment double post again. It was when I posted to my own exercism, as I mentioned before. It happened at about 8:07pm. When I posted the comment it took ~10 seconds to post and update, which is unusually long.

**Comment by trayo** [comment]
Ah! I found the real issue. When posting a comment, I am very used to using ⌘+Enter to send the form. It turns out that when the comment form is sent this way, it doesn't disable the submit button and a user is able to click submit again before the page updates.

**Comment by kytrinyx** [comment]
Aaah! Great find, thank you!

I'm editing the issue title to reflect this, and it should be fairly straight-forward to fix.

**Comment by kytrinyx** [comment]
Deploying now. Thanks!

**Comment by trayo** [comment]
Nice! Glad to help out! Thank you!
