### ISSUE TITLE
Iterations and Nits on Account page confusing

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism.io#2226]
On Accounts page under Exercises section, it was slightly confusing for me to see 0 Nits on many of my exercises which have Nits.

After examining the code in `lib/app/views/account/show.erb` I can see that the information is for current iteration only.

So maybe we can change the name of the column `Iterations` to `Current Iteration` so that `Current Iteration` and `Nits` go along to tell that the information is for current iteration only as opposed to `Iterations` which means total iterations on the exercise.

**Comment by kytrinyx** [comment]
Yeah, good call, I think changing the column names makes a lot of sense. Want to have a go at it?

**Comment by tejasbubane** [comment]
@kytrinyx Done.

**Comment by kytrinyx** [comment]
Thanks so much!
