### ISSUE TITLE
Sorry—we can't figure out who you are. Problem 

### ISSUE THREAD

**Issue by JMince** [exercism/exercism.io#2229]
Hello, I just installed exercism, but can't get access to the files I want. I tried resetting the api key as well as restarting the console etc..any help would be appreciated!

➜  ~  exercism -v
exercism version 1.9.2
➜  ~  exercism fetch ruby
2015/02/27 14:27:45 unable to fetch problems (HTTP: 400) - Sorry—we can't figure out who you are. Double-check your API key in your exercism.io account page.
➜  ~  exercism debug

**** Debug Information ****
Exercism CLI Version: 1.9.2
OS/Architecture: darwin/amd64
Home Dir: /Users/jeffreymince
Config file: /Users/jeffreymince/.exercism.json
API Key: YOUR_API_KEY=my_api_key_was_here
API: http://exercism.io
Exercises Directory: /Users/jeffreymince/exercism

**Comment by kytrinyx** [comment]
Did you figure this out? When you say `exercism configure` you need to not include the `YOUR_API_KEY=` part:

```
exercism configure --key=8857d82dd5544f99b40dd64b5cc39342
```

**Comment by JMince** [comment]
Thank you - I sorted this out. I appreciate your reply!

**Comment by kytrinyx** [comment]
Cool, glad you figured it out.
