### ISSUE TITLE
CLI restore downloads nested folders

### ISSUE THREAD

**Issue by KaoruDev** [exercism/exercism.io#2232]
I was trying to replicate 2162 by deleting all my ruby folders and running `exercism restore`
Exercise were being downloaded just fine but I noticed it had an extra sub folder under it with duplicate files. i.e:

```
- exercism/
  - ruby/
    - hamming/
      - hamming_test.rb
      - ruby/
        - hamming_test.rb
```

Happened with gigasecond and rna-transcription as well

**Comment by Tonkpils** [comment]
We have some issues to tackle this https://github.com/exercism/cli/issues/152 https://github.com/exercism/exercism.io/issues/2174. Check those out for more info

**Comment by kytrinyx** [comment]
Thanks, @KaoruDev! If you have more details that you want to add later, would you add them to https://github.com/exercism/cli/issues/152? I'm going to close this as a duplicate.

**Comment by KaoruDev** [comment]
ah nice, i should have looked at the cli repo :+1:

**Comment by kytrinyx** [comment]
There are a lot of repos :)
