### ISSUE TITLE
500s from skip API endpoint. 

### ISSUE THREAD

**Issue by Tonkpils** [exercism/exercism.io#2238]
I was wondering if the PR from #2233 had been deployed? 

When I run the app locally and curl the following

```sh
curl localhost:5000/api/v1/iterations/foo/ski/skip\?key\=ywj769 -X POST
{"error":"Exercise 'ski' in 'foo' has already been skipped."}
```

However, against exercism.io host I get Internal Server Errors.

**Comment by kytrinyx** [comment]
Let me check. I would have thought so, but the past week has been particularly unmanageable.

**Comment by kytrinyx** [comment]
Nope, not deployed. Doing so now.

**Comment by kytrinyx** [comment]
Deployed. Thanks for catching that.
