### ISSUE TITLE
Skipping problems that don't exist

### ISSUE THREAD

**Issue by Tonkpils** [exercism/exercism.io#2239]
Currently the `skip` API endpoint allows for skipping problems that don't exist. This may be an non-issue and if it is this can be closed. Just thought I'd bring this up in case it's a bug.  

e.g.

```sh
$ exercism skip foo bars
2015/03/14 20:36:24 http://exercism.io/api/v1/iterations/foo/bars/skip?key=<api_key>
Exercise skipped.
```

**Comment by kytrinyx** [comment]
It would probably be useful to let people know that it's not a real exercise, in case they made a typo and want to try again.

Let's treat it as a bug :)

The fix would have to be in the api endpoint here in the exercism/exercism.io repository:

```
lib/api/routes/iterations.rb:10:      post '/iterations/:language/:slug/skip' do |language, slug|
```

**Comment by Adam89** [comment]
I'll see if I can get around to this sometime this week

**Comment by mtakac** [comment]
This should be fixed now. See #2282.

**Comment by kytrinyx** [comment]
Yepp. Thanks!
