### ISSUE TITLE
Reinstalling exercism don't bring code for exercises already done.

### ISSUE THREAD

**Issue by jonduarte** [exercism/exercism.io#2240]
Hi, first of all I couldn't find any issue related to this so if it already exists please close this issue.

The problem is the following:

I've reinstalled exercism recently and I realized that all the exercises I've solved didn't come with its solution when I performed fetch.

Am I missing something ? 

Thank you.

**Comment by kytrinyx** [comment]
`fetch` will only return the current exercises. There's a `restore` command that should give you all the exercises that you've solved--does that work?

**Comment by jonduarte** [comment]
Yes, that was exactly what I wanted. Thank you.

**Comment by kytrinyx** [comment]
Sweet! Is there some way I could have documented this better so that you would have found it more easily?

**Comment by jonduarte** [comment]
In my opinion you could have some kind of "Quick Start page" which covers some basic flows.
