### ISSUE TITLE
Syntax Highlighting - PL/SQL

### ISSUE THREAD

**Issue by chezwicker** [exercism/exercism.io#2241]
We now have syntax highlighting for PL/SQL in linguist (see https://github.com/github/linguist/commit/9151e7066aee99b2e5528688219fd8c311d4e0bb and https://github.com/github/linguist/commit/c9a1159a2ef57ef5adb12c70ee3c9e157e4111a9), but it seems this does not show on exercism. Anything I need to do to get this working?

**Comment by kytrinyx** [comment]
Linguist might be pinned to a specific version, let me run it against master and see if that helps.

**Comment by kytrinyx** [comment]
Wait, we're not using linguist for syntax highlighting on exercism, we're using https://github.com/jneen/rouge

**Comment by chezwicker** [comment]
Oh, I thought you had pointed me towards linguist once... Ok, will have a look at rouge.
