### ISSUE TITLE
Notification email can duplicate a link in the "Spare a few minutes?" section

### ISSUE THREAD

**Issue by brockboland** [exercism/exercism.io#2242]
Low priority. 

I got a notification about new code (I think because I'd previously reviewed their first submission for the exercise?), and the same code submission was highlighted in the "Spare a few minutes?" section below that. Ideally, that would be omitted or would reach further back in time for an older submission.

![exercism io you have 2 notifications - brock brockboland com - brockboland com mail](https://cloud.githubusercontent.com/assets/163838/6680723/fb49607a-cc28-11e4-82e5-0c61a8a484b3.png)

**Comment by kytrinyx** [comment]
Yepp, that's a bug (and yepp, it's because you commented. Give us an inch, we'll take a mile. Or something :))

**Comment by kytrinyx** [comment]
For reference, this code lives in `lib/services/notification_message.rb` and there are tests in `test/services/notification_message_test.rb`.

The two methods in question are `notifications` and `pending_submissions`. I'll warn you all right off the bat that the `Workload` thing is an overly complicated mess.

I'm looking to replace all of that with some proper notification/activity stream/subscription goodness, but it's not going to happen in the next month.

**Comment by brockboland** [comment]
I have many exercisms to do before I know enough ruby to take a swing at that.

**Comment by kytrinyx** [comment]
Yeah "good first patch" does assume familiarity with the language :)
