### ISSUE TITLE
Feature: Individual mentors

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2248]
It would be useful to have a feature that lets one individual (mentor) be notified any time another individual submits some code, whether or not the mentor has done that problem or not.

It would require a two-way handshake (both parties would have to agree to the relationship).

**Comment by mattr-** [comment]
:sparkles: :+1:

**Comment by mattr-** [comment]
I love this idea. :smiley:

**Comment by anomico** [comment]
Would love seeing this idea implemented. :+1:

**Comment by jwood803** [comment]
Indeed! I'll definitely be among the first to sign up as a mentor.

**Comment by kytrinyx** [comment]
Excellent, there's a lot of interest for this feature. Let's make it happen.

Eventually this will be much cleaner with the https://github.com/exercism/exercism.io/issues/1899 which is pretty much next on the list of big changes, but I think that we can have a hacked together version of this with very little effort.

There are lots of niceties that would be great to have, but I think that the very first version should be as simple as humanly possible.

In the first version, let's make the assumption that both parties have already logged in via github, and therefore have user accounts on exercism. In the future we'll want to have fancy invitations via email, but this requires an alternate sign-up path, or at least an enhanced one.

We need to

1. track mentor/mentee relationships.
1. implement the invitation/request and acceptance
1. provide notifications when a mentee submits code
1. provide a list to access all pending mentee activity

I think (1) can be a straight-forward table: mentor_id, mentee_id, maybe a couple of other fields if we see that it's necessary.

(2) should probably be tracked in a separate table since it doesn't have to be accessed beyond just the actual invitation/acceptance. Something like `mentor_invited_at`, `mentee_invited_at`, `mentor_accepted_at`, `mentee_accepted_at`. Either the mentor or the mentee can initiate the request. This could add a system notification, a button on the profile, and trigger an email (if you have an address in the system).

For (3) we'll need to add some processing to the notifications code. Again, with the activity stream this would be moved into a separate system to be handled asynchronously.

Lastly, with (4) I think we can put an entry in the "nitpick" menu as well as something on the user's profile.

If anyone can come up with a way to simplify this for the first version, that would be great.

**Comment by kytrinyx** [comment]
We've not made any progress on this, unfortunately.

There is a workaround: create a mentorship team with the mentor and mentee. That will give the mentor access to the mentee's solutions.

Since we have a workaround I'm going to go ahead and close this.
