### ISSUE TITLE
Describe focus/purpose of exercism

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2253]
My idea of exercism has settled quite a bit compared to what I thought it was going to be at the start.

It would be very helpful to write something both in the About page and the Contributing Guide about the focus of the site and the purpose of it.

This would make it easier to close issues that are making suggestions that aren't necessarily relevant to the core purpose of the site.

The two ideas that I go back to are _conversation_ and _deep practice_. The idea of deep practice came out of [The 5 Elements of Effective Thinking](http://www.amazon.com/The-Five-Elements-Effective-Thinking/dp/1491531304), and I told a story that I got from there in my Overkill talk at RubyConf Portugal https://www.youtube.com/watch?v=GWEEPt8VvmU

Here's some "braindump-y" stuff that I've written about how I think about exercism:

----

At the most basic level, the product is about skill development. It was not
initially meant to be a tool to teach beginners to learn to program, though
beginners are definitely using it.

When people explain exercism, they say it's about practice exercises /
challenges, and throw in the conversation part as a bonus. This isn't how I
think of it. The critique/conversation is the interesting and meaningful part
of the site. It's both where the site is unique compared to other solutions,
and where the real learning/discovery happens.

In software development as a culture and industry, we tend to be terrible at
talking about code constructively. We are not taught how to give useful,
critical, kind feedback.

We tend to not have thoughtful conversations about choices, trade-offs,
idioms, style, and "best" practices (for any value of "best"). We are prone to
leap to absolutes, or to just ignore the detailed thoughtful part and blame
our feelings. "I like it better that way".

We also don't learn how to accept feedback gracefully with an attitude of
learning and curiosity.

Having these conversations forces people to articulate their vague ideas and
feelings and give them thought and reason. It turns out that looking at a
piece of code and having a gut reaction that something is "off" is completely
legitimate… but not very useful.

The useful thing is trying to identify what it is about that code that gives
you that gut feeling. And then, having articulated those ideas, having someone
push back or ask probing questions leads to insights.

I have had insights after months of giving feedback to the same exercise.
Every once in a while something crystalises into a thing that I can articulate
in a few simple sentences, where before I was struggling to even put my finger
on what was bugging me.

Kate Heddleston has two articles that are possible the best that I've read
when it comes to arguments, criticism, and feedback:

* https://kateheddleston.com/blog/argument-cultures-and-unregulated-aggression
* https://kateheddleston.com/blog/criticism-and-ineffective-feedback

----

**Comment by outkaj** [comment]
Some thoughts for the About page (may be wordy or unclear? should the conversation component come up earlier?):

Exercism is a place where programmers of all skill levels can share and discuss their code. Exercism consists of a command-line client which, when downloaded to your system, will enable you to work through a small, carefully-selected set of programming exercises one by one. The Exercism client is cross-platform and support multiple languages.  

What makes Exercism different from other websites which contain programming exercises is our focus on code review, known as nitpicking. Once your code passes the tests and you have posted it on our website, other developers will offer suggestions to help you improve your code. Once you become familiar with the nitpicking process, you also have the chance to give feedback to your peers. [These careful conversations will make you a better programmer, a more thoughtful critic, and a more receptive listener.]

**Comment by kytrinyx** [comment]
> should the conversation component come up earlier

Yeah, I think you're right. That is the key aspect of exercism, we should lead with that.

**Comment by pminten** [comment]
Just brainstorming, but maybe what would help are some succinct points, agile manifesto style.

* Discussions with peers over one-way lectures.
* One-on-one interaction over many-to-one content.
* Students-as-teachers over fixed roles.
* Repeated improvement over write and forget.
* Strife for perfection over good enough.
* Collaboration over competition.
* Feedback over criticism.
* Curious humbleness over all-knowing arrogance.

Can't say I'm fully happy with this phrasing and it feels like there's some redundancy here, but it feels like this form helps in thinking about core values.

**Comment by kytrinyx** [comment]
@pminten This is interesting, and I think it does help focus on the core values.

**Comment by kytrinyx** [comment]
I did a bunch of work on this over the past 7 or 8 months, and ended up with a new homepage because of it. So far I think it's working.

My solution was to focus on figuring out who the different groups who use exercism are (newbies, polyglots, artisans) and then figure out what specific pains Exercism addresses for each group.
