### ISSUE TITLE
First impression / Getting Started

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2254]
It's still very difficult to understand

a) what exercism is about
b) how it works, and
c) how to get started

Currently you only really get going properly if you have a friend who explains why it's useful and how to go about using it.

I'd like to start collecting some ideas about how to fix this.

Where do we explain? What do we explain?

How much information you need to get started depends on how much experience you have with programming (in general) and perhaps also unit testing.

There are videos we can point people to in order to explain concepts (Sandi Metz' "Magic Tricks of Testing" talk comes to mind).

Also, it might be helpful to have an interactive tutorial.

Any ideas for making this happen are welcome.

**Comment by kytrinyx** [comment]
Useful resources:

* Overkill https://www.youtube.com/watch?v=GWEEPt8VvmU
  (video) This talk basically explains the essence of what exercism is about.
* Nitpicks and Devils http://www.codenewbie.org/podcast/nitpicks-and-devils
  (audio) The CodeNewbie Podcast episode about exercism
* The Magic Tricks of Testing https://www.youtube.com/watch?v=URSWYvyc42M
  (video) This talk lays out the basics of unit testing in a beautiful and understandable way.

**Comment by jwood803** [comment]
This may have already been covered in a much earlier discussion, but perhaps something to help folks who aren't used to the command line feel more comfortable with it?

**Comment by kytrinyx** [comment]
You mean like a tutorial? Or more like a web interface for submitting code?

**Comment by jwood803** [comment]
More of a tutorial since it's always handy to get familiar with the command line, I think. :}

**Comment by kytrinyx** [comment]
Yeah, I wonder what's available these days. I'll ask the #codenewbie folks.

**Comment by kytrinyx** [comment]
Someone suggested https://github.com/veltman/clmystery -- a command-line murder mystery. Now I have to go try it out :)

**Comment by jwood803** [comment]
Oh nice! Should be interesting and helpful, I'm sure.

**Comment by tejasbubane** [comment]
Earlier I had made a suggestion of having `getting started` in every language in https://github.com/exercism/exercism.io/issues/2198. The `SETUP.md` solution is good but what I had in mind was a more elaborate help. And I just came across [Getting started file in ruby's hamming](https://github.com/exercism/xruby/blob/master/hamming/GETTING_STARTED.md). 
Almost everyone needs a hand-holding walk around the environment and test cases. That `getting_started` file brilliantly solves the purpose. What it has done is that it has made me very comfortable with tests and the first thing I do after fetching a new problem is to run the tests and then write code one small piece at a time just to pass one test.

Though TDD might not be the primary goal of exercism, it is good to get the habit along the way. Hence I feel that the first exercise of every language should have one such `getting_started` file to help people actually get started the right way.

**Comment by kytrinyx** [comment]
I think you're absolutely right that we should have some way of providing a really detailed guided tour for the first exercise in each language... or even a "hello world" type tutorial / simulation that comes before the first exercise just to get warmed up to the process.

**Comment by rubymorillo** [comment]
Hey @kytrinyx once the roadmap has been outlined, I'm more than happy to assist writing the copy. My bread and butter is content writing!

**Comment by kytrinyx** [comment]
@rubymorrillo this is great news. I have a ton of problems with confusing copy and missing copy on the site.

**Comment by ErikSchierboom** [comment]
@kytrinyx in passing mentioned "[...] like a web interface for submitting code?". I personally think that's a great idea. The CLI tooling is great, but it is a barrier for some people I feel. Having a simple submit form (perhaps with drag-and-drop of files) to submit code would help.

**Comment by kytrinyx** [comment]
@ErikSchierboom I agree. I've come to the conclusion that there are two distinct onboarding problems:

1. In general it's hard to know what exercism is about and how it works and how to get started (what prompted me to open this ticket), and
2. For beginners, the barrier to entry is high because of the tooling itself.

**Comment by jwood803** [comment]
If we can get to the point of something like CodeWars, then we'll be great! How to get there, though, I have no idea. :p

**Comment by kytrinyx** [comment]
I've opened two new topics to explore the two high-level ideas that this topic covers:

1. Lowering the barrier to entry: making it easier to get started for newer programmers
2. Understanding what exercism is about and how it works

There are a number of good suggestions that have come up, and I'm trying to summarize them in those two topics.

Thanks for discussing!
