### ISSUE TITLE
Suggestion: Change or eliminate "Get Started with Ruby" on main page

### ISSUE THREAD

**Issue by outkaj** [exercism/exercism.io#2255]
This is a small note. 

I would suggest either eliminating the "Get Started with Ruby" link on the main page or changing it to a more general "Get Started". As it stands, it is a bit confusing, since it makes the site appear to have a more Ruby-oriented focus than is actually true. My guess is it's a holdover from the initial version of the site, since Ruby was the first language used?

**Comment by kytrinyx** [comment]
Oh, wow, I completely missed that. Yes, we should absolutely not have "get started with ruby" on the homepage!
