### ISSUE TITLE
Invisible text on threads

### ISSUE THREAD

**Issue by rstacruz** [exercism/exercism.io#2256]
![pasted_image_3_23_15__10_03_am](https://cloud.githubusercontent.com/assets/74385/6772966/e883139e-d143-11e4-8aae-ab5ec67068f5.png)

**Comment by kytrinyx** [comment]
Where are you seeing this? Is it on all pages?

**Comment by kytrinyx** [comment]
Oh, found it: http://exercism.io/conversations/1

**Comment by rstacruz** [comment]
yep! that's the page. nice work by the way!

**Comment by kytrinyx** [comment]
Thanks! It looks like a fix is on it's way.
