### ISSUE TITLE
Beta banner sometimes partially obscures the nitpick text button

### ISSUE THREAD

**Issue by pminten** [exercism/exercism.io#2259]
I tend to zoom in on websites and at the maximum zoom level in chrome before the submission and nitpick columns are put after each other the beta banner obscures the nitpick button and sometimes part of the nitpick text field as well. It doesn't help that the beta banner is increased in size when zooming as well.

**Comment by kytrinyx** [comment]
I wonder if there's a way to keep the beta banner small when zooming. Or to remove it when zooming; that could also work.

Or perhaps it would be enough to move it to the left-hand corner. There's less going on down there.

**Comment by mixolidia** [comment]
Was thinking of getting the beta banner to stick to the bottom of the page or the top left. I think we talked about this before.

Reading this I think making it smaller and putting it on the top left would be a good idea. What do you think?

**Comment by kytrinyx** [comment]
How about just deleting it? We don't make any promises, we can say beta in small in the footer.

**Comment by mixolidia** [comment]
Yes, good idea.

**Comment by mixolidia** [comment]
Hi @kytrinyx 
Done, in pull request [#2552](https://github.com/exercism/exercism.io/pull/2552"PR#2552").

cc: @sguermond
