### ISSUE TITLE
[question] Could codenvy work for simpler onboarding?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2261]
Right now exercism is fairly straight forward to use if you're comfortable on the command line and already have a programming environment. Download the binary, stick it in your path, and you're good to go.

If you're a newbie programmer, good luck figuring out what PATH is.

I've been thinking of ways in which we could make it easier to get started. One way would be to do what Code School and several others do, and build out sandboxed environments with an in-browser editor (ish, because those editors aren't generally particularly robust), and run the tests for them.

That's a lot of work, and we have 20 different languages.

[codenvy](https://codenvy.com) might be a way around this. They have a cloud-based IDE, and you can configure skeleton projects that people can open a copy of with a single click.

I'm wondering if it would be possible to have the following workflow:

1. User clicks a link that passes their exercism API key as a query parameter.
2. This opens up a fresh ruby environment with the exercism binary installed and configured (using the API key).
3. They can now say "exercism fetch ruby" to get the first ruby exercise.
4. They can open the files (README, test suite, maybe a skeleton file for the solution) in the editor, and
5. They can run the tests. That could be a terminal window where they type the command (`ruby hamming_test.rb` or whatever), or some button that runs a build script of sorts. I don't actually care how they run the test as long as we make it easy for them to do.

They would absolutely need to see the error messages, because that is what tells them what code to write.

I saw a demo that used Java, and it took several seconds to build the project. That could be a Java thing (I've never written production code in Java, so I don't know). I think it would be fine if it takes several seconds the first time, just to boot up some sort of environment, but the test suites would really need to be sub-second like they are in a local dev environment, otherwise I don't think that the trade-off is worth it.

So my question is: Does anyone know if codenvy is a good fit for this use case? I can't quite tell from the demos on the site whether or not this would even be possible.

**Comment by lynnlangit** [comment]
Sharing the Dockerfile Jim wrote:

FROM ubuntu:14.10
WORKDIR /root
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y curl vim 

# Exercism
RUN curl -O http://cli.exercism.io/install
RUN chmod +x install
RUN DIR=/usr/local/bin ./install
RUN /usr/local/bin/exercism configure --dir=/mnt --key=*************************

# Python
RUN apt-get install -y python
RUN curl -O https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py
RUN pip install pylint
RUN pip install autopep8

# sudo docker run -t -i -v /vagrant:/mnt james/exercism /bin/bash
# the command directly above this comment runs the docker image, and mounts a local
# folder into the image.  To get this to run on windows, its double-virtualized, first in Vagrant, 
# then docker.

# for code envy, you will probably want to see if they have an appropriate base image besides 
# ubuntu

**Comment by jwood803** [comment]
Sounds like it would be beneficial, to someone starting out or even just as a demo. But ya, I'm unsure on how or if we can get it to work with our stuff.

**Comment by kytrinyx** [comment]
After I wrote this one of the codenvy peeps basically said "yepp, this can be done now". The only issue is about having fast tests, but they're actually re-engineering part of their stack to make fast tests possible.

I'm going to try to figure out how to get a demo working for Ruby, then we can figure out which languages this makes sense for (maybe all of them? I kind of imagine that if you're writing lisp or haskell it's going to be easier for you to just open your usual programming environment).

**Comment by jwood803** [comment]
Nice! I didn't dig deep with it to see if any .NET stuff can be run with it though. My initial thoughts are that it may not be.

-----Original Message-----

**Comment by kytrinyx** [comment]
I actually think that their whole team is primarily .NET peeps.

**Comment by jwood803** [comment]
I don't see anything that explicitly says they can do it, but then again nothing that says they can't. :p

**Comment by eivantsov** [comment]
Looks like this is possible - http://blogs.msdn.com/b/webdev/archive/2015/01/14/running-asp-net-5-applications-in-linux-containers-with-docker.aspx

We haven't given it a shot yet though

**Comment by masters3d** [comment]
Too bad there is not Objective-C or Swift support yet. https://groups.google.com/a/codenvy.com/forum/#!msg/codenvy/6D8LAFbuM54/yhHxIyrn4yMJ

**Comment by kytrinyx** [comment]
It looks like you can do custom builds, though... so we might be able to do it.

**Comment by kytrinyx** [comment]
OK, cool, so it looks like this is definitely a possibility. I'll get help from a couple of people to do a prototype/experiment.

Thanks all!

**Comment by bane73** [comment]
Has there been any traction on this front?  I'm a Java developer at my local university... use 3 different boxes and move around a fair amount... would LOVE to have a way to do Exercism in the cloud so I can easily play with it from anywhere that I get 5 minutes (including my phone!).

**Comment by kytrinyx** [comment]
@bane73 This is now on the table. /cc @iHiD

**Comment by iHiD** [comment]
Yeah, definitely. It's going to be July onwards, and it might take a little while to roll out for every language, but I think it should definitely be something we prioritise. I guess we'll have some sort of general roadmap together in the next month or two where we'll work it out timescales properly, and then look at what the best road for implementation is then?

**Comment by kytrinyx** [comment]
@iHiD Yeah, that sounds about right.

**Comment by lynnlangit** [comment]
I've done work with Codenvy for #TKPJava - would be interested in working on this for #Exercism.io

**Comment by bane73** [comment]
Oh this is great!  :)

If there's a gap for Java webdev, or documentation, add me to the list of potential help.  I'm not up to speed on the codebase and I haven't done much with codeenvy but I'm reasonably seasoned with Java full stack stuff.

Otherwise I'll just wait in anticipation.

**Comment by TylerJewell** [comment]
Codenvy founder here - we can help you get integrated properly.  We now have about 500,000 users and significant support for Java and advanced enterprise development scenarios - so we can support the scenarios that don't need the same sophistication.

**Comment by iHiD** [comment]
Awesome! Thanks :)  We're a while off this yet, but will definitely come pestering when we get there!

**Comment by bmicklea** [comment]
When you're ready @iHiD ping me and I'll hook you up with what you need to get this done.
