### ISSUE TITLE
Encouraging revisiting exercises

### ISSUE THREAD

**Issue by pminten** [exercism/exercism.io#2262]
Currently tracks feel linear, you complete an exercise and move on to the next one. But there's value in going back to an old exercise after you've learned new techniques and doing it again. It is often both humbling and encouraging to see old code and compare it to how you would now do it. Humbling, because it makes you realize that not so long ago you were a beginner too, and encouraging, because it shows you how much you've grown.

I'd like to raise a question, how can we encourage people to go back and revisit old exercises?

**Comment by kytrinyx** [comment]
Yes, this would definitely be useful to encourage.

I wonder if this is something we can put on the dashboard. The dashboard needs to be completely overhauled--at the moment it's just a couple of arbitrary things that feel more like annoying placeholders.

**Comment by pminten** [comment]
Thinking action oriented for a moment a dashboard would be a good place for that. I could imagine one with a bunch of primary activities like:

* Respond to new comments/iterations on submissions you've been active on
* Revisit your old exercises
* Nitpick other people's exercises
* Look at new nits

**Comment by kytrinyx** [comment]
Yes, another thing that I think could be interesting is to pull out specific stats that are relevant to you. If you've been doing a lot of elixir, it might be interesting to know that 281 other people have been active on the elixir track, and that your latest solution is on a problem where people submit, on average, 7 iterations, or perhaps that there's currently an average wait time of 12 hours (or 5 days) before people get their first nitpick.

**Comment by pminten** [comment]
That would work best if there's some kind of "I'm interested in this exercise in particular" button so that people can take action to receive notifications about submissions there. Otherwise the information is useful but it would take too much effort to act on it.

**Comment by kytrinyx** [comment]
My two current projects are

1. Figure out how to manage the roadmap so that we can make progress, and
2. Implement an activity stream feature with granular subscriptions/notifications  (#1899)

(2) would make it possible to provide relevant stats.

**Comment by kytrinyx** [comment]
I'm going to close this in favor of a couple of other open discussions:

- https://github.com/exercism/discussions/issues/33 (for improving the dashboard)
- https://github.com/exercism/discussions/issues/91 (granular notifications / flexible subscriptions)

In particular I think that we could use the dashboard to occasionally suggest that you revisit an exercise.
