### ISSUE TITLE
Different feedback types

### ISSUE THREAD

**Issue by pminten** [exercism/exercism.io#2263]
Just brainstorming here. There are, in my mind, three kinds of feedback:
- Feedback about the submission. This is the usual one.
- Feedback about feedback. For example a comment "Excellent nit. I like you don't just say that it's good but also what parts make it good.".
- Feedback about an exercise. For example "This exercise is somewhat annoying since the lines are so long they don't really fit in the viewbox.".

If we could distinguish these kinds of feedback it would be possible to improve the notifications.

For feedback about feedback the person who's feedback is commented on could receive a special notification.

For feedback about an exercise people who are interested in the quality of a particular exercise could get a notification. As an exercise author I certainly would appreciate it to be notified when someone has a comment about the exercise. That's the best to learn how to improve exercises.

**Comment by kytrinyx** [comment]
This is a very useful distinction. It should be possible to make the user interface such that people don't use the same comment box for different types of feedback.

**Comment by pminten** [comment]
Perhaps you need just two feedback forms, one hidden behind some kind of "give feedback on this exercise" link (or just a checkbox).

The feedback about submission vs feedback about feedback could be done twitter style. If the first word of feedback is an @ reference it's taken as a reply to that particular user. Might be a bit unintuitive though. An alternative would be to have reply buttons with each post so that you get a kind of tree structure.

**Comment by kytrinyx** [comment]
We had a brief experiment with threaded comments and it was very confusing. I wonder if there are any interaction designers who use exercism. I suspect that with the right interface it would be quite intuitive.

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/discussions/issues/34
