### ISSUE TITLE
Could not find command "configure".

### ISSUE THREAD

**Issue by rubymorillo** [exercism/exercism.io#2264]
I followed all of the steps for installing the CLI on Mac OS but when I try to run the "configure" command I get "Could not find command 'configure'" and to double check, running 'exercism' shows me what commands are available and configure isn't listed. How do I get this to work? Thank you!

**Comment by jwood803** [comment]
Was that with `exercism configure`?

**Comment by rubymorillo** [comment]
Yes @jwood803 - I installed the CLI, ran exercism -v to make sure it was installed properly, ran exercism configure --key=YOUR_API_KEY and got the error message.

**Comment by jwood803** [comment]
Windows machine? If so, maybe check your path to see if it includes the folder where the exercism exe is.

**Comment by rubymorillo** [comment]
Nope, Mac @jwood803

**Comment by kytrinyx** [comment]
What is the output of `exercism debug`?

**Comment by rubymorillo** [comment]
Could not find command "debug". @kytrinyx

**Comment by rubymorillo** [comment]
These are the commands that I have access to:

Commands:
  exercism demo            # Fetch first assignment for each language from exercism.io
  exercism fetch           # Fetch current assignment from exercism.io
  exercism help [COMMAND]  # Describe available commands or one specific command
  exercism login           # Save exercism.io api credentials
  exercism logout          # Clear exercism.io api credentials
  exercism open            # Opens exercism.io in your default browser
  exercism peek            # Fetch upcoming assignment from exercism.io
  exercism submit FILE     # Submit code to exercism.io on your current assignment
  exercism unsubmit        # Delete the last submission
  exercism version         # Output current version of gem
  exercism whoami          # Get the github username that you are logged in as

**Comment by kytrinyx** [comment]
What does `which exercism` say?

**Comment by rubymorillo** [comment]
/Users/stephaniemorillo/.rvm/gems/ruby-2.0.0-p247/bin/exercism

**Comment by kytrinyx** [comment]
ooooh!

`gem uninstall exercism`

Then do `which exercism` again.

**Comment by rubymorillo** [comment]
Gotcha! now I get this: /usr/local/bin/exercism

**Comment by kytrinyx** [comment]
yes, that looks much better. Does it have a configure command?

**Comment by rubymorillo** [comment]
it does and I was able to run the command successfully! Thanks so much :)

**Comment by kytrinyx** [comment]
Sweet, glad it got sorted!
