### ISSUE TITLE
using {{blah}} in a test renders as "" in submitted Javascript exercise

### ISSUE THREAD

**Issue by elliotstokes** [exercism/exercism.io#2267]
I had a string

"something something somthing {{replaceVal}}". Works ok in my tests but doesn't render properly. I imagine due to using handlebars or similar in the background.

**Comment by masters3d** [comment]
Do you want to fill this out here?
https://github.com/exercism/xjavascript
Could you also specify the problem name there? Thanks!

**Comment by kytrinyx** [comment]
I think this is a bug here on the exercism.io site, not a problem with the exercise.

I wonder if we can make handlebars ignore anything inside of a <pre> tag, or perhaps we can preprocess code markdown to replace `{` with `&lbrace;` and `}` with `&rbrace;`.

**Comment by kytrinyx** [comment]
I have confirmed the bug. Here are the reproduction steps:

Create a file locally that has something contained in double braces. E.g.:

```ruby
# this is a {{test}}
```

Submit it to exercism.

View on the site.

![screen shot 2015-03-27 at 21 55 50](https://cloud.githubusercontent.com/assets/276834/6879844/39ca0768-d4cc-11e4-8d21-ca14c7c60d60.png)
