### ISSUE TITLE
Recently Viewed page (/looks) has broken links

### ISSUE THREAD

**Issue by monkbroc** [exercism/exercism.io#2274]
Clicking any link to a recently viewed exercise in http://exercism.io/looks yields a 404 not found error.

The links are to /:username/:exercise_key

Initially I thought that there was no route for that path but there is in /lib/app/routes/user.rb.

I can't reproduce this on my development machine. The links work OK in /looks.

**Comment by tejasbubane** [comment]
This is due to deletion of code in commit 2bbe29e done 3 days ago. cc/ @kytrinyx 

Even I was unable to reproduce the issue on my dev machine. But later I found out my branch was stale, so took a fresh pull and was now able to see the issue.

**Comment by kytrinyx** [comment]
Ah, my bad! This is what I get for having no rhyme or reason in the routes. I'll bring this one back.

**Comment by kytrinyx** [comment]
Ok, deploying a fix now. Sorry about that.

**Comment by monkbroc** [comment]
Awesome :sparkles:
