### ISSUE TITLE
Syntax Highlighting in the editor

### ISSUE THREAD

**Issue by Eruhenon** [exercism/exercism.io#2275]
Currently it is quite hard to read solutions (at least for objective-c), if you're used to syntax highlighting.
It would be really nice, if a future version would do this.

**Comment by kytrinyx** [comment]
It looks like `rouge` specifies `objective_c` as the language rather than `objective-c`, which we're passing. This might be a one-liner fix (but would have to be tested).

**Comment by mtakac** [comment]
What do you mean by "would have to be tested"? If you mean manually verify if your suggested fix is correct than yes it is. If you mean by writing an automated test, could you elaborate more on what kind of test do you have in mind? Is it enough just to test the helper or would you prefer to have some kind of test for the view and rendered highlighted code as well?

**Comment by kytrinyx** [comment]
Oh, no need to test this with an automated test--just manually/visually check.
Writing tests for rouge/markdown integration seems unnecessarily complex and brittle.

If it works, would you mind submitting a pull request?

**Comment by mtakac** [comment]
Sure, here it is: #2285 :)

**Comment by kytrinyx** [comment]
Fixed :) Deploying now. Thanks!
