### ISSUE TITLE
Foreman version change causing port problems

### ISSUE THREAD

**Issue by joesiewert** [exercism/exercism.io#2277]
Noticed that the recent Foreman version change is causing port problems.  The app now starts up on port 5000 instead of 4567.  It looks like beginning in version 0.75.0, Foreman started ignoring the .env file.  https://github.com/ddollar/foreman/blob/master/Changelog.md

You can specify the port when starting the app, but I'm wondering if there's a better solution.
```foreman s -p 4567```

**Comment by kytrinyx** [comment]
I think it's fine to specify the port, let's just change the README to reflect the change.

**Comment by joesiewert** [comment]
Cool, I will make that change.

**Comment by kytrinyx** [comment]
Thanks!
