### ISSUE TITLE
Critiques: "five a day" mechanism

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2279]
From @pminten [here](https://github.com/exercism/x-common/issues/63#issuecomment-88059929):

------

Regarding the overwhelming numbers, here's a crazy idea. What if we would try to prod people into doing 5 reviews a day. Why 5? Because that's a number that's low enough to not be overwhelming and since people usually won't do this with any luck you'll end up with 2 reviews per submitted exercise, which is enough to get all exercises reviewed.

The way I imagine this is that in the top bar of the page there's a visually distinctive number. Click on it and you get five exercises that you can review. When you've interacted with the exercise the number goes down, at zero it becomes a checkmark. Every day the number is reset to five. The number never goes higher than 5 so you'll never face an overload (which is offputting).

The 5 review exercises are put in other places as well, when you complete an exercise the system will suggest 5 (or whatever your "left daily reviews number" is) exercises with links.

The idea is to always have this small bit of work easily accessible.

**Comment by kytrinyx** [comment]
In terms of implementation, I'm thinking that we can use redis sets, keying off of the user id and the numerical id of of the month, with two cron jobs:

1. to pre-distribute problems to the daily 5 set, and
2. to sweep out old keys regularly

It would also probably be a good idea to know a user's timezone so that we aren't using UTC for everyone, though this will not always work (if people are traveling, etc).

**Comment by jwood803** [comment]
Any ideas on how to prod folks to do the reviews?

**Comment by trueheart78** [comment]
The reward should be intrinsic. Otherwise, we risk gamification.

**Comment by kytrinyx** [comment]
Agreed, it has to be intrinsic.

**Comment by kytrinyx** [comment]
Sorry, I was on a call. Yes, I think it should be intrinsic.

The GitHub streak is a nice way of reflecting my intrinsic motivation to do a little bit every day on open source in general and exercism in particular. It doesn't prod me. No emails, no text messages, no warnings, no recrimination, no shaming.

I think that we might be able to do a sort of streak implementation where you get a light colour for 1 nitpick, darker for each nitpick and > 5 is the darkest. It might not be necessary, but it might be a secondary motivator that helps keep the intrinsic thing going.

**Comment by pminten** [comment]
At the same time an option to have some kind of reminder may be useful. I'm thinking of something like a personal RSS feed that every day gets 5 entries pushed to it.

**Comment by kytrinyx** [comment]
Right, that would be useful. I would want that to be opt-in rather than opt-out.

**Comment by jwood803** [comment]
> I think that we might be able to do a sort of streak implementation where you get a light colour for 1 nitpick, darker for each nitpick and > 5 is the darkest.

That's a great idea! Personally, this motivates me to get at least one commit in GitHub a day. Gotta try to keep that streak going. :}

**Comment by pminten** [comment]
RSS feeds are opt-in, there's no way to make them opt-out since the user has to configure an RSS client to fetch them.

**Comment by kytrinyx** [comment]
Yeah, I just meant in general. An RSS feed would be great for this.

**Comment by ErikSchierboom** [comment]
I like the encouragement. It is slightly similar to how SO reminds me that I can do some reviews. It is not *in your face*, but does serve as a reminder. People show of not be punished if they don't participate, but some gentle nudging might go a long way.

**Comment by sguermond** [comment]
@mixolidia and I are working on this!

**Comment by sguermond** [comment]
This is implemented in #2550

**Comment by kytrinyx** [comment]
Yepp, thanks!
