### ISSUE TITLE
Name showing twice

### ISSUE THREAD

**Issue by RickBacci** [exercism/exercism.io#2284]
A friend of mine started a team, I received and accepted the invite.

I am showing up as 'rickbacci' and also 'RickBacci'

'RickBacci' is my current github name. I am guessing it has something to do with this.

I have tried reseting my api key, but that doesn't fix the issue. How do we get rid of the old name, and have my iterations show in the correct location?

**** Debug Information ****
Exercism CLI Version: 2.0.1
OS/Architecture: darwin/amd64
Home Dir: /Users/richardbacci
Config file: /Users/richardbacci/.exercism.json
API Key: xxxxxxxxxxxxxx
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/richardbacci/exercism

**Comment by kytrinyx** [comment]
You have two entries in the team page? Or is it showing somewhere else?

**Comment by kytrinyx** [comment]
I figured out what happened. It looks like when you were invited it created an extra user for you, but then it was unable to attach the user when you joined, so we ended up with two.

Sorry about that!

**Comment by RickBacci** [comment]
It's on the team page. I have no ability to delete it either. I probably
have a time machine backup, and could possibly recover the old number if
that would help.

**Comment by kytrinyx** [comment]
No, it's not your fault. I've deleted the unattached user.

**Comment by RickBacci** [comment]
Thank you very much for your help, and for making a great learning program.

**Comment by kytrinyx** [comment]
My pleasure!
