### ISSUE TITLE
No connection...

### ISSUE THREAD

**Issue by MeTaNoV** [exercism/exercism.io#2293]
I get the following with debug after previous attempt to fetch some exercise.
Note that I am behind a firewall, but didn't find anyway to configure it for exercism.

**** Debug Information ****
Exercism CLI Version: 2.0.2
OS/Architecture: windows/amd64
Home Dir: C:\Users\pascalg
Config file: C:\Users\pascalg\.exercism.json
API Key: ***removed***
API: http://exercism.io [Get http://exercism.io: net/http: request canceled whil
e waiting for connection]
XAPI: http://x.exercism.io [Get http://x.exercism.io: net/http: request canceled
 while waiting for connection]
Exercises Directory: C:\Users\pascalg\exercism

**Comment by kytrinyx** [comment]
You can configure exercism to go through your proxy.

In linux and on mac, it will look like so:

```
set http_proxy=http://[user]:[pass]@[proxy host/port]
# or
export http_proxy=http://[user]:[pass]@[proxy host/port]
```

The following command will work inside PowerShell (tested on V3.0/Win7).

```
[Environment]::SetEnvironmentVariable("http_proxy","http://[user]:[pass]@[proxy]:[port]")
```

**Comment by kytrinyx** [comment]
Did you have a chance to test with setting up a proxy?

**Comment by kytrinyx** [comment]
Since there has been no response in over a week, I'm closing the issue. If you are still having problems, please reopen it with more information.
