### ISSUE TITLE
Restore not working in one case.

### ISSUE THREAD

**Issue by borkabrak** [exercism/exercism.io#2295]
When running `exercism restore` into a new install on a different computer, the first php challenge does not update.  (The problem is calculating the hamming distance between two DNA strings).

The other work I've done is, indeed, downloaded, but hamming.php remains in its initial state instead of being overwritten with my solution.  

My guess is that the system is checking for the *existence* of the solution files instead of looking at their contents, and since that file is provided for you in just the first case, nothing further is done.

**Comment by kytrinyx** [comment]
Yeah, this is not quite right. Thanks!

**Comment by Insti** [comment]
Is this a exercism/cli issue or an exercsim/x-api issue?

**Comment by kytrinyx** [comment]
I believe this is a CLI issue.

**Comment by Insti** [comment]
Copied Issue to the cli repository.
