### ISSUE TITLE
Open Graph protocol

### ISSUE THREAD

**Issue by Nuwen** [exercism/exercism.io#2300]
The front-end site is missing Open Graph protocol so it looks a bit messy when shared over social media. Here's the documentation for OG tags: http://ogp.me/

In particular, the **onboarding/install-cli** route should have OG tags so it looks clean when shared over Facebook/Twitter etc. 

I'll submit a pull request to add og:title & og:image to **lib/app/layout.erb** & **lib/app/styleguide.erb**. Hopefully this covers all cases!

**Comment by kytrinyx** [comment]
Very good point. Thanks so much for adding it!

**Comment by Nuwen** [comment]
Glad to help! This project is incredible, thank you thank you thank you. :)
