### ISSUE TITLE
Submitting solutions that are UTF-16 encoded results in a 500 response

### ISSUE THREAD

**Issue by ambroff** [exercism/exercism.io#2303]
I don't really have any other context to provide, except that when I submit my solution I get this output from exercism.exe

```
PS C:\Users\kyle_000\exercism\cpp\anagram> exercism.exe --verbose submit anagram.h
2015/04/03 09:44:40 unable to submit (HTTP: 500) - Sorry, something went wrong. We've been notified and will look into it.
```

**Comment by kytrinyx** [comment]
What does the output of `exercism debug` say?

**Comment by ambroff** [comment]
```
C:\Users\kyle_000>exercism debug

**** Debug Information ****
Exercism CLI Version: 2.0.0
OS/Architecture: windows/amd64
Home Dir: C:\Users\kyle_000
Config file: C:\Users\kyle_000\.exercism.json
API Key: [REDACTED]
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: C:\Users\kyle_000\exercism

If you are having trouble and need to file a GitHub issue (https://github.com/ex
ercism/exercism.io/issues) please include this information (except your API key.
 Keep that private).

C:\Users\kyle_000>
```

**Comment by ambroff** [comment]
I just started looking through the client code to see if I can get any more information. So far all that I know is that the response body from the server is just an empty list.

```[]```

**Comment by kytrinyx** [comment]
I will have more information when I get home from work and can look at the bug report from the server.

**Comment by ambroff** [comment]
Ah, so, all of the files for the previous exercises that I've submitted were created by Emacs and they are all ASCII.

This exercise on the other hand I created with powershell and it is UTF-16. I suspect that your server isn't handling that properly.

**Comment by kytrinyx** [comment]
Oh, yepp! That is a very good assumption.

**Comment by ambroff** [comment]
Yup that was it. Submitting that file in ASCII worked. So this is pretty easy to repro.

**Comment by kytrinyx** [comment]
Awesome.

Notes: this could be a problem in either the CLI or the api endpoint or both.

**Comment by ambroff** [comment]
It's a little of both. I don't know much about ruby but I'm able to reproduce it locally.

https://gist.github.com/ambroff/367159b3931678305eb1

The server *might* be able to handle this in a more graceful way, but the real problem is that the client is writing utf-16 bytes into a string as utf-8 JSON document. Looking at the client now to see if there's a built-in way to do the appropriate transcoding.

**Comment by ambroff** [comment]
Something like this seems to be doing the right thing for a bunch of tests I've run. I'll clean it up and add a couple of tests and submit a pull request.

https://gist.github.com/ambroff/430be29f6acd313dc3e3

**Comment by kytrinyx** [comment]
sweet, thanks so much for digging into it.
