### ISSUE TITLE
JavaScript exercises inconsistent formats

### ISSUE THREAD

**Issue by kbadk** [exercism/exercism.io#2304]
I just tried to do the first few JavaScript exercises, and it annoyed me a great deal that I had to spend the majority of the time guessing what format the answer was supposed to come in.

For the first exercise, Bob, you're given a skeleton where you have to extend the Bob object with a function `hey`:

    var Bob = function() {};
    Bob.prototype.hey = function(input) { ... }
    module.exports = Bob;

In the second exercise, Word Count, you're given no template, so you have to guess you have to define a function `words`:

    function words() { ... }
    module.exports = words;

In the third exercise, Hamming, neither of the two approaches above will work. Instead, you're here supposed to do:

    var Hamming = {
        compute: function(A, B) { ... }
    }
    module.exports = Hamming;

Now for the forth, Anagram, the description says "Write a program that, given a word and a list of possible anagrams, selects the correct sublist.". You'd imagine you should create a function like

    function anagram(word, wordlist) { ... }

Or maybe something like what you did with Bob or Hamming.

What you actually have to do is:

    function anagram(word) {
        return {
            matches: function(wordlist) { ... }
        }
    }
    module.exports = anagram;

If the counter-argument to this is that programming isn't just about writing the code, but also understanding the code you're working with, then I think this is a misplaced lesson.

I found getting the format right difficult, but the exercises themselves very easy. I think the real challenge ought to be in writing the code, not making it fit ever-changing testing formats.

I can imagine that the majority of the target audience (the people who find these exercises challenging), will find getting the format right to be a lot more challenging, probably to the point of giving up.

**Comment by kytrinyx** [comment]
Hm, yeah this is definitely an issue, thanks for bringing it up.

**Comment by rchavarria** [comment]
I noticed not all exercises needed to export the same structure: some need a function, some a constructor function,... But I didn't think it would be so distracting to give up trying.

I completely understand and agree @kbadk's point of view. The difficulty should be in solving the exercise, not in figuring out what structure should be exported in the module.

I'll create a new issue on exercism/xjavascript repo hoping the conversation will take place on JavaScript track.

**Comment by kytrinyx** [comment]
Thanks, @rchavarria I'll close this one in favour of exercism/xjavascript#128
