### ISSUE TITLE
Inconsistencies between between languages

### ISSUE THREAD

**Issue by kbadk** [exercism/exercism.io#2305]
In the first JavaScript exercise, Bob, all but the first test has been disabled. Luckily, the `README.md` explains this:

>In many test suites all but the first test have been skipped.
>Once you get a test passing, you can unskip the next one by
changing `xit` to `it`.

In the first PHP exercise, Hamming, all but the first test has also been disabled. Unfortunately, here nothing about that is mentioned in the `README.md`. So unless you study `hamming_test.php`, you may not realise that all tests are not being run. On top of that, even if you do realize, you may not realize that you need to remove `$this->markTestSkipped();` from each test for it to be re-enabled.

The `README.md`s should be consistent across languages, and should explain how the unit testing works in at least the first exercise you try with the language.

**Comment by kytrinyx** [comment]
Agreed, the README.md should mention this if tests are skipped and also show how to run the tests. I'll make sure we have an open issue in each language track about this.

Thanks!

**Comment by kytrinyx** [comment]
/cc @exercism/track-maintainers - if you have a moment to verify that the SETUP.md in the track(s) that you maintain contain

- a quick note about skipped tests (if you skip tests in that track), and
- how to run the tests

then I think that all of the issues linked to from this discussion can be closed: https://github.com/exercism/exercism.io/issues/2198#issuecomment-81252987

**Comment by LegalizeAdulthood** [comment]
C++ should be good on this; it was setup this way from the beginning.

**Comment by kytrinyx** [comment]
Yeah, C++ was the first one to do this, I think.

**Comment by kytrinyx** [comment]
We've made a ton of progress on this sort of issue, among other things by introducing a `canonical-data.json` data set that different language tracks can use to implement an exercise.

If you see further problems like this please open an issue in the https://github.com/exercism/x-common/issues repository.
