### ISSUE TITLE
Long links go over text box

### ISSUE THREAD

**Issue by masters3d** [exercism/exercism.io#2306]
I guess people could use a link shortening service it but it was wrapping fine when I wrote it. 

![image](https://cloud.githubusercontent.com/assets/6539412/6989537/5ab4e232-da11-11e4-8cc2-a3ad5cf3c4ea.png)

**Comment by kytrinyx** [comment]
Oh, wow :) that's kind of epic.

**Comment by elliotwms** [comment]
```sass
.comment-body p a {
    word-wrap: break-word;
}
```

Alternatively we could figure out a way to ellipsisize links after a certain length but I'm not sure this would be a purely CSS solution

**Comment by kytrinyx** [comment]
Yeah, let's just wrap it!

**Comment by mfrost** [comment]
I believe this was resolved by #2618. Tested locally and it looks like:
<img width="504" alt="screen shot 2015-11-24 at 4 35 00 pm" src="https://cloud.githubusercontent.com/assets/168570/11384029/7c3de75c-92c9-11e5-8caf-d414a54e9bb1.png">

**Comment by kytrinyx** [comment]
perfect, thank you
