### ISSUE TITLE
Create "News" or Social Media section on site

### ISSUE THREAD

**Issue by masters3d** [exercism/exercism.io#2307]
1) List a couple of interesting blogs talking about exercism.io
2) Twitter Widget for  the #exercism hashtag
https://dev.twitter.com/web/overview
A lot of people do misspell #exorcism as #exercism.io on twitter though. An alternative could be #exercismio which sounds like latin when put together so I am no sure.

**Comment by kytrinyx** [comment]
I would classify this as a nice to have, but not as important as figuring out how to actually explain what exercism is and make sure people know how to get started.

**Comment by masters3d** [comment]
This post got me thinking about this. ;)  He is talking to another user. But I do agree with you on the priorities. 
![image](https://cloud.githubusercontent.com/assets/6539412/6990833/b85c5726-da2a-11e4-8a01-26aa80d373eb.png)

**Comment by kytrinyx** [comment]
Nice! Yeah, I agree that we need more people... but we need more people carefully. We don't need more people in Ruby and Javascript right now, for example. We need to solve the bottleneck problem.

Maybe there's something we could do to figure out which languages are kind of slow going, and do some outreach to user groups?

**Comment by masters3d** [comment]
Got cha. Yeah finding out which languages are going slow is a good idea!
Here I am thinking marketing and oblivious about the bottle neck on those
tracks. ha. well I think I can do a little outreach to a couple of swift
groups.

**Comment by kytrinyx** [comment]
That would be great. And I'll open an issue about investigating the state of things in various tracks.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this (I hope your outreach to swift groups went well), as we've got several threads open to try to improve the sustainability of the community at a number of different levels.
