### ISSUE TITLE
Markdown code blocks are parsed wrong when they directly follow text

### ISSUE THREAD

**Issue by trayo** [exercism/exercism.io#2310]
When writing a nitpick with a code block an extra space after text is required in order to make the proper block appear.

#### What happens when there is no space following a line of text:
![screen shot 2015-04-03 at 9 08 30 pm](https://cloud.githubusercontent.com/assets/6809782/6991254/0708a08a-da46-11e4-8050-06892ea2677f.png)
![screen shot 2015-04-03 at 9 07 11 pm](https://cloud.githubusercontent.com/assets/6809782/6991255/0f1f101a-da46-11e4-9aa6-0546f7414c7a.png)

#### How to get around it:
![screen shot 2015-04-03 at 9 07 51 pm](https://cloud.githubusercontent.com/assets/6809782/6991262/a35de562-da46-11e4-85a9-209c4190ad15.png)
![screen shot 2015-04-03 at 9 08 05 pm](https://cloud.githubusercontent.com/assets/6809782/6991257/3901d336-da46-11e4-8b32-4ef753f66d7d.png)

Github is able to parse a code block when it directly follows a line of text:
```ruby
def more_things
  "foobar"
end
```

**Comment by kytrinyx** [comment]
Thanks for the detailed report, that should make this easier to hunt down and fix.

**Comment by rheinwein** [comment]
@mxlje and I will tackle this @rossconf!

**Comment by kytrinyx** [comment]
Sweet! :)
