### ISSUE TITLE
Add label for counts on nitpick page.

### ISSUE THREAD

**Issue by bIgBV** [exercism/exercism.io#2313]
In it's current state the counts next to each submission aren't clear about what they represent.
![Imgur](http://i.imgur.com/cCEKAhI.png)

I would suggest added labels on the top - something like this:
![Imgur](http://i.imgur.com/F8xDsyO.png)

I got that result using some hacky CSS and adding a `div` and a couple of `span`' elements. 

```
<main id="pending-submissions" class="col-md-8">
      <h2>
  <div class="language circle  python-icon">&nbsp;</div>Pending Submissions</h2>
  <div style="margin-left: 41rem;" clas="count-labels">
    <span style="color: rgb(98, 98, 98); font-family: inherit; font-size: 1.5rem;" class="label">Comments</span>
    <span style="color: rgb(98, 98, 98); font-family: inherit; font-size: 1.5rem;" class="label">Revisions</span>
  </div>

<hr>

  <div class="pending-submissions">
...
...
```
I just used the web inspector in firefox to add the styles which to position the `div` containing the two `spans` and used absolute positioning. 

It was just intended as an example because it took me a few hours of usage of the website to understand what each count meant.

Hope this helps!

**Comment by kytrinyx** [comment]
Nice, yeah! This is great, thank you.

**Comment by bIgBV** [comment]
I'm working on this right now, but I have hit a hitch in the workflow. I added a new sass file in the layouts folder and `compass watch` detects the changes and compiles it to a css files under the layouts folder. 

But I am unable to see the styling changes I made when reloading the page. I followed the steps as mentioned in the setup guide by first running the server locally then running `compass compile`.

**Comment by kytrinyx** [comment]
Did you add the new file to the `lib/app/public/sass/base/components/import.scss` file? The application.scss needs to know about it otherwise it won't get included.

**Comment by bIgBV** [comment]
Thanks for that tip. It's working now after fiddling around a bit.

I put the new file in the layouts folder according to the style guide as the styles were related to that particular page.

**Comment by kytrinyx** [comment]
Cool, yeah that sounds right.

**Comment by bIgBV** [comment]
I just sent a PR with the changes. Can you check and tell if everything is okay ? If there are any changes then I'll commit them.

Also the contributing experience has been fun, and thanks for the help you provides for noobs like me :+1:

**Comment by kytrinyx** [comment]
It's a pleasure! Thanks so much for contributing.
