### ISSUE TITLE
Unable to Submit - Unable to Identify & Track Problem

### ISSUE THREAD

**Issue by NYDrewReynolds** [exercism/exercism.io#2314]
All week I have been able to submit exercises. However, when I tried to this morning, I received this error message. What can I do to fix this issue?

**** Debug Information ****
Exercism CLI Version: 2.0.1
OS/Architecture: darwin/amd64
Home Dir: /Users/drewreynolds
Config file: /Users/drewreynolds/.exercism.json
API Key: mykeymykeymykey
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/drewreynolds/Documents/Turing/1Module/exercism

**Comment by kytrinyx** [comment]
It's quite possibly a problem on my end.

What does `pwd` say when you submit?
What exactly was the `exercism submit` command that you used?

**Comment by NYDrewReynolds** [comment]
Hey Katrina, sorry about this! I organized some files yesterday and it was an error with my pwd. Thank you!

**Comment by kytrinyx** [comment]
You're welcome. Glad it's sorted!
