### ISSUE TITLE
`exercism submit` showing "To get the next exercise..." when submitting a revision to a completed exercise

### ISSUE THREAD

**Issue by pyskell** [exercism/exercism.io#2315]
For submitted revisions the text "To get the next exercise, run "exercism fetch" again." shouldn't be shown when the next exercise has already been fetched.

**Comment by h-core** [comment]
For submitted revisions the text "To get the next exercise, run "exercism fetch" again." shouldn't be shown when the next exercise has already been fetched.

**Comment by kytrinyx** [comment]
Yes, this is a bug. Thanks!

**Comment by petertseng** [comment]
Looks like this got done recently at https://github.com/exercism/cli/commit/6ff669dd6bc28abf3be296a63ddf7c58f340df68

**Comment by kytrinyx** [comment]
yepp, thanks!
