### ISSUE TITLE
`exercism fetch` and `exercism submit` resulting in `connection refused` error.

### ISSUE THREAD

**Issue by bIgBV** [exercism/exercism.io#2317]
I had this issue when setting up my local dev environment.

Using the current front end, one needs to clone the x-api repository and use run that locally in order to access the pending submissions page and the nitpick page. At least that's how I think I could get to it because there is no direct link present when I fist log in.

If there is a better way I would like to know as right now even after configuring the CLI client to use the api server on my local machine running the `fetch` command gives me a `connection refused error` but I can still get the json if I just go to the url in the browser.

    2015/04/05 00:38:53 Get http://localhost:9292/v2/exercises/python?key=4a3fbe027ea94d6ca1c4734313c1891d: dial tcp 127.0.0.1:9292: connection refused

**Comment by mtakac** [comment]
What are you trying to do? You shouldn't need x-api for development on exercism.io. If you want to access submission page on your local machine, you can use profile of one of test users. Just pick one from the most right link in the top bar.

**Comment by bIgBV** [comment]
Yeah I deleted and started from scratch without configuring anything in the CLI and now the assume button works. Previously once I had configured the CLI and logged in with that account on my local server I couldn't log back out.

I think there should be some mention of the test users in the setup part of the README, it will definitely clear up a lot of doubts.
