### ISSUE TITLE
Javascript styleguide discussion

### ISSUE THREAD

**Issue by mtakac2** [exercism/exercism.io#2320]
We should have consistent coding style and enforce it using some linting tool. I would like to briefly discuss what this style should look like before creating our custom rules for linting.

I think we could use following documents as a base:
- (AirBnB JS styleguide)[https://github.com/airbnb/javascript]
- (Google JS styleguide)[https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml]
- (Recommendations and best practices from Angular official developer guide)[https://docs.angularjs.org/guide/introduction]
- (John Papa's Angular styleguide)[https://github.com/johnpapa/angular-styleguide]

**Comment by nickborromeo** [comment]
Should this be moved to the discussions repo and close this issue?

**Comment by kytrinyx** [comment]
I think we can close it without moving it. I've added "javascript styleguide" to the list of things to consider when we do the reboot.
