### ISSUE TITLE
Setup front end development

### ISSUE THREAD

**Issue by mtakac2** [exercism/exercism.io#2321]
There is new pipeline created for front end development (in `client`). Pipeline is build on webpack and Gulp (See [README](https://github.com/exercism/exercism.io/blob/master/client/README.md) for details). There are still some things that need to be done to ensure smooth development process.

- [ ] enable livereloading (is already there but for some reason, doesn't always work)
- [ ] we should have a JS styleguide (See: #2320) and we will need to setup JSHint (or similar tool) to enforce the style
- [x] come up with easy way to debug code during development
- [x] add ngAnnotate and minification
- [ ] modify deployment process and CI

**Comment by mtakac** [comment]
@kytrinyx Do we have some staging? Just thinking that it would be really useful to review the changes in production like environment.

**Comment by kytrinyx** [comment]
I've created the frontend label. We don't have a staging environment, but it shouldn't be too difficult to create one.

**Comment by kytrinyx** [comment]
Note: we added a staging environment (exercism-theory.herokuapp.com), which currently has the front-end branch on it.

**Comment by kytrinyx** [comment]
Since it's been 18 months I'm going to close this. We are still working on getting rid of lineman (see https://github.com/exercism/exercism.io/issues/3166).
