### ISSUE TITLE
Submiting my first exercism problem [Python]

### ISSUE THREAD

**Issue by BishopBD** [exercism/exercism.io#2327]
I keep getting:
C:\Users\Brian\exercism> exercism submit C\Users\Brian\exercism\python\bob\bob.py
2015/04/06 xx:xx:xx GetFileAttributesEx C\Program: The system cannot find the file specified.
I think the problem is my exercise directory, aka "C:\Program", which isn't even a valid folder in my "C:\" Heres my debug call:
Exercism CLI Version 2.0.2
OS/Architecture: windows/amd64
Home Dir: C:\Users\Brian
Config file: C:\Users\Brian\.exercism.json
API Key: xxx...
API: http://exercism.io[connected]
XAPI: http://exercism.io[connected]
Exercises Directory: C:\Program

**Comment by bIgBV** [comment]
Can you try changing the Exercises directory to the directory in which your exercises are actually present in the config file ? Once you do that try running `exercism configure` with your key again.

I ask this because you say that `C\:Program` isn't a valid directory.

**Comment by kytrinyx** [comment]
You can also try running configure with the following:

```
exercism configure --dir=C:\Users\Brian\exercism --key=YOUR_KEY
```

**Comment by BishopBD** [comment]
Your kindness and help is fully appreciated. As always, thank you.
