### ISSUE TITLE
Problems Creating Team

### ISSUE THREAD

**Issue by LydiaTripp** [exercism/exercism.io#2328]
I am attempting to create a team, but I am being added to the team twice.  It looks like I have two accounts, one with the user name "lydiatripp", another with the user name "LydiaTripp".

![screen shot 2015-04-06 at 2 39 53 pm](https://cloud.githubusercontent.com/assets/8502/7010972/df6868cc-dc6a-11e4-851c-c62921a313bd.png)

**Comment by kytrinyx** [comment]
This is definitely a bug. I'll dig into it and let you know what I find.

**Comment by kytrinyx** [comment]
Ok I found an extra account that might have gotten created when you (or someone) sent an invite to join a team. It's a bit odd, and I'll poke around a bit to see if I can reproduce it on my end.

Meanwhile I deleted the ghost account.

Let me know if this clears it up!

**Comment by LydiaTripp** [comment]
Thanks, deleting the ghost account allowed me to accept the team invite.  My username has caps in it, but my ghost account did not.  I am guessing it might be related to the user name being case sensitive in some place.  Let me know if you need my help to reproduce the error.

**Comment by kytrinyx** [comment]
I have a suspicion that it might be something that's happening when someone who is not yet in the system gets invited. If I can think of some steps to help reproduce it, I'll post back here.

**Comment by LydiaTripp** [comment]
I am in the system, as was my other team member.  I have been a user for over a year.

**Comment by kytrinyx** [comment]
Ok, interesting. That certainly puts this in a different light.

**Comment by Tonkpils** [comment]
@kytrinyx any way we can help figuring out this bug?

**Comment by kytrinyx** [comment]
I need to find reproduction steps for this. Some users get created in the system as ghost users (no github user id, etc) instead of attaching them to the existing user.

**Comment by Peque** [comment]
I have the same exact problem. Cannot get invited to groups. I have created a group myself and then I find two users with my name (the wrong one is the one with all lowercase).

**Comment by Peque** [comment]
Also, after creating the group, I have a notification telling me that I have an invitation from myself to join the group I just created. When I click on "accept", nothing happens (the invitation seems to stay there :joy:).

**Comment by kytrinyx** [comment]
I'm so sorry you ran into this. Thanks so much for the reproduction steps--that's very helpful. I'll hunt this down and fix it!

**Comment by Peque** [comment]
@kytrinyx: Thank's to you! :blush:

Beta software is beta software... :wink:

**Comment by kytrinyx** [comment]
Some days I want to retract the "beta" and put "alpha" on this thing :)

**Comment by Foovanadil** [comment]
I have the same issue (posted here https://github.com/exercism/exercism.io/issues/2467)

I also can't submit assignments, possibly related?

**Comment by kytrinyx** [comment]
OK, I've managed to reproduce the issue with the following steps.

Assume that your usual username is `alice`. You have an Exercism account, and you've created a team named `Team Bug`.

1. Create a second GitHub account, `bob`.
2. Log in to Exercism as `bob`
3. Log out, log in to Exercism as `alice`
4. Invite `BOB` to `Team Bug`
5. Log out, log in to Exercism as `bob`
6. Go to the notifications page
7. Try to accept the invitation

Note that this will not work if you first invite `BOB` when he has no Exercism account, and then `bob` logs in to exercism. In this case the ghost user does not get created, and `bob` will be able to accept the invitation.

It doesn't matter what the case is in the GitHub username, provided that the invitation is made with a character that has the incorrect case.

**Comment by kytrinyx** [comment]
I've deleted the ghost users in production, and deployed the fix so that ghost users will no longer be created.

**Comment by Peque** [comment]
Thanks for this fix. Everything works as expected now. :blush:

**Comment by kytrinyx** [comment]
Great, thanks for following up!
