### ISSUE TITLE
Unable to accept invitation and join team

### ISSUE THREAD

**Issue by JaKXz** [exercism/exercism.io#2331]
I'm seeing the invitation on my account page, as mentioned, but when I click on it I'm taken to the pay-it-forward page with the following error message:

https://www.dropbox.com/s/ba2i9q7yg2la31r/Screenshot%202015-04-06%2010.30.42.png?dl=0

The invitation also remains on my account page.

**Comment by kytrinyx** [comment]
Hi @JaKXz, I found a "ghost" user (duplicate account with no data in it), that might be causing this. I've deleted that ghost account.

I'm going to try to reproduce this locally (and figure out why there's a ghost account)--meanwhile, would you see if deleting the ghost user lets you accept the invitation?

**Comment by JaKXz** [comment]
@kytrinyx it seems like that's taken care of it! Thanks!

**Comment by kytrinyx** [comment]
Awesome thanks. I'm going to leave this open since I haven't yet determined the underlying cause.

**Comment by alvaroDevfacto** [comment]
I seem to be getting the same error message.  How do delete the ghost user?  I've deleted the invitations to the team and the team has resent the invitation.  I'm still unable to join the team.

**Comment by kytrinyx** [comment]
I'll delete the ghost user when I get home from work today.

**Comment by kytrinyx** [comment]
Ghost user deleted. Sorry about that!

**Comment by kytrinyx** [comment]
Related issue #2355
