### ISSUE TITLE
Tests for clojure/bank-account are incorrect

### ISSUE THREAD

**Issue by alexkalderimis** [exercism/exercism.io#2332]
Specifically, the pcalls takes a sequence of functions, not a sequence of forms, so it should be:

```clj
(deftest check-concurrent-access
  (with-bank "handles concurrent execution"
    (fn [acc label]
      (let [add-10 #(bank-account/update-balance acc 10)]
        (pcalls add-10 add-10 add-10))
      (is (= 30 (bank-account/get-balance acc)) label))))
```
I looked to fix myself, but I could not find where the tests are located.

Also, the tests could also be improved with a macro rather than a function, along the lines of:

```clj
(defmacro with-bank [label & body]
  `(let [acc (bank-account/open-account)
          label ~label] ;; Make these implicitly available.
     (do ~@body) ;; Return value never used, so no need to return it.
     (bank-account/close-account)))

;; then the tests look like:
(deftest can-increment-and-decrement
  (with-bank "increment and decrement balance"
    (is (= 0 (bank-account/get-balance acc)) label)
    (is (= 10 (bank-account/update-balance acc 10)) label)
    (is (= 0 (bank-account/update-balance acc -10)) label)))
```

You could try and be a lot cleverer and implicitly insert `acc` and `label`, but that doesn't get you very much.

**Comment by mtakac** [comment]
Hi @alexkalderimis, tests are in different repository. Each language has it's own repo with problem sets. So this one should be in [exercism/xclojure](https://github.com/exercism/xclojure). I think this is the file https://github.com/exercism/xclojure/blob/master/bank-account/bank_account_test.clj. Would you like to open a PR with the fix?

**Comment by alexkalderimis** [comment]
sure. will do

**Comment by kytrinyx** [comment]
Thanks! Closing this one in favour of the PR in the xclojure repo.
