### ISSUE TITLE
Broken "view submissions" maybe related to username change

### ISSUE THREAD

**Issue by keleshev** [exercism/exercism.io#2334]
I recently got contacted by @halst in relation to #2289 issue. He got my old username after I changed mine to @keleshev. I decided to log into exercism to check if I will get logged in as `halst` or as `keleshev`. It worked fine, I log in as `keleshev`, however when I press on "view submissions" link (http://exercism.io/halst/31aa223eae47804952b47c69) it returns "couldn't find that exercise". From the link it seems that the the error is related to username change, because if I manually edit link to http://exercism.io/keleshev/31aa223eae47804952b47c69 it correctly opens my submission.

**Comment by kytrinyx** [comment]
Which page is the "view submissions" link on?

**Comment by keleshev** [comment]
It is this one. I don't have "view submissions" on my landing page.
![screen shot 2015-04-07 at 9 42 07 pm](https://cloud.githubusercontent.com/assets/619158/7031881/05ce662e-dd6f-11e4-84fc-d22bd2c2095b.png)

**Comment by kytrinyx** [comment]
Ah, I think I know what is going on, thanks!

**Comment by kytrinyx** [comment]
I fixed this, sorry it took a while!

**Comment by keleshev** [comment]
:+1:
