### ISSUE TITLE
Daily digest email for notifications

### ISSUE THREAD

**Issue by ajcoppa** [exercism/exercism.io#2337]
I'd love to see a daily digest email instead of individual event emails. I'm a huge fan of the notifications -- I was just surprised to get 8 of them when I woke up in the morning.

**Comment by kytrinyx** [comment]
Yeah, we definitely need to do something about the notifications! We're working on an activity stream (#1899) which will include granular subscriptions. I'm pretty sure we can tie this into that work.

**Comment by kytrinyx** [comment]
We completely removed email notifications from exercism a while back. We may consider putting them back in, at which point we will be thinking through how to let people make the emails as useful to them as possible. Meanwhile I'm going to close this, since it's not something we can act on now.
