### ISSUE TITLE
Team invitation notification persists

### ISSUE THREAD

**Issue by purezen** [exercism/exercism.io#2340]
Seems like a bug. On receiving a team invitation, the notification persists even after accepting the invitation.
Team members view:
![screen shot 2015-04-10 at 2 40 26 pm](https://cloud.githubusercontent.com/assets/3036093/7084921/a57dd426-df8f-11e4-8b16-bbf49d744a01.png)

while in the Notifications page:

![screen shot 2015-04-10 at 2 40 08 pm](https://cloud.githubusercontent.com/assets/3036093/7084923/a9e5fd36-df8f-11e4-8be7-8be948671081.png)

**Comment by kytrinyx** [comment]
Yes, this is a bug. The notification is supposed to disappear. I've got a whole handful of bugs in the team invitation/notification part of the code right now, and will have to do a proper overhaul of this.

**Comment by amalrik** [comment]
@kytrinyx this can be closed since #2374 got merged.

**Comment by kotp** [comment]
Thanks @amalrik .  Not @kytrinyx but will close. (One less thing she needs to worry about this weekend.)
