### ISSUE TITLE
[topic] Marketing & Branding

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2342]
Since the beginning, in June of 2013, we have made no effort to market exercism.

The most important things to note are these:

* The site is very difficult to use, and this results in a fairly high need for support.
* There are quite severe bottlenecks in the feedback in some language tracks, where people submit solutions but do not get feedback for a very long time or at all.
* The quality of the feedback varies significantly.

Until these core issues can be addressed it would be reckless and counter-productive to actively try to bring many people to the site.

Several things have come up at various points in time:

- We should have a blog. This would let us focus on interesting topics that come up in the conversations, and deeper analyses of some of the problems, differences between the same problem in multiple languages, and in general _what exercism is all about_.
- We should have a newsletter. We kind of do, but I have been quite lax in managing it, and have only sent out one email, to announce that the Lisp and Java tracks launched. http://tinyletter.com/exercism/letters/exercism-new-language-tracks
- People say very nice and enthusiastic things about exercism. We should probably put these things on the homepage or somewhere.
- People blog about exercism and do talks at local meetups (and even do meetups dedicated to getting together and helping people get started with exercism and solving problems together. How cool is that?!). We should link to these things.
- We should reach out to local language-specific meetups and try to build up the various language track communities.

Here are some of the issues that are related to this topic: #2307, #1641, ... (?)

Another thing that is perhaps more about branding than marketing, is the term _nitpick_ itself (#1508). Some people have a very strong negative reaction to it (https://twitter.com/sbellware/status/571167911609442305).

**Comment by pminten** [comment]
Regarding "nitpick", it's really more about "feedback". It's not uncommon for me to leave a nit that simply says "I like this, in particular you're doing X and Y correctly", which is feedback but not a nitpick.

**Comment by kytrinyx** [comment]
Exactly--sometimes I leave feedback (or "critique" where critique can mean something positive) and sometimes it's more of a hint ("hey, check out this type in the standard library, it could help simplify things").

**Comment by kytrinyx** [comment]
I'm going to close this, as I'll be tackling marketing/branding as a separate thing with people who know what they're doing.
