### ISSUE TITLE
Exercise dev readme for track-translators

### ISSUE THREAD

**Issue by pminten** [exercism/exercism.io#2343]
One thing we've seen pop up over and over again is that exercises follow different logic in different tracks, often due to some confusion of the translator as to what the intended behavior is.

It may be a good idea to have some kind of dev README in the x-common repo where the original writer of the exercise can describe the idea behind it and point out some of the relevant edge cases to help translators write a correct translation.

**Comment by kytrinyx** [comment]
Agreed, this would be really useful. Perhaps, something like `bob.notes.md`.

**Comment by wobh** [comment]
If we treated readme files in x-common as templates, we could render them together with any track-specific readme files in the exercises to the downloaded exercise. An exercise unique to the track would get it's readme from the exercise alone.

**Comment by kytrinyx** [comment]
I don't understand what you mean by templates.

**Comment by kytrinyx** [comment]
Closing this in favor of https://github.com/exercism/x-common/issues/382
