### ISSUE TITLE
Hamming exercise: `const_missing': uninitialized constant MiniTest::Test (NameError)

### ISSUE THREAD

**Issue by LadyLovesCode** [exercism/exercism.io#2344]
After following the steps in the GETTING_STARTED.md file, I have come up with the following:

class Hamming
  def self.compute(a,b)
  end
end

The Getting Started guide expects you to run into various errors along the way, but by this point, I should be able to run hamming_test.rb without error and, instead, run into the failure of my first test. However, this is not the case. I still run into the same and only error I ever ran into (I didn't get the ones mentioned in the Getting Started file.) 

Error is as follows: 
/ruby/2.0.0/minitest/unit.rb:28:in `const_missing': uninitialized constant MiniTest::Test (NameError)

I've checked that hamming.rb was saved to the same directory as hamming_test.rb.  I've double checked the spelling of everything and it all matches up. My code looks the same as the solutions I've found online and it even looks the same as the answers that have been suggested to others who have asked this same question here. 

Can anyone spot what I'm doing wrong here? A friend of mine who is doing independently working on this same exercise is hitting the same error. We're both at a loss. Any help would be appreciated. :) 

Here is a screenshot of both my code, the test file, and my terminal displaying the most recent instance of the error at hand: http://cm.d.pr/16iMz/5x8pYfcp

**Comment by LadyLovesCode** [comment]
I found it! I need to install the minitest gem. Please disregard. :)

**Comment by kytrinyx** [comment]
Yay, glad you got it figured out. I'll add something to the GETTING_STARTED.md file about installing minitest!

**Comment by LadyLovesCode** [comment]
Actually, it wound up being that I needed to *update* minitest. I used 'gem list' to find that it was installed which confused me a bit. But then, upon Googling, I discovered that only v5 would use MiniTest::Unit (which the hamming test does) so I just needed to update minitest. :)

**Comment by kytrinyx** [comment]
v4.x uses `MiniTest::Unit::TestCase` which was a bit of a bear to type. v5.x simplified this to `Minitest::Test` (notice how the case of minitest is different in the two names: `MiniTest` vs `Minitest`). This is easier to type, but of course introduces no end of confusion when people have one installed but not the other :)

**Comment by LadyLovesCode** [comment]
Thanks for responding so quickly, by the way. I'm actually glad I ran into the issue. That's how you learn right? I learn far more running into problems than I do when things run smoothly. Nothing a little Googling can't fix. :)

**Comment by kytrinyx** [comment]
I learn far more when I run into problems, too. The trick for me has been to accept that it's a part of the process, and that _understanding_ the problem is the point, not making it go away. Pretty darn challenging!
