### ISSUE TITLE
[topic] Teams

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2345]
The teams feature is kind of a disaster. First of all, it was bolted on. Second of all, the performance is appalling. Third, the UX is horrendous. Fourth, it has more bugs than the rest of the site put together.

Here's my take on teams: The only reason it's there is so that people can "follow" other people they care to follow.

Eventually, I think that the team functionality could be amazing and useful, but that necessitates having the resources to work on them. As long as exercism is a nights-and-weekends effort, I don't see how we can do the teams feature justice.

In the meanwhile, once we implement Activity Streams (#1899) I think we should remove the entire teams feature.

**Comment by LadyLovesCode** [comment]
While I don't disagree that Teams could use some work. I was actually excited to discover the feature. I happen to be working through the exercises with a group of girls. We meet each Sunday afternoon via Skype to discuss how each of us has solved the problem, raise questions if we've gotten stuck, compare solutions, and so on. Once everyone has pushed their solution to the site, we'll start working on the next exercise. So, while I wish the Teams area worked a little differently, I think it could be a really cool tool for people who are doing something like we're doing right now and having such a feature might encourage more groups to participate. Just a thought. Thanks for making this available to us. It's truly an awesome resource. :)

**Comment by kytrinyx** [comment]
Hm, yeah, I can see that it's useful. I think, when I've completed the first couple of iterations of the activity stream I'll probably ask you a bit more about what your needs are to see if I can find a way to provide that while still ditching the teams feature.

**Comment by LadyLovesCode** [comment]
Yeah, that sounds good. We just started the group and have only done the first exercise (I think my solution is pretty excellent, by the way) and so I'm not sure just yet how we'll use it or what we might feel is missing. I just know that the idea of a teams page seemed like a useful one for groups like ours. So, I'll be sure to keep notes on what helps us work as group and what is difficult, if anything.

**Comment by kytrinyx** [comment]
> I think my solution is pretty excellent, by the way

:-)

> the idea of a teams page seemed like a useful one for groups like ours

Yeah, I know a bunch of people use the teams feature, but it seems like the utility of the feature is to be able to keep track of a small set of people and go look at what they've done (to provide feedback or just out of curiosity).

I think that with the activity stream and being able to subscribe to specific users, that use-case will be sufficiently covered.

And, of course, I actually think that there could be some really useful (and quite elaborate) team features, I just don't have the resources to implement and maintain it.

**Comment by LadyLovesCode** [comment]
Yeah, I agree that the activity stream sounds like it will take care of what we need. Unless you were going to add some sort of simultaneous editing/remote pairing features, I don't know what more we could really need than the ability to easily find each other. Obviously that isn't happening any time soon, and isn't necessary. 

I was really just commenting that I appreciated the thought behind Teams. And, if the features were there, we'd use them. :)

**Comment by kytrinyx** [comment]
Thanks, I appreciate getting feedback on all of this!

**Comment by dogweather** [comment]
Just chiming in to say I do like the teams feature, as simple as it is. It doesn't need to be complex.

**Comment by kytrinyx** [comment]
Thanks @dogweather -- I made some significant changes recently adding the team activity stream, and I think that this fixed the basic brokenness with teams. I'm going to keep them as is for now.

Which actually means that we can close this thread, since the premise of the discussion was that the teams were a disaster (and they no longer are).
