### ISSUE TITLE
HashMap, ImmutableMap, Map

### ISSUE THREAD

**Issue by Vulchare** [exercism/exercism.io#2347]
I see all these in the exercises, but I can't find any good source that explains what these are and how they are used.

**Comment by kytrinyx** [comment]
Which language track are you working in?

**Comment by Vulchare** [comment]
Java

**Comment by kytrinyx** [comment]
@pietvandongen - do you have any resources you could point to?

**Comment by pietvandongen** [comment]
Yes, I think this site explains the Map interface and their implementations quite well: http://tutorials.jenkov.com/java-collections/map.html

ImmutableMap is not part of the Java API, but of Guava: http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/ImmutableMap.html

**Comment by Vulchare** [comment]
Perfect! Thank you very much :)

**Comment by Vulchare** [comment]
I was able to complete the NucleotideTest with your help. Thanks again!

http://exercism.io/submissions/bb8f001aa8414c4aa1258588eb6de044
