### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by WFawzi** [exercism/exercism.io#2351]
1.	I went to http://exercism.io/ 
2.	Clicked on LOG IN VIA GITHUB
3.	Entered my GitHub credentials
4.	Once pressed OK, I was brought back to the home page
5.	In GitHub, it shows that exercism.io is authorized

**Comment by kytrinyx** [comment]
I've seen this happen once before, and I'm still not sure what causes it.

If you look at the cookies you have, do you have one called `rack.session` for the `exercism.io` domain at path `/`?

**Comment by chab** [comment]
Same problem here on Chrome and FF. Chrome shows 3 cookies for "exercism" :
```
_ga: domain ".exercism.io" and path "/"
_gat: domain ".exercism.io" and path "/"
rack.session: domain "exercism.io" and path: "/"
```

**Comment by WFawzi** [comment]
Yes, I have the same cookies as chab.

**Comment by kytrinyx** [comment]
Those are the same cookies that I have.

I think I just figured out what is causing the symptom, and have manually fixed it for the both of you.

I still don't know how it happened in the first place, but I think I can start tracing the problem, at least!

**Comment by chab** [comment]
Yep! I'm. Thank you for prompt help.

**Comment by WFawzi** [comment]
I can login now. Thanks, Katrina!

**Comment by kytrinyx** [comment]
Excellent! I'll leave this open so I am reminded to fix the underlying bug. Thanks!
