### ISSUE TITLE
Missing language in exercise listing for Scheme

### ISSUE THREAD

**Issue by canweriotnow** [exercism/exercism.io#2353]
Seems like a site-related issue (maybe?) so I'm throwing this here instead of @exercism/scheme repo... fetching/submitting Scheme exercises works great from the CLI, but in the submitted exercises, the language is blank, like so:

![screen shot 2015-04-15 at 5 52 31 pm](https://cloud.githubusercontent.com/assets/387693/7169975/4b0fd306-e398-11e4-8f51-cb155837f300.png)

and Scheme doesn't show up under the Nitpick dropdown, although entering the url manual for /nitpick/scheme does properly redirect to recent and render (although there's nothing there since I think I'm the only one to have submitted any scheme exercises.

**Comment by kytrinyx** [comment]
This is a bug. I thought we were driving this list entirely from the API (it certainly is there in [config.json](https://github.com/exercism/xscheme/blob/master/config.json#L3)), but apparently we're not:

https://github.com/exercism/exercism.io/blob/master/lib/app/views/account/show.erb#L63

It currently uses the hard-coded list in `lib/exercism/config.rb`, but we should be using the same mechanism as the about page, which boils down to:

```
ExercismWeb::Presenters::Tracks.xapi.active.map(&:language)
```

I am on my way to work, but I should be able to fix this in the next day or so if nobody has gotten to it before that.

**Comment by canweriotnow** [comment]
Always happy to help find bugs :smile_cat:

**Comment by kytrinyx** [comment]
Would you check if my workaround is working?

I still need to fix this "f'real" (as they say) but this should at least let us announce it.

**Comment by canweriotnow** [comment]
Yup, looks good! Shall we close this issue and open a more general one for fixing it f'real?

I think we're good to announce, from what I can see!

**Comment by kytrinyx** [comment]
Yeah, good idea. Would you mind opening the new issue?

**Comment by canweriotnow** [comment]
Yup, opened as #2356 - I don't have rights to add a label, so you might want to flag it as a bug if you get the chance?

Closing this issue as superseded by #2356
