### ISSUE TITLE
Track list for exercism.io site hard-coded

### ISSUE THREAD

**Issue by canweriotnow** [exercism/exercism.io#2356]
Came up in #2353 (closed now as that was re a specific case).

Via @kytrinyx the problem is: 

> This is a bug. I thought we were driving this list entirely from the API (it certainly is there in config.json), but apparently we're not:
>
> https://github.com/exercism/exercism.io/blob/master/lib/app/views/account/show.erb#L63
>
> It currently uses the hard-coded list in `lib/exercism/config.rb`, but we should be using the same mechanism as the about page, which boils down to: `ExercismWeb::Presenters::Tracks.xapi.active.map(&:language)`

(More details in linked issue).

I might dust off the Ruby gloves and tackle this myself, but I haven't even touched the exercism.io site code, so someone else might be able to resolve it more quickly.

**Comment by kytrinyx** [comment]
This was fixed, and I can't even recall when.
