### ISSUE TITLE
Design beautiful language icons

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2357]
**I am not talking about gamification, just a way of identifying languages on the site.**

These could be used when listing out which languages exist on the site, when displaying a list of languages or a list of exercises. When we get an activity stream, it would be great to have the icons/badges to identify individual feed items, and on a person's profile page it would be a nice touch to be able to list which languages they've submitted solution for and which languages they've provided code critiques in.

Kind of arbirtary statement, but: I love the coderwall.com badges:

![](https://d3levm2kxut31z.cloudfront.net/assets/badges/earlyadopter-1335c30942afc9fa1c5485be48dc1362.png)
![](https://d3levm2kxut31z.cloudfront.net/assets/badges/octopussy-cbba2f305a3527b1d78cc4822b7aec24.png)
![](https://d3levm2kxut31z.cloudfront.net/assets/badges/forked50-90a1ce430f61284eaf701265bcf40ac5.png)

**Comment by jwood803** [comment]
These look really good!

**Comment by kytrinyx** [comment]
Yeah, I'm totally envious :)

To clarify, these are coderwall badges, and I would love to have something that looks as good.

**Comment by perryharlock** [comment]
![exercism-language-logos](https://cloud.githubusercontent.com/assets/1225142/11503805/4e3ff662-983a-11e5-8292-135f5a54211e.png)

Would these be any good to you? Not sure exactly how you are envisaging using them...can split them up into individual png's if you like. Might take a look at the issue to redesign the languages page where these could be used :-) https://github.com/exercism/exercism.io/issues/2634

**Comment by jwood803** [comment]
They all look awesome! Just something to consider, though, it may be best to get permission to use some of these icons. The F# one in particular may need permission.

**Comment by perryharlock** [comment]
Thanks @jwood803 :-) good point too

**Comment by kytrinyx** [comment]
Oh, neat!

Yeah, I suspect that we would need to get permission.

I'd also really like it if we had the same "feel" across all of the icons (does that make sense? My lack of graphical background is definitely showing here). One of the things about the coderwall icons is that they use a consistent color palette (not necessarily all one or two colors, but all of the colors go together really nicely). Another thing is that they are all in the same drawn style (in the above some things have shadows, borders, glossy surfaces, etc whereas others are flat-ish).

**Comment by bordeltabernacle** [comment]
This is a super janky mock up of an idea.  I think it would be nice to avoid just using the language logos.  Aside from permissions, it would associate the badges more with the exercism site.  I'm not enough of an illustrator, nor know enough about each language, to come up with new individual drawings to represent each language in an interesting, yet recognisable way, and so I thought maybe using the language file extensions might work, in each logo's colour scheme.  The devil's horns on the badges align them with the exercism logo/concept.  As I say I just spent a half hour in GIMP on these, they're pretty horrible, you'd want to play around with fonts and whatnot of course.  But, it's an idea...

![exercism_badges_concept](https://cloud.githubusercontent.com/assets/9257284/11654337/ca7c868e-9d9c-11e5-892c-a6fdd1386dfb.png)

**Comment by kytrinyx** [comment]
Thanks @bordeltabernacle, I like that they'd all be recognizably consistent in this way. Another idea that a friend gave me was to use a script that I wrote that will replace colours in an image, and then make all of the images use the exercism colours. I'm going to play around with this for a bit and see what I get.

**Comment by kytrinyx** [comment]
Update: I've been working on this using my hacky script to rewrite colors. It's working out pretty well. Here are some examples:

![python](https://cloud.githubusercontent.com/assets/276834/12076371/ba70fd1e-b166-11e5-9c44-961adc3ee366.png)
![perl-pink](https://cloud.githubusercontent.com/assets/276834/12076372/bd984d44-b166-11e5-8fcc-746c8e473e9a.png)
![java](https://cloud.githubusercontent.com/assets/276834/12076374/c05a1a4e-b166-11e5-9885-ec65d3d2601f.png)
![elisp](https://cloud.githubusercontent.com/assets/276834/12076375/c8d7caae-b166-11e5-8822-3ea662ae4134.png)
![coffeescript](https://cloud.githubusercontent.com/assets/276834/12076376/cba2b8ac-b166-11e5-9ae5-b9d646c6cb10.png)
