### ISSUE TITLE
Exercism as a plugin like disqus for blogs

### ISSUE THREAD

**Issue by aarti** [exercism/exercism.io#2378]
First of all I love exercism and am using it constantly to learn new languages and improve understanding of existing ones. Even without the nitpicks it is extremely valuable. 
BUT 
We would all like to get more nitpicks and to have more discussions like in codereview on stackexchange. Some may also like to blog about our learnings and discussions and have them found in search results.

Recently, I wrote a blog post on Ruby -> Swift, I haven't posted it yet. I did many exercises through exercism. I would like to embed these exercises directly into my blog, sort of like a gist or disqus and have them just show up. Currently, I am having to move all the code I wrote on exercism into gists.

I think there is a lot of value in such a plugin for exercism, as the "core of exercism" can grow organically/virally without the need to have a super/duper UI design or the constant need to encourage  users to nitpick.  

I have been thinking about it, so I thought maybe @kytrinyx and others will like this suggestion. I have  a high level idea on how to build it but that's about it. It would need a new api, and plugins for wordpress, middleman, octopress etc, to get started.

I would love to build something for middleman and try and see if it integrates on my blog, if you can point me to exercism's api.

**Comment by jwood803** [comment]
Interesting suggestion. I'm guessing can just be able to embed each submission?

**Comment by kytrinyx** [comment]
At the moment the API is a bit chaotic and not designed, but we need to re-do it so that we can get control of the front-end, which would make the API very logical and it would be quite easy to have people write extensions like this.

**Comment by nickborromeo** [comment]
Should this be moved to the discussions repo and close this issue?

**Comment by kytrinyx** [comment]
I'm labeling this with design research so that we can discuss it as part of the reboot once we get to it. I'll close this, since we'll be looking at both open and closed `design research` discussions.

Thanks @nickborromeo
