### ISSUE TITLE
username case is sometimes ignored

### ISSUE THREAD

**Issue by chillpop** [exercism/exercism.io#2384]
Users with uppercase letters in their GitHub username do not show any exercises on their excercism user page.

Example: 
user JilScott shows no exercises here: http://exercism.io/JilScott
but she has completed exercises: http://exercism.io/submissions/b91411f3f33e4d06abad9ad20d6ccd8f

**Comment by Dog** [comment]
I'm not sure this issue is relevant to username case. As an example, I see exercises when I look up my own name. Also when I try going to http://exercism.io/jilscott I still see no completed exercises.

**Comment by chillpop** [comment]
I may have been too hasty in assuming it was a name case issue.  There may be something up with that user in particular.

**Comment by kytrinyx** [comment]
I have had a bit of a problem with some ghost users due to an old bug in the team invite code. The bug was fixed a while back, and I thought I had cleared out all the ghosts, but this one was left. It should be good now.

**Comment by chillpop** [comment]
Excellent.  Thank you.
