### ISSUE TITLE
Unable to Join Team

### ISSUE THREAD

**Issue by JilScott** [exercism/exercism.io#2385]
I was invited to a team and have received the invitation to Accept or Decline. After clicking 'Accept Invitation' I am directed to "http://exercism.io/onboarding/have-a-conversation" but do not seem to actually be added to the team. The outcome is the same when accepting invitation through notifications as well as my account page. How do I remedy this?

**Comment by Dog** [comment]
Perhaps your issues are related to a ghost user:
https://github.com/exercism/exercism.io/issues/2328

@kytrinyx would probably need to assist you.

**Comment by kytrinyx** [comment]
Hey, sorry about the delay in getting on this. Yes, there was a ghost user problem here. I thought I had fixed this, but clearly I have not! Also, I think I lost your invitation when I tried patching this up. Would you ask them to re-invite you?

**Comment by JilScott** [comment]
Thanks for coming to the rescue! Will have them re-invite me.

**Comment by kytrinyx** [comment]
Thanks! Meanwhile I'll try to figure out how this is happening! Sorry for the mess.

**Comment by tashoecraft** [comment]
Same problem

**Comment by kytrinyx** [comment]
@tashoecraft you should be able to log in now.

**Comment by Fraelich** [comment]
Same problem as well.

Thanks,
Al

**Comment by kytrinyx** [comment]
@Fraelich I think you might be good. Would you try again?

**Comment by Fraelich** [comment]
It worked, thank you!

Al

On Sat, May 16, 2015 at 3:51 PM, Katrina Owen <notifications@github.com>
wrote:

> @Fraelich <https://github.com/Fraelich> I think you might be good. Would
> you try again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/exercism.io/issues/2385#issuecomment-102701630>
> .
>



-- 
Al

**Comment by kytrinyx** [comment]
Fixed a couple weeks back, let me know if you still have issues.

**Comment by Peque** [comment]
It is working now. Thanks a lot. :blush:
