### ISSUE TITLE
fetch fails with "Error parsing API response"

### ISSUE THREAD

**Issue by ccblaisdell** [exercism/exercism.io#2386]
elixir|⇒ exercism fetch
    Error parsing API response: [invalid character '<' looking for beginning of value]

I've been using exercism up to this point with no problems. My latest exlir exercise was "grains," although I recently doubled back for another pass at "meetup."

`exercism debug` just prints `No help topic for 'debug'`, and the contents of ~/.exercism.go are:
`{"githubUsername":"ccblaisdell","apiKey":"<removed_api_key>","exercismDirectory":"/Users/ccblaisdell/exercism","hostname":"http://exercism.io"}`

**Comment by Tonkpils** [comment]
@ccblaisdell It seems as if you have an older version of the exercism CLI.  Could you upgrade to the latest version and let us know if you still have this issue?

**Comment by ccblaisdell** [comment]
Updating the CLI fixed it. Thanks for the help!

**Comment by Tonkpils** [comment]
Cool! this can be closed :+1:

**Comment by kytrinyx** [comment]
Thanks! Glad it got sorted.
