### ISSUE TITLE
Exercism runs, but unable to configure with API key

### ISSUE THREAD

**Issue by KrishanBhasin** [exercism/exercism.io#2393]
When I run 'exercism', I get the help list, and when I try to submit, it tells me I need to add my API key still.
When I run exercism configure --key=xxxxxxxxxx, I get:
"open ~ .exercism.json: The system cannot find the path specified"
What do I do?

**Comment by kytrinyx** [comment]
What happens if you say `exercism debug`?

**Comment by cadrev** [comment]
Hi @kytrinyx, I've also was able to encounter @KrishanBhasin 's issue with the latest version (v2.1.0 64bit Windows), I've downloaded a lower version of exercism (v1.9.2) and the command "exercism --config=/path/to/config.json configure --key=abc123" works and I was able to get my exercism tool up and running. :D

**Comment by KrishanBhasin** [comment]
C:\exercism>exercism debug

**** Debug Information ****
Exercism CLI Version: 2.1.0
OS/Architecture: windows/amd64
Home Dir: C:\Users\Krishan
Config file: <not configured>
API Key: <not configured>
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: C:\Users\Krishan\exercism

If you are having trouble and need to file a GitHub issue (https://github.com/ex
ercism/exercism.io/issues) please include this information (except your API key.
 Keep that private).


I'm going to try downloading 1.9.2 to see if I get the same error

**Comment by KrishanBhasin** [comment]
I rolled back to v2.0.2 and it works fine!

When I had v2.1.0, the .json file was locked when i viewed it in windows explorer, FYI

**Comment by kytrinyx** [comment]
Hi @KrishanBhasin and @cadrev thanks for the debug info and figuring out the workaround. I may ask you for more information as I try to figure out what went wrong.

/cc @lcowell @Tonkpils

**Comment by Tonkpils** [comment]
Looking into it, at first glance it might be the home path expansion for windows.

**Comment by kytrinyx** [comment]
This is released here: https://github.com/exercism/cli/releases/tag/v2.1.1
