### ISSUE TITLE
Add exercise: Balanced parenthesis

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#2394]
Write a function that takes a string and returns `true` if the parentheses are balanced within the string.  Parentheses are balanced if every opening parenthesis character `(` is followed by a matching closing parenthesis character `)`.

In this form the exercise is pretty simple.  The exercise can be made more difficult by including other forms of open/closed pairs: `<` and `>`, `{` and `}`, `[` and `]` and requiring that balance means that each form must be closed without straddling another open pair.

Examples:
* `"()"` is balanced
* `"(()"` is not balanced
* `")("` is not balanced
* `"[()]"` is balanced
* `"[(])"` is not balanced
* `"Hello (world)!"` is balanced

Source: a [discussion on usenet](https://groups.google.com/forum/#!topic/comp.lang.c++/EwE1asaBjNQ)

**Comment by kytrinyx** [comment]
We have something similar, which might be worth expanding on: https://github.com/exercism/x-common/blob/master/bracket-push.md

The README is nominal and could definitely use more work. It's only been implemented in JavaScript at the moment:

https://github.com/exercism/xjavascript/tree/master/bracket-push

**Comment by LegalizeAdulthood** [comment]
Yeah, that looks like a duplicate of this, we should merge these two problems together.

**Comment by kytrinyx** [comment]
The bracket-push problem description was made more ambiguous to allow other types of matched tokens.
