### ISSUE TITLE
Install CLI page is redirecting to fault page

### ISSUE THREAD

**Issue by kumarmanishbit** [exercism/exercism.io#2395]
This link is not working:- 
http://hootcode.com/installing-cli

Regards ,
Manish

**Comment by tejasbubane** [comment]
What is hootcode? How is it related to exercism? @kytrinyx

**Comment by kytrinyx** [comment]
I don't know anything about hootcode.

@kumarmanishbit Where did you see this link?

**Comment by Tonkpils** [comment]
Seems like a clone... https://github.com/hanumakanthvvn/exercism.io

**Comment by kytrinyx** [comment]
Ah, probably a school or university setup. I'm going to close this, the links should be fixed on the fork, not in exercism.
