### ISSUE TITLE
Adding a Rust language track

### ISSUE THREAD

**Issue by adolfosilva** [exercism/exercism.io#2397]
Now that [Rust](http://www.rust-lang.org/) 1.0 has been released it would be cool to have a Rust language track.

**Comment by pminten** [comment]
We have a rust language track, now that 1.0 is out it just needs some finishing touches before it can be put live. See e.g. exercism/xrust#3.

**Comment by adolfosilva** [comment]
Ah, sorry. Didn't see it.
