### ISSUE TITLE
Identify outdated submissions

### ISSUE THREAD

**Issue by crackofdusk** [exercism/exercism.io#2398]
I noticed that some problems get updated. However the only way to know is if you look at the output of the command line client after you fetch new exercises. Even then it's easy to forget, because the information is only shown once.

I think two things would be helpful to remind users of updates:

1. A notification that an exercise you have worked on has been updated
2. Some indication on the submission/iteration page that a submission was added before the latest version of the test suite.

**Comment by kytrinyx** [comment]
Yeah, this would be helpful.

At the moment the way that we store the exercises (flat files) doesn't give us any obvious ways to track versions. We could probably add some metadata (or even just a hidden file with a number in it).

**Comment by mandel01** [comment]
In particular, it would be helpful for a nitpicker to know if the test suite has been updated since they submitted their last iteration. I had a case today where I (incorrectly) nitpicked an exercise in Python's Word Count exercise. Part of the issue was that the code failed the tests on Python 3 (I had the current test suite installed). However, part of the issue was that the advice I was giving worked for when I submitted my last iteration 7 months ago but not based on the latest change in the test suite, 26 days ago.

**Comment by kytrinyx** [comment]
Good point. Being able to say: "you last solved version X, but this is version Y" is exactly what the person reviewing would need to hear.

**Comment by kytrinyx** [comment]
We've added a bit of book-keeping / versioning to a number of tracks. I'm going to close this, as the versioning provides a workaround. If this continues to be a problem we should reconsider how to tackle it.

**Comment by mandel01** [comment]
Related to this, is there a way to pull/fetch the latest version of the readme & test suite for a problem? I did python hello-world a couple years ago. My sample doesn't pass the current test suite. Here is what I tried (I was getting a new local user set up on exercism... I have it installed on Mac via homebrew).

Should `exercism fetch` have updated the test suite in this case? 

I noticed that `exercism fetch` has an `--all` flag. In the future will `exercism fetch <track> <exercise>` or `exercism fetch --all` fetch the latest version of the readme & tests? If not, would you consider a `-f` / `--force` flag for this purpose?

```
➜  ~ exercism upgrade 
Your CLI is up to date!
➜  ~ exercism -v
exercism version 2.3.0
➜  ~ exercism fetch python hello-world

unchanged: 1, updated: 0, new: 0

➜  ~ exercism fetch -f python hello-world
Incorrect Usage.

NAME:
   exercism fetch - Fetches the next unsubmitted problem in each track.

USAGE:
   exercism fetch [command options] [arguments...]

OPTIONS:
   --all  fetch all exercises for a given track
   
```

 I know that you @kytrinyx have been doing a ton of work on exercism issues recently. Feel free to ignore this if this is already related to ongoing changes. I didn't see the versions online so perhaps they are still in process. You can leave this issue closed and I can check back in the future...

And happy to help in a more substantive way if there is something non-ruby to contribute here.
