### ISSUE TITLE
Where is the Python hello_world README.md file?

### ISSUE THREAD

**Issue by mandel01** [exercism/exercism.io#2399]
I think I found a typo in the Python hello_world README.md file and I wanted to use this opportunity to learn how to do a git pull request. Part of the instructions advise the user to write "Hello world!" but the answer is only accepted if the user submits "Hello, world!" When I look on Github I can find the repository at xpython/hello-world/ but there is no README.md file. How I can edit the file and submit the change request? Thanks for any help here.

**Comment by jwood803** [comment]
Is it this one?

https://github.com/exercism/xpython/blob/master/README.md

**Comment by kytrinyx** [comment]
No, the problem READMEs are shared between all 23 languages:
https://github.com/exercism/x-common/blob/master/hello-world.md

**Comment by mandel01** [comment]
Thank you. I found the text in the hello-world.yml file. This file must
display as part of the README.md file in the command line interface. I
initiated a pull request.

**Comment by kytrinyx** [comment]
Awesome, thanks
