### ISSUE TITLE
error parsing API response - invalid character '<'   MacOSX

### ISSUE THREAD

**Issue by tigerstripe40** [exercism/exercism.io#2400]
exercism version 1.6.2

I've been working a few of the different languages for a while (C++, Objective C, Python, Java, Javascript). Now I have been working the PHP track. 

I have submitted the first PHP exercise Hamming successfully, however, when I try to pull the next exercise I get: Error parsing API response: [invalid character '<' looking for beginning of value]

I have tried logging out of exercism, then logging back in. 
When I do 'exercism configure --key= -MyAPIKeyRedacted-'  I get: "No help topic for 'configure'"

If I do 'exercism debug' I get: "No help topic for 'debug'"

**Comment by Tonkpils** [comment]
Your version of the `exercism` CLI is pretty outdated. Could you update your CLI and see if that fixes the issue?

**Comment by tigerstripe40** [comment]
Updating the CLI resolved it. Thanks.
