### ISSUE TITLE
Xcode Project Generator

### ISSUE THREAD

**Issue by nickkjordan** [exercism/exercism.io#2401]
For Swift and Obj-C, I think it would be useful to have a script that setups an Xcode Project around a Test file, which might lower the barrier for people with less experience in Xcode or true beginners.  

I started working on a [script in Ruby](https://gist.github.com/nickkjordan/8d79a08301f3ec480313), but I'm unsure if [Xcodeproj](https://github.com/CocoaPods/Xcodeproj) can build with test target right now ([issue: 227](https://github.com/CocoaPods/Xcodeproj/issues/227))

**Comment by kytrinyx** [comment]
/cc @masters3d @hankturowski @chillpop -- do you have any thoughts about this?

@nickkjordan could package his ruby script as a gem, and we could point to it in the documentation.

**Comment by hankturowski** [comment]
I don't think that I like the idea. With Swift and Xcode changing so rapidly, it seems like the solution would be too fragile. We would have to test each exercise every time there was an update. And, to be honest, if a user can't set up an Xcode project, they're probably not ready to tackle many of the exercises.

How about this as an alternative: We could check a full Xcode project into GitHub, maybe preconfigured with the (not yet written) Hello World exercise, with instructions on how to add new exercises to that project. In my local environment, I have all of the exercises set up in a single project and it works nicely. Adding new tests is as easy as dragging them to the right folder, and making sure the correct target is selected on input.

**Comment by chillpop** [comment]
I agree with @hankturowski's alternative.  I've also set up a single project that same way.  I've been meaning to write up how to do it for the obj-c setup instructions. Having an example included with the Hello World exercise would be a simpler quick start for new users.

**Comment by nickkjordan** [comment]
Fair enough, that sounds better to me too

**Comment by kytrinyx** [comment]
This sounds like a great direction. If either of you have a good grasp of what this would look like, would you add an issue to the Swift track and the Objective-C track describing it?

**Comment by chillpop** [comment]
@kytrinyx, where would the project files live so that they are delivered to users when they start an exercise?

**Comment by kytrinyx** [comment]
Would it be awful to put them in the hello world directory? That would deliver them by default when they pull the problem.

**Comment by chillpop** [comment]
Not awful, but not ideal either.  I don't suppose there's a mechanism in place to include track-level resources instead of exercise-level resources?  If not, having the project delivered with hello world would be ok.

**Comment by hankturowski** [comment]
I can't think of anything that would stop that from working. The directory structure will be a little bit odd, but not unmanageable. The issue will be when the user creates the solution file, they'll need to put it in the exercise folder at the file system level so the exercism CLI can find it.

What if we start including an empty solution file along with the test file? Adding them both to the Xcode project after download isn't much harder than adding one, and it would ensure that the solution is in the right place.

**Comment by kytrinyx** [comment]
Yes, let's include an empty solution file. That seems cheap and easy.

We currently don't have a way to deliver track-level content, but it's been asked for in the past. I can't see that it would be difficult, it's just competing with a bunch of other priorities:
https://github.com/exercism/x-api/issues/29

**Comment by chillpop** [comment]
I've created exercism/xobjective-c#27 for this.

**Comment by kytrinyx** [comment]
thanks

**Comment by RichardBronosky** [comment]
You could include a compressed file like https://dl.dropboxusercontent.com/u/310759/u/ExercismObjectiveCExampleProject.tgz and add to the README files how to:

    curl https://dl.dropboxusercontent.com/u/310759/u/ExercismObjectiveCExampleProject.tgz | tar zx

I think that should cover it. I added a script in there so that the actual instruction could be to:

    curl https://dl.dropboxusercontent.com/u/310759/u/ExercismObjectiveCExampleProject.tgz | tar zx && ExerciseName/setup.sh

That would cause all the Xcode projects to have the same name, but...
1. It would be in your properly named exercise directory, so you'd know what exercise it was for.
1. It is an Xcode project created with actual Xcode, so it should work with many future versions of Xcode just like all of your existing projects continue to work with future versions (aside from API changes that shouldn't affect a bare bones project like this).

**Comment by masters3d** [comment]
I think we addressed this with the creation of the hello word exercise Xcode project. 

I don't know about objective-c but as far as swift goes, I'd like to move it away from depending on Xcode projects once swift 2.2++ becomes available on Windows. 

https://github.com/exercism/xswift/issues/2

**Comment by kytrinyx** [comment]
Excellent. Thanks!
