### ISSUE TITLE
mobile help sidebar not wide enough for CoffeeScript

### ISSUE THREAD

**Issue by odeits** [exercism/exercism.io#2403]
Will attach scrrenshot

**Comment by odeits** [comment]
![screenshot_2015-05-22-13-37-13](https://cloud.githubusercontent.com/assets/1048498/7779293/06b4d1f4-0088-11e5-8ce5-5981b2167465.png)

**Comment by kytrinyx** [comment]
The help/docs site is pretty terrible in general. Someone started working on a redesign that I think would fix this. I'll see if I can help move that forward.

Thanks for reporting it.

**Comment by kytrinyx** [comment]
Actually, there might also be a smaller fix that we can put in place in the meanwhile :)

**Comment by alexclarkofficial** [comment]
I think this is fixed by https://github.com/exercism/docs/pull/150. It was a bit weird specifying widths without meta tag for responsive design, so this might not be perfect.

**Comment by kytrinyx** [comment]
I believe so! Thanks. The design has some issues, so perfect is unlikely to happen no matter how good the change is, unfortunately!

**Comment by kytrinyx** [comment]
I'm going to close this, but feel free to re-open it if it turns out that it's not actually fixed.
