### ISSUE TITLE
Haskell - Unable to Submit

### ISSUE THREAD

**Issue by psycotica0** [exercism/exercism.io#2404]
I've been working through a bunch of problems, and last night I fetched down robot-simulator in haskell.

I solved it this morning, and when I went to submit it I get:

    $ exercism submit Robot.hs
    2015/05/23 08:10:18 unable to submit (HTTP: 400) - unknown problem (track: haskell, slug: robot-simulator, path: )

So, I figured something might be weird, and did:

    $ exercism skip haskell robot-simulator
    2015/05/23 08:04:44 Exercise 'robot-simulator' in language 'haskell' doesn't exist. Maybe you mispelled it?

Now, I'm looking at the repo, and it looks like it's there.
And I'm in the folder right now.

If I do `exercism fetch` I see `haskell (Robot Simulator)     /home/psycotica0/exercism/haskell/robot-simulator`

Looking at the repo, it looks like queen attack is next and I'll just move on to that manually, but I thought you might want to know.

Thanks!

Exercism's Debug gives me:

    **** Debug Information ****
    Exercism CLI Version: 2.0.2
    OS/Architecture: linux/amd64
    Home Dir: /home/psycotica0
    [...]

**Comment by psycotica0** [comment]
$ exercism submit Queens.hs 
    2015/05/23 09:01:31 unable to submit (HTTP: 400) - unknown problem (track: haskell, slug: queen-attack, path: )

Alright, so the problem wasn't robot simulator.

**Comment by alukito** [comment]
Hi, I'm having the same problem with gigasecond haskell exercise. I noticed on the error message that the path field was always empty no matter what parameter I gave. 

```
$ exercism submit Gigasecond.hs
2015/05/23 20:18:26 unable to submit (HTTP: 400) - unknown problem (track: haskell, slug: gigasecond, path: )
```

My exercism debug:

```
**** Debug Information ****
Exercism CLI Version: 2.1.0
OS/Architecture: darwin/amd64
Home Dir: /Users/kuang
Config file: /Users/kuang/.exercism.json
API Key: <stripped>
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/kuang/exercism
```

**Comment by montlebalm** [comment]
Same issue here with Ruby. Might be an API outage, though I wouldn't expect a 400 in that case.

**Comment by kytrinyx** [comment]
This is my bad--I'm fixing it now. So sorry about that!

**Comment by kytrinyx** [comment]
This should be good now. Apologies again!

**Comment by psycotica0** [comment]
Looks like it worked to me!
Thanks!
