### ISSUE TITLE
Submit

### ISSUE THREAD

**Issue by Hungrybryce** [exercism/exercism.io#2406]
Hi I am new to exercism. Because I don't know much about Maps in java I am trying to submit my test so that I can ask for help. When I try to submit I get something like this: 
TheDate TheTime GetFileAttributesEx FullPathToMyProgectFolder\C;: The system can not find the file specified.

I can see why this fails because this file does not exist is it supposed to? Also is there a way to see other exercises because I know nothing about java Maps and want to try something else?

**Comment by kytrinyx** [comment]
What does `exercism debug` output?
Where on your file system are you when you're trying to submit the file?
What is the exact command that you're using to submit the file?

**Comment by Hungrybryce** [comment]
For some reason it now works. I will show you the other problem with gradle. Here are photos if something is not clear ask. Thank you very much for your help. I am new.
![win_20150525_104126](https://cloud.githubusercontent.com/assets/5306832/7800491/eab7a964-02ca-11e5-8e7d-0475e35e92ef.JPG)
![win_20150525_104139](https://cloud.githubusercontent.com/assets/5306832/7800489/eab5dc74-02ca-11e5-849e-88ce8023e4d7.JPG)
![win_20150525_104146](https://cloud.githubusercontent.com/assets/5306832/7800490/eab75c98-02ca-11e5-88c2-d6a3f6ca896a.JPG)
![win_20150525_104147](https://cloud.githubusercontent.com/assets/5306832/7800492/eabae4d0-02ca-11e5-988d-1bc0b85f1ccc.JPG)

**Comment by kytrinyx** [comment]
Try: `cd C:\Users\bryce\exercism\java\etl` then `gradle test`

**Comment by kytrinyx** [comment]
I'm closing this. Please reopen or submit a new issue if you are still having trouble.
