### ISSUE TITLE
Java Etl

### ISSUE THREAD

**Issue by Phoshizzle** [exercism/exercism.io#2408]
Hi,
I'm having trouble getting everything setup for the java exercises. I have exercism, gradle, and eclipse installed. I am unsure if I am supposed to edit EtlTest.java because it gives me the error com.google cannot be resolved.

**Comment by Phoshizzle** [comment]
Ok I figured it out I think. I needed to convert the project to a Gradle project instead of having it just as a Java Project

**Comment by kytrinyx** [comment]
Glad you got it sorted. Is there something we could have put in the documentation (http://help.exercism.io/getting-started-with-java.html) or elsewhere to make it easier to get it working?

**Comment by Phoshizzle** [comment]
Well the link for IDE integration called Gradle Tooling does not go anywhere, so perhaps a step by step approach. I've never really used gradle so I wasn't entirely sure what it did. But along the same vein, in Nucleotide, we are not supposed to change the test.java file?

**Comment by kytrinyx** [comment]
@jtigger Would you mind helping figure out the details here (or perhaps figure out if someone involved in the track can help figure out the details)?

**Comment by jtigger** [comment]
No prob. Perhaps the most enduring way is to include the command-line steps to generate the IDE project files from Gradle, directly.  I'll craft up some language for it.

**Comment by kytrinyx** [comment]
Awesome, thanks!
