### ISSUE TITLE
web stats on available tasks?

### ISSUE THREAD

**Issue by techtonik** [exercism/exercism.io#2409]
I want to see what types of exercises are available without downloading. Is that possible?

**Comment by kytrinyx** [comment]
We're working on a whole section of the website for this, but in the meanwhile you can use http://synopsis.exercism.io/

**Comment by techtonik** [comment]
Nice. Thanks.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this in favour of #2299. Thanks.
