### ISSUE TITLE
Account Exercises always displays "You have not completed any exercises yet."

### ISSUE THREAD

**Issue by pussinboot** [exercism/exercism.io#2410]
![error](https://cloud.githubusercontent.com/assets/6570054/7868245/a7427bde-0548-11e5-839a-f4022ac1fb2a.PNG)

**Comment by kytrinyx** [comment]
Oh, nice find. Definitely a bug, and probably a quick fix. Thanks!

**Comment by joesiewert** [comment]
I looked at this locally and it seems like there is a distinction between current and completed exercises.  Maybe not a bug?

![screen shot 2015-06-01 at 9 51 33 pm](https://cloud.githubusercontent.com/assets/1104976/7927620/875f735e-08a8-11e5-9284-7e74e8160912.png)

**Comment by pussinboot** [comment]
Guess it's not a bug then, whoops.
Until just now I had not realized I could mark exercises as complete, so maybe hyperlink the word "completed" to a page explaining how to do so?

**Comment by kytrinyx** [comment]
That's a great idea, thanks!

**Comment by MartinDelille** [comment]
Is this issue still valid?

**Comment by kytrinyx** [comment]
No, we took it off, thanks!
