### ISSUE TITLE
Delete team memberships when deleting a team

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2411]
I can't remember how the team deletion stuff is handled, but we currently have orphan team memberships in the database, so we may not be deleting associated memberships.

**Comment by mfrost** [comment]
Can you supply some more information about the orphaned records? The schema appears to have `NOT NULL` constraints: `ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "team_id" violates not-null constraint`. It appears that `dependent: :destroy` is set up correctly, too.

**Comment by kytrinyx** [comment]
OK, cool. I bet when we added the constraints we didn't delete orphans. I'll go ahead and do that today. Thanks for looking into this!
