### ISSUE TITLE
Got PG::UniqueViolation when submitting solution

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2412]
We got the following error in production recently:

```plain
PG::UniqueViolation ·
lib/exercism/use_cases/updates_user_exercise.rb:23
-----------------------------------------------------------------

ERROR: duplicate key value violates unique constraint
"index_user_exercises_on_user_id_and_language_and_slug"
```

This has only ever happened once. Do we have a possible race condition here?

**Comment by Insti** [comment]
Did this ever happen again? If not we can probably close this issue.

**Comment by kytrinyx** [comment]
I don't think it did. I'm closing it and we can reopen if we see it again.
