### ISSUE TITLE
Hibernate and Done status changes for problems.

### ISSUE THREAD

**Issue by kotp** [exercism/exercism.io#2415]
I think there used to be a Hibernate check box to hibernate problems.  The manage pull down in the problem will mark the problem as done, but there doesn't seem to be feedback on how to bring it back out of the 'done' status.

This is the done status activator, as it should be:

![showing_done_option_as_it_should_be](https://cloud.githubusercontent.com/assets/16747/7997355/8e0862c6-0af9-11e5-822c-8bcb24cda078.png)

This is showing the mechanism for unsetting the 'done' status:

![easy_way_to_change_done_status](https://cloud.githubusercontent.com/assets/16747/7997361/a893412e-0af9-11e5-9e69-da458c9de9fd.png)

But I thought that there used to be a 'hibernate' button near the bottom of the submission area...

![no_hibernate_option](https://cloud.githubusercontent.com/assets/16747/7997367/c47f1a8e-0af9-11e5-963a-4572a6f22609.png)

And this shows no 'Hibernated' section (and it is correct, as I moved them out of 'hibernate' by marking them 'done', but was thinking I could move a couple into 'hibernate' mode.)

![no_hibernate_section_appropriate](https://cloud.githubusercontent.com/assets/16747/7997375/ec9a7fea-0af9-11e5-9468-2c5fc5967e7a.png)

**Comment by kytrinyx** [comment]
> I think there used to be a Hibernate check box to hibernate problems. 

No, I don't think so. I believe that hibernation has always been an automated process--there's a cron job that runs daily: `lib/tasks/hibernation.rake`.

We could easily add a "hibernate" action in the management dropdown, though.

**Comment by kotp** [comment]
I wonder if having the ability to put them in hibernate mode manually would be helpful.  As in "not quite done, but not ready for feedback right now".  That is how I wanted to use the feature with those that I am "cheating" and submitting out of order.

**Comment by kytrinyx** [comment]
Yeah, I like that. Like a hiatus.

**Comment by treiff** [comment]
I was just looking into this but wanted to make sure I was on the right track before I get going.

My thoughts were obviously adding the "hibernate" option to the dropdown, and posting to a new route in ```lib/app/routes/exercises.rb``` where we're changing the submission state.  

Reasonable?

**Comment by kytrinyx** [comment]
Yeah, that works for me.

We're going to be re-evaluating the idea of submission states, but it's going to take a good long while to get to it, so this would probably be a good workaround in the meantime. Thanks!
