### ISSUE TITLE
The nitpick edit page probably shouldn't ask the user if they want to stay or leave the page when they submit or delete

### ISSUE THREAD

**Issue by trayo** [exercism/exercism.io#2418]
Currently if you change any of the text on the edit nitpick page, it will prompt you if you want to stay
on the page or leave the page when you click submit or delete.

If you chose to stay on the page, it disables the buttons and makes them unusable.

You can leave the page and everything will function normally, but the message given to the user
is scary/unclear about what will happen if they chose to leave the page.

![image](https://cloud.githubusercontent.com/assets/6809782/8071975/e12ef10a-0ecc-11e5-830b-9b679baca17a.png)

**Comment by kytrinyx** [comment]
Yeah, we should just disable that.

**Comment by trayo** [comment]
Site wide? I remember where the javascript for it is handled.

**Comment by kytrinyx** [comment]
I'm thinking it should probably be disabled on the nitpick edit page only

**Comment by GustavoCaso** [comment]
@trayo I have been looking in the code but no sign of the `confirm` is there anything I'm missing ?

**Comment by kytrinyx** [comment]
The behavior is still in place, but I have no idea how it's done. The codebase doesn't make mention of the explicit text, so it seems like it might be using some third party extension (...?) to do this.

**Comment by GustavoCaso** [comment]
@kytrinyx ok I will continue poking around.

**Comment by trayo** [comment]
@GustavoCaso Sorry for the late reply, I just confirmed that this still exists. I think the code for it is [here on line number 30359](https://github.com/exercism/exercism.io/blob/master/lib/app/public/js/app.js#L30359)

Or at least that's where it's mentioned.

**Comment by GustavoCaso** [comment]
Thanks @trayo

**Comment by kytrinyx** [comment]
Once you find the code, look for it in the coffeescript under `frontend`, I think, otherwise it will go away when we compile it.

**Comment by kytrinyx** [comment]
Actually, I take that back. Check out frontend/app/js/script.js

**Comment by GustavoCaso** [comment]
Great @kytrinyx. I saw it, also that you need `lineman` running for the code to take affect in development.
I hope to have it finish by tomorrow.

**Comment by TimMoore** [comment]
Can this be closed since #2617 was merged?

**Comment by GustavoCaso** [comment]
Of course

**Comment by kytrinyx** [comment]
Thanks!
