### ISSUE TITLE
Copy to Clipboard not working

### ISSUE THREAD

**Issue by daniellecloss** [exercism/exercism.io#2419]
I seem to not be able to copy to clipboard the code from the exercise submissions in safari on a mac.  I click the copy to clipboard button on a submission page on the exercism.io website, then the alert pops up and says "The submission code was successfully copied to your clipboard!", but when I do a paste into my text editor, that last thing I pasted is there, instead of the copied code from the exercise submission.  My mac has all the latest OS and software updates.  Let me know if you need more details, thanks!

**Comment by kytrinyx** [comment]
Thanks for the heads up!

**Comment by ethangodt** [comment]
I'm also using Safari and OS X, but it's working for me. Can copy into WebStorm fine.

**Comment by kytrinyx** [comment]
Thanks! This is likely fixed in a more recent version of Safari. @anastasiavixen Are you still experiencing this issue? If so, would you note the version of Safari that you're using?

**Comment by anastasiavixen** [comment]
I want to make a note that I have my mac set to use the tap as a click on the touchpad, and I wonder if that is part of the problem.  When I actually use the touchpad with the push down as click, it works fine.  When I use the tap as a click, I am seeing an issue only the first time I use the copy to clipboard button.  When I use it the second time, it does work.  It is repeatable after full refresh of the page as well.  My safari version is Version 8.0.6 (10600.6.3)  So, this is really a very minor issue, as I am not sure how many people would even run into it.  I hope that helps!

**Comment by kytrinyx** [comment]
Interesting! I tried reproducing it, and tap-click gives me a warning about my flash player being out-dated! Not exactly what I was expecting. After upgrading flash tap-click worked as expected.

**Comment by krishandley** [comment]
There is a non flash alternative if you are interested http://clipboardjs.com and has a fallback for Safari.

**Comment by kytrinyx** [comment]
Fixed in #2664
