### ISSUE TITLE
Next Submission button goes to top of list after leaving Nitpick

### ISSUE THREAD

**Issue by ifpingram** [exercism/exercism.io#2420]
I am not sure if this is a bug or by design. After I leave a Nitpick, when I click on the Next Submission button, it goes back to the start of the list of "Pending Submisison" Nitpicks, e.g.

[http://exercism.io/nitpick/php/hamming]

The further through the submissions I go, the longer it takes for me to get back to the submission I left the Nitpick on, in order to then view the following one. It feels a bit like Schlemiel the Painter.

**Comment by kytrinyx** [comment]
Weird, no this is not intentional. Thanks for reporting it!

**Comment by kytrinyx** [comment]
I believe this is fixed. Closing, but please re-open it if you are still seeing weird behavior!
