### ISSUE TITLE
feature request: Go to my implementation

### ISSUE THREAD

**Issue by schorsch3000** [exercism/exercism.io#2421]
Hi,
quite often while reviewing submitted code from others i'll look into my own implementation, it would be nice if, on any submission page, were a button that points me directly to my implementation of the same exercise.

**Comment by kytrinyx** [comment]
This is a good idea and very easy to implement. Thanks for suggesting it.

**Comment by wobh** [comment]
Isn't that what the little rocketship button next to the binocular's button does?

**Comment by kytrinyx** [comment]
Ooh. I forgot about that. Yes, that's what the rocket ship is. Thanks, @wobh.

**Comment by schorsch3000** [comment]
How did i not see this? sorry.

**Comment by kytrinyx** [comment]
It's not obvious--design/ux is a little rough here.
