### ISSUE TITLE
NameError: uninitialized constant Hamming::VERSION

### ISSUE THREAD

**Issue by Diope** [exercism/exercism.io#2422]
Going through the Hamming (ruby track) exercise and I've got this TDD error.  So far I've got

    class Hamming
	    def self.compute(a,b)
		    0
	    end
    end

Any direction/hint on the right direction would be much appreciated.

**Comment by Diope** [comment]
Did not mean to close it.

**Comment by wobh** [comment]
What's the error?

**Comment by kytrinyx** [comment]
> What's the error?

The error is in the subject, I think: `NameError: uninitialized constant Hamming::VERSION`

In Ruby a `NameError` means that the code is referring to something that is undefined. In this case, it's seeing a constant (`Hamming::VERSION`) and it's looking it up and not finding it.

The thing to do to fix it is to define it in your code. Do you see how you would do that here?

**Comment by Diope** [comment]
I found the solution, in the hamming_test file it says:

    This test is for the sake of people providing feedback, so they know which version of the exercise you are solving.
      def test_bookkeeping
        assert_equal 1, Hamming::VERSION
      end
Doesn't seem like it's necessary for end users who are going through the course.

**Comment by wobh** [comment]
Okay so I obviously haven't been keeping up on the Ruby track, so I was quite surprised to learn this had been added. I agree with @Diope and then some. Versioning is pretty far outside the scope of test suite's principle purpose.

**Comment by kytrinyx** [comment]
The versioning is because people often land on old solutions and complain that they don't pass the tests. They did, however, pass the tests at the time of writing the solution. The versioning makes it obvious which version of the problem they solved.

**Comment by kytrinyx** [comment]
> Doesn't seem like it's necessary for end users who are going through the course.

It avoids accusations at a later date that you didn't solve the problem correctly.

I'll add an error message to the test, in the hopes that it will be less confusing and distracting to others.

**Comment by kytrinyx** [comment]
I just saw that the VERSION test hadn't been skipped, which was an oversight. That error should have been the last one that you saw, not the first one. So sorry about that!

I've submitted a pull request that changes this: https://github.com/exercism/xruby/pull/169

**Comment by ahimsauzi** [comment]
Can you post where we can find the said exercise version? Thanks.
```
# This test is for the sake of people providing feedback, so they
# know which version of the exercise you are solving."
```

**Comment by kickinbahk** [comment]
This is still confusing in my opinion.  

The test says
```
70  def test_bookkeeping                                                                                                                                                                                                                 
71    assert_equal 1, Hamming::VERSION                                                                                                                                                                                                   
72  end         
```

The error that is being received makes you think that you need to create a class which gives this error
```
  1) Failure:
HammingTest#test_bookkeeping [hamming_test.rb:71]:
Expected: 1
  Actual: Hamming::VERSION
```

There is no easy way to search for what is being asked for (try googling exercism ::version or hamming::version) you mostly get this github ticket.

I did eventually figure it out by trying different options and eventually putting `VERSION = 1` in the Hamming class. However, I was still not sure why it works or what the :: meant in this case. I had thought it meant "inherits from," rather than "of class." Personally, I would have loved an additional comment to ruby documentation. This is the ruby doc page referring to using constants: http://ruby-doc.org/docs/ruby-doc-bundle/UsersGuide/rg/constants.html

Being that it is the second exercise, I think a little more clarity would help.

**Comment by kytrinyx** [comment]
Yeah, that's a good point. I'll add a comment to the failure in the test that explains about constants.
