### ISSUE TITLE
Stuck on Setting up Database

### ISSUE THREAD

**Issue by chesterl** [exercism/exercism.io#2423]
As per Katrina's request, I'm opening an issue on where I got stuck. After cloning the project, I am trying to set up the database.
I have followed https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#setup 
up until the *Data* setup
When I run `rake db:from_scratch`, it gives me an error of

`PG::ConnectionBad: FATAL:  password authentication failed for user "exercism"`

I'm not sure if I need to adjust my PG envr settings to allow the connection...

**Comment by kytrinyx** [comment]
Hi @chesterl I'll try to get this set up on a fresh machine and see if there's a command missing. I'm traveling at the moment, so it might take a few days before I can get to it.

**Comment by chesterl** [comment]
Sure thing!

**Comment by praveenpuglia** [comment]
can you try changing the password for user exercism to whatever it is in `database.yml` ?

Assuming you have plain simple copied `config/database.example.yml`, Try doing the follwing;

-  Log into psql prompt as user **postgres**
   
```bash
sudo su - postgres
psql
# you should now be in postgres=# prompt
```
- Change password for user exercism
```sql
ALTER USER exercism WITH PASSWORD 'apples';
```
- Now run the migrations again

```bash
rake db:from_scratch
```

Let me know if this fixes your issue.

**Comment by kytrinyx** [comment]
On my local system the exercism user doesn't have a password. I have no idea if this is default behavior, though.

**Comment by praveenpuglia** [comment]
i have been trying to do the setup and every time this would pop up! what i posted above solved the issues.

**Comment by tejasbubane** [comment]
I faced the same problem. I was actually unaware that `rake db:from_scratch` exists and assumed that I had to create the user. Looks like this is due to the `psql` create_user command being run as a normal user instead of `postgres` - https://github.com/exercism/exercism.io/blob/master/lib/tasks/db.rake#L33

**Comment by chesterl** [comment]
I think I've logged in as the sudo user, but when I use the `ALTER` command. It isn't available. 

After logging in my prompt changes to
`localhost:~ postgres$`

I can type exit to return to my exercism folder and it says `logout`

**Comment by kytrinyx** [comment]
OK, I've determined that the from scratch task is relying on the DB::Connection that reads from config/database.yml, which assumes that there's a database called `exercism_development` (ironically, since the point was to create that user).

I'll see if I can get this sorted today.

**Comment by kytrinyx** [comment]
In the meanwhile, you should be able to do this:

```
createuser exercism --superuser && createdb exercism_development && createdb exercism_test
rake db:migrate
RACK_ENV=test rake db:migrate
```

**Comment by canweriotnow** [comment]
Thanks for resolving this... I'm working on the db "models" (I use scare quotes since we don't do ORM in FP) for the new API so I was just about to jump into running the migrations. I <3 when other people's problems (being resolved) make my life easier :)

**Comment by kytrinyx** [comment]
If you ever need a plain dump of the database structure without any ruby dependencies let me know.

Actually I should probably include that in the repo just in case.
