### ISSUE TITLE
need help configuring and running java tests

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/exercism.io#2429]
When I run ```gradle test``` it doesn't seem to actually be running the code tests.  Judging by the output, I would say it's only confirming that dependencies etc are successfully downloaded.

Anyway, my Etl.java class is basically empty at this point, so there's no way it should be passing the tests!

Output is: 
```
Matthew-Morgans-MacBook-Pro:etl matt$ ./gradlew check
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE

BUILD SUCCESSFUL
```

I followed the docs in the help section, and this was as far as it got me.  Any help would be appreciated!

**Comment by kytrinyx** [comment]
@jtigger any thoughts on this one?

**Comment by matthewmorgan** [comment]
hey...turns out my exercism version was old: 1.7.  installed newest, and I'm up and running.  Sorry to bother everyone, thanks for the help.

**Comment by kytrinyx** [comment]
Nice! Glad you got it sorted.
