### ISSUE TITLE
Test suite 'empty' for Java Scrabble Score

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/exercism.io#2430]
Hi, 

When I try to run the test suite for this exercise it fails.  Here's what I got back:

```
Testing started at 8:20 AM ...
8:20:13 AM: Executing external tasks 'cleanTest test --tests ScrabbleScoreTest'...
:cleanTest
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test
Connected to the target VM, address: '127.0.0.1:54785', transport: 'socket'
Disconnected from the target VM, address: '127.0.0.1:54785', transport: 'socket'
Empty test suite.
Empty test suite.
:test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> No tests found for given includes: [ScrabbleScoreTest]
```

Thanks!

**Comment by kytrinyx** [comment]
I'm not sure what's happening.

@jtigger is there a bit of documentation that we're missing? I'm looking at the test and it does have a test method along with a bunch of test inputs/outputs.

**Comment by jtigger** [comment]
I'll have a chance to look into this later today.

**Comment by matthewmorgan** [comment]
I checked the JUnit docs and the syntax for the test all looks correct.  It doesn't look like it's the test suite per se.  I also tried requesting more verbose output from Gradle and didn't see anything obvious.

**Comment by jtigger** [comment]
Hmmm.... "it's working on *my* machine."

Here's what I get:

```
$ exercism fetch java scrabble-score

Not Submitted:        1 problem
Java (Scrabble Score) /Users/jtigger/projects/exercism-tracks/java/scrabble-score

New:                  1 problem
Java (Scrabble Score) /Users/jtigger/projects/exercism-tracks/java/scrabble-score

unchanged: 0, updated: 0, new: 1

[507] (x.y.z) jtigger@7acrewood:java $ cd scrabble-score/
[509] (x.y.z) jtigger@7acrewood:scrabble-score $ gradle test
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava
/Users/jtigger/projects/exercism-tracks/java/scrabble-score/src/test/java/ScrabbleScoreTest.java:38: error: cannot find symbol
        Scrabble scrabble = new Scrabble(input);
        ^
  symbol:   class Scrabble
  location: class ScrabbleScoreTest
/Users/jtigger/projects/exercism-tracks/java/scrabble-score/src/test/java/ScrabbleScoreTest.java:38: error: cannot find symbol
        Scrabble scrabble = new Scrabble(input);
                                ^
  symbol:   class Scrabble
  location: class ScrabbleScoreTest
2 errors
:compileTestJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.815 secs

```

... and I'm assuming that everything has been working for you with prior exercises...

But we might need a few more clues to be helpful:

* what's the output of `$ exercism debug`
* what's your current working directory? `pwd`

and if we *really* want to get to the bottom of this, feel free to report back the full output (redacted as you wish, of course) of your `gradle test --debug`.

**Comment by jtigger** [comment]
@kytrinyx , yeah, I've got too much WIP, we're not 100% there with the start-up docs.  I'm delighted to see someone running the Java track using the command-line.  I'll circle back to the docs and take on that next step.

**Comment by kytrinyx** [comment]
Yeah, I really appreciate it when people are willing to create issues for the problems they run into. It always makes things better.

**Comment by matthewmorgan** [comment]
Hi,

So in this case I hadn't been using the command line initially, but IntelliJ.  The tests work from the command line, but fail from inside IntelliJ.  I did discover that my exercism version was _still_ old (now updated) but this made no difference anyway, even after deleting and re-fetching the exercise.

What information might I want to redact from the gradle debug?  Please let me know and I'll post that as well.  Thanks!


exercism --debug:
**** Debug Information ****
Exercism CLI Version: 2.2.0
Exercism CLI Latest Release: 2.2.0
OS/Architecture: darwin/amd64
Build OS/Architecture darwin/amd64
Home Dir: /Users/matt
Config file: /Users/matt/.exercism.json
API Key: <redacted>
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/matt/exercism

pwd:
 /Users/matt/exercism/java/scrabble-score

Gradle --version:

------------------------------------------------------------
Gradle 2.4
------------------------------------------------------------

Build time:   2015-05-05 08:09:24 UTC
Build number: none
Revision:     5c9c3bc20ca1c281ac7972643f1e2d190f2c943c

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.4 compiled on April 29 2014
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Mac OS X 10.10.3 x86_64

**Comment by matthewmorgan** [comment]
BTW having apparently same issue with roman-numerals.  Passes in CL, fails as empty test in IntelliJ.

Both of these use parameterized tests...coincidence?

**Comment by matthewmorgan** [comment]
Same issue with Binary, again, parameterized tests.

**Comment by kytrinyx** [comment]
I can't remember if @canweriotnow did the setup in IntelliJ. I bet there's some sort of trick to how to import the project into the IDE.

**Comment by jtigger** [comment]
Yes, exactly...  So, @matthewmorgan, please give this a whirl:

1. pick one of these exercises;
2. make a copy of your answer;
3. delete the directory of that exercise;
4. and try out [the instructions for importing an exercise into IntelliJ](http://help.exercism.io/getting-started-with-java.html#step-3-get-started-with-the-first-exercise) (these are for Windows; the OS X instructions are in the pipeline).

**Comment by matthewmorgan** [comment]
That worked!

I had not checked the 'auto-import' and 'create roots' checks, but this doesn't seem to have been the issue.  I was running the test with the Gradle icon next to it.

Once again, thanks for your help.

**Comment by jtigger** [comment]
Thanks for reporting back, @matthewmorgan.  That's helpful to know.  Glad you're unstuck on those exercises!
