### ISSUE TITLE
anagram problem description in C++ does not agree with tests

### ISSUE THREAD

**Issue by jfsantos** [exercism/exercism.io#2431]
The README states:

>Write a program that, given a word and a list of possible anagrams, selects the correct sublist.

>Given `"listen"` and a list of candidates like `"enlists" "google"
>"inlets" "banana"` the program should return a list containing
>`"inlets"`.

However, the tests call a function with the signature `vector<string> anagram::anagram(string word)` and look for matches between the output and an arbitrary list of words. The way the tests are written, the function should return a list of all possible anagrams.

**Comment by kytrinyx** [comment]
Interesting. Yeah, this diverges from how the problem is defined in most of the other tracks.

@LegalizeAdulthood Should we make the README more vague to accommodate a broader definition of what the problem is, or should we change the test suite to match the README?

**Comment by jfsantos** [comment]
It's definitely possible to write code to match the tests (i.e., `anagram::anagram` returns an instance of a class with a class method `matches`). The problem here is that by reading the README only, I was under the impression that the problem structure would follow that of the previous exercises.

**Comment by LegalizeAdulthood** [comment]
I followed the example of the [tests for the javascript track](https://github.com/exercism/xjavascript/blob/master/anagram/anagram_test.spec.js).  Reviewing the JavaScript and the C++ implementations, they are identical and conform to the problem statement.

@jfsantos Perhaps what's throwing you off is that this time the tests are written assuming a class and not written as a pure function?

**Comment by jfsantos** [comment]
@LegalizeAdulthood that's it, but maybe assuming the tests would expect a single function as in the previous 3 exercises was my mistake. The README file does not mention anything about classes, but it gets clearer after reading the tests.

There's another problem in the tests, though: the last test (`matches_accepts_string_arguments`) does not test anything different compared to the other tests (as opposed to the JavaScript test, which tests multiple string arguments vs a list).

**Comment by LegalizeAdulthood** [comment]
You're probably right about that last test being redundant.  Pull requests are always welcome :smile_cat:

**Comment by kytrinyx** [comment]
Since javascript has some flexibility in how it accepts method arguments, this type of test makes sense. I don't think that the C++ test suite should emulate that, since it's very language-specific. Perhaps we can rename the last test so that there's no confusion.

> maybe assuming the tests would expect a single function as in the previous 3 exercises was my mistake.

Each exercise is standalone, and we're trying to introduce people to language features in a gradual/gentle way. You can assume that as you progress through the track, the solutions will require more complexity.

> The README file does not mention anything about classes, but it gets clearer after reading the tests.

The READMEs are not language-specific, and are intentionally ambiguous, to allow for different approaches in different languages, depending on what's interesting and/or idiomatic.

**Comment by Insti** [comment]
"Moved" issue to cpp track repository.
