### ISSUE TITLE
Crypto Square tests for Java version conflict with tests for JS version

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/exercism.io#2432]
Hi,

I'm not sure if this is a bug or if I am missing something different about the exercise requirements, but the test suite for the Java version of this problem seems to be expecting different segment sizes than the JS version.  EG
```
//Java test
    @Test
    public void normalizedCipherNotExactlyDivisibleBy5SpillsIntoSmallerSegment() {
        Crypto crypto = new Crypto("Madness, and then illumination.");
        String expectedOutput = "msemo aanin dninn dlaet ltshu i";

        assertEquals(expectedOutput, crypto.getNormalizedCipherText());
    }
```
yields:
```
java.lang.AssertionError: 
Expected :msemo aanin dninn dlaet ltshu i
Actual   :[msemoa, anindn, inndla, etltsh, ui]
```

But the JS test is: 
```
//JS test
  xit("normalized cipher text",function() {
    var crypto = new Crypto('Madness, and then illumination.');
    expect(crypto.normalizeCiphertext()).toEqual('msemoa anindn inndla etltsh ui');
  });
```
Note that the 'expected' in the JS test is identical to the result that failed in the Java test, and that the expected segment sizes differ in the two tests.  The README is a little vague, but illustrates that for non-perfect squares, the square size should be R x C, with C>R.  This is in agreement with the JS version tests, but in conflict with the Java version tests.

Thanks!

Edited: I do see the output type is an array instead of a string, but still, the segment length is mismatched between the tests.

**Comment by kytrinyx** [comment]
This is likely a bug. We had several language tracks that exhibited this behaviour (I don't recall which ones), but it's perfectly likely that the Java test suite was ported over based on a language with a faulty test suite.

**Comment by kytrinyx** [comment]
@jtigger - I'm never sure if I should move language-specific issues to the language track's repository.

**Comment by kytrinyx** [comment]
Oh, wow. The Ruby version disagrees with both of the above: `msemo aanin dnin ndla etlt shui`

**Comment by jtigger** [comment]
@kytrinyx I would definitely move to the language-specific track so as to make it clear it's in that track's backlog to prioritize against other stuff happening there (defects like this should be addressed immediately).

Looks like we need (at least) another for the Ruby track, too.

**Comment by jtigger** [comment]
Nice catch, btw, @matthewmorgan; thanks!

**Comment by matthewmorgan** [comment]
You're welcome.  Thanks for Exercism!

**Comment by matthewmorgan** [comment]
I think this is what you want:
```
import org.junit.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertEquals;

public class CryptoSquareTest {

    @Test
    public void strangeCharactersAreStrippedDuringNormalization() {
        Crypto crypto = new Crypto("s#$%^&plunk");
        String expectedOutput = "splunk";

        assertEquals(expectedOutput, crypto.getNormalizedPlaintext());
    }

    @Test
    public void lettersAreLowerCasedDuringNormalization() {
        Crypto crypto = new Crypto("WHOA HEY!");
        String expectedOutput = "whoahey";

        assertEquals(expectedOutput, crypto.getNormalizedPlaintext());
    }

    @Test
    public void numbersAreKeptDuringNormalization() {
        Crypto crypto = new Crypto("1, 2, 3, GO!");
        String expectedOutput = "123go";

        assertEquals(expectedOutput, crypto.getNormalizedPlaintext());
    }

    @Test
    public void smallestSquareSizeIs2() {
        Crypto crypto = new Crypto("1234");
        int expectedOutput = 2;

        assertEquals(expectedOutput, crypto.getSquareSize());
    }

    @Test
    public void sizeOfTextWhoseLengthIsPerfectSquareIsItsSquareRoot() {
        Crypto crypto = new Crypto("123456789");
        int expectedOutput = 3;

        assertEquals(expectedOutput, crypto.getSquareSize());
    }

    @Test
    public void sizeOfTextWhoseLengthIsNoPerfectSquareIsNextBiggestSquareRoot() {
        Crypto crypto = new Crypto("123456789abc");
        int expectedOutput = 4;

        assertEquals(expectedOutput, crypto.getSquareSize());
    }

    @Test
    public void sizeIsDeterminedByNormalizedText() {
        Crypto crypto = new Crypto("Oh hey, this is nuts!");
        int expectedOutput = 4;

        assertEquals(expectedOutput, crypto.getSquareSize());
    }

    @Test
    public void segmentsAreSplitBySquareSize() {
        Crypto crypto = new Crypto("Never vex thine heart with idle woes");
        List<String> expectedOutput = Arrays.asList(new String[]{"neverv", "exthin", "eheart", "withid", "lewoes"});

        assertEquals(expectedOutput, crypto.getPlaintextSegments());
    }

    @Test
    public void segmentsAreSplitBySquareSizeUntilTextRunsOut() {
        Crypto crypto = new Crypto("ZOMG! ZOMBIES!!!");
        List<String> expectedOutput = Arrays.asList(new String[]{"zomg", "zomb", "ies"});

        assertEquals(expectedOutput, crypto.getPlaintextSegments());
    }

    @Test
    public void cipherTextCombinesTextByColumn() {
        Crypto crypto = new Crypto("First, solve the problem. Then, write the code.");
        String expectedOutput = "foeewhilpmrervrticseohtottbeedshlnte";

        assertEquals(expectedOutput, crypto.getCipherText());
    }

    @Test
    public void cipherTextSkipsCellsWithNoText() {
        Crypto crypto = new Crypto("Time is an illusion. Lunchtime doubly so.");
        String expectedOutput = "tasneyinicdsmiohooelntuillibsuuml";

        assertEquals(expectedOutput, crypto.getCipherText());
    }

    @Test
    public void normalizedCipherTextIsSplitByHeightOfSquare() {
        Crypto crypto = new Crypto("Vampires are people too!");
        String expectedOutput = "vrela epems etpao oirpo";

        assertEquals(expectedOutput, crypto.getNormalizedCipherText());
    }

    @Test
    public void normalizedCipherNotExactlyDivisibleBy5SpillsIntoSmallerSegment() {
        Crypto crypto = new Crypto("Madness, and then illumination.");
        String expectedOutput = "msemoa anindn inndla etltsh ui";

        assertEquals(expectedOutput, crypto.getNormalizedCipherText());
    }

    @Test
    public void normalizedCipherIsSplitIntoSegmentsOfCorrectSize() {
        Crypto crypto = new Crypto("If man was meant to stay on the ground god would have given us roots");
        String expectedOutput = "imtgdvsf earwerma yoogoano uuiontnn lvtwttdd esaohghn sseoau";

        assertEquals(expectedOutput, crypto.getNormalizedCipherText());
    }

    @Test
    public void normalizedCipherTextIsSplitIntoSegmentsOfCorrectSizeWithPunctuation() {
        Crypto crypto = new Crypto("Have a nice day. Feed the dog & chill out!");
        String expectedOutput = "hifeia cedlve eoledd goaatc unyhht";

        assertEquals(expectedOutput, crypto.getNormalizedCipherText());
    }
}
```

**Comment by jtigger** [comment]
@kytrinyx would you like me to create an issue in the Java track for this?

**Comment by kytrinyx** [comment]
@jtigger That would be great. I keep wishing GitHub would create a "move issue" feature that replaces the old one with a link to the new one, but it keeps not happening :)

**Comment by kytrinyx** [comment]
closing in favor of exercism/xjava#55

**Comment by jtigger** [comment]
@kytrinyx, I've been looking more deeply into this.

In essence, this detail of the problem changed (i.e. how large the chunks are in the normalized cipher text) in October 2014, exercism/x-common@89d1274875bb9b8a7076c9af6af5c728786995b2. That update fixed an error in the instructions, but the change didn't propagate out to all the tracks (most notably the vbnet track).

Here's how the implementations group up.  I'll look into this more, over the weekend to determine what issues need to be filed in which tracks to correct this.

Plaintext | Cipher | clojure | go | haskell | ruby | fsharp | perl | cpp | javascript | java | swift | vbnet |
---| --- | --- | --- | --- | --- | --- | --- | --- | ---| ---| --- | ---
Madness, and then illumination. | `msemo aanin dnin ndla etlt shui` | x | x | x | x | x | x | | | | | |
 | `msemoa anindn inndla etltsh ui` | | | | | | | x | x | | | |
 | `msemo aanin dninn dlaet ltshu i` | | | | | | | | | x | x | x |
---| --- | --- | --- | --- | --- | --- | --- | --- | ---| ---| --- | ---
Vampires are people too! | `vrel aepe mset paoo irpo` |  x | x | x | x | x | x | | | x | x |
 | `vrela epems etpao oirpo` | |  |  |  |  | | x | x | | | x |

**Comment by kytrinyx** [comment]
Wow, thanks for taking the time to dig into this.

Maybe this would be a good candidate for [shared JSON test cases](https://github.com/exercism/rossconf/issues/13)

**Comment by jtigger** [comment]
My MBP (the machine I do all my non-work stuff on) is giving me serious grief (some passive aggressive behavior in response to me spilling a little coffee on it some months ago).  I think I've brought it back from the dead for the time being.  Expect delays in my commitments... but only delays.

**Comment by kytrinyx** [comment]
How on earth is coffee a bad thing? I don't get it. Your machine clearly needs to get with the program...

**Comment by jtigger** [comment]
BWHA!  Damn it!  I just spit-take'd more coffee...  Yeah, it's firmware is sooooo 2011.

Today, is the first day it's been "normal"... crossing fingers.  It seems like I've managed to keep the integrated GPU active.

Also, angling for a friendly face at the nearby Apple store who might be willing to overlook a few activated liquid contact indicators... (nervous laugh)...
