### ISSUE TITLE
"if you have a moment..." -> hello world

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2436]
We should *not* be suggesting that people give other people's hello world exercise a review. I think this is exposed on the dashboard. I can't remember what model code is involved, I can take a look at that after work today.

**Comment by kotp** [comment]
Where did this come from?  I know that I had gotten to it, but it was not 'easy' to get there.  I kind of had to work around things to make that happen.  (Also just a bump...)

**Comment by kytrinyx** [comment]
Ah. It's on the dashboard. Things have been a little bit out of control lately, I'll take a look at this now.

**Comment by kytrinyx** [comment]
I have not yet deployed--I'll do that when I get back this evening.
