### ISSUE TITLE
Can't logout and others in my network are automatically logged into my account

### ISSUE THREAD

**Issue by blackrat** [exercism/exercism.io#2437]
Hi. I've been recommending you to the new grads in my company. One of them is using a completely different machine, but asked if I had logged in from that box. I'd never been anywhere near it, but it was logged in to exercism as me!!
He couldn't sign out from that machine and neither could I from mine. Since I've been recommending you to may people in the organisation, I'm concerned about this security hole. I double checked that he wasn't also logged into my github account, and that seemed to be ok, so it may be that our proxy/nat is presenting the same to your machines (identical outbound ip addresses, but should be completely different sessions).

**Comment by kytrinyx** [comment]
Whoa, that's very weird and scary! IP address shouldn't have anything to do with it. I'm using the session middleware that ships with Sinatra, so I'll start by asking there if anyone has seen something like this.

Are you able to delete cookies in order to log out?

**Comment by jtigger** [comment]
FWIW, I'm not seeing any cache-control headers in responses for HTML.  Is cache_control is :private by default?

**Comment by kytrinyx** [comment]
Good catch. No, I don't think it's private by default.

**Comment by kytrinyx** [comment]
OK, I've set the cache control to private. Would you give this another try?

**Comment by jtigger** [comment]
@blackrat could you do us a huge favor.  While you're at it, could you share what headers you're getting back in the response?

```bash
$ curl --head http://exercism.io
```

**Comment by blackrat** [comment]
No worries. It looks like whatever was done between Thursday and today has
made it possible to log out again, and my colleague is now himself. It's
all a little complicated here, because some of the uses are on thin clients
using terminal services etc.

Best wishes,
Paul

Headers:
HTTP/1.1 200 OK
Via: 1.1 vegur, 1.1 PROXY02
Connection: Keep-Alive
Proxy-Connection: Keep-Alive
Content-Length: 14616
Date: Mon, 06 Jul 2015 11:12:06 GMT
Content-Type: text/html;charset=utf-8
Server: Cowboy
Cache-Control: private
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Set-Cookie:
rack.session=BAh7CUkiD3Nlc3Npb25faWQGOgZFVEkiRWQxYmY3YjdhZGI2NDcwMjUxMTE0%0AYjM3NTU2MjRhYmYwOTc0ZWU2NTViMDA3NjA5YWZlYjE4YWVjYjEyMzUyM2IG%0AOwBGSSIJY3NyZgY7AEZJIiUyOTRjODAzZTM1MjljMmY4YmM5NmNkMDUyMDZm%0AYTRjMgY7AEZJIg10cmFja2luZwY7AEZ7B0kiFEhUVFBfVVNFUl9BR0VOVAY7%0AAFRJIi04YjU3OGQ5ZGZiZjQ3NTBjZGRlZjkwNzI2NmU2ZjQ2Y2ZhY2I2MjZh%0ABjsARkkiGUhUVFBfQUNDRVBUX0xBTkdVQUdFBjsAVEkiLWRhMzlhM2VlNWU2%0AYjRiMGQzMjU1YmZlZjk1NjAxODkwYWZkODA3MDkGOwBGSSIOX19GTEFTSF9f%0ABjsARnsA%0A--c05f5d3026710833e327cd44c4e20b375c5164da;
path=/; HttpOnly
X-EMS-Filter: WRProxy-0516
X-EMS-SRCIP: 193.36.230.96


On 3 July 2015 at 16:56, John Ryan <notifications@github.com> wrote:

> @blackrat <https://github.com/blackrat> could you do us a huge favor.
> While you're at it, could you share what headers you're getting back in the
> response?
>
> $ curl --head http://exercism.io
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/exercism.io/issues/2437#issuecomment-118380453>
> .
>



-- 
Best wishes,
Paul McKibbin

m: +447990970862
l: +442032396225
s: blackratprime
b: http://blackrat.org/

**Comment by kytrinyx** [comment]
Thanks, Paul!
