### ISSUE TITLE
/usr/bin/env: node: No such file or directory

### ISSUE THREAD

**Issue by techtheory** [exercism/exercism.io#2438]
Noob here. I installed exorcism, npm, and jasmine-node. I am running Ubuntu, using crouton to create a chroot on a Pixel.  When I run jasmine-node . in my javascript/hello-world directory i get the error referenced in the title above. I do have an env file in my /usr/bin/ directory. It is a binary file, so I was unable to really look at it. I tried it both with and without sudo. Does anyone have any idea why jasmine-node does not see it? I have pasted some input and output from my shell below.

(trusty)jim@localhost:~/exercism/javascript/hello-world$ jasmine-node .
/usr/bin/env: node: No such file or directory
(trusty)jim@localhost:~/exercism/javascript/hello-world$ ls /usr/bin/env
/usr/bin/env
(trusty)jim@localhost:~/exercism/javascript/hello-world$ sudo jasmine-node .
[sudo] password for jim: 
/usr/bin/env: node: No such file or directory

If this is not the proper forum for questions like this, please let me know. I will endeavor to do better in the future.  --Thanks.

**Comment by kytrinyx** [comment]
Interesting, it looks like `node` might not be in your path. What happens if you say `which node`?

**Comment by chastell** [comment]
Check whether the problem is not due to [`node` executable name clash in Debian/Ubuntu](http://stackoverflow.com/questions/18130164/nodejs-vs-node-on-ubuntu-12-04), especially if your Node.js and npm come from official packages.

**Comment by techtheory** [comment]
Returns nothing. No error, no response. It appears to me that nodejs is in path. Is that different? See what I have pasted below for more info.  Also, thanks for the quick support! It is appreciated.

(trusty)jim@localhost:~/exercism/javascript/hello-world$ which node
(trusty)jim@localhost:~/exercism/javascript/hello-world$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

(trusty)jim@localhost:/usr/bin$ ls n*
namei             neqn         nl        notify-send  ntfsdecrypt
nawk              netsurf      nm        npm          numfmt
ncal              netsurf-gtk  node-gyp  nproc
ncurses5-config   newgrp       nodejs    nroff
ncursesw5-config  nice         nohup     nstat

**Comment by techtheory** [comment]
Thanks chastell...that was a great call. Followed the link that you provided and problem is solved. Glad that I found this site. You gals and guys rock.

**Comment by kytrinyx** [comment]
Yay, glad it's sorted!
