### ISSUE TITLE
Getting started with Rust

### ISSUE THREAD

**Issue by BeggarsMattM** [exercism/exercism.io#2439]
Can anyone clarify for me how to get started on the Rust exercises? Having installed Rust etc all I see when I enter "cargo test" is "error: can't find crate for `leap`". Are there instructions for how and where to create a "leap" crate, and what to put in it, that I've missed?

**Comment by kytrinyx** [comment]
Check out the rustlang book chapter on crates and modules: http://doc.rust-lang.org/stable/book/crates-and-modules.html

(and let us know how it goes, if it's not enough to get you unstuck, we'll be more specific!)

**Comment by BeggarsMattM** [comment]
Mm, I can create a crate but it's not at all clear to me how that interacts with the pre-existing tests. It just feels like if you have to create your own crate, put your code in it, and run cargo test inside it, there should be instructions to that effect - all the other languages' help docs spell out how and where to run the tests that are provided. But feels like there's a step missing in the rust documentation. Or as usual it could just be me :D

**Comment by etrepum** [comment]
Okay so here's the most minimal thing that I could make work (this crate stuff is all new to me, haven't looked at rust since the pre-1.0 days):

* Create a `src/lib.rs` file that looks like this:

```rust
pub fn is_leap_year(year: i64) -> bool {
    // implementation here
}
```

* Remove all `#[ignore]` markers from `test/leap.rs`
* Run tests with `cargo test`

**Comment by BeggarsMattM** [comment]
That seems to work, thanks @etrepum! I guess it wasn't obvious to me that the file in src should be called lib.rs. Thanks all.

**Comment by etrepum** [comment]
Me either! I don't blame you. I had to read that doc carefully and try a bunch of stuff until something worked.

**Comment by kytrinyx** [comment]
Is there a change we can make to the documentation (or the README or something) that would make it harder to get stuck?

**Comment by etrepum** [comment]
Yeah I'm sure the README could include more getting started information. Probably best to have whoever did the last pass over the rust track improve it because I'm not sure that the way I discovered is the best way, it was just the first thing I could make work.

**Comment by spazm** [comment]
I had the same issue as @BeggarsMattM .  Perhaps adding a little extra info to the suggestion to read the Crates and Modules section of the rust-book.

"""
You'll be writing a 'library crate'.  Code for a crate is stored within the `src/` subdirectory.  Library crates must contain at least a file named `lib.rs`.  If you were starting from scratch you could use `cargo new` to create the filestructure: e.g. `cargo new projectname`. 

exercism has already created the projectname directory so you'll need to create `src/lib.rs` manually:

```bash
mkdir src
touch src/lib.rs
```

For more details, check out the rustlang book [chapter on crates and modules](http://doc.rust-lang.org/stable/book/crates-and-modules.html)
"""

**Comment by kytrinyx** [comment]
@spazm that looks great. Do you want to make the change to the docs repo? https://github.com/exercism/docs/blob/master/app/pages/languages/getting-started-with-rust.md

**Comment by spazm** [comment]
PR #170 submitted.

**Comment by kytrinyx** [comment]
Sweet, thank you!

**Comment by kytrinyx** [comment]
Awesome, I've merged it and am deploying the fix.

**Comment by spazm** [comment]
woohoo! Thanks, I've been having a lot of fun with exercism.
