### ISSUE TITLE
robot-name — tests/spec vary on what's a valid robot name from exercise description across tracks

### ISSUE THREAD

**Issue by jtigger** [exercism/exercism.io#2441]
A collection of tracks enforce that the first two characters must be alphabetic:

In JavaScript:

```javascript
expect(robot.name).toMatch(/^[A-Z]{2}\d{3}$/);
```

In Lau:

```lau
assert.are.equal(string.match(robot.name, '^%a%a%d%d%d$'), robot.name)
```

In Go:
```go
var namePat = regexp.MustCompile(`^[A-Z]{2}\d{3}$`)
```

----
Another allow for alphanumeric.

In Java:

```java
private static final String EXPECTED_ROBOT_NAME_PATTERN = "\\w{2}\\d{3}";
```

(where `\w` is the character set: `[A-Za-z_0-9]`)

C++:
```cpp
const boost::regex name_pattern{R"name(^\w{2}\d{3}$)name"};
```

Scala:
```scala
val nameRegex = """\w{2}\d{3}"""
```

----
Suggestion:
1. write a `robot-name.json` containing a set of valid and invalid names to nail-down the rule, here
2. adjust the tests on tracks which do not conform to the rules (better yet, write generators for such tests!).

(thanks to @matthewmorgan for catching this).

**Comment by kytrinyx** [comment]
+100 for consistency and generators.

I originally wrote the spec as ASCII letters for the first two, numeric digits for the last three. I don't have a very strong opinion on this, but it seems like a perfectly good arbitrary rule, and I'm happy to stick with it.

**Comment by spazm** [comment]
And the test in `rust` is confusingly wrong:

```rust
fn assert_name_matches_pattern(n: &str) {
    assert!(n[0..2].chars().all(|c| c >= 'A' && c <= 'Z'), "name starts with 2 letters");
    assert!(n[3..].chars().all(|c| c >= '0' && c <= '9'), "name ends with 3 numbers");
}
```

This checks that the first 2 chars are letters and that the 4th(!) and later chars are numbers.  This passes "ABC" for example.

At a minimum, I'd suggest:

```rust
fn assert_name_matches_pattern(n: &str) {
    assert!(n.len() == 5, "name is 5 characters long");
    assert!(n[0..2].chars().all(|c| c >= 'A' && c <= 'Z'), "name starts with 2 letters");
    assert!(n[2..].chars().all(|c| c >= '0' && c <= '9'), "name ends with 3 numbers");
}
```

What's the procedure for making changes/fixes for test cases?

**Comment by kytrinyx** [comment]
I wrote a blog post about this, but I haven't actually launched the blog yet :) http://blog.exercism.io/post/touching-up-existing-exercises/

There's also a contributing guide, but I think that's more confusing at the moment (and more to read)
https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

Would you let me know if the blog post walks you through this well enough, @spazm?

**Comment by wobh** [comment]
Hmm. in xlisp we're testing for uppercase names. I wonder if we should be case-indifferent though. I don't think it makes a lot of sense for robot "AA000" to be a different robot than "aa000"

**Comment by kytrinyx** [comment]
Agreed, that should be the same robot. Unless `aa000` is invalid, I guess.

**Comment by jtigger** [comment]
I'm inching the Java track toward the simplest interpretation: first two characters are uppercase digits; everything else is invalid (i.e. `[A-Z]`).

I think much of the learning surface area of this problem is in exploring the space-vs.-computing trade-offs; I don't immediately see how it adds to consider whether the first two characters in the name are uppercase/lowercase.

**Comment by kytrinyx** [comment]
@jtigger agreed, I think just "calling it" is the right decision here.

**Comment by spazm** [comment]
Thanks for the blog post walk through, @kytrinyx.

I've modified the rust test to require a name matching 'AB123': two uppercase ascii alpha + three ascii digits.  See exercism/xrust#47

**Comment by LegalizeAdulthood** [comment]
@spazm Why does it need to be upper case?  Its amazing how these really simple sounding problem descriptions yield so many different interpretations! :smile_cat:

**Comment by Insti** [comment]
This issue was addressed in x-common with the final decision being that the letter component of robot names should be in uppercase

https://github.com/exercism/x-common/issues/260 - Discussion
https://github.com/exercism/x-common/pull/283 - Pull request to update Readme
