### ISSUE TITLE
unable to submit solution - error parsing API response - invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by Ben-Baert** [exercism/exercism.io#2442]
I get the following error when trying to submit my solution to the nucleotide-count exercise in the Scala track:

```
unable to submit solution - error parsing API response - invalid character '<' looking for beginning of value
```

 Note that I've been submitting many other exercises in this track and other tracks without any issues.I didn't do anything different this time (at least not that I'm aware of).

**** Debug Information ****
Exercism CLI Version: 2.1.1
OS/Architecture: darwin/amd64
Home Dir: /Users/Ben
Config file: /Users/Ben/.exercism.json
API Key: [DELETED]
API: http://exercism.io [Get http://exercism.io: read tcp 50.16.204.94:80: use of closed network connection]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/Ben/exercism

EDIT: the exercism.io website gives me:

```
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```

Is it 'just' the site that's down?

EDIT2: it works again. I tried it a couple of times before, didn't work, now half an hour later (and the site seems to be back on), it works.

**Comment by kytrinyx** [comment]
Weird, I have no idea what happened. Glad it got sorted, but also kind of mystified, since I didn't do any deploys or anything.

**Comment by chelseakomlo** [comment]
I get this same problem when I call "exercism fetch". 

Anything I can do to help fix this problem? If you point me in a direction I can investigate!

**Comment by kytrinyx** [comment]
What version of the CLI do you have?

**Comment by chelseakomlo** [comment]
version 1.5.0... I should probably update? :)

**Comment by kytrinyx** [comment]
uh, yeah :) That's probably a good idea.

**Comment by MiyamotoAkira** [comment]
I've just got the same error this morning. Did an upgrade, which worked, but still got the same error. And the page is down currently.

Maybe add a better description on the CLI when the error happens? I will try to submit later on.

**Comment by kytrinyx** [comment]
@MiyamotoAkira I'm so sorry you're running into trouble.

What does `exercism debug` output? Recent versions of the CLI do provide a better error message in most cases that I've found, but it's possible that you've run into an edge case that we've not seen before.

What command were you running when you got the error? Also, it might be useful to know what your working directory was when the error occurred.

**Comment by MiyamotoAkira** [comment]
The error was the same as the original post:

     unable to submit solution - error parsing API response - invalid character '<' looking for beginning of value

That happened in the morning. On the afternoon there was no issue. I was making the call from inside the exercise folder (fsharp/sum-of-multiples). If it happens again I will try that call.

**Comment by kytrinyx** [comment]
OK, thanks. I am going to close this for now, but if it does come up again, feel free to open a new issue.

**Comment by kwikiel** [comment]
Same issue here:
2015/12/23 22:59:13 unable to submit solution - error parsing API response - invalid character '<' looking for beginning of value

BTW from time to time webapp is giving such error: 
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

Maybe it is somehow connected?

**Comment by kytrinyx** [comment]
The site was down, including for submissions. It should be back up now. Sorry about that.
