### ISSUE TITLE
Indention levels are being changed when uploading Go code

### ISSUE THREAD

**Issue by hicksca** [exercism/exercism.io#2443]
In going though users submissions to provide Nits, I started to notice that there were a ton of problems that were not indented correctly. Went back to check my own submission because I know I'd been running `go fmt` on my code (I use vim-go and this is done automatically on saves.), I noticed that my leap submission was only indented four spaces. I went back to my local copy and checked it had the full eight spaces.  I then added a comment to the top of the file so that I could upload the same file and ran `go fmt` manually. Ran `cat` on the file to make sure that nothing funny was going on in my settings, and the file still looked the was I thought it would with the correct eight spaces. I resubmitted only to find that after submitting the leap exercise again it still showed only showed an 4 space indent.

Is this normal behavior or am is something funny happening here.

Orgnical submission I checked:
http://exercism.io/submissions/555b342391bb4a17b23c16c1fd1ff684
Resubmitted submission:
http://exercism.io/submissions/5121c5da760f42daaeab97cd04fdaf73

One of the users (@Nikosl) I first noticed this on:
http://exercism.io/submissions/1d3effd3386f4469873501dc2dce5b9a

Updated:
Checked to make sure it wasn't an issue of me using an outdated version of the cli
originally noticed while running cli version 2.1.1. Updated cli to version 2.2.0 and tested again still having the same issue with my uploads.

**Comment by kytrinyx** [comment]
You're right. I think tabs are being styled as four spaces. They are stored in the database with tabs, so if we can get a patch in to the rouge library, this would fix all the existing submissions in Go.

**Comment by hicksca** [comment]
👍🏾👍🏾

**Comment by kytrinyx** [comment]
The submissions are stuffed into a field in the database.

I was thinking last night: tabs are tabs--deciding how many spaces a tab should represent is really just configuration. Some people use two spaces, others use four spaces, and yet others use 8 spaces.

Is it really a bug to not have them be displayed as eight spaces?

**Comment by hicksca** [comment]
For the most part I agree with you that is isn't that big of a deal.

**Comment by kytrinyx** [comment]
I'm going to leave this open--perhaps others have some arguments for or against (I currently don't have a strong opinion either way). Thanks for bringing it up!

**Comment by kytrinyx** [comment]
This hasn't come up again, and I don't think it's enough of a big deal to push to fix it. @hicksca I'm going to close it, but if it ends up bugging you enough that you think it should be fixed, feel free to reopen it.
