### ISSUE TITLE
Word count tests

### ISSUE THREAD

**Issue by JeroenRombouts** [exercism/exercism.io#2445]
I've been looking at the Javascript tests for the word count exercise. I'd like to propose to add these tests at the end:

```javascript
  it("handles string with only whitespace", function() {
    expect(words("   \t       ")).toEqual({});
  });

  it("handles non-strings passed to words()", function() {
    expect(words({test:1})).toEqual({});
  });
```
It looks like a natural part of such an exercise.

**Comment by kytrinyx** [comment]
Yeah, these are great suggestions, thanks!
