### ISSUE TITLE
Exercism Java track -- Pascal's Triangle submission disappearing?

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/exercism.io#2446]
Hi,

Yesterday I submitted the Pascal's Triangle exercise and received no errors in the process.  Today the exercise was missing from my 'Current Exercises'.  I also didn't get the rocket icon while viewing the other solutions.

This morning I resubmitted the exercise, and it now appears in my 'Current Exercises', but I still don't get a rocket icon while viewing the other exercises.  Finally, even though there are two other open solutions to this exercise, I now can only see one of those two while iterating through using 'View next submission'.

EDIT: just went back, and now the rocket has returned, and I can see both other versions.  Maybe this is a caching issue in my browser?

**Comment by kytrinyx** [comment]
Very strange, I'll see what the database has to say about this.

**Comment by kytrinyx** [comment]
According to the database, you only have one submission for this exercise, however the exercise itself has a created at timestamp and an updated at timestamp that are hours apart.

**Comment by matthewmorgan** [comment]
Yeah.  I submitted it yesterday evening and it was gone this morning, so I
resubmitted it early today.

On Wed, Jul 22, 2015 at 2:47 PM, Katrina Owen <notifications@github.com>
wrote:

> According to the database, you only have one submission for this exercise,
> however the exercise itself has a created at timestamp and an updated at
> timestamp that are hours apart.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/exercism.io/issues/2446#issuecomment-123824422>
> .
>



-- 
Matt Morgan
Director of Technology
Dulcet Software LLC
(734) 926-8142

**Comment by kytrinyx** [comment]
Have you ever used the `exercism unsubmit` command? If so, is there a chance that it got triggered?

**Comment by matthewmorgan** [comment]
Yes, I have. I think I did unsubmit that one but resubmitted it right away
with a small change.

Let me see if I can check my shell history.

**Comment by matthewmorgan** [comment]
My shell history shows that I didn't unsubmit that exercise, actually.  It was a different one.  Don't know if this illuminates anything.

```
  485  exercism submit src/main/java/PascalsTriangle.java
  486  exercism fetch
  487  cd ..
  488  git status
  489  git add .
  490  git commit -am 'finished java track!'
  491  git push
  492  exercism unsubmit src/main/java/PigLatin.java
  493  exercism submit src/main/java/PigLatin.java
  494  cd ..
  495  ls
  496  commit -am 'revised PigLatin regex'
  497  git commit -am 'revised PigLatin regex'
  498  git push
```

**Comment by kytrinyx** [comment]
I need to check how unsubmit works, I suspect that it deletes the last iteration period, which is utterly not what one would expect, and confusing to boot.

**Comment by kytrinyx** [comment]
Ok, yes. Unsubmit doesn't take any arguments, and it doesn't complain if you give it any. It just ignores them.

I'm so sorry about this! I'm adding some guards to the command so that it doesn't just go off and delete what you wouldn't expect it to.

**Comment by matthewmorgan** [comment]
No worries.  This is a tremendous service you've created and a hell of a lot of fun!

**Comment by kytrinyx** [comment]
I've submitted a PR to the CLI to add a guard for this. Thanks so much for helping figure out what happened here!
