### ISSUE TITLE
exercism.io hello-world.js prompt is undefined

### ISSUE THREAD

**Issue by SystemsEngineer2013** [exercism/exercism.io#2447]
Hi All,

I am new to programming and am unable to proceed past square 1. When I run this (node hello-world.js) it says prompt is undefined. It seems the format from codeacademy is worthless is real life applications.

How do open a prompt? 

var HelloWorld = function() {};
var myName = prompt("What is your name?");

HelloWorld = function(myName) {
	
	if (myName != null) {
		console.log("Hello, " + myName + "!");
	} else {
		console.log("Hello, World!");
	};

};

module.exports = HelloWorld;

**Comment by kytrinyx** [comment]
Hey! Did you figure this out?

**Comment by SystemsEngineer2013** [comment]
Yes! I was oblivious to the content within hello-world_test.script.js. There is no need for a prompt as names are passed in automatically. That and I was using console.log rather than a return statement

**Comment by kytrinyx** [comment]
Is there something we could have added (documentation?) that would have let you figure it out more quickly?

**Comment by SystemsEngineer2013** [comment]
As a complete beginner, I think it a short sentence or two explaining the test files would be helpful. I am not sure what the correct wordage would be, but if someone would have said "If you are having trouble understanding how to format your script, take a look at how test.script.js is calling your hello-world.js script." 

I attempted the exercise after a long day so these comments may already exist!

**Comment by kytrinyx** [comment]
Thanks!

**Comment by kytrinyx** [comment]
I added a bit of an extra hint to the skeleton hello-world.js file.
