### ISSUE TITLE
Inconsistant spelling in submission messages

### ISSUE THREAD

**Issue by sguermond** [exercism/exercism.io#2448]
"submission" is sometimes spelled "sumbission" in `lib/app/presenters/profile.rb` and associated view/test files. I could see this causing trouble in code upkeep. Are those methods being called anywhere besides these three files?

**Comment by kytrinyx** [comment]
OMG. Really? That's awful and kind of hilarious. Yeah, that could really cause trouble...

The only place they're used is in those three files.
