### ISSUE TITLE
Add possibility to reply with quote to a nit

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#2449]
Sometimes I want to quote nit picks of other users and keep their formatting. Currently I need to C&P and then manually reformat their stuff.

This could be much easier if there were a “reply with quote” button, that would fill in the answer box with the original text where each line is prepended with `>`.

**Comment by kytrinyx** [comment]
+1 -- great suggestion, thanks.

**Comment by jdsutherland** [comment]
It looks like this is completed and was merged as part of #3327.

**Comment by kytrinyx** [comment]
Thanks @jdsutherland
