### ISSUE TITLE
"Accept Invitation" UI is broken

### ISSUE THREAD

**Issue by listrophy** [exercism/exercism.io#2450]
Problem is probably right here in [app/views/account/show](https://github.com/exercism/exercism.io/blob/master/lib/app/views/account/show.erb#L20). Basically, there's no vertical padding around the buttons, and (even though it's gray'ed out) the name of the team I'm invited to actually overflows on the left.

![screen shot 2015-07-27 at 11 04 35 am](https://cloud.githubusercontent.com/assets/26813/8911360/9e24aecc-3451-11e5-8ae5-dc7a83d631cf.png)

**Comment by kytrinyx** [comment]
Thanks for catching this.
