### ISSUE TITLE
No syntax highlighting for emacs-lisp

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism.io#2454]
I just submitted `hello-world` for elisp and found out there is no syntax highlighting.
 
![exercism-elisp](https://cloud.githubusercontent.com/assets/980783/8955863/0cbcd806-360e-11e5-97d6-a04a9e6a6bc1.jpg)

**Comment by kytrinyx** [comment]
We use https://github.com/jneen/rouge for syntax highlighting at the moment. We'll probably have to add support for it ourselves. It might actually not be too big of a deal if they support other lisp-y languages, but I've not actually looked into it.

**Comment by tejasbubane** [comment]
There is `common-lisp` and it should work for `elisp` as mentioned [here](https://github.com/jneen/rouge/blob/v1.8.0/lib/rouge/lexers/common_lisp.rb#L11). 

I tried on creating webpage and css via `irb` as given in the [README of rouge](https://github.com/jneen/rouge#usage), and was easily able to get syntax highlighting.

![lisp](https://cloud.githubusercontent.com/assets/980783/9044705/e8820682-3a3b-11e5-9225-b3aecd35685c.jpg)

But, on the exercism.io webpage, all the css tags for code styling seem to be absent for elisp only.

**Comment by tejasbubane** [comment]
Seems like `Rouge::Lexer.find_fancy(language, code)` returns `nil` and it falls back to `Rouge::Lexers::PlainText`. Code here:  https://github.com/exercism/exercism.io/blob/master/lib/exercism/markdown.rb#L77

**Comment by tejasbubane** [comment]
The language name needs to be `common_lisp` and not `elisp`. 
I have sent a PR. There exists a similar hack for `objective-c` here : https://github.com/exercism/exercism.io/blob/master/lib/app/helpers/markdown.rb#L10
