### ISSUE TITLE
Home page dropdown does not show all languages (depending on window/screen size)

### ISSUE THREAD

**Issue by mandel01** [exercism/exercism.io#2457]
I like the dropdown list of languages on the home page, but when I look on my laptop I didn't realize that there are more languages below the bottom of the window. Perhaps you are already aware of this issue but I wanted to document it in case you want to consider adding additional functionality for this dropdown, or perhaps smaller text so that more languages appear on laptops.

I attached a screenshot of an exaggerated view to show the issue. In a full-screen view on Mac / Safari (13" laptop) the last language listed is Rust. If I put my cursor in the bottom status bar then I see a link to Scala. I had to zoom out to see down to Swift (and was excited to learn that it was there!).

This seems connected to the REQ-LP-1 in the language landing page roadmap at https://github.com/exercism/exercism.io/issues/2299

![2015-07-31_09 25 36 - screenshot](https://cloud.githubusercontent.com/assets/8669125/9009429/ba95207e-3766-11e5-881b-65d80daaffd5.JPG)

**Comment by tejasbubane** [comment]
Hi @mandel01, this issue is reported in #2299 and they are working on it.

**Comment by mixolidia** [comment]
@kytrinyx I've been working on this. Neither Sarah or I are familiar with Sass and compass. For the past week, I've been trying to figure it out. I'll be getting help from one of our coaches next week.

**Comment by kytrinyx** [comment]
Cool, thanks for the update!

**Comment by mandel01** [comment]
Thanks, and really nice work on the language landing pages!
