### ISSUE TITLE
Tests for tracks_test.rb need to be updated manually

### ISSUE THREAD

**Issue by mixolidia** [exercism/exercism.io#2460]
Hi @kytrinyx 
Test in tracks_test.rb is set up so that the tests have to be manually updated. Whenever a language is added or it's status modified the tests will fail because they are compared to a static set of data. It affects active, upcoming, and planned languages and their ids. Is this how you want it?

**Comment by kytrinyx** [comment]
Let's use a fixture for the test so that the test doesn't fail when a new language is added.

**Comment by kytrinyx** [comment]
I thought I fixed this in 7b7110556b600d7da9acb056bfb28deb90019ff0, actually.

**Comment by mixolidia** [comment]
tracks_test.rb seems to be testing against a static set.  This is what's in there now:
```
require_relative '../../test_helper'
require 'app/presenters/tracks'
require 'exercism/xapi.rb'
require 'faraday'

class PresentersTracksTest < Minitest::Test
  def test_stuff
    tracks = ExercismWeb::Presenters::Tracks
    active = ["Clojure", "CoffeeScript", "C++", "C#", "Emacs Lisp", "Elixir", "Erlang", "F#", "Go", "Haskell", "Java", "JavaScript", "Lisp Flavoured Erlang (LFE)", "Common Lisp", "Lua", "Objective-C", "OCaml", "Perl 5", "PHP", "PL/SQL", "Python", "Ruby", "Rust", "Scala", "Scheme", "Swift"]
    upcoming = ["ECMAScript", "Groovy", "Nimrod", "Perl 6", "Pony", "Standard ML", "VB.NET"]
    planned = ["Assembly", "Bash", "C", "ColdFusion", "D", "Haxe", "Windows PowerShell", "Mathematical Proofs", "R"]

    assert_equal active, tracks.active.map(&:language)
    assert_equal upcoming, tracks.upcoming.map(&:language)
    assert_equal planned, tracks.planned.map(&:language)
  end
end
```

**Comment by kytrinyx** [comment]
I think that if you `require_relative '../../tracks_helper' after requiring the test helper, then it will include the fixture file instead of calling out over HTTP with faraday.

**Comment by mixolidia** [comment]
Hi @kytrinyx 
O yeah, that worked. Thanks! Should I do a pull with the new changes? I added `require_relative '../../tracks_helper' as you said and deleted  require 'exercism/xapi.rb' and require 'faraday' from the test/app/presenters/tracks_test.rb file. So now if everything is working fine it will pass whether that test is run on it's own or part of the rake.

**Comment by kytrinyx** [comment]
Yepp, thanks :)
