### ISSUE TITLE
What is the next step after using cmake

### ISSUE THREAD

**Issue by Tim-Hansen** [exercism/exercism.io#2461]
Anyone know what the next step is after finishing these instructions? http://help.exercism.io/getting-started-with-cpp.html

Am I meant to be editing bob.cpp, then compiling with

c++ bob.cpp -o bob

How do I get exercism to run the tests? If there is any documentation (that I can't find) that would be great if you can point me in it's direction.

**Comment by kytrinyx** [comment]
@LegalizeAdulthood would you jump in here, please?

**Comment by Tim-Hansen** [comment]
Hey, thanks for replying. I figured it out in the end, didn't quite get that all I had to do was type 'make' to test the project. All clear now though.

**Comment by kytrinyx** [comment]
Ah! Maybe we can update the docs to be explicit about that. Glad you got it sorted.
