### ISSUE TITLE
No idea why my tests are failing (hello world)

### ISSUE THREAD

**Issue by tripledown** [exercism/exercism.io#2466]
So here is my code:

    def hello():
        callers_name = raw_input("What is your name?\n")
        if callers_name:
            print ("Hello, " + callers_name + "!")
        else:
            print("Hello, World!")

    if __name__ == '__main__':
        hello()

    $ python hello_world_test.py 
    What is your name?
    Jane
    Hello, Jane!

======================================================================
ERROR: test_hello_with_name (__main__.BobTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "hello_world_test.py", line 20, in test_hello_with_name
    hello_world.hello('Jane')
TypeError: hello() takes no arguments (1 given)

======================================================================
ERROR: test_hello_with_umlaut_name (__main__.BobTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "hello_world_test.py", line 26, in test_hello_with_umlaut_name
    hello_world.hello('Jürgen')
TypeError: hello() takes no arguments (1 given)

======================================================================
FAIL: test_hello_without_name (__main__.BobTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "hello_world_test.py", line 14, in test_hello_without_name
    hello_world.hello()
AssertionError: u'Hello, World!' != None

----------------------------------------------------------------------
Ran 3 tests in 3.551s

FAILED (failures=1, errors=2)

**Comment by kytrinyx** [comment]
I don't know any python, but my first guess is that `print` doesn't return a value. It probably prints out to the console, and then returns the language equivalent of `nil`.

What would be the way to return a string instead of printing it?

**Comment by tripledown** [comment]
Hi,

Giving up on it now. I think its the test case:

    def hello(toprint):
        print ("Hello, " + toprint + "!")

    def userinput():
        userin = raw_input("What is your name?\n")
        if userin:
            hello(userin)
        else:
            print("Hello, World!")

    hello("Jane")

    Testing started at 21:40 ...
    Hello, Jane!


So I placed jane into the unittest, so it should pass it the same as the above in my code ( hello("Jane") )
    def test_hello_with_name(self):
        self.assertEqual(
            'Hello, Jane!',
            hello_world.hello("Jane")
        )

AssertionError: u'Hello, Jane!' != None

**Comment by kytrinyx** [comment]
In that last example, the code looks more correct, but the indentation is wrong. What happens if you indent the two last lines?

**Comment by iaptsiauri** [comment]
If this issue is still relevant, the test cases are correct it's just the matter of your implementation, in your stack trace you can see that method `hello` requires one argument, in your method you do not specify any arguments.  Also as it was noted already `print` doesn't return any value, and therefore the test without any arguments failed.
>TypeError: hello() takes no arguments (1 given)

Here is my dummy solution
```python
 def hello(name=''):
	if name == '':
		return 'Hello, World!'
	else:
		return 'Hello, ' + name + '!'`
```

**Comment by Peque** [comment]
@kytrinyx: this issue should be closed. The tests are correct, as @iaptsiauri already noted.

@tripledown: it is always a good thing to look for other people's implementations. That is the idea of Exercism. Next time you don't pass the tests, think about what you are doing wrong: search on the internet, ask somewhere/somebody, submit your exercise (even if it does not pass the tests) and look for other implementations in Exercism. Then submit a new iteration with the changes you made to pas the tests or to improve your first implementation. :wink:

**Comment by kytrinyx** [comment]
Thanks, closing now.
