### ISSUE TITLE
Can't accept team invite and can't submit lessons?

### ISSUE THREAD

**Issue by Foovanadil** [exercism/exercism.io#2467]
A coworker created a team and invited me but when I click accept invite I get redirected to a page with an error saying "You may only view team pages for teams that you are a member of, or that you manage."

The invite stays in my notification (as if I didn't accept it) and I can click it over and over again, always with the same error. 

We tried deleting the whole team and re-adding several times. 

When I am added to the team we notice my account shows up twice, once as Foovanadil with the correct avatar image. and once as foovanadil with the default github avatar (note the case difference). 

Looks like some sort of case sensitivity thing or something? No matter how I am added to the team (using the upper or lowercase version (upper is the correct username)) I always show up twice.

May also be related to the fact that I can't submit exercises either. Trying to submit the first Python exercise I get : "2015/08/08 19:32:59 unable to submit (HTTP: 400) - unknown problem (track: Python, slug: hello-world, path: )"

Adding -v to the call doesn't give me any more output.

Running from OS X Yosemite 10.10.4

Here is -debug output

**** Debug Information ****
Exercism CLI Version: 2.2.0
Exercism CLI Latest Release: 2.2.0
OS/Architecture: darwin/amd64
Build OS/Architecture darwin/amd64
Home Dir: /Users/*MyName*
Config file: /Users/*MyName*/.exercism.json
API Key:  ....
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/*MyName*/Code/Exercism/
 

Are the two related? Is my account fubar'ed somehow? Can I "un-fubar" it somehow?

**Comment by Foovanadil** [comment]
ok so the submission problem was unrelated but also weird. Submitting a separate issue for that. Will update this with the issue number

**Comment by Foovanadil** [comment]
Unrelated submission bug is documented here:https://github.com/exercism/exercism.io/issues/2468

**Comment by kytrinyx** [comment]
Thanks. Yeah, the team bug is the same as in #2328 -- it's at the top of my list.

**Comment by kytrinyx** [comment]
I've deleted the ghost users in production, and deployed the fix so that ghost users will no longer be created.
