### ISSUE TITLE
Case sensitivity issues on submission paths

### ISSUE THREAD

**Issue by Foovanadil** [exercism/exercism.io#2468]
I am on OS X and starting the Python track.

I create my code directory on disk first before pulling the excercise. 

So I had 

/pathToExercismRoot/**P**ython

Then I pulled the exercise which will put the exercise in 
/pathToExercismRoot/**p**ython

However, the issue seems to be that the code does a case insensitive check on the path (guessing on this) and sees the **P**ython folder already exists so it uses that folder instead of creating a **p**ython folder.

The problem is, when I go to submit the exercise if I use the actual OS X path (e.g. /**P**ython), which I will do because I am using tab completion on the command line, then I get a 400 error

So this: 
exercism s **P**ython/hello-world/hello_world.py

gives me:
2015/08/08 19:38:29 unable to submit (HTTP: 400) - unknown problem (track: Python, slug: hello-world, path: )

However, is I do this:
exercism s **p**ython/hello-world/hello_world.py

(even though the actual directory on disk is with a Capital **P**)

The submission works fine.

Hopefully that is a enough info to track down the issue. Let me know if you need more information.

**Comment by kytrinyx** [comment]
When the CLI fetches exercises, it will create the paths with lowercase -- a lot of things depend on this. I'll see if we can put a workaround in the CLI, bit it may be tricky.

/cc @Tonkpils @lcowell

**Comment by Foovanadil** [comment]
The biggest issue with this is that you get a 400 on an attempt to submit your first exercise with no clue what to do to fix it (I guessed on the casing issue out of nowhere)

If the creation of the directory on fetch could do one of two things it would help

1. If it finds an existing folder as the wrong case do a folder rename to the correct case (a bit tricky because you have to move files out, delete dir, create correct case dir, move files back)

2. Just show a warning that "A folder of the same name but wrong case was found. Please change to **p**ython. If you don't you will get errors") That will at least give the user the heads up that they are going to get errors and they will fix the problem for you.

**Comment by kytrinyx** [comment]
Yeah, warning might work. I was thinking about this for a bit today, and I think we might actually work around it without bugging the user about anything. I have to experiment a bit.

**Comment by Insti** [comment]
Is this still an issue? Should it be moved to the exercism/cli repository?

**Comment by kytrinyx** [comment]
I don't recall if it's a problem. If we don't already, we should downcase the track id when the submission is posted.

The code starts here:
https://github.com/exercism/exercism.io/blob/master/api/v1/routes/iterations.rb#L39

**Comment by Insti** [comment]
:rabbit: :black_circle:

**Comment by kytrinyx** [comment]
I'm so glad you provided the translation for that :)
