### ISSUE TITLE
account page needs #teams, #exercises, and #settings

### ISSUE THREAD

**Issue by mscottreed** [exercism/exercism.io#2469]
This is just a nice to have, but moving back and forth between the teams and exercises is very disconcerting at the moment (i.e. trying to compare my exercise with the same exercise from someone else on my team).  In fact it would be great to put some links or to be able to side by side / git diff (although that should be a different issue).

**Comment by kytrinyx** [comment]
Thanks!

As you may have noticed, I struggle a fair amount with front-end work / user interface design. Do you have specific suggestions for what an improved account page would look like?

**Comment by mscottreed** [comment]
So sorry, this (and the next message) ended up in my spam folder somehow.

 

The page can look the same, it just needs to remember which tab you were on in the history.  What is the front-end written in?  I might be able to take a look this weekend.

 

-Scott

**Comment by kytrinyx** [comment]
The frontend is an unholy mix of javascript and ruby (erb) templates.

**Comment by Peque** [comment]
I would love to see this implemented. When clicking on "Teams", "Exercises" or "Settings", the URL stays unchanged (`http://exercism.io/account`). I guess `#whatever_tab` should be appended to the URL instead.

Even when opening `http://exercism.io/account#exercises_tab`" manually, the "Teams" tab will be selected. And the HTML code still shows:

      <ul class="nav nav-pills nav-stacked col-md-3">
        <li class="active"><a href="#teams_tab" data-toggle="pill">Teams</a></li>
        <li><a href="#exercises_tab" data-toggle="pill">Exercises</a></li>
        <li><a href="#settings_tab" data-toggle="pill">Settings</a></li>
      </ul>

Maybe JavaScript is searching for the `active` attribute in the HTML over the URL `#whatever_tab`, and therefore, it always displays the "Teams" tab.

@mscottreed Was this what you were talking about as well?

**Comment by kytrinyx** [comment]
Oh, I finally get what you both are talking about. Sheesh--sometimes I'm a bit slow. Yeah. We absolutely need to have a way to link to the correct tab, and to know where you are in the history.

**Comment by mscottreed** [comment]
Yes @Peque, that is the first step.  If this is bootstrap (looks like it), then it is simple a matter of including the correct JavaScript file.  (although I would rename the href hash anchors to remove the _tab, for better URL readability/navigability).

 

http://getbootstrap.com/javascript/#tabs

**Comment by kytrinyx** [comment]
Yeah, we've got bootstrap in here, along with some angular.

**Comment by sguermond** [comment]
Working on it, unless someone else already is.

**Comment by Peque** [comment]
@sguermond Cool! :blush:

**Comment by sguermond** [comment]
I am having a lot of trouble with this. I've tried multiple solutions in JavaScript, but am not seeing any changes. The only way I can get the hashes to show up in the URL is by removing `data-toggle`, which prevents the active tabs from changing. Can someone help me out?

**Comment by kytrinyx** [comment]
@exercism/track-maintainers any chance any of you have javascript experience?

**Comment by aarti** [comment]
could you point me to the source? I can try.

**Comment by kytrinyx** [comment]
@aarti it's this page: https://github.com/exercism/exercism.io/blob/master/lib/app/views/account/show.erb
