### ISSUE TITLE
Brand New - Cannot get XCTests to Load in Swift

### ISSUE THREAD

**Issue by Avizacherman** [exercism/exercism.io#2471]
So I'm brand new to exercism and was doing the first swift exercise but I think I'm doing something wrong. I'm really novice with Xcode so I'm sure it's something simple. I get the following error: 

"Cannot load underlying module for XCTest".

in my LeapTest file. Please help! Thanks!

**Comment by kytrinyx** [comment]
@pminten do you have an idea of what's happening here?

**Comment by pminten** [comment]
Sorry, don't have any knowledge of Swift or Xcode.

Katrina Owen <notifications@github.com> schreef op 10 augustus 2015 05:44:07 CEST:
>@pminten do you have an idea of what's happening here?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/exercism/exercism.io/issues/2471#issuecomment-129289171

-- 
Verzonden van mijn Android telefoon met K-9 Mail.

**Comment by kytrinyx** [comment]
Oh, sorry @pminten for some reason I read Swift and thought Elixir!

@masters3d @hankturowski -- do you have a moment to jump in here?

**Comment by masters3d** [comment]
http://stackoverflow.com/questions/29965397/cannot-load-underlying-module-for-xctest

**Comment by hankturowski** [comment]
I think @masters3d answered this with the provided link. @Avizacherman, if you're still having trouble, let me know. Otherwise we should close this out.

**Comment by masters3d** [comment]
@Avizacherman

**Comment by kytrinyx** [comment]
I'll close this, and if there's still a problem, feel free to re-open it.
