### ISSUE TITLE
Getting started with scala page 

### ISSUE THREAD

**Issue by arashbi** [exercism/exercism.io#2472]
* Simply scala link is dead
* Programming in scala is also a retired page

**Comment by kytrinyx** [comment]
Thanks!

If you have a moment to update the docs, that would be wonderful. They're in the https://github.com/exercism/docs repository, at [app/pages/languages/getting-started-with-scala.md](https://github.com/exercism/docs/blob/master/app/pages/languages/getting-started-with-scala.md).

Do you happen to have any suggestions for good Scala resources?

**Comment by arashbi** [comment]
I could update it if I knew what to put there. Let me search a bit.

**Comment by jmluy** [comment]
Fixed in exercism/docs#162

**Comment by kytrinyx** [comment]
thanks!
