### ISSUE TITLE
When trying to view a userpage I get a 404

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#2473]
When I click a username, that brings me to `exercism.io/username`.

Since I use exercism, I was able to see some users information on that page, especially other exercises that particular user has already submitted.

Today I get a 404-error-page. If the feature of userpages has been removed, please don't have clickable usernames.

**Comment by kytrinyx** [comment]
That's a regression, not an intentional move.

**Comment by kytrinyx** [comment]
Fixed in e48d428feed50cce48c40f41115135bc90c4ac54. Deploying.
