### ISSUE TITLE
Can't upload swift-exercise (bob)

### ISSUE THREAD

**Issue by bernhardwaidacher** [exercism/exercism.io#2476]
I can't upload the Bob exercise of Swift.

This is the command/error: $ exercism submit Bob.swift
2015/08/12 15:50:57 unable to submit (HTTP: 400) - unknown problem (track: swift, slug: Bob, path: )

EDIT: it works... i just had to close the terminal and open it agian...

**Comment by kytrinyx** [comment]
Interesting. If it happens again, would you create a new issue with the output of `exercism debug`?
