### ISSUE TITLE
Code efficiency toplist

### ISSUE THREAD

**Issue by drozdziak1** [exercism/exercism.io#2480]
How about making a toplist where the shortest execution times would be displayed for each problem?
This way, Exercism could teach not only about clean code but also the importance of a well-developed algorythm.

The code would be executed in a uniform environment per language. Also, comparisons of analogical problems between languages could be possible

**Comment by kytrinyx** [comment]
In theory I think this would be very interesting. In practice, it would be difficult to get this to run in a uniform environment, since we are currently not doing any sort of sandboxing, and we never run the user's code anywhere.

**Comment by drozdziak1** [comment]
Yeah, that's definitely something to think about in the future. It's quite a resource-consuming idea

**Comment by kytrinyx** [comment]
I've added the label "future roadmap", and am closing the issue. When we have more resources, we'll be looking at all the various "future roadmap" issues to choose which ones to work on.

Thanks for the suggestion!
