### ISSUE TITLE
Change default configuration file location to XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by meskarune** [exercism/exercism.io#2483]
Right now the config file for Exercism cli is placed by default in the user's home directory: ~/.exercism.json

It would be better to place the configuration file in XDG_CONFIG_HOME as the default behavior. People who set XDG_CONFIG_HOME will expect configuration files to go there instead of having to set config file location for every application.

**Comment by kytrinyx** [comment]
At the moment the config can use env vars, but you're right, defaulting to XDG_CONFIG_HOME  if it's there would be better. Thanks!

https://github.com/exercism/cli/blob/a014c203b5578f1f276e5f66f77e999485464655/exercism/main.go#L50

**Comment by wobh** [comment]
I can't find the resources anymore, but when I looked into this for a CLI app I was working on earlier this year a couple of things I read made it seem like the XDG standard was mainly for X-based GUI applications (i.e. Gnome or KDE) that want to conform to the freedesktop standards, and rather less for command-line apps, and things that run on OSX (~/Library) and Windows (~\Profile last I checked). As much as I think most CLI apps would benefit from this sort of thing, my impression from a few months ago was that, the cross platform "standard" for them them is still the hidden file/folder in the users home folder.

I sure hope someone can tell me I'm wrong, or can suggest some other emerging alternative.

- http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
- http://freedesktop.org/wiki/Software/xdg-user-dirs/

**Comment by kytrinyx** [comment]
> XDG standard was mainly for X-based GUI applications (i.e. Gnome or KDE) that want to conform to the freedesktop standards, and rather less for command-line apps

That has always been my understanding as well, and for a while I resisted implementing it, but it keeps coming up as a request, and it's a really innocuous change: if the env variable exists, use it. If not fall back to our current default.

**Comment by HalosGhost** [comment]
On the contrary, *everything* should respect ``XDG_CONFIG_HOME``. Not respecting it (and not defaulting to ``$HOME/.config`` if it is not set) guarantees home-directory clutter which is a guarantee for an unhappy time.

:+1: for implementation of this.

**Comment by kytrinyx** [comment]
This has been fixed on master, and will be a part of the next release that we cut. https://github.com/exercism/cli/pull/215
