### ISSUE TITLE
Having issues submitting a java solution

### ISSUE THREAD

**Issue by dotten7792** [exercism/exercism.io#2485]
When I attempt to submit within the java folder in my directory 

    exercism submit /Users/derek/exercism/java/etl

I receive this error: "Unable to submit - unable to identify track and problem"

Here is my output when I run exercism debug

Exercism CLI Version: 2.2.1
Exercism CLI Latest Release: 2.2.1
OS/Architecture: darwin/amd64
Build OS/Architecture darwin/amd64
Home Dir: /Users/derek
Config file: /Users/derek/.exercism.json
API Key: MY KEY
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/derek/exercism

**Comment by dotten7792** [comment]
Nevermind. :)

**Comment by kytrinyx** [comment]
Ah, yepp :) It takes the path to the actual file, not just the parent dir. Sorry about that! Is there anything we could do so the next person doesn't run into the same thing?
