### ISSUE TITLE
F# SumOfMultiples Error

### ISSUE THREAD

**Issue by MiyamotoAkira** [exercism/exercism.io#2486]
Hi, 

the last test on the SumOfMultiples exercises has the wrong answer.

It says it should be 2203160, but it should be 2223370

It was the only test failing, so I decided to verify using a spreadsheet to confirm that is the correct answer. I can provide the spreadsheet  if needed

**Comment by jwood803** [comment]
Thanks for letting us know! I wonder if this is over the other language implementations, as well. In any case, we send an update.

**Comment by kytrinyx** [comment]
In the original problem, the program is configurable, and the test in question checks that the sum of the multiples of 43 and 47 up to 10,000 is 2203160.

We have this problem in the following languages:

- [ ] C++
- [ ] C#
- [ ] Elixir
- [ ] Erlang
- [ ] F#
- [ ] Go
- [ ] Haskell
- [ ] Javascript
- [ ] LFE (Lisp Flavoured Erlang)
- [ ] Python
- [x] Ruby - multiples of 43, 45
- [ ] Swift

**Comment by kytrinyx** [comment]
The test in question is:

```
    [<Test>]
    [<Ignore>]
    member tc.Configurable_43_47_to_10000() = 
        Assert.That(SumOfMultiples([43; 47]).To(10000), Is.EqualTo(2203160))
```

This is checking the sums of multiples of 43 and 47, not the sums of multiples of 3 and 5. 2203160 is the correct answer in this case.

**Comment by MiyamotoAkira** [comment]
Sorry, not sure I'm getting it correctly. You are saying that the number 2203160 is correct?

43 has a maximum multiplier of 232 before it gets to 10000 (43*232=9976). The sum of all multipliers of 43 up to, and including, 232 is 1162204

47 has a maximum multiplier of 212 before it gets to 10000 (47*212=9964). The sum of all multipliers of 47 up to, and including, 212 is 1061166

The sum of those two values is 2223370

I have used a spreadsheet (which I can provide) to create every single multiplier for 43 and 47 and sum them.

Is my logic faulty about the application? The spreadsheet confirms the results of my code and my code passes the other tests

**Comment by kytrinyx** [comment]
Any number which is divisible by both 43 and 47 will only be counted once. That is the following list of numbers: `[0, 2021, 4042, 6063, 8084]` which sums to 20210.

**Comment by kytrinyx** [comment]
OK, I see the problem. We don't have any other tests that cover that use case. I suggest that we add a test case for 

```
    [<Test>]
    [<Ignore>]
    member tc.Sum_to_100() = 
        Assert.That(sumOfMultiples.To(100), Is.EqualTo(2418))
```

**Comment by MiyamotoAkira** [comment]
Oh, I see the issue. Probably changing a bit the description on the readme.md file will help.

**Comment by kytrinyx** [comment]
Yeah, I'll reword the README. Thanks for bringing it up!

**Comment by kytrinyx** [comment]
Clarified in https://github.com/exercism/x-common/commit/236cd4280bc990afdfff78cae4d23d516572252f

**Comment by metadave** [comment]
Specifying that the numbers are below 15 and then including 15 in the list is confusing in your fix above:

        If we list all the natural numbers below 15 that are multiples of either
        3 or 5, we get 3, 5, 6 and 9, 10, 12, and 15.

**Comment by kytrinyx** [comment]
Good catch, @metadave, thanks. I've updated it here: exercism/x-commo@f09bccc
