### ISSUE TITLE
Menus missing on dashboard on mobile site

### ISSUE THREAD

**Issue by jhannes** [exercism/exercism.io#2488]
When I view the site on my phone (Samsung Note), the menu icon disappears and I can only view the dashboard page directly.

This is not the case when viewing the site in a small window in a desktop browser, but it is the same when viewing the site using Chrome Developer Tools with Device mode.

![image](https://cloud.githubusercontent.com/assets/18310/9427044/0ed4d82a-4967-11e5-9212-8ebb7fe9c268.png)

**Comment by kytrinyx** [comment]
Ouch, that's no good! Thanks for the heads up. /cc @mixolidia @sguermond any chance you'll have time to look at this?

**Comment by mixolidia** [comment]
@kytrinyx 
Looking into it. Madison+ Ruby was great but left us little time to do anything else.

**Comment by sguermond** [comment]
I think I know what is going on. The graph is not shrinking with the rest of the page, causing the menu button to appear on the far right of the page (have to scroll to it). I think fixing this is going to involve messing with the nits graph...

**Comment by sguermond** [comment]
@kytrinyx this issue is resolved, could you please close it?

**Comment by kytrinyx** [comment]
Yepp, thanks!
