### ISSUE TITLE
Unable to edit large semjs team

### ISSUE THREAD

**Issue by StevenACoffman** [exercism/exercism.io#2491]
Hello,
When I try to [edit the membership for the semjs team](http://exercism.io/teams/semjs), I get the heroku message:
```
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
```
I am able to edit the membership of other teams that I am an owner of. The semjs team has a large membership, and it has gotten slower with every new member's addition, so perhaps I've passed a tipping point.

**Comment by kytrinyx** [comment]
Yeah, the performance has been a problem on the team page for a while. I'm going to take a look at this next, but it will be a few days. The simplest and cleanest solution would be to create a fresh page just to edit, so it doesn't have to load all the team members and exercises at the same time.

**Comment by sguermond** [comment]
Working on it.

**Comment by kytrinyx** [comment]
Thanks!

**Comment by sguermond** [comment]
@StevenACoffman Are you able to edit the team now? I haven't played around with a very large team.

**Comment by StevenACoffman** [comment]
Yay! I am able the edit the team again! Thanks very much!
-Steve
