### ISSUE TITLE
Incorrect description Fsharp Difference of Squares?

### ISSUE THREAD

**Issue by MiyamotoAkira** [exercism/exercism.io#2497]
Hi,

Minor thing,
I believe the readme.md of the Difference of Squares on FSharp would need a slight change. Lines 3 and 13/14 seem to indicate that you need to do the operation (SumOfSquares - SquareOfSum). The numbers on that file and the tests do indicate (correctly) that is the other way around.

Cheers,
Jorge

**Comment by kytrinyx** [comment]
Ah, thanks for the heads up! It looks like this is a problem in the generic README, which means it's wrong in all the languages. I took a stab at clarifying it here:

https://github.com/exercism/x-common/commit/867a0be04e3885df1d7ae1756251b745b9d61e58
