### ISSUE TITLE
Markdown in docstrings is rendered incorrectly

### ISSUE THREAD

**Issue by yurrriq** [exercism/exercism.io#2498]
Example: http://exercism.io/submissions/3dddb5f4aaee49f8a8b893b1e5ff8800

**Comment by kytrinyx** [comment]
Oh, wow. That's pretty terrible!

I wonder if this is a bug in the [rouge](https://github.com/jneen/rouge) library.

**Comment by yurrriq** [comment]
Is that what GitHub uses? Somehow they deal with it: https://github.com/yurrriq/exercism/blob/clojure/allergies/src/allergies.clj

**Comment by kytrinyx** [comment]
I'm not sure what GitHub uses.

**Comment by yurrriq** [comment]
Hmm... I'll try do some digging on this tonight too.

**Comment by kytrinyx** [comment]
Thanks.

**Comment by yurrriq** [comment]
Maybe while I'm at it I can add an LFE lexer. 😈

**Comment by kytrinyx** [comment]
We upgraded to a version of the syntax highlighting library that I think has a fix for this. Is this still an issue?

**Comment by yurrriq** [comment]
Still looks the same to me :confused:

**Comment by kytrinyx** [comment]
Gah. Darn, ok.

**Comment by mfrost** [comment]
I believe this is a duplicate of #2380.

**Comment by kytrinyx** [comment]
Yepp, you're right. Thanks!
