### ISSUE TITLE
Let track mentors add other track mentors

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2501]
In the database we have the idea of "mastery" on the users table. This is an array of language tracks, and if a track is listed, then the user has unlimited access to that track: they can see everything that gets submitted, whether or not they have submitted a solution for the problem.

In the beginning I didn't know what to call this, but I think I'd like to call it "track mentor" rather than "mastery". We could change this in the database as well, for consistency/clarity.

We should expose this on the account page.

Any track mentor should be able to add more track mentors, as they see people who give good feedback and know a language well.

/cc @mixolidia @sguermond

**Comment by mhelmetag** [comment]
I'd like to try out a first iteration of this. At least to update the User model and get a migration out for `track_mentor` vs `mastery`.

I'm definitely not the best at frontend but I could also take a first swing at adding the track mentor section to the accounts page.

I'm guessing some steps would be:
* A section to manage the tracks that you are a mentor for (basically updating the track mentor array)
* A section to invite another user to be a track mentor
* Some type of invite notification and way to accept that invitation

I'll do some digging into the current account layout and mastery logic

**Comment by mhelmetag** [comment]
I changed the column mastery to track mentor, updated some tests and created a migration. All tests passed locally after `db:migrate`. I think this is a good jump off point. Let me know what you think :smile: 

https://github.com/exercism/exercism.io/compare/master...mhelmetag:issue%232501-1

**Comment by kytrinyx** [comment]
> I'm definitely not the best at frontend but I could also take a first swing at adding the track mentor section to the accounts page.

Excellent! I don't think we need any fancy front-end.

> I'm guessing some steps would be [...]

I don't think that we need to let you manage which tracks you're a mentor for.
An invitation system would be nice. It doesn't have to be complicated. We could show invitations on the notifications page (we also show team invitations there, I think).

> Does this logic exist? I don't see other mentions of mastery outside of the User model and a few tests.

I rewrote the logic recently so that we only use this field to run a cron job that writes records into the `acls` table, which controls what people have access to. That way we don't have two sets of rules about what you can see or not.

> I changed the column [...]

At the moment, if we deploy this change, then there is a bit of time between when the site is deployed and the migration finishes running where queries and methods are referencing a field that doesn't exist. I'd rather not have to take the site down for maintenance if we can avoid it.

Here's one way to make the change safely:

1. Create a migration that creates a new column on `users` called `track_mentor` that nothing references.
1. Create a data migration (`lib/tasks/data.rake`) to copy data from `users.mastery` to `users.track_mentor`
1. Deploy and run db migration and data migration.
1. Change the codebase to reference the `users.track_mentor` column instead of `mastery`.
1. Create a migration to drop the `mastery` field.
1. Deploy and run the db migration

What do you think?

**Comment by mhelmetag** [comment]
> Excellent! I don't think we need any fancy front-end.

Perfect :laughing: 

> I don't think that we need to let you manage which tracks you're a mentor for.
An invitation system would be nice. It doesn't have to be complicated. We could show invitations on the notifications page (we also show team invitations there, I think).

I'll read up about inbox, notifications, the current notifications template, etc.

> I rewrote the logic recently so that we only use this field to run a cron job that writes records into the acls table, which controls what people have access to.

So I see `acls` referenced in a rake task. Do you mean cron job like cron job runs a rake task periodically? Also, I saw a jobs dir with two template-y sidekiq jobs... are you looking to move the jobs from cron rake tasks to sidekiq?

> What do you think?

Sounds great! I've never really done a "safe" migration (or many migrations in general)... You're lists of steps seems better.

I'll get to it!

**Comment by kytrinyx** [comment]
> I'll read up about inbox, notifications, the current notifications template, etc.

If you get lost, holler. It's a bit of a mess, and it's not well documented (sorry!).

Yeah, we have a number of cron jobs that kick off rake tasks periodically.

> are you looking to move the jobs from cron rake tasks to sidekiq?

Nope, that's a hack that sticks jobs into redis so that a Go daemon on a different server can pick them up.

> I've never really done a "safe" migration (or many migrations in general)

In that case, you're in for a treat :) This is one of the things that started changing how I thought about shipping code in general, making it much more likely that I would make very small changes that kept my codebase in an always-shippable, always-deployable state.

> I'll get to it!

Excellent. Like I said, let me know if you need anything.

**Comment by mhelmetag** [comment]
I'm feeling pretty close on a first pass for adding a ui to see mentored tracks and invite others on the profile page. I should have a PR and some screenshots for that by tonight.

**Comment by kytrinyx** [comment]
Excellent, I look forward to seeing it.

**Comment by mhelmetag** [comment]
@kytrinyx , what more would you do for this issue?

**Comment by kytrinyx** [comment]
Nothing, I didn't realize it didn't get closed by the PR.
