### ISSUE TITLE
Count all comments in the conversation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2504]
Right now we're doing some weird stuff where we only count a comment if it's not by the original author of the solution, and if it's not rikki- the robot. We should just count all comments.

- [ ] when a comment is submitted, always increment the count, instead of doing it conditionally
- [ ] always decrement the count when deleting a comment
- [ ] write a query to migrate the comment counts

Alternately, when showing the submission page, do a proper SQL lookup instead of caching the count on the submission. Then we don't have to manage the state.

**Comment by mhelmetag** [comment]
Do you have an STR for this? It looks like comments are counted by `s.comments.size`... that seems okay to me.

https://github.com/exercism/exercism.io/blob/master/app/views/submissions/iterations.erb#L21

**Comment by kytrinyx** [comment]
What's an STR?

I think I may have fixed this at some point. Closing!

**Comment by mhelmetag** [comment]
Hah, we use that acronym at work... sorry! Steps To Reproduce.

Cool!
