### ISSUE TITLE
Do we really need to have the "views" tracking?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2506]
I'm starting to think about ways in which we can simplify exercism. I'm not convinced that having the number of views brings much value. We are storing every view in a table called submission_viewers. This seems kind of excessive.

![screen shot 2015-09-01 at 20 31 18](https://cloud.githubusercontent.com/assets/276834/9621807/8c43f8ee-50e8-11e5-813b-d054c9385388.png)

Thoughts?

**Comment by sguermond** [comment]
On the one hand it's nice to see that someone else is looking at your solution, on the other hand a better metric of how much attention your solution is attracting is the number of nitpicks. Since you can't see views anywhere besides the actual page, I don't think it's a necessary feature.

**Comment by kytrinyx** [comment]
Agreed. Let's take it out.
