### ISSUE TITLE
Use "lock" instead of "star" on profile page

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2507]
Instead of showing a star by exercises that you can access, let's use a lock for exercises where you only get the readme/test suite. I think this would let us explain less.

```
<i class="fa fa-lock"></i>
```

@sguermond what do you think?

**Comment by kytrinyx** [comment]
Note: I'm doing work on the profile/account pages here: #2505 -- if we want to change to the lock let's wait until that gets merged.

**Comment by sguermond** [comment]
I like this idea, but I think it would be good to explain somewhere why you can't see the code to other problems

**Comment by kytrinyx** [comment]
Agreed. We could put that at the bottom of the page.

**Comment by kytrinyx** [comment]
Actually, let's not worry about the archive flag PR. That's going to take a while, I'll just resolve the conflicts on my end.

**Comment by sguermond** [comment]
That looks great! Very intuitive.
