### ISSUE TITLE
Provide access to other solutions as soon as you've submitted?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2510]
What do you think of simplifying so that you always can access other people's solutions to the exercise you've done, provided that you've submitted at least one iteration?

This would simplify things:

1. We don't have to have any sort of interface for "unlocking nitpicking"
2. The behavior for exercises on teams and elsewhere in the code is the same. No more special cases.

/cc @sguermond @mixolidia

**Comment by sguermond** [comment]
I think this would be especially valuable because you can see other conversations happening around the same problem and ask questions that could help you better refactor your code (ie. "Why did you do this? I'm not familiar with X syntax").

**Comment by kytrinyx** [comment]
OK, cool. I'll make this change, then.
