### ISSUE TITLE
Icons on homepage too big?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2513]
I suspect that the three icons in the middle of the homepage lost some styling.

![too-big-icons](https://cloud.githubusercontent.com/assets/276834/9647400/e980ee7a-5199-11e5-9736-eb6e9ce5d3ca.png)

**Comment by chinaowl** [comment]
They are especially big in mobile:

![image](https://cloud.githubusercontent.com/assets/2628718/10177700/63b53e28-66b0-11e5-8189-ac0a6cbfa8a1.png)

I only just discovered this project, but I'd like to take a look at this issue.

**Comment by kytrinyx** [comment]
OMG, that's impressive :)

I actually have no idea how big they are... if you mess with it, I would just say "try something that seems good to you".

**Comment by chinaowl** [comment]
I figured out the problem. An extra `</div>` caused a lot of styles to be lost. The pull request is here: https://github.com/exercism/exercism.io/pull/2568

**Comment by kytrinyx** [comment]
Merged and deploying. Thanks!
