### ISSUE TITLE
Ditch the suggestion on the dashboard?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2514]
The code supporting the "have a moment?" part of the dashboard is incredibly complicated and expensive.

What do you think about ditching this for now, and then once we've simplified a bunch of things, think about how we can encourage people to talk to each other more?

![screen shot 2015-09-02 at 18 05 27](https://cloud.githubusercontent.com/assets/276834/9647734/4c1b5978-519d-11e5-8550-3c269b314ceb.png)

/cc @mixolidia @sguermond

**Comment by sguermond** [comment]
@kytrinyx do you have any usage data on it? If people don't use it then it's worth removing, but since it is the most obvious engagement driver on the site I would be reluctant to remove it before there's something else in the works to replace it.

**Comment by kytrinyx** [comment]
I have no clue what is being used and not. You're right. Let's leave it for now.
