### ISSUE TITLE
exercism fetch results in 404

### ISSUE THREAD

**Issue by cew821** [exercism/exercism.io#2517]
I just installed the CLI on OS X, which seemed to go fine. However, running 

`$ exercism fetch` resulted in:

`Error fetching assignments. HTTP Status Code: 404`

**Comment by cew821** [comment]
After some poking around, I realized that I had a very old version of the CLI installed, with no upgrade option. deleting it from from `username/bin/exercism` resolved the issue.

**Comment by kytrinyx** [comment]
Cool, glad you got it sorted out.
