### ISSUE TITLE
Menu offers to reopen submission that is still open

### ISSUE THREAD

**Issue by hkockerbeck** [exercism/exercism.io#2518]
To the best of my knowledge, my submission on RNA transcription in Ruby (http://exercism.io/submissions/57d51ca4e66240828be7fdef597ec273) is still open. I wanted to close it, but the "Manage" menu doesn't offer me that option. The menu only offers to "Reopen Exercise", "Hibernate" and "Delete". If I try to reopen the still open submission, I get the message that there's "No Such Submission".

**Comment by kytrinyx** [comment]
Thanks, I'll look into this.

**Comment by kytrinyx** [comment]
OK, I checked and your submission is open. There's something very strange going on with the reopen command. I'll dig further into it today.

**Comment by kytrinyx** [comment]
I think I found the problem. I'm deploying a fix now. Would you mind checking this again?

**Comment by hkockerbeck** [comment]
I just successfully closed the submission. It's working fine now, thanks :)

**Comment by kytrinyx** [comment]
Excellent! Thanks for checking back so quickly.
