### ISSUE TITLE
List teams on dashboard instead of top navbar?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2519]
What do you think of having the teams as a section on the dashboard instead of as a dropdown in the navbar?

/cc @mixolidia @sguermond

**Comment by sguermond** [comment]
Yeah, that makes sense. I think the dashboard needs to be even more of a central place, and the navbar gets cluttered/doubled up on smaller screens (before it jumps to mobile mode).

**Comment by kytrinyx** [comment]
Yeah, it would be fantastic to get rid of some of the stuff in the navbar!

**Comment by mixolidia** [comment]
Yeah, a teams section in the dashboard makes sense. We were just talking the other day how the nav bar is super crowded.

**Comment by kytrinyx** [comment]
Maybe we can also use the "bell" icon like GitHub does for the notifications, instead of having the whole word there.

**Comment by mixolidia** [comment]
Yeah, that would be nice!

**Comment by mixolidia** [comment]
Font-Awesome also has a little bullhorn. So just swap out the word with the bell and leave the counter.

**Comment by wobh** [comment]
What accessibility concerns need to be addressed to use an icon?

**Comment by kytrinyx** [comment]
Tooltips, I think.

**Comment by kytrinyx** [comment]
@GustavoCaso this one is also a pretty straight-forward one.

The navigation bar lives in `lib/app/views/application/_nav.erb` and the dashboard starts at `lib/app/views/dashboard.erb`.

**Comment by GustavoCaso** [comment]
@kytrinyx got it

**Comment by kytrinyx** [comment]
Thanks :)

**Comment by GustavoCaso** [comment]
Not Problem

**Comment by koppen** [comment]
Since #2627 has been merged, moving the teams section to the dashboard, I guess this issue can be closed?

**Comment by kytrinyx** [comment]
Thank you, yes.
