### ISSUE TITLE
Please check out the new exercises stream (prototype)

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2520]
@exercism/track-maintainers If you have a moment, would you mind checking out the new "inbox" style list of exercises that are active (open for feedback)?

http://exercism.io/tracks/assembly/exercises

Swap out `assembly` for a language that you actually use on exercism.

I haven't exposed this in the user interface yet, so it's a bit awkward to get to.

This is intended to replace the lists at `http://exercism.io/nitpick/LANGUAGE/recent`. A huge difference from before is that exercises show up even when other people have commented, which means there's a much larger chance of... (drumroll)... _conversations_!

I expect that we'll want a number of improvements to this basic prototype, but I actually think that it's a big enough improvement that we could launch it without getting too fancy.

This will allow for a number of simplifications:

- It gets rid of the whole `mute` thing, which is nearly impossible to understand or explain.
- It gets rid of submission states. Instead of the various submission states (pending, needs input, hibernating, done) all of which got duplicated on the exercise, we have a single flag on the exercise.
- "Next submission" becomes more deterministic: It's the next submission (chronologically older per the "last active at" timestamp) in whatever filter you are currently in.
- The query to show a list of active submissions is MUCH, much simpler. Much. It also performs better.

I wanted to get feedback before I move forward any further. Thoughts?

--------

Update based on discussion below: improvements to make before launching.

- [x] exercises should not be marked as **unread** if there are no comments newer than the most recent submission.
- [x] muted submissions should be migrated to read/unread
- [x] mark as read on individual exercises
- [x] mark as read for an entire track
- [x] add comment count (total comment count for exercise including author's comments)
- [x] add iteration count
- [x] add detail about the last activity
... probably more :)

--------

A warning up front: User interface design, HTML, and CSS are things that I'm generally quite terrible at, so I've tried making something that is _barely good enough_. If we can get the basics to a decent place, then perhaps someone with actual front-end skills will be willing to jump in and improve on what's there.

**Comment by verdammelt** [comment]
I like the intent of trying to get more conversation. I think that this might help. Certainly as a track maintainer I think it would help me make sure I've reviewed all/most of the new submission.

First thing I see is that I will need a 'mark all as read' button for each exercise and for entire tracks. At least in the beginning I don't want to go through clicking on everything to make sure it is marked as 'read'. I've muted a bunch of submissions waiting on new versions or comments - they seem to be showing as unread in this page.

**Comment by kytrinyx** [comment]
I just wanted to add that since I started trying this out a couple of days ago, I discovered a person in the Ruby track who gives great feedback. That's a +1000 for this change.

> First thing I see is that I will need a 'mark all as read' button for each exercise and for entire tracks.

Agreed.

> I've muted a bunch of submissions waiting on new versions or comments - they seem to be showing as unread in this page.

Yeah, we should probably use mutes to migrate read/unread state (I forgot about that). The migration I did was based on whether or not people had commented.

**Comment by kytrinyx** [comment]
Is there a UX idiom for 'mark as read'?

**Comment by kytrinyx** [comment]
@verdammelt I've migrated muted to the read/unread.

**Comment by verdammelt** [comment]
Is it intentional that one's own submission would also be not marked as read? I noticed an old submission of mine with no comments - but looked like 'new'. I submitted it - doesn't seem like that should be 'new'.

**Comment by kytrinyx** [comment]
Your own submissions are supposed to be viewed. If you submit new iterations, it's marked as viewed, but I must have missed that in the migration. I'll fix that.

**Comment by kytrinyx** [comment]
@verdammelt the views have been migrated on your own submissions where there are no newer comments.

**Comment by LegalizeAdulthood** [comment]
Looks great! :smile_cat:  As a track implementer, I haven't had time to review all the submissions personally, but now I can really see how people are using the track and that's very useful to me.  I never liked the "hibernating" thing anyway, because I wanted my solutions to be permanently posted for people to compare against their attempts.

**Comment by wobh** [comment]
I was going to comment earlier, but I got distracted reading code. I think that means it's okay.

**Comment by jtigger** [comment]
I jus want to say again how delighted I am by this move.  It is such a better UX: it's light on concepts, organizes the data in the way I think about it (email inbox is a very congruent metaphor), and most importantly I am instantly feeling much more aware of the activity in the community.

A few more touches that outright connect people (e.g. personally managed lists of other exercists) will invite a deeper discussion.

Imagine the quality of a dialogue that follows from, "hey @hotkeyz9000, I've noticed you give lots of advise that points people to the Functional language features... why is that?  What benefits are you hoping others will see by taking that approach?"

Think of what potential barriers exist that keeps someone from asking that kind of question... and let's eliminate them.

In my mind, this inbox feature is a step in that direction.

**Comment by jtigger** [comment]
I'm wanting to know what that last activity was and by whom:

"Nitpicked by @jtigger just now."
"Submitted Iteration #4, 2 hours ago."

**Comment by jtigger** [comment]
I love the per-track count of submissions.

**Comment by jtigger** [comment]
Would it be a positive feedback loop if a given submission was marked as "attracting attention", "drawing participation", "engaging conversation"? (one devil head / two devil heads slightly overlapping / three devil heads horizontally offset)

Each time "last activity" is updated, if it has been less than a couple of days, the submission gets a bump up.  if it has been more than a couple of days, it gets bumped down.

**Comment by rchavarria** [comment]
I agree with @jtigger, it would be awesome if last activity were more detailed.

I also miss the number of Nits and Revisions for each item. As an exercism.io user they usually helps me to find submissions (generally old ones) that are worth reviewing for learning. For example, a submission with one revision and zero nits means it probably isn't very interesting. But a submission with 4 revisions and 2 nits probably means there was a brief discussion and the author put a new concept into practice.

**Comment by kytrinyx** [comment]
I'll add the iteration count (that's easy).

More information about the last activity might more tricky in terms of implementation, unless we simply store a text string in the database (dirty, but it would get us there quickly).

I'm not sure about the feedback loop--it might be. I don't know how we would weight the sorting without using something like elasticsearch, though. I'd rather not go there until we have had this out in the wild for a while getting feedback on usage.

I would love to see meta-dialogue as suggested above.

**Comment by kytrinyx** [comment]
I've decided to go with the low-cost hack that just saves a string to describe the most recent activity. This means that if someone changes their GitHub user name the explanation will be wrong, but I think that's fine.

When we implement the proper activity feed described in #1899 then this will be implemented in a less dirty/hacky way.

**Comment by kytrinyx** [comment]
I've implemented "mark as read" both at the exercise, problem (track+slug), and track level.

**Comment by kytrinyx** [comment]
@sguermond @mixolidia I forgot to cc you on this thread.

**Comment by kytrinyx** [comment]
I've added the comment count and iteration count. Deploying now.

**Comment by kytrinyx** [comment]
I'm migrating the last activity description now.

**Comment by kytrinyx** [comment]
Holy smokes I love seeing what the last activity was. Especially when you look down and see X commented just now. X commented a few minutes ago. X commented an hour ago. Y commented two hours ago. X commented two hours ago.

Like... Who is this X person who's giving all this feedback?

**Comment by kytrinyx** [comment]
Thanks for your feedback everyone.
