### ISSUE TITLE
Font size perhaps too big in <blockquote>

### ISSUE THREAD

**Issue by Peque** [exercism/exercism.io#2521]
I think the quoted text should have similar (if not the same) size to the rest of the text in the nitpicks. See the image bellow:

![blockquote](https://cloud.githubusercontent.com/assets/526577/9746744/ef132f9e-5679-11e5-9808-aab8568d1817.png)

Instead, it could be a little gray and/or in italics and/or with a different background color.

Examples
========

Font resized only
----------
![00](https://cloud.githubusercontent.com/assets/526577/9747165/6387b9b0-567c-11e5-859d-4e684e7e0680.png)

Font resized + italic + gray
----------
![02](https://cloud.githubusercontent.com/assets/526577/9747167/64cfa238-567c-11e5-98cb-65c942f58f2e.png)

Font resized + background color
----------
![03](https://cloud.githubusercontent.com/assets/526577/9747296/30702142-567d-11e5-9eab-a4604492b43e.png)

**Comment by kytrinyx** [comment]
Thanks, @Peque - I'm marking it as a bug.

**Comment by Peque** [comment]
@kytrinyx I agree. Just for the record:

```css
blockquote {
    font-size: 1em;    /* or 14px */
    color: gray;
    font-style: italic;
}
```

Perhaps it should be added in [`comment.css`](https://github.com/exercism/exercism.io/blob/master/lib/app/public/sass/base/components/comment.scss)? (inside the `.comment {}` section)

**Comment by kytrinyx** [comment]
> Perhaps it should be added in comment.css? (inside the .comment {} section)

That sounds reasonable :)

**Comment by kytrinyx** [comment]
It worked. Deploying now. Thanks!
