### ISSUE TITLE
Problem with visualize - python sintax

### ISSUE THREAD

**Issue by yeion7** [exercism/exercism.io#2522]
![screenshot from 2015-09-08 22-06-48](https://cloud.githubusercontent.com/assets/9127504/9752459/1b0af734-5676-11e5-8aad-e5f46859b2e6.png)

**Comment by kytrinyx** [comment]
Thanks for reporting this. I think I saw a related bug with doc comments in one of the other languages as well.

**Comment by kytrinyx** [comment]
We upgraded to a version of the syntax highlighting library that I think has a fix for this. Is this still an issue?

**Comment by mfrost** [comment]
I believe this can be closed now that #2625 is merged.

**Comment by kytrinyx** [comment]
Thanks. I'll be deploying today (yesterday was 5 meetings and trying to write a talk proposal, didn't have time to accidentally break anything on the site).
