### ISSUE TITLE
UTF-8 interpreted as ISO-8859-1 on submissions page

### ISSUE THREAD

**Issue by eigengrau** [exercism/exercism.io#2523]
My submissions for Haskell exercises contain a fair deal of non-ASCII characters. Thus far, the site always rendered the submissions adequately (even if the Haskell syntax highlighter worked very poorly for such files). However, I just submitted another exercise (in UTF-8 encoding), but the site renders the code as if it were ISO-8859-1, resulting in Mojibake.

E.g., the character `α` is shown as `Î±` on the site, which is what `α` will look like when erroneously interpreted as latin-1. Since my old solutions all displayed properly, I suspect you are detecting submission file encodings automatically, and some character in my submission triggers a bug in the detection logic.

Here’s the affected [exercise](http://exercism.io/submissions/18b902f9104b4703922292e6106a39f1).

**Comment by edescourtis** [comment]
Interesting I looked at the HTTP headers and HTML it seems to be served as UTF-8 so the mistake must be somewhere else. Perhaps in the submission tool.

**Comment by kytrinyx** [comment]
I don't recall how we are doing this, but your suspicion sounds right. Thanks for reporting this.

**Comment by eigengrau** [comment]
I’ve come across this in one further submission now, though I still can’t make out what triggers this. The files all validated as UTF-8. As a work-around, I’ve found that adding a BOM will stop submissions from being read as Latin-1.

**Comment by kytrinyx** [comment]
Thanks for the additional details.

**Comment by petertseng** [comment]
I think, but can't be sure, that this is the same issue as https://github.com/exercism/cli/issues/309, and that https://github.com/exercism/cli/pull/346 would fix it.

I base this on the fact that the submission was made after the release (2015-05-08) of https://github.com/exercism/cli/pull/182 and that the submission contains at least 1024 bytes of ASCII before non-ASCII.

**Comment by kytrinyx** [comment]
Is this still an issue?
