### ISSUE TITLE
Rename "Exercises"

### ISSUE THREAD

**Issue by sguermond** [exercism/exercism.io#2525]
There are currently two navigation items called "Exercises" going to two different things. 

![Exercise links](https://raw.githubusercontent.com/sguermond/images/master/exercism-exercise-menu.png)

One goes to the new inbox feature, replacing the Nitpick/Pending page, and the other one goes to the user's Exercise page aka profile page other people can see.

These should be renamed in a way that better reflects what they do.

**Comment by kytrinyx** [comment]
How about "Your Exercises" for the one in the dropdown?

**Comment by kytrinyx** [comment]
Actually, let's call it "Profile".

**Comment by sguermond** [comment]
I like Profile.

However, I think that by removing all mention of Nitpicks (or whatever they end up being renamed as), it is hard to see what Exercises leads to, and someone unfamiliar with the site who is searching for a way to review others' code might not realize that Exercises is the link they are looking for. I think it should still be named Nitpick.

**Comment by kytrinyx** [comment]
I think that it would be better to name things after what they are (a list of exercises) rather than what we want you to do (comment).

How about "Solutions" instead of "Exercises"?

**Comment by kytrinyx** [comment]
I've renamed the one in the dropdown to "Profile", but I'm leaving this open so we can find a good name for the other nav item.

**Comment by kytrinyx** [comment]
@sguermond how about "Profile" vs "Activity"? We might have to re-think "Activity" on the dashboard, though.

**Comment by kytrinyx** [comment]
It doesn't seem like this went anywhere. I'm going to leave it as is for now, and if someone comes up with a better suggestions, we can change it.

**Comment by kytrinyx** [comment]
FYI: I ended up renaming it to "Activity Streams".
