### ISSUE TITLE
Remove your exercises from the account, leaving them only in the profile

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2526]
Right now we put your exercises in two places, which seems unnecessary.

@sguermond You're in the middle of working on some of this code (#2469). What do you think?

**Comment by sguermond** [comment]
I totally agree. The account exercises are redundant.

**Comment by kytrinyx** [comment]
Cool, do you want to take them out, or should I?

**Comment by sguermond** [comment]
I can do it since I'm fiddling around with the code anyway.

**Comment by kytrinyx** [comment]
cool!

**Comment by sguermond** [comment]
@kytrinyx can you close this?

**Comment by kytrinyx** [comment]
yepp, thanks!
