### ISSUE TITLE
Dashboard is recommending that I nitpick Ruby exercises I have not completed (and I can access those users' solutions)

### ISSUE THREAD

**Issue by mandel01** [exercism/exercism.io#2527]
The new dashboard is fantastic!! For a number of weeks it has been working very well. Tonight I noticed that it recommended I nitpick a Ruby exercise, but I have only completed Python exercises. When I clicked on the exercise it took me to their solution (not just the test). In case it helps with troubleshooting, it showed me both exercises that I had completed in Python (e.g., bob) and ones I had not (e.g., series).

I reloaded the page a bunch of times and actually it is only recommending Ruby to me.

`Help @username by providing some feedback on their solution to bob in Ruby.`

**Comment by kytrinyx** [comment]
Ah, thanks for the heads up. I broke this yesterday. I'll fix it today!

**Comment by kytrinyx** [comment]
OMG. I found the bug. It's super embarrassing... I hard-coded my own user-id to experiment with the query in production, and then when I copy/pasted it into the codebase I forgot to replace it with the current user's id. I'm pushing up the fix now.

**Comment by mandel01** [comment]
That is really funny. So, not a sly way to get more people into Ruby then ;)
The mouseover on "Why Github?" looks good in this version too!

**Comment by kytrinyx** [comment]
Awesome! Yeah, definitely not a sly way of getting people into Ruby. Thanks again for reporting this so quickly.
