### ISSUE TITLE
Recently viewed exercises missing

### ISSUE THREAD

**Issue by sguermond** [exercism/exercism.io#2528]
Changing from "looks" to "views" removed the "recently viewed" functionality on the dashboard and in `/looks`. I get a 404 when looking at '`/viewed'.

**Comment by kytrinyx** [comment]
I added the recently viewed functionality on the dashboard when I removed the looks, and it was working locally. I'll look into what's going on in production. `/exercises/viewed` isn't implemented it. I started to, but then got distracted.

**Comment by kytrinyx** [comment]
Found it. Pushing the fix now. Thanks for catching it!

**Comment by sguermond** [comment]
Hooray! :D
