### ISSUE TITLE
Couldn't find that user message showing on clicking exercises for user with no submitted exercies

### ISSUE THREAD

**Issue by mixolidia** [exercism/exercism.io#2529]
When a user with no submitted exercises clicks on 'exercises' on the nav bar, a 'Couldn't find that user.' message pops down. It should probably read 'You haven't submitted any exercises yet.' 

![screen shot 2015-09-11 at 4 52 38 pm](https://cloud.githubusercontent.com/assets/6855556/9828818/191e423a-58a8-11e5-9561-bd46d8bfd383.png)

**Comment by kytrinyx** [comment]
It's not supposed to show up for users with no exercises. I'll check what's going on.

**Comment by kytrinyx** [comment]
Fixed in f19f73fb8f1ebe5f1b6274aea06fb3fadf85a9fe, deploying now.
