### ISSUE TITLE
Change strategy when showing member exercises on team page

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2531]
Right now the team page:

- selects submissions (a.k.a. iterations) rather than exercises
- uses the submission.state to select what to show
- lets team managers see all exercises

Instead, let's select exercises, and not give team managers special access.

**Comment by wobh** [comment]
Do we need a schema of privileges and roles? Interfaces for changing them?

- add-remove users to teams :: "team manager"
- view exercises for a team :: "team mentor"
- add-remove privileges to team members :: "team admin"

A similar arrangement could be in place for language tracks such that privileges apply to the scopes.

The separation gives flexibility but likely most teams will have one or two with all roles.

**Comment by kytrinyx** [comment]
Probably, but we haven't done the user interviews to see how people are using teams yet, so I don't want to complicate matters without first having a solid reason to do so.

**Comment by kytrinyx** [comment]
This got fixed, as far as I can tell.
