### ISSUE TITLE
exercism submit generates a 400 error

### ISSUE THREAD

**Issue by ianynchen** [exercism/exercism.io#2533]
when i submit a file, exercism always says: unable to submit (HTTP: 400) - unknown problem (track: go, slug: src, path: ), version is 2.2.1,

exercism debug output: 

**** Debug Information ****
Exercism CLI Version: 2.2.1
Exercism CLI Latest Release: 2.2.1
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/ianynchen
Config file: /Users/ianynchen/.exercism.json
API Key: 9d2f***************************************
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/ianynchen/exercism

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).

**Comment by kytrinyx** [comment]
What was the `pwd` when you were submitting, and what was the actual command to submit?

**Comment by ianynchen** [comment]
my exercise path is ~/exercism, the project path is ~/exercism/go/src/leap, so is pwd, and i used exercise submit leap.go and exercise submit ./leap.go both with the same error HTTP 400

**Comment by kytrinyx** [comment]
Ah, the path is expected to be `$EXERCISM_DIR/$LANGUAGE/$PROBLEM`, so `~/exercism/go/leap`.

If you say `exercism fetch go leap`, it will put the problem in the expected place.

**Comment by kytrinyx** [comment]
I'm going to close this issue, but feel free to re-open it if this doesn't resolve your issue.

**Comment by ianynchen** [comment]
well that solved my problem. thank you very much
