### ISSUE TITLE
Language Landing Pages (the advanced edition)

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2536]
**This is a UX, design, and front-end task.**

At the moment we have a drop down in the top nav bar with a list of all the languages that we have exercises for. The page itself has a quick intro about the language, a list of the available exercises, and a link to the (off-site) documentation about how to get started in that language.

It would be fantastic to have each page be rich, helpful, and enticing.

The goals for these pages are

1. see what languages are available
2. see how to get started in a language
3. provide interesting information to make it more likely that you explore further
4. improve the language tracks by getting more people to contribute

Some ideas:

* add "how-to get started" documentation (we have this available via an API endpoint, but it's not being used yet
* what to do if you get stuck
* resources if you want to learn the language (exercism is for practice, and it assumes that you know the basics)
* how to contribute to the exercises (found a bug in a test suite? want to clarify a readme? Want to port an exercise from one language to another? Want to add an entirely new exercise?)
* key stats about activity in that track (how many people are submitting solutions / commenting, for example)

------

If something needs to be implemented on the backend to support this, there are several people who have experience working on backend issues, so it should be easy to make that happen (if you're not comfortable doing it yourself).

**Comment by sguermond** [comment]
The basics:
- info about that language. What's specific about that language? What is it used for? Who uses it?
- exercism stats: how many problems, how many users on that track, average number of comments per exercise
- link to outside resources for basic syntax (if someone is interested in a language but doesn't know it yet)
- installation basics
- testing basics

Next level: 
- contribution info (I feel pretty strongly about contribution guidelines being clearly separated from use guidelines so as not to confuse/scare off newbies)

**Comment by kytrinyx** [comment]
I completely agree about the contribution guidelines being completely separate.

We could have some small thing at the bottom saying "Interested in helping make the Python track better?" with a link. That way we make it obvious that you can contribute, but we don't mix it with the rest.

**Comment by kytrinyx** [comment]
The language landing pages have been improved. More could always be done, but I think this issue is ready to be closed.
