### ISSUE TITLE
Homepage Redesign

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2537]
**This is a UX, design, and frontend task**

We like the current branding, it has a certain playfulness, but at the moment the homepage leaves users with more questions than answers.

Here's what I think we probably need:

1. give users an idea about what exercism is
1. make it clear who it is for (if you don't know any programming at all, you're going to need to learn a bit first, since exercism doesn't teach you coding, it gives you exercises to practice)
1. reassure users about the "login with GitHub" - what is GitHub and why do we use it? What permissions will we ask for? (no permissions, we just want a simple way to authenticate users, without having to build in a login system ourselves)
1. describe (diagrams?) what the process is like (fetch a problem, solve it [locally], submit it to the website, have a discussion with peers [on the website])
1. clear call to action to tell people how to get started

**Comment by amar47shah** [comment]
For point #2: In addition to needing some programming experience, exercism users will need a basic familiarity with the command line.

For point #4: Often, I think one way to explain exercism (to intermediate and above coders) is to compare it to source control, i.e. when you "exercism submit," it's like committing and pushing in git. There's now a mile marker for your progress, and others can access your work and give feedback on it. Of course, since the analogy requires familiarity with VCS, it might be too technical to include on the home page.

**Comment by kytrinyx** [comment]
Yeah, about point 2 I think you're right. For point 4 I would rather stay away from the VCS metaphor for a couple of reasons, the first being the one you mentioned: Jargon. This could be offputting if you don't have familiarity with source control. The second is that the implementation model is very different from git, and I don't want people to get ideas about the process that are misleading.

**Comment by kytrinyx** [comment]
This issue has been claimed by a small group working on UX and product design: @jtigger, @jenndodd, @mixolidia, @sguermond, and myself.

**Comment by kytrinyx** [comment]
Here's a rough plan for the new homepage:

1. The unifying concept is "leveling up", using the Dreyfus model.
2. Talk to people at each level (novice, advanced beginner, competent, proficient, expert). Recognize the pains that they're probably experiencing at that level, and how exercism can help address that.
3. Link each level to a separate "getting started" page. We will likely only need two: one that explains carefully, with minimal jargon and lots of detail, and one that gives a very quick overview.

**Comment by kytrinyx** [comment]
I've done a first round of changes for the homepage. I'm pretty happy with how it worked out. I'll likely keep tweaking this, but I am considering this issue as closed.
