### ISSUE TITLE
Next submission button goes to 404 pages

### ISSUE THREAD

**Issue by MartinDelille** [exercism/exercism.io#2540]
I submit [my code](http://exercism.io/submissions/7ac3b1612df143bb8e86ace58fbf464d) for an exercice and wanted to see other submission by clicking the *Next submission* button and I got this 404 page: http://exercism.io//exercises/ (notice the double slash).

**Comment by kytrinyx** [comment]
It looks like there is a missing segment.

This works for me, and I'm not sure what's different in your case.

Question: have you ever gone to the "Exercises" link in the nav bar? If not, that could be it... it wouldn't know where to link you to next. I will have to try that out locally.

**Comment by MartinDelille** [comment]
No and since I tried that the problem is fixed...

**Comment by kytrinyx** [comment]
OK, cool, that narrows it down! Marking as a bug. Thanks :)

**Comment by kytrinyx** [comment]
Fixed in #2544
