### ISSUE TITLE
Error parsing API response

### ISSUE THREAD

**Issue by patrickbeeson** [exercism/exercism.io#2545]
When fetching new exercises via the CLI:

`>> exercism fetch`
`Error parsing API response: [invalid character '<' looking for beginning of value]`

**Comment by patrickbeeson** [comment]
Removed and installed the latest version. That fixed it.

**Comment by kytrinyx** [comment]
Glad you got it sorted!

**Comment by spazmeck** [comment]
Had the same issue. Removing the binary and dot-file and then reinstalling fixed the issue.
