### ISSUE TITLE
exercism fetch should not give hello-world if I already have submitted for the language

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism.io#2546]
When I do `exercism fetch ruby` and don't have `hello-word` directory, the `cli` will fetch back `hello-world` along with a new exercise.

eg.
```
New:                         2 problems
ruby (Hello World)           /home/tech-6/exercism_submissions/ruby/hello-world
ruby (Nucleotide Count)      /home/tech-6/exercism_submissions/ruby/nucleotide-count
```

I think `hello-world` should be fetched only if I am new to the language and have not submitted any assignment for that language.

**Comment by kytrinyx** [comment]
Yes, I agree. Thanks!

**Comment by tejasbubane** [comment]
Is it ok if we make `exercism.io/api/v1/exercises/<language>` return `hello-world` only if user has zero submissions in the language? That way `x-api` will not return it to the `cli`.

**Comment by kytrinyx** [comment]
Yeah, that would be fine. Or we could add logic to the x-api progression to exclude hello-world if there are other problems that are solved.
