### ISSUE TITLE
Allow nitpicking after first submission

### ISSUE THREAD

**Issue by sguermond** [exercism/exercism.io#2548]
We currently hide the Exercises tab until users have submitted something after Hello World, but I think it would be less discouraging if they were able to explore the commenting function as soon as they first submit something. Keeping the Hello World out of exercises also reduces the number of people commenting on them, which means that new users might never get someone commenting on theirs and might give up after waiting a while.

**Comment by kytrinyx** [comment]
We never intended for people to comment on Hello World. Rikki warns people that this is the case. If we add hello world then there will be a bajillion hello worlds, which I don't think adds any value. The exercise is only there to validate that you've gotten your environment set up, and it's much more interesting to solve a real problem.

**Comment by sguermond** [comment]
Just found the rikki quote: 
> In the case of hello world, however, we won't be encouraging conversations and iterations.

Guess I skipped over reading that. Maybe something to keep in mind during the redesign is leaving plenty of signs saying that Hello World is only a test.

**Comment by kytrinyx** [comment]
Yeah, agreed.
