### ISSUE TITLE
Add SwiftLang Logo

### ISSUE THREAD

**Issue by masters3d** [exercism/exercism.io#2555]
![alt text](https://developer.apple.com/assets/elements/icons/128x128/swift_2x.png)

https://github.com/exercism/exercism.io/blob/919c42b8b2bbcea851e760693df407523a8b302d/lib/app/public/sass/base/components/main.scss

**Comment by tejasbubane** [comment]
I think this can be closed with #2590 @kytrinyx

**Comment by masters3d** [comment]
Thank you!
