### ISSUE TITLE
Archived is not the same as "done"

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2562]
We've moved to archived/active on the exercise level, rather than "done" on the submission level, but the submission page still uses a checkmark on the most recent iteration.

We should change this to have something up above the iteration tabs that show that it's archived.

![screen shot 2015-09-28 at 9 25 59](https://cloud.githubusercontent.com/assets/276834/10140079/16b18fa2-65c3-11e5-8c98-44c7eab19973.png)

**Comment by kytrinyx** [comment]
@GustavoCaso I think this is a relatively straight-forward one.

The code for the code page starts at `lib/app/views/submissions/show.erb`

**Comment by GustavoCaso** [comment]
@kytrinyx Great

**Comment by GustavoCaso** [comment]
@kytrinyx You want to display some kind of text depending if is archive or active and remove the checkmark ?

**Comment by kytrinyx** [comment]
Yeah, I want to remove the checkmark and then instead of having something next to the last iteration number, I'd like to have something that says `archived`, but up in the area over it (where it says the name of the problem and "submitted by X a while ago").

**Comment by kytrinyx** [comment]
@GustavoCaso are you claiming this one?

**Comment by GustavoCaso** [comment]
Sure @kytrinyx . Sorry I have been swap with other stuff but yes I claim it looks easy enough.

**Comment by kytrinyx** [comment]
No pressure, I just want to make sure nobody else grabs it and then you both do the work.

**Comment by GustavoCaso** [comment]
Thanks @kytrinyx

**Comment by mhelmetag** [comment]
Hey @GustavoCaso, are you still working on this issue?

**Comment by GustavoCaso** [comment]
Hey @mhelmetag actually not I was working on other ones. Take it want

**Comment by mhelmetag** [comment]
Sweet!

**Comment by mhelmetag** [comment]
So I worked on this a bit and came up with this:

Unarchived:
<img width="796" alt="screen shot 2015-12-20 at 7 47 05 pm" src="https://cloud.githubusercontent.com/assets/8609429/11925563/8f443600-a771-11e5-96d6-c7e5b989cac8.png">

Archived
<img width="805" alt="screen shot 2015-12-20 at 7 47 26 pm" src="https://cloud.githubusercontent.com/assets/8609429/11925560/8d77cdf0-a771-11e5-9b69-8bcd80f9e097.png">

Thoughts?

**Comment by GustavoCaso** [comment]
@mhelmetag  Can you open a Pull Request to have a look ? So I can see in my local environment. 

I really like the icons. What do you think @kytrinyx ?

**Comment by mhelmetag** [comment]
Can do!

**Comment by kytrinyx** [comment]
I like the archived label!

I don't think we need the icon on the iteration number tab, since the whole exercise is archived, not individual iterations.

**Comment by mhelmetag** [comment]
Okay! I'll make a preliminary pull tonight with just the label. That sounds good.

I had a few other questions (re instances of "completed" throughout the codebase) but I'll have to wait until I have the code in front me.

**Comment by mhelmetag** [comment]
Updated to just have the label and hide the refresh icon when archived:

Archived:
<img width="796" alt="screen shot 2015-12-21 at 6 11 21 pm" src="https://cloud.githubusercontent.com/assets/8609429/11946519/5ab9c360-a810-11e5-8c40-a40b0e3e363d.png">

**Comment by kytrinyx** [comment]
Lovely!

**Comment by kytrinyx** [comment]
When you're ready to have the PR reviewed, please post a comment in the PR discussion thread.

**Comment by kytrinyx** [comment]
Closed by #2671.
