### ISSUE TITLE
Deleting a submission redirects to root page rather than dashboard

### ISSUE THREAD

**Issue by brannj** [exercism/exercism.io#2567]
When deleting a submission it redirects to the root page so that you must re-navigate to the dashboard to confirm submission deletion and continue browsing the dashboard.

**Comment by kytrinyx** [comment]
Yeah, that's no good, thanks for the heads up!

**Comment by kytrinyx** [comment]
Deploying the fix now. Thanks again!

**Comment by brannj** [comment]
Thanks!
