### ISSUE TITLE
Link to Rust laguage page leads to 404-ish error

### ISSUE THREAD

**Issue by IAmRasputin** [exercism/exercism.io#2570]
http://exercism.io/languages/rust leads to the "Sorry! That's our fault!" page.

**Comment by kytrinyx** [comment]
Thanks for the heads up, I'll take a look at it.

**Comment by kytrinyx** [comment]
Fixed in https://github.com/exercism/x-api/commit/47b6d24f155a498c8c29fa092d56211b529f59be -- Thanks!
