### ISSUE TITLE
triple quotes breaks markup

### ISSUE THREAD

**Issue by alex-bender** [exercism/exercism.io#2571]
As far as I understand triple quotes (module docstring) breaks markup of submitted code.
But may be deal in the triple grave accents (```)

[Here is submitted code with wrong markup.](http://exercism.io/submissions/9bd0c50e30f443038c4ac9bb450263b5)

**Comment by kytrinyx** [comment]
Thanks for reporting this! I am not sure if it's a problem in the underlying markup library we're using ([rouge](https://github.com/jneen/rouge)), or a problem on our end. We'll need to dig into it.

**Comment by Tonkpils** [comment]
Duplicate/related to #2380

**Comment by kytrinyx** [comment]
Ah, yepp. Good catch. Closing in favor of #2380
