### ISSUE TITLE
5-a-day should remove a submission after giving a thumbs up

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism.io#2572]
A submission is removed from 5-a-day after I nitpick on it, but if I think it is already good enough and give a :+1: it should also be removed from the list.

**Comment by kytrinyx** [comment]
I agree.

If we do this in the SQL, we will add a second left join. I'm not sure this is going to be tenable. We can do it and then if the performance is abysmal then we can rethink our approach to this feature.

**Comment by bmulvihill** [comment]
I like that we have to comment for it to count, even if the comment is simply mentioning something that you like about a submission!  Thumbs up are good, but conversation is better :phone:

**Comment by kytrinyx** [comment]
This is a great point. Thanks @bmulvihill. I am now perfectly undecided :)

**Comment by tejasbubane** [comment]
@bmulvihill Agree. But the important thing here is telling what is good about the submission rather than just saying `good job!` or `great submission`.

**Comment by RichardWigley** [comment]
I came here to add this issue! 

Pickers POV - I think this will motivate the pickers to clear their 5 - how many clear their 5 currently? I'm guessing very few. It is demotivating to visit something, 'like' it and have nothing change. Worse to see the same things you 'liked' yesterday still in your feedback list - that makes me want to not look at the list at all.

Picked POV - I don't get many comments and I am happy with ANY thumbs up I get. A pertinent comment is best but I would prefer a thumbs up over a manufactured generic statement 'great code'.

Statistics - you are collecting on the dashboard 'nits picked' and 'nits received' - how would you detect it was actually a nit or just a 'well done' comment?

Anyway, these are hunches  if in doubt A/B test? You have lots of users - let them decide ;-) 

Regardless of what direction you choose it should show you've interacted with a list item - there should be some visible change, to show you've visited a solution.

**Comment by jessejanderson** [comment]
What if there was a "Looks great! Show me another." button instead? Pressing the button gives them a like and a new item is added to your 5 (which you are taken to immediately).

**Comment by kytrinyx** [comment]
I don't want thumbs up to count as a five a day, but I do want thumbs up to remove it from the list so that you're shown something else. This isn't something that I want to A/B test--I simply don't think that a thumbs up is particularly interesting feedback. I personally have never cared about the thumbs up feature. If someone gives me thumbs up without having had a conversation with me, all I think is "really? there's nothing specific you can say about this?". I've considered removing the feature on a number of occasions, but at least it lets someone know that someone looked at their code, so it doesn't feel like they're shouting in the dark.

I like the idea of "looks great, show me another".

**Comment by kytrinyx** [comment]
@GustavoCaso Would you be interested in working on this one?

It's a ridiculously large SQL statement (I think `lib/exercism/user.rb:159`).

The fix, per the discussion here should be to exclude exercises that they've liked (there's a `likes` table). This might make the query so slow that we have to rethink our strategy, so it might be a bit tricky.

**Comment by GustavoCaso** [comment]
@kytrinyx SQL is not my strong suit but yes there is not better way of learning.

**Comment by kytrinyx** [comment]
I'm happy to help if you get stuck, and also don't feel bad about abandoning it if it turns out to be a rabbit hole.

**Comment by GustavoCaso** [comment]
No problem I want to improve my skills with SQL so I will try my best !!

**Comment by kytrinyx** [comment]
As always, let me know if you get stuck!

**Comment by bmulvihill** [comment]
@kytrinyx I was taking a look at this, @GustavoCaso do you need assistance?  I think I can tackle this query.  I also had a couple ideas regarding refactoring the 5 a Day feature. 

First what do you think of moving the 5 A Day SQL into a View, and then creating a migration and a Model on top of it?  This will allow us to leverage AR relations/methods, and remove some of the raw SQL from the Ruby code.

In addition what about naming the model something more along the lines of Daily, the relationship would look like:

```ruby
class User < ActiveRecord::Base
 has_many :dailies
end

class Daily < ActiveRecord::Base
  belongs_to :user
end
```

Just some ideas I got from looking at the code, let me know what you think!

**Comment by kytrinyx** [comment]
@bmulvihill I like the idea of moving it to a view. The name 'dailies' / 'daily' is better, I think.

**Comment by GustavoCaso** [comment]
@bmulvihill This will definitely will reduce the complexity in the query, I we could even do some complicated query on the `Daily` table with more confident. I like it.

**Comment by bmulvihill** [comment]
@kytrinyx @GustavoCaso Ok I'll take a look this week and see what I can do.

**Comment by bmulvihill** [comment]
@kytrinyx Can I get a bit of background information on the 5 a day feature?  What should the behavior be? Is it just 5 exercises the user hasn't commented/liked  and are not archived that are ordered by total comments?  I may have to rewrite some of the query to make it a true relation to the user.  I also want to make sure I write appropriate test ensuring correct behavior.

**Comment by kytrinyx** [comment]
What we're trying to do is encourage people to give feedback on five different pieces of code each day. We don't want to emphasise it (no badges, no achievements), just have a small thing that subtly encourages giving feedback.

> Is it just 5 exercises the user hasn't commented/liked and are not archived that are ordered by total comments?

Yes, that's exactly right. The number only decreases when they actually give a comment (not when they view or like something).

**Comment by bmulvihill** [comment]
Ok thanks, that makes sense.  One more question, is the ACL table the primary place to go to determine what exercises a user can view?

**Comment by kytrinyx** [comment]
Yepp, the ACL table is the source of truth for that.
