### ISSUE TITLE
Add possibility to remove problems.

### ISSUE THREAD

**Issue by alex-bender** [exercism/exercism.io#2573]
After `exercism fetch` (without specified language) we have a lot of problems in /home/user/exercism sub-folders. Also, there  are displayed at [dashboard](http://exercism.io/dashboard).
But I can not remove unwanted languages from list of pending problems, which I won't to solve.

It would be great to have that possibility.

**Comment by kytrinyx** [comment]
+100 This should be easy to fix by implementing some way to delete the `UserExercise` records (only if the iteration_count is zero, I think, as a protection against nuking exercises you've solved).

**Comment by frenata** [comment]
What if `exercism fetch` only pulled in exercises for language folders that already exist? This would require that to get started with a new language you'd have to first manually specify it `exercism fetch go` , but not afterwards. 

That way you only get exactly the language exercises that you want. A message to that effect when issuing the command with an empty exercism folder, and I'd guess that the workflow would be a little smoother, avoiding the issue of forgetting to specify a language and ending up with a bunch of subfolders for languages the user isn't interested in.

**Comment by kytrinyx** [comment]
Yeah, I really like this idea. I'm opening an issue for it in the CLI repository.

**Comment by mfrost** [comment]
It seems like the changes to the CLI are underway. Is there still a need for a way to clean up `UserExercise.where(iteration_count: 0)`? Are those records being created on fetch?

**Comment by kytrinyx** [comment]
Nope, we don't need to remove those. We actually need to keep them, since that's how we skip exercises. We're ignoring them in the correct place now though. I think this can be closed.
