### ISSUE TITLE
Noob workflow

### ISSUE THREAD

**Issue by mike-hewitson** [exercism/exercism.io#2574]
For noobs, its not very clear on how to get from submission to the first submitted exercise, which feels very odd under profile and took a while to find.

I'm also unclear as to how one can access other peoples solutions?

Thanks you for the great idea, and I hope it grows!

**Comment by kickinbahk** [comment]
thanks for the input @mikeyjcat I will let @kytrinyx address the finding your first submission, however when you `exercism submit` there is a url given in the terminal that will take you directly to the exercise. 

You are given access to others work as you complete the exercises. So after submitting the first exercise (and maybe after the next iteration), you will begin to see a number on the top of the dashboard appear for you to offer "nits" of other people's submissions. You can access them as well by clicking on the 'exercises' link. It will only show you exercises that you have submitted, I believe.

**Comment by kytrinyx** [comment]
@mikeyjcat You are absolutely right that it's unclear--and not only for noobs. I'm working with @jenndodd, @jtigger, @mixolidia and @sguermond on reworking the entire flow to help fix this, and I hope that over the next couple of months the experience will be improved a lot.

One of the problems we identified is that when you're new the "dashboard" gets coopted by the onboarding instructions (which themselves are less than optimal). I think that one low-hanging fruit we could tackle that isn't a huge change would be to make the onboarding instructions part of the normal dashboard, which has your submitted exercises front-and-center.

**Comment by mikeyjcat** [comment]
Thanks Katrina

Having progressed a bit further, all fell into place😄

Let me know if I can assist in any way, I think this is a great undertaking!

Regards
Mike

**Comment by kytrinyx** [comment]
Thank you! Submitting issues when you get stuck is an incredibly useful (and totally underrated) contribution, and it's much appreciated.

I think that once we get the wireframes done for the new onboarding flow, we'll be able to break down a bunch of tasks into things that are easy to tackle without having to dive into the entire project.

Meanwhile, if you're itching to tackle some low-hanging open source stuff, check out this issue along with the associated ones: https://github.com/exercism/todo/issues/13

If you get stuck, submit a PR anyway, and I'll help you get that PR accepted any way I can.

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/exercism.io/issues/2711

**Comment by kytrinyx** [comment]
We have done quite a lot to improve the documentation / onboarding since this was posted. We are also reconsidering the workflow from scratch as part of our design reboot. I'm going to close this, and we can reconsider when we have specific designs/layouts/workflows to suggest and get feedback on.
