### ISSUE TITLE
numbered toolbar feedback list contains submissions that already have my feedback

### ISSUE THREAD

**Issue by vicqstream** [exercism/exercism.io#2575]
Having reviewed 2 submissions and having 2 to give feedback on, the list containted the two that I had already given feedback to.
As opposed to the two that are pending my feedback.
Here's a screenshot in to Illustrate:
![incorrect feedback list](https://cloud.githubusercontent.com/assets/11613023/10339793/fc87f988-6d04-11e5-8c0b-d82966c0b180.png)

**Comment by kytrinyx** [comment]
Thanks for catching that!

**Comment by wobh** [comment]
Ditto. Also, mine are all the same exercise from the same track. That's fine I guess but it would be nice to stir things up.

**Comment by kytrinyx** [comment]
Yeah, I wonder what the best way to do that would be. Thinking on it!

**Comment by kytrinyx** [comment]
Deploying a fix now. I'd love to hear back from y'all how this is looking.

**Comment by vicqstream** [comment]
Fix works great!

Got through my 5 today!!!  \o/

**Comment by kytrinyx** [comment]
Yay!
