### ISSUE TITLE
List exercises on language page in the track order

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2577]
At the moment they're listed alphabetically.

The `config.json` in each track lists the problems in the correct order, and the x-api returns the problems per the order in config.json, so this should be a fairly straight-forward fix.

**Comment by davearonson** [comment]
I'll give this a whack, if nobody else is working on it....

**Comment by kytrinyx** [comment]
@davearonson That sounds great. I spent about an hour poking around in this area, and it's... pretty ugly. I've been contemplating doing some rewriting.

Here's the biggest thing that I found: The language page calls the "problems" endpoint, not the "tracks/LANGUAGE" endpoint to get the data. I think it will require making an additional call to the tracks endpoint for the language to actually get the config.

I've been contemplating doing some rewriting with respect to all the x-api stuff, since it's grown very accidentally. In other words: have at it. Also: good luck :) Please ask if you have questions.

**Comment by davearonson** [comment]
Okay.  First let me verify what I think you want: the problems presented in the order they are given to the user, for a given language.  Frex, for Ruby, starting with Hello World, then Hamming, then Gigasecond, etc.  Right?

Looks like the info from /tracks/#{language} has everything I'd need... and about 3.2 metric buttloads more.  I'll look into the API and see if there's a way to trim that down, but if you happen to recall it offhand, that would be great.

**Comment by davearonson** [comment]
Ohhh... not everything, it doesn't have the blurb, so I'd still have to get that from `/problems`, and match 'em up.

**Comment by davearonson** [comment]
I've got a solution at https://github.com/davearonson/exercism.io/tree/fix-problem-order and it passes all the tests (tho I haven't written one for it being in order)... but it bugs me that it's pulling down all that extra junk from /tracks/whatever-language, and it doesn't look to me like there's a way to trim it down.  If you want, I could put in a PR as it stands, but I'm tempted to also hack the API to be able to query /tracks/some-language/problems and have it return just them, still in track order.  Thoughts?

**Comment by kytrinyx** [comment]
> First let me verify what I think you want: the problems presented in the order they are given to the user, for a given language.

Yepp.


> I'm tempted to also hack the API to be able to query /tracks/some-language/problems and have it return just them, still in track order

That sounds excellent! Thankfully the API code is much easier to manage than the exercism.io code, and has much better test coverage.

**Comment by davearonson** [comment]
I've put in a PR on the API to add a `/tracks/:id/problems` route, including a test that verifies that they're in the same order as from `/tracks/:id`.  Assuming that that gets approved, I'll then change my site change to use that, which should be much cleaner.

**Comment by kytrinyx** [comment]
W00t, merged and deploying. Thanks so much, @davearonson!
