### ISSUE TITLE
javascript rna transcription test does not update on exercism fetch

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/exercism.io#2578]
The version of the test suite that I have locally did not match what is posted for the exercise.  When I ran ```fetch``` it did not update.

I deleted the test suite and ran ```fetch``` and the updated file downloaded successfully.

**Comment by kytrinyx** [comment]
Yes, that's the expected behavior. We don't want to overwrite files that people have locally, since they may have made changes to them.

**Comment by matthewmorgan** [comment]
OK thanks!
