### ISSUE TITLE
"next submission" should be the "next unread submission"

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2585]
Commenting on an exercise puts it back to the top of the exercises list, which causes the 'next submission' button to go back to the start. This is pretty annoying if you give a lot of feedback.

The SQL query for this is in `lib/exercism/inbox.rb:181`

**Comment by kytrinyx** [comment]
@GustavoCaso Here's another one where a SQL query is going to need to be tweaked. Interested?

**Comment by GustavoCaso** [comment]
@kytrinyx Sure

**Comment by mfrost** [comment]
@GustavoCaso would you like to pair up on solving this one? Shoot me a PM if you want to coordinate.

**Comment by GustavoCaso** [comment]
@mfrost Sorry for the late response I'm working on other issues if you want to take this, one please go ahead. Just for the purpose of learning can you mention my in the PR

**Comment by dogweather** [comment]
Hi, I'm interested in possibly helping out with this. I'd like to see the database schema. But it looks like the Rails source doesn't make use of db/schema.rb or activerecord models. Is there a way I can view the data model here in the repo without fully installing the dev environment?

**Comment by kytrinyx** [comment]
Yeah, this isn't a rails app, so none of the rails conventions hold.

I do have a schema file, though. Beware that this schema is the result of 2 years of experiments.

https://github.com/exercism/seeds/blob/master/db/schema.sql

**Comment by dogweather** [comment]
I'm glad to see it's checked in somewhere! So it looks like `submission_viewers` is the relevant table. ?

**Comment by kytrinyx** [comment]
Nope, sorry! I have a list of migrations I have to run to clean up tables and columns that are no longer in use--but I have to do it on a day when I can spend all day doing it carefully and testing at every step.

The table in question is called `views`.

**Comment by kytrinyx** [comment]
I've removed this feature for now.
