### ISSUE TITLE
Recognize "Looks great" as a "Submit Comment"

### ISSUE THREAD

**Issue by vicqstream** [exercism/exercism.io#2587]
Maybe it is by design that you should put some text to a comment.

However, sometimes when looking at a submission, all you want to do is give it a thumbs up, :+1:, "Looks great" because there's nothing more you need to say it's just good. :smile:

**Comment by kytrinyx** [comment]
You mean when counting how many comments you've given in a day?

I don't think these ideas are equivalent. The effort involved in giving a thumbs up is very low. Even when you like a submission, there's often something to say about what you like about it, unless you've had a conversation with the author through several submissions.

I'm going to leave this open for a little while to give others a chance to add their two cents.

**Comment by vicqstream** [comment]
I did think that this was by design, i.e. giving more value to a written comment than the thumbs up, Thanks for the clarification.

**Comment by jessejanderson** [comment]
It feels kind of weird to leave a "nitpick" when I look at a submission and the only thing I think is "wow, this is way better than what I submitted."

**Comment by kytrinyx** [comment]
Yeah, we need to remove the word nitpick from the site, it's not helping.

The comment _wow, this is way better than what I submitted_ would be a fantastic contribution to the conversation. You might say something specific about what you learned. I think that the conversations should be as much about what you like as about what could be improved.

**Comment by jessejanderson** [comment]
I like "nitpick" because when it is a criticism, by it's nature the criticism _is_ a nitpick since the provided code passed all the tests and should never be technically wrong.

But yah, it feels weird that I'm encouraged to leave a nitpick when I see code where I find nothing wrong with it.

**Comment by kytrinyx** [comment]
Right, nitpick has a certain charm, but we're actually looking for a back-and-forth conversation, not one-way feedback/suggestions.

**Comment by wobh** [comment]
Maybe comments could be tagged with one or more labels about the "genre" (if you will) of the comment. This could kill two birds with one stone, as both "nitpick" and "looks great!" could become such tags. Others might be "serious question" or "socratic inquiry", "explanation", "suggestion", "critique" or "defense".

I can think of some problems with this already, but I'll put it out there.

**Comment by kytrinyx** [comment]
One of the interesting things about this suggestion is that it gives people a hint about what kind of comments we think are useful.

**Comment by alebaffa** [comment]
I was about to open the same issue ("Looks great" considered as a submitted comment), but after having read the discussion here I totally agree with you @kytrinyx : it would be too low effort and we would lose maybe the greatest benefit of exercism.io, which is the review from your peers (that I saw being always really interesting and constructive).
Anyway, I also tried to submit an empty comment and apparently it counted as submitted (it has reduced my reviews-to-give count).

**Comment by kytrinyx** [comment]
Oh, neat workaround :) I think I'll file that as a separate bug.

Thanks for adding your thoughts to the discussion, @alebaffa.

**Comment by kytrinyx** [comment]
I fixed the empty comment bug in 299bb7fa054c0ed27f9cb25f3c5791463e9dff41

**Comment by alebaffa** [comment]
cool! Happy to help :+1:

**Comment by kytrinyx** [comment]
I've been reviewing issues, and this issue overlaps with #2572. The conclusion there is to make sure that you don't see any solutions where you've given a thumbs up in the list of 5-a-day. I'm going to close this as a duplicate.
