### ISSUE TITLE
Allow comments/messages in exercism submit

### ISSUE THREAD

**Issue by vicqstream** [exercism/exercism.io#2588]
It would be nice if iterative submissions had an optional comment/message similar to a git commit message that gives a synopsis of what the iteration accomplished. 

This could also be displayed in the review page for others to give better comments.

**Comment by kytrinyx** [comment]
/cc @exercism/cli-committers 

I think that we could do this with a flag that posts a comment on behalf of the user (as a regular comment, not as a new entity in the system).

**Comment by Tonkpils** [comment]
Yeah, should be simple enough as long as we have an open API to submit this comment. I'll create an issue on the CLI repo

**Comment by kytrinyx** [comment]
Cool, I'll verify that we have an API endpoint. I'm pretty sure we do, since rikki- submits comments.

**Comment by kytrinyx** [comment]
We currently do not have an API endpoint that allows users other than rikki- to comment.

Let's fix this by accepting a "comment" key in the submission in `post '/user/assignments'`.
