### ISSUE TITLE
Regular Expressions

### ISSUE THREAD

**Issue by blainesch** [exercism/exercism.io#2591]
I was curious about adding a workflow for regular expressions. A few of the problems -could- be solved with regex, but it can just as easily be avoided.

The issue is this is not language specific, and so far this is oriented around language specific challenges.

If this is something the community wants, how would we implement it? I'd be happy to take a swing at implementing giving I know what direction I should be taking.

Maybe this isn't the best project to put it in?

**Comment by kytrinyx** [comment]
I'm not sure. The best project for regular expressions so far is https://regexcrossword.com/ -- I would tend to suggest that people just go there, rather than adding regex problems here, but I would be curious to hear what other people think.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this one, as I still think that regexcrossword.com is a better match for this. Thanks so much for the suggestion!
