### ISSUE TITLE
Cannot delete a team I created

### ISSUE THREAD

**Issue by mrageh** [exercism/exercism.io#2592]
Hi @kytrinyx 

I created a team more then a year and a half ago. The other day I decided to remove the two people on the team with me and then I tried to delete the team. I went to my [teams page](http://exercism.io/teams/thoughtbot/manage) and clicked on the delete button which redirected me [to](http://exercism.io/teams/thoughtbot?). After looking at the [code](https://github.com/exercism/exercism.io/blob/master/lib/app/routes/teams.rb), deleting a team looks like it should work but in my case I think it does'nt. 

Is this a potential bug or am I doing something wrong?

If you think it's a bug I'll try to reproduce it on my local machine and hopefully I'll send a patch in.

**Comment by kytrinyx** [comment]
Yeah, probably a bug, thanks for raising the issue.

I'll take a look at it today (I have a couple of other bugs I need to look at). If you find repro steps before I do, that's always a good thing.

**Comment by kytrinyx** [comment]
FYI @sguermond (I should have caught this in the PR, sorry about that. This is definitely worth knowing about!)
