### ISSUE TITLE
Debugging C++ CMake Project in Xcode

### ISSUE THREAD

**Issue by justinoliver51** [exercism/exercism.io#2593]
Hello,

I'm having trouble debugging the first project, bob, in Xcode.  I've followed the steps, and I've successfully created the C++ Xcode project using CMake.  From there, I've begun developing in Xcode, and I can run the project.  However, I am not able to debug it (stepping from line to line).  What are the steps to do this?  I can't seem to find them in the documentation or on Google.  

Thanks,
Justin

**Comment by LegalizeAdulthood** [comment]
You can debug the unit test project just like you debug any other project in Xcode.  There is nothing special about these projects in this regard.

**Comment by justinoliver51** [comment]
Richard,

Thanks for your reply. Unfortunately, this isn't the case - there is no debug option. It simply only allows you to run. If you like, I can attach pictures to demonstrate.

Do you have documentation on how to debug cmake projects with GDB? 

Thanks,
Justin

**Comment by kytrinyx** [comment]
@marianaIAm, do you happen to know of any resources with respect to debugging in XCode?

**Comment by LegalizeAdulthood** [comment]
It looks like the debug option in the IDE isn't enabled until you set a breakpoint.

**Comment by Insti** [comment]
This has hopefully been resolved by now. If not, there's an XCode support website which could might be more helpful: https://developer.apple.com/support/xcode/
