### ISSUE TITLE
Show an icon in the ECMAScript track

### ISSUE THREAD

**Issue by rchavarria** [exercism/exercism.io#2596]
There is an icon for the ECMAScript track, but it's not shown (see Pull Request #2595)

**Comment by rchavarria** [comment]
It seems there is a CSS class missing somewhere. Searching for `javascript-icon` class:

``` bash
~/repositories/exercism.io $ grep -rl javascript-icon
lib/app/public/css/application.css
lib/app/public/sass/base/components/main.scss
~/repositories/exercism.io $ 
```

While searching for `ecmascript-icon` (the CSS class that will provide a background image):

``` bash
~/repositories/exercism.io $ grep -rl ecmascript-icon
~/repositories/exercism.io $ 
```

There are two occurrences for JavaScript and none for ECMAScript. `application.css` is probably generated from SCSS files, including `main.scss`. So, `main.scss` seems the right file to change.

Looking into `main.scss` there are other classes that show background images for other languages: Elixir, Go, Python,...

**Comment by kytrinyx** [comment]
Aha! Nice find, thanks for digging into that.
