### ISSUE TITLE
Notification history

### ISSUE THREAD

**Issue by jessejanderson** [exercism/exercism.io#2598]
It would be great if when I went to my notifications page, all of my previous notifications were still listed. Sometimes I'll see a notification and it will mark as read, but I actually want to come back to it later and there doesn't appear to be an easy way to do so.

**Comment by kytrinyx** [comment]
Notifications are fleeting on exercism (I modelled them off of GitHub's notifications. You click it, and they're gone. However, there's a list of "recently viewed pages" that I think caps at 200 or something, which should give you the things that you were notified recently. It's in the dropdown under your username.

**Comment by wobh** [comment]
I recently fumbled fingered "mark all as read" on my phone. Fortunately the back button restored the page.

**Comment by ronnieoverby** [comment]
+1 When I view the notifications list and come back, all notifications are gone, whether I checked them all or not.

**Comment by kytrinyx** [comment]
@ronnieoverby just looking at the notification list marks them as read and disappears them? (If so, ouch! That's definitely a bug.)

**Comment by abhishekbose87** [comment]
@ronnieoverby I could not recreate this bug. I clicked on the notifications bell, closed the window and opened the url again and they were still there. Are you doing something different ?

**Comment by mhelmetag** [comment]
@ronnieoverby , I second @abhishekbose87 's comment about not being able to recreate this and needing more clarification for steps to reproduce.

**Comment by kytrinyx** [comment]
I'm going to close this for now. If someone can reproduce, please add a comment and I'll reopen it. Thanks!
