### ISSUE TITLE
Unable to view past submissions, or add new submission for c# Tournament exercise.

### ISSUE THREAD

**Issue by cds-amal** [exercism/exercism.io#2600]
Hi, 

I'm unable to pull up past submission for the tournament csharp exercise.

I submitted from cli and received this [link](http://exercism.io/submissions/3bd9163b6a5e45f295154a2e4008784e)
The dashboard has this [other link](http://exercism.io/exercises/c9f01316f69d40219920377fa28b9a1e) that doesn't work either. Both urls prompt for submitting an error.

**Comment by kytrinyx** [comment]
Thanks for the heads up; definitely a bug--I'll look into it.

**Comment by cds-amal** [comment]
@kytrinyx , I love these challenges and am a fan of the site. Thank you for making this happen.

FYI, in case you need more examples
[clock](http://exercism.io/exercises/427b22c10dec4290933617d5ca67b3b3), and [twelve days](http://exercism.io/exercises/a158e2e608d04adca645a6a90c589e1f) are also MIA.

**Comment by kytrinyx** [comment]
Update on this one: It looks like there's something problematic going on when we try to parse the code to display it with highlighting on the site. I'm working on narrowing this down locally so I can troubleshoot more easily. I'll let you know what I find.

**Comment by kytrinyx** [comment]
I found it. It turns out this was a bug in the rouge library that was fixed in their latest patch release. I've updated the dependency and will redeploy shortly.
