### ISSUE TITLE
The 'copy' button not working?

### ISSUE THREAD

**Issue by jessejanderson** [exercism/exercism.io#2602]
![image](https://cloud.githubusercontent.com/assets/8367129/10807476/5e8ed0b8-7d9d-11e5-8e81-e984eee9cd66.png)

I'm assuming this button is to copy the code, but it does nothing for me - doesn't give me a pointer cursor and does nothing when I click on it.

Also looks like it's using flash which seems strange on a website that doesn't have any other flash. There are other friendlier ways to enable this using javascript (which is native to _every_ browser) instead of flash.

**Comment by kytrinyx** [comment]
I thought it used javascript, but I haven't done much on the frontend so I don't actually know. I agree that it should be javascript, and that it should change the pointer.

Marking this as a bug.

**Comment by GustavoCaso** [comment]
@kytrinyx 
Hi I'm for a first issue to start contributing to this great project.
Is someone working on this one ?

**Comment by jessejanderson** [comment]
I just started working on a solution yesterday.

**Comment by GustavoCaso** [comment]
@jessejanderson Ok no problem. 
Do you know any issue I can start with ??

**Comment by kytrinyx** [comment]
@GustavoCaso I think the following issues are good starters:

https://github.com/exercism/todo/issues/7
https://github.com/exercism/exercism.io/issues/2418
https://github.com/exercism/exercism.io/issues/2306

**Comment by GustavoCaso** [comment]
@kytrinyx Thanks I will look up them and try to contibute !!

**Comment by krishandley** [comment]
Related to #2419 There is a non flash alternative if you are interested http://clipboardjs.com, just wondered if anyone was working on this? If not then I'll open a PR later.

**Comment by kytrinyx** [comment]
I don't think anyone is working on this.

**Comment by kytrinyx** [comment]
Yepp, this is the same as #2419 -- closing as duplicate.

**Comment by kytrinyx** [comment]
Actually, they're not exactly the same.

**Comment by jessejanderson** [comment]
Sorry - I had planned to work on this and got distracted, clipbaord.js was actually the solution I was going to use. =P

Feel free to open a PR.
