### ISSUE TITLE
Ditch the `demo` feature.

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2604]
I think that the demo causes more pain than it's worth. It downloads ALL the languages. Back when that was a list of exactly one, it was great. Now that it's over 20... not so good.

I'd like to remove it.

Instead, let's show people the command to download the first exercise in a track on the language-specific page (`exercism fetch TRACK_ID PROBLEM_SLUG`).

Thoughts, @jtigger @mixolidia @sguermond?

**Comment by sguermond** [comment]
That's a great idea! It shows how to work the basics for exercism, which is what one expects from a demo. 

I think the problem slug should be optional (or the demo should make it clear that it's optional) since a new user wouldn't know what the slugs are for specific problems. 

On a related note, maybe each problem's readme page and the language page listing all problems should have slugs listed so you can easily go find a specific problem? Since the problems aren't yet organized in a sequence that makes sense educationally, it lets users pick and choose what they want to work on if, for example, they are working with someone else on a problem but don't want to go through the whole sequence.

**Comment by kytrinyx** [comment]
I was thinking that we can show the actual command for fetching the first available problem, since we know the slugs:

```
exercism fetch ruby hello-world
```

This way they don't have to be logged in to fetch (if you don't specify the problem slug, then we have to know who you are in order to give you the next available problem).

> On a related note, maybe each problem's readme page and the language page listing all problems should have slugs listed so you can easily go find a specific problem

Yeah, definitely! Actually, this makes me think we should put the list of available languages on the README page, and list to all the available test suites, and show the command to download the problem.

**Comment by karlo57** [comment]
@kytrinyx Hi, I'd like to help and work on this. I've started using the site since yesterday and I'm definitely enjoying using it.

**Comment by kytrinyx** [comment]
@karlo57 Thank you, that's much appreciated.

The first part to this, I think, is to add the explicit exercism command to fetch the first exercise on the language pages.

These are located in:

- lib/app/routes/languages.rb
- lib/app/views/languages/languages.erb

Let me know if you have any trouble getting oriented, and of course if you have any other ideas about where to start on this, go for it!

**Comment by karlo57** [comment]
@kytrinyx I just submitted my PR. Please comment on how I could improve it. I also have a few questions: 
- Does this issue mean that we ditch the whole onboarding process? Or just change the instructions shown to fetch exercises in the first step of onboarding?
- What do you think about hiding the `Available Exercises` section when the user hasn't fetched the first exercise? And then should we just hide the `Fetch your first exercise` section when the user has fetched any first exercise, regardless of language?

**Comment by kytrinyx** [comment]
We're going to rework the entire onboarding process, but we won't remove it.

Yeah, we should absolutely hide the "available exercises" section when the user hasn't fetched the first exercise, and also hide the "fetch your first exercise" section when the user has fetched an exercise.

**Comment by kytrinyx** [comment]
I'm not sure what we would have to do in order to remove the demo from the site. I think it might just be to remove the section on the homepage that mentions the demo.

@GustavoCaso @karloxyz would either of you be interested in taking a look at this?

**Comment by GustavoCaso** [comment]
@kytrinyx Sure looks simple

**Comment by kytrinyx** [comment]
Yeah, it should be as simple as that. We may have referenced the demo elsewhere, but we'll find it eventually.

**Comment by GustavoCaso** [comment]
Maybe removing from CLI ?

**Comment by kytrinyx** [comment]
Yeah, we'll remove it once it's off the site.

**Comment by GustavoCaso** [comment]
Cool

**Comment by karloxyz** [comment]
@kytrinyx Sure, I'll work on this as soon as I get home.

**Comment by kytrinyx** [comment]
@karloxyz @GustavoCaso don't both of you work on it :)

**Comment by karloxyz** [comment]
@GustavoCaso Are you working on this? If you are, you can take this one since I haven't started yet. I'll work on this tomorrow if you haven't.

**Comment by GustavoCaso** [comment]
@karlo I have started working on it. I haven't got the time to do the pull
request is been a crazy week. I will create it tomorrow or today depending
on the free time .

**Comment by karloxyz** [comment]
@GustavoCaso Alright, take this one then :)

**Comment by kytrinyx** [comment]
Sweet. I'll remove the demo command from the CLI.
