### ISSUE TITLE
Implement an in-browser workflow for the JavaScript track

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2605]
Out of all of the tracks that we have, I think that JavaScript would be the perfect candidate to try out an in-browser editor + test runner. This would lower the barrier to entry for new programmers.

We could do this as a stand-alone angular (or something) site that talks to the API and run it on javascript.exercism.io. Making it stand-alone would make it easier for people to contribute, and it would also make it possible to think about other in-browser options later.

I'm marking this as future roadmap because I can't put any time into thinking about it until we've finished the current UX work on the onboarding process, but if someone else wants to grab this, it could be a really interesting project.

/cc @exercism/javascript @jtigger

**Comment by rchavarria** [comment]
Some examples come to my mind, but I don't know if they match what you have in mind:

- [Khan Academy on Computer programming](https://www.khanacademy.org/computing/computer-programming)
- [Codecademy on JavaScript](https://www.codecademy.com/learn/javascript)
- [es6katas.org](http://es6katas.org/): probably this will interest you. Users are supposed to modify some tests in order to get them pass.

**Comment by kytrinyx** [comment]
Nice! Yeah, it feels like this should be quite achievable... I just don't have the resources to think about it yet. But if someone else would like to tackle it, I think it would be really cool, fun, and helpful.

**Comment by GustavoCaso** [comment]
@kytrinyx I would really like to help on this one. It really looks like an interesting project.

**Comment by kytrinyx** [comment]
I'd love to see this happen. If you have someone you want to collaborate with on it, that would be awesome. I'm available to do reviews and give feedback on suggestions/ideas, but I don't have the bandwidth to actually help out with implementation on it.

**Comment by GustavoCaso** [comment]
@kytrinyx I would like to know what are your opinions, on how to achieve this feature. I was thinking more into something like:
- http://www.codewars.com
Maybe you like the idea of having some endpoints for dealing with the test and provide the user with valuable information after the submitted the code.

Maybe some endpoints could be:
- Attempt solution
- Finalize Solution

**Comment by kytrinyx** [comment]
Since javascript runs in the browser, I don't think we need endpoints, other than 'submit' (which we already have an endpoint for).

**Comment by GustavoCaso** [comment]
Yeah I agree with you about JS running in the browser, but maybe in the future there would be other languages, and the implementation may be different. What do you think ?? Or are we treating this as a little experiment ? 

So it could be some sort of JsFiddle or JSBin, two windows, one for writing one for displaying the evaluated code.

**Comment by kytrinyx** [comment]
We're treating this as an experiment. I don't want to think about how to extend it, only see if we can come up with a good user experience for JavaScript.

**Comment by bmulvihill** [comment]
A good starting point might be something like the Ace editor
https://ace.c9.io

**Comment by GustavoCaso** [comment]
It looks promising, to be honest, it could take of a lot of hard work, and focus on others parts

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/exercism.io/issues/2711

**Comment by kytrinyx** [comment]
We're going to be considering an in-browser workflow option as part of the reboot / redesign. I'm going to go ahead and close this, since I don't think it makes sense to try to write this experiment in the old prototype.
