### ISSUE TITLE
Normalizing the CLI-API interface

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2607]
I'd like to start working towards locking down a solid definition of how the CLI talks to the API.

Here are the things that we currently have decided:

- get rid of the demo https://github.com/exercism/exercism.io/issues/2604
- adjust fetch so it always fetches a specific track: https://github.com/exercism/cli/issues/226

I also think that it would clean things up to make `restore` a track-level command (can't restore everything, you have to choose which track you're restoring).

That will give us the following commands:

**specific to user**

- status of track
- fetch (next on track, or specific exercise)
- submit
- restore (all solutions in the track, with associated exercise files)
- skip exercise
- open the most recent iteration for an exercise

**generic**

- list available tracks
- list available exercises in a track
- fetch a specific exercise on a track (anonymously)

For the endpoints that are user-specific, I'm thinking of namespacing them with something like `/me` (open to suggestions, but it seems useful to distinguish between generic/anonymous stuff, and things that are specific to the user).

- *status*: `GET /me/tracks/:id/status`
- *fetch*: `GET /me/tracks/:id/exercises`, `GET /me/tracks/:id/exercises/:slug`
- *restore*: `GET `/me/tracks/:id/solutions`
- *skip*: `POST /me/tracks/:id/exercises/:slug/skip`
- *submit*: `POST /me/tracks/:id/exercises/:slug`
- *open*: `GET /me/tracks/:id/exercises/:slug/url`

For the generic endpoints, I'm struggling. Consider the following:

- *list tracks*: `GET /tracks`
- *list exercises*: `GET /tracks/:id/exercises`
- *fetch exercise*: `GET /tracks/:id/exercises/:slug`

Does the resource `/tracks/:id/exercises` represent full on exercises (with all the files) or just the metadata about them?

It seems like perhaps we should have two different types of resource, one which is exercise metadata, and one which is exercise metadata+actual files.

If we can clarify all of this we could

a) implement just enough of the new API to do all of this. The new API would make calls to x-api, and x-api would not know anything about users or persisted data)
b) release a version 3.0 of the client that doesn't include any deprecated behavior.

Thoughts?

/cc @exercism/cli-committers @canweriotnow

**Comment by kytrinyx** [comment]
Perhaps instead of `/me/tracks` we could have a different name for _a track that someone is working through_.

We're working on clearing up terminology, discussion here: https://github.com/exercism/exercism.io/issues/2532

In the CLI, we're making a distinction between "language", which is the name of a programming language, like 'Objective-C' or 'C++', and "track" which is a collection of exercises in a language. A track has an ID which is a normalized, url-safe version of the language name, e.g. `objective-c` or `cpp`.

**Comment by Tonkpils** [comment]
What would be the difference between the `fetch exercise` anonymous vs user oriented?

I'm not too fond of how the `me` looks in the path. It feels like there's a disconnect for the sake of namespace but I'm not opposed to it. With that said, would there be any clashes with not namespacing the routes?

> Does the resource /tracks/:id/exercises represent full on exercises (with all the files) or just the metadata about them?

> It seems like perhaps we should have two different types of resource, one which is exercise metadata, and one which is exercise metadata+actual files.

One approach I liked was the one GitHub uses for their API. They enforce specifying `Content-Type` on their API and given a `Content-Type` of `application/octect-stream` they will stream the file itself.

**Comment by kytrinyx** [comment]
`fetch exercise` for a user would track that they fetched it. Not a big deal, and perhaps we can let the same endpoint do it, but I fear the rabbit hole of the one endpoint knowing about auth and not auth at the same time.

> I'm not too fond of how the me looks in the path.

I actually don't like the '/me' either, but I couldn't think of anything else.

> would there be any clashes with not namespacing the routes?

Yeah, `/tracks/:id/exercises` ... either get the list of available exercises, or fetch the user's next exercise in that track.

> given a Content-Type of application/octect-stream they will stream the file itself.

That's pretty elegant.

> Let's also go ahead and re-visit the milestones we have on the CLI repo so we can track our progress and a tentative release schedule.

Good idea.

> We could also start a branch for 3.0 to do some initial work without having to merge directly to master

Yeah, that's probably a good idea.

**Comment by devonestes** [comment]
I agree with @Tonkpils - `/me` seems like a kind of confusing namespace. Since all of those routes need the user's API key in the query string anyway, would it make sense to have those resources belong to a user in the URL? You could do something like the following:

* _status_: `GET /users/:api_key/tracks/:id/status`
* _fetch_: `GET /users/:api_key/tracks/:id/exercises, GET /users/:api_key/tracks/:id/exercises/:slug`
* _restore_: `GET /users/:api_key/tracks/:id/solutions`
* _skip_: `POST /users/:api_key/tracks/:id/exercises/:slug/skip`
* _submit_: `POST /users/:api_key/tracks/:id/exercises/:slug`
* _open_: `GET /users/:api_key/tracks/:id/exercises/:slug/url`

That would clearly show that those resources belong to a user on both the client and server side of the API and would hopefully be clearer to contributors to both repos.

**Comment by kytrinyx** [comment]
Namespacing it with `/users/:something` does feel like the right direction.

> Since all of those routes need the user's API key in the query string anyway

Hm. I'm not sure I want to have the API key as part of the url pattern. We're going to want to change how the auth piece works (the current one is not secure, so we'll have to add some hashing based on a secret or on other computable data, or some other strategy). If we make this part of the url pattern it's going to be harder to fix it when the time comes.

So I'm not sure what `:something` should be.

**Comment by devonestes** [comment]
The most common implementation of this pattern that I've seen in this case is to use the primary key of the table, which would be `/users/:id`in this case. However, `/users/:username` could also work since Github requires unique usernames.

**Comment by Tonkpils** [comment]
> The most common implementation of this pattern that I've seen in this case is to use the primary key of the table, which would be `/users/:id` this case. However, /users/:username could also work since Github requires unique usernames.

I like the idea of using username, we could even ditch the `/users` portion. We'd end up with something like https://exercism.io/Tonkpils/tracks/:id/status. Though I'm not sure what the implications/business rules would be around username then. If usernames can change then we'd be in trouble as we'd need a way to have the username available in the CLI, possibly config or something. If they can't, then that wouldn't be an issue.

**Comment by kytrinyx** [comment]
Usernames can already change, and we've had bugs because of it. I don't want to rely on that.

I know that the `:id` is the common pattern, but we don't need it, and I don't see a reason to store that in the CLI configuration.

**Comment by lcowell** [comment]
I'd push for eliminating the user/me namespace altogether. The only clash in doing this is between fetching the next exercise and listing all exercises for a given track.

For fetching all exercises this feels very natural, so I'd leave it alone:
GET /tracks/:id/exercises

For fetching the next exercise, this doesn't seem as intuitive. Nothing about this URL says I'm grabbing one exercise and not a collection of them.
GET /tracks/:id/exercises

I'm thinking we change it to the following as it communicates more about what it's doing:
GET /tracks/:id/exercises/next

**Comment by kytrinyx** [comment]
`GET /tracks/:id/exercises/next` is exactly what we want.

And I realized that we can make the anonymous/logged in thing really simple, so we don't need to worry about that.

I'll probably start prototyping a new API and see where it gets us.

**Comment by kytrinyx** [comment]
I've taken a bit more time to think through this.

I think that it makes a lot of sense to support two different content types, though not really for all the endpoints. It's still a bit weird that some endpoints are authenticated and some are not, but I think it's okay.

The octet-stream responses would be files that are zipped up as a single archive, including a `.metadata.json` or something file which would tell you about the solution (username, track, exercise, etc).

**Content-Type: application/json**

- `GET /tracks` - metadata about all the tracks, including a list of the exercise slugs in each track.
- `GET /tracks/:id` - one of the above
- `GET /tracks/:id/exercises` - the list of exercises in a track, including metadata about the exercises (but not the files themselves)
- `GET /tracks/:id/exercises/:slug` - one of the above
- `GET /tracks/:id/exercises/:slug/solutions/mine` - metadata about your solution, which we can use for the `open` command
- `GET /tracks/:id/status` - your current status on that track
- `POST /tracks/:id/exercises/:slug/skip` - skip this exercise on this track

**Content-Type: application/octet-stream**

- `GET /solutions/:uuid` - download a solution by the key used in the url
- `POST /tracks/:id/exercises/:slug/solutions` - submit a solution
- `GET /tracks/:id/exercises` - fetch the next exercise on all started tracks
- `GET /tracks/:id/exercises/next` - fetch the next exercise on the track
- `GET /tracks/:id/exercises/:slug` - fetch the given exercise on the track

Have I missed anything obvious? Does this all look reasonable?

**Comment by Tonkpils** [comment]
> POST /tracks/:id/exercises/:slug/solutions - submit a solution

Not sure how it would behave on this end point. Don't we send some JSON along with the payload? If not then nvm. 

Other than that it looks reasonable. :+1: I think authenticated vs not will become easier to reason about and solve if necessary once we have a prototype of the API.

**Comment by lcowell** [comment]
Looks good.   :+1:

**Comment by kytrinyx** [comment]
I would think that for the submit endpoint we would write a json file and then zip everything up (reverse of the fetch, really). I don't recall whether we send along any json right now.

**Comment by kytrinyx** [comment]
@Tonkpils said:

> Let's also go ahead and re-visit the milestones we have on the CLI repo so we can track our progress and a tentative release schedule. We could also start a branch for 3.0 to do some initial work without having to merge directly to master.

Let's do this. I'm a bit fried after two weeks of travel, but if one of you has an idea of where to begin, I'm happy to jump in and contribute.

**Comment by kytrinyx** [comment]
See also https://github.com/exercism/exercism.io/issues/2607

**Comment by kytrinyx** [comment]
Closing in favor of https://github.com/exercism/discussions/issues/35
