### ISSUE TITLE
Test suites for exercises on JavaScript and ECMAScript tracks are not shown

### ISSUE THREAD

**Issue by rchavarria** [exercism/exercism.io#2610]
While looking at a submitted iteration code, there are two buttons on the right: "Readme" and "Test Suite". "Readme" shows the README file for that particular exercise. "Test Suite" should show the tests used to guide the user to solve the exercise.

But tests are not shown.

![test-suite-not-shown](https://cloud.githubusercontent.com/assets/612688/11017673/c458bb96-85a6-11e5-8bb1-f772cf95fadf.png)

**Comment by rchavarria** [comment]
Recently, JavaScript and ECMAScript test files were renamed from `*_test.spec.js` to `*.spec.js`. So, new file names might not match a previous pattern looking for test files.

I'm still not able to run exercism.io locally and I'm not a ruby programmer, but this is what I've found:

"Test Suit" content seems to be generated from `lib/app/views/exercises/test_suite.erb`. It iterates over a variable called `testfiles`. 

These tests files could be retrieved from a method on `Assignment` class, defined at `lib/app/presenters/assignment.rb`.

In that file, there is a class, or an object, that defines a method called `testfile?`, used to filter a collection of files. It seems to return `true` if a file name match some patterns:

``` ruby
def testfile?
  filename =~ /test/i ||
    filename =~ /\.t$/ ||
    filename =~ /ut_.*#\.plsql\Z/
end
```

It tries to match `test`, what should match old file names for JavaScript/ECMAScript tests `*_test.spec.js`. But it doesn't match `*.spec.js`.

Would it be too naive to add a new line?:

``` ruby
def testfile?
  filename =~ /test/i ||
    filename =~ /spec/i ||
    filename =~ /\.t$/ ||
    filename =~ /ut_.*#\.plsql\Z/
end
```

**Comment by kytrinyx** [comment]
Yeah, that's the quickest fix. Eventually we should fill in the `test_pattern` key in the config.json for the track so we don't depend on this hard-coded thing.

**Comment by kytrinyx** [comment]
OK, "fixed" for certain values of fixed. :)

**Comment by rchavarria** [comment]
Great!! The `test_pattern` key is just an idea? I don't find any example on other track languages.

**Comment by kytrinyx** [comment]
Oh, uh, no it's implemented as part of the template. I think perl uses it. Maybe.

**Comment by simondiep** [comment]
The original issue of test suite links not working seems to be fixed for ECMAScript, but not JavaScript.

For example: http://exercism.io/exercises/javascript/leap

**Comment by kytrinyx** [comment]
Yeah, if I go to exercism.io > Languages > JavaScript > Available Exercises > Leap and try to go to the test suite, it breaks. Reopening this.

**Comment by mhelmetag** [comment]
From what I can tell... it looks like this works now for JavaScript. Close?

**Comment by rchavarria** [comment]
I think so. I was waiting for #154 to be deployed, and I think I forgot about this issue, sorry.

**Comment by kytrinyx** [comment]
@rchavarria @mhelmetag I'm *always* forgetting to loop back and close issues. Thanks to both of you for helping figure out what can be closed <3
