### ISSUE TITLE
General solution discussion area

### ISSUE THREAD

**Issue by tleen** [exercism/exercism.io#2615]
A future feature request, it may be a nice-to-have general discussion area about each problem set. This way if there is a place outside of specific issues per-submission to talk more about general tradeoffs and approaches taken buy the group of submitters as a whole.

I was looking a the [Go Clock](http://exercism.io/tracks/go/exercises/clock) problem in this case. I think the discussion of the internal representation of the clock data is a good discussion to have, but may be unwieldy if it keeps happening over and over in each problem result. It would get really repetitive. I thought it may be good to be able to say in that case, after a little discussion that the analysis of that specific point is discussed in more depth over here (in a problem set's general discussion area).

Perhaps require x number of comments on a problem in the individual solutions before you can contribute to the general discussion as an incentive to give feedback on problems.

**Comment by kytrinyx** [comment]
Thanks for the suggestion. This has come up a few times, and I think there are a few trade-offs that we need to consider before implementing something like this. I'm particularly worried that people will discuss in the general area in place of discussing in solutions. That said, this could end up being a non-issue.

**Comment by massich** [comment]
Maybe a similar feature but with less coding would be to fetch other people's answers. Then as user I could run some quick commands `cat`, `grep`, `unique`, or anything more fancy to data-mine the solutions. Then the discussions can be done at a more local level.

here's an [example](http://exercism.io/submissions/1c86154c2a7c4c609903579023b92432)

It would also be nice to be able to share (or export) conversations.

**Comment by kytrinyx** [comment]
@massich This is a really interesting approach. Did you see this discussion by any chance? https://github.com/exercism/discussions/issues/65 There are related ideas here that I think would be useful to discuss.

**Comment by kytrinyx** [comment]
I'm going to close this, since we're trying to focus on the core Exercism features and user experience, and this is currently a bit too far away from that core experience. Once we get the basics implemented properly, this might be worth thinking about.
