### ISSUE TITLE
Rewrite pieces of the codebase to make it easier to contribute

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2619]
For the past two years, Exercism has been a collection of experiments. Now the ideas are coalescing into something coherent.

The new code will be implemented within the same repository, and it will replace bits and pieces little by little.

The first step has been to move `./lib/app` out to `./app`, and `./lib/api` to `api/v1`. These sinatra apps never belonged in lib in the first place.

The second step has been to start reimplementing domain-related code in `./x/*`, using the terminology that we've decided on:

- **Track** -  track is in a language (e.g. C++) and has an ID (e.g. `cpp`)
- **Problem** - a generic description of a problem to be solved, can be implemented in any language
- **Exercise** - a language-specific implementation of a problem. It has a test suite in that language.
- **Solution** - an author's worked answer to an exercise. It may have 1 or more iterations.
- **Iteration** - a single version of an author's solution to an exercise.

The first rewrite under `./x` has been the language pages, which use the new (v3) version of the x-api.

I think the strategy we can start with is to reimplement one action or endpoint at a time. This will likely let us discover what the various dependencies are, reimplement them cleanly, and then we can refactor other parts of the codebase to use the rewritten dependencies.

**Comment by GustavoCaso** [comment]
@kytrinyx Is anyone helping you with this one ?? I'm glad to start reimplementing **iteration** or any other.

**Comment by kytrinyx** [comment]
Nope, nobody's working on this yet. Iteration sounds like a good place to start, if you want to help out!

**Comment by GustavoCaso** [comment]
Sure @kytrinyx. :-)

**Comment by kytrinyx** [comment]
Closing in favor of this discussion: https://github.com/exercism/discussions/issues/29
