### ISSUE TITLE
Add a link to the language-track repository on the language-specific page

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2620]
E.g. http://exercism.io/languages/haskell should have the link to https://github.com/exercism/xhaskell

The http://x.exercism.io/tracks/haskell endpoint has a `repository` key in the response payload.

**Comment by GustavoCaso** [comment]
Sure @kytrinyx. Thanks

**Comment by kytrinyx** [comment]
In case it's hard to find... the languages action lives in `lib/app/routes/languages.rb` and the views are in `lib/app/views/languages/`.

**Comment by GustavoCaso** [comment]
@kytrinyx Thanks, I'll let you know if I get stucks

**Comment by kytrinyx** [comment]
Yeah, I'll add a comment in the PR. Thanks!

**Comment by kytrinyx** [comment]
Fixed in #2623
