### ISSUE TITLE
Language pages should not have different data for logged in / logged out view

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2621]
Right now when you're logged in you see:

- the list of exercises
- the "getting started" section which links to the help pages

When you're logged out you see:

- fetch your first exercise
- the "getting started" section which links to the help pages

We should always see all the sections, in the following order:

- fetch your first exercise
- the "getting started" section which links to the help pages
- the list of exercises

**Comment by GustavoCaso** [comment]
I can take a look at this one as well @kytrinyx

**Comment by kytrinyx** [comment]
Thanks! Let me know if you get stuck on anything--it's a bit of a mess in there.

**Comment by GustavoCaso** [comment]
Sure @kytrinyx I will take a look tonight !

**Comment by kytrinyx** [comment]
Fixed in #2624
