### ISSUE TITLE
Reimplement Language.of

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2630]
Right now `Language.of` in `lib/exercism/language.rb` references the `ExercismWeb::Presenters::Tracks` which does an HTTP call to x-api/v2 (and then caches the entire response). This is problematic on several levels.

I think it would be cleaner if we:

1. Implemented `X::Language` under `./x`
1. Made a call to `X::Track.all`
1. Cached a hash of track ids => language names (not the entire response from `Track.all`
1. If we receive a track id that is not in the list, we can do a new call

Then we can replace the calls to `Language.of` with calls to `X::Language.of` and delete the `lib/exercism/language.rb` file.

Depends on #2628

**Comment by karloxyz** [comment]
@kytrinyx Hi, I'll be working on this.

**Comment by kytrinyx** [comment]
Thanks, @karloxyz!
