### ISSUE TITLE
Reimplement README page using x-api v3

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2631]
The `GET /exercises/:track_id/:slug/readme` action in `app/routes/metadata.rb` can be rewritten to use http://x.exercism.io/v3/tracks/ruby/exercises/bob/readme.

This should use code under `./x` which already has some things that call x-api v3 (`X::Xapi`). I'm not exactly sure what the cleanest thing would be; maybe something like `X::Exercise::Readme.find(track_id, slug)`.

Depends on #2628

**Comment by GustavoCaso** [comment]
@kytrinyx I think this one as well can be close

**Comment by kytrinyx** [comment]
Yepp, you're right. Thanks.
