### ISSUE TITLE
Reimplement exercise test page using x-api v3

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2632]
The `GET /exercises/:track_id/:slug` action in `app/routes/metadata.rb` can be rewritten to use http://x.exercism.io/v3/tracks/ruby/exercises/bob/tests.

This should use code under `./x` which already has some things that call x-api v3 (`X::Xapi`). I'm not exactly sure what the cleanest thing would be; maybe something like `X::Exercise::Readme.find(track_id, slug)`.

Depends on #2628.
Depends on `GET /tracks/:id/exercises/:slug/tests` endpoint described in https://github.com/exercism/x-api/issues/75.

**Comment by GustavoCaso** [comment]
Great @kytrinyx I will work on this one this weekend

**Comment by kytrinyx** [comment]
+1 :)

**Comment by GustavoCaso** [comment]
@kytrinyx How you doing ?
Working on this one, but I have a question about the issue.
Right now the readme and the test page are tabs, but the test page do not change the url, do you want this one to change the url or not, I don't if I explain my self very clear, english is not me native language sorry about that, also there is no link back to the exercise, I think that is need it for better user experience.

**Comment by GustavoCaso** [comment]
One more thing I guess that we only want one request per page. Just the one for the test endpoint.

**Comment by kytrinyx** [comment]
Yeah, let's make separate URLs for the two pages (I thought that's how it was, actually).

When you say a link back to the exercise, which page are you talking about?

**Comment by GustavoCaso** [comment]
This one http://exercism.io/exercises/ruby/nth-prime there is no link back to the actual problem

**Comment by kytrinyx** [comment]
Ah, right. We don't actually have a page for the problem. I can think of two ways to fix this:

1. Add a page for the problem somewhere.
2. Improve this page so that it includes the problem description.

I like (2) better. We should add the "blurb" to the `readme` and `tests` endpoints so that we only need to make one call.

We could also add the command to fetch it.

**Comment by GustavoCaso** [comment]
Ok @kytrinyx sound great I will go with this one

**Comment by GustavoCaso** [comment]
@kytrinyx do you want to create a issue for adding the blurb to the `readme` and `tests`endpoint  in 
x-api ??

**Comment by kytrinyx** [comment]
Sure thing, I'll do it now.

**Comment by GustavoCaso** [comment]
Great @kytrinyx

**Comment by kytrinyx** [comment]
https://github.com/exercism/x-api/issues/83

**Comment by GustavoCaso** [comment]
On more @kytrinyx what happen if the users try to access an non existence exercises do we display an error message and redirect ?? because in the api we have the `exists` endpoint but that would imply two requests

**Comment by kytrinyx** [comment]
Good question.

Right now the API doesn't handle non-existent exercises very well--it returns a 500. Let's do what we did for the `exists` endpoint and return a well-formed json response with all the usual keys, but a 404 status.

Then if they access a problem that doesn't exist on the website we can show them an error message (or encourage them to add the exercise).

**Comment by GustavoCaso** [comment]
@kytrinyx so i will improve the api part for handling the status 404 in exercism.io

**Comment by kytrinyx** [comment]
ok, thanks

**Comment by GustavoCaso** [comment]
@kytrinyx what kind of message are you thinking about ?

**Comment by GustavoCaso** [comment]
Sorry I tend to write faster than I read. You already told me above. I'll read more carefully next time before bugging you

**Comment by kytrinyx** [comment]
no worries

**Comment by GustavoCaso** [comment]
@kytrinyx I think we can close this one

**Comment by kytrinyx** [comment]
Oh, right. Thanks.
