### ISSUE TITLE
Reimplement language dropdown in _nav.erb to use x-api v3

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2633]
The `_nav.erb` partial displays a list of active languages, and currently relies on fully caching the call to `/tracks` in the x-api v1. This seems excessive, but I'm not sure what the correct approach here is.

Perhaps we need `X::Language.all` (see #2630), though we would have to rethink the hash described in #2630 since we would also need to cache inactive languages for `X::Language.of`.

Depends on #2628

**Comment by abhishekbose87** [comment]
Hi @kytrinyx .. could I take a jab at this one ?

**Comment by kytrinyx** [comment]
Yes, that would be great.

The loop happens in `app/views/application/_navbar.erb` and the `tracks` that it's looping over is defined in `app/routes/core.rb`.

**Comment by abhishekbose87** [comment]
@kytrinyx This issue can be closed now.

**Comment by kytrinyx** [comment]
Thanks!
