### ISSUE TITLE
Redesign the /languages page

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2634]
On the "All languages" page, let's get rid of the stats for now and only show the number of problems per language.

It would be lovely if we could have icons for the languages and show this as little boxes instead of a vertical text list, but that might be overreaching a bit.

In addition to the list of languages shown, let's also show the list of upcoming languages ("active: false" in the `X::Track.all` response body).

Depends on #2628 in order to new x-api v3 endpoints.
Could potentially depend on #2357.

**Comment by GustavoCaso** [comment]
Is anyone working on this one ?

**Comment by kytrinyx** [comment]
Not that I know of, if you want it, go for it.

**Comment by GustavoCaso** [comment]
Thanks @kytrinyx

**Comment by gytdau** [comment]
Is this issue still open? Can I contribute in any way?

**Comment by kytrinyx** [comment]
Yeah, I think @GustavoCaso ended up picking something else. If you'd like to work on this, here's where to find the code:

- `app/routes/languages.rb`
- `app/views/languages/all
- `x/track.rb` -- provides access to a method `X::Track.all` that has all the tracks (active and inactive) with various bits of data.

**Comment by GustavoCaso** [comment]
Sorry I had a branch but haven't push already I completely forgot about this branch. Sorry if looks I forgot about this one.

**Comment by kytrinyx** [comment]
Ah, thanks. Looking at the PR now.

**Comment by kytrinyx** [comment]
This is merged and deployed. I regenerated the CSS, but the page is still displaying in a single column. Do you know what might be going on, @GustavoCaso?

Also, I think we should probably only list "upcoming languages" if they have at least 1 problem in them. What do you think?

**Comment by GustavoCaso** [comment]
Hi @kytrinyx let me have a look.

**Comment by GustavoCaso** [comment]
I'm looking at it but is looking good, could it be some kind of cache ?

<img width="1280" alt="screen shot 2015-12-24 at 23 44 50" src="https://cloud.githubusercontent.com/assets/4672858/11998300/61060596-aa98-11e5-905a-3227e0af1912.png">

**Comment by kytrinyx** [comment]
This is what I'm seeing, even with a hard-refresh. I think it is a caching issue. I'll add the file mtime to the url for the css.

![single-column](https://cloud.githubusercontent.com/assets/276834/11998357/650840a4-aa58-11e5-9d78-398209a4f8dd.png)
