### ISSUE TITLE
Start here if you're doing 24pullrequests

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2636]
First of all, :sparkles: yay :sparkles:! We're huge fans of 24pullrequests, and we appreciate all the help we can get.

We're a friendly bunch, and we're happy to help you help us, so don't be scared to ask about anything. We've got a [chat room](https://gitter.im/exercism/support) and there are usually people around there, or just ask right in the issue you're wondering about.

There is a whole repo made just to hold curated "todo" issues. Start looking at the issues labeled "start here": https://github.com/exercism/todo/labels/start-here and then if you find an issue that seems interesting, follow the links from there.

If you're into Go, check out the repository for the CLI. We've labeled a few issues with "good first issue". The bugs are, of course, up for grabs as well!  https://github.com/exercism/cli/labels/good-first-issue

Lastly, in this repository, there's a bunch of stuff, mostly un-curated. Here your best bet is going to be to poke around (see: https://github.com/exercism/exercism.io/labels/bug), and ask some questions. Consider it triage (which is sorely needed and much appreciated!).

Thank you :heart:

**Comment by tejasbubane** [comment]
@kytrinyx Apart from 24pullrequests, I think this getting started info should be somewhere in the README (maybe under the [contribute section](https://github.com/exercism/exercism.io#contribute)).

**Comment by kytrinyx** [comment]
That's a good point. If you get have a moment, would you mind submitting a PR? If not no worries, I'll get to it in a bit.
