### ISSUE TITLE
Replace calls to Xapi.exists? with call to x-api v3

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2637]
I think it would make sense to implement this as `X::Exercise.exists?`, which would rely on `X::Xapi`, which calls v3.

**Comment by karloxyz** [comment]
I'll be working on this.

**Comment by GustavoCaso** [comment]
@kytrinyx @karloxyz anyone working on this one

**Comment by kytrinyx** [comment]
@karloxyz submitted a PR a while back; I asked for some tweaks, and I think that was the last thing that happened. @karloxyz are you still working on this?

**Comment by karloxyz** [comment]
@kytrinyx I've been out of it for a while. Maybe someone else could continue this. Thanks :)

**Comment by kytrinyx** [comment]
Ok, cool. @GustavoCaso in that case it looks like it's up for grabs.

**Comment by GustavoCaso** [comment]
Great @kytrinyx :+1:

**Comment by nickborromeo** [comment]
hi @GustavoCaso wanted to check if you were still working on this?

**Comment by GustavoCaso** [comment]
Hi @nickborremeo I'm currently on vacation and have a working branch in my local. But feel free if you want

**Comment by nickborromeo** [comment]
@kytrinyx I searched the code base for references of `Xapi.exists?` and only found the following references.

```shell
➜  ag "Xapi.exists?"
api/v1/routes/iterations.rb
17:        unless Xapi.exists?(language, slug)

api/v1/routes/tracks.rb
9:        unless Xapi.exists?(id)

lib/exercism/use_cases/attempt.rb
18:    !!slug && Xapi.exists?(track, slug)
```

2/3 references are used in `v1`. I am not sure if this version is still being used or not. Would you also know if the 3rd reference is also being used?

**Comment by kytrinyx** [comment]
Thanks @nickborromeo! v1 is still being used by the exercism cli, and attempt is called every time someone submits an exercise.
