### ISSUE TITLE
Exercises on user show page sorted by first submission, not most recent iteration

### ISSUE THREAD

**Issue by plato721** [exercism/exercism.io#2638]
When authenticated as a user who has completed multiple exercises, with one or more exercises having multiple iterations, the profile page sorts by and displays by the date of first submission for all the exercises instead of the latest iteration as the column heading suggests.

This might be a one-liner, changing the exercises_table partial to:
  <% exercises.order(updated_at: :desc).each do |exercise| %>

where currently it is:
  <% exercises.order(created_at: :desc).each do |exercise| %>

On the other hand, clicking the sorter on top of the table doesn't sort correctly either, and I'm not exactly sure what javascript is hooking in there or what it is doing, so there might be more to this.

Anyway, I'll submit this to get the ball rolling. Thank you.

**Comment by kytrinyx** [comment]
Nice catch, thank you. I think you're right about the one-liner to fix the initial order, but I'm not sure about the sorting.

**Comment by tejasbubane** [comment]
The sorting seems to be working fine for me.

**Comment by kytrinyx** [comment]
The sorting is working for me as well. Closing this. Please reopen it if you have more information about a particular case that doesn't work.

**Comment by plato721** [comment]
Cool looks like the PR fixed it. Thanks.
