### ISSUE TITLE
Running the tests on the master branch fails

### ISSUE THREAD

**Issue by karloxyz** [exercism/exercism.io#2641]
The tests fail inside `test/exercism/trending_test.rb:24`. Is there some setup step I forgot to do?

**Comment by kytrinyx** [comment]
Weird, I wouldn't think so. I wonder if there's a platform-specific thing hiding in that functionality. Let me dig into this a bit and see what I can find.

**Comment by kytrinyx** [comment]
Someone else ran into the same thing, it's a timezone thing: https://github.com/exercism/exercism.io/pull/2643
