### ISSUE TITLE
"Getting started with Racket" instructions are incorrect with respect to running the tests

### ISSUE THREAD

**Issue by nebkor** [exercism/exercism.io#2642]
On http://help.exercism.io/getting-started-with-racket.html, it instructs users to run the tests like "racket hello-world-test.rkt".  However, that will not run the tests in the xracket repo's test files; you need to run "raco test hello-world-test.rkt".  See https://github.com/exercism/xracket/issues/32 and https://github.com/exercism/xracket/pull/33 for the corresponding issue in the xracket repo.

**Comment by kytrinyx** [comment]
Thanks! I'm closing this issue since it's being addressed in the xracket repo.

**Comment by nebkor** [comment]
Awesome; thank you!
