### ISSUE TITLE
Rikki giving advice that isn't relevant.

### ISSUE THREAD

**Issue by remcopeereboom** [exercism/exercism.io#2651]
The Rikki (which is excellent btw) sometimes gives ruby advice that isn't relevant. The offending Rikki can be found in [rikki/comments/analyzer/ruby/control_flow/logical.md](https://github.com/exercism/rikki/blob/master/comments/analyzer/ruby/control_flow/logical.md): it describes the difference between the `and` and `&&` keywords. However, the posts where the automated nit is given contain neither keyword (see [this submission](http://exercism.io/submissions/e0dcb1083dfe4f4c85dfa61d7886aa6c) for an example).

The example above does contain the words "str**and**". Perhaps there is a parsing error by ruby_parser?

**Comment by kytrinyx** [comment]
This is likely a bug. It might be the `not` in there (I doubt that it would have trouble with variable names since the feedback depends on the AST).

/cc @JacobNinja do you know off the top of your head what might have happened?

**Comment by kytrinyx** [comment]
Yepp, it's the `not`: https://github.com/JacobNinja/exercism-analysis/blob/master/lib/exercism-analysis/processors/control_flow_processor.rb#L6

I think we should probably limit this one to `and` and `or`, since rikki- isn't saying anything about `not`. What do you think, @JacobNinja?

**Comment by JacobNinja** [comment]
@kytrinyx sounds reasonable to me. Feel free to submit a pull request to remove `not` from the control flow operator list.

Does this require a new gem version? I forget how the release process works for that gem

**Comment by JacobNinja** [comment]
I went ahead and created a PR for this issue since there were tests involved. https://github.com/JacobNinja/exercism-analysis/pull/13

:shipit: when ready

**Comment by kytrinyx** [comment]
Ooh, thanks! I was just about to submit the PR. A new gem version would be great, actually, so that I don't have to reference HEAD in the Gemfile.
