### ISSUE TITLE
fontawesome-webfont.woff2 404s

### ISSUE THREAD

**Issue by duffn** [exercism/exercism.io#2658]
http://exercism.io/

<img width="1435" alt="screen shot 2015-12-08 at 1 27 41 pm" src="https://cloud.githubusercontent.com/assets/3457341/11669091/a6eb7596-9daf-11e5-9ccc-4c0c7f7af00c.png">

**Comment by kytrinyx** [comment]
I've seen these locally, now that you mention it. We have all the other fontawesome files, just not the woff2 I think.

**Comment by duffn** [comment]
Okay, I'll fix this then.

**Comment by kytrinyx** [comment]
Excellent, thanks.
