### ISSUE TITLE
Learning X/Useful X Resources improvement

### ISSUE THREAD

**Issue by outkaj** [exercism/exercism.io#2660]
Many of the "Learning [Language X]" tabs for various language tracks on the website contain the same slightly misleading message: "We don't have any good resources for learning this from scratch." The same goes for some of the "Useful [X] Resources" tabs: "We don't have any suggestions for resources that might be helpful."
I assume this is meant literally (as in Exercism itself doesn't contain lessons), but it implies that resources for learning X are few and far between, which is rarely the case.
In order to lower the risk of a beginner getting turned away by these empty pages, what do you think about including only one of these tabs (learning or useful resources)?
The page could start with something similar to [the Scala track resources section] (http://exercism.io/languages/scala): "Exercism provides exercises and feedback but can be difficult to jump into for those learning [X] for the first time. These resources can help you get started..."

**Comment by kytrinyx** [comment]
Oh, yes, this means only that Exercism doesn't have any references, and we want other people to submit good resources if they know about them.

I think you're right that we can leave the resources tab empty if both learning/resources are missing.

**Comment by outkaj** [comment]
That makes sense!

I'm fixing these for different languages and opening relevant issues in language tracks, so I can close this here if you like?

**Comment by kytrinyx** [comment]
Sure, I'll close this. Thanks!
