### ISSUE TITLE
Clicking on Test Suite for an exercise does not go to /test, leading to 404

### ISSUE THREAD

**Issue by nate9** [exercism/exercism.io#2661]
When I click on the Test Suite link under "Available Exercises", it will not got to the "/test" page, eg.

http://exercism.io/exercises/java/triangle/tests

instead, it goes to the url without the '/test', eg.

http://exercism.io/exercises/java/triangle

which leads to a 404. The readme works fine, and links to /readme, and you can switch the test suite tab from there.

**Comment by kytrinyx** [comment]
Ah, good catch. I'll fix this ASAP.

**Comment by kytrinyx** [comment]
Fixed. Thanks again.

**Comment by nate9** [comment]
/tests now leads to a 404

When you click the tab for test suite when you are viewing the README.md

**Comment by kytrinyx** [comment]
Ok, thanks, I misunderstood the report. Fixing that now.

**Comment by kytrinyx** [comment]
I deployed a fix.
