### ISSUE TITLE
Profile is using an old avatar.

### ISSUE THREAD

**Issue by Charlotteis** [exercism/exercism.io#2666]
Hai!

I signed up for Exercism a long time ago with my GitHub account. I've just signed up again (I previously denied it permissions) and my profile is using a very old avatar of mine. How do I update it to my current GitHub avatar?

Thank you for making exercism, I tried it a while ago before I really knew how to program and found it intimidating. Now, I feel more prepared to try again!

**Comment by kytrinyx** [comment]
Ah, it might not be updating the avatars. That would be a bug.

I've been trying to figure out how to make exercism less intimidating when people are just starting up. I have some ideas (and I've been talking to some great people who have good ideas). I hope to make some progress on that in the next few months.

**Comment by kytrinyx** [comment]
The github auth code is in lib/exercism/authentication.rb and the code that updates the user data from GitHub is in `lib/exercism/user.rb`.

I've confirmed that it's a bug.

**Comment by Charlotteis** [comment]
Thanks @kytrinyx! I'm really enjoying exercism properly this time around and would love to hear your ideas on the future of exercism. And looks like there is a PR to fix this bug already, which is awesome \o/

**Comment by kytrinyx** [comment]
Yay, looking at the PR now.

I have a _bunch_ of thoughts about the future of Exercism, and I'm not sure where to put things like this.

**Comment by Charlotteis** [comment]
The way we've done it at Hoodie is to start a Discussion repo: https://github.com/hoodiehq/discussion/issues. So if your "future" can be broken into smaller issues up for dicussion, maybe that would work for you!

**Comment by kytrinyx** [comment]
Oh, nice! I think I'll try that. I sure wish I could transfer issues between repositories, there are some discussions in this repo that I think are super valuable, but they're not really actionable.

**Comment by Charlotteis** [comment]
I don't know if there is an easy way to do that :(

RE The PR you merged btw, how do I see if its worked? Sign in / Sign out or remove GitHub integration and try again? :)

**Comment by kytrinyx** [comment]
Yepp, sign out and sign back in. It's deployed.

**Comment by kytrinyx** [comment]
Closing this--if it doesn't work as expected, would you reopen it?

**Comment by Charlotteis** [comment]
Wahey, it worked! Thanks!

**Comment by kytrinyx** [comment]
Yay :sparkles:
