### ISSUE TITLE
Support to follow other users

### ISSUE THREAD

**Issue by emersonsoares** [exercism/exercism.io#2668]
It would be nice to be able to follow some users, so I can keep track of your problem-solving.

**Comment by kytrinyx** [comment]
I completely agree!

We've got this on the roadmap, in https://github.com/exercism/exercism.io/issues/1899

I'm going to close this as a duplicate. If you have more thoughts/ideas about this, would you add them to the discussion in #1899?

**Comment by emersonsoares** [comment]
Cool, sorry I had not seen that issue already exists.

**Comment by kytrinyx** [comment]
Yeah, there are so many issues, it's hard to see what's there and not. I'm trying to figure out how to make it easier to find out what features are in the works.

**Comment by emersonsoares** [comment]
:+1:
