### ISSUE TITLE
ECLIPSE

### ISSUE THREAD

**Issue by Sokos6** [exercism/exercism.io#2670]
Hello,

As instructed, I'm posting here to learn how to open the exercises with Eclipse, language Java. I'm still a little confused as to what i'm supposed to do in general...but this is a good start...
Basically, once I can open an exercise there, I complete it then push it up? 

Cheers,

Will

**Comment by kytrinyx** [comment]
@jtigger Would you help explain how to get this working with Eclipse?

**Comment by jtigger** [comment]
woah!  This one slipped through the cracks!  Will, I'm very sorry I didn't see this sooner.  It's been a month; did you make your way?  Or do you still need assistance?

**Comment by Sokos6** [comment]
Still need assistance. :(

On Friday, February 5, 2016, John Ryan <notifications@github.com> wrote:

> woah! This one slipped through the cracks! Will, I'm very sorry I didn't
> see this sooner. It's been a month; did you make your way? Or do you still
> need assistance?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/exercism.io/issues/2670#issuecomment-180685297>
> .
>


-- 
Will Sokolowski
CEO
Web Frequency
www.webfrequency.com

**Comment by jtigger** [comment]
First, I have to ask this: do you have a specific need to use Eclipse?

If you don't mind using a similar tool, the instructions at http://exercism.io/languages/java are step-by-step using IntelliJ Community Edition.

**Comment by samilaine** [comment]
There are at least two ways to get exercism tasks into Eclipse.

First, the simple way. Let Gradle handle things for you:

1. Fetch an exercise: `exercism fetch java <exercise>` (see [list of available exercises](http://exercism.io/languages/java).
2. Change to the directory containing the exercise: `cd ~/exercism/java/<exercise>` (by default things will end up in `~/exercism`).
3. Let Gradle prepare things for Eclipse: `gradle eclipse`.
4. Start Eclipse and import the exercise:
  * From the "File" menu select "Import".
  * Select "Existing Projects Into Workspace" as import source.
  * Browse the directory containing the exercise fetched during the step 1 to "Select root directory:".
  * Hit the button labeled "Finish".

Second, slightly more difficult way of doing things:

1.  Begin by installing [Eclipse Gradle plugin](https://marketplace.eclipse.org/content/gradle-integration-eclipse) from Eclipse Marketplace.
2. Fetch an exercise: `exercism fetch java <exercise>` (see [list of available exercises](http://exercism.io/languages/java).
3. Start (or restart) Eclipse and import the exercise:
  * From the "File" menu select "Import".
  * Select "Gradle (STS) Project" as import source.
  * Browse the directory containing the exercise fetched during the step 1 to "Root folder:".
  * Hit the button labeled "Build Model".
  * Hit the button labeled "Finish".

To me it seems that the simple way of doing things is, as usual, the better way of doing things. The only caveat I've found this far is that you have to run `gradle eclipse` every time you change something affecting Eclipse. For most exercises there is no need to ever touch `build.gradle` or anything else besides the source files, so this looks like a minor hassle not often encountered.

**Comment by tejasbubane** [comment]
Can we add these instructions alongside those of IntelliJ for people who want to use Eclipse?

**Comment by kytrinyx** [comment]
That would be lovely. I think this is in the https://github.com/exercism/xjava docs. Maybe also https://github.com/exercism/xgroovy.

**Comment by samilaine** [comment]
A [pull request](https://github.com/exercism/xjava/pull/122) has been put into motion.

**Comment by nickborromeo** [comment]
It looks like exercism/xjava#122 has been merged. Given that, is it OK to close this issue? 😄

**Comment by tejasbubane** [comment]
I don't see the eclipse instructions [here](http://exercism.io/languages/java/installing). Looks like they were removed later.
