### ISSUE TITLE
Server responding with error page 

### ISSUE THREAD

**Issue by n7fury** [exercism/exercism.io#2675]
hi, the server is responding to submit with an html error page, (maybe the server is down?)
#2674 here is a package capture of a submit request and the response
[execrism_pk.txt](https://github.com/exercism/exercism.io/files/71371/execrism_pk.txt)
sorry i do not know how to add label, and the github help pages seem to use the old ui?

**Comment by kytrinyx** [comment]
Sorry about that--it's back up now.

The help pages are deprecated--I'm moving all the content over to the main site.
