### ISSUE TITLE
"all languages" page has an odd breakpoint for going to one column

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2677]
At approximately 1300px wide (on my monitor) the /languages page jumps from 6 columns down to one.

![6-columns](https://cloud.githubusercontent.com/assets/276834/12004224/19b47354-ab05-11e5-92b8-80cd6619999b.png)
![one-column](https://cloud.githubusercontent.com/assets/276834/12004225/1b7cff30-ab05-11e5-9a29-e9cf94da9682.png)

@GustavoCaso would you mind taking a look at this?

**Comment by GustavoCaso** [comment]
Of course

**Comment by mhelmetag** [comment]
`app/views/languages/_block.erb` seems to be contributing to the weird styling. It's set to only use a grid layout for large displays.

Also... it seems like hover isn't working on smaller displays. Not sure if that matters because hover isn't really a thing on touchscreens.

Large:
<img width="1680" alt="screen shot 2015-12-26 at 12 57 25 am" src="https://cloud.githubusercontent.com/assets/8609429/12005303/860b9eda-ab6c-11e5-8f6b-233f09ad8719.png">

Small:
<img width="1680" alt="screen shot 2015-12-26 at 12 57 34 am" src="https://cloud.githubusercontent.com/assets/8609429/12005304/8e7e6a20-ab6c-11e5-9acb-156bc0f2ab61.png">

(Imagine my cursor on the Closure icon... for some reason screencap seems to edit that out)

**Comment by GustavoCaso** [comment]
Well I don't have a monitor that big so I'm notable to reproduce the `bug`. But could it be because Bootstrap hard code the width of the different breakpoints, and we use 1200px as the large breakpoint ?

https://github.com/exercism/exercism.io/blob/master/public/sass/base/themes/exercism.scss
```
//== Media queries breakpoints
//
//## Define the breakpoints at which your layout will change, adapting to different screen sizes.

// Extra small screen / phone
//** Deprecated `$screen-xs` as of v3.0.1
$screen-xs:                  480px !default;
//** Deprecated `$screen-xs-min` as of v3.2.0
$screen-xs-min:              $screen-xs !default;
//** Deprecated `$screen-phone` as of v3.0.1
$screen-phone:               $screen-xs-min !default;

// Small screen / tablet
//** Deprecated `$screen-sm` as of v3.0.1
$screen-sm:                  768px !default;
$screen-sm-min:              $screen-sm !default;
//** Deprecated `$screen-tablet` as of v3.0.1
$screen-tablet:              $screen-sm-min !default;

// Medium screen / desktop
//** Deprecated `$screen-md` as of v3.0.1
$screen-md:                  992px !default;
$screen-md-min:              $screen-md !default;
//** Deprecated `$screen-desktop` as of v3.0.1
$screen-desktop:             $screen-md-min !default;

// Large screen / wide desktop
//** Deprecated `$screen-lg` as of v3.0.1
$screen-lg:                  1200px !default;
$screen-lg-min:              $screen-lg !default;
//** Deprecated `$screen-lg-desktop` as of v3.0.1
$screen-lg-desktop:          $screen-lg-min !default;

// So media queries don't overlap when required, provide a maximum
$screen-xs-max:              ($screen-sm-min - 1) !default;
$screen-sm-max:              ($screen-md-min - 1) !default;
$screen-md-max:              ($screen-lg-min - 1) !default;
```

**Comment by kytrinyx** [comment]
I don't know anything about front-end. Another option would be to put all the boxes in the same row and then let them flow however the screen sees fit (but that might be a terrible idea).

**Comment by mhelmetag** [comment]
Wouldn't a fix be setting the spacing for small or xsmall resolutions by adding the class `col-sm-2` or something to each language link element?

**Comment by kytrinyx** [comment]
I don't even know what that means, but it sounds like you're speaking from experience so... probably!
