### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Ferroso** [exercism/exercism.io#2678]
exercism submit difference-of-squares.rkt
2015/12/25 21:51:52 unable to submit solution - an internal server error was received.
Please file a bug report with the contents of 'exercism debug' at: https://github.com/exercism/exercism.io/issues 
**** Debug Information ****
Exercism CLI Version: 2.2.1
Exercism CLI Latest Release: 2.2.1
OS/Architecture: linux/amd64
Build OS/Architecture linux/amd64
Home Dir: /home/ron
Config file: /home/ron/.exercism.json
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /home/ron/exercism

**Comment by kytrinyx** [comment]
I'm not getting this error. There may have been a problem during restart. Would you please try again?

**Comment by Ferroso** [comment]
Hi. I have just looked at my profile on exercism.io and found that the solution was there. The error message that I received is puzzling.  I rebooted my laptop and tried again. The second submission again produced the error message but I found the submission in my profile. I then deleted it for tidiness.

**Comment by Ferroso** [comment]
I have just successfully submitted another solution. The problem seems to have gone away.

**Comment by kytrinyx** [comment]
For reference, I figured out what happened:

- deployed
- ran a migration that removed a deprecated column from a table that was in use
- a cached prepared statement was trying to run

So even though none of the code in the codebase was using that field any more, the cached prepared statement was referencing it, and it broke.

Restarting the app fixed this.

So sorry for the trouble!

**Comment by Ferroso** [comment]
No trouble!  I have used the app today and it appears to function perfectly.
Thanks for investigating it.
