### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by emaestracci** [exercism/exercism.io#2679]
exercism submit /Users/Emmanuel/exercism/ruby/gigasecond/gigasecond.rb
2015/12/25 23:01:04 unable to submit solution - an internal server error was received.

**Comment by kytrinyx** [comment]
Checking, thanks.

**Comment by kytrinyx** [comment]
I'm not seeing it. Would you please try again? There may have been a problem during a restart.

**Comment by emaestracci** [comment]
Everything is now fine. Thanks :)

**Comment by kytrinyx** [comment]
For reference, I figured out what happened:

- deployed
- ran a migration that removed a deprecated column from a table that was in use
- a cached prepared statement was trying to run

So even though none of the code in the codebase was using that field any more, the cached prepared statement was referencing it, and it broke.

Once the app was restarted the error went away.
