### ISSUE TITLE
Daily 5 are the same everyday

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#2685]
Hi there!

3 out of the daily 5 don't changed over the last week. I already liked this three entrys but they still appear in the daily fives.

There is nothing I could nitpick on these entries and I'm feeling forced to do a stupid "+1" comment just to get rid of them as dailies.

**Comment by kytrinyx** [comment]
We have an open PR that might fix this--it's the third iteration (trying to get the performance of the query to an acceptable level). If that doesn't work today I'll try another tactic.

**Comment by kytrinyx** [comment]
OK, deployed. Would you give this a try?

**Comment by NobbZ** [comment]
I check tomorrow when dailies are rerolled.

Katrina Owen <notifications@github.com> schrieb am Di., 29. Dez. 2015 22:14:

**Comment by kytrinyx** [comment]
Did you get a chance to check this?

**Comment by NobbZ** [comment]
It seems as if they are better spread now and nothing from the previous days.

I'll watch a little bit further but close for now.

**Comment by kytrinyx** [comment]
OK, thanks.
