### ISSUE TITLE
rake db:create and db:drop fails with OS X Postgres.app

### ISSUE THREAD

**Issue by duffn** [exercism/exercism.io#2689]
I know the contributing guide suggests installing PostgreSQL with `brew install postgresql`, but if you do install on OS X with [Postgres.app](http://postgresapp.com/), then  `rake db:create` and `rake db:drop` do not work immediately.

```sh
% rake db:create                                                                                                                                            
rake aborted!
Failed to create database
/exercism.io/lib/tasks/db.rake:61:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
```

Postgres.app does not automatically put the cli tools in your path so `createdb` and `dropdb` are not available immediately upon installation.

Does this warrant a note in the contributing guide about Postgres.app?

http://postgresapp.com/documentation/cli-tools.html

>
Configure your $PATH
Postgres.app includes many command line tools. If you want to use them, you must configure the $PATH variable.
>
If you are using bash (default shell on OS X), add the following line to ~/.bash_profile:
>
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin
>
If you're using the fish shell, add the following to your config.fish (normally located at ~/.config/fish/config.fish):
>
set PATH /Applications/Postgres.app/Contents/Versions/9.4/bin $PATH
You can now check if the path is set up correctly by typing which psql.

**Comment by kytrinyx** [comment]
Yeah, we should probably add a note about that. Thanks!
