### ISSUE TITLE
java hello-world gradle build fail

### ISSUE THREAD

**Issue by jimypbr** [exercism/exercism.io#2690]
Trying the java hello-world exercise. The `gradle test` fails.

```
$ exercism fetch java hello-world
$ cd hello-world
$ gradle test

FAILURE: Build failed with an exception.

* What went wrong:
Task 'test' not found in root project 'hello-world'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.198 secs
```

The build.gradle file is empty. Should it have tests defined in here? Does this work for anyone else? Thanks.

**Comment by NobbZ** [comment]
You should ask again over on xjava.

**Comment by jtigger** [comment]
Really sorry about that, James.  We had a mix-up and inadvertently cleaned
out the build.gradle files.

It's a known issue.  Been fixed. Is being deployed, presently.

https://github.com/exercism/xjava/pull/80

**Comment by kytrinyx** [comment]
The fix is now deployed.
