### ISSUE TITLE
dashboard doesn't sort exercises by language track order

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#2693]
When I go to my dashboard, I want to see the exercises in language track order, but the sort order is just alphabetical.  This doesn't help me understand the progression of exercises within a track.

**Comment by kytrinyx** [comment]
Yepp, good call. This is the "your exercises in progress" section, right?

**Comment by LegalizeAdulthood** [comment]
Yes, that's the place.
