### ISSUE TITLE
C++ icon hides the ++

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#2699]
![image](https://cloud.githubusercontent.com/assets/4270863/12075838/6ce45ea8-b14b-11e5-837f-0518cb9e0a25.png)

To me this looks like an icon for `C`, not `C++`.  The `++` should be very prominent in the icon.  It appears that it is authored in a [high resolution version](https://github.com/exercism/exercism.io/blob/master/public/img/cpp.png) that loses the `++` when scaled down to display resolution.

**Comment by kytrinyx** [comment]
I was thinking of re-doing all of the icons so that they're all in the same style (right now some are flat, some are glossy, some are logos, some are not).

I'm going to take a stab at this today. I'll post some screenshots here so that we can discuss it.

**Comment by kytrinyx** [comment]
![screen shot 2016-01-02 at 12 42 08](https://cloud.githubusercontent.com/assets/276834/12075888/412f035a-b14e-11e5-912b-49216526d5a8.png)

How about something like that?

**Comment by LegalizeAdulthood** [comment]
I would literally make the `++` the same size as the `C`, although googling around for icons shows that your style is more common.  The reason I argue for a larger `++` is that this is going to be a really tiny icon in the end and we need the `++` to be blatantly obvious when scaled down to final display resolution.

**Comment by kytrinyx** [comment]
Yeah, good point. How about this?

![screen shot 2016-01-02 at 12 48 00](https://cloud.githubusercontent.com/assets/276834/12075905/198a056a-b14f-11e5-82f2-ca6dcc4ac799.png)
![screen shot 2016-01-02 at 12 47 39](https://cloud.githubusercontent.com/assets/276834/12075906/198aaff6-b14f-11e5-9367-ba304fd964b3.png)

**Comment by LegalizeAdulthood** [comment]
I like the 2nd one!  Not sure about the purple, though. LOL.

**Comment by kytrinyx** [comment]
Yeah, it's the main exercism color, though, so I was thinking of making all of the logos some variation of pink and black.

I'll try all black/white and see what that looks like, too.

**Comment by kytrinyx** [comment]
I'm deploying this with an all-black logo.

**Comment by LegalizeAdulthood** [comment]
That looks much nicer.  It's easy to tell at a glance that it is C++.
