### ISSUE TITLE
help pages have ragged formatting

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#2710]
I'm not sure how these help pages are being generated, but the formatting looks awful.  It looks like every newline in the source file is being treated as a hard line break?

![image](https://cloud.githubusercontent.com/assets/4270863/12097560/8d960bb2-b2d9-11e5-8fec-ef62c9ac91b9.png)

**Comment by kytrinyx** [comment]
These are being generated from markdown. I thought markdown only generated hard breaks / new paragraphs if there was a blank line between two blocks of text. I'll clean that up.

**Comment by kytrinyx** [comment]
Apparently, markdown will also generate hard breaks if a line ends with two spaces. I don't see any spaces here, so there might be a bug in how we're generating the html.

**Comment by kytrinyx** [comment]
Found it. We were passing an option explicitly--no idea why. Fix incoming.
