### ISSUE TITLE
Up-/Downvoting of nitpicks

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#2711]
Sometimes I do stumble over some nitpicks that give some advice in the wrong direction. Even while I try to argue and add clarifying nits, I'm missing the possibility to up- and downvote nitpicks.

**Comment by kytrinyx** [comment]
I think this would be useful, however I worry that it would devolve into stack-overflow style gamification.

**Comment by NobbZ** [comment]
I don't think that SO style gamification is a bad thing. I do see that it works, and at least for me it is very encouraging to see karma climbing up, to be honest, I even thought about proposing some karma system for exercism.io, but after your answer I have stopped my thinking in that direction.

So how can we achieve some system that does mark dangerous nits as such, without gamifing to much? That was the question that bothered me since I read your answer. So the following came into my mind:

* Make users able to “report” some nit including a comment (not allowed to be empty!).
* Put that report into the inbox of tracks maintainers/trusted people/mentors/whatever there is besides mainters.
* Let the tracks VIP decide wether this is a good nitpick, a bad one or a neutral one (also keeping the original request of the reporter in mind) and let him flag the nit as such.
* After the nit has gathered some votes into one or other direction, display its border/headline/some other markings in shades of red/yellow/green to signal an approximation of its “worth”.

A downside I do see here is, that users could misuse this feature too much in one or other direction instead of really thinking about and abuse it as a moderated up/downvote button, which again would put much work on the tracks VIPs.

So either users should first show they are responsible enough to not abuse that feature (which again would be easiest with some karmasystem) or the VIP should be able to flag abusing users so that an automated system would temporarily block them from reporting nits when flag count grows to much. For this case I thought about an expiration time of 30 days per flag.

Still, this system is far from perfect and just something we can argue and discuss about.

Until then I'll continue as before and give counteradvice with a reason ;)

**Comment by jtigger** [comment]
Interesting.  What about the ability to tag your own response to a
nitpick?  It would be a pre-defined list with easy-to-spot icons... for
example, "++" (thumbs-up), "--" (thumbs-down).  or emoticons that range
from delight to flipping tables.

Do no show counts of any of the tags, they are simply visual clues that
draw the eye to the comment.  To that end, any submission that has a tag
gets a generic flag in the tracks/:track/exercises view.

The UX makes it clear that tagging is absolutely optional.  In fact, when
you select a tag, there's some prompt (conditional coaching tip) next to
the tag that says something like, "Constructively, why do you feel this
way?"

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/exercism.io/issues/2711

**Comment by kytrinyx** [comment]
I've opened a high-level issue to discuss how to improve the quantity/quality of feedback: https://github.com/exercism/discussions/issues/88
