### ISSUE TITLE
Track Stats -- and related tools to improve the feedback / responsiveness on the site

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2712]
So. Stats are here: http://exercism.io/stats

Let's talk about how we can use this to improve the conversations and the tracks!

**Comment by kytrinyx** [comment]
@jtigger mentioned in the chat room:

> the ability to set a target ratio of submissions to reviews for each exercise (some ought to generate more conversation than others)... then sort submissions by those with the greatest gap between goal and actual.

Also, a gist that @jtigger appears to have made up on the fly:

```
require 'json'

RESPONSIVENESS_GOAL = 0.5 # "You have a 50/50 chance of getting a meaningful review."

def fetch_stats_for(track)
  canvas_element = `curl --silent http://exercism.io/stats/#{track} | grep canvas`
  stats_attr = /data-stats='(.*)'/.match canvas_element
  stats_json = stats_attr[1]

  stats = JSON.parse stats_json
end

def generate_exercises_from(stats)
  stats["labels"].each_with_index.map do |label, index|
    reviews = stats["reviews"][index]
    iterations = stats["iterations"][index]
    {
        exercise: label,
        reviews: reviews,
        iterations: iterations,
        responsiveness: iterations > 0 ? reviews.to_f / iterations.to_f : 0
    }
  end
end

def find_neglected_exercise exercises
  exercises.find { |exercise| exercise[:responsiveness] < RESPONSIVENESS_GOAL }
end

track = ARGV[0] || 'java'
stats = fetch_stats_for track
exercises = generate_exercises_from stats
exercise_to_review = find_neglected_exercise exercises

reviews_to_do = (exercise_to_review[:iterations] * RESPONSIVENESS_GOAL).to_i - exercise_to_review[:reviews]

puts "Review #{reviews_to_do} iterations of #{exercise_to_review[:exercise]}."
```

**Comment by kytrinyx** [comment]
Hey, @jtigger, should I create API endpoints for any of the stats that we find useful? It seems a bit less dirty than parsing it out of the canvas :)

**Comment by jtigger** [comment]
yes, please!

**Comment by jtigger** [comment]
gist: https://gist.github.com/jtigger/0681416df8a54bb38d6f

**Comment by kytrinyx** [comment]
Incoming.

**Comment by jtigger** [comment]
Better if it were reported as a list of exercises with stats attached to each exercise.

**Comment by kytrinyx** [comment]
Agreed--that's how it's coming out of the database. I had to munge it for the chart.js library.

something like:

```
track: {
  id: "java",
  problems: [
    "hello-world": {"iterations": 17, "reviews": 17},
    "anagram":  {"iterations": 12, "reviews": 9},
    // ....
  ]
}
```

**Comment by kytrinyx** [comment]
Also, what other data should we see if we can tease out of the database?

**Comment by jtigger** [comment]
I like where you're going with timing of responses... not sure how to present... will think on it.

**Comment by kytrinyx** [comment]
Hm. If we return the problems as an array, then we can have them in track order, which I think is useful.

**Comment by kytrinyx** [comment]
OK, weird. I knew that Ruby's current implementation of hashes keep them ordered, but the json appears to also be ordered.

**Comment by kytrinyx** [comment]
OK, @jtigger here you go: http://exercism.io/api/v1/stats/java/activity/recent

**Comment by kytrinyx** [comment]
@verdammelt @canweriotnow @jtigger I added variations on that chart. Take a look and let me know what seems useful.

**Comment by canweriotnow** [comment]
@kytrinyx I can't remember, does exercism use jQuery? I'd kind of like to play with a fork using highcharts as mentioned on Gitter, but I need to look at deps to see whether or not to use the jQuery version or the non-jQuery version (latter preferred :smile: )

**Comment by kytrinyx** [comment]
Yeah I think it does. At least, I think that the javascript I wrote today was jquery... but seeing as I'm javascript impaired, that might be untrue.

**Comment by jtigger** [comment]
There's a process in Data Science of doing what amounts to discovery with what's known as data exhaust.  This is very much what we're up to.  Trying lots of different shapes, sizes and colors on to see what resonates.  Read: let's keep playing like this.

This round is forcing me to wonder what the shelf life of this kind of data is.  I do find varying windows helpful for perspective (like the load outputs from unix top): is this a blip? is this a trend? is this the new normal?

Also, I'm chewing on what questions we can ask that are actionable. Things like: is there a correlation between participants getting timely feedback and the probability that they will submit again? What does "timely" mean? What feedback are participants finding useful (and why)?  What feedback are they not finding useful (and why)?

Questions like this point to some set of assumptions and desired outcomes.  What are those, explicitly?

The structure of such a model is:
a set of practices/actions taken guided by...
a collection of principles/rules of thumb that point toward...
a list of desired essences which are a realization of...
deeply held values.

----
(dictation taken by Thumba Leena)

**Comment by jtigger** [comment]
... as a matter of fact, one of our Data Scientists just did a Lunch n' Learn about the shape of a typical engagement. I am going to see what appetite April has to help out, here.  At the very least, she can help bootstrap the tool chain and process of developing statistical models that we'd want to grow to start asking such questions...

----
(dictation taken by Thumba Leena)

**Comment by jtigger** [comment]
... hey @canweriotnow, is this kind of modeling the stuff that Yet Analytics does?  I see in a different but relates issue you mention looping them in...

----
(dictation taken by Thumba Leena)

**Comment by kytrinyx** [comment]
@jtigger these are great questions. I'd love to hear what April (or Noelle) would have to suggest about how to improve this discovery process.

**Comment by simondiep** [comment]
@kytrinyx In regards to your initial comment, the link [http://exercism.io/stats](http://exercism.io/stats) redirects to [http://exercism.io/stats/clojure](http://exercism.io/stats/clojure) with an HTTP 500 error

**Comment by kytrinyx** [comment]
Ah. That's new. I must have broken something.

Update: actually, it looks like clojure is broken, but e.g. Go is not.

**Comment by kytrinyx** [comment]
This conversation has wound down. If you have new ideas around this, please open a new issue in the https://github.com/exercism/discussions repository
