### ISSUE TITLE
External integrations

### ISSUE THREAD

**Issue by canweriotnow** [exercism/exercism.io#2715]
This is more of an ideation issue, I'm not sure what exactly would be the most useful/possible.

I've mentioned the possibility of instrumenting exercism for [xAPI](https://github.com/adlnet/xAPI-Spec) and providing free LRS/analytics from [my company](http://yetanalytics.com)'s platform. 

But I was also thinking about other developer community sites like [Coderbits](http://coderbits.com), [Coderwall](https://coderwall.com), etc.

Still thinking this through. But I think being able set up webhooks would be a potentially popular feature, and low-hanging fruit for the most part. Interested in what others think.

**Comment by kytrinyx** [comment]
I'm totally open to this, but it would require other people doing the bulk of the thinking and the implementation, since at the moment I'm focused on fixing the onboarding and closing the feedback loop, both of which are big and complicated.

**Comment by canweriotnow** [comment]
@kytrinyx Yeah, definitely. Just wanted to open the conversation. I'm happy to build integrations, just wanted to see what people thought might be useful before I start on anything.

**Comment by bunnymatic** [comment]
I'll throw in another :+1:.  Given the new teams thing, I'd love to have a webhook for my team such that whenever someone on my team submitted a new exercise, one of our slack channels would get a notification.

**Comment by kytrinyx** [comment]
I like these ideas, and have marked this with `design-research` so that we can consider it as part of the reboot. I'm going to close this, but if anyone wants to do more spitballing, please open a new issue in the https://github.com/exercism/discussions repository.
