### ISSUE TITLE
Fail if migrations are pending

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism.io#2719]
Currently there is no check for pending migrations. Tests fail directly if migrations are pending. Also there should be an alert before server starts.

I tried adding the following code to `config.ru` and `test_helper.rb` but `active_record` is not loaded by then, so could not get it to work.
```
if defined?(ActiveRecord::Migrator) && ActiveRecord::Migrator.needs_migration?
  raise 'Migrations are pending run `rake db:migrate` to resolve the issue.'
end
```

**Comment by kytrinyx** [comment]
We can require Active Record in config.ru.
