### ISSUE TITLE
Show my stats such as nits given and nits recieved

### ISSUE THREAD

**Issue by StevenACoffman** [exercism/exercism.io#2721]
I feel like there used to be a way to show the nits I had previously picked, but I cannot find it.

I had left a comment on someone's, and then later found out I had perpetuated a myth, and now I cannot find it except by going through several pages of recently viewed.

I also would use this to bookmark interesting solutions.

**Comment by StevenACoffman** [comment]
Ok, yep. My browser history has URLs like:
* exercism.io/nits/StevenACoffman/stats 
* exercism.io/nits/StevenACoffman/given  
* exercism.io/nits/StevenACoffman/received
But those are now giving 404s. Have the links changed? This was very useful functionality for bookmarking previously given nits.

**Comment by StevenACoffman** [comment]
Ah! This was removed in db57479394461c32db5e02f19d9b92bed58d8de4 

So sad. Where we now have "recently viewed" can we have a "recently commented" or "recently given" or something so we have a way of getting back to things we've commented on?

**Comment by StevenACoffman** [comment]
By the way, [other people have been touting this feature](http://exercism.io/submissions/778b2276754e4592aefca30c4889f6cb) as a way to keep track of interesting solutions, and so it has been encouraging some people to comment more. I think it was hard to find that it existed.

**Comment by kytrinyx** [comment]
Yeah, it was hard to find, and not well-implemented. I think we should have a way of getting back to comments--a proper search feature would be excellent.

**Comment by kytrinyx** [comment]
I think that a good stats feature would be useful, however it didn't seem like the previous implementation was being used at all. If we implement this I'd like to do good research into what people actually need and are frustrated by, not just make wild guesses.

**Comment by StevenACoffman** [comment]
Fair enough. We've got 37 people on our team, and the consensus is that a way of bookmarking interesting solutions is very much wanted. Similarly, people want to revisit their old comments, which can be a way of bookmarking.

Actual search is an interesting idea. There's a lot of possibilities there, so actual research before implementing be good.

**Comment by kytrinyx** [comment]
Yeah, it sounds like there are lots of needs here that we should look into before taking another stab at this. Thanks for kicking off the discussion.

**Comment by kytrinyx** [comment]
There's a feature that I've been thinking about for a long time, that might help with this: Subscribe/Unsubscribe to conversations.

This would let you follow a conversation without commenting, or unfollow a conversation where you were mentioned or where you commented.

Then we could add a page that shows you the conversations you're subscribed to (that could be a bit messy--I'm subscribed to about 4000 conversations at this point, but I guess that's what pagination is for).

This isn't really the same as bookmarking, which we also probably should implement in some way. I need to think about this more.

**Comment by ErikSchierboom** [comment]
I'm actually slightly amazed that there is no page that just lists all my comments. That would be incredibly useful, as I had the same problem as @StevenACoffman where I would like to revisit an earlier comment but could not find it anywhere.

**Comment by kytrinyx** [comment]
Yeah, I know. We had something but it wasn't searchable, and it wasn't sortable by track/problem. We really should have an activity stream on your profile that shows both your exercises and your comments.

**Comment by kytrinyx** [comment]
I've added the design research label to this so that we can evaluate the question within the larger context of the design reboot (see https://github.com/exercism/discussions/issues/113 for more about this).

If you do think that it can be implemented as a not-too jarring and not-too complicated experiment in the current website, please open a new issue about it in the discussions repository.
