### ISSUE TITLE
Add a private "share" link

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2731]
I'd like to make it possible for people to share their profile in a way that gives people access to their exercises.

In other words: if you visit their profile normally, then you would only have access to the exercises that you've done yourself. If you visit with the private share link, then all the exercises would be accessible to you.

This would be really useful for people who want to share with friends and colleagues who are not on exercism, or with prospective employers.

**Comment by abhishekbose87** [comment]
@kytrinyx This would be a great addition to exercism :+1: 

I am listing some steps to get to the design of the solution. Looking forward to your suggestions.
- Have a button on profile page to generate private url link 
  - generate url using format `http://exercism.io/{{user_id}}/public_profile/{{6 digit id}}`
  - store the 6 digit id in user table for verification
- Allow visits to this page without authentication using the 6 digit id and user_id.

**Comment by kytrinyx** [comment]
I think for the URL I'd like to use `http://exercism.io/profiles/:username/:short_uuid` where :uuid is the first 6 digits of an `Exercism.uuid`. I agree that this should be stored in a table for verification -- the users table is probably fine for this.

If you have the url, then you will be able to visit the page without authentication.
On this page, all of the links to the user's exercises will go directly to the exercise (no login necessary). I think submissions currently allow views without being authenticated, so this should be fine.

**Comment by abhishekbose87** [comment]
Looks good to me. Actually 6 digits was a random number, I rather use the full value of `Exercism.uuid`.

Let me submit a PR by end of this week.

**Comment by kytrinyx** [comment]
Excellent, thanks!
