### ISSUE TITLE
directory structure not preserved on submission

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism.io#2732]
The directory structure on my local machine for a certain exercise is:

```
~/exercism/go/poker
|-- poker.go
`-- hand
    |-- hand.go
    `-- parse.go
```

All right, so I submit via `exercism submit poker/{hand/hand.go,hand/parse.go,poker.go}`.

After I submit, I think Exercism has flattened the directory structure so that everything is in the same directory. I have two reasons for thinking so.

## reason 1: automated feedback

@rikki- comments on my solution saying "`go vet` is complaining about your solution." .

I think `go vet` shouldn't complain because when I run locally `go vet ./poker; go vet ./poker/hand` the output is empty.

As an experiment I moved all three files into the same directory and run `go vet` and now the output is `can't load package: package .: found packages hand (hand.go) and poker (poker.go) in /home/pt/exercism/go/poker`

I admit I could be totally wrong -- I can't tell for certain what the `go vet` output is that @rikki- sees, so I am guessing.

## reason 2: exercism download

The exercism CLI allows a `download` function that lets you download a given submission. I download my submission, and see that all the files go in the same directory. The `hand` directory has completely disappeared.

I was content to leave it be but @kytrinyx says that's a bug, so sure, I'll go file an issue on it.

Here's the impact I see this having:
* Those who submit multiple *packages* for a Go solution will get false positives on automated feedback, one per submission. (Multiple *files* for a Go solution but in the same single package will still be OK.)
* Those who use `exercism download <submission-id>` of a submission with a directory structure instead get it flattened. This affects, for example, anyone who wants to download my solution and run it out of the box. They can't; they have to recreate the directory structure first.

In case you are wondering, everything else is fine (the code still shows up and is readable).

I imagine the affected population is quite small, but good to mention for completeness, eh?

**Comment by petertseng** [comment]
A little bit of #2174  in here. In particular, the "There's a caveat, if files are in a subdirectory, then they need to be stored relative to the problem dir, not with just the filename." needs to be done

**Comment by kytrinyx** [comment]
I'm pretty sure this was done, but I'm going to take a closer look. This is high priority bug.

**Comment by petertseng** [comment]
If you think it was in fact done already, and the change involves a CLI client change, let me know. I may have submitted with an old 2.2.1 client, since I hadn't updated until a few hours ago. I can start building clients from git instead.

**Comment by kytrinyx** [comment]
Give me a bit to dig into this. There are few moving pieces (and the ruby codebase is a mess). I think the bug is in the ruby code, the cli should just write whatever path the api says the file is at.

**Comment by kytrinyx** [comment]
The bug is definitely in the Ruby code.

**Comment by kytrinyx** [comment]
I've confirmed that the bug is in ruby.

The CLI submits:

```
{
  "clock.go"=>"...",
  "subd/subd.go"=>"..."
}
```

But the database stores:

```
{
  "clock.go"=>"...",
  "subd.go"=>"..."
}
```

**Comment by petertseng** [comment]
Thanks. I'll take a look in a few hours by submitting my poker solution.

**Comment by petertseng** [comment]
:+1: directory structures good

**Comment by petertseng** [comment]
And now the bad news. This broke `exercism download` for submissions containing directories. Will file issue and fix soon.

**Comment by kytrinyx** [comment]
Darn, ok--good catch.
