### ISSUE TITLE
Investigate New Relic noise when running local server with ruby 2.3

### ISSUE THREAD

**Issue by mhelmetag** [exercism/exercism.io#2733]
I've noticed that since the upgrade to ruby 2.3.0 there's a lot of noise in the server logs... I'm not really sure if this is just on development but I'm guessing not since new relic is for production monitoring. When I'm testing locally, I'm seeing each request take around 1 - 3 seconds (not super stoked about that).

The issue is pretty easy to reproduce. Basically pull the latest exercism master branch, make sure you're using 2.3.0 and just spin up a local server with foreman. Assume one of the test profiles and navigate to their account page (or really make any request for that matter). Watch the server logs explode! You can also look at server response times by visiting `localhost:4567/newrelic` (that's where I got my screenshot).

I reverted back to 2.2.2 just to see what would happen and the issue goes away. I'm wonder... do we even use new relic for monitoring? Do we need that gem and the integration? If so... did the API change? Do we need to upgrade? Does the API support 2.3.0?

**Comment by mhelmetag** [comment]
<img width="647" alt="screen shot 2016-01-21 at 10 32 24 pm" src="https://cloud.githubusercontent.com/assets/8609429/12504009/aa0b9a56-c08e-11e5-8c8d-941f94f7487d.png">

**Comment by kytrinyx** [comment]
I'm seeing the same noise in the server logs locally, but not in production.

I'm thinking... let's just ditch the gem for now. I haven't been looking at the newrelic stuff for a long while, and we can always take some time to put it back in when we're ready to look at actual performance issues.

**Comment by mhelmetag** [comment]
Sounds good! I'll check that out.

Last night I was experimenting with upgrading a few different gems but upgrading `newrelic_rpm` didnt solve our problems. I also looked at the implementation and thought maybe something had changed but that wasn't it either.

Since it's just a development environment issue, I have a feeling that it might have to do with tenabling developer mode (https://github.com/exercism/exercism.io/blob/master/config.ru#L32).

**Comment by kytrinyx** [comment]
I'm not sure it's just a newrelic thing. Still investigating.

**Comment by kytrinyx** [comment]
OK, I'm absolutely convinced that this has nothing to do with newrelic, but I don't really want to dig into this right now... I'm working on something else that requires a ton of work, and I don't want to go down this rabbit hole.

I'm going to revert the upgrade temporarily until someone (maybe me) has time to dig into this.

**Comment by Insti** [comment]
Newrelic was removed from exercism.io in January 2016

https://github.com/exercism/exercism.io/commit/859e7262737c6254e03dde3ebbe8a8d058ff730a
