### ISSUE TITLE
Progressbars on accountpage, differ between archived and not archived exercises

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#2734]
Hi, since I see a fundamental difference between archived and not archived submissions in their level of "finishness" I'd like to see them differentiated in the progressbars also.

I don't know if it is (easily) possible to do the change, but my idea is the following:

To the left of the bar have a green part which corresponds to the number of archived submissions in that track.
To the right of the green archived bar, lets have a yellow/orange bar corresponding to the number of not archived submissions in a track.
The remaining part just stays blank as it is now.

An explanation of the colors could be put either at the top or the bottom of the "list" of bars.

**Comment by kytrinyx** [comment]
How about gray for archived and green for "in progress"? I don't want people to think that the goal is to archive things as quickly as possible.

@paradime what do you think?

**Comment by NobbZ** [comment]
I'm not nailed exactly on the colors I mentioned and I do understand your
opinion. I just mentioned the colors as a starting point for discussions.

Katrina Owen <notifications@github.com> schrieb am Fr., 22. Jan. 2016 22:23:

**Comment by kytrinyx** [comment]
Yeah, that's what I figured. The "orange" makes me think "warning" though, so I immediately reacted to it.

**Comment by kytrinyx** [comment]
Thanks so much for weighing in on this, everyone. We're going to be removing the progress bars and trying a different tactic—we'll see how that works out. See https://github.com/exercism/exercism.io/pull/3117 for the final result (still in the works).

**Comment by paradime** [comment]
Launch and iterate. :+1:
