### ISSUE TITLE
Make display of progressbars collapsable

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#2735]
Some users have quite a large number of touched tracks.

My own list of progressbars has 13 entries (I really need to touch another track) and when I look at my own profile page, I do only see progressbars and I have to scroll down a complete "page" before I have my actual list of "open" submissions.

Perhaps there are user which have even more entries (or smaller displays) and it might be hard for them to scroll to the right place in an instance. So I think it would add much to usability when we could simply collapse the progress-area.

Maybe we can even have a setting, if one wants to see the progress on profile pages collapsed or uncollapsed per default.

**Comment by kytrinyx** [comment]
How about only showing the most recently touched track by default, with a link to expand to "show all" if you have more than one progress bar?

@paradime how easy do you think this would be?

That would make it so you don't scroll a whole lot, we don't have to have a setting, and people who only have one will never know that we only show one by default.

**Comment by NobbZ** [comment]
This does sound OK for me.

Katrina Owen <notifications@github.com> schrieb am Fr., 22. Jan. 2016 22:25:

**Comment by losingkeys** [comment]
This seems fixed (there's a 'More Languages' button in the profile that hides some of the progressbars by default). Is there still more to do here?

**Comment by kytrinyx** [comment]
I think we'll still be tweaking the profile page, but this issue seems to be solved. Thanks!
