### ISSUE TITLE
Don't include "HelloWorld" in progress or statistics in general

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#2736]
Since the HelloWorld problem is merely an introduction to exercisms workflow, rather than a real problem, I don't think it should be included in any track related statistics.

For example I did CoffeeScript HelloWorld once and after fetching the first real problem of that track, I postponed the track and didn't continue until now and I might even wait much longer. But I do have this track in my progress area, showing a single submission. This does produce some unwanted (at least for me[1]) noise.

How are other users thinking about this aspect?

[1] CoffeScript included I have a list out of 13 tracks touched, and I'd be glad about some ways to reduce noice of such short experiments

**Comment by kytrinyx** [comment]
Yeah, let's remove hello-world from the progress bar.

@paradime do you want to take a look at this one? ("no" is a perfectly good answer, just asking since you're familiar with the feature).

**Comment by paradime** [comment]
Yea, I'll get working on them. It might take a week or so because I have to slightly refactor the objects that are being returned but I've got some ideas.

**Comment by kytrinyx** [comment]
OK, cool! If you want feedback on ideas, go ahead and open a "WIP" (work in progress) pull request.

**Comment by rebelwarrior** [comment]
I actually like the Hello World in the progress bar, in some languages getting Hello World to even work is not exactly easy. Try string interpolation in R. Or setting up the environment in R or Swift. It's not trivial for all languages. I do see how having it in the progress bar can be added noise, but what's the harm, doesn't it sort them to the bottom?

**Comment by NobbZ** [comment]
Since there is no (obvious) ordering, I don't think so.

Looking at my own profile I have `haskell` at the top today (which I did the last two days), `elixir` is second and `rust` beeing third. But it feels like ages, that I did the last thing in `rust` or `elixir`. `erlang` which I have done the most exercises in (absolute as well as relative) is somewhere in the middle, which I did just before taking on `haskell` again.

But I have to admit, this (un)wanted noise generated by the various `hello-world` exercises, might be obselete if #2735 gets implemented in any way.

This and the other ticket were opened by me, because I'm searching for ways to make my profile page readable again. All the bars ontop do drop the table to the second screenpage on my display.

**Comment by kytrinyx** [comment]
I'd actually prefer to get #2735 implemented than excluding hello world from stats.

**Comment by NobbZ** [comment]
Since `hello-world` is now treated as every other exercise as well and pop ups in the activity streams as well, I will close this.

If it is not special cased in the activity stream it doesn't need to be in the progress bar ;)

It is now just an exercise that happens to be first in most of the tracks by accident. Also when I have issued this, the progress bar area wasn't collapsible. The fact it is collapsible now, does also make this issue obselete.
