### ISSUE TITLE
Error page when trying to access profile page

### ISSUE THREAD

**Issue by DaveTorbeck** [exercism/exercism.io#2740]
![screen shot 2016-01-26 at 3 07 13 pm](https://cloud.githubusercontent.com/assets/5829885/12598323/82709e84-c43e-11e5-8649-c3c3775e880b.png)

**Comment by kytrinyx** [comment]
Thanks, looking now!

**Comment by kytrinyx** [comment]
Found it. Deploying now. Thanks for reporting it!

**Comment by DaveTorbeck** [comment]
No problem!  Thank you!
