### ISSUE TITLE
Implement persistent authentication via GitHub

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2741]
https://developer.github.com/guides/basics-of-authentication/#implementing-persistent-authentication

This should improve the experience significantly for people who use exercism a lot.

**Comment by tejasbubane** [comment]
I would like to take a stab at this.

**Comment by kytrinyx** [comment]
Excellent, thank you!

**Comment by tejasbubane** [comment]
Hi @kytrinyx. I went through the github guide today and did a first attempt at implementing it and I have a question regarding this.

So when we have persistent authentication, we should directly log in the user if the `session` contains the previous valid `access_token`. This means even if the user directly lands on any page on exercism he/she should be logged in. Would a [before filter](https://github.com/sinatra/sinatra#filters) be a good place for this? I see one already there https://github.com/exercism/exercism.io/blob/master/app/routes/core.rb#L28
On the other hand, I also fear that adding a `before filter` might break the flow at unexpected places.

**Comment by kytrinyx** [comment]
I'm pretty sure a before filter would be fine, so long as it's not going to throw people out if they are not logged in (it should only set whatever session values the app checks when deciding whether or not someone should have access or not).

**Comment by GustavoCaso** [comment]
@kytrinyx, @tejasbubane is someone working on this ?

**Comment by erinnachen** [comment]
@kytrinyx: @adriennedomingus and I are working on this.

**Comment by tejasbubane** [comment]
Sorry I completely forgot about this. Thanks @erinnachen for picking this up. 👍

**Comment by nickborromeo** [comment]
@erinnachen @adriennedomingus Looking to see if there is any update on the work that you had? Maybe you can share the work you have so far so people can pick it up from there?

@tejasbubane Also checking with you on any work that you have already done. Would not want the effort you already put in to be wasted 😄

**Comment by tejasbubane** [comment]
I have not worked on this.

**Comment by GustavoCaso** [comment]
So still open for working ?  @tejasbubane

**Comment by tejasbubane** [comment]
If @erinnachen @adriennedomingus have not worked on this, yes.

**Comment by GustavoCaso** [comment]
Ok, let's wait to see if they answer. Thanks @tejasbubane

**Comment by adriennedomingus** [comment]
@GustavoCaso @nickborromeo - @erinnachen and I worked on it a bit but didn't produce anything worth sharing. Feel free to pick it up!

**Comment by GustavoCaso** [comment]
Awesome thanks. I will work on it

**Comment by luismadrigal** [comment]
Is this still open?  Is anyone working on this?

**Comment by kytrinyx** [comment]
@luismadrigal Thanks for asking 🌷

It's still open, and I don't think anyone is working on it. That said we're only a few weeks away from launching a new prototype, so I wouldn't advise putting a lot of effort into it.

**Comment by luismadrigal** [comment]
Got it. I won't spend any time on this.  Is there a repo for the new prototype?

**Comment by kytrinyx** [comment]
@luismadrigal We're working in private at the moment. Once we are ready to start testing it, we'll be making it public under the same license as this one.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, since we're now that v2 is in beta, we're actively discouraging design changes to v1.

You can see v2 here: http://v2.exercism.io/
And provide feedback here: https://github.com/exercism/v2-feedback/blob/master/README.md

Thanks for the input everyone! 🌻

**Comment by GustavoCaso** [comment]
@kytrinyx is there a repo where to help with issues for the v2?

**Comment by kytrinyx** [comment]
The repo for the v2 codebase is open source (http://github.com/exercism/prototype), but we're not looking for contributions there just yet, as we don't have the bandwidth to manage them at the moment.

We are looking for feedback, however, and always value input, thoughts, and insight in the v2-feedback repository.

**Comment by GustavoCaso** [comment]
@kytrinyx awesome I will try the v2 and add some feedback. Also, I will wait for when contributors are need it for the codebase :)
