### ISSUE TITLE
`exercism status ID` doesn't work across computers

### ISSUE THREAD

**Issue by rebelwarrior** [exercism/exercism.io#2747]
If I work on different problems on different computers, I have to keep track of what I've done manually. 
`exercism status ID` should be able to check what problems I haven't submitted to the website yet it only tracks which I have submitted from that computer only. This makes working across computers a bit harder and there doesn't seem to be a reason for it, since the `status` command should be able to fetch from the website that information. 
An alternative could be to add a `--remote` option that forces a check to the website, this would allow both the local only command and the remote one to co-exist.

**Comment by kytrinyx** [comment]
I actually thought that `status` did check remotely, but it might not check which things you have fetched/not submitted remotely. (I don't even remember if we track that. We might :), we definitely can).

/cc @exercism/cli-committers

**Comment by Tonkpils** [comment]
I can definitely check this out over the weekend unless someone else gets to it. Been a bit of a busy week with work + teaching.

**Comment by rebelwarrior** [comment]
Thank you Leo thank you Katrina. Btw loved your ruby rogues podcast, Katrina.

**Comment by amalrik** [comment]
@rebelwarrior is this issue still happening?

**Comment by rebelwarrior** [comment]
Yes and no. Most recently submitted works. Which ones are pending no. 

    On Monday, May 16, 2016 2:09 PM, Amalrik Maia <notifications@github.com> wrote:
 

 @rebelwarrior is this issue still happening? —

**Comment by Tonkpils** [comment]
Apologies for not getting back to this earlier, I will try to get to checking the issue this week

**Comment by nickborromeo** [comment]
@rebelwarrior @Tonkpils Looking at the code, I do not think it is specific to machines, because status makes an API call

```go
...
// Status is a command that allows a user to view their progress in a given
// language track.
func Status(ctx *cli.Context) error {
	c, err := config.New(ctx.GlobalString("config"))
	if err != nil {
		log.Fatal(err)
	}
	args := ctx.Args()

	if len(args) != 1 {
		fmt.Fprintf(os.Stderr, "Usage: exercism status TRACK_ID\n")
		os.Exit(1)
	}

	if !c.IsAuthenticated() {
		log.Fatal(msgPleaseAuthenticate)
	}

	client := api.NewClient(c)
	trackID := args[0]
	status, err := client.Status(trackID)
...
```

```go

// Status sends a request to exercism to fetch the user's
// completion status for the given language track.
func (c *Client) Status(trackID string) (*StatusInfo, error) {
	url := fmt.Sprintf("%s/api/v1/tracks/%s/status?key=%s", c.APIHost, trackID, c.APIKey)

	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}
```

Wanted to check if we can close this issue after either of you confirms that this is no longer a problem 😄

**Comment by rebelwarrior** [comment]
I'd have to check in multiple computers, but seems fixed on the one I'm working on.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close the issue... @rebelwarrior if you do see it happening again, would you mind reopening this?
