### ISSUE TITLE
archived exercises table on profile page has a very bad layout.

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#2748]
currently, we have a table which does look like on the screenshot below:

![archived-exercises-table-current-bad](https://cloud.githubusercontent.com/assets/58951/12788087/800aafc6-ca98-11e5-92fb-c31e508c934c.png)

But as far as I can remember, the layout has been different in the early days. Columns were swapped (language left, exercises right) and the exercises were a comma separated list. Which made the table **much** shorter and concise.

**Comment by kytrinyx** [comment]
Yeah, agreed. We could use some work on the design of the profile page. Swapping those would be a good first step.

**Comment by mhelmetag** [comment]
@NobbZ and @kytrinyx , thoughts on the new layout? Could we close?

**Comment by NobbZ** [comment]
It is much better now, only thing that looks odd is, that there is a space
before the comma, so it looks like this: `Bob
<http://exercism.io/exercises/3254942bf6d84530bb94f04f425e02e2>, Rna
Transcription
<http://exercism.io/exercises/8cad2df3f3de4770bb11aa8ea6c0d3bb>` where the
space belongs to the link of Bob. The last entry in each list, does not
have this additional space at the end.

Max Helmetag <notifications@github.com> schrieb am Di., 8. März 2016 um
21:28 Uhr:

**Comment by mhelmetag** [comment]
I thinks that's because of the spacing for `<a>` tags but I can look into this.

**Comment by kytrinyx** [comment]
I'll close this. If either of you want to submit the spacing problem as a separate issue go for it.
