### ISSUE TITLE
Unable to login with Github

### ISSUE THREAD

**Issue by rcyep87** [exercism/exercism.io#2749]
It looks like it authenticates but then takes me back to the main page for exercism and it still says I need to login with Github. I thought it might be an error and try to access my account but when I click a link regarding my account, it says I need to login with Github. I've cleared my cache and am trying this on Google Chrome and Safari.

**Comment by kytrinyx** [comment]
Yeah, that seems like something to do with cookies. Is there any way that firewalls/proxies could interfere with this in some way?

**Comment by rcyep87** [comment]
Interesting you bring that up. I got it working. Sorry for the trouble :)

**Comment by kytrinyx** [comment]
Oh, yay! What did you do to make it work?

**Comment by rcyep87** [comment]
Strangely my VPN was affecting it.

Thanks,
Ryan

**Comment by kytrinyx** [comment]
Good to know, thanks!
