### ISSUE TITLE
Update ACLs immediately for new track mentors

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2751]
See PR #2729
/cc @mhelmetag

On the account page we now have a section to let track mentors make other users into track mentors. We have a cron job running every hour that makes sure mentors have access to all the exercises in the tracks that they're mentors for.

When we give someone track mentor status, we should add all their ACLs immediately.

**Comment by mhelmetag** [comment]
I was thinking of adding an `after_save` callback on User to migrate the acls if they change. I was going to follow the logic that already exists in the rake task https://github.com/mhelmetag/exercism.io/blob/master/lib/tasks/data.rake#L151-L152.

Decent idea?

**Comment by kytrinyx** [comment]
Yeah, I think it's fine to use the same logic as in the rake task. I'm a bit uneasy about keeping it in a callback though. Let's call it explicitly for now and see how it goes.

**Comment by mhelmetag** [comment]
Awesome. Figured out a pretty weird bug in `ACL.authorize`. Basically you can't really `rescue` an ActiveRecord transaction and execute another transaction without a rollback. Postgres will throw errors like `ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block`. So I just refactored `ACL.authorize` a bit.

PR soon. Just writing some tests.

**Comment by kytrinyx** [comment]
huh. Good to know!

**Comment by mhelmetag** [comment]
Actually... even weirder... it seems like it only doesn't work in certain instances because this works https://github.com/mhelmetag/exercism.io/blob/master/lib/exercism/submission.rb#L66-L70

I don't really understand haha. Super strange.

**Comment by kytrinyx** [comment]
Oh, right. I think I wrote that. Strange.

**Comment by mhelmetag** [comment]
Today I learned that nesting transactions inside ActiveRecord callbacks makes weird things happen.

**Comment by mhelmetag** [comment]
Awesomesauce!
