### ISSUE TITLE
dashboard: fix notification for "like"

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2753]
Right now if someone likes your iteration, you'll see a notification on your dashboard that says that someone commented. Then you go to your exercise and get all disappointed because there's no comment. We should fix that.

**Comment by mhelmetag** [comment]
There is some knowledge of what the notification is `regarding` (https://github.com/exercism/exercism.io/blob/master/app/routes/submissions.rb#L36) and `'like'` is being passed around... Curious...

**Comment by mhelmetag** [comment]
Welp... I'll take a look at this over the long weekend! Seems like fun.

**Comment by mhelmetag** [comment]
Hmmm... I don't see this happening on master...

<img width="1138" alt="screen shot 2016-02-11 at 9 43 11 pm" src="https://cloud.githubusercontent.com/assets/8609429/12999854/831ede1e-d108-11e5-94f7-fa020f9f230b.png">

@kytrinyx , any tips for recreating this bug outside of production?

I'm going to try to get a friend to like a few of my submissions in production...

**Comment by mhelmetag** [comment]
Do you mean this part of the dashboard?
<img width="1365" alt="screen shot 2016-02-11 at 10 02 36 pm" src="https://cloud.githubusercontent.com/assets/8609429/13000118/50058d54-d10b-11e5-8aba-593ff413c676.png">

I see the correct distinction between comments and likes on the notifications page:
<img width="1138" alt="screen shot 2016-02-11 at 9 43 11 pm" src="https://cloud.githubusercontent.com/assets/8609429/13000131/6766cf26-d10b-11e5-9642-7093badeb6d0.png">

@kytrinyx , do you want to make the dashboard notifications section similar to the notifications page?

**Comment by kytrinyx** [comment]
Yeah, I think it would be fine to make the dashboard section similar to the notifications page (even identical, if that is easier)... just that it should only have stuff relevant to the code that you wrote, not anyone else's code.

**Comment by kytrinyx** [comment]
Also: yes, that's the part of the dashboard that I meant. Thanks!

**Comment by mhelmetag** [comment]
Awesome! Thanks for clarifying :)

**Comment by abhishekbose87** [comment]
Let me submit a PR for this .. 

I am planning to have shortened texts using icons for(comments and thumbsup) in the notification section on dashboard page.
eg. (in actual code, I will use fa icons).
ryan :+1: Hamming(Ruby)
ryan :speech_balloon: Hamming(Ruby)

What do you think ?

**Comment by kytrinyx** [comment]
Yeah, fa icons would be excellent, @abhishekbose87. Thanks!

**Comment by kytrinyx** [comment]
fixed in dc1443ea1c72f0d6f13918ba322e24fef6e581dc
