### ISSUE TITLE
 2016/02/08 10:32:36 an internal server error was received.

### ISSUE THREAD

**Issue by jonathan2224** [exercism/exercism.io#2755]
**** Debug Information ****

Exercism CLI Version: 2.2.4

Exercism CLI Latest Release: 2.2.4

OS/Architecture: windows/amd64

Build OS/Architecture windows/amd64

Home Dir: C:\Users\jmorrel

Config file: C:\Users\jmorrel\.exercism.json

API Key: *** 

Exercises Directory: C:\Users\jmorrel\exercism

Testing API endpoints reachability

	* API: http://exercism.io [connected] 140ms

	* GitHub API: https://api.github.com/ [connected] 267ms

	* XAPI: http://x.exercism.io [connected] 304ms

I have been unable to fetch java exercises this morning, though they do show up on my exercism dashboard.  My first attempt was with CLI version 2.2.3 but I have since then updated to the new release which has not fixed the problem.

**Comment by kytrinyx** [comment]
I'm unable to reproduce the problem, so I suspect that there's something in the data specific to your account that is causing this. I'll look at this today and see what I can come up with.

**Comment by kytrinyx** [comment]
Found it. There's an exercise that has a jar file in it--I've removed it for now, so you should be able to fetch.

**Comment by jonathan2224** [comment]
Thank you, it is working now.
