### ISSUE TITLE
Using a CDN for our client side libraries (mostly JS)

### ISSUE THREAD

**Issue by mhelmetag** [exercism/exercism.io#2757]
Am I just being weird here?

I feel like there's something wrong with the code percentage for exercism. The app is mostly Ruby but github says a lot of it is JS but most of the larger files are jQuery, Bootstrap and other third party libraries. Why would we host these locally? Couldn't we leverage a public CDN or a private one like Cloudfront (or something)?

Curious to hear the benefits and burdens of using a CDN for our client side libraries.

**Comment by tejasbubane** [comment]
Instead of going for CDN, I think we can reduce the assets consumption using `gzip` compression. [It reduces the assets size by more than half of the original](http://nginx.org/en/docs/http/ngx_http_gzip_module.html). On my projects, I usually just enable it with nginx and it takes care of the rest. Since exercism is on heroku I guess, I will have to search a bit on how to do that.

**Comment by tejasbubane** [comment]
And one more thing, the assets are served currently `application.css` and `app.js` do not use [fingerprinting](http://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark). Although `application.css` uses some kind of param `t`.

![exercism-1](https://cloud.githubusercontent.com/assets/980783/13025666/1ef7c884-d233-11e5-9cfc-5b174bfbadd2.jpg)
![exercism-2](https://cloud.githubusercontent.com/assets/980783/13025668/24b7253a-d233-11e5-8042-a064a2d2f133.jpg)

**Comment by mhelmetag** [comment]
Compression sounds cool. Having some type of asset pipeline would be nice. Maybe there is some type of one existing already (the `t` param that you mentioned).

**Comment by kytrinyx** [comment]
I would absolutely love to have someone look at the low-hanging fruit for the assets.

I think the `t` is a cheap-o workaround based on the last modified date.

All of the frontend is completely janky (my focus has been on figuring out what the site is about, and experimenting with features, etc).

**Comment by mhelmetag** [comment]
One more thing that I'm curious about... why are `frontend/` and `client/` two different things?

**Comment by kytrinyx** [comment]
Legacy, mostly. Two different people started two different efforts to clean up the frontend, as far as I can recall.

**Comment by kytrinyx** [comment]
FYI I'll be working with @aarti + colleagues to integrate against a CDN. gzip etc would also be good. Using publicly hosted javascript for the third party stuff would also be good.

**Comment by mhelmetag** [comment]
^^ So exciting :D

**Comment by aarti** [comment]
Looking forward to this, :heart: exercism

**Comment by kytrinyx** [comment]
Done.

**Comment by mhelmetag** [comment]
Sweet!!!
