### ISSUE TITLE
User page: sort languages by progress percentage

### ISSUE THREAD

**Issue by daveyarwood** [exercism/exercism.io#2758]
I think it might be more visually appealing to show each users' languages with a higher completion percentage higher up in the list.

This might give an idea of the languages in which the user is most active / interested.

Here's a mockup of what I'm proposing:

<img width="743" alt="screen shot 2016-02-13 at 11 34 20 am" src="https://cloud.githubusercontent.com/assets/4909079/13028730/c62c9906-d245-11e5-86d5-f537744be7e5.png">

Looks like it would just be a simple change to this view partial: https://github.com/exercism/exercism.io/blob/master/app/views/user/_exercise_progress.erb

I was going to work on a PR, but I don't have time at the moment to get the dev environment set up, and I'm not sure yet if this is something you guys actually want :)

**Comment by kytrinyx** [comment]
I think that could be good. I would probably want to put 100% tracks on the bottom, though.

Did you see the other issues about the progress bar? There were some good requests/suggestions.

#2735, #2734

**Comment by daveyarwood** [comment]
I did - those are good suggestions, although personally, I prefer the current system of showing the whole list.

I do like the idea of separating the progress bars out into "In Progress" (< 100%) and "Completed" (100%)

**Comment by kytrinyx** [comment]
The problem with showing all of them is that people with a bunch of languages have to scroll really far to see the relevant lists.

**Comment by daveyarwood** [comment]
That's a good point. Maybe a good compromise would be to cap it at say, 5 languages, and have a "show more" button if the user has more than that?

Someone mentioned that in one of the other 2 issues, but the idea was to cap it at 1 language. I think having a small handful (perhaps the 5 "most complete" languages) would give a nice snapshot of the languages in which the user is most active/interested.

**Comment by kytrinyx** [comment]
Yeah, I think capping it is the way to go. How about capping it at 3, and saying "see all {n}" or something?

I don't know if we should have a completely separate section for the completed tracks, or if they should just be sorted to the bottom. We can try one way and see what people say.

**Comment by kytrinyx** [comment]
Thanks so much for weighing in on this, everyone. We're going to be removing the progress bars and trying a different tactic—we'll see how that works out. See https://github.com/exercism/exercism.io/pull/3117 for the final result (still in the works).
