### ISSUE TITLE
Markdown parser doesn't respect list syntax if blank line is missing before the first list item

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2759]
Per the CommonMarkdown spec, we should be allowing lists to interrupt paragraphs even if there is no blank line before it.

http://spec.commonmark.org/0.24/#example-259

GitHub handles it (below: first the markdown, then the rendered output).

```
Example list.
* one
* two
* three
```

Example list.
* one
* two
* three

See https://github.com/exercism/xcpp/pull/66 and https://github.com/exercism/xcpp/pull/67

Thanks @toolness for catching this.

**Comment by kytrinyx** [comment]
I added a skipped test for it. The expected output might have different whitespace than what actually ends up there once it's fixed, but it should provide a starting point.

**Comment by toolness** [comment]
Oh nice! Thanks @kytrinyx, I will try to take a look at this thing soon--but if anyone else is really excited about fixing this issue, feel free to take it. (Just mention it on this issue please so we don't duplicate work.)

**Comment by kytrinyx** [comment]
@mfrost heads up on this one, in case you've got a hankering for fixing more markdown issues.

**Comment by mhelmetag** [comment]
So I was curious and looked into this a bit... It seems like it has to do with red carpet vs our implementation of the gem...


Here's our implementation:
```
[17] pry(main)> markdown = Redcarpet::Markdown.new(Redcarpet::Render::XHTML, options)
=> #<Redcarpet::Markdown:0x007fd464e1b2a8 @renderer=#<Redcarpet::Render::XHTML:0x007fd464e1b370>>
[18] pry(main)> content1 = "test\n\n* test"
=> "test\n\n* test"
[19] pry(main)> content2 = "test\n* test"
=> "test\n* test"
[20] pry(main)> markdown.render(content1)
=> "<p>test</p>\n\n<ul>\n<li>test</li>\n</ul>\n"
[21] pry(main)> markdown.render(content2)
=> "<p>test\n* test</p>\n"
```

Here's vanilla red carpet (from what I can tell):
```
[14] pry(main)> markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
=> #<Redcarpet::Markdown:0x007fd464fccc50 @renderer=#<Redcarpet::Render::HTML:0x007fd464fccca0>>
[15] pry(main)> markdown.render(content1)
=> "<p>test</p>\n\n<ul>\n<li>test</li>\n</ul>\n"
[16] pry(main)> markdown.render(content2)
=> "<p>test\n* test</p>\n"
```

If anyone's curious where the options and choice of XHTML come from:
https://github.com/exercism/exercism.io/blob/master/lib/exercism/markdown.rb#L36-L37

Seems like both the vanilla and our implementation trip up on the same thing...

**Comment by mhelmetag** [comment]
I got a patch for this. It's just a preprocess that adds a newline for lists that aren't split by newlines already so that they work with the current redcarpet setup.

Lists with newline:
*Text:*
<img width="336" alt="screen shot 2016-02-20 at 8 59 48 pm" src="https://cloud.githubusercontent.com/assets/8609429/13201044/f520822a-d814-11e5-951b-c9e272bb801f.png">

*Markdown:*
<img width="298" alt="screen shot 2016-02-20 at 8 59 53 pm" src="https://cloud.githubusercontent.com/assets/8609429/13201045/f98c24a4-d814-11e5-8ee5-74c2984714f9.png">

Lists without newline:
*Text:*
<img width="278" alt="screen shot 2016-02-20 at 8 59 58 pm" src="https://cloud.githubusercontent.com/assets/8609429/13201046/fe3b9638-d814-11e5-96ca-db25d9066082.png">

*Markdown:*
<img width="312" alt="screen shot 2016-02-20 at 9 00 02 pm" src="https://cloud.githubusercontent.com/assets/8609429/13201047/01ef3474-d815-11e5-8b0b-1234e86e73fa.png">

Thoughts?

**Comment by kytrinyx** [comment]
Preprocess works for me. I wonder if we should be inheriting from HTML rather than XHTML. I don't know :/

**Comment by mhelmetag** [comment]
I tried `Redcarpet::Render::HTML` vs `Redcarpet::Render::XHTML` and didn't see any change with the test text that I was using but... I honestly didn't read much about their differences besides the available options/feature flags.

**Comment by kytrinyx** [comment]
/shrug :) I have no idea either. It's not at the top of my list of important things to figure out in the near future. I think it's fine as it is for now.

**Comment by mhelmetag** [comment]
Based on reading through this issue on redcarpet (https://github.com/vmg/redcarpet/issues/429), redcarpet seems to diverge from CommonMark spec in more than this instance and they might not make that much change... If we really want to be "up to spec", we could use https://github.com/gjtorikian/commonmarker (which is a wrapper for CommonMark).

**Comment by kytrinyx** [comment]
That's a good point. I'm going to close this as fixed, and open an issue suggesting that we use commonmarker.

**Comment by mhelmetag** [comment]
Sounds good :+1:

**Comment by tejasbubane** [comment]
Is this deployed? I ran across this while writing a comment today

![screen shot 2016-02-25 at 4 31 58 pm](https://cloud.githubusercontent.com/assets/980783/13317867/68d73b02-dbdd-11e5-83fd-389accfd1b9b.png)

![screen shot 2016-02-25 at 4 32 09 pm](https://cloud.githubusercontent.com/assets/980783/13317872/713794cc-dbdd-11e5-8a1a-c87b6b15d62f.png)

**Comment by mhelmetag** [comment]
Agh... My regex wasn't as good as I thought... Not exactly sure why...

Good catch. Looks like some tweaking is needed.

**Comment by tejasbubane** [comment]
Ya right. I have some trailing spaces and your regex does not consider spaces at some places. I was just trying it out on [rubular.com](http://rubular.com/). Here is something which will take care of trailing spaces:

```
^\s*\w+\s*\n(?=[*|-]\s*\w+)
```

Switching to commonmarker would be a permanent and good fix for such issues.

**Comment by mhelmetag** [comment]
Sounds about right. I think I just got too excited that it worked for one case and forgot about testing for a few other cases before pushing. And the test written happened to be fore that one case that it worked for... Ah well... Good learning lesson for me.

Sorry about that!

Currently, I'm trying to get our syntax highlighting and @ mentions ported over to commonmarker.

**Comment by tejasbubane** [comment]
Nothing to be sorry about 😊 Regex is really hard. 
Glad that you are already working on the porting over to commonmarker.

**Comment by kytrinyx** [comment]
Reopening until we either tweak the regex or port over to commonmarker.
