### ISSUE TITLE
Idea: when person gets to the end of a track - suggest they contribute new exercises

### ISSUE THREAD

**Issue by verdammelt** [exercism/exercism.io#2762]
I am the maintainer of the Common Lisp track and we have around 30 exercises. Just the other day one person has submitted for this last exercise. I thought it would be cool if there could be a way to tell the person that they are at the (current) end of the track and it would be super great if they contributed more exercises.

**Comment by kytrinyx** [comment]
I think it would be great if @rikki- could submit a comment to them that suggests this, linking to a page that has the most up-to-date information about how to do this.

I'm hoping to use https://github.com/exercism/x-api/issues/94 to implement a "contribute" page for each track on exercism.io (maybe /languages/:track_id/contribute) that we could link to. It would have the list of exercises to implement, along with links to all the existing implementations in other languages as well as to the relevant metadata.

**Comment by verdammelt** [comment]
It would be pretty cool if there was a way to compute the list of problems yet to be written. Then it would be easy to point people to it and a link to the github repo for that track.

**Comment by kytrinyx** [comment]
Yeah, it's pretty straight-forward. It's been on my TODO list for a while, but that list is kind of out of control right now.

**Comment by GustavoCaso** [comment]
@kytrinyx Is anyone helping with this one ?

**Comment by kytrinyx** [comment]
No, not yet. We do have the list of problems yet to be written: http://x.exercism.io/v3/tracks/java/todo

**Comment by GustavoCaso** [comment]
Ok do we have an design for the page to show when they get to the end of the track ?

**Comment by kytrinyx** [comment]
No, there's no design.

I was thinking of making it a page under /languages/:track_id, for example
`GET /languages/:track_id/contribute/port-exercises`

It would use the information from the todo endpoint I listed to display a list of available problems, along with whatever useful information we can give them (README, canonical test data, if it exists, links to all of the existing implementations)

This page would not be personalized, however I think that it would be interesting later to build on this and add personalized things to their dashboard as described here: https://github.com/exercism/todo/issues/15

**Comment by GustavoCaso** [comment]
@kytrinyx Ok great I will start working on this feature to ! :+1:

**Comment by GustavoCaso** [comment]
@kytrinyx do we have and endpoint to get the content of the readme from the `x-common` repository, I'm doing the `contribute` page, but I think showing the actual readme, and a couple of links would be better, than just links

**Comment by GustavoCaso** [comment]
@kytrinyx I opened PR in `x-api` that provide the `README` https://github.com/exercism/x-api/pull/105

**Comment by kytrinyx** [comment]
That PR is merged and the API has been deployed.

**Comment by GustavoCaso** [comment]
@kytrinyx I think this one can be close

**Comment by kytrinyx** [comment]
Yepp, I think that eventually we'll need help from a ux person / designer to think through where things should really live, but for now we've got it. Thanks, @GustavoCaso for working on it.
