### ISSUE TITLE
Inbox: sum of unread problem counts doesn't equal unread count for language?

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism.io#2764]
This has happened to me a few times now, but I haven't been able to figure out exactly under what circumstances it occurs. In all cases it seems to be happening for the Ruby track.

As an example, I'll have 5 unread items in Hamming and 3 unread items in Anagram. One would think this means 8 unread items total in Ruby, but no! The counter says there are 7!

I click through the Hamming items one by one, and both the Hamming and Ruby counters decrease.

I also click through two Anagram items, which decrease both counters as well.

So now I'm left with one Anagram item unread, but zero Ruby items unread. I'd expect that the Ruby counter is 1 instead of 0 right now.

Screenshot of my current inbox as it stands now:

http://imgur.com/6of7Pqg

Maybe my unread count for the Ruby track is desynced? And it's going to -1 when I read all submissions?

I'll leave that last one submission unread for now if it helps to diagnose the issue.

(By the way why do I see Difference of Squares, with 0 submissions? I shouldn't see Difference of Squares since I've not submitted a solution to that problem)

**Comment by petertseng** [comment]
> I'll leave that last one submission unread for now if it helps to diagnose the issue.

Some new submissions came in and I was curious about the Anagram submission, so I went and read it. My current unread submission is a Hamming submission. I'm still in the same state (there's 1 Ruby Hamming unread, but zero Ruby unread)

**Comment by kytrinyx** [comment]
So weird. Definitely a bug, but not sure what it's about.

**Comment by petertseng** [comment]
I'm currently not in this state anymore. Related: The 0-submission Difference of Squares has disappeared. I suspect the two are related.

**Comment by kytrinyx** [comment]
I suspect that this could have something to do with someone submitting a comment, making this unread, and then deleting the comment again. I've been thinking about how to rewrite this to be a append-only immutable list of events that happen to an iteration so that we can cleanly recalculate current state by replaying history, but I've got a bunch of things going on, so I don't think I'll be able to tackle it for a while.

**Comment by petertseng** [comment]
I can't get back into this state. I hate to leave a bug report with no reproduction in the queue, so I'll close it for now. Always OK to reopen if someone gets back into this state, of course.
