### ISSUE TITLE
Getting timeout errors when trying to submit a file

### ISSUE THREAD

**Issue by edelpero** [exercism/exercism.io#2765]
Hi I'm getting timeout errors trying to submit a file. I've already check the help guides but I had not luck. I'm not behind a firewall.

 This is the info I've got using the exercism cli debug command.

```
**** Debug Information ****
Exercism CLI Version: 2.2.4
Exercism CLI Latest Release: 2.2.4
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/edelpero
Config file: /Users/edelpero/.exercism.json
Exercises Directory: /Users/edelpero/exercism
Testing API endpoints reachability
	* GitHub API: https://api.github.com/ [connected] 791.067657ms
	* XAPI: http://x.exercism.io [connected] 927.690139ms
	* API: http://exercism.io [Get http://exercism.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)] 20.0029312s
```

Please, let me know if you need more information. Thanks in advance.

**Comment by tejasbubane** [comment]
Seems similar to https://github.com/exercism/cli/issues/202

**Comment by kytrinyx** [comment]
Darn, yeah it seems like the timeout is too low. I think we need to add a flag to the CLI that lets people extend the timeout just to see if it helps. /cc @Tonkpils @lcowell what do you think?

**Comment by Tonkpils** [comment]
I don't think we actually have timeouts set for the API calls so this must be something completely unrelated but I can't say for sure until I look at the code. ill take a look at it tonight

**Comment by kytrinyx** [comment]
Is there a default timeout?

**Comment by lcowell** [comment]
What I found is that there is no timeout (see `https://golang.org/src/net/dial.go`). Looks like we've specified a timeout in a couple of places in the cli: `debug.go` and `upgrade.go`. This explains why the debug command times out.

**Comment by lcowell** [comment]
@edelpero the `debug` command and `submit` command work differently. Could you paste the output you get when you attempt to submit?

**Comment by Tonkpils** [comment]
What I do find interesting is why the API itself did timeout...seems odd the other two work but not that one. Are we monitoring these kind of timeouts on the exercism app?

**Comment by kytrinyx** [comment]
@Tonkpils that's actually a really good question. I'm monitoring exceptions, but I don't have logging for stuff like this.

**Comment by lcowell** [comment]
That kind of variability in response times seems like it could be a connection/packet loss issue. If that's the scenario, each time the `debug` command is run would result in different output. I think we would need more information from @edelpero to draw any conclusions.

**Comment by edelpero** [comment]
@lcowell everything is working fine now. Sadly I didn't copied the error message I got when I ran the `submit` command.

Anyway, I tried this with two different internet connections and got the same error when running the `debug` command.

**Comment by kytrinyx** [comment]
I'm going to close this for now, but if it happens again, please reopen it or submit a new issue! It would be lovely to get to the bottom of this, or figure out how to provide better information for debugging.
