### ISSUE TITLE
"mark all as read" can be unclickable

### ISSUE THREAD

**Issue by Trevoke** [exercism/exercism.io#2767]
In at least two uses cases, the "Mark all as read" button is unclickable:

- Page has browser zoom active
- Browser window is too narrow

A cursory inspection of the elements and the styles reveals that the `ul li.alert-row` can cover the button, thereby stealing the clicks.

**Comment by kytrinyx** [comment]
Thanks for reporting this.

**Comment by karloxyz** [comment]
@kytrinyx I'd like to work on this. Where could I see the "Mark all as read" button? Thanks!

**Comment by mhelmetag** [comment]
https://github.com/exercism/exercism.io/blob/master/app/views/notifications/index.erb

You'll have to seed some fake notifications to get it to show up locally which can kinda be tricky.

**Comment by kytrinyx** [comment]
I wrote a couple of rake tasks to help you generate data (run the seed data, then assume one of the user identities in the dropdown, and use their username instead of alice for the rake tasks below).

```
$ rake dev:seed:iterations username="alice" 
$ rake dev:seed:notifications username="alice"
```

**Comment by mhelmetag** [comment]
Oh perfect! That's nice to know!

**Comment by kytrinyx** [comment]
@mhelmetag in general I find it pretty straight forward to write great big hacky rake tasks for stuff like this, so if you ever come across other stuff that's painful to test on the front-end just holler, and we can work out the details of how to make it not-painful!

**Comment by mhelmetag** [comment]
Haha okay! I'll definitely keep that in mind. Good tip! I guess I just would be conflicted about whether that data could be pre-populated by seeds or optionally generated by a rake task.

**Comment by kytrinyx** [comment]
Probably pre-populated by seeds, to be honest, but I'd have to sit down and re-think the seed generation. It's been a long time since I gave it any attention.
