### ISSUE TITLE
Refactor markdown handling to use commonmark

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2768]
Markdown is not specified unambiguously, and we've had a lot of bugs and issues related to things that are a bit fuzzy, and where redcarpet handles it in one way, but people are used to it being handled differently on GitHub.

The markdown stuff has grown a bit over time, and we might also be able to simplify it.

It might be worth doing a rewrite using commonmark instead of redcarpet. See discussion in https://github.com/exercism/exercism.io/issues/2759

**Comment by tejasbubane** [comment]
For reference if anyone wants to have a stab

* The commonmarker gem: https://github.com/gjtorikian/commonmarker
* Why not to use redcarpet: https://github.com/vmg/redcarpet/issues/429

**Comment by kytrinyx** [comment]
Thanks for the references, @tejasbubane, that's very helpful.

**Comment by abhishekbose87** [comment]
@kytrinyx I am taking this up if no one else has started work on it already
@tejasbubane Thanks for the links :+1:

**Comment by abhishekbose87** [comment]
Hi @mhelmetag, are you working on this change ?

**Comment by mhelmetag** [comment]
@abhishekbose87, I was toying around with it and had some ideas but you're more than welcome to take it. I have a few other issues on my plate anyways.

**Comment by abhishekbose87** [comment]
@mhelmetag Cool, let me work on this then and you could review it 😊

**Comment by mhelmetag** [comment]
Sure thing! I look forward to the PR. Let me know if you need any ideas to getting the current @ mentions and syntax highlighting working with the renderer. That was what I was toying with.

**Comment by mhelmetag** [comment]
@kytrinyx , what heroku buildpack do you use when you deploy? Is it just stock heroku (like it gets picked up automatically when you `git push heroku master`) or do you specify (like `heroku create --buildpack https://github.com/heroku/heroku-buildpack-ruby.git`)?

**Comment by kytrinyx** [comment]
Just stock heroku, at the moment. I had a custom one, but it got out of date, and I didn't have the mental overhead to deal with it, so I just ripped it out and started committing the generated files.

**Comment by mhelmetag** [comment]
@kytrinyx , I think this can be closed now that we're not going down the commonmark path. Let me know after you deploy that small redcarpet config change.
