### ISSUE TITLE
Go Track: seeking 5 volunteers to help review the "Leap Year" exercise for one month.

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2772]
Are you new(ish) to Go? Would you be interested doing a 30-day experiment that is likely to teach you a huge amount about Go conventions and style?

I'm looking for 5 (or so) people to come by and provide feedback on 1-3 exercises every couple of days.

**I will personally walk you through how to give feedback on this exercise, if you feel that you don't know enough to jump in on your own.**  There's a lot to say about the Leap exercise; there are several interesting approaches, and many opportunities to talk about Go style, features, conventions, and tools.

In the past 30 days, over 100 different people have submitted a total of almost 300 iterations of Leap in Go. http://exercism.io/stats/go

I would love to make sure that everyone gets good feedback on the very first exercise that they submit in Go.

Right now mostly rikki- (http://exercism.io/rikki) and I are giving feedback on Leap, and this means that if I get busy with other things for a couple of days, then people only get the automated feedback from rikki-. This leaves me with a huge backlog when I get back, and it's hard to keep up. Feedback is more valuable the earlier you receive it. If it takes several days to get feedback you may never come back to read it.

If you are experienced with Go, then I'd love to have you as well, of course. My assumption is that this will be more valuable to people who are newer to the language, but that assumption could be completely wrong. If you don't need a personal guide, I'll send you a summary of the typical approaches and issues that I see as a starting point for giving feedback.

If you're interested in being a part of this 30 day experiment, then please email me (my address is on my GitHub profile).

**Comment by toolness** [comment]
This sounds cool! I've basically never used Go, so I'm interested in participating in the experiment.

**Comment by kytrinyx** [comment]
@toolness Yay! Send me an email and I'll kick this off. Also: First step would be to submit `hello-world` and `leap` yourself, just to get everything wired up and get a taste of the language.

**Comment by wobh** [comment]
What month? For me, March is out, possibly April too, but I could probably be persuaded to do this in the summer.

**Comment by archeious** [comment]
I an very intrigued.  I want to level up my go-ness and I would like to improve my collaborative skills.  My projects to date are almost exclusively solo self made projects.

**Comment by jgsqware** [comment]
I'm interested to be part of the experiment ! Great idea.

**Comment by timblair** [comment]
@kytrinyx: I'd be happy to help out.

**Comment by kytrinyx** [comment]
@wobh next 30 days starting now. I'll probably do this again, though.

@archeious I've got you on the list.
@timblair @jgsqware Excellent! would you send me an email? I'll email you the next steps.

**Comment by mem** [comment]
Late to the party, but I'd be happy to help next time

**Comment by raul782** [comment]
@kytrinyx would love to be part of the experiment if it's still open.

**Comment by kytrinyx** [comment]
@mem @raul782 send me an email and I'll send you the information. You're welcome to join now (the 30 day thing can start any time).

**Comment by kytrinyx** [comment]
This was a great experiment, thanks to everyone who participated. I wrote a bit about what we learned here: http://tinyletter.com/exercism/letters/how-do-we-get-people-to-give-more-feedback-on-exercism
