### ISSUE TITLE
Can see submissions for Common Lisp Hamming although I've never submitted solutions

### ISSUE THREAD

**Issue by mgmatola** [exercism/exercism.io#2773]
Starting this afternoon, I can now see submissions for the Common Lisp Hamming exercise, although I've never submitted any solutions for any Common Lisp exercises. (I've submitted only JavaScript and EcmaScript.)

**Comment by kytrinyx** [comment]
Damn. My bad, I ran a script yesterday and clearly got it wrong. I'll fix this now.

**Comment by kytrinyx** [comment]
OK, I've cleared away the accidental access; I think I still have a problem with some of the point-mutation / hamming stuff, and will sit down and sort it out carefully later today.

**Comment by mgmatola** [comment]
FWIW, my listings are now correct.

**Comment by kytrinyx** [comment]
OK, cool, thanks!

**Comment by verdammelt** [comment]
Any idea if this was limited to pulling in Common Lisp? and if so why? (other than startlingly good taste...)

**Comment by kytrinyx** [comment]
Nope, it was _all_ the tracks.

**Comment by verdammelt** [comment]
Whoopsie!

Glad you fixed it.
