### ISSUE TITLE
Cannot fetch anything

### ISSUE THREAD

**Issue by moccalotto** [exercism/exercism.io#2777]
$ exercism fetch ruby

Not Submitted:     1 problem
ruby (Hello World) /Users/khansen/exercism/ruby/hello-world

unchanged: 1, updated: 0, new: 0

$ exercism fetch elixir

Not Submitted:       1 problem
elixir (Hello World) /Users/khansen/exercism/elixir/hello-world

unchanged: 1, updated: 0, new: 0

$ exercism --verbose fetch elixir
verbose logging enabled
Request GET http://x.exercism.io/v2/exercises/elixir?key=XXXXXXX
Response StatusCode=200
Response Body
{"problems":[{"id":"elixir/hello-world","track_id":"elixir","language":"elixir","slug":"hello-world","name":"Hello World","files":{"hello_world.exs":"defmodule HelloWorld do\n  @moduledoc \"\"\"\n  Elixir counts the number of arguments as part of the function name.\n  For instance;\n\n      def hello() do\n      end\n\n  would be a completely different function from\n\n      def hello(name) do\n      end\n\n  Can you find a way to make all the tests pass with just one\n  function?\n\n  Hint: look into argument defaults here:\n  http://elixir-lang.org/getting-started/modules.html#default-arguments\n  \"\"\"\n\n  @doc \"\"\"\n  Greets the user by name, or by saying \"Hello, World!\"\n  if no name is given.\n  \"\"\"\n  @spec hello(String.t) :: String.t\n  def hello(name) do\n\n    \"Your implementation goes here\"\n\n  end\nend\n","hello_world_test.exs":"if System.get_env(\"EXERCISM_TEST_EXAMPLES\") do\n  Code.load_file(\"example.exs\")\nelse\n  Code.load_file(\"hello_world.exs\")\nend\n\nExUnit.start\nExUnit.configure exclude: :pending, trace: true\n\ndefmodule HelloWorldTest do\n  use ExUnit.Case\n\n  test \"says hello with no name\" do\n    assert HelloWorld.hello() == \"Hello, World!\"\n  end\n\n  @tag :pending\n  test \"says hello sample name\" do\n    assert HelloWorld.hello(\"Alice\") == \"Hello, Alice!\"\n  end\n\n  @tag :pending\n  test \"says hello other sample name\" do\n    assert HelloWorld.hello(\"Bob\") == \"Hello, Bob!\"\n  end\n\nend\n","README.md":"# Hello World\n\nWrite a program that greets the user by name, or by saying \"Hello, World!\" if no name is given.\n\n[\"Hello, World!\"](http://en.wikipedia.org/wiki/%22Hello,_world!%22_program) is the traditional first program for beginning programming in a new language.\n\n**Note:** You can skip this exercise by running:\n\n    exercism skip $LANGUAGE hello-world\n\n## Specification\n\nThe `Hello World!` program will greet me, the caller.\n\nIf I tell the program my name is Alice, it will greet me by saying \"Hello, Alice!\".\n\nIf I neglect to give it my name, it will greet me by saying \"Hello, World!\"\n\n## Test-Driven Development\n\nAs programmers mature, they eventually want to test their code.\n\nHere at Exercism we simulate [Test-Driven Development](http://en.wikipedia.org/wiki/Test-driven_development) (TDD), where you write your tests before writing any functionality. The simulation comes in the form of a pre-written test suite, which will signal that you have solved the problem.\n\nIt will also provide you with a safety net to explore other solutions without breaking the functionality.\n\n### A typical TDD workflow on Exercism:\n\n1. Run the test file and pick one test that's failing.\n2. Write some code to fix the test you picked.\n3. Re-run the tests to confirm the test is now passing.\n4. Repeat from step 1.\n5. Submit your solution (`exercism submit /path/to/file`)\n\n## Instructions\n\nSubmissions are encouraged to be general, within reason. Having said that, it's also important not to over-engineer a solution.\n\nIt's important to remember that the goal is to make code as expressive and readable as we can. However, solutions to the hello-world exercise will be not be reviewed by a person, but by rikki- the robot, who will offer an encouraging word.\n\n## Running tests\n\nExecute the tests with:\n\n```bash\n$ elixir bob_test.exs\n```\n\n(Replace `bob_test.exs` with the name of the test file.)\n\n\n### Pending tests\n\nIn the test suites, all but the first test have been skipped.\n\nOnce you get a test passing, you can unskip the next one by\ncommenting out the relevant `@tag :pending` with a `#` symbol.\n\nFor example:\n\n```elixir\n# @tag :pending\ntest \"shouting\" do\n  assert Bob.hey(\"WATCH OUT!\") == \"Whoa, chill out!\"\nend\n```\n\nOr, you can enable all the tests by commenting out the\n`ExUnit.configure` line in the test suite.\n\n```elixir\n# ExUnit.configure exclude: :pending, trace: true\n```\n\nFor more detailed information about the Elixir track, please\nsee the [help page](http://exercism.io/languages/elixir).\n\n## Source\n\nThis is a program to introduce users to using Exercism [view source](http://en.wikipedia.org/wiki/%22Hello,_world!%22_program)\n"},"fresh":false}]}

Request GET http://exercism.io/api/v1/exercises?key=XXXXXXX
Response StatusCode=200
Response Body
{}

Not Submitted:       1 problem
elixir (Hello World) /Users/khansen/exercism/elixir/hello-world

unchanged: 1, updated: 0, new: 0

Exercism CLI Version: 2.2.4
Exercism CLI Latest Release: 2.2.4
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/khansen
Config file: /Users/khansen/.exercism.json
API Key: XXXX
Exercises Directory: /Users/khansen/exercism
Testing API endpoints reachability
	* API: http://exercism.io [connected] 240.297218ms
	* XAPI: http://x.exercism.io [connected] 248.911797ms
	* GitHub API: https://api.github.com/ [connected] 469.845233ms

**Comment by kytrinyx** [comment]
Hi @moccalotto, until you have submitted the first iteration of the problem you fetched, you will not automatically get the next one.

You can, if you wish, see the full list of exercises using the `list` command:

```
exercism list elixir
```

Then you can fetch individual exercises with the slug of the exercise:

```
exercism fetch elixir bob
```

You can also see the full list of exercises under "available exercises" on http://exercism.io/languages/elixir

**Comment by moccalotto** [comment]
Perfect. Thanks
