### ISSUE TITLE
Team members can view exercises from notifications, but not from team dashboard

### ISSUE THREAD

**Issue by IanWhitney** [exercism/exercism.io#2778]
When people in my team complete an exercise, I'm notified:

![screenshot 2016-03-02 09 43 04](https://cloud.githubusercontent.com/assets/12144/13465515/a98ccf86-e05b-11e5-99af-b07e6d79b774.png)

The first one in that list is a Perl 5 solution of RNA. I have not done any exercises in Perl, but I can still click on that link and see my teammate's solution:

![screenshot 2016-03-02 09 43 14](https://cloud.githubusercontent.com/assets/12144/13465530/bf90dab6-e05b-11e5-8590-08e481908830.png)

However, if I go to my team's dashboard, I am prevented from seeing the exact same solution that I was able to see via notifications

![screenshot 2016-03-02 09 42 57](https://cloud.githubusercontent.com/assets/12144/13465545/cd9142ea-e05b-11e5-9557-f87782640c05.png)

Note that the Perl 5 RNA exercise is Locked.

My thought is that team members should be able to see all their team's solutions, regardless of language. Our team is polyglot, so we're always going to have people working in languages that other members don't use. Having these exercises locked on the dashboard makes it hard for us to collaborate and discuss.

**Comment by kytrinyx** [comment]
Thanks, Ian, I've been wondering how to deal with the team thing lately. I think I'll try what you suggest--just opening everything up if you're viewing something via the team dashboard.

I'm in the middle of working on a "team activity stream" that's like the track exercises list, except scoped to the team, and then I'll remove the notifications altogether.

**Comment by kytrinyx** [comment]
@IanWhitney I finished the implementation of the new team activity stream feature that I've been working on. This makes it so that you can access any exercises by a given user on the team from the team dashboard.

I'm going to remove the notifications for new stuff from team members altogether.

**Comment by IanWhitney** [comment]
It looks great. Thanks.
