### ISSUE TITLE
Feature Request - label which exercises are complete

### ISSUE THREAD

**Issue by blackfist** [exercism/exercism.io#2780]
When I go to http://exercism.io/languages<lang> and see the list of exercises I can download, it would be helpful to have a badge next to them showing which ones I've already done. If I go away for a day or two or if I'm working through several languages it can be easy to lose my place and then I have to go into my filesystem and figure out where I left off.

Something as simple as "submitted" or a count of the iterations I've done would be sufficient.

**Comment by kytrinyx** [comment]
+100 I think this would be great.

There's also the `exercism status` command that right now is semi-helpful. That could also be improved.

**Comment by kgrz** [comment]
I'll see if I can add this feature.

**Comment by tejasbubane** [comment]
I just noticed a strange thing when I followed the link given by @blackfist 
http://exercism.io/languages/ (notice the trailing `/`) returns 404 while http://exercism.io/languages serves the languages page.

**Comment by kgrz** [comment]
Yeah, looks like sinatra doesn't auto-add [the trailing slash at the end](https://github.com/sinatra/sinatra/blob/4c7d38eb1b2cc02ce51029f28e0c3c34ca12ccfd/test/compile_test.rb#L49). We could fix that by changing the route declaration from `get '/languages'` to `get '/languages/?' or perhaps a regex: `get /\/languages/`

@tejasbubane Can I add an issue on Sinatra for this?

**Comment by kytrinyx** [comment]
Yeah, I considered adding the trailing `/?` everywhere. I have it in some places, but haven't gone through and done that. I remember looking at a couple of issues in Sinatra to see how easy it would be to fix this, and whether or not it would be compatible with other fixes. We had a long discussion a few months back about updating the README to reflect some of the quirks of the route patterns, and I got distracted from my mission.

**Comment by kgrz** [comment]
Took an initial stab at this. Is this what you had in mind? 
![image](https://cloud.githubusercontent.com/assets/400299/14859775/49e53ec6-0cc3-11e6-94e3-8a5e36249dac.png)

**Comment by kytrinyx** [comment]
Is there any way to make this more scannable? It would be neat if we could see at a glance which tracks were started. Maybe it would help to not show 0 submitted at all if you haven't started the track.

**Comment by sebarmano** [comment]
What about something like this? I like the idea of having the "# / # completed". I think that that way is showing all the information without adding too much text to the page. (However I think that the word *submitted* like in the @kgrz solution is more appropriate than *completed*). 

<img width="395" alt="screen shot 2016-04-26 at 7 05 24 pm" src="https://cloud.githubusercontent.com/assets/1483625/14930316/0eed90e2-0e31-11e6-909f-00ab4330e606.png">

**Comment by kytrinyx** [comment]
How about a badge for the ones that you've submitted exercises on?

Then the text would still say "31 Problems", but if you have actually completed some, there would be a colorful badge (maybe with a tooltip) that has the number that you've actually done in it.

**Comment by kgrz** [comment]
One more idea I had was to separate the in progress items into a different section and they can have the style @sebarmano created and the rest would just be arranged in the current manner.

 One possibly bad side-effect of this is to confuse users about all the sections on the page. The current separation is "Active" and "Inactive".  Adding another with similar meaning (say In progress) would probably end up confusing users as to what the difference between each is.

**Comment by kytrinyx** [comment]
Yeah, I suspect that between Active/In Active and In progress the completely different sort of category would be confusing.

**Comment by blackfist** [comment]
Sorry to be late to the party. What I meant when I created the issue is that when I go to the list of Elixir problems and I have to download the next one it would be nice to be able to tell which ones I've already done.

Right now I do an ls in my exorcism folder and then see which problems don't have a local folder. Which is fine when I've only done a handful but gets out of hand eventually.

**Comment by kytrinyx** [comment]
Ahh, ok this makes more sense.

Where do you go to the list of elixir problems. Is it on http://exercism.io/languages/elixir in the "Available Languages" tab?

**Comment by kytrinyx** [comment]
Another question: What if your profile page showed you what would be next? Or the dashboard?

**Comment by blackfist** [comment]
Yep, that's exactly where I go to find the available exercises. And I'm not picky about where I find out about the next exercise, so profile page or dashboard would be fine. I just want something easier than comparing my filesystem to the webpage.

**Comment by kytrinyx** [comment]
Perfect. I think either would work fine--it might make sense on the profile page since that lists all the exercises you've done. It could fit nicely to have the "next exercise" listed there.

**Comment by kotp** [comment]
I missed  exercism/discussions#13 which is related, although from the CLI perspective.

**Comment by kytrinyx** [comment]
The CLI thing would probably solve this nicely, as well, though. I think we should put it in both places.

**Comment by sebarmano** [comment]
I agree with @kytrinyx on having the next exercise for each language in the profile page. I'm wondering if it would be useful to have also an indication of that in the list of available exercises for each language. I'm thinking in something like a tick or badge next to the completed ones (a very basic example in the figure). This would also keep consistency between profile/dashboard and exercises views. 
Any thoughts? (Maybe this could go in as a different issue or feature?)
<img width="1103" alt="screen shot 2016-05-17 at 8 18 31 pm" src="https://cloud.githubusercontent.com/assets/1483625/15343673/ce7e7e32-1c6c-11e6-8805-958b86166d68.png">

**Comment by kytrinyx** [comment]
From a code perspective I would prefer to keep personalized content out of the generic language track, for a couple of reasons. First, it adds a bit of complexity to personalize the content. Second, as we start trying to cache things, personalized content makes a page much harder to cache. Right now we can't straight-up cache any of the pages on Exercism due to the way that the header menu changes based on logged in / not logged in status, but it's definitely something I want to do when we have the time to tackle it.

The question, of course, is whether or not having these check-marks on the "available exercises" page is significantly better than not having them. I don't know, since I don't regularly submit code to the site.

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/discussions/issues/34

**Comment by troubalex** [comment]
@kgrz:
> One more idea I had was to separate the in progress items into a different section and they can have the style @sebarmano created and the rest would just be arranged in the current manner.

To me, that immediately makes sense. I submitted 2 exercises in the Javascript track, and I had to look very hard to find the language on the page. Adding a section on top called something along the lines of "my languages" would be conveniently obvious.

> One possibly bad side-effect of this is to confuse users about all the sections on the page. The current separation is "Active" and "Inactive". Adding another with similar meaning (say In progress) would probably end up confusing users as to what the difference between each is.

I don't see anything "Active" or "Inactive". Are you referring to the language page or the exercises which are part of the language tracks? The latter is generally confusing.

**Comment by troubalex** [comment]
And now I know why.

The buttons listing all available exercises look like dropdown buttons but behave like an accordion header which is unexpected. I also wonder if it wouldn't be better to list the name of the exercise as a link, and only add the one line description beside it. The link would then take me to the exercise page with all necessary information.

That way the list would look more like an exercise catalogue, and be fairly easy to scan.

Kind of like this quick hack: http://codepen.io/troubalex/pen/GqYXwm

**Comment by kytrinyx** [comment]
> Kind of like this quick hack

Holy smokes that looks so much better :heart:

**Comment by Insti** [comment]
I really like that @troubalex :art:

**Comment by troubalex** [comment]
I'll check with @gusseting if this is something she'd like to work on during [RGSoC](railsgirlssummerofcode.org), otherwise I'll prepare a patch.

**Comment by nickborromeo** [comment]
@troubalex @kytrinyx I wanted to follow up on this and wanted to ask some clarification,

It seems like the `http://exercism.io/languages/<language>/exercises` already has this layout

<img width="784" alt="python_-_exercism_io" src="https://cloud.githubusercontent.com/assets/1518902/24031730/7767f672-0aa1-11e7-938e-1c6588cc93f2.png">

Which seems very much like the mock up that @troubalex has. Does this mean that this issue is resolved or am I missing what the issue is completely? 😄

**Comment by troubalex** [comment]
@nickborromeo This particular part of the discussion was moved into its own issue (#3033), and solved there.

**Comment by kytrinyx** [comment]
I think this is resolved.

**Comment by petertseng** [comment]
Hmm. From my point of view, e.g. if I go to http://exercism.io/languages/ruby/exercises I can't tell apart dominoes (an exercise I have solved) from tournament (an exercise I haven't solved) in any way. Unless there is a distinction and it is just invisible to browser (problem on my end)

**Comment by petertseng** [comment]
Oh  I am not paying attention.

> From a code perspective I would prefer to keep personalized content out of the generic language track, for a couple of reasons.

I missed the above sentence. Please ignore my comment!

**Comment by kytrinyx** [comment]
The question about orienting oneself in a track is one that we've got on the list of discussions for the redesign.
