### ISSUE TITLE
Admin - Update button leads to 404

### ISSUE THREAD

**Issue by scott-joe** [exercism/exercism.io#2781]
On the http://exercism.io/teams/__teamname__/manage page, attempting to change the Slug or Name results in a 404 on pushing the Update button.

**Comment by kytrinyx** [comment]
Thanks for the heads up!

**Comment by mhelmetag** [comment]
This [form](https://github.com/exercism/exercism.io/blob/master/app/views/teams/manage.erb#L11) is missing an `<input type="hidden" name="_method" value="put" />` to override the post method and conform to the put method defined [here](https://github.com/exercism/exercism.io/blob/master/app/routes/teams.rb#L81).
