### ISSUE TITLE
Language info pages: markdown emits three asterisks after a bulleted list

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism.io#2784]
For example, try out "Recommended References" or "Learning Javascript" at http://exercism.io/languages/javascript and see how there are `***` after the list.

However, it doesn't happen after all lists. See how "About the Javascript Track" doesn't have the `***` after its list.

**Comment by petertseng** [comment]
Ah... what would you say if I said I thought it was the three dots in https://raw.githubusercontent.com/exercism/exercism.io/master/x/docs/md/track/BETTER.md ?

I wonder...

**Comment by mhelmetag** [comment]
Yeah... I'd agree that they're from that file. Looks like those 3 asterisks are getting tacked on. I might have an idea for this...

**Comment by mhelmetag** [comment]
I feel like it's related to this https://github.com/exercism/exercism.io/blob/master/x/docs/track.rb#L22-L28... not sure if that `if else` is doing it's job correctly.

**Comment by petertseng** [comment]
Probably intentional to combine the language-specific docs with `BETTER.md`. That lets people know how to improve the docs.

OK, so I believe that because of the `strip` (and note there is a leading newline on `BETTER.md`), with a bulleted list it looks like this:

```
* list item
* list item
***

_Help us explain this better!
```

Which apparently is causing the three asterisks to get appended to the last list item.

So, maybe just adding a single extra newline to either `BETTER.md` or at https://github.com/exercism/exercism.io/blob/master/x/docs/track.rb#L26 would suffice.
