### ISSUE TITLE
bash: fetch: command not found

### ISSUE THREAD

**Issue by sind1990** [exercism/exercism.io#2787]
Im new at this, I tried using the command "$ fetch" in bash git cmd but i got this message bash: fetch: command not found. how can I fix it.

**Comment by NobbZ** [comment]
Where does it tell you to run ``fetch``? The closest thing to ``fetch`` you are supposed to run is ``exercism fetch``.

**Comment by kytrinyx** [comment]
@sind1990 did you get it working with `exercism fetch`?

**Comment by sind1990** [comment]
I still got an error "sh.exe: exercism: command not found". I have been trying to figure it out, but no luck

**Comment by NobbZ** [comment]
How did you install the exercism CLI?

sind1990 <notifications@github.com> schrieb am Mo., 7. März 2016 um
12:51 Uhr:

**Comment by sind1990** [comment]
@NobbZ I installed it through cmd. i think the problem was that i didnt add the path to the system var, once i did it start working. Thanks For ur help

**Comment by kytrinyx** [comment]
Glad you got it sorted.
