### ISSUE TITLE
Unable to View Completed Exercise/Fetch Next Exercise

### ISSUE THREAD

**Issue by ehrlichwirklich** [exercism/exercism.io#2789]
Hi,

I recently completed the Hello World for Java. I submitted the file, but am unable to fetch the next item on the track. I also can't view my recently submitted code, as the link provided from exercism (which if it matters does match the one given by the cmd line) is broken. I also can't use the exercise buttons to go directly to exercise while I am logged in, as I receive a pop up, that they can't find that user. My cmd prompt says that hello world is unchanged, but it appears to have submitted, because when I try to submit the same file it says 404 duplicate iteration. I have checked that I am submitting the file I changed, but I can't verify what is submitted, because I can't view it on the site. I am at a loss with this.

**Comment by kytrinyx** [comment]
Hi @ehrlichwirklich, this is odd! Let's see if we can get it sorted.

I've looked up your exercise on the site, and it's missing the exercise name, which it usually detects from the directory structure of where the code is located when you submit it. I suspect that there might be a problem with the directory structure in your case... but it could also be a bug.

What does `exercism debug` output?

**Comment by kytrinyx** [comment]
I've manually updated the exercise on the site to have the right language and problem data; you should be able to see it now.

That said, we have to figure this out, or it's just going to happen again.

**Comment by ehrlichwirklich** [comment]
It all seems in order 
**** Debug Information ****
Exercism CLI Version: 2.0.0
OS/Architecture: windows/amd64
Home Dir: C:\Users\[my_name]
Config file: C:\Users\[my_name]\.exercism.json
API Key: [my_current_key]
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: C:\Users\[my_name]\exercism

Everything is where I expect it

**Comment by kytrinyx** [comment]
Yeah that looks right. What was the location of the java file that you submitted?

If there are further issues with this, you could also try updating to the most recent version of the CLI. I try to maintain backwards compatibility, but since exercism is still somewhat of a prototype, this sometimes gets messed up.

**Comment by ehrlichwirklich** [comment]
C:\Users\[my_name]\exercism\java\hello-world\src\main\java
Also, I just did the process of setting up CLI a few days ago. It's already to a stable update?

**Comment by kytrinyx** [comment]
2.2.4 was released in January. What method did you use to install it?

**Comment by ehrlichwirklich** [comment]
I used Go, since I had that already.

**Comment by ehrlichwirklich** [comment]
kytrinyx I am trying to update it now, but i managed to upload etl without the exercise name again. Any interim solution ideas?

**Comment by ehrlichwirklich** [comment]
@kytrinyx  I unsubmitted my last submission until i can figure this out so as to not muddy the waters more.

**Comment by kytrinyx** [comment]
What happens if you say `go get -u github.com/exercism/cli/exercism`, then `exercism -version`?

**Comment by ehrlichwirklich** [comment]
It doesn't update. I am still at 2.0.0

**Comment by kytrinyx** [comment]
OK, that seems like a bug as well. I'll dig into both of these issues (API/backwards compatibility and `go get -u`)

/cc @exercism/cli-committers (in case you have any ideas).

**Comment by Tonkpils** [comment]
@ehrlichwirklich you may need to delete the installed binary from the go bin path. 

If the output of `which exercism` looks it's somewhere in your Go path go ahead and delete the `exercism` binary from that path and retry the `go get` command.

**Comment by kytrinyx** [comment]
I don't think there's a `which` on Windows. Maybe `where`?

**Comment by Tonkpils** [comment]
> I don't think there's a which on Windows. Maybe where?

Right! thanks for the catch, didn't notice it was on Windows

**Comment by ehrlichwirklich** [comment]
Nope. Its in my program(x86 files) actually.

**Comment by Tonkpils** [comment]
@ehrlichwirklich did you happen to install it any other way? Can you delete any exercism binaries you may have installed and re-install them?

**Comment by ehrlichwirklich** [comment]
I may have installed it before, but I'm not sure if there are any duplicates or where to find them...
Sorry.

**Comment by Tonkpils** [comment]
No problem, as long as you remove the current one that `where exercism`. What we want is a clean slate to make sure you're using the latest binary.

**Comment by ehrlichwirklich** [comment]
Okay cool. Can I just uninstall that or do I need to do something special. Sorry if that's an obvious question.

**Comment by Tonkpils** [comment]
You can just delete it/remove nothing special :)

**Comment by ehrlichwirklich** [comment]
@Tonkpils I removed it. Would I do something different than before?

**Comment by Tonkpils** [comment]
@ehrlichwirklich just to be sure are you able to run `exercism` after you deleted it? If so you may have another copy of it. 

If not which is the most likely case, just re-install it following the instructions from  http://exercism.io/cli#windows and make sure you have the latest version

**Comment by ehrlichwirklich** [comment]
Do you think there is any difference between me manually installing it and using Go?

**Comment by kytrinyx** [comment]
There shouldn't be any difference, but if you're not getting the most recent code with `go get` then there will be a difference.

**Comment by ehrlichwirklich** [comment]
I did it manually and it setup correctly. Thanks for all the help  @kytrinyx @Tonkpils . My exercises button doesn't work still, but that is unrelated.

**Comment by kytrinyx** [comment]
*whew* OK, glad that's sorted on your end. I'm going to leave this open as a reminder to fix the underlying issue on the backend.

**Comment by kytrinyx** [comment]
@ehrlichwirklich What is the status on this. Can we close it?
