### ISSUE TITLE
Problem suggestion: find words made from a collection of letters

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#2794]
This is a problem we did at our Salt Lake City Software Craftsmanship meetup:

Given:
- a collection of individual letters, such as the letter tiles in a scrabble game
- a collection of words

Write code to return all possible words that can be formed from the individual letters.

**Example:**

Given:
- the letters 'a', 'b', 'e, 'e'
- the words "a", "an", "baa", "be", "bee", "ebb"

The algorithm returns the words "a", "be", and "bee".

Things to note:
- The collection of letters can include duplicates.
- Each word selected need not consume all of the letters in the collection.
- Each word selected considers the collection of letters separately.  In other words, letters selected to form one word do not impact the letters used to form another word.
- The words selected cannot contain more letters than are in the collection of letters.

**Comment by kytrinyx** [comment]
I like this suggestion. @roseaboveit Should we put "new problem suggestions" in the x-common repository?

**Comment by wobh** [comment]
A related, though not combinatorial problem: http://thenoisychannel.com/2011/08/08/retiring-a-great-interview-problem.

**Comment by Insti** [comment]
This would be a better fit in [x-common](https://github.com/exercism/x-common/issues), are you able to move issues between repositories?

**Comment by kytrinyx** [comment]
> are you able to move issues between repositories?

This, unfortunately, is not a GitHub feature.

There is, apparently, a browser plugin that kind of does it for you (it copies all of the content and opens a new issue in the target repository). I can't remember who used that plugin. @kotp maybe?

**Comment by kotp** [comment]
I did, it was ZenHub, though I just temporarily signed up/in and used it to see what it would do on that one issue.

**Comment by kytrinyx** [comment]
I wish there was a way to do a proper move, but in the absence of one of those, the ZenHub approach seems like a good workaround.

**Comment by nickborromeo** [comment]
@kotp @kytrinyx was this moved to the x-common repo issues? I tried looking for it, but my search skills I guess is not that good 😄 

If it was indeed moved over, could we also close this issue? 😄

**Comment by kotp** [comment]
Issue moved to [exercism/x-common #727](https://github.com/exercism/x-common/issues/727) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kotp** [comment]
I also could not find it, so I must assume I did not move it.
