### ISSUE TITLE
Rikki link in comment box has points to a URL that returns a 500.

### ISSUE THREAD

**Issue by colinrymer** [exercism/exercism.io#2797]
## Steps to reproduce:
1. Go to a submission that has a comment by Rikki
2. Click on the URL that is Rikki's name at the bottom of the comment.

## What I expected:
I expect to go to the link for Rikki - `http://exercism.io/rikki` or at least get a 404 response for the page.
## What happened instead:
I was taken to `http://exercism.io/rikki-` which returned a 500 response code and page.

## Additional Information:
This appears to be due to Rikki's username, `rikki-`[0], which the app has hardcoded dependencies on. Given this, an easy solution seems to be adding a route that matches on `/rikki-` and redirects to `/rikki`, but I realize that adding a route is an action that shouldn't be taken lightly.

Thoughts?

--
 0 - Example in the [source code]( https://github.com/exercism/exercism.io/blob/cabe45808a4fa43bad6fce194e9ff35e642df6b6/api/v1/routes/comments.rb#L19).

**Comment by kytrinyx** [comment]
I'll add the redirect and also fix the link in rikki's comment. Thanks!

**Comment by kytrinyx** [comment]
Wait, I misunderstood the issue. When I go to http://exercism.io/rikki- I get a 200, not a 500 error.

Would you double-check this, please?

**Comment by colinrymer** [comment]
Hrm, interestingly, I'm now getting a 200 for `http://exercism.io/rikki-`. I was definitely getting a 500 before - maybe Bugsnag could shed some light on that.

That said, I would still expect the page `/rikki-` and `/rikki` to have the same information - but now I suppose there's a new question of whether that info should be displayed on a regular profile page or a special page (like the current `/rikki` page.

**Comment by kytrinyx** [comment]
Right, I don't know what the right answer is. Since rikki is a user in the system I'd rather not screw with it, but if I add something where people can add some profile info, we could link to the experiment page from there. That might make it less confusing.

**Comment by colinrymer** [comment]
FWIW, from trying to approach this from a UX perspective, I think that adding a special case to the routes for redirecting `/rikki-` to `/rikki` is still a reasonable approach - since Rikki is a bot, it seems unlikely that `/rikki-` will ever contain any meaningful information.

While something that allows people to add some profile info certainly could also solve the problem, you now have to handle user input, which of course can mean a whole new set of challenges to address. Additionally, adding the information on `/rikki` to Rikki's user profile still leaves Rikki with empty Current and Archived Exercise sections, which provides no value to users.

**Comment by kytrinyx** [comment]
Yeah, agreed. I'm going with the redirect.
