### ISSUE TITLE
Incorrect feedback link on dashboard

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism.io#2798]
If you have a link to feedback on your dashboard, it misses the `/submissions` part of the URL. 

E.g., on my dashboard, the link for a feedback item was `http://exercism.io/f96cf9abef4c49e98b30b6c07f80953d`. This is a dead link. However, the notifications page has the correct link: `http://exercism.io/submissions/f96cf9abef4c49e98b30b6c07f80953d`

![image](https://cloud.githubusercontent.com/assets/135246/13740001/aab4bec4-e9ce-11e5-91c7-50a542a28d80.png)

**Comment by kytrinyx** [comment]
Ah, my bad! Thanks for catching it. Fixing that now.
