### ISSUE TITLE
Unable to submit - unable to identify track and problem

### ISSUE THREAD

**Issue by wendy0402** [exercism/exercism.io#2802]
Hi it's a little bit silly, but I have this kind of trouble when try to submit(I've seen many issues related with this, and try it but nothing works), can you help me?
```
**** Debug Information ****
Exercism CLI Version: 2.2.1
Exercism CLI Latest Release: 2.2.4
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/wendykurniawan
Config file: /Users/wendykurniawan/.exercism.json
API Key: ce85ffbc0eaa046ca828063d6211bb52ca518c55
API: http://exercism.io [connected]
XAPI: http://x.exercism.io [connected]
Exercises Directory: /Users/wendykurniawan/exercism
```
```
pwd
/Users/wendykurniawan/exercism
```

**Comment by mhelmetag** [comment]
@wendy0402 , not silly at all! What seems to be the problem when submitting? Are you receiving an error? 

When you say that you've seen many issues related to this, are there any that you could point to that seem similar (just curious; not required)?

**Comment by wendy0402** [comment]
for example like this one https://github.com/exercism/exercism.io/issues/2314. I try to submit elixir, In my current directory I runt this command:
```
exercism submit elixir/hello-world
```

**Comment by NobbZ** [comment]
You need to submit the actual files, not the complete folder. Please do
submit the solutions file only, not the testsuite or project organisation
files.

wendy kurniawan soesanto <notifications@github.com> schrieb am So., 20.
März 2016 09:04:

**Comment by wendy0402** [comment]
Thanks a lot!

**Comment by petertseng** [comment]
It could be good to file an issue in https://github.com/exercism/cli to say that if the `exercism submit` command is used on a directory it should give a helpful message that files should be submitted instead

**Comment by mhelmetag** [comment]
I like that idea. Easy to implement as well and might improve the user experience a bit.

**Comment by alebaffa** [comment]
I can take care of this :) it would be my first PR here on exercism.

I took a look and it seems pretty simple to implement. 
I think I could add a new check in _cli/cmd/submit.go_ along with these existing ones:

```go
if isTest(filename) ...
if isREADME(filename)...
```
I see two solutions, but I would like to hear your opinion:

1) to create a new function (which will be stored in _/cmd/cmd.go_)
```go
if isDirectory(filename)
```

2) To use the function
 ```go
func IsDir(path string) bool
```
which is already implemented and stored in _paths/paths.go_

The 1) allows to stay coherent with the previous coding style (isTest, isREADME), the 2) allows to reuse an existing function.

What do you suggest?

**Comment by alebaffa** [comment]
(sorry, I just moved my comment in the issue 300 on the cli)

**Comment by mhelmetag** [comment]
@kytrinyx , I think this could be closed now that the cli shouldn't allow checking in directories.

**Comment by kytrinyx** [comment]
Thanks @mhelmetag!
