### ISSUE TITLE
Status endpoint in API does not return correct information

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2804]
To reproduce:

- fetch a specific exercise that you have not fetched before (e.g. `exercism fetch elixir diamond`)
- check the status endpoint (e.g. curl `http://exercism.io/api/v1/tracks/elixir/status?key=$API_KEY`)

Please see the full discussion in https://github.com/exercism/cli/issues/287 for the details.

**Comment by GustavoCaso** [comment]
@kytrinyx is anyone working on this one ?

**Comment by kytrinyx** [comment]
Nope, not yet. Want it?

**Comment by GustavoCaso** [comment]
Yes

**Comment by GustavoCaso** [comment]
@kytrinyx I think we can close this one.

**Comment by kytrinyx** [comment]
Yepp, good call. Thanks!
