### ISSUE TITLE
Extra space needed after the (language) in Dashboard "Recently Viewed"

### ISSUE THREAD

**Issue by mandel01** [exercism/exercism.io#2813]
As shown in the screenshot below an extra space is needed (red arrows):

![2016-04-05-15-11-02-screenshot](https://cloud.githubusercontent.com/assets/8669125/14299347/8654e2ec-fb4f-11e5-941a-0091302b9c5c.png)

**Comment by kytrinyx** [comment]
Thanks for catching it (and for the screenshot; that always helps with this sort of thing).
