### ISSUE TITLE
Profile Page: completed exercises chart

### ISSUE THREAD

**Issue by masters3d** [exercism/exercism.io#2816]
I love the profile page but I am not a fan of the percentage of completion as the first thing that gets seen. 
Humans are kinna of prideful creatures. A profile is something I'd like to show my friends when we are having coffee. 
The percentage of completion makes it feel to me that I have not *finished* something or that I am falling. 
I much rather have a page that shows me *how many * problems I've completed and maybe if I click or hover over the language I can get a percentage but the percentage should not be the first thing I see when go to my page. 

![image](https://cloud.githubusercontent.com/assets/6539412/14324872/94ba0a38-fbdb-11e5-95ce-30b469b4fa5b.png)

Perhaps it can be something like this and also include how many problems I have nitpicked from each language? 

// Something along these lines
Swift
35 Completed Problems 
45 Peer Reviewed Problems
![image](https://cloud.githubusercontent.com/assets/6539412/14325034/465a809c-fbdc-11e5-93d8-8a89299b117b.png)

Cross posted:
https://github.com/exercism/x-common/issues/218#issuecomment-206465143

**Comment by kytrinyx** [comment]
Copying my response from the other thread:

Yeah, I'm all for making a change like this, both in terms of moving or downplaying the progress bars, as well as including how many problems the person has reviewed.

Let's do the thing where we show you the icon + completed problems + peer reviewed problems, and then if you hover over it (or click?) you get more information.

I'm not married to the progress bar, it's an experiment in giving more information. If a grid of the language icons with numbers gives a better impression, we can drop the progress bars altogether.

**Comment by GustavoCaso** [comment]
@kytrinyx I'll be happy to remove the progress bar in favor to of number of total and completed and adding the total reviewed problems

**Comment by kytrinyx** [comment]
@GustavoCaso that sounds great!

**Comment by GustavoCaso** [comment]
@kytrinyx here a draft without style, but wanted to check first, to see your impressions
![image](https://cloud.githubusercontent.com/assets/4672858/18463539/2cc93ad8-798b-11e6-8294-09a7d1d2f2c9.png)

**Comment by kytrinyx** [comment]
There are several people who do code reviews without completing exercises. We have a setting on the user record that gives people "mentor" status on a track, where they can see everything without having done the exercises.

What do you think of something like this:

[icon] Language Name
Completed: 19
Peer Reviewed: 2

Or maybe:
[icon] Language Name
Completed: 8
Peer Reviewed: 5

I worry that the language around how many you've peer reviewed will be confusing, because you might have done thousands of reviews on three different problems and it will say 3 not 2876 (or whatever). I don't know what the right answer to that is.

Maybe we need to have both numbers (but is that going to be messy? A performance problem?)

[icon] Language Name
Completed: 51 problems
Reviewed: 2987 iterations on 3 problems

What would it look like if we took the basic style from the activity stream?

<img width="613" alt="screen shot 2016-09-13 at 1 22 18 am" src="https://cloud.githubusercontent.com/assets/276834/18466452/9f4323c0-7950-11e6-8153-e4248c3180e2.png">

**Comment by GustavoCaso** [comment]
@kytrinyx 
With the problem about reviewed count, you are right we should probably have in mind that you could have more than one reviewed in the same exercise.

With performance in the initial approach I took the completed exercises from `UserExercises` and the reviewed from joining `Comments and Submissions` so I guess that I could improve the query to extract the number of iterations for each exercises or something like that, everything well encapsulated in a `ServiceObject`

About the design yes following the activity stream style might be a good idea.

**Comment by GustavoCaso** [comment]
![image](https://cloud.githubusercontent.com/assets/4672858/18623396/dddbf198-7e3c-11e6-8d02-6d8d8d2f1b77.png)

@kytrinyx do you like this style ? the reviewed section show the total but is missing the information related with how many exercises you have reviewed, but I just wanted to check if you like where this is going ? or we should rethink

**Comment by kytrinyx** [comment]
I think the style works well. It's pretty easy to scan.

**Comment by masters3d** [comment]
if Completed == 1 then "1 Problem" else "`X` Problems" 
if Reviewed == 1 then "1 Iteration" else "`Y` Iterations" 
:)

**Comment by kytrinyx** [comment]
@masters3d good call. I think active support has something that does this for English - http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-pluralize

So:

```
pluralize("Problem")
```

**Comment by GustavoCaso** [comment]
It does @kytrinyx

**Comment by GustavoCaso** [comment]
@kytrinyx I'm not able to load a new helpers I just created, I added the file and then added in the `helpers.rb` file but keep telling `undefined method`, any advice

**Comment by kytrinyx** [comment]
On Mon, Sep 19, 2016 at 1:01 PM, Gustavo Caso <notifications@github.com>
wrote:

> @kytrinyx <https://github.com/kytrinyx> I'm not able to load a new
> helpers I just created, I added the file and then added in the helpers.rb
> file but keep telling undefined method, any advice
>

Check out this section:
https://github.com/exercism/exercism.io/blob/master/app/routes/core.rb#L44-L56

**Comment by GustavoCaso** [comment]
@kytrinyx thanks 👍

**Comment by GustavoCaso** [comment]
@kytrinyx I think we can close this one.

**Comment by kytrinyx** [comment]
Yepp, agreed. Thanks!
