### ISSUE TITLE
Account deletion/clearing

### ISSUE THREAD

**Issue by sotojuan** [exercism/exercism.io#2817]
Um, I was [told](https://twitter.com/exercism_io/status/713453062057299968) to come here.

Basically I'd like to start "from scratch", even if I can skip or delete submissions (which I've done). If possible, deleting my account so I can remake it would be great. If not, just clearing the data.

[Here's me!](http://exercism.io/sotojuan).

If it's not possible, then that's fine! I understand if this is a silly request.

**Comment by kytrinyx** [comment]
You can clear all the data by going to your profile, selecting all of the exercises, and clicking delete. We don't have account deletion at the moment.

**Comment by sotojuan** [comment]
Thanks! Closing.

**Comment by texastoland** [comment]
> We don't have account deletion at the moment.

Still no?

**Comment by iHiD** [comment]
Nope, but if you want your account deleted you can email support@exercism.io and we'll action it.
