### ISSUE TITLE
Make landing page for upcoming language tracks be about how to help launch them

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2820]
There are several language tracks that currently are in progress. To see which ones, go to the languages page on exercism and scroll to the bottom: http://exercism.io/languages

We should have an extra tab on the upcoming languages (e.g. http://exercism.io/languages/groovy).

Right now the first item in the menu is "About the Groovy Track".

![menu](https://cloud.githubusercontent.com/assets/276834/14411504/511a187a-ff07-11e5-9063-1cde18a450f8.png)

I think we should make an additional menu item (only for inactive tracks) that says "Help Launch the $LANGUAGE Track".

This would then point to the repository for the track, and explain what needs to be done to launch it. 
There are a number of things that need to be in place before they can launch: enough exercises (10), an icon, documentation, people who will come provide feedback in the early days.

See the full checklist from the Elm track that recently launched:
http://github.com/exercism/xelm/issues/1

**Comment by joeltaylor** [comment]
@kytrinyx Can I safely assume that the first issue of a track will always be the checklist issue? Seems like that has been the convention thus far.

**Comment by joeltaylor** [comment]
@kytrinyx Any thoughts on the copy for the new tab? I essentially copied and pasted from the groovy checklist.

I thought about linking directly to the issue, but we'd need to store that issue number since the checklist issue number varies (I had first banked on it always being the first issue).

**Comment by kytrinyx** [comment]
Hey! So sorry it took forever to get back to this. I'm in the middle of some travel and am behind on everything. For the copy I think we should stay close to what is in that elm issue I linked to. I'll add some comments about copy over in the PR.

Going forward the checklist issue will always be the first one, because I post it via the API as soon as I create the repo, but for older repos that's not the case.... now... I could go back and edit issue 1 in all the open/in-the-works repos, which would let us link directly to it. Worth it? Might be.

**Comment by joeltaylor** [comment]
Totally understandable!

I'll go ahead and make changes where you commented on the PR. Having issue 1 always be the checklist seems like a nice convention and would allow us to directly link users to it. Less clicking == more happiness?

**Comment by kytrinyx** [comment]
less clicking, definitely more happiness. I will do some editing to make it so on the older tracks.
