### ISSUE TITLE
Add TECO language track

### ISSUE THREAD

**Issue by LegalizeAdulthood** [exercism/exercism.io#2834]
I'd like to add a [TECO](https://en.wikipedia.org/wiki/TECO_(text_editor)) language track.  However, TECO is unlike other languages in that non-printing characters are language instructions.  This is what makes it fun!  And weird.  This issue is a checklist for everything I need to do in order for a TECO language track.

- [ ] Enhance the code highlighter to understand TECO code.
- [ ] Add language track documentation
  - [ ] Describe TECO execution model
  - [ ] Describe where you get a TECO implementation
  - [ ] Describe how you edit TECO source files
- [ ] Create a unit test framework for TECO
- [ ] Decide which exercises to language track
- [ ] Implement sample solutions for the exercises
- [ ] Take the language track live

**Comment by kytrinyx** [comment]
Cool, I'll make a repository for you.

**Comment by kytrinyx** [comment]
OK, repo exists. I've opened the "launch checklist" issue here: https://github.com/exercism/xteco/issues/1

I also made a new team and made you team admin.

I'm going to close this issue in favor of the other one.

**Comment by LegalizeAdulthood** [comment]
Ooh, that looks great, lots of stuff I forgot.  Thanks!

**Comment by kytrinyx** [comment]
I have a pre-written issue that I submit to new repositories :)
