### ISSUE TITLE
Able to access and remove members of a team after removing myself from the team

### ISSUE THREAD

**Issue by brettchalupa** [exercism/exercism.io#2836]
When trying to remove myself from a team, my access and membership was not revoked, even though my avatar no longer showed up in the members list.

Here are the steps that I took:

1. Went to the team Manage page
2. Clicked on the [X] button by my avatar  
    ![exercism_io](https://cloud.githubusercontent.com/assets/928367/14718201/17ad5182-07aa-11e6-994b-d2929cb568df.png)
3. Confirmed my removal
4. Refreshed and still had access to the team's Manage, Members, and Activity, even though I no longer show up in the Member list  
    ![exercism_io](https://cloud.githubusercontent.com/assets/928367/14718227/499f5cbc-07aa-11e6-9cfc-b87772ef0ff5.png)

I was able to reproduce this behavior by creating a new team called 'foobar' and walking through these steps again.

The behavior I expected was that I would be redirected to the home page and no longer have read or management access to the team. For what it is worth, the original time I experienced this and the reproduction instance, I was the creator of the teams.

 Is this an issue or are my expectations off? I would be happy to help contribute to the fix if someone can outline the expected behavior.

**Comment by mhelmetag** [comment]
You definitely shouldn't have management access. That seems unexpected. I think teams are public so read access seems reasonable.

Nice find!

**Comment by kytrinyx** [comment]
Membership and management is not the same thing. If you remove yourself as a member, you are still a manager. You can't quit as the manager if you are the only manager.

I'd be open to suggestions about how this should work.

**Comment by brettchalupa** [comment]
@kytrinyx that makes sense to me, thanks for explaining it. Is there an interface for managing the managers/would that be helpful to have?

I think the confusion I had was not knowing that I was still a manager, so would it be helpful to have that be more clear?

If folks have thoughts on what it would look like to make it clearer, I would be happy to help implement the changes. 😄

**Comment by kytrinyx** [comment]
Yeah, there's supposed to be a "manage" tab... if you're not seeing it, I'm going to have to dig into what the situation is with your team.

I'd love some help getting this cleaned up!

**Comment by brettchalupa** [comment]
I see the "Manage" tab and the "Managers" section. The "Managers" section is empty, which is probably why I didn't realize I was one. See:

![screen shot 2016-04-25 at 11 34 16 am](https://cloud.githubusercontent.com/assets/928367/14794585/c35b4da4-0ad9-11e6-841f-131bfc4a3593.png)

I just tried entering "brettchalupa" to add myself as a manager and nothing changes. I will dig into the code and see what is going on and share/ask thoughts on improving the experience.

**Comment by kytrinyx** [comment]
Huh, yeah, it should absolutely list you as a manager, and probably explain that you can't remove yourself as a manager if you're the only one.

**Comment by brettchalupa** [comment]
I was able to figure out why and where this is occurring. I am working on adding the explanation and listing the current user as a manager if they are one (as well as tests). 🎉

**Comment by kytrinyx** [comment]
Ah, that's excellent news. Thank you!

**Comment by brettchalupa** [comment]
How does this seem?

<img width="503" alt="screen shot 2016-04-26 at 8 09 10 am" src="https://cloud.githubusercontent.com/assets/928367/14823107/30751616-0b86-11e6-82f3-e21816ce1614.png">

I kept the same button but disabled it and added a tooltip explaining the situation.

**Comment by kytrinyx** [comment]
Yeah, I like it.
