### ISSUE TITLE
Reword 'Delete' to 'Delete Iteration' 

### ISSUE THREAD

**Issue by kenden** [exercism/exercism.io#2840]
When viewing an iteration of my answer, there is a "Manage" menu on the top right part of the page.
In the menu, there are two options "Archive Excercise" and "Delete".

The intent of the "Delete" option could be made clearer, I was half-scared it would delete my exercise submission entirely.

I propose renaming to "Delete Iteration"

![screen shot 2016-04-25 at 10 17 45](https://cloud.githubusercontent.com/assets/480586/14777948/87349c6c-0ad0-11e6-938e-3c9db7b882fb.png)

**Comment by kytrinyx** [comment]
Yeah, _delete iteration_ would be much clearer.

This is found in the `app/views/submissions/user_actions.erb` file in this repository.
