### ISSUE TITLE
latest iteration changed with new date

### ISSUE THREAD

**Issue by masters3d** [exercism/exercism.io#2850]
http://exercism.io/profiles/masters3d/77d47b1cec02419489bbcebaf3236d80
take a look at the swift track. The "latest iteration" date was overwritten to a newer date even though there was not been new submissions. The swift track problems should have dates raging back to 2015.

**Comment by kytrinyx** [comment]
Yeah, this looks like a bug. Not sure what happened, but it definitely looks wrong.

**Comment by NobbZ** [comment]
On my profile I have a similar problem across various tracks that are
bumped to a date of the last week. It did happen to multiple tracks and the
whole track shares the same date, but the date differs between affected
tracks.

When I'm back home in one or two days I might be able to tack a closer look
at the page and give more insight about which tracks are affected and also
I might be even able to share the real date of the last submission for one
or other solution.

Katrina Owen <notifications@github.com> schrieb am Fr., 29. Apr. 2016,
20:31:

**Comment by amalrik** [comment]
I want to tackle this bug. :smiley: 
I see there's a field `last_iteration_at` on table `user_exercises` but on `app/views/user/_exercises_table.erb` the field `updated_at` is showed instead.

I will try to submit the fix tonight.

**Comment by kytrinyx** [comment]
Awesome, thanks!
