### ISSUE TITLE
UNABLE TO FETCH ON WINDOWS

### ISSUE THREAD

**Issue by iamharshit** [exercism/exercism.io#2853]
>>>i tried to do `exercism fetch python` on my window cli, but it showing `No connection could be made because the target machine refused it`, ,NEED SOME GUIDANCE, to cope up with.....
>>>below is the screenshot of the same
![query](https://cloud.githubusercontent.com/assets/15041829/14916566/0ee804cc-0e38-11e6-9052-8bbbde52ef3e.png)

**Comment by kytrinyx** [comment]
Would you please run `exercism debug` and paste the output here?

**Comment by iamharshit** [comment]
>@kytrinyx as you asked,
![query](https://cloud.githubusercontent.com/assets/15041829/14926331/5536fee8-0e69-11e6-9a22-569c44615f44.png)

**Comment by kytrinyx** [comment]
Do you get the same error message if you reconfigure the CLI to talk to google instead?

```
$ exercism configure --api=http://google.com
```

Then:

```
$ exercism debug
```

**Comment by iamharshit** [comment]
@kytrinyx ,yup i have the same error,
![query2](https://cloud.githubusercontent.com/assets/15041829/14926764/63d1508c-0e6b-11e6-8b09-c2b714807a33.png)

**Comment by kytrinyx** [comment]
OK, so this doesn't have anything to do with the actual endpoints, but is more likely related to your environment.

Are you behind a firewall? Have you tried any of the troubleshooting tips on this page? http://exercism.io/help

**Comment by iamharshit** [comment]
>@kytrinyx No, my firewall is turned off,
yup i have gone thru the help page, but didn't find a satisfactory solution because,
* `exercism -v` shows `exercism version 2.2.5` -> :+1: 
* `exercism -degug` shows the correct result -> :+1: 
* my api key matches -> :+1: 
* I don't know how to set the Exercise directory -> :-1: 
* since, it is not showing `No DNS Server `Error i skiped the step ->:+1: 
* since , my Firewall is off, i skiped the step ->:+1:

**Comment by iamharshit** [comment]
>>even i am not able to submit the solution,
i think i am about to reach the so called breaking point (i.e when a student looses interest in something when he don't know how to get out of a problem)
 ***GOD please HELP***
![ex sol submit](https://cloud.githubusercontent.com/assets/15041829/14935421/b48c2c30-0eee-11e6-85a0-de3b28c9e3fc.png)

**Comment by kytrinyx** [comment]
> exercism -degug shows the correct result -> :+1:

No, the debug output is not correct. It shows that the CLI is unable to connect to any of the endpoints, that's what the error message means. This means that you will be unable to fetch or submit.

@jwood803 have you run into issues with TCP connections on windows before?

**Comment by NobbZ** [comment]
Are you able to ping to google from command-line? Are you able to connect
via telnet to one of the endpoints and do a simple GET /?

are you behind a proxies network? Or may there be something else in your
network behaving like a firewall?

Katrina Owen <notifications@github.com> schrieb am Sa., 30. Apr. 2016,
17:03:

**Comment by iamharshit** [comment]
@NobbZ 
**ans1**, I tried to ping google but got this
![ping](https://cloud.githubusercontent.com/assets/15041829/14937931/01437710-0f33-11e6-8798-b2df13a55f7f.png)

**ans2**,no, there is nothing else like firewall,yes, i am behind proxies which tried to set by `set http_proxy=http://your_proxy:your_port` , after doing that i got this
![final](https://cloud.githubusercontent.com/assets/15041829/14937968/ebae39c0-0f33-11e6-803d-06ea053617ca.png)

**Comment by NobbZ** [comment]
So, sitting behind a proxy will fluff away any ping... For the proxy
variable... I don't know how that stuff is handled on windows though... But
in general the proxy is your current problem.

iamharshit <notifications@github.com> schrieb am Sa., 30. Apr. 2016, 21:00:

**Comment by kytrinyx** [comment]
You need to remember to reconfigure the API so that it has http://x.exercism.io instead of http://google.com

Look at `exercism configure`, which will show you the current configuration, and also shows the flags that it accepts.

**Comment by iamharshit** [comment]
>>@kytrinyx thats the output of `exercism configure`,
![untitled](https://cloud.githubusercontent.com/assets/15041829/14939761/de940a64-0f72-11e6-9287-2f661d4aefa0.png)
how  do i reconfigure the API so that it has  http://x.exercism.io instead of http://google.com

**Comment by tejasbubane** [comment]
@iamharshit As written in the output of exercism configure, you need to use the `--api` option and pass in the url like this:

```
exercism configure --api http://x.exercism.io
```

You should see this output:
```
Configuration written to /home/tejas/.exercism.json

  --key=<your exercism API key>
  --dir=C:\Users\LENOVO\exercism
  --host=http://exercism.io
  --api=http://x.exercism.io
```

**Comment by iamharshit** [comment]
@tejasbubane still a no,
![still](https://cloud.githubusercontent.com/assets/15041829/14942370/6232e6dc-0fd8-11e6-8330-5b420a2f2168.png)

**Comment by kytrinyx** [comment]
@iamharshit The configuration is now correct, but you still have a problem with your proxy.

**Comment by iamharshit** [comment]
@kytrinyx How to fix that?

**Comment by kytrinyx** [comment]
I'm not sure, I've never worked on a windows machine. @jwood803 do you have any experience with this? @ErikSchierboom you've written code in a bajillion environments... would Windows be one of them by any chance?

**Comment by ErikSchierboom** [comment]
@kytrinyx Yes, I almost exclusively work on Windows and I have never had this problem. This is the output for `exercism configure` on my machine at work:

![image](https://cloud.githubusercontent.com/assets/135246/14976553/fce69824-110c-11e6-9a64-c06b83792be6.png)

I also use the CLI on Windows at home, which I also never had a problem with.

**Comment by kytrinyx** [comment]
@ErikSchierboom Do you know how to figure out if there is a firewall-ish sort of thing, or how to figure out what proxy one would need to use to get past a refused TCP connection?

**Comment by ErikSchierboom** [comment]
@kytrinyx I'm sorry, I don't :(

**Comment by kytrinyx** [comment]
OK, thanks. Let's try twitter! https://twitter.com/kytrinyx/status/727482691445125120

**Comment by kytrinyx** [comment]
According to rboudinot:

> First thought is to use c9.io until fix is found. I have a windows machine I can use to try this.

rboudinot also mentioned that they'd have some time to help out later this week.

@iamharshit Here's a tutorial about how to use c9.io with Exercism. https://www.youtube.com/watch?v=r0TnwOLxoks

**Comment by selfup** [comment]
@kytrinyx 

Just leaving a quick comment but I am the rboudinot from Twitter! Should have some time tomorrow and Thursday.

**Comment by trptcolin** [comment]
@iamharshit Are you able to visit http://x.exercism.io/ in the web browser (IE?) on your Windows machine? I'm expecting so (since you could visit the documentation), and so I'd suggest ensuring that the command line proxy configuration matches the one the web browser is using (see also: http://stackoverflow.com/a/28153935/495302). You can find [IE's proxy configuration instructions here](http://windows.microsoft.com/en-us/windows/change-internet-explorer-proxy-server-settings#1TC=windows-7).

Make sure that you've got any username/password credentials in there that you need!

Also: keep in mind that if you set `http_proxy` value in a `cmd` session, that value will only stick around for the single `cmd` session that you're running. It looks like many of these screenshots are from brand-new `cmd` sessions that don't have a `set http_proxy=http://your_proxy:your_port` at the start, but perhaps you're setting it externally through the GUI somewhere. 

Environment variables are case-sensitive, but according to [this issue](https://github.com/exercism/exercism.io/issues/1914), they used an upper-case version, so you might try changing the case as well (some programs care about the difference between `http_proxy` and `HTTP_PROXY`; others don't).

I'm assuming/hoping here that there's not some crazy proxy configuration where it's rejecting requests from any non-whitelisted User-Agent or something. But that's in the realm of things that a proxy *could* do. 😨 

So no one obvious fix here, but hopefully those are a few hypotheses to falsify or prove out! Hope it helps.

**Comment by iamharshit** [comment]
@kytrinyx 

ok, i got started with c9.io, its cool.

**Comment by iamharshit** [comment]
thanks @trptcolin , it took me 2 days to complete ur comment,
but it worked,
for future users who face this problem there is one line solution,

>**set your proxy by** `set http_proxy=http://your_proxy:your_port`

**Comment by kytrinyx** [comment]
So glad you worked it out, @iamharshit! Thanks for sticking with it until you found the solution.

**Comment by selfup** [comment]
Oh great! There was a fix. Was about to hop on it. 

Glad it all worked out

**Comment by raghuchowdareddy** [comment]
If you have a authetication for http_proxy, here is the command
"set http_proxy=http://<username>:<password>@your_proxy:your_port"
