### ISSUE TITLE
Stop filtering out hello-world

### ISSUE THREAD

**Issue by Wilfred** [exercism/exercism.io#2855]
It doesn't seem possible to view other people's solutions. If I look at a solution I've submitted, e.g. http://exercism.io/submissions/d2333db5fe6b4acfae3cd8e523ab0068 or http://exercism.io/submissions/444b5e4d14d24fca921da5db0d6353c1, there's no link to view other solutions.

If I go to the dashboard, I get a link to a http://exercism.io/tracks/clojure/exercises . However, that doesn't show anything:

![clojure_track](https://cloud.githubusercontent.com/assets/70800/14935875/47595300-0ed9-11e6-8917-205c76dfaffc.png)

**Comment by NobbZ** [comment]
That's because hello world isn't in any reviewers queue. Just move on and
try to review following exercises.

Wilfred Hughes <notifications@github.com> schrieb am Sa., 30. Apr. 2016,
14:41:

**Comment by Wilfred** [comment]
Hello world is a great way of exploring the site, so it will often be where users get their first impression. Could we at least display why the page is blank?

**Comment by kytrinyx** [comment]
This has come up before. We've considered removing the restrictions with hello-world, and I think it's the right thing to do now.

**Comment by kytrinyx** [comment]
I've updated the title to reflect the action that I think we should take on this.

I think the main place to start is to look for all the places where we explicitly mention "hello-world" and figure out from there whether this is something that is filtering it out, and then remove the filters.

```
git grep hello-world lib
```
