### ISSUE TITLE
Add a section to the dashboard if you've not submitted anything yet

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2856]
When you log in, you get redirected to the dashboard. If you haven't submitted anything yet we should tell you how to get started:

- link to the two "getting started" pages (one for code newbies, one for experienced developers) with some short copy about why you would look at one or the other
- link to the /languages page and explain that they'll need to follow instructions to get started

**Comment by cshutchinson** [comment]
I have a PR in progress. Would you take a look at the attached screenshot and suggest any modifications you might like before I submit? 
<img width="1246" alt="screen shot 2016-05-05 at 7 55 49 pm" src="https://cloud.githubusercontent.com/assets/10334271/15062370/84d55a18-12fc-11e6-9162-f74d25408c36.png">

**Comment by kytrinyx** [comment]
@cshutchinson Nice! Let's get rid of the bit about not having any unsubmitted problems--that kind of follows from what is said right above it.

I wonder if we should also have a sort of "welcome to exercism!" vibe there. Maybe say something about how each language has instructions about how to install any language-specific dependencies?

**Comment by tejasbubane** [comment]
This can be closed @kytrinyx

**Comment by kytrinyx** [comment]
Thanks!
