### ISSUE TITLE
DEPRECATED Action signature.  Must be `cli.ActionFunc`.

### ISSUE THREAD

**Issue by pschipitsch** [exercism/exercism.io#2858]
When I do (among others):

 ```exercism fetch go```

I get this deprecation message:

```DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature```

**Comment by kytrinyx** [comment]
Did you `go get` or did you download the latest release?

**Comment by pschipitsch** [comment]
I did ```go get```

**Comment by kytrinyx** [comment]
Yeah, they just released a new version of the cli library that we use that is backwards incompatible. We have vendored this. @exercism/cli-committers do you know off the top of your head why go get doesn't use the vendored stuff?

**Comment by Tonkpils** [comment]
@pschipitsch what version of Go are you using? 

Vendor is automatically triggered on Go 1.6. If you're on Go 1.5 you have to `export GO15VENDOREXPERIMENT=true`. If you are in Go 1.4 or less, you need to use `godep go build` to build the binary. 

I'd highly suggest you upgrade your Go version if you're on anything under 1.6.

**Comment by pschipitsch** [comment]
@Tonkpils Thanks.  I upgraded to version 1.6 and after doing ```go get -u github.com/exercism/cli/exercism``` I no longer see the message.

**Comment by Tonkpils** [comment]
@kytrinyx  we should close this since ideally we shouldn't encourage users to install the CLI through `go get`

**Comment by kytrinyx** [comment]
OK, I'll make sure to take it off the description on the site.
