### ISSUE TITLE
Add a link to the relevant activity stream from the code/submission page

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2859]
The normal workflow of submitting exercises on Exercism doesn't give you any encouragement about reviewing other people's code. E.g.

- submit an exercise
- the CLI reports the URL to your submission
- go to the submission
- ... that's it.

We should add a link to the activity stream that corresponds to that language track and exercise, perhaps with text like "see other implementations of $PROBLEM in $LANGUAGE".

The correct link is `/tracks/:track_id/exercises/:problem_slug`.

See discussion in #2803

**Comment by jkrmr** [comment]
@kytrinyx What do you think of this placement?

![screen shot 2016-05-06 at 10 02 49 am](https://cloud.githubusercontent.com/assets/4433943/15075321/bc67ed9a-1371-11e6-9836-27fdf2bf8cfa.jpg)

**Comment by jkrmr** [comment]
Also, this is what's displayed when looking at an archived submission:

![screen shot 2016-05-06 at 11 21 18 am](https://cloud.githubusercontent.com/assets/4433943/15077513/c16c70e4-137c-11e6-8c19-f673079a4c10.jpg)

I wonder if these two views can be merged? (i.e., if both can just display the "see other implementations [etc]" link)

**Comment by jkrmr** [comment]
Another iteration:

![screen shot 2016-05-06 at 11 45 34 am](https://cloud.githubusercontent.com/assets/4433943/15078227/22a9c2be-1380-11e6-8791-c33648de833e.jpg)

**Comment by kytrinyx** [comment]
I like the placement!

Let's get rid of the text that shows up on the archived one--it's legacy cruft. That way we can have the same text always, which is easier to understand when using the site.

/cc @juliatjoy
