### ISSUE TITLE
Add link to "mine" at top of track activity streams

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2860]
We have two activity streams:

1. One for teams which can filter by language, by language/problem, by user, and by user/problem.
1. One for tracks, which filters only by language and language/problem.

On the track activity stream, it would be useful to have a quick way to get to everything by the user who is currently logged in. This would not include archived stuff, since that is the default in streams.

If nobody is logged in, there would be no such menu item.

Here's the current sidebar for track streams:

![activity-stream](https://cloud.githubusercontent.com/assets/276834/14955368/49656b10-102e-11e6-9604-c6ce14320185.png)

The track stream code starts in `lib/exercism/track_stream.rb`. In particular, look at `lib/exercism/track_stream.rb:35` at the method called `menus`. We loop over these menus in the view template in order to produce the sidebar.

We don't currently have a UserFilter for the track stream, but we do have one for the team stream which we could look for. Look at `lib/exercism/track_stream_filters.rb` and `lib/exercism/team_stream_filters.rb`.

See discussion in #2803

**Comment by jkrmr** [comment]
@kytrinyx As a first pass:

![screen shot 2016-05-06 at 10 13 40 am](https://cloud.githubusercontent.com/assets/4433943/15075606/498d5aa6-1373-11e6-81bd-ff289e6cd4c7.jpg)

I'm not entirely sure what to label the filter -- I felt torn between "My solutions" and "My implementations". I'm probably overthinking it, but I wonder if you have any strong feelings either way...

**Comment by kytrinyx** [comment]
I don't have any strong feelings either way, but here's how I've been using words lately:

- solution: refers to code written by a user to solve an exercise. A solution might have many iterations.
- problem/exercise - more or less used interchangeably
- implementation - a language-specific implementation of a problem

Based on that I'd slightly lean towards "solutions" as you have here.

**Comment by ramyaravindranath** [comment]
@kytrinyx : Looking into this.

**Comment by ramyaravindranath** [comment]
@jkrmr Are you still working on the issue ?

**Comment by jkrmr** [comment]
@ramyaravindranath thanks for the ping! I'd actually lost track of this issue. I haven't started work on it yet, and realistically probably won't have time to in the near future, so if you'd like to run with it, go for it.

**Comment by ramyaravindranath** [comment]
@kytrinyx PR for the issue: https://github.com/exercism/exercism.io/pull/3115.

**Comment by Insti** [comment]
Resolved by #3115
