### ISSUE TITLE
Tweak human-friendly date display

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2861]
I saw this tweet by @caike today, and decided that I agree.

https://twitter.com/caike/status/727147399496519680

The discussion clarified:

> when more than 1 day has passed, I’d like to be able to see the actual date - caike

And also this good idea:

> I'm fan of that kind of format, only when there is a title attribute with the Date in a legible format! - arekfu

I think we should change to a format that looks like this "2 November 2016 at 16:00 UTC" for everything that is older than one day, and include a title attribute or tooltip that has the actual date and time for the stuff that's posted in the past day.

The main logic is in `app/helpers/fuzzy_time.rb`, and this is used in the following templates:

- app/views/notifications/index.erb
- app/views/stream/_main.erb
- app/views/submissions/nit.erb
- app/views/submissions/show.erb

**Comment by josepajay** [comment]
@kytrinyx I tried to implement what you suggested. Kindly have a look at my PR.

**Comment by amalrik** [comment]
@kytrinyx i think this could be closed.

**Comment by kotp** [comment]
Thanks @amalrik ...

**Comment by kytrinyx** [comment]
The PR broke the page, so I commented out some of the behavior. I'll open a new ticket explaining what went wrong.
