### ISSUE TITLE
Surface the information about commenting when submitting

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2862]
We added a flag on the CLI so that you can post a comment when submitting a solution to an exercise. These comments are great places to say what you were thinking, what was interesting about the exercise, what did you get stuck on, what surprised you, what trade-offs did you make, etc.

A lot of people don't add comments at all, others do, but they do so from the website.

It would be great to encourage people to use the `--comment` flag when submitting.

The most logical place for this would be on the /cli page.

The route for this is in `app/routes/static.rb`, and the view template is in `app/views/site/cli.erb`, but most of the contents are defined in markdown in `x/docs/md/cli/*`.

There are probably a number of other places where we explain how to submit, both in the main repository and the documentation for the various language tracks. We could catch these later (or do some digging and searching and update them along with this).

See https://github.com/exercism/exercism.io/issues/2803

**Comment by NobbZ** [comment]
Since I haven't anything ready to submit, how does it work?

Am I limited to a single line of comment, can I use heredoc on shells that
do support it? Can I even leave out a value and my editor opens up, as `git
commit` does it?

Katrina Owen <notifications@github.com> schrieb am Mo., 2. Mai 2016 um
18:27 Uhr:

**Comment by kytrinyx** [comment]
You can use heredoc or open up a string with a double-quote and it can be more than one line. I haven't implemented the thing where you leave out the value and it opens up an editor. That would be lovely.
