### ISSUE TITLE
Exercism Restore Not Working

### ISSUE THREAD

**Issue by McEileen** [exercism/exercism.io#2863]
Hi, I recently switched computers and wasn't able to transfer my old hard drive to my new machine.  I want to download all of my completed exercism problems onto my new computer.  However, when I run "exercism restore," it only downloads the original exercises, and doesn't download my solutions.  Any ideas on what's up?

Thanks in advance for your help!

**Comment by kytrinyx** [comment]
Hi, that's definitely a bug. I have a suspicion about what might be going on—I'll get back to you in a moment with an update.

**Comment by kytrinyx** [comment]
Also: so sorry to hear about the hard drive. Such a pain!

**Comment by kytrinyx** [comment]
I can't believe I didn't have a test for this. Amateur hour on Exercism!

**Comment by kytrinyx** [comment]
OK, so I totally had a test, and it was testing it wrong. Amateur hour indeed. Not only that but two separate bugs were in play, both of which could have caused this behaviour separately. I'm so sorry about the mess, please let me know if this works for you.

**Comment by McEileen** [comment]
I just tried it and exercism restore perfectly restored all of my exercises.  Thank you so much!  I was very impressed by your speedy reply :)

**Comment by kytrinyx** [comment]
Yay, glad it worked! Good call on sticking them in git, by the way. I love your super-clever name.

We've been toying with the thought of making exercism run on top of git, but at the moment we decided to not solve underlying technical problems like that, but to figure out how to fix the core experience. Maybe eventually we'll get to fun things like actual real technology :)
