### ISSUE TITLE
Link directly to Launch Checklist in "Help Launch" sections

### ISSUE THREAD

**Issue by joeltaylor** [exercism/exercism.io#2875]
Each non-implemented language has a "Help Us Launch" section [(example)](http://exercism.io/languages/groovy) that includes a link to the track's "Launch Checklist". 

Currently, we're linking to the track repo with search params [(source)](https://github.com/exercism/exercism.io/blob/master/x/docs/md/track/LAUNCH.md) included to direct users to the issue, but once https://github.com/exercism/x-api/issues/109 is merged we can link directly to the issue.

We'll need to add `checklist_issue` to x-api and then pass it on to the LAUNCH.MD.

**Comment by kytrinyx** [comment]
Sweet, I'm looking forward to this change. So much cleaner than the hack we came up with.

**Comment by kytrinyx** [comment]
Good to go!

**Comment by amalrik** [comment]
@kytrinyx is this feature already deployed on x-api?
I just curl to http://x.exercism.io/v3/tracks/groovy and it didn't return the checklist_issue field. 😕 
I can help with this issue if you want.

**Comment by kytrinyx** [comment]
There's an open PR. https://github.com/exercism/x-api/pull/110 I was waiting for the author to make the change, and just saw that he had done so, but not added a comment, so I didn't get a notification. I'll merge and deploy it now.

**Comment by kytrinyx** [comment]
Aaaand the x-api is deploying.

**Comment by joeltaylor** [comment]
Meant to get to this earlier this week, sorry! @amalrik it's all yours if you want or I can get to it this week.

**Comment by amalrik** [comment]
There you go 😃 @kytrinyx  @joeltaylor

**Comment by kytrinyx** [comment]
Aaaand merged. Deploying now.
