### ISSUE TITLE
On private page, "More Languages" button doesn't work

### ISSUE THREAD

**Issue by helenst** [exercism/exercism.io#2876]
If I visit my private profile link when logged out, clicking the "More Languages" button reverts to the public profile view (so asks you to log in via Github). It's available if you build up the URL manually (e.g. http://exercism.io/profiles/helenst/<secret_id>?all=true) but then "Fewer Languages" has the same problem.

**Comment by kytrinyx** [comment]
Ah, we totally forgot about these.

We need to support the same "private" hash on these links.

**Comment by kytrinyx** [comment]
For context, see https://github.com/exercism/exercism.io/pull/2739 and https://github.com/exercism/exercism.io/issues/2731
