### ISSUE TITLE
Sublist's tests should catch people using string search functions

### ISSUE THREAD

**Issue by hop** [exercism/exercism.io#2877]
Well, technically it's OK, I guess, but you should be careful.
See http://exercism.io/submissions/9bd909365e8f4be5b0602c26a498039e .

```
def test_accidental_sublist(self):
    l1 = [1, 0, 0]
    l2 = [100, 2, 3, 4]
    self.assertEqual(UNEQUAL, check_lists(l1, l2))
```

**Comment by kytrinyx** [comment]
I think that this probably is fine to leave as is, since it makes for a really good conversation/discussion with the author of the original code.

@exercism/track-maintainers What do you think?

**Comment by IanWhitney** [comment]
Checking implementation like this always seems fidgety to me. I think it's a great topic for comments/nitpicks.

**Comment by kotp** [comment]
On Sat 2016-05-14 10:04, Ian Whitney wrote:
>Checking implementation like this always seems fidgety to me. I think it's a great topic for comments/nitpicks.

If we need to remember to comment about it, @kytrinyx suggested using
Rikki for something like this regarding defining `each` methods in Ruby.

**Comment by Cohen-Carlisle** [comment]
I like adding the suggested test as it gives immediate feedback. I don't like relying on a reviewer pointing it out on exercism.io as
 * it may not happen
 * if it does happen, the coder may never see it
 * I prefer an immediate failing test to someone maybe catching the problem in a code review.

**Comment by ryanplusplus** [comment]
+1 for adding the test. This really doesn't have anything to do with mandating a particular implementation, it's about enforcing the _correctness_ of an implementation. You can still use string search as long as you join the fields with a delimiter.

**Comment by kytrinyx** [comment]
Yeah, after hearing the arguments for this test from @ryanplusplus and @Cohen-Carlisle I agree. This doesn't specifically check for string / join, it checks for an interesting edge case. Let's add it (and when we add a sublist.json file in x-common, we should add it there too).

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/x-common/pull/227

**Comment by petertseng** [comment]
The case requested in this issue was added at https://github.com/exercism/x-common/pull/438.

**Comment by petertseng** [comment]
Thus, I recommend this issue be closed.

**Comment by kotp** [comment]
I agree.  This is now referenced there as well.
