### ISSUE TITLE
'exercism fetch' already has solution

### ISSUE THREAD

**Issue by RyanMilstead1** [exercism/exercism.io#2882]
So I have been working through the ruby exercises and I use the `exercism fetch` command to download the next exercise (pangram). When I opened the folder I noticed that there was already a pangram.rb file, the solution was already completed and it passed all of the tests. I'm not sure if this is how exercism should function but I wanted to open an issue just to be sure.

**Comment by pschipitsch** [comment]
I experienced the same thing with RNA Transcription in the ruby track.

**Comment by kotp** [comment]
Thanks for reporting.

Can you give a exercism debug report here?  It may give some information that we can use to limit the logs that need to be examined.

**Comment by dannypaz** [comment]
+1. @kotp This has happened to me with `exercism fetch ruby` also. Specifically using fetch for the `hamming` and `gigasecond` exercises. Both contained .rb files with a completed answer. The next exercise: `rna-transcription` was not affected.

**Comment by kotp** [comment]
Thank you very much @dannypaz for the debug and the did and did not happen points.  I think this will help.

@kytrinyx Any hints?

**Comment by kytrinyx** [comment]
Not yet, but I will be digging through this today.

See also: https://github.com/exercism/xruby/issues/315

**Comment by kytrinyx** [comment]
OK, this is so strange. I'm not able to reproduce this at all so far, even if I configure my local environment to pretend that I'm one of these users and then fetch one of the exercises that comes with a solution for them.

@dannypaz if you delete (or rename) the gigasecond folder and then say `exercism fetch ruby gigasecond` again, do you still get the solution?

**Comment by kytrinyx** [comment]
OMG. I have a suspicion about this. I bet I'm mutating the track cache in the API!

**Comment by dannypaz** [comment]
@kytrinyx I tried deleting and renaming the gigasecond folder. I was not able to reproduce when using `exercism fetch ruby <exercise_name>`.

**Comment by kytrinyx** [comment]
@dannypaz thanks.

Update: so far, no luck finding a place where I'm mutating the track cache in the API. Still digging.

**Comment by kytrinyx** [comment]
Wow. OK, so on heroku I get a different result from locally on this:

```
Xapi.tracks['ruby'].implementations['gigasecond'].dup.files.object_id
Xapi.tracks['ruby'].implementations['gigasecond'].files.object_id
```

On Heroku they are the same, locally they are not. Therefore, locally I am _not_ mutating the cache, but on Heroku I am.

This is what is causing the bug, I'll change the implementation.

**Comment by dannypaz** [comment]
@kytrinyx you. are. awesome. Is this something in lib/tracks in `x-api`?

**Comment by kytrinyx** [comment]
it's in the `api/v1/routes/exercises.rb` file in the restore endpoint.

**Comment by kytrinyx** [comment]
OK, deploying now.

**Comment by kytrinyx** [comment]
For what it's worth, this is the ruby version on Heroku vs my machine:

```
$ heroku run ruby --version
Running ruby --version on exercism-x-api... up, run.6604
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
~/code/exercism/x-api $ ruby --version
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin12.0]
```

So... same patch level, same revision number, only difference is platform.

**Comment by kytrinyx** [comment]
Update on the bug, this was due to memoization, not a difference in environments. Apparently I checked differently on heroku and locally.

This script gets different object ids in both places:

```
require 'bundler'; Bundler.require; require_relative 'lib/xapi'
Xapi.tracks['ruby'].implementations['gigasecond'].dup.files.object_id
Xapi.tracks['ruby'].implementations['gigasecond'].files.object_id
```

This script gets the same object id in both places:

```
require 'bundler'; Bundler.require; require_relative 'lib/xapi'
Xapi.tracks['ruby'].implementations['gigasecond'].files.object_id
Xapi.tracks['ruby'].implementations['gigasecond'].dup.files.object_id
```
