### ISSUE TITLE
Activity stream not sending me to /notifications.

### ISSUE THREAD

**Issue by pschipitsch** [exercism/exercism.io#2887]
I think something is wrong with the Activity Stream button.

I'm getting sent to '/tracks/go/exercises'.  Before I re-authenticated, i was being sent to '/tracks/ruby/exercises/sieve'

**Comment by kotp** [comment]
Why to sieve, and why does sieve make sense?

**Comment by kytrinyx** [comment]
We don't save state, it's a per-session thing. I want to change this, but haven't yet. It will go to the last stream you looked at, unless you've reauthenticated.

It's actually super annoying (but not technically a bug, unless something new happened recently).

**Comment by kytrinyx** [comment]
Activity stream never sends you to /notifications, btw. It shouldn't. The "bell" icon should go to notifications.

**Comment by pschipitsch** [comment]
Yes.  I retracted that part.  I guess the inconsistent behavior is what threw me.

**Comment by pschipitsch** [comment]
@kotp sieve makes sense now after reading @kytrinyx's comment about going to the last stream I looked at.

Thanks for the info!

**Comment by kytrinyx** [comment]
Yeah, I'm going to take a look at how to fix this so that it doesn't feel so arbitrary.
