### ISSUE TITLE
Multi-line comments in Python not properly highlighted

### ISSUE THREAD

**Issue by Peque** [exercism/exercism.io#2891]
It seems that multi-line comments in Python are not highlighted properly. See for example:

![screenshot from 2016-05-17 19-45-27](https://cloud.githubusercontent.com/assets/526577/15333001/18d35de0-1c68-11e6-9add-9f0b51ef43b4.png)

Lines 1 to 3 should be highlighted in red, rather than just the first line, right?

This particular submission [can be found here](http://exercism.io/submissions/205b88badb0d41a18ee78f97c7cc6a36).

**Comment by amalrik** [comment]
I suspect this can be a problem with [rouge gem](https://github.com/jneen/rouge)
I have reproduced the same behavior on my local machine and 
I can take a deeper look at this in worst case at the weekend.

**Comment by amalrik** [comment]
Unfortunately this will require more effort than I thought.
My investigation led me to this class `lib/rouge/formatters/html_exercism.rb` which is where I think the problem belongs but I'm not sure yet why.
I going to try to solve this puzzle again on Thursday.

**Comment by Peque** [comment]
@amalrik May the Force be with you! :muscle:

**Comment by amalrik** [comment]
:smiley: tks!

**Comment by Peque** [comment]
@Insti Is the update in production? If so, it seems it is still an issue, yes:

http://exercism.io/submissions/205b88badb0d41a18ee78f97c7cc6a36

**Comment by Insti** [comment]
@Peque yes it is in, but that code has already been rendered and converted to html, are you able to submit a new iteration?

**Comment by Insti** [comment]
Confirmed still broken: http://exercism.io/submissions/8146d9059e7d4690ae4633b7f2192b95

**Comment by Insti** [comment]
Code renders correctly on the Rouge demo page: http://rouge.jneen.net/pastes/XQGP
![exercism - python syntax highlighting](https://cloud.githubusercontent.com/assets/5096681/17366181/2d594a18-598a-11e6-9dab-4711f14255e9.png)

**Comment by Insti** [comment]
@amalrik do you have any more information/clues that might help solve this?

**Comment by Insti** [comment]
Clue, Pull reqest: #2838
This is the origin of the `lib/rouge/formatters/html_exercism.rb` file.
Maybe something is missing that is in the original `rouge/formatters/html.rb` file (which might have been updated.)?

**Comment by Insti** [comment]
Clue, Issue: #3044
Also happens in OCaml
It seems that when the line numbers are added the 'c' (comment?) css class is not maintained after the first line. So I suspect the problem is with the code that adds the line numbers.
