### ISSUE TITLE
Possible bug on See other implementations of...

### ISSUE THREAD

**Issue by amalrik** [exercism/exercism.io#2894]
On public submissions theres a button to see other implementations of your submitted exercise.
<img width="1325" alt="screen shot 2016-05-18 at 21 35 56" src="https://cloud.githubusercontent.com/assets/801340/15379174/cc3964d2-1d40-11e6-80c6-81ae9d7647d9.png">

But If I click on the link I got a blank page:
<img width="1325" alt="screen shot 2016-05-18 at 21 39 10" src="https://cloud.githubusercontent.com/assets/801340/15379196/0764c01a-1d41-11e6-8382-f44dc4136c65.png">

The same don't happen if you have submitted exercises on the language you are browsing. See:
<img width="1531" alt="screen shot 2016-05-18 at 21 57 00" src="https://cloud.githubusercontent.com/assets/801340/15379432/7a583e6a-1d43-11e6-8213-804da513fa15.png">

Maybe this behavior is desired in order to avoid spoilers of exercises in languages you haven't finished.
But if thats the case, I think the link to other implementations should be omitted.

**Comment by amalrik** [comment]
If confirmed a bug i'm interested in fixed it.
I just need clarification of the desired behavior.

**Comment by kytrinyx** [comment]
Agreed, I think we should omit the link if the person does not have access to the general population of solutions in question.

The way to check this is to see if they have a record in the acls table (it stands for "Access Control List") for the language (this is actually the track_id... we have changed some terminology) and slug in question.

```
                                     Table "public.acls"
   Column   |            Type             |                     Modifiers                     
------------+-----------------------------+---------------------------------------------------
 id         | integer                     | not null default nextval('acls_id_seq'::regclass)
 user_id    | integer                     | not null
 language   | character varying           | not null
 slug       | character varying           | not null
 created_at | timestamp without time zone | not null
 updated_at | timestamp without time zone | not null
Indexes:
    "acls_pkey" PRIMARY KEY, btree (id)
    "index_acls_on_user_id_and_language_and_slug" UNIQUE, btree (user_id, language, slug)
```

There is a model, ACL, for this in `lib/exercism/acl.rb`
