### ISSUE TITLE
Cannot view other's implementation of the solution.

### ISSUE THREAD

**Issue by jealous** [exercism/exercism.io#2897]
Hi,

I think I encounter a bug.  After I submit my solution, I could see it in the site.  
But when I clicked "See other implementations of XXX", I got an error. 
 Here is the link of the error page:
http://exercism.io/tracks/javascript/exercises/bob

And here is the screen shot.
![bug](https://cloud.githubusercontent.com/assets/1789979/15429930/a2e629b2-1ed5-11e6-94ee-9b564b422ab7.png)

I have tried both firefox and chrome.
All "exercises" I have completed have the same issue.
I don't know whether it only happens to my account.

Hope it could be fixed because people won't be able to improve if they can't view/comment solutions of others.
Thanks!

**Comment by kytrinyx** [comment]
Hi! So sorry you ran into this. This is definitely a problem on our end, not on yours. Most likely there's some bad data in there that is blowing things up. I'll dig into it and let you know what I find (unfortunately it might take a couple of days).

In the meanwhile... what does the output of running `exercism debug` on the command-line say?

**Comment by jealous** [comment]
Hi Katrina,

I really appreciate your help!
Here is the output for `exercism debug`.

```
**** Debug Information ****
Exercism CLI Version: 2.2.5
Exercism CLI Latest Release: 2.2.5
OS/Architecture: windows/amd64
Build OS/Architecture /
Home Dir: C:\Users\zhuanc
Config file: C:\Users\zhuanc\.exercism.json
API Key: c6c54abb14b048b3810b93def937ef32
Exercises Directory: c:\work\exercism
Testing API endpoints reachability
        * API: http://exercism.io [connected] 1.0020573s
        * XAPI: http://x.exercism.io [connected] 1.4110807s
        * GitHub API: https://api.github.com/ [connected] 1.4140809s

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except
your API key. Keep that private).
```

Please let me know if you need more information.

**Comment by kytrinyx** [comment]
Thanks so much. I'll be looking at this today.

**Comment by kytrinyx** [comment]
> I don't know whether it only happens to my account.

It is not happening to me on my account, even if I view the exercises that you have completed. I'm investigating further, as I still suspect that there's some bad data involved somewhere.

**Comment by kytrinyx** [comment]
OK, I found and eradicated the bad data. Let me know if this works for you!

**Comment by jealous** [comment]
Hi Katrina,

Thank you so much.  The problem is resolved.

**Comment by daveyarwood** [comment]
I am seeing the same behavior on my account -- could there be more bad data?

Example: http://exercism.io/tracks/kotlin/exercises/hello-world

I am actually seeing this when I click on _any_ "See other implementations of..." link.

```
$ exercism debug

**** Debug Information ****
Exercism CLI Version: 2.3.0
Exercism CLI Latest Release: 2.3.0
OS/Architecture: darwin/amd64
Build OS/Architecture darwin/amd64
Home Dir: /Users/dave
Config file: /Users/dave/.exercism.json
API Key: 5d056f6375e7405d8b4b9941390def2f
Exercises Directory: /Users/dave/Code/exercism
Testing API endpoints reachability
        * GitHub API: https://api.github.com/ [connected] 37.444981ms
        * XAPI: http://x.exercism.io [connected] 122.227981ms
        * API: http://exercism.io [connected] 191.084306ms

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).
```

**Comment by kytrinyx** [comment]
@daveyarwood This is likely. I really need to figure out how to avoid this in the first place. I'm digging into this today.

**Comment by kytrinyx** [comment]
Update—I found and deleted a couple of pieces of bad data, but nothing that should have any effect on the kotlin track, which makes this all the more mysterious. Still digging.

**Comment by daveyarwood** [comment]
@kytrinyx Whatever you did, it fixed my issue! Maybe there was something weird about my user data? The problem I wasn't seeing wasn't just the Kotlin track, I was totally unable to see other users' solutions to the problems I'd solved.

**Comment by kytrinyx** [comment]
Whaaat? That's good in that it's fixed and terrible in that I still don't understand why this is happening.

Thanks for reporting back!
