### ISSUE TITLE
Feature Request - archive more than one exercise at a time

### ISSUE THREAD

**Issue by marioIncandeza** [exercism/exercism.io#2898]
If there's a way to do this already, I haven't found it. Would be nice for lazy people.

**Comment by kytrinyx** [comment]
Haha, yeah :) It would probably be nice for not-lazy people, too.

Maybe we can leverage the profile page which already has checkboxes that let you delete things. Maybe instead of just supporting delete we could support both delete and archive as actions.

**Comment by ramyaravindranath** [comment]
![image](https://cloud.githubusercontent.com/assets/8723247/17173202/aea7fea0-543c-11e6-8db7-527603ae03cc.png)

**Comment by kytrinyx** [comment]
I tend to miss things like this when people don't auto-close related issues with `Closes #123` or `Fixes #123` in their commit or PR.

Thanks for catching it!
