### ISSUE TITLE
bin/setup file does not prepend rake commands with bundle exec

### ISSUE THREAD

**Issue by siakaramalegos** [exercism/exercism.io#2900]
Causes issues for new contributors trying to set up the repo locally. Submitting a pull request for this shortly...

**Comment by kotp** [comment]
Which issues are caused?  Can you outline them?

**Comment by siakaramalegos** [comment]
[Here](http://stackoverflow.com/questions/8106095/why-does-my-environment-require-i-run-bundle-exec) is a good explanation of why prepending `rake` commands with `bundle exec` can be required by some contributors. One reason is multiple versions of `rake` in an environment. Since exercism has multiple contributors using many different environments, cleaning up the bin/setup file to use the full version of the rake commands would make life easier for new contributors.

Also, in the file itself, it already uses `bundle exec` for some commands and not others. I think it's best to be consistent in a way that helps contributors especially since the only purpose of this file is to help contributors.

**Comment by siakaramalegos** [comment]
Just as another example, the user that created PR #2899  also came across this issue.

**Comment by kotp** [comment]
I think that as a project managed with bundler, all commands are meant to be prepended and managed by Bundler, so all commands referring to the project should be `bundle ...`

All contributors should have the need, it is just some contributors may be using tools that are aware, and those tools are doing the needful.

Let's get this knowledge out there that running `bundle exec rubocop` or `bundle exec rake` or other commands should be done under Bundler's influence. 

Let's not have the code internally do this, as it raises maintenance costs, if we should change from Bundler to another tool, all places it was changed to and is currently using it, would need to be changed.

**Comment by siakaramalegos** [comment]
`bundle exec` actually runs the commands within the context of the project's gemfile which is considered more correct. Running `rake` without `bundle exec` in front actually executes the commands in the context of the system's gems rather than the project's gems. Thus, it would be more correct to use `bundle exec`. For more discussion, please see [this](http://stackoverflow.com/questions/8275885/use-bundle-exec-rake-or-just-rake) post.

**Comment by kytrinyx** [comment]
Thanks for bringing this up. I've been super, super lax about all of this, and I'd love some help thinking through what the right approach is so that we can clean it all up throughout the project and in the documentation. It's so frustrating when different users get different experiences (and as a result: different error messages).

**Comment by pschipitsch** [comment]
It would be nice to have the pry command in bin/console also prepended with ```bundle exec```

**Comment by kytrinyx** [comment]
@pschipitsch The current approach is to load the bundled gems inside the script. https://github.com/exercism/exercism.io/blob/master/scripts/console.rb#L3 What are the pros to running it with `bundle exec` instead?

**Comment by siakaramalegos** [comment]
It doesn't work unless you call `bundle exec bin/console`.  See screenshot below - for the second example, I prepended `pry` with `bundle exec` in the file.
![image](https://cloud.githubusercontent.com/assets/4777393/15456331/46d65224-2032-11e6-8634-70142ec81851.png)

**Comment by pschipitsch** [comment]
@kytrinyx I'm not fully sure what causes the error.  Similar to @siakaramalegos, the console script works when I do ```bundle exec bin/console``` or if i prepend the pry command with ```bundle exec```

Here's the error I see:
```
./bin/console 
/Users/pschipitsch/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.5/lib/bundler/runtime.rb:34:in `block in setup': You have already activated coderay 1.1.0, but your Gemfile requires coderay 1.1.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```

**Comment by kytrinyx** [comment]
Ahhhh, OK, thank you. That's definitely a terrible experience, and you're absolutely right that the fix for this is to rip out the bundler stuff from `scripts/console` and change the documentation to always run the `bin/console` command with `bundle exec`.

**Comment by TimMoore** [comment]
OK to close this, now that #2901 is merged?

**Comment by kotp** [comment]
Thanks @TimMoore
