### ISSUE TITLE
Replace PNG track icons with SVG

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2910]
I created an icon for each language track, to use on the site to identify that language. They can be seen here: http://exercism.io/languages

For most language tracks, I tweaked the official language logo to have the exercism "brand" colors (charcoal and pink). We could also use a lighter gray for variation/emphasis where useful.

The copyright etc for language logos is all over the map, so there's an [ATTRIBUTION.md](https://github.com/exercism/exercism.io/blob/master/ATTRIBUTION.md) file that describes what we've found out.

```
# Brand colors
PINK=D81D4E
CHARCOAL=212121
```

Some languages do not have logos, or their logos were too hard to make icons out of (e.g. JavaScript, C++, Objective-C, and PL/SQL), and some languages have such heavy restrictions on the use of their logos that we decided to not even try (e.g. Java).

Right now all of these are PNGs, because that's all I know how to work with (I literally wrote a command-line script that swaps out colors in PNGs... couldn't figure out how to use any graphical software). This is pretty terrible, because it slows down the performance of the site.

I would love to have a proper SVG of each track icon to use on the site. The icons wouldn't need to be exactly what we have, but we would need to make sure that copyright and attribution are dealt with correctly.

Also, for the tracks where I just made something up it would be awesome to have a properly designed icon, but that's totally just a bonus request, and the SVG thing is the main issue here.

In terms of design I really love the general feel of what they have on coderwall badges. It's simple, cute, elegant all at once.

<img width="293" alt="screen shot 2016-11-12 at 2 48 04 pm" src="https://cloud.githubusercontent.com/assets/276834/20240479/29f61804-a8e7-11e6-92fc-4098dd73efef.png">

Obviously I'm not looking to copy, just trying to express something about the type of feeling I'd like the icons to evoke. If possible.

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/discussions/issues/34

**Comment by punithn** [comment]
I have converted all the existing icons to svg. I'll send PRs to each track for replacing the same.

**Comment by tejasbubane** [comment]
I guess we will have to do changes in `x-api` as well. Are there any other things we need to take care of before replacing the icons? How do you suggest we proceed with this? cc @kytrinyx

**Comment by Insti** [comment]
@punithn please add them rather than replacing them.

**Comment by Insti** [comment]
Both `trackler` and `x-api` will need updating.
Although this might be a good opportunity to remove redundant references from `x-api`

**Comment by tejasbubane** [comment]
Ok. So we do this:

- [ ] Add `img/icon.svg` to each track and get all these PRs merged
- [ ] Make necessary changes in `x-api` and `trackler` to use `icon.svg` instead of `icon.png`. Review these changes and deploy
- [ ] Delete `icon.png` from all tracks

Sounds good?

**Comment by kytrinyx** [comment]
I can make a change to x-api to use `svg` if it is available, and `png` if it is not.

I'll do that now.

That way each PR can both add the SVG and remove the PNG.

**Comment by Insti** [comment]
Isn't the correct solution for Trackler to handle all the image stuff? And for x-api ask for 'track.image'?

**Comment by kytrinyx** [comment]
@Insti yes, that's what I ended up doing. It's what Exercism is already doing. I'll release this as soon as I've finished testing it.

**Comment by kytrinyx** [comment]
This is well underway. We support both PNGs and SVGs at the moment, and we've opened issues in all the repos asking for a replacement.
