### ISSUE TITLE
Typo in submission text

### ISSUE THREAD

**Issue by alberthu16** [exercism/exercism.io#2914]
This is what the script currently outputs:

```
Your Ruby solution for Hello World has been submitted. View it here:
http://exercism.io/submissions/503da6b32a8e4e13a7384a4fdfe038c0

See related solutions and get involved here:
http://exercism.iotracks/ruby/exercises/hello-world
```

`http://exercism.iotracks/ruby/exercises/hello-world` is not a valid url

**Comment by alberthu16** [comment]
It should be `http://exercism.io/tracks/ruby/exercises/hello-world`

**Comment by kytrinyx** [comment]
Thanks for the heads up. There's an open pull request to fix this: https://github.com/exercism/cli/pull/319 so I'm going to go ahead and close this (we need to handle configurations both with and without the trailing slash for the host url).

In the meanwhile, you can change your configuration to have the trailing slash on the exercism.io url (see the output of `exercism configure`.

**Comment by alberthu16** [comment]
Thanks!
