### ISSUE TITLE
Markdown code blocks do not display in comments.

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#2915]
When trying to add a markdown code block to a comment on a solution the code block will show up correctly in the preview but not in the submitted comment.

Steps to reproduce:

* Find a solution to comment on
* Add a code block in the markdown using triple backticks "```"
* Preview the comment and see that it looks as you would expect
* Submit comment.
* Note that the code blocks are no longer displayed correctly.

**Comment by kytrinyx** [comment]
Thanks so much for the reproduction steps!

My guess is that we either use different code for handling the markdown of the preview vs the actual comment, or perhaps we have some incorrect HTML that is blowing things up.

The code is a bit of a mess, but the starting point for the page is `app/views/submissions/show.erb`, and then it uses a number of partials (`<%= erb :"some/partial/name", locals: {...} %>`). It also has some angular stuff.

**Comment by Insti** [comment]
What is the 'correct ' newline sequence when storing comments in the database?
On my local dev version all the comments that pre-populated in the database use "\n" but new comments I add via the browser have "\r\n"

If they should be all "\n" then the comments probably need filtering on the way in.

If they can be either then the triple backtick markdown parsing regex needs some tweaking.

Once I know the answer I can make the appropriate fix.

**Comment by Insti** [comment]
For reference: 

Related (closed) issue: #2310 and its PR: 7ea91da42535c33952d3c086f614dd1aebacea47

**Comment by kytrinyx** [comment]
> What is the 'correct ' newline sequence when storing comments in the database?

The database should use `\n`... I bet we have some filtering that translates `\c\r` to `\n` somewhere on preview but not the actual comment. Good find!

**Comment by kytrinyx** [comment]
Actually, the preview is submitted via javascript, and the actual comment is not. There might also be something about the way the javascript is submitting it that is translating the newlines.

**Comment by Insti** [comment]
Ok, I'll do some more investigation into what happens when the comment is submitted.

**Comment by Insti** [comment]
Is it possible that I've got something misconfigured at my end?

**Comment by kytrinyx** [comment]
No, not really. Though it's possible that your setup is different from what most people have. Still, the bug is on our end, not yours.

**Comment by Insti** [comment]
OK. It seems that the preview is submitted by javascript call and therefore has "\n"(%0A) linebreaks. 

The real submit is handled by the browser using "application/x-www-form-urlencoded" and has "\r\n" linebreaks. From the docs [1] 
> Line breaks are represented as "CR LF" pairs (i.e., `%0D%0A').

So I believe the data is going into the database without normalizing line endings.
This is certainly the case on my dev machine and I expect there exists a lot of live data with "\r\n" line endings also.

So, my questions are: 

a) Is it worthwhile normalizing line endings? 
b) Should it be done as a big-bang process where we try to get them all at once?
c) Should we just normalize the input to various routes as we find it necessary?
or
d) Should we just accept that there will be different line endings and make the code that needs to care about line endings take care of itself?
e) Something else?


References: 
[1] http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4

**Comment by kytrinyx** [comment]
> Is it worthwhile normalizing line endings? 

I think that we should probably normalize line-endings on the way in.

> Should it be done as a big-bang process where we try to get them all at once?

No, I think that if we take care of

- code submissions
- comments

then any further problems could be dealt with when they come up.

> Should we just accept that there will be different line endings and make the code that needs to care about line endings take care of itself?

If we do this, then we will be processing the same bit of text over and over. I'd rather do the processing just once.

Am I missing any gotchas with this?

**Comment by mhelmetag** [comment]
Well we save all of the comments in the db as processed markdown but some type of frontend sanitization couldn't hurt. I wonder if loofah does that I could throw in a log before and after running the comment through loofah (before redcarpet) to see what happens.

**Comment by Insti** [comment]
In order to keep changes small and logically grouped, I've fixed the markdown block bug (#3007) and created a new issue for normalizing the line endings (#3008) further discussion about line endings should take place there.
