### ISSUE TITLE
500 errors on exercise and team pages

### ISSUE THREAD

**Issue by suzannehamilton** [exercism/exercism.io#2916]
I've been seeing 500 errors on exercism.io today from a few of the pages. I've seen consistent errors (i.e. refreshing doesn't fix the problem) on these pages:

* Exercise summary pages, e.g. http://exercism.io/tracks/ruby/exercises/grade-school
* http://exercism.io/inbox, which redirects to the last exercise summary page I visited
* http://exercism.io/teams/softwire/streams (the only team I'm a member of, so I don't know if this happens on other team pages)

I haven't seen errors on any other pages.

Possibly related: http://x.exercism.io/v2/exercises/restore?key=my_api_key also returns a 500 error. (I realise the API is a separate project - I can also raise an x-api ticket if you like.)

Also possibly related, but possibly a complete red herring: I submitted an exercise a few days ago which got into a really weird state: http://exercism.io/submissions/1599c4ac548c4e3e9b06fa4302bf5bf0

It's a solution to the nucleotide-count problem on the Java track, but the exercise has been named "Java" and it appears to have no track. 😬 

![screen shot 2016-05-30 at 15 10 16](https://cloud.githubusercontent.com/assets/754712/15651650/dcbc7fc4-2678-11e6-8c9f-4cfd8d6b8ce5.png)

I think this might have happened because I was using an old version of the Windows command-line client. When I saw that something had gone wrong, I upgraded the client to the latest version and resubmitted the exercise successfully. (I should have raised an issue at that point, sorry!)

I use this Github account for Exercism, so my profile is at http://exercism.io/suzannehamilton

**Comment by kytrinyx** [comment]
Thanks so much for the heads up! I'll debug this (no need to open a separate ticket for the x-api).

> I think this might have happened because I was using an old version of the Windows command-line client. 

Ah! Yeah, I'm pretty sure that's it. If you happen to know which version of the windows client you had, I'd love to see if I can fix the API to work with it (or at least reliably complain and suggest that one should upgrade).

**Comment by kytrinyx** [comment]
OK, I ran my script to clean up the accidental bad data from these old clients... would you check if this fixes it for you?

**Comment by suzannehamilton** [comment]
Amazing, thanks!

Yes, that fixes all the errors (including the API "restore" one).

Not totally sure what the old client version was because I replaced the exe when I upgraded, but my best guess from what's in my Downloads folder is 1.9.2.

**Comment by kytrinyx** [comment]
Thanks! I'm going to close this, and open a ticket specifically to investigate the old client issue.
