### ISSUE TITLE
Create a new page exercism.io/repositories

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2924]
It would be lovely to be able to explain succinctly which github repositories are for what, in a reasonable order, and leave off all the legacy stuff, the experiments, and the tools that really aren't important the first time you want to get an overview over the project. We could also link to it from the new "contribute to exercism" page (https://github.com/exercism/exercism.io/pull/2918).

I think the relevant repositories to include are:

**The Basic Components**

- github.com/exercism/exercism.io - the main website
- github.com/exercism/x-api - the problems API (this is going to get absorbed into exercism/exercism.io as soon as I have the time to make it happen, but the x-api will need to exist for a long time because old exercism command line clients will still point to it).
- github.com/exercism/cli - the command-line client

**The Language Tracks**

Here we can loop through all the existing tracks like we do for the /languages page (https://github.com/exercism/exercism.io/blob/6af63b81b9c280d2db7394aeee604274a5de2013/app/routes/languages.rb#L6)

**Interesting Tools**

- github.com/exercism/rikki - Rikki, the friendly neighborhood code review robot
- github.com/exercism/blazon - Blazon, which helps us manage cross-track issues

**Comment by kytrinyx** [comment]
Ref: https://github.com/exercism/discussions/issues/34

**Comment by ramyaravindranath** [comment]
Hey @gusseting and I are working on this. Will keep you posted on this.

**Comment by mhelmetag** [comment]
There's some interesting info here about the main repo (here)[https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#exercism-web-structure].

**Comment by nickborromeo** [comment]
@mhelmetag can we close out this issue?
