### ISSUE TITLE
Move language track icons into track repositories

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2925]
It doesn't make sense to keep track-specific content in the main repository. It would be much easier to manage if this were in the respective language track repositories.

I suggest that we:
- Add a directory named `img/` in each track repository at the root level (if it doesn't already exist).
- Put the icon in here as `icon.png` and optionally `icon.svg`
- Serve the track icon from x-api
- Provide the URL to the track icon in the basic track data that x-api serves up

**Comment by joeltaylor** [comment]
On it!

I imagine that this should also be added to future course checklists?

**Comment by kytrinyx** [comment]
Yepp! In here somewhere https://github.com/exercism/x-template

**Comment by joeltaylor** [comment]
Encountered a _slight_ setback. I'm uncertain of the best approach for grabbing track images for objects that have a `track_id` (e.g. iterations, submissions).

I almost considered making an API call in the [track_image](https://github.com/joeltaylor/exercism.io/blob/f8acfda4db6f6cddeabc0412a78f3db07ee79c1b/app/helpers/track_image.rb) helper, but I think that might be too much for a view helper. 

Instead, I'm thinking I'll create a helper for the routes that can be responsible for fetching a track's image url. The fun part will be associating the images with the appropriate objects before sending everything to the view (e.g. [notifications route](https://github.com/exercism/exercism.io/blob/master/app/routes/notifications.rb#L8))

Wonder if it's worth caching track images?  Not sure what sort of load Exercism is under, but I can imagine those API calls adding up when someone has a large amount of notifications.

**Comment by kytrinyx** [comment]
I'm going to inline the whole x-api into exercism.io, so the HTTP calls will go away eventually.

In the meanwhile I think we should deliver the url for the images along with the rest of the track-level data, which I believe gets cached. It's accessed via `::X::Track.find(id)`.

**Comment by kytrinyx** [comment]
Oh, I think that's what you did over in #2941 except that the x-api isn't delivering the images yet.

**Comment by joeltaylor** [comment]
Ah, ok  - I  saw that method and assumed it was a separate API call. It'll work perfectly! Inlining x-api sounds interesting, excited to see what that looks like.

I've been serving the images locally with x-api. I'll go ahead and submit a PR for that :smile:

Thanks!

**Comment by joeltaylor** [comment]
> Provide the URL to the track icon in the basic track data that x-api serves up

I've created this endpoint in a [PR](https://github.com/exercism/x-api/pull/112) - `x.exercism.io/v3/tracks/:track_id/img/icon`?  It allows for a track to add the icon filetype to their config.json

**Comment by kytrinyx** [comment]
Let's provide the endpoint rather than assuming it—that way we can change our mind about where we serve it from without the web app having to know about the change.

**Comment by joeltaylor** [comment]
That makes sense. The moment I typed the word "assumption" I knew something wasn't right there. Thanks for the feedback! Should be able to get to these changes tonight.

**Comment by kytrinyx** [comment]
> Should be able to get to these changes tonight.

Excellent. I'm writing up that blazon issue now.

**Comment by petemcfarlane** [comment]
I tried to submit a PR for the xphp track but came up with this error in Travis:

>$ ./bin/configlet .
Evaluating .
-> config.json does not include [img].
The command "./bin/configlet ." exited with 1.

Does anyone know how to solve this?

Thanks

**Comment by kytrinyx** [comment]
Yeah, stick "img" in the "ignored" section in the config.json.

**Comment by petemcfarlane** [comment]
eureka!

**Comment by kytrinyx** [comment]
Aaaaand: @ryanplusplus is updating configlet to ignore the img directory by default, so once that's done we won't have to stick it in the config.

**Comment by martinsvalin** [comment]
I noticed the list of opened issues stopped at `exercism/xr`, so I figured whatever script created them aborted at that point. I've opened PRs for the languages that the script missed.

**Comment by kytrinyx** [comment]
Dammit. I bet I got rate limited and my script didn't report it. Thank you!

**Comment by kytrinyx** [comment]
This has been done.
