### ISSUE TITLE
Disappearing notifications

### ISSUE THREAD

**Issue by jessbowers** [exercism/exercism.io#2926]
It would also be useful if notifications remained visible for longer. I just had 2 notificaitons, clicked on the first one, then hit the notification icon again. When returned to the notification screen, I saw no notifications and no way to unarchive them.

**Comment by kytrinyx** [comment]
Notifications on exercism work the same way that notifications do on GitHub, but this has come up before so we may have to rethink it. In this case it sounds like both notifications were for the same iteration of the same solution (two comments? An iteration and a comment?).

There's also the "recently viewed" page, if that helps.

**Comment by jessbowers** [comment]
Paying close attention today when this happened again, you are correct. Thanks!
