### ISSUE TITLE
exercism over https gives certificate error

### ISSUE THREAD

**Issue by cdman** [exercism/exercism.io#2930]
Hello,

Accessing exercism over HTTPS (ie. https://exercism.io/) gives a certificate error stating that the served certificate contains domain names different from exercism.io ( a.ssl.fastly.net, *.a.ssl.fastly.net, fast.wistia.com, etc). I guess that this could be fixed by setting some SSL related settings on Fastly? I think this describes how to do it: https://docs.fastly.com/guides/securing-communications/setting-up-free-tls

Alternatively, Cloudflare and Let's Encrypt are other solutions to provide (free) HTTPS, however these solutions would need to change more in the way the site is hosted.

BTW, @kytrinyx - congrats for making #2 on the list: http://blog.sourced.tech/post/100-awesome-women-in-the-open-source-community-you-should-know/ :smile_cat:

**Comment by kytrinyx** [comment]
Hi, thanks for the heads up. Yeah, I'm pretty sure the folks at Fastly will be able to help me out with that!

I looked into lets encrypt, but since we're hosting on heroku, it became extremely expensive. I've been talking to a few folks about some of these issues (if you're interested/curious).

- https://github.com/exercism/discussions/issues/23
- https://github.com/exercism/exercism.io/issues/2589

Also, thanks :-)

**Comment by mhelmetag** [comment]
https://blog.heroku.com/archives/2016/5/18/announcing_heroku_free_ssl_beta_and_flexible_dyno_hours

Just saw this in an email about this today. Could be of interest in the mean time while exercism is still on heroku.

**Comment by mhelmetag** [comment]
https://blog.heroku.com/archives/2016/5/18/announcing_heroku_free_ssl_beta_and_flexible_dyno_hours

So if we get the free ssl certs, it might not be all that expensive anymore.

**Comment by kytrinyx** [comment]
Yes! That is awesome. We've got plenty of time, so we should just do this.

**Comment by mhelmetag** [comment]
Okay so I looked into this a bit more.

Seems like this is a pretty good way to set things up:
http://collectiveidea.com/blog/archives/2016/01/12/lets-encrypt-with-a-rails-app-on-heroku/

Then all we need is a auto cert updater using something like this:
https://github.com/unixcharles/acme-client

I'm going to look into getting a little mockup going on my heroku exercism.

**Comment by cdman** [comment]
Thank you for taking care of this :+1:

**Comment by kytrinyx** [comment]
I'm going to close this in favor of the discussion in https://github.com/exercism/exercism.io/issues/2589
