### ISSUE TITLE
Suggestion message to contribute to completed languages on user's profile is visible to all users

### ISSUE THREAD

**Issue by rbndickson** [exercism/exercism.io#2932]
When looking at another users profile this message was visible:

> Contribute:
> You've completed the following tracks. Want to help add more exercises?
> 
> Lang 1
> Lang 2

From the "You've" I'd expect this to only be visible to the profile's owner.

**Comment by kytrinyx** [comment]
Indeed. Thanks for the heads up. @GustavoCaso would you have time to look at this today?

**Comment by GustavoCaso** [comment]
Sure @kytrinyx no problem

**Comment by kytrinyx** [comment]
Deploying the fix now.

**Comment by rbndickson** [comment]
Wow that was quick, thanks!
