### ISSUE TITLE
Contribute to track page lists deprecated exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism.io#2938]
The quite new (and awesome!) page that lists the not implemented exercises, lists deprecated exercises.

For example, the F# track's [contribute page](http://exercism.io/languages/fsharp/contribute) lists the [point-mutations](https://github.com/exercism/x-common/blob/master/point-mutations.md) exercise:

![image](https://cloud.githubusercontent.com/assets/135246/15856201/6cd16f3e-2cb4-11e6-82c0-15fb976552a1.png)

Upon further investigation, I found that the `deprecated` section in the F# language track's [`config.json`](https://github.com/exercism/xfsharp/blob/master/config.json) file is empty. Should I add the `point-mutations` exercise there, or is there some master list of deprecated exercises that the contribute page should look at?

**Comment by kytrinyx** [comment]
It is an awesome page :) I'm pretty excited about it.

I think we should add globally-deprecated things to the API side of things so that we filter them out for all the languages.

I've been wanting to re-arrange the x-common repository. I think that would be the right place for it. I'll open an issue there and refer back to this one.

**Comment by kytrinyx** [comment]
I've opened the issue here: https://github.com/exercism/x-common/issues/269

**Comment by petertseng** [comment]
Duplicate of #3103

Can close now, right? https://github.com/exercism/x-api/pull/140 and the specific exercises mentioned are now `.deprecated`.

**Comment by petertseng** [comment]
by https://github.com/exercism/x-common/pull/406

**Comment by ErikSchierboom** [comment]
@petertseng Ah yes, this can be closed. Sorry about that.
