### ISSUE TITLE
Explain the origin of the name "exercism" as well as the e-with-horns logo

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2940]
I realized that this is not written down anywhere, and it's not at all obvious.

The origin of the name is a pun on **exercise**.

The way that I think about these exercises, is that they are small, trivial, and seemingly simple. The phrase that came to mind for this was _the devil is in the details_, which is an idiomatic phrase that means **It might seem simple on the surface, but once you start looking at the details, it really isn't**.

The logo came about because I mentioned the idea of _the devil is in the details_ to the designer who made it.

This is not related to actual demons or the Devil. I've never thought of this as having "evil code" that you improve.

**Comment by joeltaylor** [comment]
Took a stab at adding your summary to the About page in third person. Hopefully, I didn't botch it too much!

**Comment by kytrinyx** [comment]
That looks so good. Thank you :heart:
