### ISSUE TITLE
python, word-count, unicode

### ISSUE THREAD

**Issue by masahx** [exercism/exercism.io#2942]
hi, 

I am using Python IDLE 3.5. In last test of Python word-count exercise there is unicode character "u-1f596". Editor automatically closes because of this character. It crashes if I try to paste any unicode character with more than four hex digits in unicode code. If I try to write '\uXXXXX' - it accepts only first four hex digits as code. How to solve this? Thanks

**Comment by NobbZ** [comment]
Try to figure out if this is idle or python related and then post a bug
report upstream or use a version that does not have that bug.

masahx <notifications@github.com> schrieb am Mo., 13. Juni 2016 13:34:

**Comment by masahx** [comment]
this is IDLE 3.5.1 related thing, I think. Where to post bug report?

**Comment by NobbZ** [comment]
Since IDLE is official I'd try https://bugs.python.org/

masahx <notifications@github.com> schrieb am Mo., 13. Juni 2016 um
13:51 Uhr:

**Comment by masahx** [comment]
I am only one with this problem?

**Comment by kytrinyx** [comment]
I don't know if this is a common experience :/ I'll ask in next week's newsletter.

**Comment by kytrinyx** [comment]
I'm going to close this, as I've not heard anything more about it. If you still are having issues, please open a new issue in https://github.com/exercism/xpython
