### ISSUE TITLE
Viewing and finding teams and general improvements to them

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#2944]
Currently I am able to see which teams a user is a member of when viewing his/her profile page.

But I can't see any details about that team.

So I'd suggest to add the following features to teams:
- Give team-managers the ability to describe the team in a brief.
- Give team-managers the ability to mark a team as “private” or “public” while only “public” teams are shown in a users profile or discoverable via search (later)
- Give team-managers the ability to mark a team as “open” or “closed”, where “open” means, that a user that has discovered the teams profile page may also apply for beeing a member (needs to be approved by manager!)
- Give team-managers the ability to tag a team by focused languages, geographic area, corporations or stuff like that
- Make (public) teams discoverable by a search which can find in name, description and tags (while description should only be searched when requested by the the user explicitely)

The above suggestions are mostly about external presentation of a team as well as its discoverability. The following suggestions are aiming to improve the internal UX of teams but do at least parts of the things above are/gets implemented:
- When there are focused languages, do not show other languages per default on the teams activity stream
- Mark exercises in the activity stream that the current user hasn't implemented himself so far (I accidently spoiled myself a couple of times)
- Send notifications (configurable!) to the other members of a team when a member does an (re) iteration in one of the focused languages

**Comment by kytrinyx** [comment]
> Currently I am able to see which teams a user is a member of when viewing his/her profile page.

I can't remember if this is a conscious decision, but in retrospect I think that I would like to not show this information by default. If we have the resources, we could make showing this opt-in for the user.

> Make (public) teams discoverable by a search which can find in name, description and tags (while description should only be searched when requested by the the user explicitely)

I think I would rather let individuals decide whether a team shows up rather than having team managers decide this.

> Give team-managers the ability to describe the team in a brief.

Yes, if we show the teams on the person's profile page, we should have a description for it.

> Give team-managers the ability to mark a team as “open” or “closed”, where “open” means, that a user that has discovered the teams profile page may also apply for being a member (needs to be approved by manager!)

This is really interesting. This would give us the ability to have a /teams page where open teams are visible, and we could encourage people to join teams. This could have a great effect on people finding like-minded people to get feedback from.

> Give team-managers the ability to tag a team by focused languages, geographic area, corporations or stuff like that

Yepp, if we add a /teams page with open teams that people can apply to, then this would be crucial for finding appropriate teams.

> When there are focused languages, do not show other languages per default on the teams activity stream

Can you elaborate on this one? This would require tracking more information about the team, right?

> Mark exercises in the activity stream that the current user hasn't implemented himself so far (I accidently spoiled myself a couple of times)

Yes, this would be a huge improvement.

> Send notifications (configurable!) to the other members of a team when a member does an (re) iteration in one of the focused languages

Yeah, I want to have fine-grained, configurable subscriptions for a lot of things. At the moment we have subscriptions to conversations. Adding these for teams would be a great addition.

**Comment by NobbZ** [comment]
>>Make (public) teams discoverable by a search which can find in name, description and tags (while description should only be searched when requested by the the user explicitely)

>I think I would rather let individuals decide whether a team shows up rather than having team managers decide this.

Probably you are right, but I am too. Consider a team “secret brotherhood of villains” which trys to gather enough knowledge to take over the world through doing exercism. This group wants to stay hidden at all cost by having a team wide flag to do so, and not beeing uncovered because a drunk member ticked the wrong box when cleaning up his teams shown on the profile page.

While of course you are right, as a student I'd like to have a team of my university and show it with pride, while hiding the team created at my sons kindergarten to not tell everyone where it is.

>>When there are focused languages, do not show other languages per default on the teams activity stream

>Can you elaborate on this one? This would require tracking more information about the team, right?

I already told about the idea of assigning tags like a focused language, geographical area, corporations and stuff in a paragraph before. This idea just uses whatever is setup as focused language (or generic tags that happen to be track names?) to filter the activity stream.

Take my current team. We are mostly focused on elixir, second most is ruby stuff, and about 40 members do see my personal junk in roughly 15 tracks they will probably never touch.

So if this gets implemented by default only elixir and ruby would be displayd, as well as a hint that there are a bazillion of unread stuff in hidden languages. You can than either choose elixir or ruby activity stream as you are used to it or click on that note about the hidden stuff, then you will see the full activity stream just as it looks now.

>>Send notifications (configurable!) to the other members of a team when a member does an (re) iteration in one of the focused languages

>Yeah, I want to have fine-grained, configurable subscriptions for a lot of things. At the moment we have subscriptions to conversations. Adding these for teams would be a great addition.

I'm pretty sure there have been discussions about this before, but I wasn't able to find something, so I just put it on the list.

**Comment by kytrinyx** [comment]
> This group wants to stay hidden at all cost by having a team wide flag to do so, and not beeing uncovered because a drunk member ticked the wrong box when cleaning up his teams shown on the profile page.

Yepp, you're right. We need both.

>  This idea just uses whatever is setup as focused language 

Ok, cool, yeah that makes total sense.

Excellent, I think that all of these things are good. Let's work out which things are independent of each other and make a plan for how to implement them (the smaller each task is, the more chance we'll actually get the features).

**Comment by bernardoamc** [comment]
Thinking in terms of complexity I think we could start with the following:

**First Iteration:** 
Since we already showing the teams we could start with the team description. 

**Second Iteration:**
Add a global flag (dictated by the manager) specifying a public/private team.

**Third Iteration:**

- Allowing users to display or not their teams (if the team is not private).
- Allowing users to request membership for a team.
- Adding tags.

There is still a ton of tasks pending, but this should be a good start. @NobbZ since the feedback was yours, what do you think of this "roadmap"? Should we prioritize something else? My suggestions was totally based on complexity, not on the value of each task.

**Comment by NobbZ** [comment]
I don't only think this is sorted by complexity but also follows some
natural order on top of what we already have. I'm still trying to find my
way through the codebase, perhaps I might contribute an item or two in this
issue myself.
Am 24.06.2016 04:31 schrieb "Bernardo Chaves" <notifications@github.com>:

**Comment by bernardoamc** [comment]
Just let me know if you need help. I'm also learning some aspects of the codebase, maybe we can complement our knowledge gaps.

**Comment by kytrinyx** [comment]
I like this roadmap.

I'd even suggest splitting up the third iteration into independent steps, since none of those things depend on the others.

**Comment by bernardoamc** [comment]
I agree, which one of these tasks should take precedence on the third iteration?

**Comment by NobbZ** [comment]
Since the main point of this proposal was to increase discoverability and joinability of teams, I'd prioritize the subtasks of that third iteration like this:

1. Add tags to teams and make them searchable by tags (discoverability)
2. Allow request for membership (joinability)
3. Allow hiding membership to public teams on the profile (decrease discoverability)

**Comment by kytrinyx** [comment]
We don't have anything on the list about implementing search for teams, or a search interface. Where would that go?

If we implement searchability, I would want to implement hiding before search. Exposing private data is something that can't be undone after the fact.

**Comment by bernardoamc** [comment]
Is this roadmap acceptable?

* [x]  ~~Add team description.~~
* [ ] Add a global flag (dictated by the manager) specifying a public/private team. A private team will not be found by a search.
* [ ] Add tags to teams
* [ ] Make teams searchable by tags (discoverability)
* [ ] Allow users to request membership for a team.
* [ ] Allowing users to display or not their teams (if the team is not private).

**Comment by kytrinyx** [comment]
This looks excellent!

**Comment by bernardoamc** [comment]
Now we can finally implement tags, but I would like to discuss the implementation since we have several options to tackle this. I'm considering the following:

- Add a `tags` column (array of strings).
- Make sure every tag is downcased (investigate the use of `citext` with arrays)
- Use the  `gin` index.

I think this approach is simple and performs well, but we don't have an easy way of suggesting tags for example during the creating and searching teams steps.

Suggestions?

**Comment by NobbZ** [comment]
I'm not quite sure what `gin`-index means.

But according to normalform, wouldn't be a table with tags and a many-to-many more appropriate?

This way tags were browsable by itself, and we could suggest/complete them.

I do not know how performant this is. I do see that having another 2 tables costs its price though.

**Comment by bernardoamc** [comment]
> I'm not quite sure what gin-index means.

It's a type of index so we can avoid a sequential scan in our table.

> But according to normalform, wouldn't be a table with tags and a many-to-many more appropriate?
> This way tags were browsable by itself, and we could suggest/complete them.
> I do not know how performant this is. I do see that having another 2 tables costs its price though.

Yeah, it does not perform so well. We can try a mixed approach, we can create a table for tags and an array column in the teams table and store the ids. This way we can search by tags using the table but still have good performance during a search. The only problem is that we will need to query twice, one for fetching the id of a tag and the other for fetching the teams that have this id stored. What do you think?

**Comment by NobbZ** [comment]
I think that tags that I can't browse directly or not getting suggestions
rather useless. Querrying twice sound wrong as well. I don't know how well
it is supported by ar or the underlying FH engine. But can we died
something using views?
Am 07.07.2016 15:24 schrieb "Bernardo Chaves" <notifications@github.com>:

**Comment by bernardoamc** [comment]
Not that I can think of, but could be possible. So far a tags table with tags column in the teams table give us all the benefits, but as you said querying twice is not ideal.

**Comment by bernardoamc** [comment]
I will give it a try, we can test the performance during development.

**Comment by bernardoamc** [comment]
Now that we can search teams the next step will be allowing users to request membership for a team.

What I am thinking for this feature:

- Add a button to request membership on the `/teams` page.
- Add a section called "Membership requests" on the `/teams/:team/manage` page.
- Notify the current team manager about a request (this would involve adding some code to `app/presenters/inbox.rb` and `"app/views/notifications/index.erb`).

We have to add something on the database side responsible for storing a membership request. Currently we have a `confirmed` column on the `team_memberships` table, but this will not suffice anymore. It can be a column, but we would have to deal with two boolean columns (`confirmed` and `request`) and check both of them to see if an user has been invited or has requested membership instead.

@kytrinyx @NobbZ Thoughts on this?

**Comment by kytrinyx** [comment]
I think this plan makes sense. I don't think app/presenters/inbox.rb is the right place (we have some very odd and confusing naming, I think the inbox is the track activity stream). In the notifications page we already show team invitations with buttons to accept/decline, I think it makes sense to include the team access requests as well.

I think it would make sense to use the `team_memberships` table, though like you say we can't use it straight up.

```
exercism_development=# \d team_memberships
                                     Table "public.team_memberships"
   Column   |            Type             |                           Modifiers                           
------------+-----------------------------+---------------------------------------------------------------
 id         | integer                     | not null default nextval('team_memberships_id_seq'::regclass)
 team_id    | integer                     | not null
 user_id    | integer                     | not null
 confirmed  | boolean                     | 
 created_at | timestamp without time zone | not null
 updated_at | timestamp without time zone | not null
 inviter_id | integer                     | 
Indexes:
    "team_memberships_pkey" PRIMARY KEY, btree (id)
```

What if we have two ways of being confirmed. Either you're invited and you confirm, or you request and get confirmed. So in order to check actual memberships, we would still just have the same boolean field, but in order to look for invitations, we would check for confirmed='f' and inviter_id not null, and for requests we would look for confirmed='f' and requested_at not null or something like that.

**Comment by bernardoamc** [comment]
> What if we have two ways of being confirmed. Either you're invited and you confirm, or you request and get confirmed. So in order to check actual memberships, we would still just have the same boolean field, but in order to look for invitations, we would check for confirmed='f' and inviter_id not null, and for requests we would look for confirmed='f' and requested_at not null or something like that.

Right! We have inviter_id, we can't totally use this to decide if someone was invited or has requested membership. 👍 

> I don't think app/presenters/inbox.rb is the right place (we have some very odd and confusing naming, I think the inbox is the track activity stream).

Currently the `/notifications` page uses `ExercismWeb::Presenters::Inbox` to build the notifications page (I think), I will investigate a little more.

We also have to add an option for the manager to **refuse** a request, totally forgot this.

**Comment by kytrinyx** [comment]
> Currently the /notifications page uses ExercismWeb::Presenters::Inbox to build the notifications page (I think), I will investigate a little more.

Oh, wait. Yeah, I think you're right.

> We also have to add an option for the manager to refuse a request, totally forgot this.

Me too :)

Maybe we need a second boolean field, `denied`. Hm. This is getting a bit dirty.

**Comment by bernardoamc** [comment]
> This is getting a bit dirty.

Indeed! 😅  Suddenly we have to check for `confirmed='f'` and `inviter_id` is not null and `denied='f'`. I don't know if it is premature to extract this to a table called `team_membership_requests`.

**Comment by kytrinyx** [comment]
Hm. Yeah.

How about having requests in a separate table, and invitations in a separate table, and then if you have a row in the memberships, you're a member. No "confirmed" necessary.

**Comment by bernardoamc** [comment]
> How about having requests in a separate table, and invitations in a separate table, and then if you have a row in the memberships, you're a member. No "confirmed" necessary.

I think this is the correct choice. It would be something like:

team_membership_requests:

- team_id
- user_id
- inviter_id
- denied
- created_at
- updated_at

team_membership_invites:

- team_id
- user_id
- created_at
- updated_at

team_memberships:

- team_id
- user_id
- created_at
- updated_at

**Comment by bernardoamc** [comment]
Or we can drop the `denied` column from `team_membership_requests` and simply remove the row if the team manager denies the request. Do we want to keep denied entries?  If we want we need to add a column called `refused` to the`team_membership_invites`. :)

**Comment by Insti** [comment]
Isn't an invite just a membership_request where inviter_id = [a current member]?

**Comment by bernardoamc** [comment]
> Isn't an invite just a membership_request where inviter_id = [a current member]?

It is indeed! I think the only difference is the person who accepts/refuse the request. In the case of a request it is the team manager and in the case of a invite the user. So you are suggesting that we can have only a `team_membership_requests` table and manage it based on the `inviter_id` value?

**Comment by Insti** [comment]
> you are suggesting that we can have only a team_membership_requests table and manage it based on the inviter_id value?

Yes.

**Comment by bernardoamc** [comment]
Sounds good to me, looks like I was over complicating things. Thanks @Insti !

**Comment by Insti** [comment]
@bernardoamc I'm worried I'm complicating things by overloading the function of the inviter_id column and maybe 2 tables is the way to go.

**Comment by bernardoamc** [comment]
> I'm worried I'm complicating things by overloading the function of the inviter_id column and maybe 2 tables is the way to go.

It really depends on the way we can express this in the code. For now a single table would work well, but if we need to add columns for specific scenarios in the future it would be better to have two tables. I don't have a strong opinion about these alternatives, we can always change things later...

Since both approaches will take a similar amount of time let's go with the two tables approach.

**Comment by kytrinyx** [comment]
I think going with two tables will keep things easier to understand, even though it's a bit more complexity.

**Comment by bernardoamc** [comment]
We are finally in a good state to add the link to search for teams. 🎉  

Ideas?

**Comment by kytrinyx** [comment]
@bernardoamc Yay! How about on the dashboard?

**Comment by bernardoamc** [comment]
@kytrinyx Seems like a good place, below `Your Teams` section?

**Comment by kytrinyx** [comment]
@bernardoamc Yepp, let's do that.

**Comment by NobbZ** [comment]
As already briefly said in #3362, this issue shall be split into multiple separate ones.

I will walk through this pile of messages about this evening (European Time) and split it up, trying to incorporate the discussion here and already implemented things.

**Comment by NobbZ** [comment]
As far as I can see, only a single Item from my original proposal is left open, and that's the "focused language" via tags. So I think we should close this one and leave #3362 as a tracking issue for the idea of a focused language.

**Comment by kytrinyx** [comment]
Yeah, I concur. Thanks for sorting that out @NobbZ
