### ISSUE TITLE
filter already read submissions in the activity stream

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#2945]
I like to look at and comment old submissions which haven't been commented so far. Because of this, I do have a lot of already read pages at the end of a tracks activity stream and I have to click through to actually find the last page with submissions I haven't read so far.

Therefore I'd like to filter already read submissions from the activity stream.

**Comment by kytrinyx** [comment]
💯 

If someone wants to help define what work would have to happen to implement this, it would be easier for someone who is not familiar with the project to tackle the issue.

**Comment by bernardoamc** [comment]
I was inspecting this and it looks like we have to change these files:

- `app/routes/tracks.rb`
- `lib/exercism/track_stream.rb`
- `app/views/stream/_main.erb` or `app/views/track_stream/index.erb`

These files are linked to the `Activity Stream`, there are other files involved if we want to also add this option to the `Team Stream`.

**Comment by kytrinyx** [comment]
I think you're right.

What should the user interface look like. Remember the idea of "mine" as a menu/filter in the sidebar? https://github.com/exercism/exercism.io/issues/2860 Should this be something like this where you can filter a language/problem by "no comments"?

**Comment by bernardoamc** [comment]
What do you think of transforming the `unread` number as a filter on its own?

![screen shot 2016-06-21 at 2 06 43 am](https://cloud.githubusercontent.com/assets/428984/16218503/e056d282-3754-11e6-817c-dfd850d52922.png)

Clicking on the number `3` in `(3) Ruby   4` would display only unread exercises (3 in this case).

**Comment by kytrinyx** [comment]
That's clever. I don't know how discoverable it is, but it would be kind of nice to not have more visual elements. (I am not a designer, I might be very, very wrong about this).

**Comment by NobbZ** [comment]
I'm not sure if I really like that way for the following reasons:

* The unreadcount has a rather small area, might be hard to hit on
  mobile devices.

* It is not obvious that it might have a meaning different from the rest
  of the same button.

Katrina Owen writes:

**Comment by kytrinyx** [comment]
Both of those points are good.

I think I'm now convinced that we should go with the same sort of idea as the "mine" thing.

**Comment by bernardoamc** [comment]
Really good points. 👍 

How would this "mine" thing work? Do we have a simple mock to help me visualize the layout?

**Comment by kytrinyx** [comment]
> How would this "mine" thing work? Do we have a simple mock to help me visualize the layout?

Yeah I was thinking we could add it as a separate option:

![screen shot 2016-05-06 at 10 13 40 am](https://cloud.githubusercontent.com/assets/4433943/15075606/498d5aa6-1373-11e6-81bd-ff289e6cd4c7.jpg)

But now that I think of it, we would potentially want:

-> language
    -> slug
        -> unanswered

and also

-> language
    -> unanswered

**Comment by bernardoamc** [comment]
Just throwing ideas, could an [accordion](http://getbootstrap.com/javascript/#collapse-example-accordion) work here?

We would click on the language and it would display some options:

- All
-  Unanswered (or unread)

**Comment by kytrinyx** [comment]
If possible, I want to make it so the default case doesn't require an extra click.

**Comment by bernardoamc** [comment]
Fair enough, but in this case we would need two requests to filter unanswered submissions (one after the click in the language to see all submissions and expand the accordion and another one after the click on the unanswered option). Looks like an accordion is not the way to go here after all?

**Comment by kytrinyx** [comment]
I don't know. Maybe there could be a setting that people turn on for the page, and then clicking anything within it would keep the setting?

**Comment by bernardoamc** [comment]
Maybe! Design is so hard! ;)

I'm out of ideas for now, I would like something intuitive that don't change the current layout so much since I like it.

**Comment by kytrinyx** [comment]
Agreed—I also like the current layout. It's been much easier to use than any of the earlier iterations/attempts.

**Comment by NobbZ** [comment]
There is already the "mark all read" in the upper right corner of the actual stream, what if we add "show only read" at the upper left corner?

Culprit is, that whenever they need to swap because of some contrived reason that will kill the activity stream of many users, as well when they are to close of each other the beginning…

Hard…

**Comment by kytrinyx** [comment]
> "show only read"

What is the use case / workflow that you're solving with this? I don't think I've ever wanted/needed a "show only read" option.

**Comment by NobbZ** [comment]
Totally my fault… I do not want to do anything with such a thing ;) It was more of starting to write a halfthought label, changing the mind halfway through and not correcting what was already there…

I wanted “show only unread” first, but changed my mind to “hide read” inbetween and now we do have that totally useless filter which does show me everything I already know, but hides everything I really want to see, the new stuff ;)

**Comment by kytrinyx** [comment]
That makes a lot more sense! :)

**Comment by bernardoamc** [comment]
I think we can go with "Show only unread" button for now, it is easier to start with something simple like this and create the functionality, we can always change things during development.

**Comment by bernardoamc** [comment]
Looks like things will be more difficult than planned since we can't do a `join` with the `views` table according to [this](https://github.com/exercism/exercism.io/blob/master/lib/exercism/track_stream.rb#L50) comment.

@kytrinyx Do you know if this is still an issue? I'm guessing it is.

**Comment by kytrinyx** [comment]
We might be able to create a view that we could join against. I'm not sure how it would perform, though.

**Comment by kytrinyx** [comment]
I'm trying to think of another approach to this :/ At the moment, no such luck.

**Comment by bernardoamc** [comment]
We are on the same boat, could not think on an alternative solution. :(

**Comment by kytrinyx** [comment]
This is something that we will likely need to address by reconsidering the data model.

I've added the design research label to this so that we can evaluate the question within the larger context of the design reboot (see https://github.com/exercism/discussions/issues/113 for more about this).

Since this issue addresses things that are going to be difficult to implement as a quick experiment in the current prototype, I'm going to close this. If you do think that it can be implemented as a not-too jarring and not-too complicated experiment in the current website, please open a new issue about it in the discussions repository.
