### ISSUE TITLE
Teams activity stream does show far too many unread submissions

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#2946]
In my team I do have an overall unread count of nearly 600 items, while there are only about 100 items unread over the languages.

![exercism-team-view](https://cloud.githubusercontent.com/assets/58951/16143518/7d8f181a-346d-11e6-8a55-5322daa3cc34.png)

**Comment by bernardoamc** [comment]
Well spotted @NobbZ, thanks!

I will investigate this one soon (probably tomorrow).
