### ISSUE TITLE
Fetching File in Big-5 by Default, Windows 64-bit

### ISSUE THREAD

**Issue by YauHsien** [exercism/exercism.io#2951]
exercism fetched files and got some file in Big-5. How to configure file encoding?

> D:\work\exercism\elixir>exercism
> 
> fetch elixir word-count
> 
> Not Submitted:      1 problem
> elixir (Word Count) D:\work\exercism\elixir\word-count
> 
> New:                1 problem
> elixir (Word Count) D:\work\exercism\elixir\word-count
> 
> unchanged: 0, updated: 0, new: 1

What shown in emacs:
![default](https://cloud.githubusercontent.com/assets/595388/16211410/e33f048c-3773-11e6-8f59-352cd662bf4f.PNG)

**Comment by kotp** [comment]
https://www.emacswiki.org/emacs/UnicodeEncoding may help out here.

**Comment by kytrinyx** [comment]
@YauHsien Since we've not heard back on this I'm hoping that you got it sorted. I'm going to go ahead and close this, but feel free to reopen it if you've not got it figured out yet.
