### ISSUE TITLE
Exercism site crashes and installs trovi search on mac

### ISSUE THREAD

**Issue by hewitt205** [exercism/exercism.io#2952]
After a few minutes on the website safari closes completely and when reopened has trovi search installed. I have removed this with malware bytes thinking it was something else but it has happened every time I am on exercise.io

**Comment by kytrinyx** [comment]
Thanks so much for reporting this!

/cc @exercism/track-maintainers Do any of you have any experience with trovi search hijacking things? Where would the code live that hijacks this? Could someone have submitted an exercise solution that would inject javascript somewhere?

**Comment by kytrinyx** [comment]
I've been trying to figure out how a trovi infestation occurs, and it seems like this would be installed when one downloads something that also installs trovi. There's nothing that I know about in exercism that would do this.

@hewitt205 did you also try removing trovi via the safari preferences/extensions? https://malwaretips.com/blogs/remove-trovi-mac-os-x/#browser

**Comment by Cohen-Carlisle** [comment]
I've also been checking this out and it appears to be very similar to the ask toolbar being bundled with Java; that is, while technically legal because it gets installed with the user's permission, it is bundled in a sneaky fashion and hijacks a lot of browser functionality. It definitely seems like this was installed at some point with "permission" and that the symptoms are merely showing up on exercism because that's just where the browser is.

**Comment by hewitt205** [comment]
I have tried removing through the extensions but it's not there. I've also searched my system using the terminal it also doesn't show there. Using malware bytes is the only thing that seems to work that and changing the start page from trovi to something else

**Comment by kytrinyx** [comment]
I don't know where to go with this one. I'm going to ask in the next newsletter and on twitter to see if anyone has run into this before.

**Comment by hewitt205** [comment]
When I run malwarebytes the threat it finds is adware.vsearch and the path is /library/launchdaemons/com.apple.kimathen.plist
Not sure if that would help or lead anywhere. I found another resource that helped get rid of other files trovi had hidden on my system so I'm going to try recreating my steps to see if it gets back on or if it was just never removed to begin with

**Comment by kytrinyx** [comment]
That sounds like a good plan, @hewitt205. Let us know what you figure out!

**Comment by hewitt205** [comment]
What I've found is that using the network at my work nothing seems to be coming up. So the problem might just be on my personal network. I've been navigating around exercism for a little while, longer than it would normally take to get the issue, and everything seems fine.

**Comment by hewitt205** [comment]
I believe I have narrowed down the issue for trovi to most likely be a residual file from a different incident. The crashing could either be issues safari has had lately and thus not related. Overall I don't believe anything specific to exercism has caused the issues I was having. Thanks for taking a look around though

**Comment by kytrinyx** [comment]
Thanks for following up, @hewitt205! I'm glad you got this sorted.
