### ISSUE TITLE
Reference a couple of conference talks about exercism-ish ideas in the about page

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#2953]
@tejasbubane noted in https://github.com/exercism/exercism.io/pull/2950 by @joeltaylor that

> The idea devil is in the details with exercism's problems is best seen through Katrina's talks.

There are in particular two talks that really make this clear, both of which take an exercism exercise as a starting point:

- https://www.youtube.com/watch?v=GWEEPt8VvmU Overkill (based on `bob` in Ruby)
- https://www.youtube.com/watch?v=59YClXmkCVM Succession: A Refactoring Story (based on `food-chain` in Ruby)

Overkill directly addresses the idea of the devil being in the details.

**Comment by joeltaylor** [comment]
Made a PR to add both those talks. (Just  finished Overkill - so, so, so, good!)

**Comment by kytrinyx** [comment]
Aw, thank you :heart:
