### ISSUE TITLE
Remember comments when switching iterations

### ISSUE THREAD

**Issue by joeltaylor** [exercism/exercism.io#2957]
Currently, if you make a comment on an iteration but aren't logged in, we will keep that comment around while you go through the login process and repopulate the comment box when you're redirected back.

I'm wondering if it'd be worth it to keep around comments when switching between iterations? Currently, if you start commenting, switch to a different iteration, then return to the original iteration, your comment will be lost. Granted, the browser alerts you that you're leaving so it's not really a bug so much as a nice to have.

This can be accomplished by storing the comment in local storage here (https://github.com/exercism/exercism.io/blob/master/app/views/submissions/submit_comment.erb).

**Comment by joeltaylor** [comment]
I'll gladly open a PR for this if others think it'd be useful.

**Comment by kytrinyx** [comment]
This would be a really nice touch!

**Comment by joeltaylor** [comment]
I'm going to preface all this by first saying that I'm a bit out of my comfort zone when it comes to front-end development. 

I've made some headway on this issue, but am hesitant about not being able to verify some of the race conditions. I'm also wondering if it'd be worth splitting the JS into page-specific bits, but that's potentially overkill since we don't have _that_ much JS.

 My current roadblocks:

I haven't been able to verify that a JS timeout (https://github.com/exercism/exercism.io/blob/master/app/views/submissions/submit_comment.erb#L25-L31)  is still needed...but it also doesn't hurt to keep the code around. (Note, my PR moves the page specific JS code for comment submissions into `frontend/app/js/app.coffee`)

Also trying to figure out this bit of code since I'm already thrashing around in JS. Apparently, based on the commit history, it's a solution for an edge case.(https://github.com/joeltaylor/exercism.io/blob/e4d7413ed3cbdb352b08e02e024705fd7efe6563/frontend/app/js/script.js#L32-L41)

If anyone is fluent in front-end JS, I'd love to pair to refactor/see how we can guard against race conditions.

**Comment by rezen** [comment]
For the `comment.erb` there should be a document.ready event hook vs. a timeout. jQuery lets you hook into that event.
