### ISSUE TITLE
Better information about activity on a submission

### ISSUE THREAD

**Issue by TeaDrivenDev** [exercism/exercism.io#2958]
What I find myself wishing for pretty much every time I check the submissions in the track I follow is more information about _what_ has changed in a particular submission. Is it a new submission? Did the author submit a new iteration? Did someone leave a comment, or just approve of the solution?

Being able to see that would help me choose what to look at _right now_, and what maybe later or not at all.

Just showing the last handful of updates would certainly be enough; it might look something like this:

![screenshot - 25 06 2016 00_03_29](https://cloud.githubusercontent.com/assets/2247219/16351952/ffd67104-3a69-11e6-8bba-523b0ef7aa96.png)

There is the risk of the UI becoming to noisy, and there limited horizontal space in those "panels", but I would find having this kind of information on the overview page very helpful.

**Comment by kytrinyx** [comment]
We used to tell you what the latest thing that changed was (not the full list of changes since you last looked at it, but just the most recent change). I see that we've lost this, which was not intentional.

**Comment by kytrinyx** [comment]
I think to get this right, we need to consider it within the larger context. I'm going to close this, but I've added the design research label to this so that we can evaluate the question within the larger context of the design reboot (see https://github.com/exercism/discussions/issues/113 for more about this).
