### ISSUE TITLE
Compilation issues for projects using require_equal_containers.h

### ISSUE THREAD

**Issue by sandordargo** [exercism/exercism.io#2961]
Hello,

I have the following error for all the cpp projects using require_equal_containers.h. I tried boost 1.55 and 1.61 and I use this gcc on Xubuntu 14.04:

sdargo@ncelr51130 ~/exercism/cpp/etl/build $ gcc --version
gcc-4.8.real (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Thanks for your help!

[ 50%] Building CXX object CMakeFiles/etl.dir/etl_test.cpp.o
In file included from /usr/local/include/boost/test/tools/floating_point_comparison.hpp:21:0,
                 from /usr/local/include/boost/test/tools/old/impl.hpp:21,
                 from /usr/local/include/boost/test/test_tools.hpp:46,
                 from /usr/local/include/boost/test/unit_test.hpp:18,
                 from /home/sdargo/exercism/cpp/etl/etl_test.cpp:3:
/usr/local/include/boost/test/tools/detail/print_helper.hpp: In instantiation of ‘struct boost::test_tools::tt_detail::print_log_value<std::pair<const char, int> >’:
/usr/local/include/boost/test/tools/detail/print_helper.hpp:178:40:   required from ‘std::ostream& boost::test_tools::tt_detail::operator<<(std::ostream&, const boost::test_tools::tt_detail::print_helper_t<T>&) [with T = std::pair<const char, int>; std::ostream = std::basic_ostream<char>]’
/usr/local/include/boost/test/utils/wrap_stringstream.hpp:66:19:   required from ‘boost::basic_wrap_stringstream<CharT>& boost::operator<<(boost::basic_wrap_stringstream<CharT>&, const T&) [with CharT = char; T = boost::test_tools::tt_detail::print_helper_t<std::pair<const char, int> >]’
/usr/local/include/boost/test/tools/old/impl.hpp:212:19:   required from ‘boost::test_tools::assertion_result boost::test_tools::tt_detail::equal_coll_impl::operator()(Left, Left, Right, Right) [with Left = std::_Rb_tree_const_iterator<std::pair<const char, int> >; Right = std::_Rb_tree_const_iterator<std::pair<const char, int> >]’
/home/sdargo/exercism/cpp/etl/etl_test.cpp:15:5:   required from here
/usr/local/include/boost/test/tools/detail/print_helper.hpp:47:5: error: static assertion failed: Type has to implement operator<< to be printable
     BOOST_STATIC_ASSERT_MSG( (boost::has_left_shift<std::ostream,T>::value),
     ^
make[2]: *** [CMakeFiles/etl.dir/etl_test.cpp.o] Error 1
make[1]: *** [CMakeFiles/etl.dir/all] Error 2
make: *** [all] Error 2

**Comment by NobbZ** [comment]
I do not have a problem running the tests using boost 1.55, Ubuntu 14.04 as well.

Perhaps you should file the bug at the tracks issue tracker, https://github.com/exercism/xcpp/issues

**Comment by sandordargo** [comment]
Ok, thanks!
