### ISSUE TITLE
Text editor shows two indentation spaces, Exercism shows 4

### ISSUE THREAD

**Issue by kellymason** [exercism/exercism.io#2963]
I have my sublime text set to 2 spaces for indentation (shown below). When I submit to exercism, it shows four spaces, and I receive feedback only on the indentation.

![image](https://cloud.githubusercontent.com/assets/7332011/16500464/82aaa886-3eb9-11e6-9c1a-2319eee15569.png)
![image](https://cloud.githubusercontent.com/assets/7332011/16500474/8c49b2a6-3eb9-11e6-80ca-e877fbd45726.png)

**Comment by jakegavin** [comment]
I think you're still using tabs in your editor. Click on "Tab Size" and try selecting "Indent Using Spaces"
![image](https://cloud.githubusercontent.com/assets/5965895/16502895/6a65ca24-3ec5-11e6-8241-1cdfacdc998c.png)

Once that is checked, it will change the option to show "Spaces: 2" 

![image](https://cloud.githubusercontent.com/assets/5965895/16502903/79d1e7e0-3ec5-11e6-962e-a22dcff459e0.png)

**Comment by machikoyasuda** [comment]
@jaimemendozadev might be of interest to you :)

**Comment by kotp** [comment]
@kellymason Did this help you out?

**Comment by kytrinyx** [comment]
:heart: thanks everyone! I'm going to close this, but @kellymason if you're still stuck, please feel free to reopen it!
