### ISSUE TITLE
Notification about new comment, but there is none

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#2964]
![no_comment](https://cloud.githubusercontent.com/assets/58951/16515102/43811160-3f70-11e6-9cb5-be5a0849af87.png)

This is not the first time this happened, but the first time I was able to do some screenshot. This has happend about 4 or 5 times during the last 6 months, so the rate is very low.

To summarize the picture shown above:

There has been a notification about a comment to one of my submissions, after opening that submission there are no (new) comments on any given iteration (there is only one iteratation without comments in this example).

After following that link in the notification to my submission, the notification is marked as read and vanishes.

**Comment by kytrinyx** [comment]
I'm pretty sure this is when people comment and then delete their comment. I don't think we currently track the comment id in notifications, so deleting the notification is probably not super trivial.

**Comment by NobbZ** [comment]
One can delete a comment? I never realized...
Am 01.07.2016 10:11 schrieb "Katrina Owen" <notifications@github.com>:

**Comment by kotp** [comment]
The delete is when you click on 'edit'.  You can't "cancel" an edit, just browse away from it, effectively doing the "cancel".  The options are "delete" and "submit".

**Comment by kytrinyx** [comment]
Yeah, the UX is not great on this. I've been hoping a designer would like to help rethink the whole page for a better usability.

**Comment by MohanL** [comment]
Would it be great if the system has a retract feature for the notifications like invitations, comments ? 
potentially relate to https://github.com/exercism/exercism.io/issues/3185

@c1505, what is your idea about this issue, since you are working on retracting the invitations

**Comment by c1505** [comment]
@MohanL I haven't had much time to look over #3185 yet this week.  Haven't looked at the implementation of notifications yet.  Targeting this weekend to submit the PR.  

An alternative solution could be to also notify when a comment is deleted.  Not sure which would be more appropriate here.

**Comment by kytrinyx** [comment]
What if we marked comments as deleted and instead of showing the comment, we showed a message in the comment flow saying something like `@username deleted their comment`?

**Comment by MohanL** [comment]
@kytrinyx in my opinion, I still feel like we should not bother people by the unnecessary notifications. For people who have obsessive-compulsive disorder about notifications, it is a pain.

**Comment by MohanL** [comment]
@kytrinyx 
I think `@username deleted their comment` is a great idea, but do we need the notifications though ?

**Comment by kytrinyx** [comment]
@MohanL No, we don't need a notification, I just don't know if we can delete it at the moment.

**Comment by kytrinyx** [comment]
We're going to need to reconsider the data model for this one when we rethink the notifications.

I've added the design research label to this so that we can evaluate the question within the larger context of the design reboot (see https://github.com/exercism/discussions/issues/113 for more about this).

Since this issue addresses things that are going to be difficult to implement as a quick experiment in the current prototype, I'm going to close this. If you do think that it can be implemented as a not-too jarring and not-too complicated experiment in the current website, please open a new issue about it in the discussions repository.
