### ISSUE TITLE
Won't submit from the CLI "no such file or directory"

### ISSUE THREAD

**Issue by IanDCarroll** [exercism/exercism.io#2969]
Hey, this is a first issue submit. Please let me know if I need to edit this for style or info.

is this a potential bug? Or am I doing it wrong? 
Is there a dependency I've missed? Something ill configured?

```
~/exercismSolutions/javascript/word-count$ ls
README.md  word-count.js  word-count.spec.js
~/exercismSolutions/javascript/word-count$ exercism submit word-count.js
2016/07/10 10:42:50 lstat /home/ian/exercism: no such file or directory
~/exercismSolutions/javascript/word-count$ exercism -v
exercism version 2.2.5
```
Background: using Ubuntu 14, Just pushed to GitHub before this. 
And I was trying to setup exercism locally to work on contributing with a team, but got stuck on something relating to postgreSQL.
Could I have overwritten my earlier configuration for just working on problems?

**Comment by kotp** [comment]
It looks like the config is set to /home/ian/exercism but your "exercism" directory is ~/exercismSolutions instead.

**Comment by IanDCarroll** [comment]
Ooh! That looks like some obvious thing that I would do. Let me try that!

**Comment by IanDCarroll** [comment]
That was the problem. Thanks so much!
