### ISSUE TITLE
Search by topic e.g. "recursion"

### ISSUE THREAD

**Issue by willnwhite** [exercism/exercism.io#2976]
I'd like to do a recursion exercise in Elm (to learn how to do it, actually), but I can't see "recursion" from Elm's Available exercises without popping open all the tabs and looking for it. I think you should be able to find exercises by topic.

**Comment by kytrinyx** [comment]
I'd love to have a good search. This is a bit complicated, as we currently haven't classified exercises at all. We have talked about it, though. E.g. https://github.com/exercism/x-common/issues/63

**Comment by jtigger** [comment]
Folding this in the broader discussion forming around topical search (exercism/discussions#83).

**Comment by canweriotnow** [comment]
Searching for "recursion" should return a helpful suggestion like [did you mean recursion?](https://www.google.com/search?q=recursion)
