### ISSUE TITLE
First few lines of submission repeated, but not in original code...

### ISSUE THREAD

**Issue by kotp** [exercism/exercism.io#2977]
@kotp commented on [Fri Jul 15 2016](https://github.com/exercism/cli/issues/338)

[exhibits this strangeness](http://exercism.io/submissions/c8efa0c302354c31ad24c2a73449bf63)

![screenshot from 2016-07-15 20 06 02](https://cloud.githubusercontent.com/assets/16747/16891459/b5d71cf2-4ac7-11e6-848d-a5fc70046a26.png)

See comments from @mcritchlow for details in that submission.

---

@Tonkpils commented on [Sat Jul 16 2016](https://github.com/exercism/cli/issues/338#issuecomment-233135490)

That is very odd but I'm not sure how we could even begin debugging this. All of the other solutions don't have the duplicate module. If we had access to the request that generated this iteration then we'd be able to see what was sent on the request body but as it stands I'm not sure this is possible. 

I'd be happy to take a look if we had a bit more information.

---

@kotp commented on [Sat Jul 16 2016](https://github.com/exercism/cli/issues/338#issuecomment-233162767)

The link shows the sha, if that is logged, the user, as well, and the time.  So if it is possible to track back, in the logs.

I have never seen it happen before, but I have only seen a small subset of submissions.

---

@kytrinyx commented on [Sun Jul 17 2016](https://github.com/exercism/cli/issues/338#issuecomment-233188907)

That's the strangest thing. We don't rewrite anything in the CLI.

That said, there's some stuff that munges the markdown into HTML for display inside the exercism/exercism.io application. My guess is that it has something to do with that.

I wish we could move issues easily between repositories in the same org.

---

@mcritchlow commented on [Sun Jul 17 2016](https://github.com/exercism/cli/issues/338#issuecomment-233209010)

thanks all! fwiw, I've done a few more exercises since and haven't experienced the issue. If you decide it's worth looking into more, please let me know if there's anything else I could do to help. 

@kytrinyx - I wish we could move issues easily between repos in the same org too! Our team still uses JIRA for internal projects, but are looking to move to GH tickets + waffle.io. We have to move tickets to different projects/repos fairly often, since we have a bunch of different folks creating tickets. So yea, 👍 to that hopefully being a thing in GH at some point.

---

@Tonkpils commented on [Sun Jul 17 2016](https://github.com/exercism/cli/issues/338#issuecomment-233209756)

> I wish we could move issues easily between repositories in the same org.

~
> We have to move tickets to different projects/repos fairly often, since we have a bunch of different folks creating tickets. So yea, 👍 to that hopefully being a thing in GH at some point.

@kytrinyx @mcritchlow Check out https://www.zenhub.com/ it has a great Move Issue and it's free for Open Source! Where do we want to move this issue? 
![image](https://cloud.githubusercontent.com/assets/1507561/16903676/7cdd4282-4c52-11e6-840f-da9768264106.png)

**Comment by Insti** [comment]
Can we close this as "can not reproduce?"

**Comment by kotp** [comment]
I think so, other changes have been made and no other noise on this issue.
