### ISSUE TITLE
Not receiving emails for new notifications

### ISSUE THREAD

**Issue by veswill3** [exercism/exercism.io#2983]
I do not receive emails for new notifications. I know I used to a long time ago. I don't see any configuration around this. Am I missing something? Should I be receiving emails from exercism.io? I don't have any filters in my email and they are not showing up in my spam.

**Comment by NobbZ** [comment]
Email notifications have been disabled about 1.5 years ago.

Am 22.07.2016 16:24 schrieb "Vesper" <notifications@github.com>:

**Comment by veswill3** [comment]
Thanks explains it. Thanks.
