### ISSUE TITLE
Unable to build this repo locally

### ISSUE THREAD

**Issue by scottwhudson** [exercism/exercism.io#2985]
I set out to work on issue 174 in exercism/todo, but I failed to build the app locally (looks like Bugsnag doesn't get initialized correctly).  

`~/Development/exercism.io/config/bugsnag.rb:1:in '<top (required)>': uninitialized constant Bugsnag (NameError)`

Having build instructions in the README would be super helpful for people wanting to contribute to these projects.  I'm happy to write the docs myself and open a PR, but I'd like to know if there are any curveballs with the build process since following the default sinatra setup didn't work.

**Comment by amalrik** [comment]
I have setup exercism on mac and ubuntu and never got this problem.
I just followed the instructions on [contributing guide](https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md)
It would be useful if you could show all steps you took to get this error message.

good luck

**Comment by kytrinyx** [comment]
Hey @scottwhudson, I just realized from reading this that it's completely not obvious that our setup instructions are in the CONTRIBUTING.md file, not the README. If you would like to submit a PR to the README to help point people in the right direction, I'd really appreciate it! (No pressure, of course! Happy to make the change if not).

**Comment by scottwhudson** [comment]
done! @kytrinyx

**Comment by Insti** [comment]
@scottwhudson Which problem did you want to work on?  #174 seems to have been resolved in 2013.

**Comment by scottwhudson** [comment]
@Insti took me a bit to figure out the confusion here, heh.  I meant issue 174 in the todo repo: https://github.com/exercism/todo/issues/174, not here in the exercism.io repo. 

I know I'm totally new to the project here.  I am curious though, are issues in the specific repos higher priority than what's in the todo repo or something?

**Comment by Insti** [comment]
Ah OK, you need to include the repository if you're linking to another one (Exercism has lots) I just copy/paste the issue url: https://github.com/exercism/todo/issues/174

I don't think there is any difference in priority, just do what you can/want.

**Comment by Insti** [comment]
Are you able to build now?

**Comment by scottwhudson** [comment]
I did that originally and Github incorrectly referenced the readme branch with that issue, so I removed it to see if it would remove the ref.  Alas, it did not.  Build instructions worked beautifully though. 👍

**Comment by Insti** [comment]
Great. You should be able to close this issue then.

**Comment by kytrinyx** [comment]
> I know I'm totally new to the project here. I am curious though, are issues in the specific repos higher priority than what's in the todo repo or something?

The TODO repo was originally made for an open source hackathon, and the goal of all of those issues is to be immediately actionable. I would actually like to rework all the issues everywhere so that anything not-yet-actionable goes in the https://github.com/exercism/discussions/issues, and everything else in all the other repositories would be actionable. It's a bit of a mess right now.
