### ISSUE TITLE
[crystal; lfe; others?] Syntax-Highlighting

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#2988]
Currently there is no syntax highlighting in the tracks `xcrystal` and `xlfe`, maybe other tracks are lacking highlighting as well.

Crystal as a Ruby-inspired language, which even does borrow API-documentation from Ruby should be safe to be highlighted by the Ruby-highlighter until we get something more appropriate. But I can tell so far, that I have not come to any problems using emacs `ruby-mode` to edit my crystal stuff.

LFE should be safely highlightable by the same highlighter that powers `xemacs` or `xclojure` or `xracket` or any other lispy/schemey track. Personally I used `lisp-mode` for the first couple of exercises until I installed the more appropriate `lfe-mode`. I think that a lispy highlighter would be the best, since there are some differences in lisps and schemes way to define functions. Lisp uses the funtions name as first argument to the `defun`-macro followed by the list of arguments, while scheme uses a list which first element is the name of the function and the tail lists the arguments.

@exercism/track-maintainers if your track also does not have proper syntax highilghting but are not mentioned so far, please rise your voice, I will maintain a progresslist in this post.

- [ ] xcrystal (#2997)
- [ ] xlfe
- [ ] xfsharp (#2997)
- [ ] xlisp

**Comment by ErikSchierboom** [comment]
The F# track (xfsharp) also doesn't have syntax highlighting.

**Comment by NobbZ** [comment]
Are you aware of a fallback that could be used as for crystal and lfe? Or do you know about a plugin/extension for exercisms highlighter?

@kytrinyx can you actually point out which one is used? Looking at the delivered HTML I'd guess it's done server side?

**Comment by ErikSchierboom** [comment]
@NobbZ the language that comes closest is OCaml I guess, but I think F# is mainstream enough to just have its own highlighter. Perhaps @kytrinyx can point out what is used for the highlighting?

**Comment by Insti** [comment]
Can confirm there is a ruby gem that takes care of syntax highlighting.
(I don't have time to check for more info right now but I can look later.)

**Comment by NobbZ** [comment]
I did a quick lookup at exercism/exercism.io's Gemfile and it seems as if we are using an old version of [`rogue`](https://rubygems.org/gems/rouge) ([GitHub](https://github.com/jneen/rouge)).

The current version seems to support F# out of the box. There is a file in the lexer-folder named `fsharp.rb` at least ;).

**Comment by verdammelt** [comment]
The Common Lisp track (xlisp) doesn't have syntax highlighting.

**Comment by Insti** [comment]
> The current version seems to support F# out of the box

It may just be a case that the language mapping (Exercism name -> Rouge name) needs updating.
See: https://github.com/exercism/exercism.io/blob/master/lib/exercism/syntax_highlighter.rb#L6

**Comment by ErikSchierboom** [comment]
@Insti I don't think that's it, as the mapping is later used in the following code:

```ruby
 normalize_language(language)
      # HACK: Some languages have different names in Rouge
      ROUGE_LANG.fetch(language) { language }
    end
```

**Comment by Insti** [comment]
@ErikSchierboom you're right, it looks like the Exercism Rouge version needs to be updated to include the fsharp lexer.

**Comment by mhelmetag** [comment]
Sorry for the double PR... I was trying to get my heroku exercism working and made some dumb commits (didn't realize that I could push non-master branches to my heroku master branch).

**Comment by Insti** [comment]
lisp can probably be done by mapping to rouge's "common_lisp"

**Comment by Insti** [comment]
Is "common_lisp" also appropriate for xlfe? (Lisp Flavoured Erlang (LFE))

**Comment by NobbZ** [comment]
I think that common_lisp is appropriate for LFE, at least I did the first couple of exercises using emacs lisp-mode. Maybe some of the "keywords" will be named differently, but I don't think that matters.

**Comment by mhelmetag** [comment]
Woops! Well... When we decide which languages to lfe and lisp, someone can make a quick PR to update that map.

**Comment by kytrinyx** [comment]
> Perhaps @kytrinyx can point out what is used for the highlighting?

Sorry, it looks like you all figured this out. We use the `rouge` gem for this.

**Comment by LegalizeAdulthood** [comment]
Possible TECO language track will be super crazy to syntax color.  Some language operations are control characters 😸

**Comment by verdammelt** [comment]
It looks like the 'common_lisp' option in Rouge is the right one for the xlisp track. Could anyone put in a PR for such a change? I don't have a dev environment for exercism so I wouldn't be able to test it until I did...

**Comment by kytrinyx** [comment]
@verdammelt I made #3004
