### ISSUE TITLE
I changed my exercises directory, how do I get around to submit the files I want?

### ISSUE THREAD

**Issue by JakeDobson** [exercism/exercism.io#2990]
here's my exercism debug:

**** Debug Information ****
Exercism CLI Version: 2.2.6
Exercism CLI Latest Release: 2.2.6
OS/Architecture: darwin/amd64
Build OS/Architecture darwin/amd64
Home Dir: /Users/jacobdobson
Config file: /Users/jacobdobson/.exercism.json
API Key: ******************************
Exercises Directory: /Users/jacobdobson/Users/jacobdobson/Desktop/Coding/iOS/Objective-C/exercism

**Comment by JakeDobson** [comment]
Never mind, I figured it out. There was a "bad path" somehow. Had to copy the files, fetch the problem again, and insert the files into the new directory!

**Comment by kotp** [comment]
The config file that is shown has what it thinks is the folder... I will close this based on your report.

**Comment by kytrinyx** [comment]
> Never mind, I figured it out.

Glad you got it sorted!
