### ISSUE TITLE
Live deploy notifications?

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#2991]
Is there any way to discover or be notified when new live deployments happen?

I've been following the progress of a few patches lately and am interested in seeing when they go live and being able to personally verify that everything is working as expected.

**Comment by mhelmetag** [comment]
I'm sure we could could get some kind of release notifications (with commits and relevant PRs) for the exercism/dev gitter channel... Could be a cool integrations project.

**Comment by Insti** [comment]
The [API](http://x.exercism.io/) contains a "build_id" as part of the json output.

**Comment by Insti** [comment]
https://github.com/exercism/exercism.io/pull/3000 add a /version route that will report build information for the web app.

**Comment by kytrinyx** [comment]
Does heroku have web hooks?

**Comment by Insti** [comment]
https://devcenter.heroku.com/articles/deploy-hooks

**Comment by kytrinyx** [comment]
Sweet. If someone decides to do this, please tell me what I need to do to activate the hook in the way that you want within heroku.

**Comment by Insti** [comment]
Gitter integration instructions:
```
Instructions

You need to configure your Heroku app to send Webhook notifications.

    Open your Heroku app in a terminal
    Run this command with your webhook URL:

    heroku addons:add deployhooks:http --url=webhook_url

    Click Apply

Your unique webhook url for this service:

https://webhooks.gitter.im/e/<redacted>
```

**Comment by Insti** [comment]
you get the webhook url from gitter by going to 
Room settings -> Integrations -> Heroku

(I'd suggest exercisim/dev as a good room.)

**Comment by kytrinyx** [comment]
OK, thanks.

**Comment by kytrinyx** [comment]
OK, I think I did it. I'll deploy a tiny change now.

**Comment by Insti** [comment]
Looks like it works
> Heroku [exercism] deployed 13d447a

Thanks :heart:

**Comment by kytrinyx** [comment]
Excellent. Is there anything else we need to do for this ticket or are we good to close it?

**Comment by Insti** [comment]
I think it can be closed.

**Comment by Insti** [comment]
Although it probably should be documented somewhere.

**Comment by kytrinyx** [comment]
Hah. Yeah, it probably should.... along with all the other deploy-related stuff, now that you mention it!

**Comment by Insti** [comment]
The current "build_id":"13d447a" seems not to match any of the ids in the public repository.

**Comment by Insti** [comment]
I added some documentation to CONTRIBUTING.md - #3003

**Comment by kytrinyx** [comment]
> The current "build_id":"13d447a" seems not to match any of the ids in the public repository.
> Are you deploying from a branch?

Weird, I didn't think so. I used to have this scripted, but just changed machines, and now I need to put those scripts somewhere re-usable. Let me check.

**Comment by kytrinyx** [comment]
I have no idea where that came from. Apparently I had a commit on HEAD locally that I deployed but didn't push. It's gone now (deploying again).

**Comment by kytrinyx** [comment]
Oh. Hah.

```
commit 13d447a737e77f6fd43b6f5fc68eaa22fbc59ba9
Author: Katrina Owen <kytrinyx@github.com>
Date:   Wed Jul 27 12:44:13 2016 -0600

    Test deploy hook

```

This was `git commit --allow-empty -m "Test deploy hook"`

**Comment by Insti** [comment]
Documentation updated.
Build_ID matching what's in Github verified.
A lesson about the dangers of empty commits learned.
Thanks @kytrinyx :smile:
