### ISSUE TITLE
Spelling error on about: - What's with the name "Exericism"? Change Exericism to Exercism

### ISSUE THREAD

**Issue by gusseting** [exercism/exercism.io#2994]
Spelling error is on the about page: http://exercism.io/about
Under the heading of "Origin of Exercism's name"
is: What's with the name "Exericism"? which needs to be changed to Exercism.

- [ ] claim this issue (assign yourself or comment below)

**Comment by ErikSchierboom** [comment]
I can do this :)

**Comment by ErikSchierboom** [comment]
[PR](https://github.com/exercism/exercism.io/pull/2999) has been submitted.

**Comment by kytrinyx** [comment]
Thanks @ErikSchierboom
