### ISSUE TITLE
Coveralls: needs re-authorization

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#2998]
I was looking at the output from coveralls https://coveralls.io/github/exercism/exercism.io

But when I tried to view the contents of any files, for example: https://coveralls.io/builds/7180204/source?filename=lib%2Fexercism%2Fgithub.rb

I got the following error:

> Source Not Available
> The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.

**Comment by kytrinyx** [comment]
Thanks! Yeah, I updated all my credentials and forgot to re-authorize. Thanks for catching it!

Would you check again? I think I've done this correctly.

**Comment by Insti** [comment]
Confirmed working :+1:

**Comment by Insti** [comment]
Thanks.
