### ISSUE TITLE
bork is borked when not logged in.

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3002]
There is a static route /bork which seems to exist to trigger an exception which is then caught and passed to Bugsnag.

http://exercism.io/bork

This seems to work correctly when you are logged in to Exercism, but when you are not it results in a long textual stacktrace.

```
Puma caught this error: undefined method `username' for #<Guest:0x007fea625d0d78> (NoMethodError)
/app/app/routes/core.rb:27:in `block in <class:Core>'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
/app/vendor/bundle/ruby/2.2.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `[]'
<another 50 or so lines omitted>
```

The error handler should be fixed to handle a `nil` current_user

**Comment by Insti** [comment]
I suspect it also fails to report to Bugsnag which doesn't happen until 7 lines later on line 34.

**Comment by kytrinyx** [comment]
As far as I know this used to work; no idea when things got screwed up. I'm ok with deleting the endpoint.

**Comment by Insti** [comment]
Ok, the 500 handler still needs fixing so I'll do that and delete the /bork route when I'm done.
Is there a way for me to check if Bugsnag is seeing the right errors?

**Comment by kytrinyx** [comment]
I think I can add you to bugsnag. Shield your eyes—it's a mess.

**Comment by Insti** [comment]
:sunglasses:

**Comment by kytrinyx** [comment]
Give me a few hours.

**Comment by kytrinyx** [comment]
OK, invited.
