### ISSUE TITLE
Normalizing line endings

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3008]
While resolving #2915 I discovered that ajax requests and browser requests were submitting content with differing line endings.

The content submitted via a javascript call has "\n" (`%0A`) line endings
The content submitted via a browser using "application/x-www-form-urlencoded" and has "\r\n" line endings  (`%0D%0A`)

This content is going into the database without any normalization of the line endings.

My questions were:

a) Is it worthwhile normalizing line endings?
b) Should it be done as a big-bang process where we try to get them all at once?
c) Should we just normalize the input to various routes as we find it necessary?
or
d) Should we just accept that there will be different line endings and make the code that needs to care about line endings take care of itself?
e) Something else?

[kytrinyx replied](https://github.com/exercism/exercism.io/issues/2915#issuecomment-225336446):

> [...] we should probably normalize line-endings on the way in.
> 
> [...] if we take care of code submissions [and] comments then any further problems could be dealt with when they come up.

Other issues: 

Are there any other consequences we need to be aware of?
What about existing database content with "\r\n" line endings?

**What needs to be done:**

Line endings should be normalised from "\r\n" to "\n" as the content comes in for submissions and comments and before it is used by the app for further processing or storage in the database.

**Comment by kytrinyx** [comment]
> Are there any other consequences we need to be aware of?

Not that I know of. We display the comments on the site, and we don't export them anywhere. If we did, then normalizing them would still be the right move, I think.

> What about existing database content with "\r\n" line endings?

I think that we should run a data cleanup task on existing data. I tend to create a specific rake task for the purpose in lib/tasks/data.rake and then delete the task when we're done.

**Comment by ErikSchierboom** [comment]
This would be a great feature. It would prevent exercises that are essentially the same, except for the whitespace from being duplicated when submitted, right?

**Comment by kytrinyx** [comment]
>  It would prevent exercises that are essentially the same, except for the whitespace from being duplicated when submitted, right?

Yepp, that would solve it.

**Comment by kytrinyx** [comment]
This is an actionable issue, but I'd love it if it could be summarized in a way that makes it easier for someone to come and do the work.

Summarizing could happen either at the top of the original issue (with "original below" and a horizontal rule, or something like that) or in a new issue. If you open a new issue, please add a reference to this issue for complete history.

**Comment by Insti** [comment]
I expect this has become an issue that nextercism needs to worry about?

**Comment by kytrinyx** [comment]
> I expect this has become an issue that nextercism needs to worry about?

Yeah, we should make sure that this is handled consistently in v2. If someone has time to summarize the problem and open an issue in v2-feedback (and mark this as closed), that would be ✨ much appreciated ✨ .
