### ISSUE TITLE
translation PT_BR

### ISSUE THREAD

**Issue by yesroh** [exercism/exercism.io#3009]
there is some concern/effort to translate the platform?

**Comment by kytrinyx** [comment]
The question has come up before, but unfortunately we don't have the capacity to put in place the necessary things for translation work yet (and probably will not for the foreseeable future).

**Comment by scottwhudson** [comment]
@yesroh just curious, have you tried using the [Google Translate](https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb) Chrome plug-in to dynamically translate the exercism pages in the browser? I had customers use it at an old job and got them most of the way there.

**Comment by jtigger** [comment]
We'll pick this up when we do have the capacity (or someone can bring that capability).  In the meantime, seems like @scottwhudson has a workaround.
