### ISSUE TITLE
Clarify cryptic link to 'my solution'

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3010]
Ever since I've joined Exercism, While reviewing solutions, I've been looking for a direct link to my solution from the solution I am looking at.

I've just discovered that there is a '\</\>'  button in the top left.

Could we replace '\</\>' with something more obvious such as a plain text: 'My solution'?

**Comment by kotp** [comment]
Hmm... I think keeping the symbol (as it is key in communicating, it has become, to me, the thing I look for) is good, but perhaps adding something like "view my solution" before the symbol, very close to it.

But until it is known, you are definitely right, in that it is there, but not drawing attention to itself, for what it does.

So my vote is to: augment it with words

**Comment by kytrinyx** [comment]
> So my vote is to: augment it with words

That sounds reasonable to me (with the caveat that I am no user experience designer).

This might help people discover that if there's a `</>` in the footer of a comment, it will take you to that person's solution.

**Comment by Insti** [comment]
Awesome! Thanks @aaron-suarez :heart:
