### ISSUE TITLE
Only display 'add comment' box when logged in.

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3011]
## Issue
If you visit a submission page when not logged in you still have access to an 'add comment' box.

### Steps to reproduce
1) Open a browser session which is not logged in to Exercism,
2) Visit any submitted problem. (Here's one: http://exercism.io/submissions/f72e42aa0c244a33a2e9e738cf2bc349)
3) Note that there is a big working comment box there.

### Note
This is **not** a security issue. If you try to submit a comment you are given a page containing an error message: 
> You're not logged in right now. Please log in via GitHub to comment.

Which is expected behaviour.

## Task
Replace the comment box on the submission page with instructions about how to log in including a button to log in directly.

### Where do I start?
If you're completely new to Exercism development, read the [CONTRIBUTING guide](https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md)
If you have your Exercism development environment set up, look in the file: `app/views/submissions/show.erb` (That will not be the file you need to change, but it should lead you to it.)

### How do I get help?
Add a question here on Github.
(Or if you're impatient try the Gitter chat channel: https://gitter.im/exercism/support)

**Comment by ramyaravindranath** [comment]
I am looking into this.

**Comment by ramyaravindranath** [comment]
Here is the PR : adds condition to show comment box only when logged in #3023 for this issue.

**Comment by bernardoamc** [comment]
Is this still a issue? :)

**Comment by Insti** [comment]
Implemented! Thanks @ramyaravindranath :star:
