### ISSUE TITLE
Contribution suggestion only works when completion is exactly 100%

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/exercism.io#3015]
In the profile, there section where completed tracks are listed under the heading "You've completed the following tracks. Want to help add more exercises?". This works correctly for Lua on my profile (66/66), but does not indicate that I have completed Clojure which, because of deprecated exercises, sits at 45/43.

Presumably it is checking for the completion rate to be exactly 100%, but it should handle the case where the completion percentage can get out of whack due to deprecated exercises.

**Comment by kytrinyx** [comment]
I'm not sure that we've addressed the case where we have a deprecated exercise (that you've done) and a new exercise (that you haven't).

**Comment by ryanplusplus** [comment]
Yeah, you're right. It's pretty close, but it should really check whether the list of all exercises is a subset of the completed exercises.

**Comment by kytrinyx** [comment]
Yes, as a set operation rather than an arithmetic one.

**Comment by Insti** [comment]
Will you make a new issue for this. It could make for a good_first_patch
