### ISSUE TITLE
Team stream: Show exercise language 

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3020]
When viewing all exercises in a team with multiple languages, there is no indication of which language a particular solution is in.

![exercism - team stream all](https://cloud.githubusercontent.com/assets/5096681/17290013/ab3037da-57dc-11e6-8145-9fbe7d334456.png)

There should be some way of seeing the languages of the solutions.
 
**Suggestion:** A little language track icon to the left of the problem name.

**To reproduce:** 
In a developement environment:
Assume 'amelie' and visit: http://localhost:4567/teams/slate/streams

**Comment by kytrinyx** [comment]
> Suggestion: A little language track icon to the left of the problem name.

Nice, yes I think this would be excellent.

**Comment by machikoyasuda** [comment]
Looks like a great first-timers issue @kpearson @jendiamond

**Comment by bhoover85** [comment]
Is anyone working this? If not, I'd like to take it.

Here's how it would look with a 20x20 icon. Any suggestions on the size?

![stream_language_icons](https://cloud.githubusercontent.com/assets/4006188/17821936/3d8eaf64-6622-11e6-99a3-81563e82a22d.png)

**Comment by bhoover85** [comment]
I wonder if it would also be good to add the language icon to the list on the left.

**Comment by Insti** [comment]
> Any suggestions on the size?

What does "same size as the text" (smaller icon) look like?
Or maybe if the text was vertically centred?
What's the lower limit for icon visibility?

>  I wonder if it would also be good to add the language icon to the list on the left.

Could be good, could be too "busy" can you do a preview image of it?

**Comment by sobinsunny** [comment]
I would like to work on this :)

**Comment by bhoover85** [comment]
Hi @sobinsunny, I've already started working this issue. Can you pick a different one?

@Insti, I played around with a couple sizes. I don't think we want to go any smaller than 15px for the icons. The java icon starts becoming difficult to read.

**10px**
![10px](https://cloud.githubusercontent.com/assets/4006188/17830717/1fd99314-66a2-11e6-8c08-83145cf600b3.PNG)

**15px**
![15px](https://cloud.githubusercontent.com/assets/4006188/17830719/267c9702-66a2-11e6-970e-9088b05add86.PNG)

**15px with `vertical-align: baseline` on the icon**
![15px_baseline](https://cloud.githubusercontent.com/assets/4006188/17830722/3b769568-66a2-11e6-98a2-d42a9d7b9ec5.PNG)

**Comment by Insti** [comment]
Thanks @bhoover85 
I like the middle one (15px)
Put it in a PR and see what @troubalex has to say.

**Comment by kytrinyx** [comment]
Another thing to try is the lower-right hand corner—that might help make it more scannable. But yeah @troubalex is going to be the one who has the best feedback on this.

/cc @gusseting since this is your interest area.

**Comment by troubalex** [comment]
Sweet! 😄 

@bhoover85:
> I wonder if it would also be good to add the language icon to the list on the left.

I'm a bit worried that this might become very cluttered and hence hard to scan, but if it's not much work, you could try it out.

@kytrinyx 
> Another thing to try is the lower-right hand corner—that might help make it more scannable.

That's what I thought, only top-right hand corner. Both would probably work.

I'd most likely go for 15px icons, and give them the same padding as the avatar on the left. You could also try and only set the height to 15px to keep the width varied. That might work better for the rectangular icons such as the Java one.

**Comment by bhoover85** [comment]
Top right looks good. I actually like the 20px over the 15px here, but if you want to stick with 15 just let me know and I'll submit the PR. If you want a full page preview I can attach one.

**20px**
![20px_right](https://cloud.githubusercontent.com/assets/4006188/17833340/7fd02b70-66e8-11e6-8287-66adf0b12a39.PNG)

**15px**
![15px_right](https://cloud.githubusercontent.com/assets/4006188/17833342/85eb8f4a-66e8-11e6-8447-c91650202f57.PNG)

**Comment by troubalex** [comment]
Agreed, 20px looks good. :shipit:

**Comment by sobinsunny** [comment]
Ok . Go ahead

**Comment by gusseting** [comment]
I think any addition is going to be an improvement.

The issues that I can see with an icons is that it's not searchable - you can't do a find (eg ⌘f on a mac), and search through the exercises - however is that a functionality that would be helpful? 
Not everyone is going to know what each icon means - perhaps only the ones of the languages that they're learning - what problems might not knowing each icon cause?
I'm wondering how much those icons might affect performance of the site over using text too. Thoughts?
@Insti what do you think?

**Comment by Insti** [comment]
@gusseting:

> The issues that I can see with an icons is that it's not searchable - you can't do a find (eg ⌘f on a mac), and search through the exercises - however is that a functionality that would be helpful?

The team view already allows you to view problems by language, the problem this solves is you previously had no way at all to know which language a problem belonged to in the 'all problems' list.

> Not everyone is going to know what each icon means - perhaps only the ones of the languages that they're learning - what problems might not knowing each icon cause?

Finding out what the language icon means is easy, click on a problem and it will tell you, or click down the list of languages and see which icon shows up.

> I'm wondering how much those icons might affect performance of the site over using text too. 

Not enough to notice, 

It's good you're thinking about these things, but be wary of trying to bundle too many things in with a change, if any of these turn out to be particularly important then we can create another issue & pull request and make sure they get addressed without holding up all progress. Don't let the perfect become the enemy of the good.

**Comment by radar** [comment]
(I work at @cultureamp where @gusseting is doing RGSoC):

> The issues that I can see with an icons is that it's not searchable - you can't do a find (eg ⌘f on a mac), and search through the exercises - however is that a functionality that would be helpful?

For an initial pass on this feature, I don’t think that this change is necessary enough to include. While I can see a few people _possibly_ wanting that feature, it isn’t like a “OMG I NEED DIS” part of this feature.

> Not everyone is going to know what each icon means - perhaps only the ones of the languages that they're learning - what problems might not knowing each icon cause?

They can hover over the icon to get some alt-text which shows the icon’s language, perhaps?

> I'm wondering how much those icons might affect performance of the site over using text too. Thoughts?

Very likely to be negligible. The icons are small enough and that means that they should load quickly.

**Comment by kytrinyx** [comment]
Fixed by #3072

**Comment by Insti** [comment]
Thanks for all your work on this @bradhvr :heart:
