### ISSUE TITLE
Make links previewable in tweets.

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3024]
Sometimes when you link to a webpage in Twitter it shows a nice preview with an image/excerpt.
Currently links to Exercism problems show up as just linkified blue words.

What do we need to do to make Exercism links show as pretty page previews in Twitter?

**Comment by hanneskaeufler** [comment]
I think a start would be to include the meta tag as described in https://dev.twitter.com/cards/getting-started#started

```html
<meta name="twitter:card" content="summary" />
```

**Comment by gusseting** [comment]
It's an issue with Slack too, and here's what I've worked out so far by comparing the slack brand to exercism on slack and twitter.
![slack on twitter](https://cloud.githubusercontent.com/assets/540264/17468469/afb830e8-5d6b-11e6-8906-d77a673ed52c.png)
![exercismslack](https://cloud.githubusercontent.com/assets/540264/17468536/2ea801bc-5d6c-11e6-8de1-46a18ef81778.png)

What's missing from exercism is metadata in the following areas:
```
<meta property="og:type" 	content="website"/>
<meta property="og:site_name" 	content="Slack"/>
<meta property="og:image" 	content="https://slack.com/img/slack_hash_128.v1464126652.png"/>
<meta property="og:title" 	content="Slack: Be less busy"/>
<meta property="og:description" content="Slack brings all your communication together in one place. It’s real-time messaging, archiving and search for modern teams."/>
		<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@slackhq">
<meta name="twitter:title" content="Slack: Be less busy">
<meta name="twitter:description" content="Slack brings all your communication together in one place. It’s real-time messaging, archiving and search for modern teams.">
<meta name="twitter:image" content="https://slack.com/img/slack_hash_twitter.v1464126652.png">	
```


We have an empty description: ` <meta content='' name='description'>`
here's slack: 
```<meta name="description" content="Slack brings all your communication together in one place. It’s real-time messaging, archiving and search for modern teams.">```


It looks like we're getting this image in slack: http://exercism.io/icons/apple-touch-icon.png
so I'll see if there's a way to make the smaller version appear in slack + twitter: 
http://exercism.io/icons/favicon.ico?v=4

this is what I plan on adding: (I need to create/find the exercism.io png)
```
<meta property="og:type" 	content="website"/>
<meta property="og:site_name" 	content="Exercism.io"/>
<meta property="og:image" 	content="https://exercism.io/pathtoimage.png"/>
<meta property="og:title" 	content="Exercism.io: Crowd-sourced code mentorship."/>
<meta property="og:description" content="Practice having thoughtful conversations about code."/>
		<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@exercism.io">
<meta name="twitter:title" content="Slack: Crowd-sourced code mentorship">
<meta name="twitter:description" content="Practice having thoughtful conversations about code.">
<meta name="twitter:image" content="http://exercism.io/icons/favicon.ico?v=4">	
```
What do you think?

**Comment by Insti** [comment]
Make sure all the four required open graph properties are present: http://ogp.me/

This blog post has more information about open graph and twitter/facebook meta tags https://blog.kissmetrics.com/open-graph-meta-tags/

**Comment by kytrinyx** [comment]
I like that metadata, @gusseting!

**Comment by gusseting** [comment]
@Insti to help answer your question "What do we need to do to make Exercism links show as pretty page previews in Twitter?" I'm finding that part of the answer is: first you need to have pretty pages with images to preview. Exercism doesn't have informational pages with images in the way that say [http://www.alistapart.com](alistapart.com) does, but we can provide a summary in the same way that slack.com does, as shown above.

**Comment by Insti** [comment]
Thanks @gusseting the logo image should be enough for an image, we're not an image heavy site after all as you alluded to. 
The link summary should be possible to make page specific and relevant to the pasted link though?

**Comment by gusseting** [comment]
@insti: 

> The link summary should be possible to make page specific and relevant to the pasted link though?
To make the summary page specific and relevant to the link, there needs to be specific summaries for every single page that we think will be linked - do we have the resources to do that? 

So the question here is: what is most linked to on twitter?
I've just gone through the statistics, and the biggest jump in stats was on july 12. Here's the results on twitter, [which was due to @kytrinyx doing a talk on golang](https://twitter.com/search?q=exercism%20since%3A2016-07-11%20until%3A2016-07-13&src=spxr). 

It's a case of, with limited resources, how can we have the most impact? Right now, my recommendation would be to see if we can change the metadata for the language tracks which are being maintained and used, so that exercism + those tracks show up in google searches, which is where we get the bulk of our traffic from, after direct hits. <-- sounds like a separate issue/discussion, and fine to write that up, if appropriate.

**Comment by Insti** [comment]
@gusseting thanks. Just having the metadata there should cause *something* to show up which will be a big improvement over what happened previously.

> with limited resources, how can we have the most impact?

It would be good to find out what @kytrinyx thinks is best to concentrate on.

**Comment by kytrinyx** [comment]
I think the thing people link to the most is their submissions. I don't know what makes sense in that situation, though.

> Right now, my recommendation would be to see if we can change the metadata for the language tracks which are being maintained and used, so that exercism + those tracks show up in google searches, which is where we get the bulk of our traffic from, after direct hits.

That sounds like an excellent suggestion.

**Comment by Insti** [comment]
I linked to a submission, and the link showed up nicely. It's great for letting people know what Exercism is.  

![exercism twitter link](https://cloud.githubusercontent.com/assets/5096681/17649107/e0c7643c-622b-11e6-96ea-2564254b1c8e.png)

As for what makes sense when linking to a solution, maybe something like adding a line:
"Insti's first iteration of the beer-song problem" to the summary text.

But that's a separate issue/PR.

Great work @gusseting :heart:

**Comment by gusseting** [comment]
Whoa - that image is rather large! Lets scale that down a little!

**Comment by kytrinyx** [comment]
Deploying the fix in a moment.

**Comment by kytrinyx** [comment]
OK, this should be deployed.

**Comment by gusseting** [comment]
Looks great on slack, no image on twitter - investigating.

**Comment by gusseting** [comment]
@Insti I think we're done here - if you agree, could you close the issue?

**Comment by Insti** [comment]
Thanks for all your work on this @gusseting :heart:
