### ISSUE TITLE
Command Line Interface (CLI) update windows install information

### ISSUE THREAD

**Issue by gusseting** [exercism/exercism.io#3026]
The current CLI information for Windows at http://exercism.io/cli needs updating to reflect changes which include:
- 2015 release of Windows 10 - [21% of market share, so while we have a large % of mac users, there's still a significant % of exercism users affected].(https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0)
- Apt-Get and OneGet for Windows - [Article from Scott Hanselman may be an appropriate resource.](http://www.hanselman.com/blog/AptGetForWindowsOneGetAndChocolateyOnWindows10.aspx)
- 1 simple main method of installation _first_ in the documentation, perhaps with less used methods/systems in a troubleshooting page as per the discussion on onboarding: https://github.com/exercism/discussions/issues/18#issuecomment-235412332
- which package of exercism should be used with Windows 10  - 32bit or 64? Article on switching: http://www.howtogeek.com/228042/how-to-switch-from-32-bit-windows-10-to-64-bit-windows-10/

**Comment by kytrinyx** [comment]
This is great!

Will you be taking a stab at fixing it?

**Comment by gusseting** [comment]
I'm fine to do the update itself, but need some outside guidance. What I'm after is one set of instructions for installing in windows 10, 8, and 7. Can the CLI be installed the same way simply on all three? How?
That's what I need to have the instructions for in order to do the update. I'll do some research, and see who might be able to help.

**Comment by kytrinyx** [comment]
> Can the CLI be installed the same way simply on all three? How?

Excellent questions!

@jwood803 is this something you could help out with?

**Comment by gusseting** [comment]
@kytrinyx it looks like the interim solution to our problem is to simply have the instructions for chocolatey: http://exercism.io/cli#chocolatey as the main instructions, and put the rest into troubleshooting as an alternative. Powershell + chocolately are available for all versions, and chances are that windows folk might already have chocolately installed.

**Comment by blueelvis** [comment]
@gusseting - Are there uninstallation instructions as well for the Chocolatey method? I am working on the polish for the installer. Looking forward to release the polished version :)

**Comment by gusseting** [comment]
@blueelvis I've checked with Katrina, and there's only install required for chocolately.

**Comment by kytrinyx** [comment]
@gusseting that sounds good.

@blueelvis to uninstall, delete the binary (`exercism.exe`) and the config file (`.exercism.json` usually)

**Comment by kytrinyx** [comment]
I'm going to open a new issue to replace this one, since the new installer supersedes all of this.
