### ISSUE TITLE
User finished tracks should determine completeness via a set operation

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/exercism.io#3029]
User finished tracks are currently determined by comparing the number of completed exercises within a track against the total number of exercises currently in the track. The issue is that due to exercise deprecation within a track, there may be exercises completed that are no longer in a track. This comparison should be improved by ensuring that the set of all exercises within a track is a subset of all completed exercises.

See #3015 for some background

**Comment by MohanL** [comment]
I want to have a try on this.

**Comment by MohanL** [comment]
Related issues https://github.com/exercism/exercism.io/issues/3103

**Comment by kytrinyx** [comment]
> what does state do ?

I don't think we currently use `state`. We now have `archived` (bool).

At some point I will go through and figure out what all the deprecated columns are so we can delete them!
