### ISSUE TITLE
Elixir regex syntax highlighting is too greedy

### ISSUE THREAD

**Issue by mathiasose** [exercism/exercism.io#3031]
As seen on line 8 on http://exercism.io/submissions/3d830d8338564b88a4951bf5e3100052

There's probably a regex (ha!) in the syntax highlighter that should be modified to be less greedy.

**Comment by Insti** [comment]
Does this happen on the Rouge demo site? http://rouge.jneen.net/

**Comment by mhelmetag** [comment]
@Insti , it does. Seems to be an issue with the Elixir parser for Rouge.

**Comment by Insti** [comment]
In which case, this is a Rouge issue rather than an Exercism issue.
Please raise an issue on the Rouge project.
Once it is fixed in Rouge we can update the gem and the fix will be available in Exercism.

**Comment by mhelmetag** [comment]
Can do!

**Comment by Insti** [comment]
Why was this closed? Is it fixed? What is the PR for the fix?

**Comment by kytrinyx** [comment]
This is being tracked as an issue in the jneen/rouge repository where the fix belongs.

If you want to track it on Exercism, please open an issue in the https://github.com/exercism/xelixir with the necessary information.

**Comment by Insti** [comment]
We need to remember to update the rouge gem here though.

**Comment by kytrinyx** [comment]
There's an open PR, but I'm waiting for the author to fix based on the feedback I gave: https://github.com/exercism/exercism.io/pull/3452

**Comment by kytrinyx** [comment]
Oh, sorry. You mean "when it happens". Yeah—we will need to update the rouge gem.

What is the correct way to track a dependency like this?

**Comment by Insti** [comment]
I don't know if it is the _correct_ way, but _a_ way is leaving this issue open and until 
https://github.com/jneen/rouge/issues/528 is resolved and an Exercism PR is made that updates Rouge to the fixed version.

**Comment by kytrinyx** [comment]
Fair enough.

**Comment by kotp** [comment]
It is also being tracked there by the @exercism/pascal team.

**Comment by kytrinyx** [comment]
@kotp I believe the Pascal team is tracking a different rouge-related fix.

**Comment by kotp** [comment]
It could be.  This one was mentioned to me directly though, so wanted to make sure it got put in our monitor queue.

**Comment by mhelmetag** [comment]
I think think the elixir syntax highlighting is better now so I closed the rouge issue and I think we're okay to close this one as well. I think maybe just the demo site hadn't updated all those months ago.

**Comment by kytrinyx** [comment]
I'll upgrade it here. v2 is using prism for highlighting, so we may need to verify that it looks right there as a separate task.

**Comment by kytrinyx** [comment]
Upgraded, deploying now. If something looks awful let me know and I'll back out the change.
