### ISSUE TITLE
Check that contribute page excludes foregone exercises.

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3032]
The contribute page lists all the problems that need to be implemented in a language, for example: 
http://exercism.io/languages/ruby/contribute

I'm fairly sure it excludes deprecated exercises but need to also check that this list excludes forgone exercises.

Hint: This data might come from exercism/x-api

**Comment by kytrinyx** [comment]
A specific exercise you can check is Java—for which "leap" is foregone.

**Comment by nickborromeo** [comment]
@Insti @kytrinyx I was browsing the code and I believe the foregone exercises are already being excluded.

```ruby
get '/tracks/:id/todo' do |id|
  track = find_track(id)

  slugs = ::Xapi.problems - track.slugs
```

```ruby
module Xapi
  # Track is a collection of exercises in a given language.
  class Track
     # code ...
     def slugs
      problems + foregone + deprecated
     end
```

Based on this do you think that foregone exercises are still being included?

**Comment by kytrinyx** [comment]
Nope, this looks like a solved problem. Thank you!

**Comment by Insti** [comment]
Thanks for that @nickborromeo  :+1:
