### ISSUE TITLE
Make the exercise list inside each language track easily scannable.

### ISSUE THREAD

**Issue by troubalex** [exercism/exercism.io#3033]
_Copied from #2780_

I am talking about pages like this: http://exercism.io/languages/cpp#exercises

The buttons listing all available exercises look like dropdown buttons but behave like an accordion header which is unexpected. I also wonder if it wouldn't be better to list the name of the exercise as a link, and only add the one line description beside it. The link would then take me to the exercise page with all necessary information.

That way the list would look more like an exercise catalogue, and be fairly easy to scan.

Kind of like this quick hack: http://codepen.io/troubalex/pen/GqYXwm

**Comment by kytrinyx** [comment]
💯 I would love to see this change happen!

**Comment by gusseting** [comment]
@troubalex I'm wondering if instead, each problem could be formatted like so:

Problem 1: Problem description 1
Readme  | Test Suite

Problem 2: Problem description 2
Readme  | Test Suite

Let's discuss re: picking up.

**Comment by Insti** [comment]
I don't think the test suite is useful information on the all problems page.

**Comment by troubalex** [comment]
@gusseting and myself have already talked about it. I'll repeat my arguments here for documentation's sake.

Since test suite an README are tabs on the same page, we'd be winning very little by adding those links to the list items. Adding extra elements to the list would therefore be visual noise making the list harder to scan.

**Comment by GustavoCaso** [comment]
@kytrinyx this issue is closed but the current design reflects the old one, is this correct ?

**Comment by kytrinyx** [comment]
Probably not. I will try to get this sorted out.

**Comment by kytrinyx** [comment]
It was lost; I've put it back. Thanks so much for catching that @GustavoCaso

**Comment by GustavoCaso** [comment]
No problem
