### ISSUE TITLE
Add breadcrumbs to exercise detail pages

### ISSUE THREAD

**Issue by troubalex** [exercism/exercism.io#3034]
This is the flow I base my observations on:
1. Go to "Languages" from by clicking the menu on the top
2. Choose a language
3. Navigate to the exercise list via the left hand navigation
4. Choose an exercise, and navigate to the details page by clicking the README or Test Suite link

What if I now want to go back to the exercise list to check out another one?

The least cumbersome way is to hit the browser's back button (or swipe back if you're the fancy type) until I get there. Alternatively, I could start over from step 1 above.

Adding breadcrumbs would make this more convenient. They should probably look something like this:

Home > Languages > $language > Exercises > $current_exercise 

Both Home and Languages are items up for debate, and a matter of taste and space.

**Comment by troubalex** [comment]
Related to #3033.

**Comment by kytrinyx** [comment]
:heart: I think this would help a lot.

**Comment by troubalex** [comment]
This is done, and can be closed, I believe?
