### ISSUE TITLE
Make language sections separate urls

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3035]
Right now if you go to `exercism.io/languages/:track_id` there is a menu in the sidebar. E.g. http://exercism.io/languages/ruby

Each of these is a section in the same page, and we can't link directly to them. Also, they break the back button in some browsers. If you click into one, you can't use the back button to get to the previous place.

I think that it would be useful to have actual endpoints and urls for each of these.

Relevant code:

- **route** `app/routes/languages.rb`
- **view** `app/views/languages/language.erb`

**Comment by nickborromeo** [comment]
@kytrinyx wanted to help out with this 😄 

Are you thinking about making the url for installing maybe something like 

`exercism.io/languages/:track_id/installing`

And maybe have a view for each section? so that we can replace the `href` with the url?

```html
<li>
  <a data-toggle="tab" href="#installing">Installing <%= track.language %></a>
</li>
```

**Comment by Insti** [comment]
@nickborromeo that sounds good. Let us know if you need any help along the way.

**Comment by nickborromeo** [comment]
this issue can be closed 😄

**Comment by Insti** [comment]
Thanks for your work on this @nickborromeo ! :heart:
