### ISSUE TITLE
refactor css for grays

### ISSUE THREAD

**Issue by gusseting** [exercism/exercism.io#3037]
I'm working on [the user experience for exercism](https://github.com/exercism/discussions/issues/34), and whilst sorting out the css for the navigation to change it grey, noticed the following issues, which I'll be working on:
- the greys specified are in the "muddy accessibility danger zone" as described in [UX/design article from Nathan Curtis](https://medium.com/eightshapes-llc/color-in-design-systems-a1c80f65fa3#.xz4zfjagp)
- we have 2 files, with the same greys, which I'd like to refactor down to 1 set of greys in variables.scss:

exercism.scss:

```
$gray-dark:              lighten($gray-base, 20%) !default;   // #333
$gray-light:             lighten($gray-base, 46.7%) !default; // #777
$gray-lighter:           lighten($gray-base, 93.5%) !default; // #eee
```

variables.scss:

```
$exercism-charcoal: #333;
$exercism-medium-plus-gray: #777;
$exercism-light-gray: #eee;
```

What I'll be doing is a sitewide search and replace to ensure that all the greys above are referenced in the one file, with 1 name. Making this change will mean that when a grey needs to change in the future, it's one change to one file.

**Comment by Insti** [comment]
Awesome @gusseting, I really like these types of posts that give clear description and context for what you'll be working on.

**Comment by Insti** [comment]
That Nathan Curits article is really good, :heart: there is a lot of other advice in there which could also be good for Exercism to adopt.

**Comment by kytrinyx** [comment]
> I really like these types of posts that give clear description and context for what you'll be working on.

Me too! :sparkles: :heart: :heart: :sparkles:

I know GitHub added reactions to avoid me too posts, but I really, really like these and a +1 just doesn't seem like enough.

**Comment by gusseting** [comment]
@Insti oh? Is there anything in particular that you'd like to see adopted?

**Comment by Insti** [comment]
It would be good if there was some kind of short document/page that gave a summary/examples of the different colours.

Here are the brand colours: xxx yyy zzz
Here are the different tints of exercism-pink we use: xxx yyy zzz
Here are the different tints of exercism-grey we use: xxx yyy zzz
Here are the feedback colours: success warning error informational

All this is probably available in the css, but it would be nice to have a design document to refer to.
(I guess it could be generated from the css.)

**Comment by gusseting** [comment]
@Insti agreed, and a styleguide (a summary of styles, and what goes where) is certainly something that I'm aiming for ASAP before the end of September. I've got a quick and dirty version that I'm using locally for the moment:
![bootstrap_hack](https://cloud.githubusercontent.com/assets/540264/17514192/8c540f6e-5e74-11e6-957d-695d7c4ea9d8.png)
It would be great to have something more public facing that can help anyone that needs to use design elements, and would mean that maintainers could simply point people to the styleguide when contributors need to know what a button etc should look like.

**Comment by kytrinyx** [comment]
If we don't hear back from @gusseting on this one in the next few days, we can assume that it's up for grabs.

**Comment by troubalex** [comment]
I assume http://exercism.io/styleguide is somewhat relevant to this? According to the [contributing guide](https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#styleguide), the page is auto-generated by [KSS](https://github.com/kneath/kss).

**Comment by kytrinyx** [comment]
Huh. I forgot about that page. I wonder if it's still up-to-date. We don't have that "pending submissions" page anymore, we use the activity streams.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this. We will gladly review CSS refactorings. I'd like to mention, however, that we're doing a redesign of the website (doing user experience design from the ground up). For more about this see exercism/discussions#113
