### ISSUE TITLE
nodejs deprecation warnings

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3041]
When running npm as part of the build process there are a number of deprecation warnings that probably need addressing, For example see: https://travis-ci.org/exercism/exercism.io/builds/150752208

```
npm WARN deprecated grunt-ngmin@0.0.3: use grunt-ng-annotate instead

-npm WARN deprecated ngmin@0.4.1: use ng-annotate instead

-npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

/npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

-npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

/npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

\npm WARN deprecated graceful-fs@1.1.14: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

| 

> js2coffee@0.3.3 preinstall /home/travis/build/exercism/exercism.io/frontend/node_modules/lineman/node_modules/js2coffee

> node ./cyclic.js

|npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

-npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.36","npm":"1.4.28"})

npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.36","npm":"1.4.28"})

npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.36","npm":"1.4.28"})

|npm WARN deprecated lodash@2.3.0: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

/npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

-npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

|npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

-in@0.0.3 node_modules/grunt-ngmin

└── ngmin@0.4.1 (astral@0.1.0, clone@0.1.19, commander@1.1.1, astral-angular-annotate@0.0.2, esprima@1.0.4, escodegen@0.0.28)
```

Is there someone who knows about nodejs who can look into this?

**Comment by kytrinyx** [comment]
That's a good question. @bernardoamc @tejasbubane - is this something you know about?

**Comment by bernardoamc** [comment]
> is this something you know about?

Unfortunately no, but we have to change the `frontend/package.json` file to solve these warnings. I don't know which versions we should use to avoid breaking things though.

**Comment by kytrinyx** [comment]
> I don't know which versions we should use to avoid breaking things though.

I honestly don't think anyone knows at this point.

**Comment by tejasbubane** [comment]
Not sure if this will break things, but I can give a try to upgrade these dependencies. 

@kytrinyx Should I do this as a part of #2949 so that you can test it as a whole, or do you want a separate PR?

**Comment by Insti** [comment]
Since we're not sure what will break, a separate PR seems like a good idea.

**Comment by kytrinyx** [comment]
> a separate PR seems like a good idea.

Agreed.

**Comment by jtigger** [comment]
@Insti any update on this?

**Comment by Insti** [comment]
@tejasbubane was going to be looking into this, have you had a chance to look at it @tejasbubane I know you've been busy with other things as well!

**Comment by tejasbubane** [comment]
I missed this one. I can look into this in a couple of days, but if @jtigger wants to give it a try, he can go for it.

**Comment by kytrinyx** [comment]
Are we still seeing deprecation warnings?

**Comment by tejasbubane** [comment]
@kytrinyx Yes there are still warnings in the [latest build](https://travis-ci.org/exercism/exercism.io/builds/217259250). 

I see two types of warnings:
1. **Package deprecations:** Some of these are related to [lineman having deprecated dependencies](https://github.com/linemanjs/lineman/issues/390). We might need to fix these upstream.

2. **Nodejs version warnings:** Might be related to our [travis config](https://github.com/exercism/exercism.io/blob/master/.travis.yml) where we have set `language: ruby` but are installing lineman directly (without selecting/installing node version). Looks like travis has no way of setting [multiple languages for single project](https://github.com/travis-ci/travis-ci/issues/4090#issuecomment-217704573), but nodejs version can be set using [nvm](http://stackoverflow.com/a/31928227/3507206). That might fix these warnings.

**Comment by kytrinyx** [comment]
Thanks @tejasbubane both of those sound doable, if anyone wants to take a stab at them.

**Comment by Insti** [comment]
This is probably another one of the things we will continue to ignore until it is no longer a problem when we move to Nextercism.

**Comment by tejasbubane** [comment]
> This is probably another one of the things we will continue to ignore until it is no longer a problem when we move to Nextercism.

The problem is some of them are lineman dependencies and it isn't maintained anymore.

**Comment by kytrinyx** [comment]
> This is probably another one of the things we will continue to ignore until it is no longer a problem when we move to Nextercism.

Yeah, I'm OK with this, to be honest. In a perfect world I would deal with them but I'm slammed as it is, and I'm prioritising other things.
