### ISSUE TITLE
Help Page has missing information

### ISSUE THREAD

**Issue by blueelvis** [exercism/exercism.io#3045]
Hello ^_^,

The Help page located here - http://exercism.io/help
is missing some information.

The `Directories` section does not tell anything about the `exercism configure --dir=` command. The code part should be changed.

Also, at the bottom of the page, there are outgoing links for opening Issues and PRs. I think they should redirect to this repository instead of the Github Help Pages.

**Comment by bernardoamc** [comment]
Thanks for the information @blueelvis! ^^

Do you want to tackle this?

**Comment by blueelvis** [comment]
Yep. Will do :)

**Comment by blueelvis** [comment]
@bernardoamc - Sorry to say but I am really having trouble finding how that page is rendered :( . There is no route as well defined for that page. Could you please give me a hint? :)

**Comment by kytrinyx** [comment]
The page can be hard to find.

The route starts here: https://github.com/exercism/exercism.io/blob/master/app/routes/static.rb#L16

Holler if you have trouble finding anything—it's a bit of a mess in there.

**Comment by bernardoamc** [comment]
Sorry for the delay. :)

A good trick when you don't find the route is to copy some text from the page and do a search for it using something like grep or ack. This way you will find the view file, with the view file you can do another search to find the route file. In your case:

```
$ ack "Troubleshooting" app/views/
app/views/site/help.erb
8:    <h2>Troubleshooting</h2>
```

The view file is `site/help.erb`, so:

```
$ ack "site/help" app/routes
app/routes/static.rb
17:        erb :"site/help", locals: { docs: X::Docs::Help.new }
```

And you have the route. :)

**Comment by blueelvis** [comment]
@kytrinyx @bernardoamc - Thanks a lot for the perfect explanation! I found the page after searching around and hence deleted my previous comment.

I have created a PR. Please take a look when free :)

**Comment by bernardoamc** [comment]
Thanks @blueelvis ! I think we can close this one? 🎉
