### ISSUE TITLE
Design Issue - Correct margins below code snippets

### ISSUE THREAD

**Issue by gusseting** [exercism/exercism.io#3046]
As noted in #2535, we have a visual problem with margins below code snippets - in that there doesn't appear to be any. I'm not sure how widespread this issue is, but I've noticed it in the following:
http://exercism.io/cli
http://exercism.io/help (screenshot below)
![cssmarginproblem](https://cloud.githubusercontent.com/assets/540264/17578534/75210f40-5fcd-11e6-94b4-67b4c043b95a.png)

I've tried to find the appropriate css, have come up with `<div class = “highlight shell”>`, but got stuck re: how to find and change the source file, and which content is dependent on that source.

**Comment by Insti** [comment]
Try: `exercism.io/public/sass/base/components/pygments.scss`

Found by `grep`ping the sass files for `\.highlight` and looking at a few matching files to see which one had the other css properties.

**Comment by troubalex** [comment]
> Try: exercism.io/public/sass/base/components/pygments.scss

Isn't that the standard Pygments styles file? If so, adding a margin here would overwrite it if Pygments ever is updated. 

If that is the case, adding a margin to ```.highlight``` could be done in exercism.scss

**Comment by Insti** [comment]
@troubalex I know more about  `grep` than I do about `scss` :) so I'm happy to see your recommendations.

**Comment by troubalex** [comment]
I double checked, and the change should probably go into ```exercism.io/public/sass/application.scss```

**Comment by bernardoamc** [comment]
We can tag this with `good first patch`. =]

**Comment by bhoover85** [comment]
Hello, I've created pull request #3062 for this issue.

**Comment by nickborromeo** [comment]
looks like the fix for this was merged 😄 we should close this issue out.
