### ISSUE TITLE
Display for Code and Comment does not match in "horizontal split" mode

### ISSUE THREAD

**Issue by kotp** [exercism/exercism.io#3057]
![wrong size](https://cloud.githubusercontent.com/assets/16747/17728588/f3523236-642d-11e6-894a-851ca59e313b.png)

The above graphic shows that the comments are not as wide as the screen, when the view is horizontally split.

One of the reasons for selecting this view is in viewing the code, but sometimes the code examples in answers need the additional width as well to be easily read.

**Comment by Insti** [comment]
I expect this is caused by #3050 and is probably not a separate issue.

**Comment by kotp** [comment]
Right on.  Updated picture to hopefully be more clear.
