### ISSUE TITLE
Permission denied on runtests.sh

### ISSUE THREAD

**Issue by AWaselnuk** [exercism/exercism.io#3061]
This is probably a gap in my understanding of bash and linux but I'm not sure where else to ask this question.

Whenever I fetch a new exercise, I can't immediately run `runtests.sh` because the file does not have the correct permissions.

![screen shot 2016-08-18 at 9 31 29 am](https://cloud.githubusercontent.com/assets/3630241/17775517/9442bc3a-6526-11e6-914c-be0df8262386.png)

I can certainly change this with `chmod` but is there a way to permanently change permissions so that I don't have to run `chmod` after every fetch?

**Comment by kytrinyx** [comment]
We explicitly made the CLI write the files as non-executable. The discussion was held here: https://github.com/exercism/cli/issues/276

If you think we should re-evaluate this decision, would you mind opening a new ticket in the github.com/exercism/cli repository and reference the previous discussion there?

**Comment by AWaselnuk** [comment]
Thanks @kytrinyx. I'll read that discussion and consider opening a new ticket if I strongly disagree :)
