### ISSUE TITLE
all solutions accessible in team's dashboard

### ISSUE THREAD

**Issue by davideghz** [exercism/exercism.io#3065]
Hi :)

In the team's dashboard iI can see/access other team members' solutions even if I have not posted my solution yet for those exercises.. I guess it's a kind of a bug / unexpected use case

**Comment by kotp** [comment]
This has been like it always has been, and I think it is as designed.  This is good, and acceptable, because even if you are not logged into github, as long as you know the link, you are able to see the solution as well.

**Comment by kotp** [comment]
@davideghz did you know that you can also submit a failing or incomplete exercise to be able to see others solutions?

Thanks for posting an issue, I know it is appreciated!

**Comment by davideghz** [comment]
hi @kotp, thanks for pointing out the fact solutions are accessible as long as you know the link, i didn't notice it. I knew it's possible to access solutions posting a failing exercise, but that to me means losing the challenge, and - for what that can matter - it is registered as a solution that most likely will be improved!

**Comment by kytrinyx** [comment]
@davideghz Yeah, this is intentional. In teams it's common to pair on work, and also to have mentors who review code, but don't do many exercises.

**Comment by davideghz** [comment]
@kytrinyx very clear use case, thank you
