### ISSUE TITLE
Elm Track: Not sure how to run tests / Something wrong with test framework setup

### ISSUE THREAD

**Issue by jehoshua02** [exercism/exercism.io#3067]
Things have been going very smoothly so far. Until I got to the robot-simulator exercise.

There was no `runtests.sh` file like previous exercises and no instructions on how to run the tests.

What I tried:

1. Copying in `runtests.sh` from a previous exercise. It builds and executes but no test output is reported to the terminal window, even after modifying code to guarantee test failure.
2. Running `elm-test` installed via `npm install -g elm-test`. I tried `elm-test RobotSimulatorTests.elm` and just get strange errors that I have no idea how to fix.

So I refactored the test to match previous exercises, verify they fail and produce output as expected, then continued on with the exercise.

I submitted all the files I had to modify to get it working.

Link to my submission: http://exercism.io/submissions/81b881ea88cf40b693d37ca794b27b1a

That's all fine, I was able to finish that exercise, but then I fetched the next one (list-ops) and same thing.

Being new to the elm ecosystem I have no clue what's going on here and how I should cope. If you guys need help updating exercises, I'd be glad to help. Or if there's something I'm missing to get those tests working I'd love to learn. I just don't know what's what yet so I can't be sure what the right way is here.

Please help. Thanks!

**Comment by jehoshua02** [comment]
```~/exercism/elm/list-ops
$ node --version
v4.2.1
~/exercism/elm/list-ops
$ elm --version
0.17.1
~/exercism/elm/list-ops
$ elm-test --version
0.17.3
~/exercism/elm/list-ops
```

**Comment by kytrinyx** [comment]
Hi @jehoshua02! Some help getting this sorted would be excellent! Would you mind opening this in the elm repository for these exercises? The @exercism/elm folks there will be able to help you figure out what the fix is and point you in the right direction with respect to making the change.

**Comment by tgecho** [comment]
@jehoshua02 I'm so sorry about the confusion. We have an open issue about the removed `runtests.sh` here https://github.com/exercism/xelm/issues/100

Please feel free to open another issue over there if that doesn't look relevant.

**Comment by jehoshua02** [comment]
@tgecho yeah same issue. Closing this one. Thanks.
