### ISSUE TITLE
When a comment is about 24 hours old no timestamp appears next to it

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3076]
In this screenshot you can see that the first 3 comments have visible timestamps, but the 4th does not:
![exercism - undated comment](https://cloud.githubusercontent.com/assets/5096681/17882167/00daa708-690b-11e6-994e-5451ac092e33.png)

It did show a timestamp yesterday when I posted the comment, and did a again few minutes later.

Here is a screenshot from the Firefox element inspector which shows the relevant html:
![exercism - undated comment - html](https://cloud.githubusercontent.com/assets/5096681/17882166/00d1fd9c-690b-11e6-93b4-d45e4a483627.png)

### Knowledge required:
Basic Ruby, a bit of html, maybe some javascript.

### Where to start: 

`app/helpers/fuzzy_time.rb`
`test/app/helpers/fuzzy_time_test.rb`

The [Contributing guide](https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md) can help you set up an exercism.io development environment if you do not already have one.

### What to do:

* Work out what the problem is.
* Create a failing test case that demonstrates this.
* Fix the code so that the test no longer fails.
* Submit a pull request
* Improve the pull request based on feedback from reviewers.
* Celebrate once your pull request is accepted into the project and the bug is fixed!

### Other information: 
Recent pull request that updated the time handling: #3021

### Optional extra challenge:
This is NOT a requirement, but an optional extra if you can handle a bigger challenge.

Refactor to eliminate the (currently ignored) Rubocop warnings: Metrics/AbcSize, Metrics/MethodLength, Metrics/CyclomaticComplexity

### Help?
We're happy to help however we can. Just post a reply to this issue.

If you're planning on working on this issue please post a comment below so other people know it's being worked on.

**Comment by blueelvis** [comment]
@Insti - Oh my god! I simply wish I could give you a hat for writing in this detail for the beginners. Would it be fine to tackle this one? I don't know Ruby but I can try to fix this issue out :)

**Comment by Insti** [comment]
sure @blueelvis, you can learn some Ruby along the way :)

**Comment by blueelvis** [comment]
@Insti - Please allow me a bit more time. The instructions to setup the whole website are somewhat confusing :( . I am trying to create a vagrant script to see if it could also be made a single source for installation :)

**Comment by blueelvis** [comment]
@Insti - I have setup my development environment and got exercism.io up and running. But, there is one problem, in order to test the Comments functionality, I have to go and browse some of the exercises to make comments and check. But, whenever I click on any of the exercise, it says that "That submission does not exist"

On checking the logs, it checks the local `exercises` directory which is not present in the Github repository. Any workaround?

**Comment by kytrinyx** [comment]
>  But, whenever I click on any of the exercise, it says that "That submission does not exist"

Could you post a screenshot of how you're navigating?

> On checking the logs, it checks the local exercises directory which is not present in the Github repository.

Could you paste one of the log messages?

**Comment by blueelvis** [comment]
> Could you post a screenshot of how you're navigating?

Here is the screenshot -
![2016-09-06](https://cloud.githubusercontent.com/assets/6985763/18281925/73083ad0-747c-11e6-900f-b6566fc4d079.png)

The link is this - http://localhost:3030/exercises/b796cae2192e4fb5f44ac377

> Could you paste one of the log messages?

Here is the log message which is relevant according to me -

`12:05:51 web.1  | 10.0.2.2 - - [06/Sep/2016:12:05:51 +0000] "GET / HTTP/1.1" 200                                    19928 0.0276
16:25:12 web.1  | 10.0.2.2 - - [06/Sep/2016:16:25:12 +0000] "GET /exercises/b796cae2192e4fb5f44ac377 HTTP/1.1" 302 - 0.0043
16:25:12 web.1  | 10.0.2.2 - - [06/Sep/2016:16:25:12 +0000] "GET / HTTP/1.1" 200 19928 0.0164
16:25:12 web.1  | 10.0.2.2 - - [06/Sep/2016:16:25:12 +0000] "GET /icons/logo.svg HTTP/1.1" 200 776 0.0014`

**Comment by kytrinyx** [comment]
@blueelvis Did you run the rake task to get seed data? You should already have comments.

**Comment by kytrinyx** [comment]
For reference, the relevant code is in https://github.com/exercism/exercism.io/blob/master/app/routes/user_exercises.rb#L4-L17

**Comment by kytrinyx** [comment]
In the database, the table is called `user_exercises`, and each user exercise has many `submissions`.

**Comment by nickborromeo** [comment]
@blueelvis wanted to see if you are still actively pursuing this?

**Comment by kytrinyx** [comment]
If @blueelvis doesn't respond within a week, I think we should call this up for grabs.

**Comment by MohanL** [comment]
I want to have a try on this

**Comment by bernardoamc** [comment]
Awesome @MohanL ! Thank you!

**Comment by Insti** [comment]
> Create a failing test case that demonstrates this.

>    find a case where failing test case happens (Need Help, ideas )

@MohanL: You need to look in, `test/app/helpers/fuzzy_time_test.rb` and create a new failing test case.

It will probably fall between: `test_a_bit_more_than_23_hours_ago` and `test_bit_more_than_a_day`

**Comment by MohanL** [comment]
Pull request at https://github.com/exercism/exercism.io/pull/3159
