### ISSUE TITLE
Add .gitignore file for Haskell 'projects' now you're using stack

### ISSUE THREAD

**Issue by mikemcgowan** [exercism/exercism.io#3080]
In particular, the `.stack-work` directory should be in `.gitignore`.

**Comment by Insti** [comment]
Thanks @mikemcgowan 

Which `.gitignore` are you referring to?
It already exists in the xhaskell `.gitignore` https://github.com/exercism/xhaskell/blob/master/.gitignore#L22


(Can someone on the @exercism/haskell team look at this?)

**Comment by mikemcgowan** [comment]
Ah, sorry, that could've been clearer.

Today, after a three month break, I did `exercism fetch haskell prime-factors` and I saw that, unlike three months ago, I got a Stack project (instead of just ad-hoc files). (Which is a great improvement, btw!)

In the subsequently downloaded `prime-factors` directory (i.e. the one with `prime-factors.cabal`, `package.yml` and `stack.yml`) I don't have a `.gitignore` file, so when I do `stack build` or `stack test` or whatever, the `.stack-work` directory isn't excluded from version control.

It's no big deal, really, I can just add a `.gitignore` file to every fetched exercise, but I suppose it would be nice for it to be there by default. (I haven't got any `.gitignore` file anywhere in my Exercism directory.)

**Comment by Insti** [comment]
Exercism doesn't come with git built-in\*, so you must have set up the repository yourself.
In which case I suggest just creating your own `.gitignore` file in your top level Exercism directory.

\* Unless there are there some instructions somewhere that suggest setting up a repository for your Exercism problems?

**Comment by mikemcgowan** [comment]
Okay, no problem. There's no such instructions I know about. I'll close this.
