### ISSUE TITLE
Login: Fix signup for those without a github account.

### ISSUE THREAD

**Issue by gusseting** [exercism/exercism.io#3084]
Here’s the problem:
1. go to the “Login with Github” on the top right of exercism.io
2. you don’t have a github login, so you sign up for one.
3. you can’t do anything until your email signup is verified, so you verify your email
![screen shot 2016-08-26 at 9 53 42 am](https://cloud.githubusercontent.com/assets/540264/17991294/a09cd51e-6b80-11e6-8c35-a5822a792aeb.png)
1. you end up on this screen on github, and aren’t redirected back to exercism:
   ![screen shot 2016-08-26 at 7 40 12 am](https://cloud.githubusercontent.com/assets/540264/17991263/5cb846b2-6b80-11e6-9e28-05833eb730ca.png)

Possible solutions:
a) we make it a requirement that you have to have a github account before logging in, and the login process needs to make that requirement clear.
b) we ensure that the redirect happens after verification.

Linking back to lowering the barrier to entry: https://github.com/exercism/exercism.io/issues/2323

**Comment by joeltaylor** [comment]
This is an interesting one!

Generally, we can pass a redirect url to OAuth to bring the user back, but it doesn't seem like Github includes that redirect in their email verification link. I've gone ahead and submitted a request via Github support to see if that's something that's plausible.

It seems like the only thing we could do is what you proposed in solution `a`, which would require a designated login page. 

I wonder if it'd make sense to have a "login" and "sign up" link in the header. The "sign up" page could include the necessary copy to prep brand new users while not being too tedious for those already familiar with Github?

**Comment by gusseting** [comment]
@joeltaylor it would make sense, yes. I've documented a solution for a consistent "get started" link in the header: https://github.com/exercism/discussions/issues/64#issuecomment-244658945

**Comment by kytrinyx** [comment]
> I've gone ahead and submitted a request via Github support to see if that's something that's plausible.

:heart:

This would be lovely to get fixed.

**Comment by troubalex** [comment]
> I wonder if it'd make sense to have a "login" and "sign up" link in the header. The "sign up" page could include the necessary copy to prep brand new users while not being too tedious for those already familiar with Github?

Based on my experience, there is a number of advantages with a dedicated screen like that. 

1. Not everyone realizes that OAuth lets you sign up **as well as** log in through the exact same button. I have seen even technically savvy users stumble there.
2. A dedicated sign up page would be an excellent place to sum up all the benefits of being an exorcism member in a TL;DR format.
3. It makes for a nice, more caring onboarding experience.

Downside is that for people who **do** understand OAuth, this may be total overkill. It might be worth finding out of these people just use the "sign in with Github" button in the top bar without even entering the sign up screen...

I'm personally not sold on having two CTAs in the header. But that is of course up for debate.

**Comment by kytrinyx** [comment]
I think that for us the benefits of a dedicated sign up page outweigh the costs. It would help people understand what's going on, and warn them ahead of time that they need a GitHub account, and if they don't have one, create one first.

I thought it was common to have both "sign up" and "sign in" in the header. Sign up would go to the dedicated page, and sign in would kick off the authentication process.

**Comment by troubalex** [comment]
> I thought it was common to have both "sign up" and "sign in" in the header. 

Yes, it's a matter of taste, and depends on the context. I personally don't like it because two CTAs compete with each other for attention to some extend, and it's very easy to click the wrong one if you're not particularly observant or clumsy.

That being said, not having both in the header requires more carefully placed CTAs on pages at the top of the funnel.

**Comment by joeltaylor** [comment]
With strategic styling, we could potentially reduce the CTA competition. For example, this is what the designers came up with where I work:

![screen shot 2016-09-19 at 4 07 20 pm](https://cloud.githubusercontent.com/assets/6965062/18647307/5e2b398a-7e83-11e6-8c14-97d2ded0d01a.png)

**Comment by kytrinyx** [comment]
@joeltaylor I like that. I'd be very unlikely to click the "create free account" if I'm looking for "sign in".

**Comment by kytrinyx** [comment]
I'm tracking this issue for the redesign (see https://github.com/exercism/discussions/issues/113). I am going to go ahead and close this, leaving the problem to be solved in the new site.
