### ISSUE TITLE
No documentation shown for Upcoming and Planned tracks

### ISSUE THREAD

**Issue by catb0t** [exercism/exercism.io#3094]
https://github.com/exercism/xfactor/issues/17

Click any of the "Upcoming" or "Planned" language tracks [here](http://exercism.io/languages) and none of them show their docs even if their respective repos have docs in `docs/`.

**Comment by tejasbubane** [comment]
@catb0t Does that `https:` link to `/languages` page work for you?

**Comment by catb0t** [comment]
@tejasbubane um, that's weird, it worked yesterday and every day before then. maintenance?

**Comment by kytrinyx** [comment]
Ahhh the missing docs thing is definitely a bug.

**Comment by ramyaravindranath** [comment]
Fixes bug https://github.com/exercism/exercism.io/pull/3097

**Comment by catb0t** [comment]
Closed by #3097.
