### ISSUE TITLE
Add "Contact Us" to the footer

### ISSUE THREAD

**Issue by gusseting** [exercism/exercism.io#3095]
Suggestion: have the contact us info from the [readme file on github](https://github.com/exercism/exercism.io/blob/e8748dac272f3f0aaa8041bf5d5b652240a21b58/README.md) in the footer on the website, as a link to a static page, and make it an issue for a newbie to do their first PR with exercism.io.

Contact Us

To report a bug, suggest improvements to exercism.io, or if you're having trouble installing or using the CLI, please open a GitHub issue. You can also visit our support chat. We'll do our best to help you out!

Follow us on Twitter @exercism_io.

For occasional updates, such as new language tracks being launched, sign up for the newsletter.

Exercism.io was started by Katrina. To get in touch with her, send an email to kytrinyx@exercism.io.

@Insti I thought this could be a good issue for a complete newbie to exercism, and started writing the documentation, however it seemed to get quite involved. If you'd like to go ahead with it, my incomplete work is here: https://gist.github.com/gusseting/a075fb96b33c7346c1b090843c8de6fd

**Comment by troubalex** [comment]
I think this can be closed since @hailuhr's PR has been merged. 👏

**Comment by kytrinyx** [comment]
Yes! thanks everyone
