### ISSUE TITLE
Make the list of language track repositories more scannable

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3101]
In the repositories page (http://exercism.io/repositories) there is a list of language track repositories in a grid.

Let's turn this into a table with:

- the icon
- the name of the programming language (links to the exercism/languages/:track_id page)
- the link to the GitHub repository (display the full link as the anchor text)

The code for this starts in the `app/views/languages/repositories.erb` file.

**Comment by ramyaravindranath** [comment]
@kytrinyx : Looking into it.
