### ISSUE TITLE
When Adding Yourself To A Team That You Created, Accepting Invite Causes Error

### ISSUE THREAD

**Issue by weilandia** [exercism/exercism.io#3110]
When a user goes to /teams/new and subsequently adds themselves to the team invite list and creates the team, the user gets an invite to the team that blows up upon accepting the the invite.

Potential solution: If a user adds themselves to a team that they are creating, they should not get an invite.

<img width="856" alt="screen shot 2016-09-16 at 12 34 31 pm" src="https://cloud.githubusercontent.com/assets/13652979/18593637/5232adf0-7c0a-11e6-91b9-ad46e3feb8b8.png">

**Comment by weilandia** [comment]
<img width="950" alt="screen shot 2016-09-16 at 12 34 37 pm" src="https://cloud.githubusercontent.com/assets/13652979/18593639/5572bb86-7c0a-11e6-8e74-df020eea2fba.png">

**Comment by weilandia** [comment]
I can work on this if ya'll want.  Lmk :)

**Comment by mhelmetag** [comment]
Go for it! Looking forward to the PR and seeing what approach you took.

**Comment by bernardoamc** [comment]
Thank you for noticing this, don't hesitate to ping me if you have questions! ❤️

**Comment by aaron-suarez** [comment]
Also, if you created the group, then you refuse the invite, it doesn't take you away from the group.

@weilandia Are you still working this? If not, we can go ahead and take it over.

**Comment by MohanL** [comment]
@aaron-suarez, do you mind if I join your team for this bug ?

**Comment by aaron-suarez** [comment]
I have no problem with that. @nellshamrell is our team leader, so I'll let you coordinate with her about the coordination details :slightly_smiling_face:

**Comment by weilandia** [comment]
@aaron-suarez go for it!

**Comment by MohanL** [comment]
@aaron-suarez  @nellshamrell 
how are you guys going to do this ? How can I join the team ?

**Comment by MohanL** [comment]
It is just an interesting bug. Guys, I am working on this. 

- [ ] recreate the error 
- [ ] form a logic 
- [ ] coding 
- [ ] PR
- [ ] Improvement

**Comment by aaron-suarez** [comment]
Sorry if there was a lack of communication for a few days there. We typically have a conference call on Saturdays but this last one was especially inconvenient for several of us and no one was really able to make it. As far as I'm concerned, if you find a solution to this between now and next Sat, feel free to submit the pull request and we'll pick a different issue for that week. If you don't find a solution, I'll send you an invite to our call and we can all collaborate together. @nellshamrell let me know if you have any issues with that

**Comment by MohanL** [comment]
@weilandia @aaron-suarez can you guys try to replicate the error ? I have tried and it seems like when I invite myself, I don't get any notifications.

**Comment by aaron-suarez** [comment]
I did replicate the error:

![screenshot from 2016-10-18 23-55-18](https://cloud.githubusercontent.com/assets/2008701/19506125/6d15cf42-958e-11e6-9e04-439b15dbf693.png)

![screenshot from 2016-10-18 23-55-34](https://cloud.githubusercontent.com/assets/2008701/19506126/733f394e-958e-11e6-9b83-08ff76adb0fd.png)

**Comment by MohanL** [comment]
@aaron-suarez  please do invite me for the conference call, Thank you

**Comment by nellshamrell** [comment]
@aaron-suarez The more the merrier!

**Comment by Insti** [comment]
Is getting an invite for your own group even a good idea?
I expected I would just create the group and be a member without any invitation and was surprised when one showed up in my notifications.

**Comment by aaron-suarez** [comment]
@Insti I agree that there probably should be no invitation given to the group creator. This would solve both issues discussed in the thread. We'll make it so that the group creator can't receive an invitation to their own group, but are instead automatically added as a manager.

**Comment by MohanL** [comment]
@aaron-suarez 
we could probably do a check on the team's member set to decide weather it is valid to add the user. what do you think ? Also, we could have notifications saying that someone is already a member of the team if the invitation is not valid.  What do you think ?

**Comment by aaron-suarez** [comment]
That sounds good. By the way, have you been getting any of the emails I've sent to contact@mohanl.com ?

**Comment by MohanL** [comment]
@aaron-suarez Yes, I just saw it. sorry about the late reply.

**Comment by lizvdk** [comment]
Does anyone want to take this on? It looks like #3219 is not moving forward.

**Comment by bernardoamc** [comment]
Will take a look when I get home, thanks for bumping it up @lizvdk!
