### ISSUE TITLE
Remove ATTRIBUTION.md and all track icons from public/img/tracks/*.png when all submodules are updated

### ISSUE THREAD

**Issue by catb0t** [exercism/exercism.io#3112]
This is kind of a placeholder issue for myself. I expect the PRs I'll be creating to add attribution and track icons to various track repositories that are missing one or both of these to be accepted in the next few weeks, and then we can nuke `public/img/tracks/*.png`.

**Comment by kytrinyx** [comment]
:tada: Thanks for taking the time to go through and fix all of these!

**Comment by catb0t** [comment]
And thank you for going through and merging the rest of those! Of course, I'm not done yet, I was just waiting for those to be closed before opening more. :)
