### ISSUE TITLE
After submitting a comment, there is still a comment in the textarea

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3123]
When I do a review on a submission and submit the comment, I can see the submitted comment in the discussion, also the source of the comment remains in the comment-editor.

Some browsers think, we had a (partially) filled form and warn when we try to leave and ask if we really want to leave the page or finish the form.

I realized this behaviour the first time a couple of days ago and canceled the pageswitch, and checked carefully if my comment was submitted. I did that about the first two or three times.

Today I nearly lost a comment, because I thought "Oh... that one again, just click leave" and closed the tab. In another tab I saw a similar problem, so I wanted to go back, hit CTRL-SHIFT-T to recover last closed tab and realied that I had not submitted my comment. I was able to repair it, but who knows how many were really lost?

**Comment by jtigger** [comment]
@NobbZ do you have a specific proposal to address this?

**Comment by NobbZ** [comment]
Delete the content of the textarea after submitting it should be totally sufficient. About everyone else on the internet does it like that ;) eg: After hitting submit for this reply, the box I am typing in, will be empty.

**Comment by jtigger** [comment]
Huh... actually... I'm unable to replicate this bug, @NobbZ.

Here's the steps I took:

1. view a submission on the site (e.g. http://exercism.io/submissions/e8252c46a95547eb8cfe327dc4377cdf)
- enter a comment and click "Submit Comment"

Based on how I'm reading the issue, the bug I expect to see is that not only is my comment listed, but the comment text is still in the textarea, like this: 

![image](https://cloud.githubusercontent.com/assets/470176/19025250/ebe0193e-88ca-11e6-8f3a-e524336a0865.png)

... but I don't.  Instead, I see this ...

![image](https://cloud.githubusercontent.com/assets/470176/19025259/fd95d524-88ca-11e6-8148-1645c9aba55f.png)

... which is the *expected* behavior.

**Comment by NobbZ** [comment]
I just retried, also disabling selectively a bunch of plugins which could possibly interfere, and as a last resort I even commented in inkognito-mode, disabled all plugins, even there I have the behaviour described above.

* **Operatingsystem** Windows 10
* **Browser** Google Chrome 53.0.2785.116

**Comment by jtigger** [comment]
I've tried this on a plain vanilla install of Windows 8, IE 11 and Chrome 53.0.2785.143.  I still haven't been able to replicate. :(

**Comment by NobbZ** [comment]
I tried again from my working computer using my browser config from my home computer, weird as it is, at work it "works"...

So it seems that there is something else at home that interferes, something outside of the browser. I will close this ticket, since there is currently no reason anymore to think it were exercisms fault.
