### ISSUE TITLE
Add exercism to up-for-grabs?

### ISSUE THREAD

**Issue by Trevoke** [exercism/exercism.io#3124]
Up-for-grabs is a website that tracks issues that are approachable for beginners and people new to contributing to open source. I know exercism is doing this, why not add it?

https://github.com/up-for-grabs/up-for-grabs.net#add-your-project

**Comment by kytrinyx** [comment]
Hi @Trevoke I think it would make sense to add individual language track repositories if and only if:

- there are 2 or more active maintainers
- we have issues that we can label with "good first patch"

There are a lot of tracks where we don't have enough active maintainers, and sometimes people wait a very long time before someone notices their issue or pull request. I'm putting in place much better filters for my exercism notifications, so I am catching more of these, but it's still a problem, and in many languages I can't provide actual feedback on pull requests, so it doesn't really help much that I see an issue. My response will usually be "thank you for this, let me see if I can track down someone to do a code review".

Mozilla has done research about this—the real kind, not the "I poked around on the internet a bit" kind :-) and they discovered that if someone gets a response from maintainers (or people who are highly engaged with the project) within 24 hours of opening an issue or a pull request, then their likelihood of making a second contribution skyrockets.

https://docs.google.com/presentation/d/1hsJLv1ieSqtXBzd5YZusY-mB8e1VJzaeOmh8Q4VeMio/edit#slide=id.g4435d357b_20

**Comment by kytrinyx** [comment]
I forgot to mention that a "response" doesn't mean that the issue gets resolved or that the patch gets merged within those 24 hours.

**Comment by Trevoke** [comment]
I completely missed that you had replied! My apologies. Tool snafu.

Is there some kind of "Exercism health dashboard" where we can find out
which tracks need maintainers, etc?

**Comment by kytrinyx** [comment]
> Is there some kind of "Exercism health dashboard" where we can find out
which tracks need maintainers, etc?

There's no dashboard per se, but we did do a deep dive into the current state of things a couple of weeks ago, where we categorized tracks as _maintained_, _at risk_, _endangered_, and _orphaned_. https://github.com/exercism/discussions/issues/97

I think that for this we could add all the tracks that are _maintained_ or _at risk_ to **up for grabs**.

**Comment by kytrinyx** [comment]
I'm taking a pass through our issue tracker with the goal of making sure that every open issue we have on exercism/exercism.io is actionable. 

As this issue stands it isn't actionable. If you would like to move this topic forward, please open a new issue in http://github.com/exercism/discussions

Please:
- summarize the points so far in 
- link back to this issue
- include the intended goals for the discussion
