### ISSUE TITLE
Benchmark results on exercise page

### ISSUE THREAD

**Issue by shevchenkodenis** [exercism/exercism.io#3127]
There is a benchmark included in almost every Golang problem. 
is it possible to add it results to exercise page on exercism.io?
It would be super useful to sort by it and view the quickest solution.

**Comment by jtigger** [comment]
I see how being able to see a quality of the solutions (here, you're suggesting performance) to compare would be really cool.  I love the spirit of the idea in the ways that it enriches the conversation about the code.

Personally, while I think it would be interesting to be able to include metrics in a submission, I'm a little hesitant to promote it as a sortable value on its own.  Two reasons come to mind:

1. *it risks substituting numbers for the conversation.*  Exercism is about creating a space for programmers to learn and share about code.  When we include metrics, those are great launching points for a conversation.  But when we start organizing around metrics, it encourages what looks more like distanced comparisons.
-  *it introduces a facilitated competition/gamification feel.*  From the start, exercism has deliberately avoided gamification features.  When reward shift to extrinsic, it dramatically changes the dynamic.  There are plenty of places when programmers can go head-to-head.

Would you consider a feature where one could include a set of key/value pairs for descriptive purposes?  Those values could be displayed alongside the code (in a table or some such).

A workaround could be encouraging golangers to include a comment with their benchmark in the submitted solution.

**Comment by kytrinyx** [comment]
This is an interesting topic, and related ideas have come up before. If you want to explore: #2312, #2803, and #1710

One thing we might consider is to include the output of a command as part of the submission:

```
exercism submit file.go --output-of="go test -bench ."
```

**Comment by Insti** [comment]
> One thing we might consider is to include the output of a command as part of the submission:
> `exercism submit file.go --output-of="go test -bench ."`

This could already be done manually by submitting multiple files and would still be able to discussed in reviews.
```
go test -bench . > file.benchmarks
exercism submit file.go file.benchmarks
```
The Go track could include these instructions in their HINTS.md file so the convention could become known.

This doesn't solve the sorting by benchmark results part, but I suspect that is not compatible with the Exercism "avoid gamification at all costs" philosophy.

**Comment by kytrinyx** [comment]
I'm taking a pass through our issue tracker with the goal of making sure that every open issue we have on exercism/exercism.io is actionable. 

As this issue stands it isn't actionable. If you would like to move this topic forward, please open a new issue in http://github.com/exercism/discussions

Please:
- summarize the points so far in 
- link back to this issue
- include the intended goals for the discussion
