### ISSUE TITLE
See all contributions (submissions and comments) by a specific user in the Activity Stream

### ISSUE THREAD

**Issue by jtigger** [exercism/exercism.io#3128]
There are users on exercism from whom I want to learn more.  I know they have left insightful comments on others' submissions; I found some by manually searching.

I want to easily find users' contributions (**both submissions and comments**) so I can enjoy and participate in them.

**Straw man**

1. User's homepage: follow/unfollow.
- Activity Stream: like tracks and exercises, followed users
- When I click on a followed user, the Activity Stream limits to submissions by **or commented on** the user.

Related: #1899

**Comment by kytrinyx** [comment]
What I really, really want here is to put the user's own activity stream on their profile page. #2059

**Comment by kytrinyx** [comment]
The comments activity stream is something we haven't done yet and _totally should_ include on the user's own profile page.

**Comment by jtigger** [comment]
Yup... this is a dupe, in spirit.
