### ISSUE TITLE
Viewer filter in track stream paginates incorrectly

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3133]
We recently added a "my solutions" filter to the sidebar of the track activity stream (#3115). This makes it quick and easy to go see all of your own exercises, and quickly navigate to the ones where there has been new activity (comments) since you last looked at it.

In my own solutions for the Go track I should not have any pagination, since I have only submitted to exercises. I would expect someone who has submitted over 50 exercises in a single track (e.g. @ErikSchierboom or @NobbZ) to have 2 pages.

-------

<img width="1037" alt="screen shot 2016-10-02 at 1 50 51 am" src="https://cloud.githubusercontent.com/assets/276834/19019384/8913794a-8843-11e6-84ba-939d06edf34c.png">

/cc @ramyaravindranath

**Comment by NobbZ** [comment]
Thank you for pinging, perhaps we found another bug by this mention.

According to my profile page, elixir is the track with most submissions and has a count of 48.

Still I investigated a bit.

The number of pages on "my submissions" is equivalent to the number of pages on the unfiltered view of that language.

**Comment by kytrinyx** [comment]
> The number of pages on "my submissions" is equivalent to the number of pages on the unfiltered view of that language.

Thank you for confirming that, @NobbZ 

> perhaps we found another bug by this mention.

I didn't actually verify the counts last night, I just recalled that you had done a very large number of exercises. I ran a query just now and you're right, your track with the most exercises is Elixir at 48.

**Comment by kytrinyx** [comment]
@ErikSchierboom it looks like you have more than 50 exercises in each of F#, Haskell, and C#. We've verified the bug, but once we have a fix I'd appreciate it if you'd take a look and verify the fix.

**Comment by ErikSchierboom** [comment]
Sure, no problem. I've just returned from my holiday, which is why I hadn't replied yet.

**Comment by kytrinyx** [comment]
I didn't mean to rush you, @ErikSchierboom :)

**Comment by ErikSchierboom** [comment]
I can also confirm the bug: 

![image](https://cloud.githubusercontent.com/assets/135246/19031097/6c9b4120-8952-11e6-839c-57001fd5854e.png)

This is from the first page of the My Solutions page for my F# track, which I have 106 entries in:

![image](https://cloud.githubusercontent.com/assets/135246/19031112/86de6a26-8952-11e6-822b-5a787c328100.png)

**Comment by tejasbubane** [comment]
I don't see the bug on a fresh `db:reseed` on localhost

![screen shot 2016-10-05 at 12 26 49 am](https://cloud.githubusercontent.com/assets/980783/19088150/944b2ae6-8a92-11e6-8dd6-f87a010f7ac3.png)


Maybe some data in production?

**Comment by kytrinyx** [comment]
It's more likely that we're missing some crucial data in our seeds, I think.

**Comment by ErikSchierboom** [comment]
I can confirm that this problem is now solved! 🎉 

![image](https://cloud.githubusercontent.com/assets/135246/19450257/fc861f74-94a8-11e6-9bef-48b1cd0fe8e8.png)

**Comment by bernardoamc** [comment]
Awesome! 😁  Thanks for the feedback!
