### ISSUE TITLE
Make display of batches collapsable

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3137]
This is in tradition to #2735.

---

Some users have quite a large number of touched tracks.

My own list of batches has 8 rows and when I look at my own profile page, I do only see batches and I have to scroll down a complete "screenpage" before I have my actual list of "open" submissions.

Perhaps there are user which have even more entries (or smaller displays) and it might be hard for them to scroll to the right place in an instance. So I think it would add much to usability when we could simply collapse the progress-area.

Maybe we can even have a setting, if one wants to see the progress on profile pages collapsed or uncollapsed per default.

**Comment by kytrinyx** [comment]
@NobbZ would you mind posting a screenshot of what this looks like for you?

@GustavoCaso you worked on this feature; would you be interested in iterating on it?

**Comment by NobbZ** [comment]
Of course I can.

This is how it looks like on my laptop, the cut rectangle spans the height of the viewport:

![profile_view_badges_laptop](https://cloud.githubusercontent.com/assets/58951/19023535/c7880f44-88f0-11e6-84a4-92c217f21b83.png)

The one above is, when I have scrolled already a bit, but on the next one you can see, that my complete viewport is covered by the badges and some headlines when I open my profile:

![profile_view_badges_not_scrolled_laptop](https://cloud.githubusercontent.com/assets/58951/19023553/4f1a6e98-88f1-11e6-85ba-1bf3b6159f90.png)

**Comment by GustavoCaso** [comment]
@kytrinyx sure thing, I grab this one

**Comment by GustavoCaso** [comment]
@kytrinyx we can close this one

**Comment by bernardoamc** [comment]
Thank you @GustavoCaso ! Next time we can add a `Fixes #issue_number` in the PR so the issue closes automatically. :)

**Comment by kytrinyx** [comment]
Thanks! I'll be deploying tonight after work.

**Comment by GustavoCaso** [comment]
Thanks @bernardoamc I had no idea. Thanks @kytrinyx
