### ISSUE TITLE
Do not fail the build for decreases in coverage

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3139]
Coveralls has a tendency to fail the build on coverage decreases that are -0.008%. This is frustrating and unhelpful.

I'd like to change coveralls so that it _reports_ changes, without having it fail the build because of them. Or, perhaps only fail the build if the coverage decreases by more than 2% or something.

This would be "gameable", but since humans are involved I don't think that would be a problem.

**Comment by tejasbubane** [comment]
@kytrinyx This can be set from the coveralls settings page:

![screen shot 2016-10-03 at 2 31 57 pm](https://cloud.githubusercontent.com/assets/980783/19032526/e63d889c-8977-11e6-8368-fc92d974d484.png)

**Comment by kytrinyx** [comment]
:heart: :heart: :heart: @tejasbubane thank you so much for looking into that. It was going to end up at the bottom of a massive pile of TODOs.

**Comment by kytrinyx** [comment]
I've updated the settings. We'll see how that goes.

**Comment by Insti** [comment]
Was 2% the threshold you used?

**Comment by kytrinyx** [comment]
Yeah, I'm not feeling very strongly about what threshold we should use, I just don't want it failing for the micro changes that happen a lot of the time.

**Comment by ebraminio** [comment]
It failing on -0.01% https://github.com/harfbuzz/harfbuzz/pull/931 should be configure anything there?

**Comment by kytrinyx** [comment]
As far as I can tell, harfbuzz/harfbuzz is not related to this project. Nothing to do here.

**Comment by ebraminio** [comment]
Oh, very sorry... thank you very much
