### ISSUE TITLE
Group notifications by language track

### ISSUE THREAD

**Issue by troubalex** [exercism/exercism.io#3140]
Follow up from the [discussion here](https://github.com/exercism/discussions/issues/68):

Currently, notifications are all lumped together in a big list which is hard to scan. It would be nice to group them by language track. It's probably worth looking at the activity stream for inspiration.

**Comment by jmkoni** [comment]
Not sure if this is exactly what you are looking for, but I submitted a PR that groups the notifications:
https://github.com/exercism/exercism.io/pull/3207

**Comment by kytrinyx** [comment]
There's a bunch of great work in #3207 

For anyone who has the time to carry this, here's what I'd suggest:

- `git fetch origin refs/pull/3207/head && git checkout -b carry-3207 FETCH_HEAD`
- `git rebase master`
- make the changes (adding new commits on top of these)
- submit a new pull request, that way @jmkoni gets full credit in the commit history for the work that's already done.

**Comment by kytrinyx** [comment]
This was fixed by #3432
