### ISSUE TITLE
Fix bin/setup to compile CSS and JS

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3145]
Since we merged the pull request that lets us stop committing the compiled assets, the bin/setup (probably) needs to install npm and lineman, and run compass compile per the contributing guide: https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#frontend-development-setup

```
$ bundle exec compass compile -e production --force
$ npm install -g lineman
$ npm install
$ cd frontend && lineman build
```

I have not tested running setup from scratch.

**Comment by tejasbubane** [comment]
Also the docker setup (`Dockerfile` and maybe`docker-compose.yml`). I guess `Dockerfile` can use `bin/setup` itself.

**Comment by kytrinyx** [comment]
Good call, @tejasbubane. Yeah, it should probably also use `bin/setup`.

**Comment by mhelmetag** [comment]
Also, I checked out the [docker README](https://github.com/exercism/exercism.io/blob/0eb974ec68c5cc290370476a4a30370b75f870e3/docker/README.md) and saw that it should be setup with `bin/setup` so I think we're good!

**Comment by tejasbubane** [comment]
> I am going to try to speed up the docker process though because bundle install'ing on every build is realllly slow.

I use docker volumes to cache gem installs. Mount a local directory (eg. `vendor`) to the gem install path in container and it will be reused across containers.

**Comment by mhelmetag** [comment]
Actually looks like I was just doing something wrong. Docker seems to be using the cache no problem.
