### ISSUE TITLE
Request for comments: Typography improvements

### ISSUE THREAD

**Issue by troubalex** [exercism/exercism.io#3147]
This issue is the first result of a larger discussion which is going on [over here](https://github.com/exercism/discussions/issues/31).

I am currently working on the following tasks related to typesetting, with the main focus being on the front page, and other text heavy pages in the beginning of the user journey:
- [x] Find a good combination of typefaces
- [ ] Land a well-balanced typographic scale
- [ ] Introduce a clear visual hierarchy to all copy on those pages

For now, I am not planning any content changes. Those will be easier to see once the rhythm is right, especially of the front page.

**Comment by troubalex** [comment]
Here is a first round of combinations that I think all work reasonably well together. Since the goal is to see different combinations in action, I did not use any color, apart from the buttons. This is to make them stand out clearly as call to action.

[Please see this PDF (104 KB)](https://github.com/exercism/exercism.io/files/506807/font-combinations.pdf) for the best quality, the pngs are blurry.

All fonts are freely available from Google Fonts, and IIRC open source. Yay!

## Reasoning

I tried to find pairs that are readable, especially in body copy, easy to scan in headlines, and communicate the technical nature of exercism. The current headlines are very skinny, and don't sit well on the page, unfortunately, even though the thought behind choosing the typeface probably was the same.

## Variation A

**Big, fat display type for headings and CTAs.** This font is part of a whole family that gives us much to play with on the "marketing-pages" but will not work in-app. There we would use variations of the font used for body copy which is intentionally neutral.

![variation a](https://cloud.githubusercontent.com/assets/1913615/19047276/6edf132c-89a1-11e6-87eb-fb04d4a80303.png)

## Variation B

**Very readable, very safe version.** Feels very solid and reliable, but neither very technical nor particularly distinctive. Readability is excellent at all sizes.

![variation b](https://cloud.githubusercontent.com/assets/1913615/19047285/79a44eee-89a1-11e6-9927-fff570fd990f.png)

## Variation C

**Very factual look.** Clean and readable, with a dash of flair thanks to the serif used in the ingress paragraph. Will work well with almost any color or imagery, both on "marketing-pages" and in-app, but is again not very distinctive.
 
![variation c](https://cloud.githubusercontent.com/assets/1913615/19047296/80234c70-89a1-11e6-887f-5c77f296be7c.png)

## Variation D

**Good tech feeling.** Headlines and ingress are clean and neutral, while the body copy puts emphasis on written code. Readability is somewhat flaky, and dependent on line-length and font size. 

In-app, the monospaced body font will probably drown between the actual code snippets, and would therefore be replaced by the other one in the pair. Instead the monospace font would be used for the snippets themselves.

![variation d](https://cloud.githubusercontent.com/assets/1913615/19047303/862a8ce6-89a1-11e6-8999-6d8cd821e97a.png)

## Variation E

**Similar solution as variation D but with more weight on the page.** Readability is better in this combination, but the same solution for in-app use applies.

![variation e](https://cloud.githubusercontent.com/assets/1913615/19047306/8b45d1a4-89a1-11e6-98cd-35ea0b13e41e.png)

**Comment by kytrinyx** [comment]
My two favorites are A and C, with B a nice second.

I think D and E, while "tech-y" feel a little bit more choppy and are a bit harder to scan.

I think I lean more towards C than A, because the call to action gets a little bit hard to read on A.

**Comment by kytrinyx** [comment]
These are gorgeous, by the way. I forgot to say that I really, really like where this is going.

**Comment by troubalex** [comment]
> I think I lean more towards C than A, because the call to action gets a little bit hard to read on A.

The font on the CTA button can be the same in A as it is in C, or it can reuse the body font.

**Comment by catb0t** [comment]
I'll second @kytrinyx in saying they all look awesome, although personally I think the blocky font in A is too clumsy and inhibits readability. 

The monospace fonts in D and E are *cool* but IMO monospace is harder to process for 1) prose where 2) the text is darker than the background, so I like C most, with B second because C feels way more "modern".

**Comment by catb0t** [comment]
Also, here are the variations in order in higher resolution so people don't have to open a PDF:

![screenshot from 2016-10-03 18-23-29](https://cloud.githubusercontent.com/assets/3238748/19056329/84a4b7e4-8996-11e6-9636-49956fa29921.png)
![screenshot from 2016-10-03 18-23-24](https://cloud.githubusercontent.com/assets/3238748/19056331/84a78f50-8996-11e6-8a40-68ff05b45b21.png)
![screenshot from 2016-10-03 18-23-20](https://cloud.githubusercontent.com/assets/3238748/19056330/84a5eb50-8996-11e6-93a4-cfa0e6ecf972.png)
![screenshot from 2016-10-03 18-23-14](https://cloud.githubusercontent.com/assets/3238748/19056332/84a85fac-8996-11e6-836c-84b3410c9f22.png)
![screenshot from 2016-10-03 18-23-09](https://cloud.githubusercontent.com/assets/3238748/19056333/84b0a13a-8996-11e6-966c-0113bc92da79.png)

**Comment by kytrinyx** [comment]
I took another look after taking a walk and I like C even more now.

**Comment by troubalex** [comment]
Thx @catb0t 😸

**Comment by troubalex** [comment]
I made small adjustments after I did some more research today (I turned off image compression, the images should be less blurry now).

## Variation A

![variation a](https://cloud.githubusercontent.com/assets/1913615/19090217/b617a146-8a7d-11e6-8aa9-a8ae6e24562b.png)

## Variation D

![variation d](https://cloud.githubusercontent.com/assets/1913615/19090235/c81ff4c4-8a7d-11e6-8d02-a9c1157a54cc.png)

**Comment by bradhvr** [comment]
I like B the most, with C right behind it. I feel like they're the most readable and pleasing to the eye.

**Comment by Tetsuro** [comment]
**Huge** fan of B, it's like a massage for the eyes! Although I would use a sans-serif font for the button.

**Comment by troubalex** [comment]
Thanks for your comments so far, @kytrinyx, @catb0t, @bradhvr, @Tetsuro!

There seems to be a clear preference for the B or C variations, so I went ahead and iterated some more. Not making things too easy here.

## Variation B
This is without doubt a very readable and clean combination, but it's also pretty bland. So I tried to add some more character.
### B1 
(only minor tweaks)
![variation b 1](https://cloud.githubusercontent.com/assets/1913615/19198733/f434e66a-8cc0-11e6-9a0f-a8127a82b1da.png)
### B2
![variation b 2](https://cloud.githubusercontent.com/assets/1913615/19198730/f42cec94-8cc0-11e6-9b65-808fdeb7a8dc.png)
### B3
![variation b 3](https://cloud.githubusercontent.com/assets/1913615/19198735/f43769d0-8cc0-11e6-8347-87ac7b6f7454.png)
### B4
![variation b 4](https://cloud.githubusercontent.com/assets/1913615/19198731/f42db7fa-8cc0-11e6-9985-90fbb1cbb33a.png)

## Variation C
This one has more character but wasn't as easy on the eye. I tried to address that.
### C1
(only minor tweaks)
![variation c 1](https://cloud.githubusercontent.com/assets/1913615/19198732/f431023e-8cc0-11e6-80be-1423ab8c28f0.png)
### C2
![variation c 2](https://cloud.githubusercontent.com/assets/1913615/19198734/f4356838-8cc0-11e6-8391-a26a478eb8e9.png)
### C3
![variation c 3](https://cloud.githubusercontent.com/assets/1913615/19198736/f44b7f88-8cc0-11e6-8f1c-f00aceaf791b.png)

**Comment by kytrinyx** [comment]
I love the italic in B—very airy and easy to read. I think the B4 combination is gorgeous. In the C series my favorite is C3.

**Comment by troubalex** [comment]
Alright, so I'll move on with this now. Thanks for your comments so far! I'll take the favorites, and see how well they play on the page.

There is a chance though that once they are set in context, I may have to do another round of type tweaking, and might land on a different combination.

I'll keep you posted. ✌️😎

**Comment by troubalex** [comment]
I dropped the ball on this. Sorry.

Do you still want me (or someone else with more spare time) to pick it up, or do you think there is no real point because of the ongoing work related to https://github.com/exercism/discussions/issues/113 ?

**Comment by kytrinyx** [comment]
@troubalex I hate to say "no real point", but I think you're right. We should just table it and let exercism/discussions#113 be the place where UX and UI efforts are happening.

I'm going to go ahead and close this. :heart: Thank you

**Comment by troubalex** [comment]
Perfectly fair, and honest. I learnt stuff, and I hope others did as well. ❤️
