### ISSUE TITLE
Incorrect sections on upcoming and planned language pages

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3149]
Languages such as [PowerShell](http://exercism.io/languages/powershell) that don't yet have enough exercises to launch are listed under the **Upcoming** header on [/languages](http://exercism.io/languages). 

There are two issues:

* On the main page it displays the same text twice.
* On the other pages linked to from the sidebar it displays that same text (but only once) instead of linking to the content for that section.

The same happens for a planned language, e.g. [Pascal](http://exercism.io/languages/pascal)

The routes file for these pages is [app/routes/languages.rb](https://github.com/exercism/exercism.io/blob/master/app/routes/languages.rb).

- https://github.com/exercism/exercism.io/blob/master/app/routes/languages.rb#L24-L38
- https://github.com/exercism/exercism.io/blob/master/app/routes/languages.rb#L49-L64

These then call the template with ` erb :"languages/language"`: https://github.com/exercism/exercism.io/blob/master/app/views/languages/language.erb

**Comment by MohanL** [comment]
Let me have a try. Thank you

**Comment by mhelmetag** [comment]
@MohanL , here ya go.
This shows duplicate content on the root of the upcoming language (Pascal for example):
![duplicate_content](https://cloud.githubusercontent.com/assets/8609429/19425678/7a6d7870-93ea-11e6-8867-184942f4f7c9.png)

And this shows the incorrect content when trying to view the installing doc (also Pascal):
![incorrect_content](https://cloud.githubusercontent.com/assets/8609429/19425679/7a7f7566-93ea-11e6-9111-ad17be740f4a.png)

**Comment by MohanL** [comment]
@mhelmetag  Thank you!

**Comment by MohanL** [comment]
Working on it, 
- [ ] fix the duplicate content 
- [ ] fix the incorrect content 
  - [ ] logic
