### ISSUE TITLE
Like not showing on solution

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3151]
I got a notification that there was a new 'like' on one of my solutions:

![exercism - notification screenshot](https://cloud.githubusercontent.com/assets/5096681/19064736/72e6288e-8a0f-11e6-8f3f-db20471d6b04.png)

But when I visit the [Strain in Ruby link](http://exercism.io/submissions/f72e42aa0c244a33a2e9e738cf2bc349), there is no like visible:
![exercism - no like information screenshot](https://cloud.githubusercontent.com/assets/5096681/19064744/7a128dc8-8a0f-11e6-9baf-910744f6152d.png)

**Comment by Insti** [comment]
Likes are still visible on other solutions.
Was it a 'like' that was removed maybe?

**Comment by NobbZ** [comment]
There aren't any likes on that submission right now. Perhaps someone liked
and unliked. You got a notification on the like but it hasn't got deleted
on the unlike? There is/was a similar bug with deleted comments.

Geoff Hubbard <notifications@github.com> schrieb am Di., 4. Okt. 2016 09:14:

**Comment by kytrinyx** [comment]
I have confirmed this.

Reproduction steps:

1. Alice submits a solution.
2. Bob likes it.
3. Bob unlikes it.
3. Alice still has the notification.

**Comment by Insti** [comment]
> Alice clicks on the notification, and is taken to the exercise, and when she goes back to the notifications, the "like" notification is still showing.

I did not see this happen in my case. The notification disappeared as normal. I did have another 'normal' notification as well. I opened both in tabs before looking at the pages.

**Comment by kytrinyx** [comment]
> I opened both in tabs before looking at the pages.

You opened both of what?

**Comment by Insti** [comment]
>>     I opened both in tabs before looking at the pages.

> You opened both of what?

Both notifications shown in the first image of the OP.

**Comment by mhelmetag** [comment]
I got dis :D

**Comment by mhelmetag** [comment]
@Insti , I had that happen once or twice... I just had to be adamant about having a clean notification slate (check `Notifications.last` and stuff) and made sure to refresh while assuming/switching between users.
