### ISSUE TITLE
Create redirect from /inbox if you've not completed any exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3153]
`/inbox` is our shortcut to the Track Activity Stream (we realized this was an activity stream several months after we implemented the feature, so the naming is really confusing).

When you have submitted a solution to at least one exercise, then the stream starts getting filled with the solutions that other people have submitted to the same exercise.

If you _haven't_ submitted anything yet, then currently you get an error saying "that person doesn't exist". That's unhelpful and confusing!

What would be great is to have a new page, maybe `/streams/about` that explains what the stream is, and that you'll start seeing things there when you have submitted stuff.

So the TODO here is:
- [ ] create a new page with a little bit of content about the track streams
- [ ] redirect to this page from `app/routes/inbox.rb`

**Comment by MohanL** [comment]
I am working on it :)

**Comment by jtigger** [comment]
If someone is at the inbox page, and they haven't submitted, they've fallen off the on-ramp.

The on-ramp flow:

1. homepage
- [How it works](http://exercism.io/how-it-works/newbie)
- Sign-up via GitHub (assume creating a GitHub account)
  - When they verify their email address they land at GitHub's home page:
![image](https://cloud.githubusercontent.com/assets/470176/19935845/b82c5d3e-a0d8-11e6-8a76-5d7e7ae8b134.png)
  - Some might get lost here and start working on the [GitHub Hello World tutorial](https://guides.github.com/activities/hello-world/).
  - Others will return to Exercism, possibly by starting at step 1.
- Authorize Exercism
![image](https://cloud.githubusercontent.com/assets/470176/19935937/1e6f38dc-a0d9-11e6-9e64-435f68080c4d.png)
...

I can't find a link on the website to get to the Activity Stream / Inbox...  This means, someone would have to type that URL in the browser.

I believe the most helpful thing to do at this point is get them back to the on-ramp: a simple message that says something like,

> Before this becomes useful, you need to make your first submission, go here to do so: http://exercism.io/how-it-works/newbie"

**Comment by jtigger** [comment]
@MohanL the issue still stands: the current behavior is super confusing.  My observation is that this condition should be really rare; and in those rare cases, the most helpful thing we can do for that person is point them back to the instructions that get them to their first submission.

@kytrinyx does this match your understanding?

**Comment by MohanL** [comment]
@jtigger 

I agree with you that some people will get lost when register for a github account, but there is nothing we can do at that point. 

So the best we could do is to clarify the whole process and assume that people will get back to Exercism website. 

> I can't find a link on the website to get to the Activity Stream / Inbox... This means, someone would have to type that URL in the browser.
 
about this, this [PR](https://github.com/exercism/exercism.io/pull/3224
) takes cares of it

**Comment by jtigger** [comment]
Hmmm.... looks like that PR encourages this path (in fact, for most makes it possible).  When we zoom out and walk the path that the new user will go through, is this a direction we'd like them to go?

Or would we rather they find their way back to submitting?

I've suggested an alternative in #3220 as part of [this comment](https://github.com/exercism/exercism.io/issues/3220#issuecomment-258176998).

**Comment by MohanL** [comment]
@jtigger, no worries. I am open to all kinds of feedbacks 😀

**Comment by kytrinyx** [comment]
Yeah, I don't want to encourage this path, I just want to make sure that if you land on it, you're helped back to where you need to be.

**Comment by MohanL** [comment]
@kytrinyx  @jtigger 
I am really confused about the content of this redirect page.

**Comment by kytrinyx** [comment]
I'm thinking something that tells the user that this is an activity stream, and in order to start seeing activity, they first need to submit a solution to an exercise. Then it should link to the two "how it works" pages (if you're pretty new to programming, go to the one, if you're an experienced programmer go to the other).

**Comment by MohanL** [comment]
That sounds really cool. 
if I want to work on this path, do you think it would be better have a link lead them to a popular exercise/sample exercise to get started ?  
@kytrinyx @jtigger

**Comment by kotp** [comment]
I think it needs to be the instructions on how to get started... this is the pages that I think @kytrinyx is indicating.

**Comment by jtigger** [comment]
@kytrinyx said:

> I'm thinking something that tells the user that this is an activity stream, and in order to start seeing activity, they first need to submit a solution to an exercise. Then it should link to the two "how it works" pages (if you're pretty new to programming, go to the one, if you're an experienced programmer go to the other).

... and ...

@kotp reinforced:

> I think it needs to be the instructions on how to get started... this is the pages that I think @kytrinyx is indicating.

Beautiful.  👍

**Comment by kytrinyx** [comment]
@jtigger kind of a tangent... but what if we made all the hello worlds accessible to everyone whether or not you've solved it... read-only, maybe.

That would let people see how the site works a bit more than it currently does.

**Comment by kotp** [comment]
Read only might limit what they can use it for.  If they would want to comment and ask a question, this means they would be unable to?  Have it as usable as anything else, and if they have questions, they can "tinker" and see if they can answer it or they can set the help flag, etc.

**Comment by jtigger** [comment]
@kytrinyx asked:
>@jtigger kind of a tangent... but what if we made all the hello worlds accessible to everyone whether or not you've solved it... read-only, maybe.
>
> That would let people see how the site works a bit more than it currently does.

Here's the thing: I don't know what goal the would-be practitioner has in mind when she is in this situation.  Is she...

- trying to evaluate if Exercism is right for her and wanting some clear "this is the value you get" information?  Or...
- trying to get going and has just "gotten lost"?
- going for something else?

If it's the first situation, perhaps she'd be best served by some kind of (very short; < 2 min) video (screencast style) that would both give you an overview of the whole Exercism experience AND as a parting word, redirect you to the "getting started" flow.

If it's the second situation, getting back to the "Getting Started" flow would be most helpful.

And I'm not sure what else could be happening here.

...

What if we asked?

> Hey there!  Looks like you're poking around, can we help?
>  * [I'm trying to see if Exercism is right for me]() — revive the animation from previous versions of the homepage or create the screencast and display it here.
>  * [I'm trying to get setup]() — takes you back to the getting started page.
>  * [I don't know what to do next, I'd like to talk to someone]() — takes you to Gitter

We could then at least start seeing what's going on here.

**Comment by kytrinyx** [comment]
> trying to evaluate if Exercism is right for her and wanting some clear "this is the value you get" information?

@jtigger I think this is it.

I was watching a (very, very accomplished) programmer poke around exercism and it was extraordinarily painful. They wanted to get some overview of _what it is and does_. Right now we're missing something between the homepage and the "how it works". Maybe that video that you mention :)

**Comment by kotp** [comment]
My apologies, wrong issue to reference for the templates.

**Comment by jtigger** [comment]
@kytrinyx said:
> Maybe that video that you mention :)

@kopt and I are taking a first take at said video next Wednesday. :)

**Comment by kytrinyx** [comment]
> a first take at said video

wuuuut, that's awesome!
