### ISSUE TITLE
Sidebar shows incorrect counts in activity stream after marking all as read

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3154]
I recently implemented watermarks (https://github.com/exercism/exercism.io/pull/3146) on the track_id/problem slug combination, rather than adding a row to the views table for every single exercise. See #3130 for the full story.

Here's what I got after marking all as read in the Ruby track:

<img width="881" alt="screen shot 2016-10-04 at 7 35 27 pm" src="https://cloud.githubusercontent.com/assets/276834/19098885/5b91a564-8a6e-11e6-9422-989dcf2eebec.png">

The track itself doesn't show any "unread" items, but some of the problems listed in the sidebar do show unread items. Which makes no sense.

The unread count is computed in the same way in both cases:

https://github.com/exercism/exercism.io/blob/master/lib/exercism/track_stream_filters.rb#L15-L21

It counts

1. the views that have been made directly, and then
2. counts how many exercises are above the watermark which have not been viewed
3. finally it subtracts this number from the total

The actual queries are here, in the `ProblemFilter`.

https://github.com/exercism/exercism.io/blob/master/lib/exercism/track_stream_filters.rb#L157-L199

I'm clearly missing something, and I can't think what it is.

**Comment by kytrinyx** [comment]
@bernardoamc figured it out:

If you have viewed an exercise, and then you have a newer watermark, then it doesn't get counted. I'll fix this today.

**Comment by bernardoamc** [comment]
@kytrinyx Opened an PR with the fix, if something is missing/wrong we can close it.

**Comment by kytrinyx** [comment]
I can't believe I missed your PR. I'm getting on a plane, would you read through my comments on my PR and figure out if I'm thinking about this right? (This whole thing has had me a bit confused, I want to be very certain that we've gotten this fixed properly).

**Comment by bernardoamc** [comment]
No problem, I opened it just to be sure I wouldn't forget the situation.

**Comment by bernardoamc** [comment]
And have a nice flight! :)
