### ISSUE TITLE
No CLI binary available for the ARMv8 architecture

### ISSUE THREAD

**Issue by fuzzytern** [exercism/exercism.io#3157]
The [installation page](http://exercism.io/cli/linux) doesn't offer any option for the ARMv8 architecture.

Also, there is not any build for ARMv8 available on the [Github release page](https://github.com/exercism/cli/releases/tag/v2.3.0).

A new build or instructions to compile the CLI from source on this platform would be helpful.

Additional information:
Distribution: Arch Linux ARM
Architecture: aarch64
Note: also tried the AUR package, which doesn't build.

**Comment by catb0t** [comment]
The CLI is written in Go, and I don't think Go has cross-compilation targets to ARM-anything, which has always made me sad.

It might be possible to build cli.go into a dynamically linked library to be called from C, which can be built for ARM, but I think this merely shifts the problem, because it needs to be linked against the `.so` for the same arch.

Another option is a complete rewrite in C for platforms on which C is more available than Go (anything that isn't Intel x86, because Go is intended for servers.

**Comment by fuzzytern** [comment]
Thanks you cat.
But then how has it been made available for ARMv5 v6 and v7? Also is it
possible to somehow run the 32bits ARMv7 on my 64bit ARMv8?

**Comment by mhelmetag** [comment]
https://github.com/golang/go/wiki/GoArm

Seems like you could clone the repo and build it for `arm64`.

**Comment by kytrinyx** [comment]
> how has it been made available for ARMv5 v6 and v7

Go has cross-compilation targets for these.

In terms of building from source, if you clone the cli codebase to your ARMv8 machine try:

```
go install github.com/exercism/cli/exercism
```

**Comment by fuzzytern** [comment]
@kytrinyx After setting my Go path (to a new ~/.go folder), when I run

    go install github.com/exercism/cli/exercism

I get an error of type `error: import file 'aaa/bbb/ccc' not found`

If I then do

go get aaa/bbb/ccc

and run the `install` command again, I go one step further, but another dependency is missing so I still get an `import file 'ddd/eee/fff' not fount error'.

Is there an alternative to having to `go dep` manually all of the dependencies? I tried using the tool `godep` to no avail.

**Comment by Insti** [comment]
I'm not trying to chase you away :), but there there is a repository for the cli  https://github.com/exercism/cli which might be a better place for this technical discussion.

**Comment by mhelmetag** [comment]
@fuzzytern , can this be closed as a duplicate to the issue in exercism/cli?

**Comment by fuzzytern** [comment]
@mhelmetag Absolutely.
