### ISSUE TITLE
My Solutions page - Pagination

### ISSUE THREAD

**Issue by chynkm** [exercism/exercism.io#3160]
Pagination appears when record count is less. 
![selection_001](https://cloud.githubusercontent.com/assets/859879/19217833/458f9292-8e03-11e6-923f-1a59ed853ff8.png)

**Comment by tejasbubane** [comment]
Duplicate of #3133

**Comment by bernardoamc** [comment]
I'm going to close this in favor of #3133 as @tejasbubane pointed out, but thank you for the feedback @chynkm!
