### ISSUE TITLE
Add hacktoberfest labels

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism.io#3161]
[`Hacktoberfest`](https://hacktoberfest.digitalocean.com/) is happening this month. We should add the `hacktoberfest` labels so that they show up in the [search](https://github.com/search?l=&q=state%3Aopen+label%3Ahacktoberfest&ref=advsearch&type=Issues&utf8=%E2%9C%93). Maybe to all `good-first-patch` issues?

**Comment by Insti** [comment]
Go for it. (Are you able to add labels?) See also [Hacktoberfest discussion in /discussions](https://github.com/exercism/discussions/issues/76)

**Comment by tejasbubane** [comment]
No I am not able to add labels @Insti

**Comment by Insti** [comment]
I just added the Hacktoberfest label and added it to all good-first-patch issues.
I think we need to get @kytrinyx to give you the right permissions so you can assign labels in case you find more that need it added.

**Comment by kytrinyx** [comment]
I've created a team @exercism/triage and added you to it. I'm going to close this issue in favor of https://github.com/exercism/discussions/issues/76
