### ISSUE TITLE
Comments and code solution overlap when a user zooms on a submissions page

### ISSUE THREAD

**Issue by mrageh** [exercism/exercism.io#3163]
When the submissions page has enough comments that the comments section becomes scrollable, and a user starts to scroll down. If that user zooms in on the page after scrolling down the comments section then the users submission and the comments start to overlap.

Here is a [link](https://j.gifs.com/r0YZ3L.gif) to a gif that demonstrates the problem I've described above.

**Comment by troubalex** [comment]
Nice gif! 💯 

Potentially relevant for #2770.

**Comment by Motardo** [comment]
I wanted to try to reproduce this bug but I don't how you are zooming the window with the cursor like that in the gif. When I just zoom with CTRL-+ the comments jump below the code when they don't fit.

Tested with Firefox and Chrome on Ubuntu.
