### ISSUE TITLE
[Discussion] Investigate lineman alternatives

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism.io#3166]
[`Lineman`](http://linemanjs.com/) has been used in exercism since a while and we recently got it to work with the new [heroku buildpack](https://github.com/exercism/exercism.io/pull/2949). But there are still a lot of issues. 

People are also facing several issues with lineman #2936, #3120. This will make it harder for new people to contribute to exercism if they cannot get lineman to work. @kytrinyx has suggested at a few places that we should look for alternatives such that many people are familiar with it.

Also I hope we can clean up the `frontend` stuff along the way and manage it better. Mainly I see lot of dependencies are just lying there in [`frontend/vendor/js`](https://github.com/exercism/exercism.io/tree/master/frontend/vendor/js) directory without any version locking. 

Any views/opinions/suggestions regarding lineman and its alternatives?

**Comment by mhelmetag** [comment]
webpack could be a good alternative? It's also very well known.

I would love to clean up `frontend`. Either pull out angular (it's probably not really needed). Or embrace a framework (and probably switch to something more approachable like React).

I'm game to help out with those items (or however this all works out).

**Comment by troubalex** [comment]
> I would love to clean up frontend.

YASS! I'd be happy to help, the Sass part needs some TLC as well.

**Comment by kytrinyx** [comment]
I don't think we need Angular. We have very little in the way of javascript functionality.

**Comment by kytrinyx** [comment]
We're doing a redesign from the ground up: exercism/discussions#113

At this point I think that it probably wouldn't make sense to replace lineman in this app. When we reimplement we will not be using lineman. I'm going to go ahead and close this.

Whatever we do end up choosing for the redesign it will be something standard.
