### ISSUE TITLE
Using Exercism on Chromebook

### ISSUE THREAD

**Issue by lapaperboy** [exercism/exercism.io#3167]
Hello!

Is there a way to use exercism on chromebook? Trying to do a work around right now but not making much progress.

Kris

**Comment by mhelmetag** [comment]
I don't know of a way to do it directly but... indirectly, you can install [crouton](https://github.com/dnschneid/crouton) to get Linux on your chromebook. I used that back when I had the first chromebook and it worked pretty well (and I bet it's lightyears ahead of what it used to be now; it seems very well maintained).

Will Linux on your chromebook, you should have no problems at all.

**Comment by ryanplusplus** [comment]
Check out Cloud9 (https://c9.io/). It is an online IDE that uses an Ubuntu VM and you get a shell that allows you to install any packages that you want.

**Comment by mhelmetag** [comment]
Total +1 to Cloud9. That's a better option for sure. Way less setup and lots more time coding.

**Comment by kytrinyx** [comment]
There's a video that shows how to do it. It's a bit old, but I think the basic ideas still hold: https://www.youtube.com/watch?v=r0TnwOLxoks

That would definitely be the recommended way to do it on a chrome book!
