### ISSUE TITLE
Block a user from seeing my submissions

### ISSUE THREAD

**Issue by jtigger** [exercism/exercism.io#3180]
I've had less-than-stellar interactions with a given user (call him/her "User X").
I want to be able to block User X from seeing my submissions (and thus cannot comment on them) so that we both can continue to enjoy exercism... separately.

Given I've added User X to my "blocked users" list,
- when User X browses to my profile page, they get a 404
- when User X browses to any of my submissions, they get a 404
- when User X views the Activity Streams, my submissions are not included.

---

Features:
- [ ] In Account Settings, be able to maintain a "Blocked Users" list.  The UX should be identical to how Team members are managed.
- [ ] in Activity Stream, modify the query to exclude users who have blocked the current user.
- [ ] in the `submissions` route, verify that the current user is not on the submission user's blocked list; if so, return a 404 instead.
- [ ] in the profile route, verify that the current user is not on the target user's blocked list; if so, return a 404 instead.

**Comment by kotp** [comment]
I have had mostly "less than stellar" interactions on Exercism.  But only one "sexually suggestive" interaction of some twisted sense.  And only a few stellar interactions.

Would an "other than 404" page be more appropriate, a kind of "This user is not available for comments" type of communication?  I think 404 has an intended communication all of it's own.

**Comment by jtigger** [comment]
mmm... I used a subtle form of hyperbole.  Sorry about that.  I meant to imply, "I've had particularly uncomfortable / challenging / inappropriate interactions with a given user."

In addition to someone being outright rude or otherwise inappropriate, I might be motivated to block a user because they seem to be dominating the conversations.  I might find their feedback to be unhelpful.

**Comment by kytrinyx** [comment]
I fully support the idea of being able to explicitly avoid interactions with selected individuals.

This is a really complex topic, and I don't know much about it, and I worry that it's a feature that would be very easy to get wrong in a number of different ways.

Does anyone know of any resources that have to do with the ins and outs of this sort of feature?

**Comment by kotp** [comment]
The most apparent "thing" I have seen recently is the "Sin Box" that stack exchange puts in place.  Community drive, as SO is.  With moderator intervention, etc.  Yes, a very complex thing to "enforce through code" (anti-)social behavior restrictions.

What we don't currently have is a way to "+1" or "-1" interactions to help support something like this on a broad level.  And of course, at the moment, it is only our own personal choice to not interact, or to even remove the iteration through "Manage -> Delete" button, if there is something there that we feel is important enough to remove.

**Comment by kytrinyx** [comment]
GitHub released these guidelines last week https://help.github.com/articles/github-community-guidelines/, which I think are exactly what we're looking for. I'll read through them, and would love it if others also did so so we can discuss this at the higher-level "how do we avoid unpleasantness" rather than the "let's implement feature X".

**Comment by kytrinyx** [comment]
Hm. OK, community guidelines are not exactly what we're looking for, though they could be helpful.

**Comment by kytrinyx** [comment]
Another thing that we should consider is muting. Or even time-delayed muting, e.g. "mute for 24 hours".

**Comment by jtigger** [comment]
I absolutely agree, @kytrinyx: the best solution is a culture/mindset of mutual respect (and all the actions that stem from that).

That said, I see a number features that point to an evolution of bringing Exercism users together(!)... improving the discoverability of quality exchanges.  As we nudge people together, I think it's important that we also give them the tools to moderate their own experience.

The good news is that the whole onboarding process seems to self-select for those who just want to learn.  The complaints I received have been about overly eager or inadvertently curt comments.

The spirit of this feature request is based in the scenario where a given Exercism user has "had it" with another (for whatever reason) and wants to quietly disappear from the "offending" user's view.  Unlike mute, this avoids weird comment chains where someone appears to be talking to a wall.

I see this as a long-tail feature: used infrequently, but oooohhh so valuable when used.

**Comment by jtigger** [comment]
To your point about focusing more on people and interactions over process and tools, I think we can do a better job of injecting "skillful" mindset hints into the experience.  Imagine a "tip" box that shows up as you click in the comment box with a MotD (one sentence) that encourages helpful interactions:

"Make your feedback more digestible: start by pointing out something you really liked about this submission."

"Imagine this person is you when you first started in the language."

"With each challenge, include a piece of support."

"What if you framed your feedback as a question to encourage curiosity, rather than a correcting directive?"

"Consider leaving a praise-only comment on this one."

...

**Comment by kytrinyx** [comment]
I think this is a really important topic, but this issue is not directly actionable.

I'm taking a pass through our issue tracker with the goal of making sure that every open issue we have on exercism/exercism.io is actionable. 

As this issue stands it isn't actionable. If you would like to move this topic forward, please open a new issue in http://github.com/exercism/discussions

Please:
- summarize the points so far in 
- link back to this issue
- include the intended goals for the discussion

I should mention, we're also talking about anonymity and blocking as a core part of our redesign discussions.

**Comment by jtigger** [comment]
Delighted that we're talking through how to manage visibility in the redesign.  As we get better at encouraging conversation among Exercism users, there will be a greater need for managing those interactions.

@kytrinyx I'm a little confused with the assessment that this issue is not actionable.  It states an objective with intention, enumerates scenarios and suggests a feature set.  Is it too big in scope?  Is it too vague in wording?  Did the subsequent discussion leave those goals in doubt?

I share the goal of writing actionable issues, please critique (kid gloves off)! :)

**Comment by kytrinyx** [comment]
This is a feature request, by which I assume that everything in it is a recommendation for discussion. The action is "discuss" and "decide". There's nothing here that someone off the street could go in and implement, because we don't necessarily have an agreement on what to implement or how.

**Comment by kotp** [comment]
@jtigger If you would like, I can get this moved to discussion which will retain the discussion, and then we can edit it to bullet the points, and come back with an actionable set of steps.

**Comment by jtigger** [comment]
Thanks, @kotp, that would be fantastic!

**Comment by kotp** [comment]
Issue moved to [exercism/discussions #134](https://github.com/exercism/discussions/issues/134) via [**ZenHub**](https://www.zenhub.com/)
