### ISSUE TITLE
Make track todos scannable

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3192]
As a follow-up to https://github.com/exercism/exercism.io/pull/3191 I think it would be useful to turn the grid of problems to implement into a scannable list, much like we did with the [available exercises](http://exercism.io/languages/ruby/exercises).

Here's the "todos" grid:

<img width="655" alt="grid" src="https://cloud.githubusercontent.com/assets/276834/19613224/1f1fb6ca-97e3-11e6-85cf-876406b8026b.png">

There are several bits of information here:
- the name of the problem
- the blurb describing the problem
- the link to the generic problem description
- **if available** - the link to the canonical test data
- links to each of the existing implementations from other tracks

This means that the table or scannable list will need to be a bit more comprehensive than what we have in the "available exercises" list. I'm not sure what it should look like.

**Comment by snsavage** [comment]
@kytrinyx Is anyone working on this?  I'd be happy to give it a shot.

**Comment by snsavage** [comment]
Here is what I came up with.  Any thoughts?
![screen shot 2016-10-25 at 7 51 51 pm](https://cloud.githubusercontent.com/assets/6299224/19708453/9f957388-9aec-11e6-803e-5183548937a7.png)

**Comment by Insti** [comment]
Looks good, can you submit a Pull Request for this?

**Comment by tejasbubane** [comment]
I guess this can be closed via #3208
