### ISSUE TITLE
Getting a Sinatra error when running locally

### ISSUE THREAD

**Issue by nellshamrell** [exercism/exercism.io#3195]
I am currently seeing a Sinatra error when trying to run exercism.io locally in both Mac OS X 10.10.5 and Ubuntu 16.04.1 - in both cases using Firefox as my browser.

I start localhost using:
```
  $ bundle exec foreman s -p 4567
```

This is the error that I am seeing:

![screen shot 2016-10-22 at 10 48 09 am](https://cloud.githubusercontent.com/assets/813007/19621379/54b36810-9845-11e6-9135-16e6fd9a366d.png)

**Comment by MohanL** [comment]
@nellshamrell, I think the document at  [frontend compile instructions](https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#frontend-development-setup) would help

**Comment by aaron-suarez** [comment]
I don't think that's the problem MohanL. I tried your solution and it did not work.

If you look at the stacktrace, routes/core.rb assigns a variable called css_url to the value "/css/application.css?t=#{File.mtime('./public/css/application.css').to_i}" . Basically, it looks like it's trying to reference `public/css/application.css`which is a folder that does not exist.

Looking through the commit history, it looks like [commit 0118535c5ecfc2a2f1393219f346e411bb4511ba](https://github.com/exercism/exercism.io/commit/0118535c5ecfc2a2f1393219f346e411bb4511ba) deleted this file. 

How are we currently rendering the css if not from `public/css/application.css`?

**Comment by bernardoamc** [comment]
Hey @aaron-suarez , the problem is that you currently have not compiled your assets, when compiled they will generate those files. Please try to run `bundle exec compass watch` and these files should be generated. You could even run `bundle exec compass compile -e production --force` to generate the files for production use, but the first command should solve your problem. :)

**Comment by MohanL** [comment]
@aaron-suarez  sorry about this.

**Comment by aaron-suarez** [comment]
It's all good, @bernardoamc's solution worked for me. Thank you, guys! I was working with @nellshamrell on this earlier, I think this issue can be closed.

**Comment by bernardoamc** [comment]
Glad it worked @aaron-suarez ! 👍
