### ISSUE TITLE
Inviting a user to a team creates a user if they do not exist

### ISSUE THREAD

**Issue by c1505** [exercism/exercism.io#3197]
When you manage a team, you can put in any string of characters to invite.  If that user does not exist, they are created.  

This creates the problem of if you invite someone and make a typo, you have no indication that you made a typo.  If there is another reason why a user is created when you invite them, feel free to close this issue :)

**Comment by MohanL** [comment]
I have an idea, what about we have a dropdown list of registered users for people to have a look ?

**Comment by kytrinyx** [comment]
We want to be able to invite GitHub users who are not yet in the system. That way when they join Exercism the team invitation will be there for them.

**Comment by MohanL** [comment]
we could try to have a dropdown list showing the registered users on github when people type the usernames.

**Comment by kytrinyx** [comment]
@MohanL There are many, many millions of users on GitHub. I don't think that a dropdown would be usable.

**Comment by MohanL** [comment]
@kytrinyx  
Oh, I got it. :)
Is there anything we could do about this ? like telling the current user that if the invitee is registered in the system or not ?

**Comment by c1505** [comment]
We could check with the github api if that user exists or have some clarifying note about what inviting people actually does.  I'm also perfectly ok closing this issue without changes.

**Comment by aaron-suarez** [comment]
I think that some checking of whether it is a valid user (either Exercism user or GitHub user) would be a helpful addition. The app displays the strings that were typed in. If they're users, it looks great. If they're not, it basically creates a placeholder for a deadlink. I agree we should check if that github user exists and give some kind of simple "User not found" kind of error to the the user know they mistyped it.

**Comment by kytrinyx** [comment]
Thanks @c1505 @aaron-suarez - I think it would make sense to do some extra checking and reporting here:

1. For the invitations that were created for existing users, we can say "Exercism users a, b, and c, were invited".
2. For existing GitHub users who are not on Exercism we can explain what happens—they'll have an invite waiting for them the first time they log into Exercism.
3. For non-existent GitHub users, we should ask them to check the spelling or something like that.

Maybe. Thoughts?

**Comment by aaron-suarez** [comment]
That sounds like a great idea.

Are we going to do it as banners at the top with green/red, similar to how it's currently implemented? I don't think that will be too much code to add.

**Comment by kytrinyx** [comment]
I'd be fine with going with the banners (a.k.a. flashes). The other option would be to stick some data into redis or something and then show a separate page inside the team/management area where we have more breathing room.
