### ISSUE TITLE
Activity Stream is slow for some users and "mark as read" fails

### ISSUE THREAD

**Issue by jtigger** [exercism/exercism.io#3206]
Reported in the support chat (by @cds-amal):
1. Log in and go to the Activity Stream
   - **Expected:** the page would load quickly
   - **Actual:** the page takes a long time to load (although < 30 secs, so it actually loads!)
2. Submissions "mark[ed] as read" still come back as unread.

**Comment by bernardoamc** [comment]
Hmm, ok, my code for the profile page don't touch the `mark as read` feature, that's good. haha I'm trying to reproduce the mark as read bug, so far no luck, but will keep trying though. :)

**Comment by jtigger** [comment]
Yeah, @bernardoamc, I'm encouraging @cds-amal to detail his experience so that we can (at least) have a fighting chance of narrowing it down (somehow)...  Let's give it some time and see.

**Comment by bernardoamc** [comment]
Any updates on this? :)

**Comment by jtigger** [comment]
Didn't hear back from him.  Will bump.

**Comment by jtigger** [comment]
No response.  We'll close this for now.
