### ISSUE TITLE
Create Hacktoberfest Label at XPython

### ISSUE THREAD

**Issue by laurauzcategui** [exercism/exercism.io#3211]
Hi I am looking forward to contribute as part of Hacktoberfest in XPython repo but unfortunately the label is not created :disappointed:  

Will someone be able to create the label ? so I can tag my pull request and issues ? :smiley:

**Comment by snahor** [comment]
You don't need that label to participate.

**Comment by laurauzcategui** [comment]
Good then. Thanks.
