### ISSUE TITLE
Setting up boost for c++ 

### ISSUE THREAD

**Issue by LapisFox** [exercism/exercism.io#3212]
I'm having problems getting everything set up for the C++ track.  I'm attempting to do this on Windows 10 with Visual Studio 2015 and have tried some prebuilt boost installs and also building it myself.  No matter what I try, I'm still having issues when I run the cmake command: cmake -G "Visual Studio 14" ..    

I get the following error:

CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/FindBoost.cmake:1793 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.55.0

  Boost include path: C:/local/boost_1_55_0

  Could not find the following static Boost libraries:

```
      boost_unit_test_framework
      boost_date_time
      boost_regex
```

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package)

CMake Warning (dev) at CMakeLists.txt:17 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!

Thanks for any help anyone could provide!

**Comment by tejasbubane** [comment]
Hi @LapisFox would you mind opening an issue here -> https://github.com/exercism/xcpp ?
We have separate repositories for each language and people there might be able to help you better.

**Comment by tejasbubane** [comment]
@LapisFox I think issue https://github.com/exercism/xcpp/issues/96 might be related to your issue, especially this comment: https://github.com/exercism/xcpp/issues/96#issuecomment-236381909. If not, please feel free to open a new issue in that repository.
