### ISSUE TITLE
Activity stream is visible to a user who has not submitted anything

### ISSUE THREAD

**Issue by MohanL** [exercism/exercism.io#3221]
![image](https://cloud.githubusercontent.com/assets/10900547/19839633/ce42ccda-9ebb-11e6-8086-869bc8924d4b.png)

The problem is that the user madison has never submitted anything but he could view the activity stream page.

**Comment by MohanL** [comment]
Under investigation :)

**Comment by kytrinyx** [comment]
Did they archive it?
