### ISSUE TITLE
Activity Stream: Track mentor view state indicators

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3226]
When you are a track mentor, on the left hand side of your activity stream you can see all the exercises.

![exercism - track mentor view](https://cloud.githubusercontent.com/assets/5096681/19851422/1a56c5ac-9f5e-11e6-8317-c72334dc566a.png)

In the above image, I have solved `Isogram` but none of the others that are visible.
`Lib`, `Octal` and `Point Mutations` are deprecated (and I have not solved them)

It would be good if there were a visible indicator of 
a) Which exercises were deprecated.
b) Which exercises I have/have not  submitted solutions to.

Ideas:
Add an icon to the left of the name. :coffin: Lib, :heavy_multiplication_x: List Ops
Add text.
Change the background colour of the cells.

Issues: 
How to cope with combinations? Deprecated exercises I have/have not done?

Note: 
This is only an issue for track mentors, "ordinary" view does not need to (and probably should not) change as a result of these improvements.

**Comment by NobbZ** [comment]
Well at least the same problem does exist for team activity streams and was
already issued some time ago by me. But since Ian on a mobile I can't ref
right now.

Geoff Hubbard <notifications@github.com> schrieb am Mo., 31. Okt. 2016
11:47:

**Comment by Insti** [comment]
@NobbZ? Viewing and finding teams and general improvements to them: https://github.com/exercism/exercism.io/issues/2944

**Comment by NobbZ** [comment]
Yes, that's the one I meant.

Geoff Hubbard <notifications@github.com> schrieb am Mo., 31. Okt. 2016 um
12:01 Uhr:

**Comment by kytrinyx** [comment]
How about using the list of current exercises in Trackler in order to construct the menu, and then "gray out" or make inactive the ones that you don't have access to. If you click on an inactive one, you get a message that you have to submit the exercise in order to get access to it.

Then for any exercises that are not in the active list, we could show them separately with some indication that they're not currently part of the curriculum (they could be deprecated, but it could also be a typo. There are some weird submissions sometimes that end up showing up in this list).

**Comment by Insti** [comment]
Still relevant.

**Comment by clarammdantas** [comment]
Hi! :)
Can I work on this one?

**Comment by kytrinyx** [comment]
> Can I work on this one?

Absolutely! If you get stuck on anything, jump into the chat https://gitter.im/exercism/dev - there are often people hanging out there

**Comment by masonraus** [comment]
Is anyone still working on this? I'd like to give it a shot if it's open 😄

**Comment by kytrinyx** [comment]
@masonraus nobody is working on this, but we're in the middle of working on a complete redesign, so we're generally discouraging updates to the v1 site.

You can see v2 here: http://v2.exercism.io/
And provide feedback here: https://github.com/exercism/v2-feedback/blob/master/README.md

I'm going to go through and close the various open feature-related issues for v1.
