### ISSUE TITLE
Changed github names -- cannot log into exercism account

### ISSUE THREAD

**Issue by jessfrisch** [exercism/exercism.io#3227]
Hi--

I recently changed my github username from jessf to jessfrisch.  I can see my exercism user account at jessf, but I cannot log into it.  Can you merge jessf into jessfrisch?

Thanks,
jess

**Comment by jessfrisch** [comment]
Somehow I managed to log into the old account, so perhaps I didn't manage to merge them on Github as I thought.  This is probably still a relevant issue to exercism, as I see other people have struggled with it, but since I don't have an immediate problem anymore I'm going to close the issue.

**Comment by jtigger** [comment]
Glad you found a way out, @jessfrisch.  We'll pursue this through the linked issue.

Thanks for sharing.  AFAIK, we don't have much data on people wanting to merge Exercism accounts; it is helpful to have such examples captured.
