### ISSUE TITLE
As a meetup & Exercism team organizer, I need to be able to get to my Team's stream ASAP.

### ISSUE THREAD

**Issue by machikoyasuda** [exercism/exercism.io#3228]
![screenshot 2016-11-02 10 09 17](https://cloud.githubusercontent.com/assets/3673236/19939027/728d99a8-a0e4-11e6-8542-7a030ecc12a1.png)

As a meetup organizer / Exercism team organizer who cares a LOT about the humans she has onboarded onto Exercism, suggested Exercism to and taught them GitHub.com and Command Line so they can use Exercism,
I need to be able to get to my Team's Stream ASAP.

So I would like to add a URL to the nav somewhere.

It should be cute and beautiful. Maybe with an emoji. Or something with a different color, to show me that I am looking for my ⚡️Fullstack team @kpearson

**Comment by kytrinyx** [comment]
Yeah, that works for me. A drop down with all your teams, perhaps?

**Comment by machikoyasuda** [comment]
yes <3 <3 <3

**Comment by machikoyasuda** [comment]
We will work on this at our meetups <3 <3 <3
