### ISSUE TITLE
Installation instructions for windows

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3231]
In gitters exercism/support it came up very often that there were trouble installing choco and the cli.

Very often it was solved by the following steps:

1. Make sure the user is running a priviliged powershell
2. Make sure the user installs choco as explained at https://chocolatey.org/install (and pointing them at the [Get-ExecutionPolicy](https://go.microsoft.com/fwlink/?LinkID=135170) thing)
3. Restart the priviliged powershell
4. Do a simple `choco install exercism-io-cli` (or what the package was called)
5. Make sure `%ChocolateyInstall%\bin` is part of `%PATH%`.

Perhaps we should use this as installation instructions after having it written a bit better and tested if I really have not forgotten anything ;)

**Comment by kotp** [comment]
@jtigger is meaning to create the requisite issue(s) related to this.

**Comment by jtigger** [comment]
This is great.  Thanks for logging this, gentlemen!

**Comment by jtigger** [comment]
Note: there's prior art for installing Chocolatey here: http://exercism.io/languages/java/installing#windows

**Comment by jtigger** [comment]
If anyone has the gumption and access to a Windows machine (if you're on *nix; think VirtualBox); this is a particularly painful and frequent source of problems on Gitter; we could really use your help.  I can only imagine the number of people who just quit before coming to Gitter.

**Comment by bordeltabernacle** [comment]
I use windows at work, I'd be happy to have a look at this on Monday.

**Comment by ErikSchierboom** [comment]
I've just looked at this, and what I think there are several things we can improve:

1. Remove the `Using PowerShell` section. The `Using the Command Prompt` section does the exact same thing, but with some advantages over the Powershell instructions:
  - You can explicitly pass the execution policy as an argument `-ExecutionPolicy unrestricted`. This is usually one of the problems when following the Powershell instructions.
  - People are more familiar with the command prompt, and thus feel more comfortable. They probably have an easier time opening an administrator Command Prompt than an administrator Powershell prompt.

2. I think we should instruct people to open the command prompt in administrator mode. This would probably fix a lot of issues.

**Comment by spuder** [comment]
I would vote steering people to use powershell and not cmd, since

- powershell [is the default shell now](https://fossbytes.com/powershell-replaces-command-prompt-windows/)
- powershell can do everything the command prompt can do, and more.

**Comment by jtigger** [comment]
@bordeltabernacle, this is one of those big bang for your buck contributions — we get regular visitors to the support chat room where people have gotten lost trying to get going on Windows.

Thanks for stepping up!

**Comment by bordeltabernacle** [comment]
Ok, so I've drafted something here: https://github.com/bordeltabernacle/exercism.io/blob/update/windows-install/x/docs/md/cli/windows.md

It's Windows 7 based as that's what I have, I haven't used Windows 10 so I don't know if there's anything significantly different that would need to be changed, or if the images might need to be windows 10 based. 

I chose to go with the `cmd` instructions just because Powershell is a whole different beast, a language as well as a prompt and I didn't want to confuse the issue by referencing it. I felt `cmd` is just simpler, and sufficient for these purposes.

Please do say if it's not what you are after, and add any suggestions for changes etc.

**Comment by NobbZ** [comment]
I do not like to replicate `chocolatey`s installation instructions. When they change the flow, we need to update our instructions as soon as possible or we end up in a situation we had before. People coming into the support channel and asking for help because they are thinking they cant install exercism-cli, but the problem is already the chocolatey installation.

Just link https://chocolatey.org/install, then get specific about how to install exercism.

When someone comes into the chat and asks for help, because he does not understand the instructions on choco can be helped easily, but if he already had a mangled installation because our installation instructions diverged from reality, it will be hard to lead him back into a clean state before actually helping to install it correctly.

**Comment by ErikSchierboom** [comment]
@NobbZ's suggestion to lose the Chocolatey instructions make sense. It would put the burden of correct explaining how to install Chocolatey with those who know it best: the creators themselves. The rest looks very good to me! As mentioned earlier, I also support using `cmd` instead of PowerShell.

**Comment by bordeltabernacle** [comment]
Yes, I agree with @NobbZ and @ErikSchierboom 

I've updated the instructions, and opened a PR #3283 

While I have left the Chocolatey installation instructions to the Chocolatey website, I thought it might still be useful to include some info on opening an Admin Command Prompt, as this can often be the source of many problems. Maybe it's overkill/patronising?? Same for the Chocolatey installation instructions, I thought they might be useful for someone for whom Exercism is their first experience of the command line, but again maybe it's overkill/patronising?? 

Let me know what changes might be needed, or if it's just not what you're looking for. No worries. :smiley:

**Comment by ErikSchierboom** [comment]
Excellent work! LGTM

**Comment by kytrinyx** [comment]
I think the tone is great! It's really important to include these things which trip up a lot of people. We're not assuming you _don't_ know, we're just letting you know in case you don't have experience with it.

**Comment by bordeltabernacle** [comment]
> We're not assuming you don't know, we're just letting you know in case you don't have experience with it.

I like how you've phrased this.

I think this issue can be closed now. :smiley:
