### ISSUE TITLE
Deprecate the SETUP.md file in the language track repositories

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3240]
[configlet]: https://github.com/exercism/configlet
[trackler]: https://github.com/exercism/trackler
[blazon]: https://github.com/exercism/blazon
[exercism-repo]:  https://github.com/exercism/exercism.io

Right now each exercise README is compiled from:

* (in exercism/x-common) - `exercises/:slug/description.md` (the basic problem specification)
* (in exercism/x$TRACK_ID) - `SETUP.md` (a reminder about how to run the tests)
* (in exercism/x$TRACK_ID) - `exercises/:slug/HINTS.md` (any hints about the specific exercise)

`SETUP.md` is a terrible name, since it sounds like it should be a one-time thing about how to set the track up. If you're doing all the exercises in a track, this will get annoying.

Instead of `SETUP.md`, we're going to use `exercises/TRACK_HINTS.md`.

Since we have about 50 different repositories that need to be updated, we will need to leave the support for SETUP.md in place, while starting to support the `exercises/TRACK_HINTS.md` file as well.

Once we have support for it, each track can move / rename their `SETUP.md` file.

- [x] Make sure [configlet][] only looks at directories (not files) in the `exercises` directory to determine which exercises have been implemented.
- [x] Add support for `exercises/TRACK_HINTS.md` in [trackler][] (without deleting support for `SETUP.md`)
- [ ] Draft an issue that we can submit to every language track that explains the problem and what to do to fix it. It should contain a link to this issue so that we get a living list that shows us each related issue in either green (open) or red (closed).
- [ ] Submit the issue to all the tracks using [blazon][]
- [ ] When all of the related issues are closed, close this issue

**Comment by petertseng** [comment]
The Haskell track bravely volunteers itself to be the first track to test out exercises/TRACK_HINTS.md.

We left a dummy SETUP.md in place so that we can:

* verify that exercises/TRACK_HINTS.md is being served in preference of STACK.md
* not be completely hosed if it turns out that exercises/TRACK_HINTS.md is not being served.

**Comment by Insti** [comment]
https://github.com/exercism/trackler/pull/17 added support for TRACK_HINTS.md so it should be working now.

**Comment by petertseng** [comment]
Confirmed good. We are removing our backup SETUP.md. exercises/TRACK_HINTS.md is the way to go.

**Comment by petertseng** [comment]
Signing up a second track (Rust)
