### ISSUE TITLE
Grains test for Haskell strange behaviour

### ISSUE THREAD

**Issue by concernedsyndicate** [exercism/exercism.io#3241]
After C:\Users\LENOVO\Desktop\funcional-programming\Haskel-exercises\exercism\haskell\grains>stack test
I got:

grains-0.0.0: build (lib + test)
Preprocessing library grains-0.0.0...
Preprocessing test suite 'test' for grains-0.0.0...
[1 of 1] Compiling Main             ( test\Tests.hs, .stack-work\dist\b7fec021\build\test\test-tmp\Main.o )

C:\Users\LENOVO\Desktop\funcional-programming\Haskel-exercises\exercism\haskell\grains\test\Tests.hs:25:21: error:
    * Could not deduce (Integral (Integer -> Integer))
        arising from a use of `fromIntegral'
        (maybe you haven't applied a function to enough arguments?)
      from the context: (Show t, Num t, Eq t)
        bound by the inferred type of
                 totalTest :: (Show t, Num t, Eq t) =>
                              (String, t)
                              -> hspec-core-2.2.3:Test.Hspec.Core.Spec.Monad.SpecWith
                                   (hspec-core-2.2.3:Test.Hspec.Core.Example.Arg
                                      hspec-expectations-0.7.2:Test.Hspec.Expectations.Expectation)
        at test\Tests.hs:(23,5)-(25,58)
    * In the first argument of `shouldBe', namely `fromIntegral total'
      In the expression: fromIntegral total `shouldBe` expected
      In an equation for `assertion':
          assertion = fromIntegral total `shouldBe` expected
Progress: 1/2
--  While building package grains-0.0.0 using:
      C:\Users\LENOVO\AppData\Roaming\stack\setup-exe-cache\x86_64-windows\setup-Simple-Cabal-1.24.0.0-ghc-8.0.1.exe --builddir=.stack-work\dist\b7fec021 build lib:grains test:test --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1

I've checked WITH http://exercism.io/exercises/haskell/grains/test-suite and my test content is the same.

**Comment by rbasso** [comment]
Hi, @concernedsyndicate!

Thanks for opening this issue!

I'm one of the maintainers of the Haskell track and I found this issue accidentally.

The proper place for discussions about Haskell exercises is https://github.com/exercism/xhaskell , so I took the liberty of opening an issue there: https://github.com/exercism/xhaskell/issues/430.

You can close this one, @kytrinyx. :+1:

**Comment by bernardoamc** [comment]
Thanks @rbasso ! <3
