### ISSUE TITLE
Cannot fetch?

### ISSUE THREAD

**Issue by adsr13** [exercism/exercism.io#3245]
I keep getting over and over again the same issue. You will see in the screenshot how I fetch and it won't fetch, telling me:

cdb:ruby adsr13$ exercism fetch ruby hello-world

Not Submitted:     1 problem
ruby (Hello World) /Users/adsr13/exercism/ruby/hello-world

unchanged: 1, updated: 0, new: 0

cdb:ruby adsr13$ exercism restore

unchanged: 0, updated: 0, new: 0

![image](https://cloud.githubusercontent.com/assets/8008703/20240737/53cf3002-a8dd-11e6-8bb1-7ef3fcc03502.png)

**Comment by Insti** [comment]
You already have it. look in `/Users/adsr13/exercism/ruby/hello-world`

**Comment by adsr13** [comment]
follow the trail down the terminal commands, I don't have it. It started
with the hamming exercise, and the hamming exercise was not there. I had
hello-world. I uninstalled exercism then reinstalled it, went to fetch
hello-world and start from scratch and I'm stuck.

**Comment by Insti** [comment]
Can you also show the output of `pwd` and `ls -la`

& you might want to change your (secret) API key, since you've exposed it to the world.

**Comment by Insti** [comment]
Come by the Gitter chat room if you want more real-time support getting this resolved: https://gitter.im/exercism/support

**Comment by adsr13** [comment]
lmao, thanks bro, yeah that api dam I've done before w/o realizing it.
Thanks!

**Comment by adsr13** [comment]
well its working now, the Gods I guess. Thanks a bunch for the gitter
invite for sure!

**Comment by Insti** [comment]
Did you work out what the problem was?

**Comment by adsr13** [comment]
yes thank you
