### ISSUE TITLE
exercise in progress sort order

### ISSUE THREAD

**Issue by ldwoolley** [exercism/exercism.io#3246]
I have noticed on my dashboard in the exercise in progress block, that I always hit the "see all" link, to see the more recent exercise worked.  I would love to see the sort order changed so that you click the "see all" link only occasionally, because the recent work is at the top.  Am I alone on this? or do others with the exercises sorted from most recent on top to oldest on the bottom?

I know I can archive them to move them out, but I am still hoping for more feedback on some of the exercises.  The element ID is: "menu-current" on the Dashboard page.  This idea would also apply to the list order on profile page where all the current exercises are listed.

**Comment by kytrinyx** [comment]
@ldwoolley Yeah, I agree, this would be better.

The code starts in https://github.com/exercism/exercism.io/blob/master/app/routes/main.rb

The view is "dashboard", so app/views/dashboard.erb, and also uses the `ExercismWeb::Presenters::Dashboard` presenter.

**Comment by Insti** [comment]
https://github.com/exercism/exercism.io/blob/master/app/views/dashboard.erb#L9

**Comment by ldwoolley** [comment]
As far as I can tell, we should use the simplest method here to change the sort order in both the dashboard view and on the user.username view.  So: 
change [https://github.com/exercism/exercism.io/blob/master/app/views/dashboard.erb#L9](https://github.com/exercism/exercism.io/blob/master/app/views/dashboard.erb#L9) to:
`<% dashboard.current_exercises.reverse.limit(5).each do |exercise| %>`

And change [https://github.com/exercism/exercism.io/blob/master/app/views/user/_exercises_table.erb#L21](https://github.com/exercism/exercism.io/blob/master/app/views/user/_exercises_table.erb#L21) to:
`<th data-sorted="true" data-sorted-direction="ascending">Latest Iteration</th>`

I will pull these and make the changes if we agree?  This will certainly reduce the number of mouse clicks I use while I continue to learning with exercism.
