### ISSUE TITLE
Profile page lists language as not completed but CLI 

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism.io#3247]
On [my profile page](http://exercism.io/ErikSchierboom?all=true), the tracks I've completed are listed. However, there are two tracks that aren't listed, for which the CLI doesn't fetch any new exercises. In my case, the C# and Scala tracks are not in the completed tracks section, even though the CLI doesn't fetch any new exercises for those tracks:

<pre>
Eriks-MacBook-Pro:haskell erikschierboom$ exercism fetch haskell
unchanged: 0, updated: 0, new: 0

Eriks-MacBook-Pro:haskell erikschierboom$ exercism fetch scala
unchanged: 0, updated: 0, new: 0

Eriks-MacBook-Pro:haskell erikschierboom$ exercism fetch java
unchanged: 0, updated: 0, new: 0

Eriks-MacBook-Pro:haskell erikschierboom$ exercism fetch csharp
unchanged: 0, updated: 0, new: 0

Eriks-MacBook-Pro:haskell erikschierboom$ exercism fetch fsharp
unchanged: 0, updated: 0, new: 0

Eriks-MacBook-Pro:haskell erikschierboom$ exercism fetch kotlin
unchanged: 0, updated: 0, new: 0

Eriks-MacBook-Pro:haskell erikschierboom$ exercism fetch elm
unchanged: 0, updated: 0, new: 0
</pre>

![image](https://cloud.githubusercontent.com/assets/135246/20266922/7d2c8278-aa78-11e6-8607-6a14cb225999.png)

Either the website displays the wrong thing, or the CLI does.

**Comment by ErikSchierboom** [comment]
@kytrinyx Is it possible to somehow import the data I used in production when developing locally? That would make it easier to try and fix this.

**Comment by kytrinyx** [comment]
@ErikSchierboom we don't have a way to export a user's data for local development at the moment.

What happens if you say `exercism list scala`? Does it show exercises that you've not fetched?

**Comment by ErikSchierboom** [comment]
Well, Scala is not a really good example anymore, as they have just added the `dominoes` exercise, so I really haven't finished the track this time. However, the C# track is a better example:

<pre>
Eriks-MacBook-Pro:Programming erikschierboom$ exercism list csharp
hello-world
bob
leap
gigasecond
difference-of-squares
rna-transcription
sum-of-multiples
space-age
hamming
grains
pangram
raindrops
nucleotide-count
accumulate
bank-account
grade-school
etl
phone-number
strain
scrabble-score
proverb
robot-name
kindergarten-garden
protein-translation
perfect-numbers
clock
triangle
beer-song
sieve
queen-attack
binary-search
robot-simulator
isogram
secret-handshake
allergies
simple-linked-list
acronym
matrix
largest-series-product
house
saddle-points
pythagorean-triplet
series
twelve-days
anagram
word-count
prime-factors
meetup
all-your-base
pascals-triangle
simple-cipher
roman-numerals
flatten-array
binary-search-tree
minesweeper
atbash-cipher
food-chain
grep
sublist
scale-generator
bracket-push
parallel-letter-frequency
linked-list
crypto-square
custom-set
ocr-numbers
circular-buffer
luhn
run-length-encoding
tournament
word-search
bowling
transpose
nth-prime
pig-latin
rail-fence-cipher
change
palindrome-products
poker
diffie-hellman
dominoes
rectangles
wordy
zebra-puzzle
diamond
say
variable-length-quantity
sgf-parsing

In order to fetch a specific assignment, call the fetch command with a specific assignment.

exercism fetch csharp hello-world
</pre>

And the fetch output:

<pre>
Eriks-MacBook-Pro:Programming erikschierboom$ exercism fetch csharp

unchanged: 0, updated: 0, new: 0
</pre>

**Comment by ErikSchierboom** [comment]
I have managed to find the problem! It's the `hello-world` exercise. The problem is that I started the tracks before they added the `hello-world` exercise. The bug is that the CLI didn't fetch the `hello-world` exercise, even though I didn't submit it. Having manually fetched and then submitted the `hello-world` exercise, now displays the correct status.

I've opened an issue for the CLI: https://github.com/exercism/cli/issues/361

**Comment by kytrinyx** [comment]
Oooooh! OK, that makes a weird sort of sense. Thank you so much for figuring that out!

**Comment by ErikSchierboom** [comment]
I was quite happy to figure it out, those not-completed tracks really bugged me ;)

**Comment by kytrinyx** [comment]
@ErikSchierboom if you have thoughts on the "we should make people do hello-world" vs "no, just ignore it in the stats" discussion, would you weigh in on the above-linked issue?

**Comment by ErikSchierboom** [comment]
@kytrinyx Done!
