### ISSUE TITLE
Profile page lists language as completed due to submitted deprecated problem

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism.io#3248]
I was working on the Haskell track lately. At some point, my profile page listed the track as being completed, even though the CLI would fetch a new exercise. I believe this is due to the fact that I had previously submitted several exercises that were now deprecated. Therefore, I had completed some exercises that weren't active anymore but which appeared to be counted towards my progress.

**Comment by bernardoamc** [comment]
Wow, I'm pretty sure this problem was solved at some point. Going to take a look at it, thanks for reporting @ErikSchierboom! <3

**Comment by bernardoamc** [comment]
@kytrinyx Can you spot something wrong [here](https://github.com/exercism/exercism.io/blob/master/lib/exercism/user_finished_tracks.rb#L13)? If this is still happening my theory is that tracks being fetched via `X::Track.all` can have deprecated problems in their `problems` attribute.

The line `(user_finished_exercises & track.problems.map(&:slug)).size` should return the number of exercises that were completed by the user and that are present in the `track.problems`.

**Comment by GustavoCaso** [comment]
@bernardoamc could add some condition to not count the deprecated one, or remove from the api the ones that are deprecated. What do you think ?

**Comment by bernardoamc** [comment]
@GustavoCaso I'm not sure if the API has deprecated exercises though, but I don't see why this is happening if that is not the case. :/

**Comment by GustavoCaso** [comment]
@bernardoamc I helped in this feature, I will try have a look this weekend. So I'll keep you updated.

**Comment by kytrinyx** [comment]
Yesterday we switched from using the X::Track (which uses the x-api) and Trackler (which is a ruby gem), which may also play into this.

The API should not have deprecated exercises. @GustavoCaso if you don't figure it out this weekend would you please report back here so we can help dig into it?

**Comment by ErikSchierboom** [comment]
The problem was solved by the update @kytrinyx mentioned!
