### ISSUE TITLE
Error running `bin/setup` on macOS Sierra

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism.io#3249]
I just did a `git clone` of the repository and tried to follow the steps in the contributing document to get the website up and running. When executing the `bin/setup` file, the following error occured:

<pre>
fetching over the wire
rake aborted!
NameError: uninitialized constant Faraday
/Users/erikschierboom/Programming/exercism.io/lib/tasks/seed.rake:6:in `block (2 levels) in <top (required)>'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/bin/bundle:23:in `load'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/bin/bundle:23:in `<main>'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/bin/ruby_executable_hooks:15:in `eval'
/Users/erikschierboom/.rvm/gems/ruby-2.2.2@exercism/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:from_scratch => db:seeds:fetch
</pre>

Directly running the rake fetch using `bundle exec rake db:seeds:fetch` also fails with the same error. Any idea how to solve this?

**Comment by esparta** [comment]
I can replicate this issue, and sadly it seems to be my PR #3214 :(

**Comment by ErikSchierboom** [comment]
Thanks for the heads-up. Perhaps that means you'll also be able to fix it? ;)

**Comment by esparta** [comment]
Yes, I just did the local fix, and testing.

**Comment by mhelmetag** [comment]
Can't this be solved with `require 'faraday'` in the right db task? Or am I missing something? I ran into this as well but just thought something was wrong with my dev environment. I think I just had to run `bundle exec rake db:seed` or `db:from_scratch` to overcome this.

**Comment by ErikSchierboom** [comment]
@esparta @kytrinyx The [submitted fix](https://github.com/exercism/exercism.io/commit/b72cca5fa6df420e77c0c0767f18171c8dc89658) fixed this! Thanks for the quick response.

**Comment by esparta** [comment]
exercism.io was using the `Bundle.require` all the time, #3214 change it to use `Bundle.setup`, this work fine until this happen, @mhelmetag . Yes, `require 'faraday'` will also fix the issue, but there's a possibility other issues with other rake tasks, @mhelmetag.

The quick-fix on taking back Bundle.require will let us use a better approach on not use Bundle.* at all. I'm volunteering myself to do it, but currently I'm on my day-job time, so I will work on this at night.

**Comment by esparta** [comment]
I sent the PR #3254 to a better solving of this issue.
ping @mhelmetag
