### ISSUE TITLE
Extract "How to Setup a Local Development Environment" from CONTRIBUTING.md

### ISSUE THREAD

**Issue by jtigger** [exercism/exercism.io#3251]
*(part of a larger effort to overhaul documentation around contributing: exercism/discussions#73)*

[CONTRIBUTING.md#setup](https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#setup) describes how to setup a local development environment.

In order to support making it easier to reference this block of instructions and to make it easier for them to follow:

- [x] extract this section into a separate file: `docs/setting-up-local-development.md` (please use that name, other work (e.g. #3194) is aiming to reference it).
- [x] optimize the main flow through the documentation for first-time contributors.
  *There are some sections that describe "advanced" topics or "special case" topics; these should be yanked down in the page to avoid confusion.*
- [x] reword/rework any hard-to-follow parts.  Some sections are a little awkward or redundant.

**Comment by ErikSchierboom** [comment]
As I was working on getting a local development environment setup yesterday, I'll be happy to proof-read this new document.

**Comment by MatMoore** [comment]
Hi, I'm working on this. 👋

**Comment by MatMoore** [comment]
I've made an attempt at the first two tasks in https://github.com/exercism/exercism.io/issues/3293

What do you think, @ErikSchierboom @jtigger ?

**Comment by ErikSchierboom** [comment]
@MatMoore Looks very promising! I've added some comments to your PR, mostly some styling and I'd like to also include instructions for the Windows platform.

**Comment by jtigger** [comment]
Hey @MatMoore, I've been out sick and just getting back into the swing of things.  So delighted that you picked this up!

Thank you for doing this work.  Every bit the we smooth out the road for contributors means it's that much easier for all those people who come behind you to get going.  Also, there are a number of paths through which people will arrive at the need to setup a local install; by pulling it out, you've made that easier to find/reference. 🙏

**Comment by MatMoore** [comment]
@jtigger Thanks - I think it's really great that this project is so welcoming to new contributors. I'm glad I could help! 😃

**Comment by mathvesilva** [comment]
@jtigger Is there anything else that we can help? This issue is still open, but i think the work was done.

**Comment by arumoy-shome** [comment]
I think we can close this since @MatMoore has already 🚀 the [extraction](https://github.com/exercism/exercism.io/pull/3293)?

**Comment by jtigger** [comment]
@mathvesilva: @arumoy-shome is right, we can close this particular issue.

However, there's a raft of documentation-oriented work over in the new doc repo: https://github.com/exercism/docs/issues

If you're still game to contribute in that way, we'd love it!
