### ISSUE TITLE
More complete starter implementations?

### ISSUE THREAD

**Issue by rstockbridge** [exercism/exercism.io#3255]
I am new to Java but have prior programming experience. The problems I have completed so far on the Java track either have either come with a nearly blank starter implementation, or no starter implementation at all.

For my code to be compilable (and therefore testable), I have had to reverse engineer all the tests at once to deduce method signatures and 3rd party dependencies, even if most tests are ignored to begin with. It was quite challenging to infer some of the return values given that I am a beginner in Java.

It would be really helpful if the starter implementations contain sufficient information to be compilable, i.e. they contain required methods with appropriate signatures and dummy return values, and import statements. This way the focus can be on writing code that passes one test at a time.

**Comment by tejasbubane** [comment]
Linking the issue in `xjava` for reference: https://github.com/exercism/xjava/issues/178
