### ISSUE TITLE
Minify app.js

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism.io#3261]
We have two files which are generated after compiling multiple js/css files: [app.js](http://exercism.io/js/app.js) and [application.css](http://exercism.io/css/application.css).

Out of these two, `application.css` is minified correctly by [compass](http://compass-style.org/) but `app.js` is not. Ideally [lineman](http://linemanjs.com/) should minify generated js files. We might be missing some configuration in lineman.

**Comment by kytrinyx** [comment]
@tejasbubane thanks for catching that. I'm pretty sure I had no idea what I was doing when I originally set this up, so we probably do have some missing configuration.

**Comment by tejasbubane** [comment]
> I'm pretty sure I had no idea what I was doing when I originally set this up

Even I don't have much idea about lineman, never used it anywhere else. Just playing with stuff and making it work 😄 

Since this is not a major issue, I will get to this when I find some time. Meanwhile if someone else wants to have a go at it, they can.
