### ISSUE TITLE
App should give useful error message if app.js is not generated.

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3262]
When developing Exercism if you do not generate the `app.js` file the js on the site will not work, but with no indication of why.

That `app.js` is missing and needs to be generated should be made obvious to the developer.

**Comment by Insti** [comment]
See also: https://github.com/exercism/exercism.io/pull/3260 which deals with the css not being generated.

**Comment by tejasbubane** [comment]
The code for `js` will more or less be the same as that for `css`. I think we can modify `CssUrl` to maybe `AssetUrl` and add code in there which reuses stuff like error messages.

**Comment by Insti** [comment]
This is still a relevant issue.
I also had the experience recently where the app.js was out of date and the site would not render.

**Comment by iHiD** [comment]
Hi. As we're launching the new Exercism site, I'm closing this issue. If the issue persists on the new site, please reopen it. Thank you! :)
