### ISSUE TITLE
CSS: Exercise description indentation.

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3263]
On the list of exercises: http://exercism.io/languages/ruby/exercises

For any exercise with a description that is more than 2 lines long, the later lines are indented less than the first two. This is visible in 'Accumulate' and 'Strain' in the image below:

![exercism - alignment issue](https://cloud.githubusercontent.com/assets/5096681/20560735/342b9d3e-b17b-11e6-9508-d62223f51bf0.png)

(I'm assuming this is an error and not a design choice.)

**Comment by omerbn** [comment]
I'll take it

**Comment by kytrinyx** [comment]
Fixed in #3264

**Comment by Insti** [comment]
Super! thanks @omerbn
