### ISSUE TITLE
Unimplemented exercises page is broken

### ISSUE THREAD

**Issue by ferhatelmas** [exercism/exercism.io#3266]
`http://exercism.io/languages/track/todo` gives `Sorry! That's our fault!`

I'm not sure if it's a known issue but as far as I see, I couldn't find a ticket mentioning it.

**Comment by Insti** [comment]
An example link that actually exhibits the problem: http://exercism.io/languages/ruby/todo

**Comment by Insti** [comment]
This is due to the recent [change to use Trackler rather than the x-api.](https://github.com/exercism/exercism.io/pull/3164)
`Trackler::Track` appears to be missing an `unimplemented_problems` method.

**Comment by Insti** [comment]
I'm working on fixing Trackler.

**Comment by Insti** [comment]
I've done what I can for now, @kytrinyx now needs to:

- [ ] Merge https://github.com/exercism/trackler/issues/8
- [ ] Update the Trackler gem
- [ ] Update the Trackler gem version used by exercism.io
- [ ] Deploy everything to the live server.

**Comment by tejasbubane** [comment]
A bunch of pages are failing:

* http://exercism.io/languages/ruby/installing
* http://exercism.io/languages/ruby/tests
* http://exercism.io/languages/ruby/learning
* http://exercism.io/languages/ruby/resources
and 
* http://exercism.io/languages/ruby/todo

Need more tests here: https://github.com/exercism/exercism.io/blob/master/test/app/languages_test.rb

**Comment by kytrinyx** [comment]
Sorry this is my bad. I had a branch that reworked all the language track stuff, but I think I got confused with a couple of other PRs that were touching the same bit of code, and never submitted it. I'll go rework that now.

**Comment by tejasbubane** [comment]
@kytrinyx See discussion in #3267. @Insti has done some work in `Trackler`.

**Comment by kytrinyx** [comment]
Thanks @tejasbubane I saw that. I don't want to make all of those changes to Trackler, so I've merged in the bits that I want selectively.
