### ISSUE TITLE
Cannot submit test file 

### ISSUE THREAD

**Issue by thebasharjobs** [exercism/exercism.io#3269]
I can submit the test file for hello world in the swift language, but not much else thereafter. 

The message I continue to get is "You're trying to submit a test file. If this is really what you want, please pass the --test flag to exercism submit."

I'm currently on the difference of squares test (I skipped two tests and can't verify they're working).

**Comment by kytrinyx** [comment]
Hey @thebasharjobs, did you try jumping into the Gitter chat? https://gitter.im/exercism/support There are often people who hang out there and can help you figure out what's going on.

Failing that, I'd submit a question over in https://github.com/exercism/xswift/issues, which will catch the attention of the folks around here who know the swift track intimately.

**Comment by thebasharjobs** [comment]
Thanks for the response. I'll try em out.

**Comment by kotp** [comment]
@thebasharjobs Please let us know.  I haven't seen you in the gitter rooms, and not on swift yet.  Just don't want to lose track of your progress on this.

**Comment by thebasharjobs** [comment]
@kotp Just submitted. Thanks for the follow up. Gets a little tricky to maintain any degree of focus over the holiday.

**Comment by kotp** [comment]
You are welcome,  I also see that you figured it out.  Can you detail what it is that was wrong?  Is it a problem with the documentation?  Something we missed?

**Comment by thebasharjobs** [comment]
I'm fairly new (completely unwashed, for that matter) to the realm of programming and didn't immediately understand the test file (and it's instructions) contained within the fetch was to be contained separately from the solution.swift file in the directory and used for submission.

It probably would have been more apparent for someone with a little more experience, but again, I'm a total beginner. 

I appreciate your help, however, and really enjoy the site.

**Comment by kotp** [comment]
Welcome to the world of Yak Shaving!

**Comment by Insti** [comment]
> didn't immediately understand the test file (and it's instructions) contained within the fetch was to be contained separately from the solution.swift file in the directory and used for submission.

This is the sort of thing that more experienced programmers forget that people do not know, and it would be useful to include it in our 'getting started' documentation.

**Comment by kotp** [comment]
I just checked, it is indeed true that the Swift hello test file is not as "introductory" as Ruby one, and it has a solution file there, as well, so two pretty large differences in onboarding.

**Comment by kytrinyx** [comment]
If any of you have any specific recommendations for the Swift hello world in particular, would you open an issue on the swift track with some suggestions and reasoning for why it would be a good idea?

Also, it might be worth discussing in general what makes a good hello world / first exercise, and what we can do to ensure the best possible onboarding experience regardless of which track you're on.

**Comment by kotp** [comment]
I was mistaken, the hello-world is in line with the Ruby track.  So am considering what can be done to improve the instruction of how to submit the file(s).
