### ISSUE TITLE
Incorrect instruction on ruby 'about' page

### ISSUE THREAD

**Issue by Skilly** [exercism/exercism.io#3270]
The [ruby about](http://exercism.io/languages/ruby/about) page contains the instruction `exercism ruby  hello-world` for obtaining the first problem, which is incorrect. 

It should be `exercism fetch ruby`.

**Comment by Insti** [comment]
Well spotted, & thanks for reporting it.

**Comment by Insti** [comment]
This affects **all** language tracks.

Fix here: https://github.com/exercism/exercism.io/pull/3271
