### ISSUE TITLE
Teams: Create new team button on /teams

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3274]
http://exercism.io/teams

There should be a button here to create a new team.

This came up in the Gitter chat when someone could not work out how to create a new team so I asked where they expected it to be.

(Edit: for more context.)

**Comment by kytrinyx** [comment]
I think the teams stuff is still in progress, but I'm not sure if we have a high-level tracking issue for it.

/cc @bernardoamc who has done a ton of work on improving teams over the past few months.

**Comment by bernardoamc** [comment]
I've missed this discussion somehow! I totally agree that we need a button to create a new `team`. We are currently lacking design for the `teams` page and I would love some ideas/feedback like this.

@Insti @kytrinyx Ideas for where the button should be displayed?

**Comment by kytrinyx** [comment]
@bernardoamc beats me! How about the upper right-hand corner?

**Comment by Insti** [comment]
Anywhere is better than nowhere, we can always move it.

**Comment by bernardoamc** [comment]
Closing this one. :)
