### ISSUE TITLE
Teams: Search view member count wrong.

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3275]
When searching for teams: http://exercism.io/teams

A team that has 1 member will show up as having 2 members.

(I've not yet checked to see if all teams are showing +1 members)

Steps to reproduce: 

Create a team with 1 member.
Search for that team.
See that the search results show the team has 2 members.

**Comment by bernardoamc** [comment]
Thanks @Insti , will investigate when I get home! <3
