### ISSUE TITLE
Copy and Expand buttons missing in submissions with multiple files.

### ISSUE THREAD

**Issue by rbasso** [exercism/exercism.io#3276]
When visualizing an iteration in the exercism website, only the top file (alphabetically first) has a button to copy or expand the visualization area.

This, of course, only affects submissions with two or more files.

Example: http://exercism.io/submissions/804ab8d2b3184afe97725136528714f1

**Comment by kytrinyx** [comment]
We implemented the expand long before we added support for multiple files, so it kind of makes sense that we'd see this bug. Thanks for reporting it!

**Comment by tejasbubane** [comment]
I feel expand makes sense for all the files since it changes the entire layout of the page, putting the nitpicks sections below the files. It would be difficult to expand one file only. 
Copy should be per file. Thanks for reporting it 👍

**Comment by Insti** [comment]
# Good first patch:

## Knowledge required: 
html, css, basic javascript

## Start here:
`app/views/submissions/current_submission.erb`

## Need help?
Just ask here, or come by the [Dev chatroom](https://gitter.im/exercism/dev) 
We're here to help.

**Comment by Motardo** [comment]
I took a swing at this one. I duplicated the copy and expand buttons once for each file. All the expand/shrink buttons affect all the files together. 
![expanded](https://cloud.githubusercontent.com/assets/2099793/20788135/6b97a9cc-b77d-11e6-81cf-094482e66eb8.png)
![collapsed](https://cloud.githubusercontent.com/assets/2099793/20788144/748138aa-b77d-11e6-8c3d-3b90ea28dd03.png)

**Comment by Insti** [comment]
Awesome.

Some thoughts: 
* There probably should only be one expand/shrink button.
* Does the copy  button only copy the code in the box it is next to?

Thanks for including the screenshots :heart:

**Comment by tejasbubane** [comment]
@Motardo This looks great! Just one suggestion from my side: (I know this is not a final design, but thought I should post it so it doesn't get missed later)

![web image 2016-12-01 16-26-50](https://cloud.githubusercontent.com/assets/980783/20791508/5c030cd4-b7e3-11e6-8230-73f209cf8b24.png)

**Comment by Motardo** [comment]
@tejasbubane I think you're right. Moving the buttons down against the text area would look nicer.

@Insti 
The copy button only copies the code it is next to, which I think is the desired behavior?   

**Single vs. multiple expand buttons:** imagine a submission where the first two files have short lines and the third file has long lines that are cut off. It's more convenient to click expand right there on the third file without having to scroll up to the top to click the single expand button. On the other hand, having several buttons that do the exact same thing could be confusing.

**Comment by Insti** [comment]
> The copy button only copies the code it is next to, which I think is the desired behavior?

Yes, I think so. Great.

**Comment by Motardo** [comment]
Here are a couple of screenshots. One with the buttons outside the code area
![outside](https://cloud.githubusercontent.com/assets/2099793/20805628/774934e6-b7c5-11e6-85fa-a229cc363bba.png)  

And one with the buttons inside.
![shrink](https://cloud.githubusercontent.com/assets/2099793/20805640/816c8afe-b7c5-11e6-84f8-81de289d5ae5.png)

**Comment by Insti** [comment]
outside :+1:

**Comment by Insti** [comment]
I like how you've moved the box closer.

I think we shouldn't worry about multiple expand buttons for now.
Put this version in place and see how it goes in practice.
If it bugs anyone too much we can create another issue to do something about it.

**Comment by tejasbubane** [comment]
Looks like this is deployed and works great! Thanks @Motardo :+1: 
Closed via #3287

**Comment by rbasso** [comment]
Perfect! Thanks, @Motardo!

**Comment by Insti** [comment]
Thanks @Motardo :heart:
