### ISSUE TITLE
Ignore hello-world when considering completion status for a track

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3278]
If you start on a language track before someone implements a `hello-world` exercise for the track, then the CLI will never fetch `hello-world`. This makes sense, as you don't really need hello world if you've already solved other things.

This means that when you get to the end of the track, the CLI will not download any new exercises, but the profile page will list that track as incomplete.

We should not include `hello-world` when considering whether or not a track is complete. If you've done everything except hello-world, you're done.

/cc @ErikSchierboom who figured this all out.

See https://github.com/exercism/cli/issues/361 and https://github.com/exercism/exercism.io/issues/3247 for the full history.

**Comment by Insti** [comment]
I don't like this exception.
If you've already done every other exercise hello world should be trivial for you anyway.

**Comment by kytrinyx** [comment]
It seems perfectly useless to deliver a hello world to you if you've done anything else on the track already.

I don't think we should make someone jump through a hoop, just so that we can give them "completed" status.

**Comment by NobbZ** [comment]
Some time ago, we agreed upon not to special case hello world. Also I want
to remind you that hello world is a very hard task in some languages and
also I do want to remind you that in exercism/x-common#290 we talked about
creating a completely new style of introduction, replacing hello-world
exactly because it is not as easy across all languages as initially thought.

Just deliver hello-world if it was added to the track, as you would deliver
any other exercise.

Katrina Owen <notifications@github.com> schrieb am Mo., 28. Nov. 2016 um
23:17 Uhr:

**Comment by kytrinyx** [comment]
> Some time ago, we agreed upon not to special case hello world.

Yes, in the context of the activity stream on the website, we agreed to not treat it differently.

> hello world is a very hard task in some languages

Yes, and that is a completely different problem/question. This behavior assumes that hello world is completely trivial, as that was it's original intent.

Given that the purpose of the exercise is to help people make sure that they've got everything wired together and configured correctly, once we know that this has happened (i.e. they've submitted a solution), then we should not bother them with that exercise.

**Comment by ErikSchierboom** [comment]
To be honest, I could live with both solutions. Doing the `hello-world` exercise when you have already done lots of more difficult exercise, feels a bit odd, but then again, it only takes a couple of minutes to finish it. The main benefit of this approach is that you don't need to hard-code an exception. Furthermore, the `hello-world` exercise, while fairly simple, is not trivial. So from that viewpoint it's not that odd to have to solve it later. 

All in all, I think I would just modify the CLI to also serve the `hello-world` exercise, but that's just my take on it, other people might be more bugged with having to do the `hello-world` exercise later.

>> hello world is a very hard task in some languages

> Yes, and that is a completely different problem/question. This behavior assumes that hello world is completely trivial, as that was it's original intent.

It's a very good question, as I think `leap` is a much better candidate for a first exercise. But that's another issue altogether.

**Comment by kytrinyx** [comment]
OK, thanks everyone for weighing in. It sounds like the consensus is to remove all the special-casing for hello-world, which lives in x-api, here: https://github.com/exercism/x-api/blob/master/api/v1/routes/exercises.rb#L44

I'll open a new issue in x-api and close this one.
