### ISSUE TITLE
Clearer UX excercise page

### ISSUE THREAD

**Issue by celiagomezdev** [exercism/exercism.io#3282]
Hi,

Yesterday I was asking for some help in the gitter chat about general workflow in exercism. At some point I was explained there is a super useful option called "Request for help", but I never saw it, then I knew it was in the manage menu, that first looked to me like a social media menu as it was close to the twitter icon. 

I created this possible new view. I made it quickly and in the most simple way, to don't need to do too many changes, but be able to see more clear all the options. I attach a picture: 

![ux improvement_2](https://cloud.githubusercontent.com/assets/22910264/20711720/6e8e3cf0-b641-11e6-9559-eae78bbb83a6.jpg)

Probably it can be better done, it's just a first approximation.

Notes:
1. Those grey labels will only appear when you hover the mouse.
2. I thought it could be nice to add the "Archive" and "Delete" button close to the "Copy" and "Enlarge". This way we don't need the Manage menu anymore. Will be also nice to include a little explanation label when you hover the mouse over to them.
3. I think the size of the text of the current project (below iterations) was too big, and also could be better aligned with the buttons I talked about just before. 
4. I didn't add this into this proposal, but I would also make smaller the button "Submit Comment", and I would change the blue to the same one than the blue of the little arrows in iterations.
5. The requested help view will appear once you click on the "Request for help"  button. We won't need anymore that red label or the grey notification that appears currently. Then the button will change to green when the requested is made. I would add the same label and text that is right now when hovering the mouse over to "Request for help", and add the clickable label "Cancel request" to appear when you hover the mouse over the "Help requested" green button. If you cancel, you come back to the normal view.
6. I added a mail and facebook sharing options, so maybe you can send it to a friend also by mail or fb.
7. I think it will be nice that when you click on options like "See others' solutions", "Instructions" or "Test unit", it open's in a new tab window.

Looking forward to your thoughts,
Best.

**Comment by NobbZ** [comment]
I do like the proposal, but I have to add, that we need to sort out #3277 first and decide which of "enlarge", "copy", "archive" and "delete" needs to be per iteration or per file.

Could you prepare a mock, were you put "archive" and "delete" as an iteration command and "enlarge" and "copy" as a file command, just to see how it might look like?[1]

[1] : This does only reflect old behaviour and is not supossed to be a solution or anything else for what is discussed in #3277.

**Comment by celiagomezdev** [comment]
Thanks @NobbZ. Organise again all the design would need quite a lof of time but, trying to maintain the one that is now, there are 2 options:
1. Adding the icons in the main exercise iteration menu, something like: 
![ux improvement_4 copia copia](https://cloud.githubusercontent.com/assets/22910264/20715550/dad0c514-b64f-11e6-91cc-7e2578d96746.jpg)
Very important here that should appears a label "Delete iteration" and "Archive exercise" when you hover the mouse, and when you click, a pop up with something like "Are you sure that you want to delete this iteration?" "archive this exercise"?.

2. Adding again a Menu but a bit more separated of social media icons, with some options, and leaving in the "main" menu the direct options "View solutions of others'" and "Request for help".
![ux improvement_5](https://cloud.githubusercontent.com/assets/22910264/20718884/7fd9e16c-b65a-11e6-9c25-1c2e93d9c651.jpg)

**Comment by kytrinyx** [comment]
@celiagomezdev Thank you so much for this!

I really like where you're going with this. I think that your latest iteration which keeps the menu but reorganizes it works best, especially as it reduces some of the visual elements.

I'm not sure what the share by email would do—is there a standard type of behavior for this? (I've never done facebook integration, but I'm pretty sure it would be fairly straight forward to figure it out, and I think it would be a neat addition).

@jtigger want to see something cool? Look what @celiagomezdev is working on! :-)

**Comment by celiagomezdev** [comment]
@kytrinyx I'm glad that you like it!

Yes, I think I also like the last iteration the most. About the e-mail button... I don't know, I thought it could be nice to share directly the code in an email to someone maybe to ask for a review or help, to someone that is not inside exercism, like in a very direct way (the code appears in the body of the email so the person can answer directly on that email). But maybe it makes no sense... (by the way, I think the twitter sharing is not working properly, it appears an almost empty tweet, but maybe is only to me!).

Yes, sharing by Facebook can also help to spread the word about exercism :)

**Comment by celiagomezdev** [comment]
Ah, I would also add in the exercise view a direct link to the language page (in this case http://exercism.io/languages/swift/about) -and maybe also make clickable the logo to that same page-. I find a bit annoying to need to go every time to the full languages page and then look for your language. Something like:

![exercise_page](https://cloud.githubusercontent.com/assets/22910264/20750555/ca63d6aa-b6f7-11e6-9c02-d59bbd743fd8.jpg)

I would also add a field with the clickable languages in the Dashboard page:

![dashboard](https://cloud.githubusercontent.com/assets/22910264/20750641/3f2e80fc-b6f8-11e6-85cb-d2a9df90a882.jpg)

**Comment by kytrinyx** [comment]
> I would also add in the exercise view a direct link to the language page (in this case http://exercism.io/languages/swift/about) -and maybe also make clickable the logo to that same page-. I find a bit annoying to need to go every time to the full languages page and then look for your language.

Yes, that would be excellent!

**Comment by kytrinyx** [comment]
> I think is not working properly, it appears an almost empty tweet, but maybe is only to me!).

@celiagomezdev maybe. I know I see tweets from this regularly, but I haven't checked recently.

[update] I checked, and the most recent one is from Nov 22nd, so... maybe broken? https://twitter.com/tech_populi/status/801141476658794497

**Comment by kytrinyx** [comment]
>  this way also the twitter bird is not alone anymore

Haha, yeah. Let's implement sharing via facebook to fix the lonely twitter bird problem. Email seems a bit complicated (mostly that I don't know what it should do). I'd prefer to keep all the conversation on the site, if possible.

**Comment by celiagomezdev** [comment]
Twitter: It appears to me if I share:
https://twitter.com/celiagvp/status/804077557192806404

E-Mail: Yes, I agree! maybe better just inside exercism 👍

**Comment by kytrinyx** [comment]
@celiagomezdev Definitely broken! I'm posting a new issue specifically about that.

**Comment by jtigger** [comment]
@celiagomezdev I also really dig what you're up to, here.  I'm with you: I really like your latest iteration... the make easily discoverable the actions that cultivate the behavior we want... and the other (valuable, but not as crucial) stuff just one click/hover away.  I :heart: it!

I like where you are going with the color treatment too.  Right now, the "official" palette is black, white and pink.  Other color shows up, but I believe these are the Bootstrap defaults for flash messages and buttons (read: not intentionally picked).  I does seem like we've got need/room for some accent colors... would be terrific to make a run at picking those.  This reminds me of an ongoing discussion with @troubalex about esthetics in exercism/discussions#31 ... the palette is a crucial aspect of that.

👍 👍 !!!

**Comment by celiagomezdev** [comment]
Yes, I agree, I think using only the palette that is now on the main page -black/white, grey and dark pink- would be perfect. I would also not use the blue tone, or just If we add it to the whole visual project and with a purpose, for example, highlight some buttons for any reason, but never randomly. I've been reading a bit the topic you mentioned, really interesting! Somehow I like the pink background in the header, as everything else will be in white or light grey background. It gives a power/personality to the page IMO, but maybe it would be also nice to see another options. 
I'm happy that you are considering these changes, let me know If I can do something else!

**Comment by kytrinyx** [comment]
@jtigger @Insti What do you think of making new issues that describe each individual change that @celiagomezdev has described here? I think they're potentially great "good first patch" issues, aside from the fact that the website can be tricky to get running locally.

**Comment by Insti** [comment]
Individual issues, good idea. I think all of these ideas are great.
Keeping focus on one thing at a time makes it a lot easier to review and merge.

**Comment by kytrinyx** [comment]
There are a lot of great ideas in here, but as it stands, this issue is not actionable, because it contains a lot of different ideas and suggestions.

If you would like to move this topic forward, please open a new issues for each idea in http://github.com/exercism/discussions, linking back to this issue so that we can discuss each separately to figure out exactly what can/should be done.

**Comment by celiagomezdev** [comment]
Hi @kytrinyx @Insti I'm really sorry for being away, I'm having hard health family issues for the last 8 months so I couldn't focus on this. I agree in discuss every issue separately, I hope to be able to dedicate more time on this at some point in the near future.

**Comment by kytrinyx** [comment]
@celiagomezdev ❤️ :heart: :heart: :heart: :heart: I wish you all the best.
