### ISSUE TITLE
Twitter sharing is broken

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3285]
@celiagomezdev reported that twitter sharing is broken. Here's what she gets if she shares:
https://twitter.com/celiagvp/status/804077557192806404

**Comment by Insti** [comment]
# First Good Patch

## What do I need to know?

basic html, a little bit of Ruby.

## What will I learn?

Some basic Ruby, A bit about how twitter's API works.
How to [set up an Exercism development environment](https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#setup)

## Where should I start:

Start here: https://github.com/exercism/exercism.io/blob/master/app/views/submissions/show.erb#L17


##  What if I get stuck?

Just ask for help here! Or visit the [Developer chatroom](https://gitter.im/exercism/dev)
We're all very friendly.

**Comment by tejasbubane** [comment]
This is an example URL being generated:

`https://twitter.com/intent/tweet?text=I just submitted the #Elixir raindrops exercise at @exercism_io - Leave me a nitpick at http://exercism.io/submissions/0b7122bb15044990a62717315ea68dd6`

**Hint**: Notice the hashtag in for language name `#Elixir`. This and everything after this gets ignored.

**Comment by esparta** [comment]
--- Tweet Button & HashTags… is it possible?
https://twittercommunity.com/t/tweet-button-hashtags-is-it-possible/16915

Apparently it needs to be encoded if needed in the mids of the text.

**Comment by tejasbubane** [comment]
> Apparently it needs to be encoded if needed in the mids of the text.

Yes. Ruby's [URL.encode](https://ruby-doc.org/stdlib-1.9.3/libdoc/uri/rdoc/URI/Escape.html#method-i-encode) can be used.

**Comment by Insti** [comment]
## Advanced: 

It would be good to extract the code that is currently in the template into a helper, so the template code becomes: 
```
href="<%= tweet_url(submission) %>"
```

**Comment by collin-mcgrath** [comment]
I wrote up a fix for this issue if @esparta is no longer working it.

**Comment by kytrinyx** [comment]
I'd love to see this fixed @collin-mcgrath. We've not heard from @esparta for a few weeks on this one, go ahead and submit your fix.

**Comment by esparta** [comment]
Hi all,

Sorry for been out this long. I need to apologise for not communicate on
time...

For the last weeks I have been out of the USA to complete the immigrantion
process for my current working visa, in the meaning time my computer was
commissioned by my wife, she think since I was not working I should expend
more time with her and my son, I was agreed.

Yesterday I came back to the country, reviewing what needs to be reviewed,
and trying to be on again. Been out 3 weeks without computer and internet
is bigger than I thought.

I will continue on this tonight if you all agree on continue whatever is
missing.

Thanks and sorry again.

**Comment by kytrinyx** [comment]
> For the last weeks I have been out of the USA to complete the immigrantion
process for my current working visa

@esparta that sounds super stressful! I've been through the whole immigration process to the USA twice, and it wasn't fun either time.

If you're still up for working on this, then that's awesome.

@collin-mcgrath it sounds like @esparta has this one covered :heart:

**Comment by bernardoamc** [comment]
Seems like this one is fixed. 🎉
