### ISSUE TITLE
Expand code doesn't expand until window scrolled

### ISSUE THREAD

**Issue by Motardo** [exercism/exercism.io#3288]
This is kind of hard to explain but:  
Using this page as an example [Gigasecond](http://exercism.io/submissions/4f008927d8d042c581fd0be145924bce)  

When viewing a submission, if the comments on the right are longer than the code on the left,  
![view](https://cloud.githubusercontent.com/assets/2099793/20818944/1f27980e-b7ff-11e6-8ede-b96d5dcc7eca.png)

and you scroll the window down until the code tops out and the comments start to slip -   
![scroll](https://cloud.githubusercontent.com/assets/2099793/20818946/28e0369e-b7ff-11e6-9f41-bbe869cb7823.png)

then click the expand button -  
![comments](https://cloud.githubusercontent.com/assets/2099793/20818969/4d29de92-b7ff-11e6-853b-775d58a79aa0.png)

the comments get moved below the code but the code window does not actually get bigger until the window is scrolled.  
![expand](https://cloud.githubusercontent.com/assets/2099793/20818980/5b2fe842-b7ff-11e6-96fa-c9a687534fbc.png)

Tested with firefox on ubuntu.

**Comment by Insti** [comment]
Reproduced. (firefox on debian)
Great instructions @Motardo .
Do you think you can fix it?

**Comment by NobbZ** [comment]
I can reproduce it on chrome as well (`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36`), but not in microsoft IE11 nor Edge.

**Comment by Motardo** [comment]
> Do you think you can fix it?  

Unfortunately no. I dug around and found that when the left code sidebar tops out, it gets set to `position: fixed` by [theia-sticky-sidebar](https://github.com/WeCodePixels/theia-sticky-sidebar). It also gets a `width` style and all the parent divs get `transform: none`.  I was able to get the code window to expand by removing `transform: none` from the parent divs, so I think there is some interaction there. I don't know why scrolling the browser window fixes things.  There is a [possibly related issue on theia](https://github.com/WeCodePixels/theia-sticky-sidebar/issues/16)

**Comment by Motardo** [comment]
I was going to try to bisect the culprit, but rewound the repo back to May 2016 and the bug is still there. Going further back the db schema is too different and the seeds wouldn't load.  

What would you think about replacing theia-sticky-sidebar with native Bootstrap affix api?  We could fine-tune the exact behavior we want without any plugin weirdness?

**Comment by Insti** [comment]
It's not a very serious bug. I'd be inclined not to worry about fixing it at all. 
Eventually something will change and it will fix itself.

Unless replacing theia-sticky-sidebar is on the roadmap anyway, but that sounds front-endy so I have no opinion on that. (@tejasbubane?)

**Comment by tejasbubane** [comment]
> but that sounds front-endy so I have no opinion on that. (@tejasbubane?)

I am pretty bad when it comes to CSS. 😄 



> We could fine-tune the exact behavior we want without any plugin weirdness?

If this is the case, and you think it is worth the effort, I would say go for it 👍

**Comment by Motardo** [comment]
I got it to work somewhat by turning off theia's fixed positioning styles. Using [this page](http://exercism.io/submissions/5c68a77ffec34d0daa6ab26d4e092f82) as an example if I scroll down to the last comment:  
![scrolldown](https://cloud.githubusercontent.com/assets/2099793/21032417/576e6e36-bd77-11e6-961f-7669ed0e4ae7.png)
Then in the browser console:
```javascript
$(window).scrollTop() // =2095, scrolled way down to the last comment
$('a[data-action=enlarge]').trigger('click') // click the expand button
$('.theiaStickySidebar').css('position', 'static').css('width', '') // remove sticky styles
$('.code').css('min-height', '') // remove more sticky style
$(window).scrollTop() // =2095, still at the bottom :(
```
The code is at the top and expanded but I'm still at the bottom, so the code unexpectedly jumps out of view:
![jumped](https://cloud.githubusercontent.com/assets/2099793/21032438/7648f6b4-bd77-11e6-8faf-303f0570c8ef.png)

I think it would be nice if the code window stayed in the same relative position when clicking expand and shrink. It is a little disorienting otherwise. I'm going to work on scrolling the window back up to where the code is.

**Comment by Motardo** [comment]
It seems that theia is responding to scroll events and repositioning things correctly, so all that is needed is to send the right scroll event when the expand button is clicked. I'm going to make a PR with this fix  

I'm not sure how we want to handle shrinking the window. When the page is in full-width expanded mode the code window could be scrolled up into the navbar area with just a little bit of the shrink button showing. Then if you click shrink, you can't really keep the code window up there because that's not generally a valid location for the code window in a two column sticky layout. So I don't think we can avoid the code window jumping a bit in certain cases when the window shrinks.

**Comment by kytrinyx** [comment]
I'm deploying this now. I tested it locally before merging it, but please do take a look to see that the new behavior is what you expected.

**Comment by Motardo** [comment]
@kytrinyx Hmm, the live site with build b2f992b should have my change, but it doesn't seem to be working. I don't think the the new script.js file that I changed got compiled into the app.js that is being served?

excerpted from http://exercism.io/js/app.js:
$(".code a[data-action='enlarge']").on("click",function(){var a=$(this).parents(".code"),b=a.siblings(".comments");a.removeClass($(this).data("old-class")),a.addClass($(this).data("new-class")),b.removeClass($(this).data("old-class")),b.addClass($(this).data("new-class")),$("a[data-action='enlarge']",a).hide(),$("a[data-action='shrink']",a).show()}),$(".code a[data-action='shrink']").on("click",function(){var a=$(this).parents(".code"),b=a.siblings(".comments");

The new line is missing :(  I know there was some tinkering with lineman recently...

**Comment by Motardo** [comment]
I just refreshed the browser and got the new version of js/app.js and everything seems to be working. I don't know if you fixed it, or I just had a cached version the whole time? Anyway it looks good now. Thanks!

**Comment by kytrinyx** [comment]
@Motardo It probably was cached, or you tested before it was completely deployed.
