### ISSUE TITLE
Submitting a comment with the keyboard doesn't clear the text area

### ISSUE THREAD

**Issue by Trevoke** [exercism/exercism.io#3289]
If you click submit, the comment shows up and the text area is blank.

On OSX, you can submit with the keyboard by pressing Command-Enter (probably Ctrl-Enter on other OS but I don't have another box handy to check).

When I submit that way, the comment shows up fine, but the text area has the comment's text in it, so when I attempt to navigate away I get an annoying JS warning that I've got unsaved work.

**Edited to add reproduction steps (@kytrinyx):**

1. Navigate to a submission's discussion
    * If you've already used Exercism before you can go directly to http://exercism.io/inbox 
    * If you're new, follow the instructions in the "how it works" pages to submit a new solution, and then visit that solution (the CLI will give you the link when you submit it, and there will also be a link from your dashboard)
2. Type some text into the comment box
3. Type Command-Enter (or Ctrl-Enter on linux/windows?)
4. _Comment should be submitted and appear in the discussion thread, and comment box should still have a copy of the text in it_.

**Comment by Insti** [comment]
Reproduced (Firefox on Debian)

Is this something you are able to fix Trevoke?

**Comment by Trevoke** [comment]
I'm sorry, but no, not in the near future. This is probably a relatively
good first patch for someone who's new to OSS contributions though.

**Comment by nickborromeo** [comment]
@Insti @Trevoke looks like the PR that addresses this has been merged. Can we close this issue out?

**Comment by Trevoke** [comment]
Wow, so it has! I got no notice of this (and I've not been using exercism in the past two weeks) but it's totally fixed now!

Thanks!
