### ISSUE TITLE
Verify CSS instructions in Contributing Guide

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3290]
Right now the contributing guide section on compass/scss says:

> Before committing, tell compass to compile the stylesheets for production use. - [Contributing Guide](https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md#scss)

Is that still accurate now that we have buildpacks that compile?

/cc @tejasbubane who probably knows the answer to this

**Comment by kytrinyx** [comment]
Well, on second thought... it helps catch syntax issues. So maybe we could specify that this is why you want to do it.

**Comment by troubalex** [comment]
This bit me. I'm not entirely sure if my setup is broken somehow or if I am plainly doing it wrong, but I didn't get compass to compile my stylesheets locally. Building after merge seemed to work just fine though.

Maybe some clarification around front-end tooling might be in order, provided I didn't simply miss something.

**Comment by kytrinyx** [comment]
> Maybe some clarification around front-end tooling might be in order

Yeah, definitely. I get compass to recompile, but I'm not sure what I'm doing differently than you :(

**Comment by tejasbubane** [comment]
> Well, on second thought... it helps catch syntax issues. So maybe we could specify that this is why you want to do it.

@kytrinyx I can see `compass watch` catching errors as well. So I think we can safely remove the `compass build` step and let heroku buildpack worry about it. 

> but I didn't get compass to compile my stylesheets locally. Building after merge seemed to work just fine though.

@troubalex Can you elaborate more on what fails? Maybe I can help. Try using just `compass watch` while developing, this will compile all sass and keep watching these files for any further changes. You don't need `compass build`.

**Comment by Insti** [comment]
Alternate viewpoint:
As someone who is not doing front end development, and just needed the assets to be built once `compass build` was more appropriate. `compass watch` built a lot of stuff and then never returned, (the desired behaviour if you're expecting it) but left me thinking it was stuck or broken. 
I would suggest that the default be for `compass build` and provide further instruction for those explicitly doing frontend development that `compass watch` is available.

**Comment by tejasbubane** [comment]
@Insti Yeah you are right. 👍  `compass watch` can be confusing and only needed by people doing frontend development.

**Comment by tejasbubane** [comment]
I am working on updating the frontend instructions.

**Comment by troubalex** [comment]
@tejasbubane 
> Can you elaborate more on what fails?

I think it's a combination of things. I'll delete my local repo, and start over. I'll let you know then if/where I get into trouble. Thanks for the offer!

Related: are we using compass for anything beyond compiling Sass?

**Comment by tejasbubane** [comment]
> Related: are we using compass for anything beyond compiling Sass?

@troubalex I don't think so.

**Comment by tejasbubane** [comment]
@Insti Going through the contributing guide made me think. 

1. Is `foreman` being used by heroku? If not can we add `compass watch` and `lineman run` there. So that these two processes run along with other stuff and all compilation is realtime.
Even for people concerned with backend only, they will need to compile if any new changes are pulled in. Might lead to inconsistencies and unnecessary bugs. 

2. Now that we don't have compiled js and css files, npm is actually a development dependency. Which is unnecessary for people working on backend stuff. Can we somehow remove this extra burden?

cc @kytrinyx

**Comment by kytrinyx** [comment]
`foreman` is not being used by heroku (see: https://github.com/exercism/exercism.io/blob/master/Procfile#L1)

I managed to have something work locally (I stuck an accidental semi-colon in a sass file) and then it seemed to build just fine locally with compass, but then it failed when I deployed. I don't know if I was just doing something wrong locally, though—this is quite likely.

I like the idea of just having foreman do what we need locally, though. That seems like a very sensible change.

**Comment by kytrinyx** [comment]
> npm is actually a development dependency [...] Can we somehow remove this extra burden?

That would be lovely. No ideas (this being totally outside of my field of experience), but I support the idea :-)

**Comment by tejasbubane** [comment]
> foreman is not being used by heroku (see: https://github.com/exercism/exercism.io/blob/master/Procfile#L1)

Umm, I think [foreman uses procfile](http://blog.daviddollar.org/2011/05/06/introducing-foreman.html) and [so does heroku](https://devcenter.heroku.com/articles/procfile#deploying-to-heroku). This `Procfile` works:

```
web: rackup -s puma -p $PORT
compass: compass watch
lineman: cd frontend && lineman run
``` 
But will this also take effect on heroku deployment running multiple dynos?

**Comment by troubalex** [comment]
Shouldn't lineman be able to compile Sass, and take care of all the prefixing and minifying? Compass feels like overkill if all we use it for is compiling...

**Comment by tejasbubane** [comment]
Yes lineman can compile sass. But I think we will need some configuration for that.

**Comment by kytrinyx** [comment]
I think it's fine to close this. The next time someone is confused about the CSS instructions, we can update them.
