### ISSUE TITLE
Sidebar does not show unread counts for language tracks

### ISSUE THREAD

**Issue by bcc32** [exercism/exercism.io#3295]
[Screenshot](https://cloud.githubusercontent.com/assets/1239097/20872805/929f2708-ba6f-11e6-98c1-f2e84693ca50.png)

I am not able to see any unread counts for language tracks, although the unread counts are working correctly for each of the exercises within a language track.

If I remember correctly, this problem occurred after marking all exercises as read within a language track; formerly, some of the unread counts were working fine, and others were not, but now that I have marked each language track as read *at least once in the past*, none of them are working.

**Comment by Insti** [comment]
Thanks for the report.

As another data point: I **can** see unread counts for language tracks and exercises. 
I have never used the mark all read button.

**Comment by kytrinyx** [comment]
I'm deploying the fix from @Motardo now. If you get a chance would you see if this fixes it for you?

**Comment by Motardo** [comment]
@kytrinyx It seems to be fixed for me! Awesome!

**Comment by bcc32** [comment]
@kytrinyx Appears to be fixed.  Thanks!

**Comment by Insti** [comment]
Thanks @bcc32 and @Motardo for your help. :heart:
