### ISSUE TITLE
rikki highlighting issue with indents

### ISSUE THREAD

**Issue by Skilly** [exercism/exercism.io#3306]
*Refer [solution](http://exercism.io/submissions/1a3bc1a868fa42e48b4abfb6d4391a0f)*

[Rikki](http://exercism.io/rikki) commented 

> The indentation is inconsistent which makes it harder to read and understand the code.

However, as per the screenshot below, which shows the result of searching the source code for "  " (i.e. two spaces), the indenting used in the particular example is consistent
![rikki_indenting](https://cloud.githubusercontent.com/assets/94933/21077205/f97c4140-bf97-11e6-9965-22564b3b04c1.png)

Therefore the comment that Rikki provided appears at face-value to be incorrect

**Comment by mhelmetag** [comment]
Your method `def` and closing `end` are on different indents. Also you have indented under `raise ArgumentError` which is non-standard in Ruby.

I'm not sure what rikki's indent rules are offhand but I would assume these are contributing factors.

You might want to take a look at https://github.com/bbatsov

**Comment by kotp** [comment]
The indenting should look like this:

```ruby
class Hamming
  def self.compute arg1, arg2
    raise ArgumentError unless arg1.length == arg2.length
    hammingDistance = 0
    arg1.length.times do |pos|
      hammingDistance += 1 unless arg1[pos] == arg2[pos]
    end
    hammingDistance
  end
end
```

The `unless` does not start a body of a block in the case of line 7.  This is what Rikki is complaining about.

**Comment by Skilly** [comment]
Funny how you can look at something for ages and see absolutely no issues, yet once the problems are pointed out they're glaringly obvious and are blatantly staring you in the face!

Thanks @kotp  and @mhelmetag for your feedback.

Will mark issue as closed (obviously)

**Comment by mhelmetag** [comment]
> Funny how you can look at something for ages and see absolutely no issues, yet once the problems are pointed out they're glaringly obvious and are blatantly staring you in the face!

No worries 😆
