### ISSUE TITLE
Tree Building exercise in F# has nonsense readme

### ISSUE THREAD

**Issue by cowlike** [exercism/exercism.io#3310]
From the readme:

> The ID number is always
between 0 (inclusive) and the length of the record list (exclusive). No record
has a parent ID lower than its own ID and no record, except the root record,
has a parent ID that's equal to its own ID.

These sentences are both false and violated in the tests. Maybe the design changed and someone forgot to update the readme? Currently the root node has a parent id of -1.
[edit] Also I forgot to mention that the root record, and at least one child of the root, **must** have "a parent ID lower than its own ID".

**Comment by ErikSchierboom** [comment]
@cowlike The correct place to log that issue is at: https://github.com/exercism/xfsharp/issues Would you mind posting it there?

**Comment by cowlike** [comment]
Done! Thanks
