### ISSUE TITLE
Feature Request: View golang submissions with comments unrelated to formatting errors

### ISSUE THREAD

**Issue by nryberg** [exercism/exercism.io#3320]
Linting is great and automatic feedback is important.  It'd be great to browse other submissions to exercises that have comments that aren't automatically generated (eg. Golang's insistence on correct formatting).

Looking for more constructive feedback here.

**Comment by kytrinyx** [comment]
@nryberg Yeah, that's a good point. At the moment there's not an easy way to do this, but I think we should put this on the list of things to think through how to accomplish. It's very important to figure out how to make it easy for people to browse relevant and interesting comments!

**Comment by kytrinyx** [comment]
I'm taking a pass through our issue tracker with the goal of making sure that every open issue we have on exercism/exercism.io is actionable. 

As this issue stands it isn't actionable. If you would like to move this topic forward, please open a new issue in http://github.com/exercism/discussions

Please:
- summarize the points so far
- link back to this issue
- include the intended goals for the discussion
