### ISSUE TITLE
Typo on the main exercism.io page

### ISSUE THREAD

**Issue by gamefreak9125** [exercism/exercism.io#3321]
On the main there is a typo in the Are you ramping up in a new language? section. This is how it reads, Now you feel hamstrung with one hand tied behind your back and an an unfair suspicion that you should already know this. I know it's a tiny issue but I was wondering if I could fix it for my first contribution! :)

**Comment by kotp** [comment]
Yes, you may, and please do @gamefreak9125!

**Comment by gamefreak9125** [comment]
Alright thanks, I just submitted the pull request for it.

**Comment by Insti** [comment]
Thanks @gamefreak9125 :heart:
No contribution is too small.

**Comment by kytrinyx** [comment]
> No contribution is too small.

So very true! It's absolutely amazing to come back from two weeks of vacation and see the accumulated improvements from all the various changes people have been making :heart:
