### ISSUE TITLE
link on elixir about page leads to 404

### ISSUE THREAD

**Issue by kentonscode** [exercism/exercism.io#3326]
On the Elixir [about](http://exercism.io/languages/elixir/about) page there is a link to "BEAM Erlang Virtual Machine." However, it goes to a 404. 

Here's the updated link: http://erlangcentral.org/videos/euc-2014-robert-virding-hitchhikers-tour-of-the-beam/

Simple, but thought to mention it :)

**Comment by Insti** [comment]
This needs to be fixed in the [Exercism Elixir repository](https://github.com/exercism/xelixir)

Edit the file: https://github.com/exercism/xelixir/blob/master/docs/ABOUT.md

**Comment by syivanes** [comment]
HI! I fixed it and ready to push.

**Comment by Insti** [comment]
:tada: thanks @syivanes do you know what you need to do next to make a Pull Request to the xelixir repository?

**Comment by kentonscode** [comment]
closing as it seems to have been fixed and merged.

**Comment by kytrinyx** [comment]
Thanks @kentonscode for catching this! ✨
