### ISSUE TITLE
rescue me! label remove !

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3330]
The new 'rescue me!' label made it difficult to link due to the ! being excluded from Github's urlifier. 

https://github.com/exercism/exercism.io/labels/rescue%20me! (this now links to the modified label due to the ! at the end being ignored)

So I removed the `!` at the end of the label.

https://github.com/exercism/exercism.io/labels/rescue%20me

**Comment by kytrinyx** [comment]
Sounds good. /cc @kotp

**Comment by kotp** [comment]
Yep, that will work.
