### ISSUE TITLE
Finalize deprecation of old language track file structure

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3336]
A while back we started moving all of the exercise implementations into a subdirectory called `exercises` in each of the stand-alone language track repositories.

That is to say that instead of having a mix of `bin`, `docs`, and individual exercises,
we can have `bin`, `docs`, and `exercises` in the root of the repository, and all
the exercises collected in a subdirectory.

In other words, instead of this:

```
x{TRACK_ID}/
├── LICENSE
├── README.md
├── bin
│   └── fetch-configlet
├── bowling
│   ├── bowling_test.ext
│   └── example.ext
├── clock
│   ├── clock_test.ext
│   └── example.ext
├── config.json
└── docs
│   ├── ABOUT.md
│   └── img
... etc
```

we have something like this:

```
x{TRACK_ID}/
├── LICENSE
├── README.md
├── bin
│   └── fetch-configlet
├── config.json
├── docs
│   ├── ABOUT.md
│   └── img
├── exercises
│   ├── bowling
│   │   ├── bowling_test.ext
│   │   └── example.ext
│   └── clock
│       ├── clock_test.ext
│       └── example.ext
... etc
```

The production code handles both variants (and has for a while), but now we're starting to get eager to delete the old code that handles the deprecated version.

There are a few repositories that have not yet moved their exercises, so we'd need to finish doing that first (listed below).

**Comment by definemethod** [comment]
I can take care of this.

**Comment by definemethod** [comment]
exercism/xcpp#63 is already done
[PR to xcoldfusion](https://github.com/exercism/xcoldfusion/pulls)
[PR to xhaxe](https://github.com/exercism/xhaxe/pull/15)
[PR to xnasm](https://github.com/exercism/xnasm/pull/16)
[PR to xtcl](https://github.com/exercism/xtcl/pull/8)
[PR to nvbnet](https://github.com/exercism/xvbnet/pull/14)

Two projects, xnasm and xtcl don't have any exercises. For those projects I just created the exercises directory and put a note inside referencing this issue and instructing future contributors to put new exercises in the exercises directory.

**Comment by kytrinyx** [comment]
Thank you so much @definemethod! I'm so excited about all the code we'll get to delete now :-)

**Comment by definemethod** [comment]
Happy to help!
