### ISSUE TITLE
Build in Java track breaks

### ISSUE THREAD

**Issue by javaeeeee** [exercism/exercism.io#3339]
Hello, build in the Java track breaks with the following message.

+echo ==================================================
==================================================
+echo '52 of 52 -- list-ops'
52 of 52 -- list-ops
+echo ==================================================
==================================================
+./exercism --config .journey-test.exercism.json fetch java list-ops
2017-01-09 20:52:24 - JSON::GeneratorError - source sequence is illegal/malformed utf-8:
	/home/travis/.rvm/gems/ruby-2.2.5/gems/petroglyph-0.0.7/lib/petroglyph/engine.rb:9:in `to_json'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/petroglyph-0.0.7/lib/petroglyph/engine.rb:9:in `render'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/petroglyph-0.0.7/lib/tilt/petroglyph.rb:22:in `evaluate'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:822:in `render'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/petroglyph-0.0.7/lib/sinatra/petroglyph.rb:6:in `pg'
	/home/travis/build/exercism/xjava/build/x-api/api/v1/routes/exercises.rb:84:in `block in <class:Exercises>'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1609:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1609:in `block in compile!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/bugsnag-2.8.12/lib/bugsnag/rack.rb:33:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:953:in `forward'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1027:in `route_missing'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:988:in `route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/bugsnag-2.8.12/lib/bugsnag/rack.rb:33:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:953:in `forward'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1027:in `route_missing'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:988:in `route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/bugsnag-2.8.12/lib/bugsnag/rack.rb:33:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:953:in `forward'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1027:in `route_missing'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:988:in `route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:953:in `forward'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1027:in `route_missing'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:988:in `route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:984:in `route!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/bugsnag-2.8.12/lib/bugsnag/rack.rb:33:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/puma-2.15.3/lib/puma/server.rb:541:in `handle_request'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/puma-2.15.3/lib/puma/server.rb:388:in `process_client'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/puma-2.15.3/lib/puma/server.rb:270:in `block in run'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `call'
	/home/travis/.rvm/gems/ruby-2.2.5/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
W, [2017-01-09T20:52:24.286294 #27402]  WARN -- : ** [Bugsnag] No API key configured, couldn't notify
2017/01/09 20:52:24 an internal server error was received.
Please file a bug report with the contents of 'exercism debug' at: https://github.com/exercism/exercism.io/issues 
::1 - - [09/Jan/2017:20:52:24 +0000] "GET /v2/exercises/java/list-ops HTTP/1.1" 500 514662 0.5579
+on_exit
+echo '>>> on_exit()'
>>> on_exit()
+[[ 27402 != '' ]]
+kill 27402
+echo 'stopped x-api (pid=27402)'
stopped x-api (pid=27402)
+cd /home/travis/build/exercism/xjava
+echo '<<< on_exit()'
<<< on_exit()
The command "bin/journey-test.sh" exited with 1.
Done. Your build exited with 1.
Top

**Comment by javaeeeee** [comment]
Removed config files from the project folder, build passed.

**Comment by tejasbubane** [comment]
@jadevance Would you mind checking the issue on the [java track](https://github.com/exercism/xjava)? If this is an issue with exercism's config, we should fix it.

**Comment by javaeeeee** [comment]
Hu, @tejasbubane, I've fixed it. Just uploaded some IDE config files to the repo and the API choked on it. Already removed files, so everything works OK and I closed the issue. Sorry for the disturbing you.
