### ISSUE TITLE
Can't log in with Github Profile

### ISSUE THREAD

**Issue by NolanChan** [exercism/exercism.io#3340]
Hi, I'm currently having an issue signing into exercism with my GitHub account. Basically whenever i click on the log in button, it refreshes the page and brings me back to the same page. I know it's not much info, but hopefully someone else experienced this issue as well? I can't get my API key because of this...

![exercism](https://cloud.githubusercontent.com/assets/1487616/21791068/4796aed8-d695-11e6-9b49-8a236b6d1ef0.gif)

**Comment by bernardoamc** [comment]
Hi @NolanChan are you still having the issue?

**Comment by NolanChan** [comment]
Hi @bernardoamc , yup the issue still exists for me

**Comment by bernardoamc** [comment]
- Do you have another browser where you can try this? :)
- If you go to [exercism](http://exercism.io/) and click on `Login with Github` in the top right do you still have the problem?
- Did you clear the cache?

If none of these solve the problem we can start investigating with the developer tools. But I hope we can solve this as fast as possible. ;)

**Comment by NolanChan** [comment]
Hi @bernardoamc , thanks for the suggestions:

1. I've tried this on all the browsers on my mac (Safari, Firefox, Chrome). However, I can log in on my phone (which points to something local on my Mac causing this problem)
2. I've tried clicking on the top right Login text and it doesn't log me in either.
3. I've tried an `Empty Cache and Hard Reload` and nothing changed

I'm open to debugging this in dev tools 👍

**Comment by Insti** [comment]
Can you/are you log(ged) into GitHub on your mac?

**Comment by NolanChan** [comment]
Yup, I'm logged in

**Comment by NolanChan** [comment]
I'm guessing it's gunna be pretty hard to diagnose :\

**Comment by kytrinyx** [comment]
@NolanChan it might be! Can you try opening an incognito window in chrome and trying that?

If that doesn't work, try revoking Exercism in https://github.com/settings/applications and then re-authorizing it.

If that doesn't work, it might be worth opening the JavaScript console, making it so it doesn't clear errors, and then trying to log in.

**Comment by lblackstone** [comment]
I don't have logs to confirm, but I suspect I'm running into the same problem as @NolanChan. I was unable to log in to exercism.io using any browser, and tried clearing the GitHub auth as well, but no dice.

I believe the culprit is the parental controls software I have installed on our home computer (Covenant Eyes).  It does work fine if the parental control software is disabled, so that's almost certainly the problem.

**Comment by petertseng** [comment]
Ah that is a helpful lead. I do know that if I set my browser to block cookies from exercism.io, I will receive the same behaviour: logging in just directs to the same page (whether I log in via the "Log in with Github" on the homepage, or http://exercism.io/please-login). If I then allow cookies from exercism.io, it will then work. If a similar setting is possible with the appropriate software on everyone's respective computers, we might want to see if that helps.

**Comment by lblackstone** [comment]
I just verified that my browser is accepting cookies, and the ad blocker is disabled. I'm still unable to log in as long as the parental controls are running.

**Comment by kytrinyx** [comment]
@lblackstone That's incredibly helpful. With the parental controls on you're able to log into GitHub, though, right?

**Comment by lblackstone** [comment]
@kytrinyx Yes, GitHub works normally, and I'm seeing Exercism on the list of authorized applications.

**Comment by NolanChan** [comment]
Hi @lblackstone , it seems likely that covenant eyes is responsible for this issue. Seems to be some sort of edge case though, as I've been able to log into every other application fine

**Comment by kytrinyx** [comment]
I asked the support team at GitHub if they'd heard of this happening before, and they hadn't.

Since the log in is through the GitHub API, the cookie that gets set is on the exercism domain, not the GitHub domain.

Is covenant eyes not able to set the Exercism cookie?

**Comment by lblackstone** [comment]
As far as I can tell, the same three cookies are set with or without the filter running. Here is a capture of a failed auth request: https://gist.github.com/lblackstone/2222a739ce81817ce04b0b524722911e

**Comment by lblackstone** [comment]
I added a successful request to the gist for comparison. Looks like the referrer is different between the streams. I'm guessing the filter is breaking the redirection somehow.

**Failed:** https://gist.github.com/lblackstone/2222a739ce81817ce04b0b524722911e#file-wireshark-capture-request-failed-L97
**Successful:** https://gist.github.com/lblackstone/2222a739ce81817ce04b0b524722911e#file-wireshark-capture2-successful-request-for-comparison-L68

**Comment by kytrinyx** [comment]
Thanks @lblackstone. A different referrer would break the request.

**Comment by kytrinyx** [comment]
@lblackstone @NolanChan It looks like this problem is being caused by the parental control software, not by anything on Exercism or GitHub's side of things.

You should be able to whitelist Exercism within the software controls. You might also contact their support and make an argument that Exercism should not be blacklisted by default.

Thanks for helping figure this one out.

**Comment by lblackstone** [comment]
Whitelisting exercism.io and github.com fixed the login problem. I contacted their support and suggested that they whitelist the sites globally as well, though not sure if they will follow through on that.

**Comment by kytrinyx** [comment]
@lblackstone Thanks so much for checking back in to confirm!
