### ISSUE TITLE
Fix order-dependency in test

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3342]
The build failed non-deterministically with the following:

```
  1) Failure:
CommentTest#test_mentions [/home/travis/build/exercism/exercism.io/test/exercism/comment_test.rb:29]:
Expected: ["bob", "alice"]
  Actual: ["alice", "bob"]

```

**Comment by Insti** [comment]
https://github.com/exercism/exercism.io/blob/master/test/exercism/comment_test.rb#L29

**Comment by definemethod** [comment]
Hey I would like to take a crack at this, but running the individual file with ```ruby test/exercism/comment_test.rb``` does not cause me any failures. Can you provide the seed value from the failed build please?

**Comment by definemethod** [comment]
PR is up, please see 5e358

**Comment by Insti** [comment]
Can you reproduce the problem if you create bob before alice?

**Comment by definemethod** [comment]
I was able to reproduce the problem in the console.
