### ISSUE TITLE
Ignore submissions without modifications

### ISSUE THREAD

**Issue by ukchukx** [exercism/exercism.io#3343]
First off, thanks for such a wonderful platform.
I would like to suggest that submissions that do not differ from the last submission be ignored.
I've mistakenly re-submitted solutions a couple of times while trying to fetch.

Thanks, once again.

**Comment by kytrinyx** [comment]
@ukchukx We currently do ignore solutions that are not changed. I'm not sure why the behavior would be different for you, and we'd need some more information to start tracking it down.

Here's what I get if I try to resubmit:

```
$ exercism submit hello.go
2017/01/28 15:12:26 unable to submit (HTTP: 400) - duplicate of previous iteration
```

If your duplicate submissions are going through, would you please reopen this with a link to a submission with duplicate iterations?

**Comment by Insti** [comment]
Something is strange with duplicate detection. See also #3359 which had the opposite problem.

**Comment by kytrinyx** [comment]
I wonder if it's checking duplicates against deleted iterations. I'd like to have reproduction steps for these issues.

**Comment by ukchukx** [comment]
@kytrinyx See this: http://exercism.io/submissions/c1603b446f1e4065b8cd27db66422020

**Comment by kytrinyx** [comment]
@ukchukx It's saying that submission doesn't exist.

**Comment by ukchukx** [comment]
Sorry about that. Deleted it since this issue was closed. Didn't know anyone would check it out.

**Comment by kytrinyx** [comment]
@ukchukx No worries. If you're able to get reproduction steps for this, please open a new issue so we can track it and fix it.
