### ISSUE TITLE
Teams: I don't need an invite to the team that I created

### ISSUE THREAD

**Issue by bunnymatic** [exercism/exercism.io#3346]
As a user who created a team
I see that I'm automatically added to the team
but I also see a notification that I am invited to join the team.
When I click to accept the invite, i get an error page (presumably because i've already been added to the team).

Obviously not a big deal, just a light user flow bug.

BTW, super excited about the idea of teams.

**Comment by Insti** [comment]
Thanks for the report @bunnymatic, I think this is already being worked on here: https://github.com/exercism/exercism.io/issues/3110

**Comment by bunnymatic** [comment]
Yep.  I did an issue search but didn't catch that one.  I'll close as a duplicate.

Thanks

**Comment by bunnymatic** [comment]
Closed as a dup of #3110 which is in progress.
