### ISSUE TITLE
The "circling arrows" icon on some Iterations tabs is confusing

### ISSUE THREAD

**Issue by ssokolow** [exercism/exercism.io#3348]
In the submission views, one tab (it seems to always be the highest-numbered) has an icon with blue circling arrows next to the number and I have no idea what it means.

There's no tooltip and I tried opening it up in the DOM explorer but it doesn't follow Bootstrap recommended practices of having a hidden hint for assistive technologies either.

I wondered if it might mean that my answer was still being checked (sort of like a "Travis-CI job still in progress" indicator) but it never seems to go away.

All I can assume is that maybe it's an extremely counter-productive attempt to indicate which tab represents the newest entry.

Depending on what it actually means, it either needs a tooltip or needs to be replaced with more appropriate iconography.

**Comment by mhelmetag** [comment]
You're right in that it means the most recent/current iteration of a solution. Do you have any suggestions for a more appropriate icon?

**Comment by Insti** [comment]
Does it need an icon at all? Is not being the highest number indication enough that it is the most recent?

**Comment by ssokolow** [comment]
The issue with suggesting an icon for this use is that using an icon is inherently counter to established convention. Not only is there no established iconography for exactly what you want, attempting to use an icon for it is liable to cause confusion.

The convention is to make these sorts of temporal distinctions using other aspects of the UI's design, such as size, shape, colour, saturation/desaturation, very self-evident labels, or some kind of axial "older <-> newer" labelling.

(One thing which might work would be to reduce the font size slightly for all but the most recent tab... thus clearly indicating "this is the most important/significant one".)

A big part of the reason I was so confused was that, when I looked at it, the fact that it was counting up was so glaringly obvious that the purpose of the mysterious "reload" (when in toolbars) or "variant throbber" (when not clickable) icon in the button **couldn't possibly** have anything to do with that, so I tried to figure out what less obvious thing I was missing.

That said, if you really must have an icon, look at icons intended to convey "new". While not entirely accurate (newly arrived != newest entry), it's the safest places where you can fudge the definitions since there is precedent for "it remains new until ousted by something newer".

I remember seeing `fa` in your classes, so I poked around in the FontAwesome catalogue but there's nothing in that vein. However, using a little CSS to put a point of specular reflection on the border of the tab would be in line with the visual shorthand most icon themes use. (ie. "so new it's still shiny")

I'd still go with something less tacky though.

**Comment by mhelmetag** [comment]
I like the idea of no icon and relying on order. Seems cleaner and much simpler.

> (One thing which might work would be to reduce the font size slightly for all but the most recent tab... thus clearly indicating "this is the most important/significant one".)

It's already kind of this way with the bold so maybe that's enough?

**Comment by ssokolow** [comment]
The boldface styling is tied to the active tab, not the rightmost... it's also a bit subtle with your chosen font.

**Comment by mhelmetag** [comment]
> The boldface styling is tied to the active tab, not the rightmost... it's also a bit subtle with your chosen font.

Ah, right. Definitely worth improving then.

**Comment by NobbZ** [comment]
If you remove that icon there is nothing to differantiate active and
archived submissions.

Max Helmetag <notifications@github.com> schrieb am Mo., 16. Jan. 2017,
09:20:

**Comment by ssokolow** [comment]
@NobbZ What about the red "Archived" badge on the byline? Isn't that serving the purpose you're talking about?

**Comment by NobbZ** [comment]
You are totally right, that should be sufficient.

Stephan Sokolow <notifications@github.com> schrieb am Mo., 16. Jan. 2017,
09:31:

**Comment by bastienvinh** [comment]
It's confusing to me as well. Each time I feel like it's synchronising, compiling or doing tests. 

Is it possible to have a status on the page to see if the iteration passes it or fail it? And what happen if we do 500 iterations? Is it not better to make a list like Travis-CI or any test suite.

Because I don't if I should resubmit or not since I have not response from the robot.

**Comment by kytrinyx** [comment]
> Is it possible to have a status on the page to see if the iteration passes it or fail it?

Unfortunately, that's not possible with our current setup. We don't test people's solutions after they submit.

If you do a bunch of iterations, the page will be pretty unusable.

> Because I don't if I should resubmit or not since I have not response from the robot.

The robot doesn't reply to everything. We have a small set of things that the robot recognizes (via static analysis), but for the most part there's no post-processing.

**Comment by kytrinyx** [comment]
I'm taking a pass through our issue tracker with the goal of making sure that every open issue we have on exercism/exercism.io is actionable. 

As this issue stands it isn't actionable. If you would like to move this topic forward, please open a new issue in http://github.com/exercism/discussions

Please:
- summarize the points so far
- link back to this issue
- include the intended goals for the discussion

**Comment by ssokolow** [comment]
Sorry. I just don't have the time or willpower.

...and, as a UX guy, I have to say that this sort of approach to actionability triage is discouraging to issue-reporters and, in the long run, likely to result in harming your product.

1. I may have the confidence and reading/writing skills to check off your bullet points, but other issue reporters may not.
2. It's likely to demoralize and discourage potential participants from reporting an issue a second time.
3. If nobody reopens the bug, you just silently accumulate a pile of flaws that went unfixed.

**Comment by kytrinyx** [comment]
This issue is a problem statement with no recommendation as to how to solve it.

If it is intended to offer feedback, then the feedback has been heard and I agree with it. It is something that is on my mind and when I determine a way to resolve it, I will. If feedback was the goal, then the goal has been achieved, so the issue can be and has been closed. 

If there is a greater goal here, i.e. to determine a way to resolve it by supplying expert recommendations from people with greater UX experience than I have, then please follow the process I described to gather those recommendations.

If there is already a specific recommendation of how to resolve the problem described here, please open a new issue with those details.

Thanks very much for helping make Exercism better!

**Comment by ssokolow** [comment]
Ahh, that makes more sense. In that case, I'd suggest rephrasing this line...

> As this issue stands it isn't actionable. If you would like to move this topic forward, please open a new issue in http://github.com/exercism/discussions

...to something which makes it more clear that closing means "Any remaining problems are being moved to a TODO list for more abstract/long-term items so they don't bog down the short-term list" rather than "As far as we're concerned, this is resolved."

**Comment by kytrinyx** [comment]
@ssokolow That's a great point. "Closed" doesn't mean resolved.

In the case of UX, we're working closely with a group of professionals (see https://github.com/exercism/discussions/issues/113 for context) to reconsider everything from the ground up. Everything in the current site happened by accident. We never actually did all the UX research, asking questions about the people involved (who they are, how they learn, what is holding them back) etc. We're questioning everything—even the things that seem to work.

Thanks for your thoughts and contributions 🌷
