### ISSUE TITLE
The purpose of archiving exercises is unclear

### ISSUE THREAD

**Issue by ssokolow** [exercism/exercism.io#3349]
When I look at my Exercism dashboard and see the "Archived" section, there's no indication of what archiving actually means, beyond moving things from one category to another.

Worse, it leaves me with a nagging worry over whether action or inaction will hurt more. (eg. Will I irreversibly disable functionality I wanted by archiving something or do I have to archive things to keep them from getting unexpectedly deleted?)

I'd suggest putting one of those "question mark in a blue circle" icons at the end of the "Archived" header which, when clicked, produces a popup of some sort, explaining what archiving does and why they would or wouldn't want to archive something.

**Comment by mhelmetag** [comment]
So based on the tooltip that exists when archiving a single solution (not on the profile page):
<img width="1536" alt="archive_tooltip" src="https://cloud.githubusercontent.com/assets/8609429/21972691/1f2070ee-db70-11e6-9674-63cd82e4cd8b.png">

Would you suggest simply mirroring that info (possibly with a little more explanation) on one of these hypothetical question mark tooltips on the profile page? A la something like this:
<img width="1649" alt="profile_page" src="https://cloud.githubusercontent.com/assets/8609429/21972787/08172644-db71-11e6-8ce0-743415a242ef.png">

**Comment by ssokolow** [comment]
Something like that, but, when I see that description, my impulsive response is "That's it? You wrote all that extra GUI and backend complexity for so little?"

There are some questions you'll want to answer in order for such a description to be effective:

1. So... what do I get out of this? (ie. Is it a "declutter my Current list" button? A "stop other learners from bugging me" button? Something else?)
1. Is there any downside to just trying to leave everything in the "Current" list forever to shy away from having to take responsibility for anything that may happen?
1. Can I change my mind later?

Also, since I noticed `fa` in your classes, the FontAwesome icon you'd want to use is [fa-question-circle](http://fontawesome.io/icon/question-circle/).

**Comment by mhelmetag** [comment]
Seems like a reasonable addition to me.

We might want to look into a dictionary for explanations (e.g. have a library with short and long descriptions of certain features) so that they can be easily standardized and referenced through the app. Like for archive which appears as a single action on solutions and bulk action on the profile page.

**Comment by tejasbubane** [comment]
Thanks @ssokolow! This definitely is an issue.

And it looks like a `good first patch`. For anyone looking to fix this, the archive button can be found on any user's profile page:  eg. http://exercism.io/tejasbubane - below `Current Exercises` table. Refer @mhelmetag's screenshot in previous comment for position of tooltip.

Related code: https://github.com/exercism/exercism.io/blob/master/app/views/user/_exercises_table.erb#L57-L58

**Comment by timpwbaker** [comment]
I've submitted a first pass at this here:
https://github.com/exercism/exercism.io/pull/3350

**Comment by nickborromeo** [comment]
I think this issue can be closed 😄

**Comment by kotp** [comment]
I agree.
