### ISSUE TITLE
Broken "help launch" on upcoming tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3351]
I'm not sure when this happened, and it could very well be my fault, but we're missing the text on the "help launch this track" page. E.g.

http://exercism.io/languages/ceylon/launch

<img width="773" alt="screen shot 2017-01-22 at 12 11 26 pm" src="https://cloud.githubusercontent.com/assets/276834/22185087/2bf44d46-e09c-11e6-99a1-27d3a54460fc.png">

I bet the content is there, just not being included correctly.

**Comment by yannvery** [comment]
Hi,
As I understand before usage of `Trackler` gem, `X::Docs::Launch` class used a default `LAUNCH.md` file to build 'launch' docs.
This behavior does not exist on `Trackler`. Maybe we could create a default `LAUNCH.md` file and implement the same behaviour on Trackler ?

**Comment by kytrinyx** [comment]
Ah, right. Yeah, that's exactly what happened.

I don't think Trackler should know about this, since it's specific to the website, rather than to the curriculum. We can replace the LAUNCH file and run it through the markdown processor, or hard-code it in an Erb template.

**Comment by yannvery** [comment]
Ok, I could prepare a PR about this if you don't mind.
