### ISSUE TITLE
Usability, find good code, and remember where it was.

### ISSUE THREAD

**Issue by Daniel-at-github** [exercism/exercism.io#3353]
How can I do to find good examples of the code?
At this time I take a look at several (the more the better) and mark as `looks great` the one I like.
After this search and find... How can I see all my `looks great` again if I want them as reference?

**Comment by kotp** [comment]
There is currently no way to do this, as far as I know.  It really is a good feature request!

**Comment by kotp** [comment]
Let me expand on that a little bit.  There is a way to find and look at good examples of solutions.  But it is a manual process.

It would be good to be able to pull up the ones marked as "Looks Great" and to classify them somehow based on the "type" of solution.

There could be concerns about "popularity voting effect" in that the ones that get more marks attract more marks because of those marks...

What I do in the meantime is just record those iterations in a file...

**Comment by Daniel-at-github** [comment]
To avoid marks "hype" surely something have been invented yet. May be a http://www.kittenwar.com/ type of system (choose one of two random)? (This avoids the self promotion bot too).

**Comment by kotp** [comment]
We can't mark our own as "Looks great" so no problem there.

**Comment by Daniel-at-github** [comment]
My comment wasn't well redacted in "This avoids the self promotion bot".

You could create more users (bots) to upvote yourself (but nowadays there is no incentive to cheat in this way). With "choose one of two random" upvote yourself needs too much effort.

But "choose one of two random" was only an example of a means of see good code.
(My goals coming to exercise is learn to code better and learn and practicing peer review).

**Comment by Daniel-at-github** [comment]
One workaround is to write in my own exercise a comment with the links of what I liked, and what reviews I have done.

**Comment by kytrinyx** [comment]
This isn't quite the same topic but it's got some really interesting stuff in it related to this if you want to take a look https://github.com/exercism/exercism.io/issues/2803

**Comment by kytrinyx** [comment]
I'm taking a pass through our issue tracker with the goal of making sure that every open issue we have on exercism/exercism.io is actionable. 

As this issue stands it isn't actionable. If you would like to move this topic forward, please open a new issue in http://github.com/exercism/discussions

Please:
- summarize the points so far
- link back to this issue
- include the intended goals for the discussion
