### ISSUE TITLE
"Help us make this better" text is missing

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism.io#3355]
According to https://github.com/exercism/exercism.io/blob/0eb974ec68c5cc290370476a4a30370b75f870e3/x/docs/track.rb#L28, it should be the case that https://github.com/exercism/exercism.io/blob/0eb974ec68c5cc290370476a4a30370b75f870e3/x/docs/md/track/BETTER.md gets included on each language track topic page - for example at the bottom of http://exercism.io/languages/cpp/resources. It is not currently present.

This appears to be similar to #3351 and #3356 (both already fixed). Someone attempting to fix this might consider using a similar fix as the fix to both of those issues.

**Comment by petertseng** [comment]
How embarrassing. I have accidentally created a duplicate report. Katrina already noticed that at #3351.

**Comment by petertseng** [comment]
I'll just repurpose this issue number for a different issue I found - "Help us make this better" text missing. New issue description reproduced below:

According to https://github.com/exercism/exercism.io/blob/0eb974ec68c5cc290370476a4a30370b75f870e3/x/docs/track.rb#L28, it should be the case that https://github.com/exercism/exercism.io/blob/0eb974ec68c5cc290370476a4a30370b75f870e3/x/docs/md/track/BETTER.md gets included on each language track topic page - for example at the bottom of http://exercism.io/languages/cpp/resources. It is not currently present.

This may be similar to #3351, so those fixing this issue may consider fixing the two at the same time.

**Comment by petertseng** [comment]
next deploy, I hope.

**Comment by kytrinyx** [comment]
This is deployed now
