### ISSUE TITLE
i/o timeout whilst fetch 

### ISSUE THREAD

**Issue by alex-bender** [exercism/exercism.io#3358]
During `fetch` I got this error:
```
$ exercism fetch c   
2017/01/25 17:41:03 Get http://x.exercism.io/v2/exercises/c?key=REDACTED: dial tcp: lookup x.exercism.io on 217.20.184.1:53: dial udp 217.20.184.1:53: i/o timeout
```
Would be better to have well described reason of this error;
Not sure if it is issue, or if it is already opened.

```
$ exercism --version
exercism version 2.3.0
$ uname -a
Linux bender 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
```

**Comment by Insti** [comment]
Thanks for the report @alex-bender, would you mind re-posting this in the cli repository: https://github.com/exercism/cli/issues

**Comment by alex-bender** [comment]
@Insti
Sure. Should I close this one?

**Comment by Insti** [comment]
Probably, any fix will need to happen in the cli repository and it would be good to avoid duplicating the discussion.

We can always re-open this instance if it becomes relevant.
