### ISSUE TITLE
LinkedIn Badges and GitHub intergration 

### ISSUE THREAD

**Issue by paulbonneau** [exercism/exercism.io#3361]
Maybe you could setup a badge system as Codeschool one.
It could be really interesting for newbies that want to show their progression to potentials recruiters and it could also helps you growth your community.

An incentive to post the exercises done on Github could helps you achieve the same goals.

**Comment by kytrinyx** [comment]
We're going to be looking into the topic of progression a lot more deeply in the coming months. There's been a bunch of discussion about the topics of badges. If you are interested, take a look at this discussion: https://github.com/exercism/exercism.io/issues/1617

**Comment by kytrinyx** [comment]
I'm closing this in favor of https://github.com/exercism/discussions/issues/123 - please take a look at that and chime in if you have any thoughts that are not covered there.
