### ISSUE TITLE
Pagination does not work on team language and user stream pages

### ISSUE THREAD

**Issue by pjhades** [exercism/exercism.io#3363]
Pagination on the team language and user stream pages like:

    http://exercism.io/teams/XXX/streams/tracks/rust
    http://exercism.io/teams/XXX/streams/users/YYY?page=2

does not work. Clicking on either the page number or the Next button does not show the desired page.

I'm not familiar with web development but I think it would be easy to reproduce this problem by running the website locally with some fake team data.

**Comment by kytrinyx** [comment]
There was a fix in progress for this, but I believe it was abandoned: https://github.com/exercism/exercism.io/pull/3096

**Comment by yannvery** [comment]
It could be a good idea to rescue this PR and keep first commit from @jendiamond and include fixes for all streams views.
I would like to work on it if nobody already takes it.

**Comment by Insti** [comment]
Go for it @yannvery . But it may be better to start afresh.
