### ISSUE TITLE
Can't fetch next problem--timeout issue (python track)

### ISSUE THREAD

**Issue by garylippens** [exercism/exercism.io#3364]
Debug information:
**** Debug Information ****
Exercism CLI Version: 2.3.0
OS/Architecture: linux/amd64
Build OS/Architecture linux/amd64
Home Dir: /home/gary
Config file: /home/gary/.exercism.json
API Key: XXXXXXXXXXXXXXXXXXXXXXXXXXX
Exercises Directory: /home/gary/exercism
Testing API endpoints reachability
	* API: http://exercism.io [connected] 5.167883557s
	* XAPI: http://x.exercism.io [Get http://x.exercism.io: dial tcp: lookup x.exercism.io on 127.0.1.1:53: dial udp 127.0.1.1:53: i/o timeout] 10.000703467s
	* GitHub API: https://api.github.com/ [Get https://api.github.com/: dial tcp: lookup api.github.com on 127.0.1.1:53: dial udp 127.0.1.1:53: i/o timeout] 10.000714829s

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).

Email:  Gary.Lippens@gmail.com

**Comment by kytrinyx** [comment]
@garylippens Are you still having trouble on the python track?

Which command are you running? `exercism fetch` or `exercism fetch python`? Have you tried asking for the explicit exercise (see http://exercism.io/languages/python/exercises).

**Comment by garylippens** [comment]
Hi,
Thanks for getting back with me.
Problem persisted for a couple of days (timeouts when trying to fetch a new
problem).  Problem just went away and things seem OK now.  Don't know what
resolved the issue.
I was using exercism fetch python

Thanks,

Gary Lippens

**Comment by kytrinyx** [comment]
Glad it's resolved, sorry we didn't help figure out it while it was happening! Thanks for the update :sparkles:
