### ISSUE TITLE
Profile is not working at the moment.

### ISSUE THREAD

**Issue by kotp** [exercism/exercism.io#3365]
The page to load profile is not working at the moment.  Bugsnag reports should be coming in.

**Comment by kotp** [comment]
This is only effecting kotp and rpottsoh, perhaps related to recent changes to pascal/dephi

**Comment by kytrinyx** [comment]
Ah, could be. Let me see what I find.

**Comment by kytrinyx** [comment]
When I updated the data I forgot to account for conflicting unique indices. This should be corrected now.
