### ISSUE TITLE
Error page after `Accept` on team invitation to self

### ISSUE THREAD

**Issue by febeling** [exercism/exercism.io#3372]
I setup a team with myself as member and got invited.

This invitation I can’t accept as the app each time responds with an error (“This is our fault” page).

The notification also doesn’t get marked as read and keeps showing in my notifications list.

I’m in the team already, so this is more about smoothness than blocking any functionality.

The button does a `POST` on `/teams/elixirdrinkersberlin/invitation/accept`, fwiw.

**Comment by bernardoamc** [comment]
Thanks for the report @febeling ❤️ 

I have an open PR dealing with this issue [here](https://github.com/exercism/exercism.io/pull/3308) and we have this issue #3110. Would you mind if I closed this issue in favor of the existing one? :)

**Comment by febeling** [comment]
@bernardoamc - no, man, let's close it by all means! :) I only want to help here!
