### ISSUE TITLE
Cant submit Cssharp Solution on Windows Machine

### ISSUE THREAD

**Issue by tornikegomareli** [exercism/exercism.io#3375]
i configured my working directory, also configured my exercism API, i fetched my csharp first lesson, make solution, tests checked me that my solution is working, so now i'm trying to submit my solution in this way first.

C:\Users\micro>exercism submit C:\Users\micro\exercism\csharp\csharp\hello-world\HelloWorld.cs

Command line said to me:

**It seems like you've tried to submit a solution file located outside of your**
**configured exercises directory.**

Current directory:      C:\Users\micro
**Configured directory:   C:\Users\micro\~\Desktop\Exercism**

**Try re-running "exercism fetch". Then move your solution file to the correct**
**exercise directory for the problem you're working on. It should be somewhere**
**inside C:\Users\micro\~\Desktop\Exercism**

**For example, to submit the JavaScript "hello-world.js" problem, run**
**"exercism submit hello-world.js" from this directory:**
**inside C:\Users\micro\~\Desktop\Exercism**

**For example, to submit the JavaScript "hello-world.js" problem, run**
**"exercism submit hello-world.js" from this directory:**

_You can see where exercism is looking for your files with "exercism debug"._

_Then i changed my command directory_ 

**C:\Users\micro>exercism submit C:\Users\micro\~\Desktop\Exercism\csharp\csharp\hello-world\HelloWorld.cs**

**And CMD returned this output**
**2017/02/10 03:09:41 unable to submit (HTTP: 400) - Unknown problem 'csharp' in C# track**

_**what's problem, i have just stucked on HelloWorld solution more then 2 hour, i cant submit and fetch next lesson.**_

There is also my exercism debug

** Debug Information **
**Exercism CLI Version: 2.3.0**
**Exercism CLI Latest Release: 2.3.0**
**OS/Architecture: windows/amd64**
**Build OS/Architecture windows/amd64**
**Home Dir: C:\Users\micro**
**Config file: C:\Users\micro\.exercism.json**
**API Key: 9ec9dd001a9a4be69aaae9d0737f4d61**
**Exercises Directory: C:\Users\micro\~\Desktop\Exercism**
**Testing API endpoints reachability**
        *** GitHub API: https://api.github.com/ [connected] 156.3138ms**
        *** API: http://exercism.io [connected] 290.0972ms**
        *** XAPI: http://x.exercism.io [connected] 429.5635ms**

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).

**Comment by NobbZ** [comment]
> ```
> C:\Users\micro>exercism submit C:\Users\micro\exercism\csharp\csharp\hello-world\HelloWorld.cs
> ```

That path should be ``C:\Users\micro\exercism\csharp\hello-world\HelloWorld.cs``

Move your exercise accordingly and try again

**Comment by tornikegomareli** [comment]
Thank you it solved my problem <3
