### ISSUE TITLE
Broken tracks links under teams/.../users/../

### ISSUE THREAD

**Issue by stain88** [exercism/exercism.io#3376]
When going to your `teams/xxx/streams` overview page, there is the option to filter by language, or by user. 
Clicking on a user then seems to offer a further filter by tracks, but clicking on one of those points to `teams/xxx/streams/users/xx/tracks/xx`, which is a 404. 
Are these tracks links supposed to instead point to `teams/xxx/streams/tracks/xx`?

**Comment by bernardoamc** [comment]
Hi @stain88 , thanks for the feedback! <3

I think #3367 deals with this scenario, soon this will be solved.

**Comment by stain88** [comment]
Ah, cool, missed that PR.

**Comment by kytrinyx** [comment]
The PR got merged today ✨ 

This is being deployed now.
