### ISSUE TITLE
Mouse hovering on iteration number removes syntax highlighting

### ISSUE THREAD

**Issue by pjhades** [exercism/exercism.io#3378]
To reproduce:

* Visit a submission page `http://exercism.io/submissions/<hex>` with multiple iterations
* Hover on an iteration number

Then the syntax highlighting of the code is gone.

I'm not sure if this is actually a feature rather than a bug.

**Comment by NobbZ** [comment]
This is a side-effect of the quick-preview feature and intended as such to not slow down the quick-switch of the panes.

**Comment by kytrinyx** [comment]
@Motardo Since you did the work in https://github.com/exercism/exercism.io/pull/3324 you might have thoughts about this.

**Comment by pjhades** [comment]
If this is just the designed behaviour rather than a bug then feel free to close this issue. The preview feature is really convenient for people to see the code in other iterations without actually switching to them. 👍  It would be cool to preview the highlighted code. But anyway, thanks for the great work!

**Comment by Motardo** [comment]
Yes, this is the designed behavior. The main reason for this is that I wanted the preview to be instantaneous, without any network/server delay (Currently, highlighting is done on the back-end and previews are a front-end effect). I considered some ways to get instant previews with highlighting (use a front-end highlighter, or pre-compute the highlighting of every iteration and include it in the initial server response), but it seemed like too much computation for a feature that most people are probably not going to use? Also, when flipping back and forth between two iterations, I think the code changes might actually stand out better when there is no highlighting, so I left it like that. But I don't have any objection to adding highlighting to the previews. We would just have to think about what is the best way to do it.

**Comment by kytrinyx** [comment]
> If this is just the designed behaviour rather than a bug then feel free to close this issue.

Since that is the case I'm going to go ahead and close this. Thanks for taking the time to discuss it!
