### ISSUE TITLE
Proposal:  Developing a Selenium Based GUI Automated Tests

### ISSUE THREAD

**Issue by GalaDe** [exercism/exercism.io#3380]
This technique will help to reduce the effort required in GUI modeling and test coverage analysis during the software testing process. With automated testing, a tester or the developer can use a testing framework such as Visual Studio, ReSharper and Selenium Web Driver to finish all of the usual test cases and print out a test result file without having to manually execute the tests themselves. This allows the tester to leave the workstation running the tests on its own while working on another task simultaneously. I believe having these automated tests will greatly increase productivity at Exercism for both developers and testers.

Effective Automation:

1. Reduced utilization of manual resources
2. Reduced test cycle time
3. Improved test coverage, since testing may be done more frequently.

In my opinion, automated testing will be a huge boon to an Exercism as it allows developers to run the test suite right after the implementation of a new feature. It will provide additional guaranteed test coverage without the risk of human error. The tests will cover all the main functionality of the UI.

I will glad to develop the automated tests, if you don't have them.

**Comment by kytrinyx** [comment]
@GalaDe Thank you so much for offering. I completely agree that having a good suite of GUI tests would be useful for all of the reasons that you mention.

The one concern that I have at the moment is that the current website is a prototype and we're in the process of doing from-the-ground-up / from-scratch research and user experience design. This means that we expect to completely re-imagine the user interface.

I would not want to have you put in a huge amount of effort towards these tests right before the user interface completely changes.

/cc @exercism/reboot

**Comment by kytrinyx** [comment]
For more about the design work that we're undertaking (and the reasons for it) see:

- https://github.com/exercism/discussions/issues/113
- http://tinyletter.com/exercism/letters/the-delightful-design-of-exercism

**Comment by GalaDe** [comment]
Hi @kytrinyx, Thank you for your response.  I agree, it doesn't make any sense to develop automated tests, if you're planning to change the GUI. I will be happy to help you in the future with that.

**Comment by kytrinyx** [comment]
@GalaDe Awesome! I am making a note of this. I'm going to close this, and we'll open a new issue (and ping you in it) when we're ready to add GUI tests.

**Comment by GalaDe** [comment]
@kytrinyx, sound good!
