### ISSUE TITLE
archiving/unarchiving redirects to dashboard

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3381]
When one archives or unarchives an exercise directly from that exercises view, one gets redirected to the dashboard.

I'd think though it would make more sense to stay on the exercises page for further review.

Please label as discussion.

**Comment by kytrinyx** [comment]
> I'd think though it would make more sense to stay on the exercises page for further review.

Yeah, I think you're right about that. If nobody has very strong feelings in the opposite direction, I'd say we should go ahead and make the change.

**Comment by nholden** [comment]
Makes sense to me! I took a shot at addressing this issue in https://github.com/exercism/exercism.io/pull/3421.
