### ISSUE TITLE
Inviting yourself to new team produces a weird notification

### ISSUE THREAD

**Issue by JIghtuse** [exercism/exercism.io#3383]
There are actually a few issues with creating a new team.

First one is in interface. It is not clear that if I create a new team I will be in it already (i.e., I do not need to add myself to "Usernames" field).

Second issue appears when I create a new team and invite myself to it (due to first issue). Team created as planned, but I have always-unread notification with a message `JIghtuse would like you to join the team TEAM-NAME.` It is possible to click "Decline" and it will disappear. But if you click "Accept" you will get an error `Sorry! That's our fault!`, and notification will be still unread. Again, it is unclear to user what happens if he clicks "Decline". I thought that I can be removed from the group.

I guess, for the second problem it would be best to ignore invitation to yourself and not to send a notification. For the first one, we can then rename field to something like "Invite following users". It is still not ideal, but a bit clearer.

Related issue with user invitation: https://github.com/exercism/exercism.io/issues/3197

**Comment by kytrinyx** [comment]
/cc @bernardoamc, who has the most experience dealing with teams.



> It is not clear that if I create a new team I will be in it already

That's a good point. I wonder if it would be worth documenting this in depth on the new team page.

The short version is that you can have team managers who are not members.

- a manager can add/remove people and edit the metadata for the team
- a member's code will show up in the activity stream

You can be one or the other or both.

> Second issue appears when I create a new team and invite myself to it (due to first issue). Team created as planned, but I have always-unread notification with a message JIghtuse would like you to join the team TEAM-NAME.

That's a bug. I'm going to go ahead and mark this as such, even though the first issue is one of documentation.

**Comment by mhelmetag** [comment]
> Second issue appears when I create a new team and invite myself to it (due to first issue). Team created as planned, but I have always-unread notification with a message JIghtuse would like you to join the team TEAM-NAME.

I believe that #3308 , should've fixed the invite that was being sent out on creation but it looks like we still aren't blocking managers from inviting themselves to their team.

I agree that it would be great to document this and then reference the documentation (or a shortened version) in a flash message when we prevent inviting yourself.

**Comment by bernardoamc** [comment]
> I believe that #3308 , should've fixed the invite that was being sent out on creation but it looks like we still aren't blocking managers from inviting themselves to their team.

Right now when you create a team you will be added as a member automatically and will not receive a notification. If you are a manager and you invite yourself as member (already being one) you will also not receive a notification. On the other hand if you are not a member and you invite yourself you will receive one.

> That's a good point. I wonder if it would be worth documenting this in depth on the new team page.

I agree it's not really clear and it would be a good idea to document it. :)

**Comment by kytrinyx** [comment]
> it looks like we still aren't blocking managers from inviting themselves to their team after creation.

I don't think we should prevent you from doing so. I think it would make sense to simply add you as a member (if you're not already), and not add a notification for it.

**Comment by bernardoamc** [comment]
> I don't think we should prevent you from doing so. I think it would make sense to simply add you as a member (if you're not already), and not add a notification for it.

Yeah, I agree. Right now you will be added automatically as a member, but if you remove yourself and add it in a later time you will receive a notification. Not receiving this notification for managers is an improvement for sure.
