### ISSUE TITLE
Links inside email not clickable

### ISSUE THREAD

**Issue by blueelvis** [exercism/exercism.io#3386]
@Hi!

I just received the email from the exercism newsletter and it contains a lot of links of which a lot of them are not clickable. In other words, they are there as simple plain text which means that one should copy the link (Many of them are inside circular brackets) which make the process of visiting a link difficult.

For example, below is an excerpt from the email -

http://pasted.co/3fd91c3b

I was wondering if this could be improved :)

Have a nice day!

**Comment by kytrinyx** [comment]
Thanks @blueelvis This is my bad. I usually link them up manually, and forgot to yesterday.

I'll make sure to link them up properly next time.

Unfortunately there's no way to edit an existing email in the archive.

**Comment by blueelvis** [comment]
Thanks Katrina :)
