### ISSUE TITLE
Benchmark testing for Python and more

### ISSUE THREAD

**Issue by Benco1** [exercism/exercism.io#3387]
A friend of mine who has completed the Go track pointed out that there are benchmarks in addition to unit tests for Go, but not for Python and some other languages. I am currently working through the Python track and thought it would be great if it also had benchmark testing.

I would be happy to help on this if it's something Exercism folks would like to move forward on.

**Comment by kytrinyx** [comment]
@Benco1 This is a great question. Would you mind opening an issue in the https://github.com/exercism/discussions/issues repo? That will get the question in front of everyone who is concerned with the higher-level questions and cross-track concerns.

**Comment by tejasbubane** [comment]
I guess this can be closed in favour of https://github.com/exercism/discussions/issues/121.
