### ISSUE TITLE
Broken my profile & dashboard pages

### ISSUE THREAD

**Issue by robphoenix** [exercism/exercism.io#3388]
I'm working on this PR: https://github.com/exercism/cli/pull/374

I'm testing it in a fresh VM. I installed Go, cloned my repo, switched to my development branch and ran `go build -o out/exercism exercism/main.go`
I added my API key and fetched an exercise without a problem.

```sh
vagrant@vagrant:~/code/go/src/github.com/robphoenix/cli/out$ ./exercism fetch fsharp

Not Submitted:       1 exercise
fsharp (Hello World) /home/vagrant/exercism/fsharp/hello-world

New:                 1 exercise
fsharp (Hello World) /home/vagrant/exercism/fsharp/hello-world

unchanged: 0, updated: 0, new: 1
```

I then tried to submit an exercise but got the following error:

```sh
vagrant@vagrant:~/code/go/src/github.com/robphoenix/cli/out$ vim ~/exercism/fsharp/hello-world/hello-world.fs
vagrant@vagrant:~/code/go/src/github.com/robphoenix/cli/out$ ./exercism submit ~/exercism/fsharp/hello-world/hello-world.fs 
2017/02/27 15:27:40 unable to submit solution - an internal server error was received.
Please file a bug report with the contents of 'exercism debug' at: https://github.com/exercism/exercism.io/issues 
vagrant@vagrant:~/code/go/src/github.com/robphoenix/cli/out$ ./exercism debug

**** Debug Information ****
Exercism CLI Version: 2.3.0
Exercism CLI Latest Release: 2.3.0
OS/Architecture: linux/amd64
Build OS/Architecture /
Home Dir: /home/vagrant
Config File: /home/vagrant/.exercism.json
API Key: 6a99*************************bb0
Exercises Directory: /home/vagrant/exercism
Testing API endpoints reachability
	* XAPI: http://x.exercism.io [connected] 390.135067ms
	* API: http://exercism.io [connected] 415.212136ms
	* GitHub API: https://api.github.com/ [connected] 567.325971ms

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).
vagrant@vagrant:~/code/go/src/github.com/robphoenix/cli/out$ ./exercism submit ~/exercism/fsharp/hello-world/hello-world.fs 
2017/02/27 15:28:29 unable to submit (HTTP: 400) - duplicate of previous iteration
```

Now, when I visit my profile page and dashboard page on exercism.io I get a `Sorry! That's our fault!` page and am unable to view my profile or dashboard.

I am able to submit and fetch exercises using the regular exercism/cli client. I can also view my previous exercise submissions and other users profile pages on exercism.io.
 
Although when I try to visit the fsharp solutions page (the first exercise in this track is the test one I submitted above) it says `Couldn't find that user`, which says to me that it wasn't properly submitted.

As far as I know I've only broken my own profile, thankfully. My question then is not what's wrong with my PR, but what have I done to my profile page and how can I fix it? I'm not sure how to find out what's happened to my profile page on the backend? As far as I can tell I my data is still available, as I can access old solutions, it's just the profile & dashboard pages that are not working when I try to access them.

I take full responsibility for this screw-up and I explicitly implore anyone not to test out my PR as it's obviously unstable and I'd hate for anyone else to break their exercism.io profile.

**Comment by kytrinyx** [comment]
> I take full responsibility for this screw-up

I suspect that we have some pretty fragile code on the backend, which would make it my fault, not yours. Or we could share :)

> and I explicitly implore anyone not to test out my PR

:heart: Let me take a look at the data and the logs to see if I can figure out what's going on.

**Comment by kytrinyx** [comment]
@robphoenix I'm seeing an exercise that has the correct track id (`fsharp`), but the slug is `nil`.

The attached submission also has `fsharp` as the track ID and a nil slug.

**Comment by kytrinyx** [comment]
@robphoenix are you comfortable enough with Ruby to get this running locally? You could configure the CLI to submit to your local machine, which would let you delete and recreate submissions much more easily.

I'm going to go ahead and delete this exercise with the associate submission so you get your profile/dashboard back.

**Comment by robphoenix** [comment]
:heart: Thankyou @kytrinyx all is back to normal! phew :relieved: 

I did manage to get this running locally before, so I'll try and get that going again, makes a lot more sense and I don't know why I didn't think to do it before. C'est la vie.

Again, thankyou for fixing this, I hope your ankle heals as speedily.

Now, why was the slug nil? hmmm :confused: and on to the next problem.
