### ISSUE TITLE
Unable to submit my first Python solution.

### ISSUE THREAD

**Issue by mohammedsultan** [exercism/exercism.io#3389]
I get the following error when I try to submit the first solution.

Sultans-MBP:~ Sultan$ cd Documents/exercism/python/hello-world/
Sultans-MBP:hello-world Sultan$ exercism submit hello_world.py
2017/02/27 11:28:28 unable to submit (HTTP: 400) - Unknown language track exercism

Thanks,
Sultan.

**Comment by kytrinyx** [comment]
@mohammedsultan would you paste the output of the `exercism debug` command? I think we need to reconfigure your `--exercism-dir` path.

**Comment by ADKebert** [comment]
having a similar issue:

~/Exercism/Elixir/hello-world
$ exercism s hello_world.exs 
2017/02/27 16:06:58 unable to submit (HTTP: 400) - Unknown language track Elixir

and here's my debug output:
**** Debug Information ****
Exercism CLI Version: 2.3.0
Exercism CLI Latest Release: 2.3.0
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/akebert
Config file: /Users/akebert/.exercism.json
API Key: Hidden
Exercises Directory: /Users/akebert/Exercism
Testing API endpoints reachability
	* GitHub API: https://api.github.com/ [connected] 47.124477ms
	* XAPI: http://x.exercism.io [connected] 159.969844ms
	* API: http://exercism.io [connected] 166.029982ms

**Comment by NobbZ** [comment]
@ADKebert Your problem is slightly different. Your basepath seems to be recognized correctly, but the languages folder is named wrong. It should be `elixir`, not `Elixir`, please note the changed capitalisation.

Please rename your folder and everything should work.

**Comment by mohammedsultan** [comment]
@kytrinyx Here's the submit error and the debug info.
```
sultans-mbp:~ Sultan$ cd Documents/exercism/python/hello-world
sultans-mbp:hello-world Sultan$ exercism submit hello_world.py
2017/02/27 18:17:07 unable to submit (HTTP: 400) - Unknown language track exercism
sultans-mbp:hello-world Sultan$ exercism debug

**** Debug Information ****
Exercism CLI Version: 2.3.0
Exercism CLI Latest Release: 2.3.0
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/Sultan
Config file: /Users/Sultan/.exercism.json
API Key: 11f5f7394d0a4bb4b07044265901c56d
Exercises Directory: /Users/Sultan/Documents
Testing API endpoints reachability
	* GitHub API: https://api.github.com/ [connected] 16.845185ms
	* XAPI: http://x.exercism.io [connected] 91.728737ms
	* API: http://exercism.io [connected] 123.893126ms

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).
```
The exercism folder is located in Documents.
It used to be in `/user/Sultan/exercism` folder previously, later I changed the directory using the command `exercism configure --dir=~/Documents/exercism/`

**Comment by kytrinyx** [comment]
@mohammedsultan Would you please rerun the configure command:

```
exercism configure --dir=~/Documents/exercism/
```

At the moment, if you say `exercism configure` it will show that the directory is `~/Documents` or `/Users/Sultan/Documents`. It looks like the path didn't get reconfigured with `/exercism/` appended.

You can rerun `exercism configure` without any flags in order to see the current configuration, too.

You can also look at this by opening up the `/Users/Sultan/.exercism.json` file in your favorite editor.

**Comment by mohammedsultan** [comment]
@kytrinyx You were right. I did the following and it worked!
```
Sultans-MBP:~ Sultan$ exercism configure

Configuration written to /Users/Sultan/.exercism.json

  --key=11f5f7394d0a4bb4b07044265901c56d
  --dir=/Users/Sultan/Documents
  --host=http://exercism.io
  --api=http://x.exercism.io

Sultans-MBP:~ Sultan$ exercism configure --dir=~/Documents/exercism/

Configuration written to /Users/Sultan/.exercism.json

  --key=11f5f7394d0a4bb4b07044265901c56d
  --dir=/Users/Sultan/Documents/exercism/
  --host=http://exercism.io
  --api=http://x.exercism.io

Sultans-MBP:~ Sultan$ exercism submit Documents/exercism/python/hello-world/hello_world.py
Your Python solution for Hello World has been submitted. View it here:
http://exercism.io/submissions/f44935b7eb064558871b42be0fc05eba

See related solutions and get involved here:
http://exercism.io/tracks/python/exercises/hello-world
```
Thank you for your support, Katrina!

**Comment by kytrinyx** [comment]
That's excellent news, @mohammedsultan! Glad it got sorted.
