### ISSUE TITLE
Submission API: track id and slug should be case insensitive

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3390]
We detect the track ID and the slug based on the path of the submission. E.g.

```
/Users/me/tmp/exercism/go/clock/clock.go
```

In this case the track ID is `go` and the slug is `clock`.

In this https://github.com/exercism/exercism.io/issues/3389#issuecomment-282854697 it is clear that we don't normalize the track id and the slug when someone submits. In the following case we would get an error saying that there's no such track:

```
/Users/me/tmp/exercism/GO/clock/clock.go
```

We should make these case insensitive in the API endpoint (https://github.com/exercism/exercism.io/blob/master/api/v1/routes/iterations.rb#L43).

**Comment by sbeidels** [comment]
I would love to work on this issue if no one has picked it up already

**Comment by mathvesilva** [comment]
@sbeidels Hey, are you working on it? If not i have a fix ready.

**Comment by sbeidels** [comment]
Yep, i just need to do some testing and then I'll submit the pull request.

**Comment by kotp** [comment]
@mathvesilva sounds like you are ready to review too!  That would be awesome!

**Comment by sbeidels** [comment]
@mathvesilva, If you have a fix ready, go for it.  I submitted my pull request, but it didn't pass all of the checks.  It may be a few days before I have a chance to get back to this, and there is no reason to hold this fix up any longer.

**Comment by mathvesilva** [comment]
@jdsutherland Hello, don't worry. Your PR look ok to me, i think it should be accepted. Cheers

**Comment by kytrinyx** [comment]
> I didn't mean to swoop in and steal anyone's thunder.

It's always tricky in a fully distributed, fully volunteer situation to figure out who's working on what.

I don't know if there's any official etiquette. In this case I'd go with either the earliest PR or the one that we all agree is the best solution (sometimes there's a huge difference in approach. Here, probably not).

Either way: I really appreciate all of the contributions, and also the respectful discussion you all have had here on discovering that you were potentially stepping on each other's toes. :heart: :heart:

I'll go take a look at these now.

**Comment by kytrinyx** [comment]
In this case, I'm going to be pulling in @jdsutherland's solution, for a few reasons:

- the tests are passing
- the indentation is consistent

There's also a bit less code, which isn't always necessarily a factor, but if I have two equivalent solutions and they're equally readable, then I'll usually pick the one with less code.

I'm going to add a couple of notes to your solution @sbeidels, for learning purposes.
