### ISSUE TITLE
Typo in Foreman command in  "How to Setup a Local Development Environment" from CONTRIBUTING.md

### ISSUE THREAD

**Issue by aklap** [exercism/exercism.io#3393]
In the [Running Exercism.io locally section documentation](https://github.com/exercism/exercism.io/blob/master/docs/setting-up-local-development.md#run-exercismio-locally) there's a typo that causes the command to return an error:

`$ bundle exec foreman -s -p 4567`

Should be 's' no dash: 

`$ bundle exec foreman s -p  #4567`

**Comment by kytrinyx** [comment]
Closed by #3394
