### ISSUE TITLE
Clarification of the sentence on implementation dependencies in the Java "about" page

### ISSUE THREAD

**Issue by travisfw** [exercism/exercism.io#3396]
The [about page for Java](http://exercism.io/languages/java/about ) says "It has been specifically designed to have as few implementation dependencies as possible" and links to [a page about "implementation dependencies" with regards to Netbeans](https://www.java-tips.org/other-api-tips-100035/60-netbeans/1025-what-is-an-implementation-dependency-and-whathowwhen-should-i-use-one.html ). I have been programming with Java since 2003 and for a year of that used Netbeans, and I have never encountered the feature described on java-tips.org. Java 9 will introduce a *module* concept which seems similar design-wise to the *OpenIDE* modules described there, but I'm not sure what the relationship between the two is (I suspect this Netbeans feature influenced the design of Java 9 modules, and may have even served to prototype that design, but I'm speculating). In any case, it's an inappropriate link for an introduction to what Java is about.

Regardless of the confusing link, I don't know what the sentence about implementation dependencies is trying to communicate. Can it be clarified?

**Comment by kotp** [comment]
Thank you @travisfw for opening this issue.  Do you have the time to make an improvement of this paragraph?  Either removal, or clarification if that can be determined?

**Comment by tejasbubane** [comment]
@travisfw [This](https://github.com/exercism/xjava/blob/master/docs/ABOUT.md) is the file you want to change.

**Comment by kytrinyx** [comment]
This issue should be in the https://github.com/exercism/xjava repository to get tracked by the right folks.

**Comment by kotp** [comment]
Issue moved to [exercism/xjava #406](https://github.com/exercism/xjava/issues/406) via [**ZenHub**](https://www.zenhub.com/)
