### ISSUE TITLE
Submissions being indexed by Google

### ISSUE THREAD

**Issue by wolf99** [exercism/exercism.io#3397]
Just did a google search to find more info on a Meetup exercise to see that submissions by others (thankfully in other language tracks) are turning up in search results.... this can't be good! Surely a `Disallow` rule in the robots.txt or something is needed?

**Comment by wolf99** [comment]
Or a header setting https://yoast.com/prevent-site-being-indexed/

**Comment by kytrinyx** [comment]
Yes, definitely.

I think these are being indexed because people are posting the links to them on twitter.

**Comment by wolf99** [comment]
An example, googling for more info on what makes a day a "-teenth" day (I didn't understand the exercise at first!):
![teenth](https://cloud.githubusercontent.com/assets/281700/23699032/a25e995c-03e5-11e7-95b0-0caa611b75c7.PNG)

**Comment by wolf99** [comment]
According to the link I posted above, this could be solved by a simple few lines in the server configuration to stop listings of all pages under `submissions/`, or having all pages in that location served with the meta tag something like `<meta name="robots" content="noindex,nofollow"/>`.

Unfortunately current web development is not something I really have much knowledge of these days, so will have to leave the work up for grabs by someone better equipped!

**Comment by kytrinyx** [comment]
Appreciate it! I've added a "good first patch" label to this, for those who do have web development experience in Ruby / Sinatra.

**Comment by bermannoah** [comment]
Hi there! Is it cool if I volunteer to take this on?

**Comment by bernardoamc** [comment]
It would be awesome @bermannoah! <3

**Comment by bermannoah** [comment]
Hooray! I pushed up a potential fix. ( #3403 ) I'm not sure if it's the _best_ way to go about it, so let me know if there's something else I ought to do. :)
