### ISSUE TITLE
Feature request: link from submission page to exercise page

### ISSUE THREAD

**Issue by wolf99** [exercism/exercism.io#3398]
To get from a submission page to an exercise page (perhaps to refer to the readme or tests for that submission) one has to us navigate via Languages > <language-choice> > Available Exercises > <exercise-choice>. 

It would be handy if each submission page showed a link to the exercise page, for e.g. on my submission of Raindrops in C I would see a link "See the exercise" that would link to the C track's Raindrops exercise page

To "flip" back to the submission one has to navigate to Profile > <exercise-choice>. Admittedly this is a lot shorter for the return journey, but could be shorter still with a similar "See your submission" link on the exercise page. Obviously it only shows if one actually has made a submission for the exercise in question!

The latter link is a nicety really, considering how short the return journey is (although I only just discovered that link 😖), but the former would be very helpful indeed!

**Comment by kotp** [comment]
![selection_005](https://cloud.githubusercontent.com/assets/16747/23659092/056dbf2e-0313-11e7-8d12-d7cb1c7ea4e9.png)

Does the link for test and readme not show as it does in this image when you are on a submission page?

Can you capture an image of what you are seeing, and what you would want?

**Comment by wolf99** [comment]
OMG How did I never see those before?! 😖
Please excuse my blindness 😆
