### ISSUE TITLE
Label of a language when archived differs from its active entries on profile page

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3399]
Yesterday I searched my profile for submissions in the xcsharp track by doing a search in my browser for "c#" literally, this only found one entry, `bob`, it was in the table of active submissions.

Since I had more folders in my local exercism-dir, I searched again for the exercise names instead and found the row labeled "Csharp" in the table of archived submissions.

The label used for a language should be the same in both tables.

Maybe other tracks are affected as well?

**Comment by NobbZ** [comment]
I skimmed my own profile and found these:

| track | active label | archived label |
|:-:|:--|:--|
| `xlfe` | Lisp Flavoured Erlang (LFE) | Lfe |
| `xcpp` | C++ | Cpp |

**Comment by kytrinyx** [comment]
I bet we're doing some sort of capitalization of the slug on the archived label instead of using the name of the language.

**Comment by kytrinyx** [comment]
Indeed. Submitting a fix for this one in a moment.
