### ISSUE TITLE
Add documentation about CLI completion script

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3402]
We have bash and zsh completion scripts for the command-line client, but these are only documented on the stand-alone CLI site. (http://cli.exercism.io/)

We need to add something to the main CLI page on the site http://exercism.io/cli

The route for `/cli` is in `app/routes/static.rb`.

**Comment by Insti** [comment]
Resolved in #3415

**Comment by Stigjb** [comment]
There is no information about completion scripts on the current https://exercism.io/cli, can this issue be reopened?
