### ISSUE TITLE
Where does documentation live?

### ISSUE THREAD

**Issue by IanWhitney** [exercism/exercism.io#3412]
I'm working on documenting a new feature. @kytrinyx suggested I put it into the [docs folder of this repo](https://github.com/exercism/exercism.io/tree/master/docs)

However, much of the content of that folder seems to be duplicated in [x-common's contributing guide](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md)

What are the best practices for adding docs? Is there a way we can reduce the duplication and put all the docs in one place?

-------

Update: we've decided to create a single documentation repository for all organization-wide / project-wide documentation.

**TODO**

- [x] create an `exercism/docs` repository
- [x] create a tracking issue in the docs repository for this project https://github.com/exercism/docs/issues/2

**Comment by kytrinyx** [comment]
I'm hoping to get rid of the duplication in x-common's contributing guide.

We used to have a separate documentation site, but that wasn't working very well for us. Maybe a separate documentation _repo_ would be a good idea?

**Comment by jtigger** [comment]
Love the central documentation repo idea!  One stop shop!

**Comment by IanWhitney** [comment]
@kytrinyx what would need to happen to remove document duplication? Is it just a matter of consolidating everything into one repo, or are there build-automation steps that would also have to happen?

**Comment by kytrinyx** [comment]
OK, one stop shop it is. I don't think there are any build-automation steps, but there will be broken links in various places.

I will edit the original issue with a suggested TODO list.

**Comment by kytrinyx** [comment]
Ok, this issue is superseded by the tracking issue in https://github.com/exercism/docs/issues/2
