### ISSUE TITLE
Track each user's client version, and notify when there are updates

### ISSUE THREAD

**Issue by nilbus** [exercism/exercism.io#3416]
Users generally aren't updating their exercism client (cli). Consider tracking each user's most recently used client version and providing a dismissable flash notice when the cli version is not the latest.

Open questions:
1. what is the best way to track the latest client releases
2. how notice dismissal fits in with this proposed API

### Proposed API

```ruby
module Exercism
  class ClientVersion
    attr_reader :user

    def initialize(user:)
      …
    end

    def notice_when_client_outdated
      "(some message to the user)" if outdated? && !dismissed_latest?
    end

    def record_client_version(request:)
      …
    end

    def dismiss_notice!
      …
    end

    def outdated?
      …
    end

    def dismissed_latest?
      …
    end
  end
end
```

### New `User` fields

- client_version_in_use
- client_version_in_use_last_seen_at
- client_version_update_notified
- client_version_update_notification_dismissed_at

### Proposed usage

```ruby
# for API calls (ExercismAPI::Routes::Core),
# which should have the client version in an HTTP header
after do
  client_version = ClientVersion.new(user: current_user)
  client_version.record_client_version(request: request)
end
```

```ruby
# for app pages (Routes::Core)
after do
  client_version = ClientVersion.new(user: current_user)
  flash.now[:notice] ||= client_version.notification_when_client_outdated
end
```

**Comment by kytrinyx** [comment]
This is an _excellent_ idea.

> what is the best way to track the latest client releases

I think probably the releases API: https://developer.github.com/v3/repos/releases/#get-the-latest-release

We could check that once an hour or once a day or something, and check the header that comes in against that value.

> how notice dismissal fits in with this proposed API

I'm not sure. My first thought is to track

- their currently installed version
- when it was last reported
- the CLI version that they've been notified about
- when they dismissed the notification

And then if there's a release that is newer than the latest one they were notified about, we could update the version and reset _dismissed at_ to null.

**Comment by nilbus** [comment]
For these, fields on the `users` table seem appropriate:

- `client_version`
- `client_version_reported_at`
- `client_version_notified`
- `client_version_notification_dismissed_at`

**Comment by kytrinyx** [comment]
> For these, fields on the users table seem appropriate

Yeah, that works for me.

**Comment by kytrinyx** [comment]
- `client_version_reported_at` - maybe `client_version_last_seen_at`?
- `client_version_notified` - I'm worried that we'll get confused since `client_version` refers to two different things. How about something like `newer_client_notified` and `newer_client_dismissed_at`?

**Comment by nilbus** [comment]
Are the two things you're referring to the `client_version` field on User, and the `ClientVersion` class?

**Comment by nilbus** [comment]
Oh, I see now… it's the client version they're *using*, and the client version that's *available*.

**Comment by nilbus** [comment]
I like the idea of having a common prefix, making these obviously grouped. If there aren't names that make sense with a common prefix, perhaps this should become a separate table that gets joined to users.

How about these? *in_use* and _update_ should make it clear what thing's version is being tracked.

- `client_version_in_use`
- `client_version_in_use_last_seen_at` 👍  Your suggestion is good.
- `client_version_update_notified`
- `client_version_update_notification_dismissed_at`

**Comment by kytrinyx** [comment]
> How about these? `in_use` and `update` should make it clear what thing's version is being tracked.

Yes! Those are great. (Naming is hard!)

**Comment by nilbus** [comment]
@kotp I'll make sure this works without javascript when I implement it in a week or two.

**Comment by kotp** [comment]
We really probably should know the number of people that are interacting with the older client.  If this is unknown, as soon as they are using it.  The client should report this, not the website.  I think that it does not matter until they go to use the exericism client.

Not saying that the current notification is wrong, but saying that it should be the client that is notifying, because that is where the problem is.

**Comment by kytrinyx** [comment]
I'm not sure where we are with this, but we talked about using the HTTP header that the client sends in the submit request to track which client they submit with.

**Comment by kytrinyx** [comment]
What's the next step on this?

**Comment by nilbus** [comment]
I think we have a good API and fields for tracking the information needed to notify people about updates in a way that can be dismissed. The next step is to build it.

I planned on starting on this after accomplishing a couple other things (experiment reporting, history starring), but this is open for anyone else to work on, if there's interest.

**Comment by nilbus** [comment]
Proposed API updated in the issue description.

**Comment by nilbus** [comment]
> I'm not sure where we are with this, but we talked about using the HTTP header that the client sends in the submit request to track which client they submit with.

For documentation purposes, it's the User-Agent header that contains the version. E.g.

    User-Agent: github.com/exercism/cli v2.4.0 (darwin/amd64)

**Comment by nilbus** [comment]
After doing some planning for this feature, I came to a new realization. With people using the [gui client][gui] now, there's more than one client version that we should track. Rather than attempting to track an arbitrary number of clients or track only the cli and leave gui/other users out, I'm coming to the conclusion that each client should track its own updates. Furthermore, not all exercism.io users even want to submit solutions any more (e.g. track maintainers, reviewers) and may not care about client updates. Providing update notifications in the client delivers this information to the relevant users at a relevant time, when they're using the client.

[gui]: https://github.com/exercism/gui

A partial implementation of this feature has already been shipped and should be reverted. @kytrinyx  Unless you disagree with the direction I'm going here, I'll open a pull request to roll back the partial implementation. Let me know if you'd like me to open issues in exercism/cli and exercism/gui to add this feature to those projects' roadmaps. I don't currently plan to implement this feature.

**Comment by kytrinyx** [comment]
The catch-22 with this is that they'll never see the message unless they upgrade to a version of the client that has this functionality. Right now that's probably about 130k people.

**Comment by nilbus** [comment]
You're absolutely right. What do you think about this approach?

1. Add the update-aware feature to cli.
2. Use the existing implementation, and reset everyone's notification acknowledgements.
3. Remove the feature flag check surrounding the implementation (for clean-up), and keep the feature as-is in exercism.io for a while.
4. (someday maybe) Remove the update notification feature from exercism.io.

**Comment by kytrinyx** [comment]
@nilbus this sounds like a good plan.

**Comment by nilbus** [comment]
I believe this is obsoleted by nextercism.
