### ISSUE TITLE
Readme for Bob exercise has incorrect responses (Swift)

### ISSUE THREAD

**Issue by vipuldelwadia** [exercism/exercism.io#3418]
Readme has `Whoa, chill out!` but tests expect `Woah, chill out!`.
Readme has `Fine. Be that way!` but tests expect `Fine, be that way.`

**Comment by kytrinyx** [comment]
Would you please open this issue in https://github.com/exercism/xswift ?

There's a canonical data file here that can be used to update the tests to match what other languages do: https://github.com/exercism/x-common/blob/master/exercises/bob/canonical-data.json

**Comment by vipuldelwadia** [comment]
Looks like there is already an issue: https://github.com/exercism/xswift/issues/255, my apologies

**Comment by kytrinyx** [comment]
Thanks @vipuldelwadia
