### ISSUE TITLE
GradeShool Test may be inappropriately

### ISSUE THREAD

**Issue by drinkingcoder** [exercism/exercism.io#3419]
"
A set stores distinct values of the same type in a collection with no defined ordering. You can use a set instead of an array when the order of items is not important, or when you need to ensure that an item only appears once.
 "
                                    - introduced by apple developer

[Doc Address](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/CollectionTypes.html)

But I have to return [Int:Set<String>] when property sortedRoster is used, which suggested Set can be sorted.

**Comment by NobbZ** [comment]
This issue-tracker is for the website of exercism. Your question/report seems to be related to how the swift-track has its tests, please re-issue your question at [exercism/xswift issues](https://github.com/exercism/xswift/issues).

**Comment by drinkingcoder** [comment]
OK~
