### ISSUE TITLE
Quote a comment does not provide the needed new line

### ISSUE THREAD

**Issue by kotp** [exercism/exercism.io#3425]
It is happening commonly now that we have the fa-reply button, is because the new line is not added when placing the quotation in the text area, the students response gets added to the quotation.

We should not rely on the user knowing to place a new line, but should place a newline for them.

**Comment by kytrinyx** [comment]
This change lives in:

- /app/views/submissions/nit.erb
- /frontend/app/js/script.js

/cc @binoymichael who implemented the original feature

**Comment by krypten** [comment]
Hi, Is it open for new contributors also? I want to work on this issue.

**Comment by kytrinyx** [comment]
@krypten Absolutely! If you run into any trouble with it, feel free to jump into the https://gitter.im/exercism/dev chatroom, and someone there should be able to help you out.

**Comment by krypten** [comment]
@kytrinyx Sure, I will start working on it.

**Comment by krypten** [comment]
@kotp @kytrinyx Would not be able to work on this issue anymore. I got a lot work from office. Feel free to assign to this issue to anyone.

**Comment by Insti** [comment]
That's fine @krypten, thanks for letting us know.

**Comment by clarammdantas** [comment]
Hi! :)
Can I work on this bug?

**Comment by Insti** [comment]
Sure @clarammdantas, good luck!
Let us know if you have any questions, either here or in the [dev chat room](https://gitter.im/exercism/dev)
