### ISSUE TITLE
Can't find how to search for a team

### ISSUE THREAD

**Issue by catherinedevlin** [exercism/exercism.io#3428]
The team page (http://exercism.io/teams/about) tells how to create and manage a team, but not how to find an existing team.

"A public team will appear in search results", it says, but not where to search.

I haven't been able to find it anywhere by navigating the site, or even by googling for it.

Having heard that a team I was interested in existed, and successfully guessing at their name, I was able to guess that the team page would be http://exercism.io/teams/<team name>.  But that was just a lucky guess.

**Comment by catherinedevlin** [comment]
After guessing my team's name and requesting membership, I was redirected to http://exercism.io/teams, which is what I'd been looking for.  But I don't think http://exercism.io/teams is linked to from http://exercism.io/teams/about or from anywhere else I could find.  Also, I'd tried http://exercism.io/teams/ before, but the trailing backslash meant a 404.

**Comment by kytrinyx** [comment]
@catherinedevlin Thanks, yeah this is not good.

I think we should add documentation to the /teams/about page which starts in `app/routes/static.rb`

We might also optionally consider handling trailing slashes for all routes.

**Comment by tejasbubane** [comment]
> We might also optionally consider handling trailing slashes for all routes.

Sinatra [now has an option](https://github.com/sinatra/sinatra/pull/1273/commits/2445a4994468aabe627f106341af79bfff24451e) to ignore the trailing slashes. We should update to `2.0`.

**Comment by kytrinyx** [comment]
Updated to 2.0

@tejasbubane would you have time to submit a fix to use the "ignore trailing slashes" option?

**Comment by tejasbubane** [comment]
@kytrinyx Done - #3509.

**Comment by kytrinyx** [comment]
❤️ Appreciate it! And merged :-)

**Comment by HarrisonMc555** [comment]
@kytrinyx I just added some documentation to resolve this issue. This is my first pull request (ever!) so let me know if I'm doing this right :smile:

I wasn't able to figure out which, if any, tests I was supposed to run myself before I pushed. However, I basically only added some html so I'm fairly confident everything is fine. It looks good on my local dev environment. If there were some tests I was supposed to run locally, let me know (I saw Rubocop but didn't have time to get it set up this morning).

**Comment by HarrisonMc555** [comment]
I just noticed that there's also a blurb about teams at http://exercism.io/account as well. Should I add something there, too?

**Comment by kytrinyx** [comment]
@HarrisonMc555 This looks great! Also, Travis CI runs the tests, so when in doubt... just wait for Travis to tell you what you did wrong :-)

I don't think we need anything in the account page.

Congrats on your first (ever!) pull request :sparkles: :heart: :sparkles:
