### ISSUE TITLE
Add help requests to the stats page

### ISSUE THREAD

**Issue by behrtam** [exercism/exercism.io#3430]
Would it be possible to add help requests to the stats page? http://exercism.io/stats/python

I think help requests can be a good indicator that there are problems with an exercise, or that the position in the track might be wrong, etc.

**Comment by kytrinyx** [comment]
That sounds like an excellent idea.

**Comment by kytrinyx** [comment]
@behrtam would you mind editing the issue to contain enough context for someone to complete the work on it?

- why is it important?
- what needs to be done?

The stats route lives in app/routes/stats.rb
