### ISSUE TITLE
Running C++ tests

### ISSUE THREAD

**Issue by DolevEfr** [exercism/exercism.io#3436]
Hello good people, 
I started out with the C++ exercises, and I must say that your documentation is really good for setting everything up (at least on linux).
The only thing missing there (and in the readme) is how to run the tests...
I'm new to C++ and developing using the terminal, and I can't figure out how to run the tests.

The first time I run 'make'- it gave me compile-time errors in the tests file, but once I finished declaring the essential namespaces and functions- it just compiles my binary without giving me any feedback regarding the tests (I know for sure I don't pass the first test).

**Comment by kytrinyx** [comment]
@DolevEfr Thanks! We should absolutely see about getting that fixed. Would you mind opening an issue in the https://github.com/exercism/xcpp repository? That should get this in front of the people who are best suited to take care of this.

There's some information here: http://exercism.io/languages/cpp/tests

I suggest using the 'HINTS.md' file in the first exercise to help document how to run the tests (or where to find the information about running the tests). The documentation about how to update the exercise READMEs is here: https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/fixing-exercise-readmes.md

**Comment by kotp** [comment]
Issue moved to [exercism/xcpp #115](https://github.com/exercism/xcpp/issues/115) via [**ZenHub**](https://www.zenhub.com/)
