### ISSUE TITLE
Cannot upgrade to cli-2.4.0 on Windows 8.1

### ISSUE THREAD

**Issue by AlbertMoscow** [exercism/exercism.io#3439]
Cannot upgrade to cli-2.4.0 on Windows 8.1 due to the following message:

"open C:\ProgramData\chocolatey\lib\exercism-io-cli\tools\exercism.exe: The process cannot access the
 file because it is being used by another process."

My computer has just been turned on.

![cannot upgrade to cli-2 4 0 on windows 8 1 due to the following message - 1](https://cloud.githubusercontent.com/assets/3895816/24345330/49d4ffe0-12d8-11e7-8288-03d4df789d6a.png)

![cannot upgrade to cli-2 4 0 on windows 8 1 due to the following message - 2](https://cloud.githubusercontent.com/assets/3895816/24345339/4e6c4626-12d8-11e7-82c7-331dc2c12726.png)

**Comment by NobbZ** [comment]
Also reported at exercism/cli#381

**Comment by kytrinyx** [comment]
I'm going to close this as a duplicate, in favor of exercism/cli#381. If you have any further details to add, please do so there.

Thanks!

**Comment by kytrinyx** [comment]
@AlbertMoscow In the meanhile you should be able to replace the binary per the original install instructions: http://exercism.io/cli/windows
