### ISSUE TITLE
Put /cli and /gui routes under a namespace

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3442]
We need to be able to add a '/gui' URL to document the graphical user interface for Exercism (http://github.com/exercism/gui), and I'd like to group this together with /cli under a shared namespace.

'/clients' would make sense to me.

`/cli` is defined in app/routes/static.rb

**Comment by peeshar** [comment]
ขอร้อง

**Comment by aklap** [comment]
Hi, I'd like to take this one on! Just to be clear, you'd like to move out the /cli routes into a separate module and file rather than using the Sinatra::Namespace extension, right?

**Comment by kytrinyx** [comment]
Sweet, thanks @aklap! That's a good question.

I don't even need it to move into a separate file or module, it could stay in the file where it is, making it so that the routes have an extra bit before the '/cli'. E.g. '/clients/cli'.

And then updating all the references to it so it points to the right place.

**Comment by aklap** [comment]
Ah, okay, I see what you're saying! Thanks for clarifying.

**Comment by morrme** [comment]
i feel like i'm a fake "stale issue" bot lol but this one looks like it can be closed too.

**Comment by kytrinyx** [comment]
Ah, you're right (about this being closed, not about you being a bot :sparkles:) :)
