### ISSUE TITLE
Delphi contributed code is not receiving highlighting.

### ISSUE THREAD

**Issue by kotp** [exercism/exercism.io#3450]
Rouge is currently "Close enough" in version that I would expect it to work, but Rouge current version is "2.0.7" and we are using "2.0.5".

This could be pretty straight forward... map "Delphi" to "Pascal" in `lib/exercism/syntax_highlighter.rb` and change the Gemfile for the later version of Rouge.

**Comment by kotp** [comment]
Oh, Markdown for comments does highlight using `pascal` but does nothing, as expected, for `delphi`.

**Comment by kytrinyx** [comment]
Yeah, mapping it to pascal should work. We should update rouge, too.

**Comment by kotp** [comment]
This is fine that it is closed, the upgrade for Rouge should happen as it happens regarding #3452
