### ISSUE TITLE
submitting error !!!

### ISSUE THREAD

**Issue by ujjwal-git** [exercism/exercism.io#3456]
I am getting error as below :
--------------------------------------------------------------------
$ exercism submit ~/exercism/exercises/hello.cpp
2017/04/09 21:17:40 unable to submit - Bad path to exercise file.

You're trying to submit a solution file from inside your exercises directory,
but it looks like the directory structure is something that exercism doesn't
recognize as a valid file path.

First, make a copy of your solution file and save it outside of
/home/ujjwal/exercism/exercises

Then, run "exercism fetch". Move your solution file back to the correct
exercise directory for the problem you're working on. It should be somewhere
inside /home/ujjwal/exercism/exercises

If you are having trouble, you can file a GitHub issue at (https://github.com/exercism/exercism.io/issues)
-------------------------------------------------------------------------------------
My file name is " hello_world.cpp " ,located inside the specified directory .
I am a new to exercism and git .

**Comment by tejasbubane** [comment]
> $ exercism submit ~/exercism/exercises/hello.cpp


> My file name is " hello_world.cpp " ,located inside the specified directory .
> I am a new to exercism and git .

@ujjwal-git Is the filename `hello.cpp` or `hello_world.cpp`?

**Comment by ujjwal-git** [comment]
@tejasbubane 
Thanks for your concern ! 
the issue has been fixed now.
Actually it needed to specify full path name of file.

**Comment by tejasbubane** [comment]
Glad you got it sorted @ujjwal-git
