### ISSUE TITLE
Rikki refinement suggestion

### ISSUE THREAD

**Issue by cleeverz** [exercism/exercism.io#3458]
Any time you submit an exercise on the ruby track where a conditional is used while iterating through a collection, you get this feedback from rikki:

>"Whenever you are looping through a collection and find yourself writing a conditional (if or unless) nested inside of the loop, take a moment to look through the available enumerable methods.
There are some very handy ones that might let you simplify."

However, there are some exercises in which you are meant to implement your own, low level solution to a problem that one of these existing methods already has solved.  In these cases this feedback is inapplicable at best, or could prove very confusing at worst, given the experience of a particular submitter. 

I suggest making a change to rikki that would repress this feedback in these cases. 

A couple of possibilities:
 
-Make a change to rikki so that this feedback is not offered in cases where both a module and class are declared in the code. (Though I don't think this would cover all cases, and would probably be very clunky to extend for use on other language tracks.)

-Add a flag checking system where contributors could flag certain exercises according to what kind of rikki feedback applies that rikki could use to repress certain feedback in certain cases. 

I haven't worked through enough of the other language tracks yet to know if rikki is even used on them, so I don't know if this applies beyond the ruby track.

**Comment by mhelmetag** [comment]
So the great thing about rikki is that, currently, each supported language track has it's own "checker". The ruby one included. So this shouldn't be that hard to implement over in [rikki-ruby-analyzer](https://github.com/exercism/rikki-ruby-analyzer).

The only issue I can see is that I think rikki doesn't send info about the exercise name... so... we. currently, would need to add that before being able to handle certain exercises differently on the ruby side. I can open an issue for that in [rikki](https://github.com/exercism/rikki).

Could I move this issue over to rikki-ruby-analyzer? As I think it's more relevant there...

> In these cases this feedback is inapplicable at best, or could prove very confusing at worst, given the experience of a particular submitter.

Totally agree.

> > Add a flag checking system where contributors could flag certain exercises according to what kind of rikki feedback applies that rikki could use to repress certain feedback in certain cases.

Really cool idea. I'm not sure when we could look into applying this but probably after refactoring rikki a bit to make it easier to integrate "checkers" for other languages/tracks.

> I haven't worked through enough of the other language tracks yet to know if rikki is even used on them, so I don't know if this applies beyond the ruby track.

Rikki is used to varying degrees on go, ruby and crystal with the idea to spread it to more tracks.

**Comment by cleeverz** [comment]
Cool. Thanks for the reply!  And yes, moving the ticket to rikki-ruby-analyzer sounds good to me.

**Comment by mhelmetag** [comment]
Closing out in favor of https://github.com/exercism/rikki-ruby-analyzer/issues/5

**Comment by cleeverz** [comment]
Awesome! Closing.
