### ISSUE TITLE
Anchor links broken in setting-up-local-development.md

### ISSUE THREAD

**Issue by aklap** [exercism/exercism.io#3459]
The anchor links were broken in [`exercism.io/docs/setting-up-local-development.md`](https://github.com/exercism/exercism.io/blob/master/docs/setting-up-local-development.md) because there was an extra '-' character in between the words 'exercism' and 'io' in the slugged filename. 

Removing the '-' fixes the anchor links.

**Comment by Insti** [comment]
Thanks @aklap !
