### ISSUE TITLE
Push footer to bottom of page

### ISSUE THREAD

**Issue by rootulp** [exercism/exercism.io#3465]
Hi! I have an idea to improve the appearance of exercism.io
I think the site would look better if the footer was pushed to the bottom of the page. Screenshots to explain:

The current notifications page has a lot of whitespace below the footer:
<img width="1440" alt="screen shot 2017-04-17 at 4 30 16 pm" src="https://cloud.githubusercontent.com/assets/3699047/25093754/8e158ea4-238b-11e7-9fe2-62e191eeb49d.png">

If we push the footer to the bottom:
<img width="1440" alt="screen shot 2017-04-17 at 4 32 05 pm" src="https://cloud.githubusercontent.com/assets/3699047/25093759/95ecf5b8-238b-11e7-9cec-5bdfc39fdbc1.png">

Thoughts? I did this by modifying the `margin-top` property on the footer but I realize this isn't the correct approach. I imagine the correct technique uses some type of CSS `float` property or something else.
<img width="1435" alt="screen shot 2017-04-17 at 4 34 14 pm" src="https://cloud.githubusercontent.com/assets/3699047/25093804/c562ed7a-238b-11e7-88f0-b88e31bcf5f6.png">

**Comment by kytrinyx** [comment]
I think that sounds like a great idea. I don't know CSS, so your guess is better than mine. I have no problem accepting what you think might be a hack, if you like :-)

**Comment by arumoy-shome** [comment]
@rootulp bootstrap's [`navbar-fixed-bottom`](http://getbootstrap.com/components/#navbar-fixed-bottom) should do the trick. I would be happy to push up a PR if you haven't started on this already. :)

**Comment by rootulp** [comment]
@arumoy-shome I haven't started on this - please go ahead with your PR! Excited to see this fix.
