### ISSUE TITLE
Add information about the Windows installer for the CLI

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3466]
There's an installer for Windows, which simplifies the instructions on http://exercism.io/clients/cli/windows

The actual text is defined in `x/docs/md/cli/windows.md`.

The installer lives in https://github.com/exercism/windows-installer, instructions for using it are defined in the README of that repo.

**Comment by Raptorian** [comment]
Would linking the installer be fine? Or do you want the information from the README page of the installer documentation on this page? If linking the installer is fine, I have simple edit as a pull request up: #3481
