### ISSUE TITLE
Bugsnag is not capturing all errors.

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3469]
I've suspected this for a while, but now have some evidence.

A screenshot of an error with a 'submitted to bugsnag message': https://github.com/exercism/exercism.io/issues/3455#issuecomment-295426007

A failure to find mention of the error in Bugsnag: https://github.com/exercism/exercism.io/issues/3455#issuecomment-295450923

It is working sometimes:
![20170420 - bugsnag events](https://cloud.githubusercontent.com/assets/5096681/25213978/da637fe0-2594-11e7-9e16-e1088545038a.png)
_screenshot from Bugsnag dashboard (which requires a login)_

But mostly seems to only catch GitHub being down.

And does NOT work when explicitly triggered by: http://exercism.io/bork see: https://github.com/exercism/exercism.io/blob/master/app/routes/static.rb#L56

References: 
Bugsnag Sinatra integration guide: 
https://docs.bugsnag.com/platforms/ruby/sinatra/

**Comment by allcentury** [comment]
I went through the changelog and nothing jumped out about this issue.  I do see we explicitly call bugsnag on some errors we rescue (which is normal) however, as your link mentions @Insti I don't see that we tell Sinatra/BugSnag to raise unhandled exceptions.

That should only require a few lines of code:

```ruby
use Bugsnag::Rack

set :raise_errors, true
set :show_exceptions, false
```

I'm going to write a few tests and see if Bugsnag get's called...

**Comment by allcentury** [comment]
Ok, I tested this on master and I can step through the bugsnag code (and watch it send the error) when I simply do this:

```ruby
module ExercismWeb
  module Routes
    class Main < Core
      get '/' do
        raise RuntimeError.new 'AHHH'
        erb :"site/index"
      end
      ...
```

I'm giving a fake API key to bugsnag but it's returning a 200 with a body of 'OK'.  🤷‍♂️ Without access to bugsnag I'm probably not much more help.

**Comment by kytrinyx** [comment]
Thanks both of you for confirming that this is a problem, and providing a starting point for debugging!

I'll do a git bisect on this locally next week when I'm back home to see if we broke it somewhere along the way, or if this is a change to the BugSnag APIs.

**Comment by Insti** [comment]
> I tested this on master and I can step through the bugsnag code (and watch it send the error) when I simply do this.

This is master without any changes?

I suspect it's something to do with some kind of difference between environments,  development  and production

https://github.com/exercism/exercism.io/blob/ce2fe970ccd90993c5822147ca429ac3241d2937/app/routes/core.rb

Sets :show_exceptions differently.

Are there any other places where the different environments might be setting things differently? Some Sinatra/Rack defaults?

But it's probably good if Bugsnag is NOT notified in development mode.

Glad you're looking into this @allcentury :heart:

**Comment by allcentury** [comment]
@Insti I did have to turn off `show_exceptions`, I edited my previous comment with that as well - thanks for calling that out.  The Bugsnag gem does log through it's notify process (to STDOUT), so perhaps another place to start debugging is checking for logs for other exceptions and seeing if Bugsnag is logging as well.  

I changed the bugsnag log level from 2 to 0 via:

```ruby
Bugsnag.configure do |config|
  config.release_stage = ENV["RACK_ENV"]
  config.notify_release_stages = %w(production development)
  config.api_key = ENV['BUGSNAG_API_KEY']
  config.project_root = File.expand_path("../..", __FILE__)
  config.logger.level = 0
end
```

and I can see more in the logs with my local exception:

```bash
07:59:14 web.1  | started with pid 39780
07:59:16 web.1  | I, [2017-04-21T07:59:16.052981 #39780]  INFO -- : ** [Bugsnag] Bugsnag exception handler 4.0.0 ready, api_key=aaaaaaaaaaaaaaaaaaaaaaaaafffffff
07:59:16 web.1  | Puma 2.15.3 starting...
07:59:16 web.1  | * Min threads: 0, max threads: 16
07:59:16 web.1  | * Environment: development
07:59:16 web.1  | * Listening on tcp://localhost:4567
07:59:39 web.1  | 2017-04-21 07:59:39 - RuntimeError - AHHH:
07:59:39 web.1  | 	/Users/anthonyross/projects/exercism.io/app/routes/main.rb:5:in `block in <class:Main>'

STACKTRACE OMITTED

07:59:39 web.1  | I, [2017-04-21T07:59:39.714009 #39780]  INFO -- : ** [Bugsnag] Notifying https://notify.bugsnag.com of RuntimeError from api_key aaaaaaaaaaaaaaaaaaaaaaaaafffffff
```

We coudl run production with a lower log level for a bit and see if anything jumps out?

**Comment by Insti** [comment]
What about updating the Bugsnag gem?

Exercism seems to be using 4.0.0: https://github.com/exercism/exercism.io/blob/master/Gemfile.lock#L29

But the latest version seems to be 5.3.1:https://github.com/bugsnag/bugsnag-ruby/releases
(Maybe there is a changelog that says something interesting.)

**Comment by allcentury** [comment]
Right - I mentioned in my first comment about looking through the changelog.  A possibly related issue I noticed was this PR: https://github.com/bugsnag/bugsnag-ruby/pull/307.  On our version of Bugsnag if we're not sending a stacktrace through, Bugsnag is swallowing the exceptions (but still responding with a 200).

**Comment by Insti** [comment]
> On our version of Bugsnag if we're not sending a stacktrace through, Bugsnag is swallowing the exceptions (but still responding with a 200).

That sounds a lot like our problem.

Would you be able to:

a) Upgrade the Bugsnag gem and check that Exercism still works & submit a PR
and/or
b) Verify whether the stack trace is being sent through by the request?

**Comment by allcentury** [comment]
I added the PR @Insti .  I'm seeing stacktraces locally (with the same setup as https://github.com/exercism/exercism.io/issues/3469#issuecomment-295908504).  Bugsnag is planning to send a large JSON payload that looks like this...


```bash
12:57:39 web.1  |          {"lineNumber"=>15,
12:57:39 web.1  |           "code"=>{"12"=>"    end", "13"=>"", "14"=>"    def call(env)", "15"=>"      status, headers, body = @app.call(env)", "16"=>"      headers = HeaderHash.new(headers)", "17"=>"", "18"=>"      if !STATUS_WITH_NO_ENTITY_BODY.include?(status.to_i) &&"},
12:57:39 web.1  |           "file"=>"gems/rack-1.6.5/lib/rack/content_length.rb",
12:57:39 web.1  |           "method"=>"call"},
12:57:39 web.1  |          {"lineNumber"=>541,
12:57:39 web.1  |           "code"=>{"538"=>"", "539"=>"      begin", "540"=>"        begin", "541"=>"          status, headers, res_body = @app.call(env)", "542"=>"", "543"=>"          return :async if req.hijacked", "544"=>""},
12:57:39 web.1  |           "file"=>"gems/puma-2.15.3/lib/puma/server.rb",
12:57:39 web.1  |           "method"=>"handle_request"},
12:57:39 web.1  |          {"lineNumber"=>388,
12:57:39 web.1  |           "code"=>{"385"=>"        close_socket = true", "386"=>"", "387"=>"        while true", "388"=>"          case handle_request(client, buffer)", "389"=>"          when false", "390"=>"            return", "391"=>"          when :async"},
12:57:39 web.1  |           "file"=>"gems/puma-2.15.3/lib/puma/server.rb",
12:57:39 web.1  |           "method"=>"process_client"},
12:57:39 web.1  |          {"lineNumber"=>270,
12:57:39 web.1  |           "code"=>
12:57:39 web.1  |            {"267"=>"          client.close",
12:57:39 web.1  |             "268"=>"        else",
12:57:39 web.1  |             "269"=>"          if process_now",
12:57:39 web.1  |             "270"=>"            process_client client, buffer",
12:57:39 web.1  |             "271"=>"          else",
12:57:39 web.1  |             "272"=>"            client.set_timeout @first_data_timeout",
12:57:39 web.1  |             "273"=>"            @reactor.add client"},
12:57:39 web.1  |           "file"=>"gems/puma-2.15.3/lib/puma/server.rb",
12:57:39 web.1  |           "method"=>"block in run"},
12:57:39 web.1  |          {"lineNumber"=>106,
12:57:39 web.1  |           "code"=>{"103"=>"          end", "104"=>"", "105"=>"          begin", "106"=>"            block.call(work, *extra)", "107"=>"          rescue Exception", "108"=>"          end", "109"=>"        end"},
12:57:39 web.1  |           "file"=>"gems/puma-2.15.3/lib/puma/thread_pool.rb",
12:57:39 web.1  |           "method"=>"block in spawn_thread"}]}],
12:57:39 web.1  |     "severity"=>"error",
12:57:39 web.1  |     "device"=>{"hostname"=>"Anthonys-MacBook-Pro.local"},
12:57:39 web.1  |     "metaData"=>{"app"=>{"version"=>"unknown"}}}]}
```

Let's test this theory and see if the upgrade solves our issue(s).

**Comment by Insti** [comment]
Bugsnag is still not being notified by http://exercism.io/bork so I suspect the problem still exists.

**Comment by kytrinyx** [comment]
I haven't deployed.

**Comment by Insti** [comment]
That would explain it :)
I saw there was a recent deploy but didn't realise it didn't include these changes.

**Comment by kytrinyx** [comment]
Sorry about that. I deploy first thing, and then sometimes I have a few minutes before work to go through a few PRs. Typically that goes out in the next deploy the next morning.

**Comment by kytrinyx** [comment]
This is deployed, and is still not reporting.

**Comment by Insti** [comment]
@kytrinyx is the next thing to try increasing the log level as suggested in: https://github.com/exercism/exercism.io/issues/3469#issuecomment-296173131 ?

cc: @allcentury

**Comment by kytrinyx** [comment]
Increasing the log level did not cause reporting to happen.

If I add a BUGSNAG_API_KEY locally it reports.

**Comment by kytrinyx** [comment]
In production with a lower log level we do get the following information:

```
2017-05-27T15:21:28.108188+00:00 app[web.1]: I, [2017-05-27T15:21:28.108099 #4]  INFO -- : ** [Bugsnag] Notifying https://notify.bugsnag.com of NilClass  
```

Which presumably Bugsnag would ignore.

So perhaps `$ERROR_INFO` is nil in production.

**Comment by kytrinyx** [comment]
Confirmed. `$ERROR_INFO` in production is `nil`, despite the fact that we are inside of an `error 500` block.

**Comment by kytrinyx** [comment]
It appears that "English" is not turned on in production. By explicitly requiring "English" bugsnag starts reporting. I'm submitting a PR.

**Comment by Insti** [comment]
Awesome, great detective work. Thanks for getting to the bottom of this.
Bugsnag errors have started flowing, so it looks like it's working now.

**Comment by kytrinyx** [comment]
> Bugsnag errors have started flowing

:-) Yeah! Now we have other problems!
