### ISSUE TITLE
Remove LetsEncrypt temporary route

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3470]
https://github.com/exercism/exercism.io/commit/eadc88d3e10bbee4768224744f63b1b8f969cdd2 added the certificate challenge required to generate the LetsEncrypt SSL certificate. 

This can be removed once the certificate has been generated.

References:

https://letsencrypt.readthedocs.io/en/latest/using.html#webroot
> The webroot plugin works by creating a temporary file for each of your requested domains in `${webroot-path}/.well-known/acme-challenge.` 

https://letsencrypt.readthedocs.io/en/latest/using.html#hooks
> /path/to/http/cleanup.sh
> #!/bin/bash
>   rm -f /var/www/htdocs/.well-known/acme-challenge/$CERTBOT_TOKEN

**Comment by bermannoah** [comment]
Went ahead and removed it, pushed up a PR.
