### ISSUE TITLE
Wrong Version number for Exercism

### ISSUE THREAD

**Issue by wingedearth** [exercism/exercism.io#3471]
I used "brew install exercism to install 2.4.0.
exercism -v returns 2.2.5
I deleted the 2.2.5 directory. I've run brew doctor and brew cleanup. 2.4.0 appears to be the only version I have. But the debug also is telling me that I'm running v2.2.5
**** Debug Information ****
Exercism CLI Version: 2.2.5
Exercism CLI Latest Release: 2.4.0
OS/Architecture: darwin/amd64
Build OS/Architecture darwin/amd64

and so on. How can I set my exercism version to 2.4.0?

**Comment by wingedearth** [comment]
I tried running exercism upgrade and an error was returned: error downloading executable: Get https://api.github.com/repos/exercism/cli/releases/assets/3484980: x509: certificate has expired or is not yet valid

**Comment by kytrinyx** [comment]
Wow, that's totally confusing, and I'm so sorry you're running into it!

What does `which exercism` return?

**Comment by Insti** [comment]
Have you tried running
`exercism update`

**Comment by wingedearth** [comment]
[which exercism] returns the path /Users/[myname]/bin/exercism (which is not where my version of exericsm is stored).

**Comment by wingedearth** [comment]
Hmm...`exercism upgrade` seems to have worked. But I think the underlying issue is that when I tried to reinstall or upgrade using Homebrew, it installed to a different directory than where the active version of exercism is located. In what ways can I resolve the conflict between Homebrew and the active exercism? 

I have Homebrew's copy of exercism in usr/local/Cellar like most other Homebrew installs.

**Comment by Insti** [comment]
try renaming  `/Users/[myname]/bin/exercism` to exercism.disabled and see what happens.

**Comment by wingedearth** [comment]
@Insti - I just renamed exercism to exercism.disabled in that directory. I changed directory to home and then tried running some exercism commands but they still work.

**Comment by wingedearth** [comment]
Maybe now it's somehow reading from the /usr/local/Cellar folder? I can't tell.

**Comment by Insti** [comment]
try: `which exercism` again.

**Comment by Insti** [comment]
I'm around in https://gitter.im/exercism/support for real-time support.

**Comment by wingedearth** [comment]
`which exercism` is now returning /usr/local/bin/exercism

**Comment by Insti** [comment]
Maybe that's where homebrew puts the executable. 
what is the result of  `exercism -v` now?

**Comment by wingedearth** [comment]
2.4.0

**Comment by Insti** [comment]
So is this issue resolved now?

**Comment by Insti** [comment]
(you can probably delete that `exercism.disabled` file now.)

**Comment by wingedearth** [comment]
Getting the right version active is resolved. Figuring out what exercism and homebrew exercism are pointing to and where that can be altered is not.

**Comment by Insti** [comment]
Ok, 

`where exercism` should report all locations it can be found.

But I think you've reached the limit of my homebrew knowledge, so you'll have to wait for someone who knows more about that to see this issue.

**Comment by kytrinyx** [comment]
@wingedearth The problem here is that both the `/usr/local` path and the `~/bin` path are on your PATH, and the order in which they appear in your PATH will decide which of the two binaries gets detected.

I can't figure out how you would have an executable that ended up in the `~/bin` directory.
