### ISSUE TITLE
Dead link exercism.io/cli at exercism.io/how-it-works

### ISSUE THREAD

**Issue by cmccandless** [exercism/exercism.io#3476]
Found under Getting Started ->3. Download and configure [command-line client](http://exercism.io/cli).

I'm guessing this used to point to what is now at exercism.io/clients/cli.

**Comment by Insti** [comment]
Thanks for the report. :heart:

I think this was fixed in https://github.com/exercism/exercism.io/pull/3474 and we're just waiting for the fix to be put live.

**Comment by tejasbubane** [comment]
This has been fixed and deployed.
