### ISSUE TITLE
Reposition remove buttons on Team Management page

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism.io#3477]
The `Manager` section on `http://exercism.io/teams/<your-team-slug>/manage`
Here is how it looks now:

![screen shot 2017-04-24 at 7 53 01 pm](https://cloud.githubusercontent.com/assets/980783/25341864/e50a6882-2927-11e7-8569-08b9707e65dc.png)

It is difficult to tell which remove button is for which user.

The team section on the other hand, is better:

![screen shot 2017-04-24 at 7 47 43 pm](https://cloud.githubusercontent.com/assets/980783/25341895/02d35b76-2928-11e7-93dd-12bbc73f6637.png)

I suggest use same `x` buttons instead of `Remove` and place them to the left of names. Like this:

![screen shot 2017-04-25 at 12 52 07 pm](https://cloud.githubusercontent.com/assets/980783/25373202/535536ee-29b6-11e7-8baa-0d7cdb282be7.png)

The corresponding code is here: https://github.com/exercism/exercism.io/blob/master/app/views/teams/manage.erb#L76-L104

This should be a view-only change and fairly easy to be fixed. Let us know is you face any issues.

**Comment by arumoy-shome** [comment]
I can take this up if nobody else has started on this. :)

**Comment by Insti** [comment]
Should the x be to the left of the profile picture to match what is in the members list?

**Comment by tejasbubane** [comment]
> Should the x be to the left of the profile picture to match what is in the members list?

I thought of this while writing the issue, and I don't mind it either ways. 
But for consistency let's keep it to the left. I will modify the screenshot in the issue.

**Comment by tejasbubane** [comment]
@arumoy-shome Please make a note of the change in issue description. For consistency on the page and proper alignment, lets keep all cross buttons to the left side of text.

**Comment by Smarticles101** [comment]
This should be closed now that the issue is resolved, thanks :grin:

**Comment by tejasbubane** [comment]
Indeed this has been fixed. Thanks @Smarticles101.
