### ISSUE TITLE
Team dropdown shows only member-teams, not manger-teams

### ISSUE THREAD

**Issue by tejasbubane** [exercism/exercism.io#3478]
I am a member (as well as manager)  of `team-X`. For `team-Y`, I am just an manager, not a member.
In the `Teams` dropdown in the header, I can see only `team-X` and not `team-Y`. 

But on my profile page in the `Teams` list, I can see both the teams. The team lists should be consistent at both these places. I should be able to switch to both teams through the dropdown.

**Comment by arumoy-shome** [comment]
I can take this up if no body is pursuing this.

**Comment by bernardoamc** [comment]
That would be awesome @arumoy-shome , thanks for your help! ❤️

**Comment by tejasbubane** [comment]
Go for it @arumoy-shome 👍

**Comment by arumoy-shome** [comment]
@tejasbubane where exactly is this `teams` dropdown located? Also a few screenshots would help to gather a bit more context. Thanks!

**Comment by tejasbubane** [comment]
Sorry for the confusion @arumoy-shome. Here is a screenshot of my profile page:

![screen shot 2017-04-27 at 12 12 02 pm](https://cloud.githubusercontent.com/assets/980783/25471089/076b3740-2b43-11e7-8c12-7723ebabb871.png)


The dropdown is in the header and can be accessed from any page as a quick switch to team. 

A person can just be manager of the team without being a member. The dropdown does not show teams of which I am a manager but not a member.
