### ISSUE TITLE
Exercism fetching exercises that have already been completed. 

### ISSUE THREAD

**Issue by cleeverz** [exercism/exercism.io#3482]
After completing the "beer-song" exercise in the ruby track, I ran exercism fetch and the got exercism responded that the "strain" exercise had been fetched. I had already completed and submitted this exercise. 

Investigating a bit further, I can see a couple other exercises that have been completed are missing from the archive list at http://exercism.io/cleeverz 

Missing: "Trinary" and "Etl".

A couple things that might be contributing factors:

I have previously skipped one exercise: "nth-prime"

I figured out after this occurred that I had already fetched the "bowling" exercise but have yet to submit an iteration.

**Comment by Insti** [comment]
Were the files present on your local system before you ran the fetch?

"ETL" I can see in the 'current' list so it won't be in the archive list.
"Trinary" has been deprecated, so this may be a bug if the website is not showing completed but deprecated exercises.

**Comment by cleeverz** [comment]
The Files were present on my local system, yes. 

The ETL exercise was only showing up in the current list after I posted this issue, because I resubmitted it to get it out of the way.

Got you on the Trinary exercise.

**Comment by cleeverz** [comment]
Come to think of it, should I move this issue to the CLI issues list?

**Comment by Insti** [comment]
Only if you can reproduce it.

**Comment by kytrinyx** [comment]
The problem could be in the CLI, or it could be in the API.

Have you been able to reproduce the problem @cleeverz?

**Comment by cleeverz** [comment]
I will see if I can reproduce this again today or Tomorrow and close it out if I can't.

**Comment by cleeverz** [comment]
I've been unable to reproduce this after several new tries. I think the issue is still out there, but requires a scenario which I  can't pinpoint. Closing for now.

**Comment by kytrinyx** [comment]
Thanks @cleeverz!
