### ISSUE TITLE
Link to `exercism/todo` returns a 404

### ISSUE THREAD

**Issue by arumoy-shome** [exercism/exercism.io#3483]
The link `exercism/todo` on [CONTRIBUTING.md](https://github.com/exercism/exercism.io/blob/master/CONTRIBUTING.md) returns a 404.

![screen shot 2017-04-25 at 11 40 08 pm](https://cloud.githubusercontent.com/assets/6236828/25417304/2a787cbc-2a11-11e7-81b5-a7c09f52b88e.png)

I would be more than happy to push up a fix if someone can provide me with the correct link. 😄

**Comment by Insti** [comment]
The todo repository has been deleted: https://github.com/exercism/discussions/issues/135

That line needs to either be reworded or removed.

**Comment by arumoy-shome** [comment]
> That line needs to either be reworded or removed.

@Insti Are there any alternative locations where issues are curated? If not, I can 🔥 the line.

**Comment by Insti** [comment]
We tag issues that we think are good for starting out as [good first patch](https://github.com/search?q=org%3Aexercism+is%3Aissue+is%3Aopen+label%3A%22good+first+patch%22)

**Comment by arumoy-shome** [comment]
> We tag issues that we think are good for starting out as good first patch

@Insti How can I do this? I don't seem to have that option on the right.

**Comment by Insti** [comment]
You need to have the right permissions on the repository to do the tagging (e.g. by being an admin or whatever github calls them.)

**Comment by RaptorRCX** [comment]
Did a pull request to move the info about good first patch to replace the original sentence + link.

**Comment by arumoy-shome** [comment]
@RaptorRCX thanks for taking care of this, closing this issue.
