### ISSUE TITLE
Inconsistency in ruby version for existing contributors

### ISSUE THREAD

**Issue by arumoy-shome** [exercism/exercism.io#3484]
- currently in [bin/setup](https://github.com/exercism/exercism.io/blob/master/bin/setup#L9) we check if a `.ruby-version` file already exists, if not, we then copy the `.ruby-version.example` file over
- this approach however leads to inconsistency in the ruby version of existing contributors
- if we change the ruby version in `.ruby-version.example`, this change is never reflected for existing contributors since they already have a `.ruby-version` file.
- the copy procedure for the [.env](https://github.com/exercism/exercism.io/blob/master/bin/setup#L14) file shares the same problem.

**FIX:** I propose that we remove the check and directly copy over the files.

I will be more than happy to take this up. Thoughts?

**Comment by Insti** [comment]
No, don't unconditionally overwrite existing files.

> this approach however leads to inconsistency in the ruby version of existing contributors

What are the implications of this?
How does it lead to inconsistency?
Why are existing contributors re-running the setup script?

**Comment by arumoy-shome** [comment]
@Insti thanks for the questions.

I faced this issue just now, I had cloned the exercism.io repo a few months back and must have run the setup script. Back then, the ruby version specified in `.ruby-version.example`was `2.2.2`. I got pulled into other stuff and didn't get around the contributing back then. However today when I came back, I synced my fork, ran the setup script however I noticed that I was still on ruby `2.2.2` whereas `.ruby-version.example` states `2.3.3`.

Bundler does yell at you if you have the incorrect ruby version however it might get frustrating to consciously change the ruby version. So apologies on my part, I guess I didn't frame the issue correctly.

> Why are existing contributors re-running the setup script?

Running the setup script is just easier I guess to install missing gems, setup the db and run the tests after pulling in the latest changes. Running the commands individually can get a bit tedious.

**Comment by Insti** [comment]
Thanks, your explanations are helpful to me in understanding the issue.

Maybe rather than overwriting, the setup script could check the contents of the files and print an informative warning if they differed?

**Comment by arumoy-shome** [comment]
> Maybe rather than overwriting, the setup script could check the contents of the files and print an informative warning if they differed?

This could work however it will get buried in the logs from bundler, pg and rake so if the contents do not match, we should probably print out an informative error and exit the script.

**Comment by Insti** [comment]
I've been thinking about this, maybe overwriting, but backing up the original file is the right thing to do. Anyone intentionally doing custom things with these files is probably not also running the setup script that often.

**Comment by kotp** [comment]
The setup script could check for the version of the example and report that "Current Ruby version is _whatever_ would you like to O)verwrite or B)ackup and update or I)gnore?"

**Comment by Insti** [comment]
We need to be wary of over-engineering a solution to a trivial problem.
Maybe the original suggestion is the best, unconditionally overwrite.
Any files you care about should be checked into git, right?

**Comment by kotp** [comment]
In the case of version files, checking them into git and being able to change them (The reason for the `.example` extension in the first place) is so you don't check them into git.  Being careful to not arbitrarily change files meant to be contributor modified is something we can help guard against.

**Comment by joelwallis** [comment]
Well, I completely understand the point of @arumoy-shome. If you limit the version of the Ruby your software uses - I mean, programmatically, you must provide a way to "encapsulate" a Ruby version.

It's possible by making use of RVM, and setting the Ruby version into the `Gemfile`. My team uses this approach in our product:

```ruby
source 'https://rubygems.org'

ruby '2.4'

# gems
```

**Comment by kotp** [comment]
The Gemfile is used here as well, currently set at 2.3.3.

Perhaps that portion of the script should no longer exist.

**Comment by arumoy-shome** [comment]
@kotp @Insti  just to clarify, are you proposing that we get rid of the checks in the setup script or that we remove the `.ruby-version.example` file and add a `.ruby-version` file directly into the repo which will be checked into git? 

> The setup script could check for the version of the example and report that "Current Ruby version is whatever would you like to O)verwrite or B)ackup and update or I)gnore?"

Personally, I feel checking the version of the `.example` file is a bit overkill. We should not let contributors choose to "ignore" the specified ruby version, this should be enforced by the project itself. I am okay with either of the following options:

1. Override existing `.ruby-version` with `.ruby-version.example` whenever the setup script is run. 
2. remove `.ruby-version.example` altogether and simply provide a `.ruby-version` file in the repo which will be version controlled by git.

Thoughts?

**Comment by kotp** [comment]
I am definitely for not having the .ruby-version committed to version control.  That is 'fine-grain' control file for the developer.  It may specify gemsets, etc.  Overwriting it arbitrarily can be irritating.

**Comment by Insti** [comment]
Is removing `.ruby-version.example` completely and not creating `.ruby-version' at all a valid option?

I suspect that all ruby environment selectors know to check the Gemfile for the right version.

**Comment by arumoy-shome** [comment]
@Insti I don't think ruby version managers check the Gemfile to pick up which version of ruby to use (I checked [rbenv](https://github.com/rbenv/rbenv#choosing-the-ruby-version) and [chruby](https://github.com/postmodern/chruby#auto-switching) and I suspect rvm works the same way). They look for a `.ruby-version` file in the following order:
`your project dir > home dir > system`.

I think Bundler checks the Gemfile and it exits out if the ruby version mentioned in the Gemfile doesn't match the one on your computer.

**Comment by kotp** [comment]
RVM does indeed pick up (not sure if it in which order it overrides though) the Gemfile version.

**Comment by tejasbubane** [comment]
I don't use `rbenv` but looks like it does not check for Gemfile: https://github.com/rbenv/rbenv#choosing-the-ruby-version

Here's the order precedence for `rvm` (I guess it might help): https://rvm.io/workflow/projects#supported-files
