### ISSUE TITLE
Is Probot working?

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3489]
Exercism recently decided to install Probot to help manage stale issues https://github.com/exercism/discussions/issues/128
> (on April 10th) install https://github.com/integration/probot-stale

It's been more than 2 weeks but there is nothing tagged as `stale`:
https://github.com/search?utf8=%E2%9C%93&q=label%3Astale+user%3Aexercism

There are still many stale issues/pull requests in the repositories.

Is Probot working?  How can we confirm, rather than waiting for the time limit?

**Comment by kotp** [comment]
I got a flood of Probot related announcements, so I would have to say "Yes".
