### ISSUE TITLE
Broken link on fallback "learning" page.

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#3490]
When a language documentation page is using the fallback content the link to the github repository is incorrect.

Example: http://exercism.io/languages/nasm/learning

The link pointed to by: `repository on GitHub.`, `http://exercism.io/languages/nasm/REPO`
is wrong. I suspect there is a template replacement of the 'REPO' string missing.

This may also apply to other fallback pages.

See also: 

https://github.com/exercism/exercism.io/issues/3356
https://github.com/exercism/exercism.io/pull/3454

**Comment by Insti** [comment]
This is probably closer to where this needs to be fixed: https://github.com/exercism/exercism.io/pull/3475

cc: @nholden

**Comment by kytrinyx** [comment]
I think this is fixed.
