### ISSUE TITLE
tiny improvement to mac cli instructions for beginners

### ISSUE THREAD

**Issue by onealexharms** [exercism/exercism.io#3492]
Under the instructions for autocomplete, it says you should be able to type exercism s and get exercism submit. A beginner may not know that they have to press tab after typing it, and so, think they broke something. Page: http://exercism.io/clients/cli/mac

More importantly, though, is that I thought I'd just submit a pull request to fix it, but I can't figure out how. I guess that's two issues, huh?

**Comment by Insti** [comment]
Welcome @onealexharms, it's great you want to help fix this. :heart:

The file that you will need to edit is: https://github.com/exercism/exercism.io/blob/master/x/docs/md/cli/completion.md

There are some instructions about how you can edit the file here: https://help.github.com/articles/editing-files-in-another-user-s-repository/ 

If you get stuck, or need more advice come to: https://gitter.im/exercism/support and someone will be able to help you.

**Comment by morrme** [comment]
it looks like this was done here https://github.com/exercism/exercism.io/commit/a0563d15b64d3a79464c0ec1c9c8586ab65022b2

by @onealexharms but the issue was not closed.
