### ISSUE TITLE
Tweak chocolatey install instructions for users without admin privileges

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3494]
In `x/docs/md/cli/windows.md` we should clarify that if you don't have admin privileges, please use a different installation method.

**Comment by Spinarooni** [comment]
Submitted PR: #3653

**Comment by NobbZ** [comment]
Sorry for beeing late to the party... 

> In x/docs/md/cli/windows.md we should clarify that if you don't have admin privileges, please use a different installation method.

If one hasn't necessary access rights to a computer, we should suggest asking someone who has. Those rights are often denied for reasons and even using other installation methods violate corporate security policies.

**Comment by Spinarooni** [comment]
So, include the non-admin install doc link and add a note about having an admin do the install or not include the link?

**Comment by NobbZ** [comment]
In my opinion we simply should not supply a link to those instructions. But instead point out that even though installation methods for choco exist that do not need adminastrator access, the languages later on probably will not have a workaround for missing rights and that one should ask the computers/networks adminastrator to provide exercism and language installation.

**Comment by Spinarooni** [comment]
Updated PR.
