### ISSUE TITLE
Strange rendering on JavaScript testing instructions

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/exercism.io#3498]
Not sure if this is the right repo for this issue, but I noticed some odd rendering in the JavaScript track.  I'm guessing this is some HTML parsing algorithm trying to be helpful by adding closing tags where they are not appropriate.

This Markdown:
```markdown
For running tests, install `jasmine` as described in the [Installing Javascript section](http://exercism.io/languages/javascript/installing).
Move to the folder where that exercise's files are located (a path similar to <EXERCISM_HOME_DIR>/javascript/<EXERCISE>).

    cd ~/exercism/javascript/bob
    jasmine bob_test.spec.js

Only the first test will be executed, all the others have been marked pending using `xit` or `xdescribe`.
As you keep solving the exercise, one by one change all `xit` and `xdescribe` to `it` and `describe` respectively to run all the tests.
See [Test Driven Development (TDD)](https://en.wikipedia.org/wiki/Test-driven_development) to know more about this approach.
When all tests pass, you are ready to submit!
```

Renders strangely in the user-facing app (http://exercism.io/languages/javascript/tests).  Note the extra closing tags just before the indented block: `</exercise></exercism_home_dir>`

I've also attached a screenshot.:

![screen shot 2017-05-07 at 1 03 55 pm](https://cloud.githubusercontent.com/assets/2478531/25783206/1bdcba92-3326-11e7-92e1-872e898efb4c.png)

BTW if the solution to this is for us to use some other syntax (EG `{EXERCISE}` instead of `<EXERCISE>`) that's easily done.  LMK.

**Comment by Insti** [comment]
Well spotted.
I suspect there is a template replacement issue here, but I've not worked out where yet:

Clues:

The documentation is provided by exercism.io here: https://github.com/exercism/exercism.io/blob/master/app/presenters/track.rb

Which gets its information from trackler: https://github.com/exercism/trackler/blob/master/lib/trackler/track.rb

And the javascript markdown comes from here: https://github.com/exercism/xjavascript/blob/master/docs/TESTS.md

I'm not sure where it is getting replaced and how it is being down-cased. 

cc: @nholden any ideas?

**Comment by Insti** [comment]
There is a another rendering step when the text is converted from markdown to html.
https://github.com/exercism/exercism.io/blob/master/app/helpers/markdown.rb

It is this step which turns 
`<SOMETHING IN ANGLE BRACKETS>foobar` into `
<something in angle brackets>foobar</something>
`

This is probably a feature of the markdown processor, so I would agree with your suggestion to change the delimiters. Curly brackets will work as you intend.

Can you please submit a PR for that @matthewmorgan?

Thanks.

**Comment by nholden** [comment]
> This is probably a feature of the markdown processor

That sounds right to me! Exercism.io [uses](https://github.com/exercism/exercism.io/blob/master/lib/exercism/markdown.rb#L1) [redcarpet](https://github.com/vmg/redcarpet) for markdown processing. I didn't see anything about this particular example, but I do see [a long-running issue](https://github.com/vmg/redcarpet/issues/13) around mixing HTML and markdown, so it's probably best to avoid including things that look like HTML in our markdown that aren't.

Changing the delimiters should work. I also wonder how much value that bit in the parentheses adds. Between the prose description ("the folder where that exercise's files are located") and the command line example, it seems pretty clear to me where I'd go to run the tests. I guess that's a better discussion for the PR in https://github.com/exercism/xjavascript, though.

**Comment by matthewmorgan** [comment]
@insti @nholden thanks for your feedback.

I've opened an issue in xjavascript for this.  I'm hoping a first timer might pick it up.  :)

**Comment by kytrinyx** [comment]
Closing, since it's tracked in the JavaScript repository. Thanks everyone!
