### ISSUE TITLE
Account renaming

### ISSUE THREAD

**Issue by fados** [exercism/exercism.io#3501]
Hi Guys
Would it be possible to rename my exercism.io from my secondary github account (@fados) to my main github account (@ofadeyi)? 
I would really appreciate the assistance thanks.

**Comment by kytrinyx** [comment]
@fados, yeah we can do that. I'll let you know when it's done.

**Comment by kytrinyx** [comment]
OK, this is done.

**Comment by fados** [comment]
@kytrinyx Thanks really appreciate it!

**Comment by kytrinyx** [comment]
🌻
