### ISSUE TITLE
Old submission that I can neither access nor remove

### ISSUE THREAD

**Issue by paulmr** [exercism/exercism.io#3504]
Hi, the following submission is listed on my dashboard, but I am unable to access it or delete it:

http://exercism.io/submissions/19954a6be801409690b3c61b989fb914

Could it possibly be removed from my dashboard please?

Many thanks! -Paul

**Comment by kytrinyx** [comment]
@paulmr, sorry about that! I'm looking into why it happened, and also clearing it out of your dashboard for you.

**Comment by kytrinyx** [comment]
I've reproduced the problem locally with the following:

```
code = ";;; bob.el --- Bob exercise (exercism)\n\n;;; Commentary:\n\n;;; Code:\n\n(defun response-for (input)\n  (let ((case-fold-search nil))\n    (cond\n     ((string-match \"^\\\\s-*$\" input) \"Fine. Be that way!\")\n     ((and\n       (not (string-match \"[a-z]\" input))\n       (string-match \"[A-Z]\" input))\n      \"Whoa, chill out!\"\n      )\n     ((string-suffix-p \"?\" input) \"Sure.\")\n     (\"Whatever.\")\n     )\n    )\n  )\n   ((string-suffix-p \"!\" input) \"Whoa, chill out!\")\n   ((string-suffix-p \"?\" input) \"Whoa, chill out!\")\n   (\"Whatever.\")\n   )\n  )\n\n(provide 'bob)\n;;; bob.el ends here"
language = "elisp"

ExercismLib::SyntaxHighlighter.new(code, language).render
```

I'm narrowing it down from here.

**Comment by kytrinyx** [comment]
Update: this lexes just fine:

```
lexer = Rouge::Lexer.find_fancy "common_lisp"
lexer.lex(code)
```

The problem is in the `Rouge::Formatters::HTMLExercism` formatter, which is a home grown affair.

**Comment by kytrinyx** [comment]
@karloxyz you're the most familiar with the HTMLExercism formatter. Would you have a moment to dig into this a bit to see what might be blowing up here?

@paulmr I'm going to wait to clear it out of your dashboard, since I think this is a formatting bug... unless it's blowing up your dashboard (in which case I'll delete it and you can put it back when the bug is fixed). Let me know what you'd prefer.

**Comment by Insti** [comment]
@kytrinyx try:
```
lexer = Rouge::Lexer.find_fancy "common_lisp"
lexer.lex(code).to_a
```
`lexer.lex` returns an enumerator, so it won't fail until you try to enumerate it.

**Comment by paulmr** [comment]
@kytrinyx thank you for your help. It is not causing me any problems, so there is certainly no hurry to remove it.

Kind regards, -Paul

**Comment by kytrinyx** [comment]
> lexer.lex returns an enumerator, so but it won't fail until you try to enumerate it.

Ah, good point.

**Comment by kytrinyx** [comment]
And it's a problem in the lexer. We're off the hook.

@paulmr I'd like to create the smallest possible sample code that would exhibit this behavior so I can submit a failing test to the upstream project.

If I create a gist that exposes the issue in a test, would you be able to help me narrow down the problematic elisp example to help pinpoint the problem?

**Comment by kytrinyx** [comment]
OK, just in case (optimism, yo!) I've created the gist: https://gist.github.com/kytrinyx/462b0fd50b747b2e50c54fd130f76537

If you don't have time that's totally cool, just let me know and I'll submit this to jneen/rouge and see if they can help me narrow it down.
