### ISSUE TITLE
Cannot upgrade on Windows

### ISSUE THREAD

**Issue by daniel-afana** [exercism/exercism.io#3507]
I've got Windows 10 x64 and Exercism version 2.3.0

```
> exercism upgrade
Downloading exercism-windows-64bit.zip
2017/05/17 14:11:44 open C:\ProgramData\chocolatey\lib\exercism-io-cli\tools\exercism.exe: The process cannot access the
 file because it is being used by another process.
```

**Comment by kytrinyx** [comment]
Hi @daniel-afana sorry you're running into this!

We have an open issue for the problem in the CLI repository: https://github.com/exercism/cli/issues/391

Would you mind reporting your problem in that issue?

There's a fix in the works.

**Comment by daniel-afana** [comment]
Oh right. Thanks, Katrina.
