### ISSUE TITLE
Tests and linter checks

### ISSUE THREAD

**Issue by lukaszklis** [exercism/exercism.io#3508]
Hey, first of all—I love your website! ❤️ 

Sometimes solutions posted on exercism don’t pass the linter or test suite you added for us (for various reasons, people don’t want to omit semicolons, etc.). What about adding a component to the page with ”check” (similar way GitHub does it) and display whether for a specific iteration of the task the linter and tests have passed? Tests and linter could be ran before exercism’s CLI pushes the file to exercism.io.

**Comment by kytrinyx** [comment]
Hi @lukaszklis, we'd love to... but at the moment we don't have resources to execute other people's code remotely, and we've not come to a conclusion on how to do it locally yet.

We have an open discussion about this here: https://github.com/exercism/discussions/issues/94

If you have time to read through it and think through ramifications and your use case, I'd love to hear your thoughts there!

I'm going to close this one in favor of https://github.com/exercism/discussions/issues/94
