### ISSUE TITLE
unable to accept invitation to join team

### ISSUE THREAD

**Issue by wandrewni** [exercism/exercism.io#3518]
I have an invitation to join the ITHAKA team but when I click Accept, I'm taken to a page that says 'Sorry! That's our fault!'

**Comment by eskimoquinn** [comment]
I also have this issue.

**Comment by Insti** [comment]
Thanks for the report.

Possibly related: https://github.com/exercism/exercism.io/issues/3455
@bernardoamc and @kytrinyx might like to look at this.

**Comment by kytrinyx** [comment]
I'll take a look at this today. So sorry you're running into this!

**Comment by wandrewni** [comment]
Thanks for taking a look!

**Comment by kytrinyx** [comment]
I believe that I have a fix for this. It needs a review, and once it's merged I'll deploy and let you know.

**Comment by kytrinyx** [comment]
Alrighty, I'm deploying the fix now. Let me know if you're still having trouble!

**Comment by kytrinyx** [comment]
(oh, uh—give it a couple of minutes to finish deploying)

**Comment by kytrinyx** [comment]
(ok, deployed)

**Comment by wandrewni** [comment]
It's working!  Dang y'all are fast -- thanks much!

**Comment by kytrinyx** [comment]
Yay! OK, glad we figured that one out. It's not the first time we've had trouble with team invitations!
