### ISSUE TITLE
Exercises already completed when fetched

### ISSUE THREAD

**Issue by CBuchanon** [exercism/exercism.io#3519]
The Python exercise 'hamming' comes with a completed solution when fetched from the command line. I deleted the files and tried the fetch again and the same files, with the completed solution, were received. 

I uploaded the solution to move on to the next exercise, word-count, and it also was downloaded with a completed solution.

**Comment by hiphamster** [comment]
Same here. anagram and allergies are both completed.

**Comment by Insti** [comment]
Thanks for the reports. I have made a PR that fixes it we just need to wait for @kytrinyx to be able to do a release to fix it on the live site.

**Comment by Insti** [comment]
This will be a problem for all language tracks.

**Comment by corroded** [comment]
I was just about to post this. It also happens in the `elixir` and `ruby` tracks

**Comment by kytrinyx** [comment]
The fix for this should now be deployed.
