### ISSUE TITLE
Profiles reveal private teams

### ISSUE THREAD

**Issue by edwardbartholomew** [exercism/exercism.io#3550]
Per #3522 it seems private team names should not be revealed at all. However when viewing someone's profile, private team names appear in the listing under teams.

**Comment by Insti** [comment]
> Per #3522 it seems private team names should not be revealed at all. 


I'm not entirely sure this is the case. #3522 was about private teams being listed in search where they weren't going to be selectable.

I think we need to have a project level [discussion](https://github.com/exercism/discussions/issues) about the difference between public, private and secret as it relates to teams.

**Comment by Insti** [comment]
@edwardbartholomew I'm interested in your opinion on https://github.com/exercism/discussions/issues/148, would you comment there please?

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, since we had a great discussion about it in exercism/discussions#148

Thanks for raising the issue!
