### ISSUE TITLE
Python Meetup Test Problem

### ISSUE THREAD

**Issue by Ef-Eff** [exercism/exercism.io#3552]
The last test for the Python challenge  Meetup is written incorrectly, it is simply missing the parentheses for the function after the exception. 
This:
`def test_nonexistent_fifth_monday_of_february_2015(self):
        self.assertRaises(MeetupDayException, meetup_day, 2015, 2, 'Monday',
                          '5th')`
Should be this:
`def test_nonexistent_fifth_monday_of_february_2015(self):
        self.assertRaises(MeetupDayException, meetup_day(2015, 2, 'Monday',
                          '5th'))`

After making this change, the test worked as intended.

**Comment by catb0t** [comment]
cc @exercism/python and the repository at https://github.com/exercism/xpython; you can create a pull request there if you like (it would be a good first patch if nobody takes it).

**Comment by kytrinyx** [comment]
I've moved this issue into the python track repo: https://github.com/exercism/xpython/issues/476
