### ISSUE TITLE
Error on `test:lineman`

### ISSUE THREAD

**Issue by kntsoriano** [exercism/exercism.io#3557]
# Problem
When I ran `test:lineman`, I encountered the following error:

```
Running "spec-ci" task
Fatal error: Testem runner wasn't found! Make sure it is installed locally to your project or under `node_modules/lineman`
```
# Cause
Upon looking into it, the error occurred because the [testem](https://github.com/testem/testem) package isn't present.

# Solution
To fix it, I did the following:

1.`cd node_modules/lineman`
2. `npm install`

# Questions
1. Am I the only who has encountered this problem? I'm inclined to think so because `testem` is set as a dependency for `lineman.js`.
2. If not, should we add an instruction in the readme to install the `testem` package globaly OR do the solution as I described above?

**Comment by kytrinyx** [comment]
Thank you @kntsoriano!

@tejasbubane you've messed a fair bit with the javascript dependencies. Would you weigh in here?

**Comment by mhelmetag** [comment]
I've run into this before when running the js specs so I don't think it's just you. I usually get it when I run `bin/setup`.

I'd be more inclined to either add `testem` to our local `packages.json` or to a setup script/instruction guide for global installation.

**Comment by Insti** [comment]
This is causing the Travis CI tests to fail.

See: https://travis-ci.org/exercism/exercism.io/builds/273341130#L2296

**Comment by kytrinyx** [comment]
> I'd be more inclined to either add testem to our local packages.json

Let's do that! Would one of you be willing to make the change?

**Comment by tejasbubane** [comment]
Since the error says `Make sure it is installed locally to your project or under "node_modules/lineman"`, seems like we need to add it. But I wonder why tests were not failing before.

**Comment by kytrinyx** [comment]
> But I wonder why tests were not failing before.

Who knows! I'm assuming it got included by some transitive dependency or something.
