### ISSUE TITLE
Error: while fetch new problem golang

### ISSUE THREAD

**Issue by longtranf** [exercism/exercism.io#3563]
When i try to fetch new problem. I got this 
`2017/06/22 09:22:57 error parsing API response - invalid character '<' looking for beginning of value` 
I have no idea what happen. The previous one worked. Here is my `exercism debug `
```
**** Debug Information ****
Exercism CLI Version: 2.4.0
Exercism CLI Latest Release: 2.4.0
OS/Architecture: linux/amd64
Build OS/Architecture linux/amd64
Home Dir: /home/<user_name>
Config File: /home/<user_name>/.exercism.json
API Key: <secret_key>
Exercises Directory: /home/<user_name>/exercism
Testing API endpoints reachability
	* GitHub API: https://api.github.com/ [connected] 293.93072ms
	* API: http://exercism.io [connected] 407.669015ms
	* XAPI: http://x.exercism.io [connected] 533.009912ms

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).
```
I still submit successful.
What i have done so far: reboot machine, reset API key.

Update: After an hour, it work again. I haven't done anything.

**Comment by kytrinyx** [comment]
@longtranf I'm not sure what happened, but I'm glad it's working again. I didn't deploy in the meantime so there's something weird going on. If it happens again, holler, and we'll see if we can see more about what's going on.

**Comment by NobbZ** [comment]
In the past we could explain this problem very often with a misconfigured proxy, firewall with package inspection, or parental control software.

So far we always solved this issue by bypassing them.

Perhaps add some stuff in, which gives a better error message[*] in such cases and other stuff which enables us to inspect the sent and received data?

[*] : Simply telling the student that there is **possibly** one of these 3 problems and asking him to file an issue if he wasn't able to make `exercism` work by bypassing them.

**Comment by kytrinyx** [comment]
Sometimes it's also a problem in the API with certain 500 errors, which (for a reason I have not yet debugged) returns HTML rather than JSON.
