### ISSUE TITLE
"Couldn't find that user" when track is not known

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3570]
I wanted to navigate to the lua-landing page in exercism by typing it out by hand, but accidentally typed https://exercism.io/tracks/lus instead of .../lua.

I got a redirect to exercism.io and a flash message telling me that the user couldn't be found.

I think that a generic 404 ore a flash telling me that there is no such track "lus" were much more appropriate.

**Comment by kytrinyx** [comment]
There is currently no `tracks` URL, everything is under `languages`. If you go to http://exercism.io/languages/lus you do get the expected error message.

**Comment by NobbZ** [comment]
Okay, I confused it, since I had .../tracks/<lang>/exercises in my history.

**Comment by kytrinyx** [comment]
The routes are a mess right now. We'll be a lot more intentional about this in the new prototype.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, since we're now that v2 is in beta. Thanks @NobbZ :-) 🌷
