### ISSUE TITLE
Building up to larger examples.

### ISSUE THREAD

**Issue by daantjie** [exercism/exercism.io#3571]
I'm finding that, as I work through some of the exercises, I want to reuse some of the general utility functions that I've created from past exercises.

I think that the current exercises are surprisingly good at getting me to think about what would be the best design for a solution; however, I think it would be nice to have **exercises which *build up* from previous ones**; that is, they are designed so that **you get to use the utilities which you created previously**. Not only would this be fairly gratifying, but I think it would also allow people to consider how good their designs were – something that golfed Ex. 3 nicely might not scale well to Ex. 10, for example.

I'm very happy to have a go at prototyping a kind of *campaign*-style exercise myself – it sounds like a lot of fun, and I might even get to create a narrative around it! – but I'd love to hear what you think. (wrt the efficacy, as well as how it might fit into the current exercism model).

**Comment by kytrinyx** [comment]
@daantjie This has come up before and I think that it's a great idea. I can't for the life of me figure out where we were talking about it. @IanWhitney do you recall where this was?

Would you please move this discussion into http://github.com/exercism/discussions/issues (unless we find that older issue). I think with the model of track progression that we're working on for the new prototype this could fit in: https://github.com/exercism/docs/blob/master/about/conception/progression.md (discussion about core/side exercises here: https://github.com/exercism/discussions/issues/159)

**Comment by daantjie** [comment]
Got it!

**Comment by kytrinyx** [comment]
I found it! https://github.com/exercism/discussions/issues/5

**Comment by kytrinyx** [comment]
Would you mind moving your thoughts into that thread and closing this one? I'm saving a link to that new one in our curriculum design docs.
