### ISSUE TITLE
Possible inconsistency with Bob JavaScript test spec regarding "Whoa, chill out!" response

### ISSUE THREAD

**Issue by rclai** [exercism/exercism.io#3579]
If I'm not mistaken, the specs that determine whether Bob will respond with "Whoa, chill out!" require that all alphabetical characters be uppercase.

However, the following test spec seems to invalidate that rule because all alphabetical characters are uppercase but Bob responds with "Whatever.":

```
it('calmly speaking about umlauts', function() {
  var result = bob.hey('\xfcML\xe4\xdcTS');
  expect(result).toEqual('Whatever.');
});
```

If I were to speak calmly about umlauts to Bob, shouldn't there be some lowercase alphabetical characters?

**Comment by catb0t** [comment]
Could you clarify and write out which actual characters the hex codes correspond to?

**Comment by NobbZ** [comment]
Totally depends on the encoding, but in my local node it prints out `'üMLäÜTS'`, 2 lower case umlauts and an uppercase one. So, it is not yelled.

BUT, we decided to remove non-ASCII tests through the curricula to avoid exactly this kind of confusion. Therefore the @exercism/javascript should take a look at the testsuite and bring it inline with the [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/bob/canonical-data.json), or at least replace the hexcodes by a written out form of the string, to make it easier for a student to understand (at least when his editor is able to understand and the font is able to display).

**Comment by kytrinyx** [comment]
@rclai would you be willing to open this in https://github.com/exercism/javascript? This discussion needs to live where javascript-interested folks will see it.

**Comment by rclai** [comment]
Continued [here](https://github.com/exercism/javascript/issues/376).
