### ISSUE TITLE
"Sorry! That's out fault!" 500 server error on most pages related to my profile

### ISSUE THREAD

**Issue by 6A** [exercism/exercism.io#3580]
I just logged in on [exercism](http://exercism.io) using GitHub, and many pages return a 500 server error.  
The following pages return the error:
- http://exercism.io/notifications
- http://exercism.io/dashboard
- http://exercism.io/6A (`6A` being my username)

However, other pages that required me to log in (http://exercism.io/account and http://exercism.io/account/key) work normally.

I had previously successfully logged in.

### Update
I believe the error comes from the `dlang` language. All *Activity Streams* pages work (ie: http://exercism.io/tracks/nim/exercises, http://exercism.io/tracks/rust/exercises), but the `dlang` does not (http://exercism.io/tracks/dlang/exercises also returns a 500 internal server error).

I believe it comes from the fact that the [`dlang` course was recently renamed to `d`](https://github.com/exercism/d/pull/44).

**Comment by kytrinyx** [comment]
You're absolutely right. I've updated the data, and I think we should be good now. My apologies for missing that!

**Comment by 6A** [comment]
Right now, it looks like everything is back to normal, thank you.
