### ISSUE TITLE
Top 5 implementation

### ISSUE THREAD

**Issue by jadermcs** [exercism/exercism.io#3586]
How about gamification for the implementation area? Users "thumbs up" codes in the implementation area and, for each exercise, the top 5 highest implementations stay in a highlighted area.

It would be nice to encourage users to compete for better codes and the others to see how to write good code.

**Comment by kytrinyx** [comment]
Thank you for your suggestion, @jadermcs. Please see this issue for a discussion about why we're being very careful about gamification: https://github.com/exercism/discussions/issues/123
