### ISSUE TITLE
Migrating to HTTPS

### ISSUE THREAD

**Issue by serathius** [exercism/exercism.io#3587]
I really love the project, but there is something bothering me, so I put my two cents in and offer help if needed.

Sorry If I didn't read for all issues, and don't know all history of project,  but for me as a web developer using HTTP for a page in 2017 is bad, but furthermore having web application with login and third party token authorization is really really bad.

I'm not expert, so I just wanted to share https://doesmysiteneedhttps.com

**Comment by kytrinyx** [comment]
Thanks, yes we're quite aware of this. We'll be moving to HTTPS shortly (probably within the next 3 months) as part of a complete redesign.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, since v2 is in beta, and is HTTPS.

You can see v2 here: http://v2.exercism.io/
And provide feedback here: https://github.com/exercism/v2-feedback/blob/master/README.md

Thanks for the input everyone! 🌻
