### ISSUE TITLE
Faster way to look at solutions

### ISSUE THREAD

**Issue by cpaulbond** [exercism/exercism.io#3588]
After I have completed an exercise I like to review other peoples solutions looking for interesting patterns used to solve the problem.  Unfortunately, the process of looking at solutions is slow and tedious. It requires too many clicks to review a page of solutions.  Would it be possible to expand all the solutions on a page at once, so you could see at a glance which solutions are more interesting?

**Comment by kytrinyx** [comment]
@cpaulbond You're right, this is very painful.

We're working on a complete redesign of the app, and this process of looking for interesting solutions is one of the key things that we're trying to get right. 


> Would it be possible to expand all the solutions on a page at once, so you could see at a glance which solutions are more interesting?

Thanks so much for the suggestion. We'll add this to our list of potential approaches to improving the browsing of solutions. 🌷 

/cc @iHiD @nicolechalmers
