### ISSUE TITLE
Robot-name c++: inconcistency between readme and tests

### ISSUE THREAD

**Issue by fropeter** [exercism/exercism.io#3598]
In the readme file, a reset is said to result in a new random name, while the test fails if the reset changes the name. Which is the correct behaviour?

Also, in the case that a new name should be generated, should the old name be freed for later use, or still be illegal as a name for another robot?

The readme:
```
Every once in a while we need to reset a robot to its factory settings, which means that 
their name gets wiped. The next time you ask, it will respond with a new random name.
```

The test:
```
BOOST_AUTO_TEST_CASE(is_able_to_reset_name)
{
    robot_name::robot robot;
    const auto original_name = robot.name();

    robot.reset();

    BOOST_REQUIRE_NE(original_name, robot.name());
}
```

**Comment by NobbZ** [comment]
The test asks for `original_name` and `robot.name()` to be `n`ot `e`qual. So where do you base your assumption tests and README were contradicting each other on?

Also, if there really is an error in the tests, please report at [exercism/cpp](https://github.com/exercism/cpp), while errors or issues regarding an exercise belong to [exercism/problem-specifications](https://github.com/exercism/problem-specifications).

**Comment by fropeter** [comment]
Sorry! Obviously, I didn't read the test correctly. My apologies!

**Comment by kytrinyx** [comment]
@fropeter You're all good. Glad you got it sorted!
