### ISSUE TITLE
Add a button to navigate to the next solution submitted by other users.

### ISSUE THREAD

**Issue by JuanManuelAbate** [exercism/exercism.io#3599]
Hi, I really like the site and I like to learn making reviews of other users solutions, but I find a little navigability problem. When I access  a solution of an exercise and finalize it, when I want to go to next solution posted by other user I need to came back to the full list of solutions and pick another one.

Is there any possibility to add a next button in the solutions to go to the next one?. To avoid going back and forward every time and make the review process more friendly?

![nextbutton](https://user-images.githubusercontent.com/16357060/28673356-aae25cac-72b8-11e7-8ed7-d4e1610e01e7.png)

**Comment by kytrinyx** [comment]
Thank you for the suggestion @JuanManuelAbate 

We're in the middle of a complete redesign, which should improve the experience significantly.

You might also be interested in seeing some of the earlier discussions about this topic, though this has nothing to do with the redesign:

- https://github.com/exercism/exercism.io/issues/3305
- https://github.com/exercism/discussions/issues/33#issuecomment-241856639

**Comment by Basager** [comment]
Yes, please. That would be very helpful.

**Comment by kytrinyx** [comment]
@Basager we're working on a completely new site design, which will hopefully address your needs better. If you want a sneak peek you can see what we're working on here: http://v2.exercism.io/

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, since we're now that v2 is in beta, we're actively discouraging design changes to v1.

You can see v2 here: http://v2.exercism.io/
And provide feedback here: https://github.com/exercism/v2-feedback/blob/master/README.md

Thanks for the input everyone! 🌻
