### ISSUE TITLE
Wordy in PHP. Invalid test

### ISSUE THREAD

**Issue by BatyaHack** [exercism/exercism.io#3601]
testAddThenMultiply()  compares incorrect values. 
![image](https://user-images.githubusercontent.com/20016700/28745564-787877c0-7483-11e7-92cb-86e25e703f2b.png)
![image](https://user-images.githubusercontent.com/20016700/28745549-2a07e6f2-7483-11e7-8d27-85b80ad790e6.png)
Even Google answered -17

**Comment by kytrinyx** [comment]
You'll notice that Google is adding parentheses and using the default order of operations here. This is a word problem, and the problem specification states that this is to be handled like a verbal word problem, evaluated from left to right, ignoring order of operations:

https://github.com/exercism/problem-specifications/blob/master/exercises/wordy/description.md#iteration-3--multiple-operations

I'm going to close this. If you think that we should reconsider the problem specification, please open an issue in https://github.com/exercism/problem-specifications
