### ISSUE TITLE
Lua activity stream appears to be broken

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/exercism.io#3602]
When I am logged in and I try to navigate to http://exercism.io/tracks/lua/exercises I get a 500 and the "Sorry! That's our fault!" page. This occurs in Chrome and Firefox.

I am able to navigate to the activity stream for all of my other tracks (Clojure, ECMAScript, Ruby, Kotlin) so this doesn't appear to affect all tracks.

Is there any way for me to grab additional information? Or is everything already available via a Bugsnag report?

**Comment by NobbZ** [comment]
I can confirm. Accessing an exercises stream works fine... At least for lua rain drop.

**Comment by kytrinyx** [comment]
Bugsnag says

> NoMethodError/tracks/lua/exercises
> undefined method `to_datetime' for nil:NilClass


The code is

```
@at ||= last_activity_at.to_datetime
```

So I think we have some bad data. I'm taking a look.

**Comment by kytrinyx** [comment]
Would you give this another go? I haven't found the place where we're failing to set this value, but I did find some records with nulls that I updated to equal the "updated_at" timestamp.

**Comment by ryanplusplus** [comment]
Looks to be good now (at least on my phone).

**Comment by ryanplusplus** [comment]
Looks good on the desktop as well. Thanks @kytrinyx.

Do we need to create an issue to track down why the records had `null`s?

**Comment by kytrinyx** [comment]
@ryanplusplus I think let's see if it happens again. We're launching the nextercism prototype to maintainers/contributors next week, and if there are no blockers, we could be abandoning this codebase in 4 or 5 weeks' time.
