### ISSUE TITLE
Contact with Latinamerica

### ISSUE THREAD

**Issue by ChrisADR** [exercism/exercism.io#3603]
Hi,

My name is Christopher Díaz Riveros, I'm a software development student
in Lima, Peru. For some time now I have been supporting my Linux
community, Gentoo Linux, and I have discovered a wide world of
possibilities in open source.

I tell you this because it has been so much benefit in my training as a
a developer that I am determined to start a new community in my country
to be able to make technology-related career students find an open
source community in which they can learn to work And get the same
positive effect that I have had on mine. I have already been talking to
some teachers, I am about to begin my final year of studies in the institute, and they agree to start the community with students of the
institution.

As one of the main problems when getting involved with a community here
is the barrier of english language, and few are able to have fluent
conversations in that language, as it is a bit intimidating for most to
approach an open source community. My community hopes to get in touch
with different open source projects throughout the world and seeks to
be a midpoint to interact with young developers and communities.

Having said all this I have only to offer to your community, the
availability of our community (we still do not have a definite name)
and see if anyone is interested in supporting this group of developers
here and with a bit of luck be able to turn it into a movement of all
Latin America.

Thanks and any kind of feedback is welcome :)
Christopher Diaz Riveros

**Comment by kytrinyx** [comment]
Hi Christopher,

Thanks so much for getting in touch. We are always excited to welcome new contributors!

I don't actually know how many of our contributors or maintainers are Spanish-speaking, but I think there are at least a few. Maybe we could add a spanish-language channel to our chat room, and an `@exercism/espagnol` team that people could opt into if they're willing to help out in Spanish.

I'm not sure what else I can say here, only that I'm excited to hear that you're working on this.

🌷

**Comment by ChrisADR** [comment]
Hi Katrina,

Nice to meet you :)

That's an awesome idea! I have another one, what if we could help you to translate some of your web content and make it available on spanish? Would it be hard? That could help us to make your community and ours participate in the code reviews and helps us to be able to teach our community new languages :)

Right now I'm working with the git project to be able to have git (the command line) on spanish, having your web too would be an amazing starting point for some of our members ( I have to admit that right now we are only 4 members, but hopefully I'll contact a lot of people when the classes begin on August 15th :D 

Thanks and any feedback is appreciated
Christopher Díaz Riveros

**Comment by kytrinyx** [comment]
> what if we could help you to translate some of your web content and make it available on spanish? Would it be hard?

At the moment, unfortunately yes. In a couple of months we might be in a different position, as we're talking about extracting all of the copy to a separate repo, which would potentially make it possible to translate.



> right now we are only 4 members, but hopefully I'll contact a lot of people when the classes begin

I'd recommend looking at the resources that Mozilla have for student open source clubs. They're doing a ton of great work in this area.

**Comment by ChrisADR** [comment]
Thanks for the info :) please let us know when you are ready to translate, maybe we can help a bit with that ;) till then, good luck :)

**Comment by mhelmetag** [comment]
> In a couple of months we might be in a different position, as we're talking about extracting all of the copy to a separate repo, which would potentially make it possible to translate.

The Rails upgrade (if that's what's happening) should definitely make translation easier.

Food for thought, I've used [phraseapp](https://phraseapp.com) before and it seems pretty useful for maintaining and crowdsourcing translations.

**Comment by ChrisADR** [comment]
Thanks @mhelmetag :) great info!
