### ISSUE TITLE
Add "Looks great!" counter to learn from top solutions.

### ISSUE THREAD

**Issue by MichalTHEDUDE** [exercism/exercism.io#3605]
Hi, Is it possible to add "Looks great!" counter next to `1 iteration 0 comments` and a way to filter by it? (Add it into `/tracks/<language>/exercises` panel).

IMHO it would be very nice if anyone could additionally filter by `Looks great!` counter. It would allow to learn from best practices and top solutions.

**Comment by kytrinyx** [comment]
For the past 8 months we've been working on a complete redesign from the bottom up. We should be launching the beta for testing with maintainers and contributors in the next couple of weeks, and if there are no blockers, launching to everyone in a month or so.

The new site is much better thought through in terms of navigation, browsing, and filtering.

If you hang on tight, I promise it will get better 🌻

**Comment by MichalTHEDUDE** [comment]
Aww apologies! I didn't know! Good to hear that :).
No rush, I will be waiting patiently :).

**Comment by kytrinyx** [comment]
> No rush, I will be waiting patiently

I appreciate it :sparkles:

If you keep an eye on http://github.com/exercism/discussions/issues or the newsletter http://tinyletter.com/exercism then you'll be one of the first to know when this goes out :heart:

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, since we're now that v2 is in beta, we're actively discouraging design changes to v1.

You can see v2 here: http://v2.exercism.io/
And provide feedback here: https://github.com/exercism/v2-feedback/blob/master/README.md

Thanks for the input everyone! 🌻
