### ISSUE TITLE
xUnit tests not appearing - Windows system requirements?

### ISSUE THREAD

**Issue by gnivler** [exercism/exercism.io#3607]
I couldn't find this in existing issues or mentioned on the site, sorry if duplicated or just entirely wrong.

From troubleshooting missing unit tests in the Test Explorer (0 discovered) for the csharp/leap exercise, I had to install the dotnet SDK and then manually add C:\Program Files\dotnet to my path, and upon restarting VS the unit tests appear.  Using the CLI indicated the tests were found and passing but it wasn't until I updated the path that VS showed the tests.

I was setting up from a VS 2017 Community install with the C# workload "bundle" which I expected was sufficient but perhaps not?  I am not experienced enough to do anything other than report what I encountered.

Thanks!

**Comment by kytrinyx** [comment]
@gnivler Sorry you're running into trouble!

Would you mind opening an issue in this repository? https://github.com/exercism/csharp That will get this in front of the folks who can best help you out. :heart: I hope you get this resolved quickly.
