### ISSUE TITLE
ruby pangram test is broken

### ISSUE THREAD

**Issue by taw** [exercism/exercism.io#3609]
All the `skip` lines disable the tests and then there's this meaningless thing:

```ruby
  def test_bookkeeping
    assert_equal 4, BookKeeping::VERSION
  end
```

**Comment by NobbZ** [comment]
All Test suites in the ruby track follow that scheme.

**Comment by taw** [comment]
Oh, I compared with old versions without this `BookKeeping` silliness.

Like seriously, why? It makes no sense.

**Comment by Insti** [comment]
@taw I suggest you open an issue in the Exercism Ruby repository if you want to discuss this further. https://github.com/exercism/ruby/issues

**Comment by Insti** [comment]
> why?

The test suites change over time, so it's useful to let reviewers know which version of the tests were used when writing a solution.

**Comment by kytrinyx** [comment]
For what it's worth, we are working on some changes to the backend that will let us get rid of this—where we can always show the exact version of the test suite that someone solved, and deliver it when people download someone's solution to try it out locally.

**Comment by Insti** [comment]
Closing this, if you want to discuss it further please raise an issue in the Exercism Ruby repository.
