### ISSUE TITLE
Add unit test and performance test results to submissions

### ISSUE THREAD

**Issue by mcmahonr** [exercism/exercism.io#3610]
As I review other people's submissions I've noticed that a couple don't pass all of the unit tests. There have also been a lot of submissions that I've thought "Neat! How does it perform?". To test I've been pulling the code locally. It would be really nice to see these results attached to the submissions.

**Comment by NobbZ** [comment]
Allowing to submit even when not all tests pass is kind of a design decission.

1. It does allow to submit solutions which are correct according to personal knowledge (eg dialekts of pig-latin) but not to the test suite.
2. It does allow to submit a solutions which is correct in a future version of the tests. I've done this a few times, while submitting a PR to the tracks repo where I fix small bugs or inconsistencies in the actual tests.
3. It lets you ask for help if you are stuck.

----

Supporting and displaying benchmarks is a feature that is asked often for, but has some problems. We do need a reference system where all those are run on.

Running benchmarks on the implementors machine would make them incomparable. Even the fastest prime generator of the world might be a thousandfold slower on an Amiga 500 compared to a naive one a modern Intel Core i7.

**Comment by mcmahonr** [comment]
I get what you're saying. I don't mean to block the uploads if they fail, just include the output of the tests on the submission page or a link to the test results. I think something like TravisCI or Codeship could accomplish this. 

For performance testing you'd need a consistent machine, maybe a docker or vagrant build to make a consistent environment that you can bring up and tear down at will and run some tests on those.

**Comment by jkinred** [comment]
It would be nice to show if the tests for a solution pass or fail as it would help users locate which solutions can assist them.

This could be done on the machine doing the submission and the pass or fail result sent as part of the submission.

**Comment by kytrinyx** [comment]
>  I think something like TravisCI or Codeship could accomplish this.

If you're willing to investigate how we could accomplish this, that could be an interesting thing to experiment with. Be aware, though, that we would need some sort of API, since the exercises on the website are not backed by git.

**Comment by kytrinyx** [comment]
If you wish to see earlier discussions about this topic, please see #2312, #2803, #1710, and #3127.

I am not currently going to explore these further, so I'm going to close this issue, but as I mentioned, if you're interested in doing an experiment, I would be interested in discussing the results and implementation of that further with you.
