### ISSUE TITLE
Add fb analytics support to Exercism

### ISSUE THREAD

**Issue by abdulhannanali** [exercism/exercism.io#3611]
Exercism currently has no way to get data and insights from it's site, since I see no Analytics system implemented on it which leaves a lot of gap, for data that can be used to improve the experience of Exercism.

Lately, I have been wanting to implement the Facebook Analytics solutions which seems a user friendly analytics solution to gather insights from the people visiting exercism. I'd be happy to modify the templates to integrate the exercism site to use Facebook analytics and help in creaing useful reports and goals in there. 

If the maintainers are interested I can get started on the work, and after the integration and PR is merged, maintainers can use their own FB API Key. 

You can learn more about [Facebook Analytics for Web](https://developers.facebook.com/docs/analytics/quickstart-web) and also check out this [cool guided demo app for more information](https://www.intern.facebook.com/analytics/776816812461629/)

**Comment by kytrinyx** [comment]
@abdulhannanali Thank you for your interest in this!

This website will shortly go away, as we are replacing it with one that we are rewriting from scratch. I would rather not put a lot of work into adding to the site now, as that would be wasted effort.

On a second note, I don't see how FB Analytics would work for us, since this is not a Facebook app.

**Comment by abdulhannanali** [comment]
@kytrinyx Yes I did read another issue after opening this one. So I wanted to say, If it's possible I can make this and other contributions to the newer version.

Facebook Analytics for Web is a solution just like Google Analytics. It is built for websites not just for Apps within Facebook. A very diverse solution.

**Comment by kytrinyx** [comment]
We are using Google Analytics in the new site.

**Comment by abdulhannanali** [comment]
@kytrinyx Cool! Thanks for your response. Closing this issue

**Comment by kytrinyx** [comment]
Thanks @abdulhannanali

**Comment by NobbZ** [comment]
@kytrinyx please be aware of the fact that some users might dislike beeing observed. Personally I just block most trackers by browser plugins, other people will just turn away as soon as they realize them.

I will allow them during the beta though, I think they can provide valuable feedback during this phase.

**Comment by abdulhannanali** [comment]
@NobbZ Analytics data is helpful to improve the experience of application for the users and to determine where we are failing to provide them with a good experience. I think Analytics should strongly be there at all levels. We don't need to collect personally identifiable information but general statistic. IMO, if users don't want this no body is stopping them to download AdBlock.

**Comment by kytrinyx** [comment]
People are free to block the analytics. There are plenty of tools to do so.

**Comment by NobbZ** [comment]
Still a disclaimer would be nice. Similar to those cookie disclaimers popping up on sites under european juristication…
