### ISSUE TITLE
CLI shuts down immediately after starting

### ISSUE THREAD

**Issue by Nick532** [exercism/exercism.io#3613]
I try to use CLI for Windows. 
When I click exercism.exe it starts and shuts down immediately.
What am I doing wrong?

**Comment by kytrinyx** [comment]
Hi @Nick532 so sorry that's confusing!

The CLI is expected to be called from the command prompt or from powershell.

/cc @exercism/windows do we have any good guides for using the CLI on the command line in Windows?

**Comment by rpottsoh** [comment]
@nick532 the CLI is designed to be used at a command (CMD) or powershell prompt.  CLI is short for Command Line Interface. 

Are you familiar with opening a command prompt?   `start` `Run` type `cmd` then click OK or press enter.  At the prompt input `exercism` press enter.  The CLI will provide some help along with available commands for the CLI.
Hopefully this helpful.  Please ask if you need further assistance.
