### ISSUE TITLE
Remark for cpp/gigasecond/gigasecond_test.cpp

### ISSUE THREAD

**Issue by lkskstlr** [exercism/exercism.io#3617]
This is a question:

Wouldn't it be nicer to include "boost/date_time/posix_time/posix_time.hpp" into the gigasecond_test.cpp as it actually needs it, instead of implicitly relying on gigasecond.h to include it. Maybe one wants to keep the header slim and thus forward declares boost::posix_time::ptime and includes the full boost header in the cpp? Additionally there is "boost/date_time/posix_time/posix_time_types.hpp" which has no i/o and would be sufficient for the implementation of advance().

Please correct me if I am wrong :)

Cheers, Lukas

**Comment by lkskstlr** [comment]
Sorry. Only now read the docs and understood that this is the wrong place.

**Comment by kytrinyx** [comment]
> Only now read the docs

I appreciate that you read them! Eventually I'll figure out how to make it more obvious where to submit suggestions and issues ❤️
