### ISSUE TITLE
Typo in GETTING_STARTED.md (the first exercise for Ruby)

### ISSUE THREAD

**Issue by bsielski** [exercism/exercism.io#3618]
There is
```
    1) Failure:
    HelloWorldTest#test_no_name [hello_world_test.rb:11]:
    When given no name, we should greet the world!.
    Expected: "Hello, world!"
      Actual: nil
```
should be
```
    Expected: "Hello, World!"
```
instead of 
```
    Expected: "Hello, world!"
```

**Comment by Insti** [comment]
Thanks @bsielski , did you want to try to fix this?
The file you would need to edit is: https://github.com/exercism/ruby/blob/master/exercises/hello-world/GETTING_STARTED.md

**Comment by Insti** [comment]
Thanks to @bsielski for reporting this and @thejoycekung for fixing it.
Teamwork 👏
