### ISSUE TITLE
Issue with submission

### ISSUE THREAD

**Issue by samuelsincera** [exercism/exercism.io#3619]
I have done as much research on this as I could find. Google puts out almost nothing of use. Forgive a novice jumping in over his head. I bet this is a really simple solution, but my research has not been fruitful yet. This is also my first question, so unsure if I'm breaking any rules. 

I have tried using the readme's, etc. 
You can see the three ways I have tried solving this problem below: 

This is what returned when I entered the debug command:
```
Exercism CLI Version: 2.4.1
Exercism CLI Latest Release: 2.4.1
OS/Architecture: windows/amd64
Build OS/Architecture windows/amd64
Home Dir: C:\Users\Master
Config File: C:\Users\Master\.exercism.json
API Key: f953*************************eb9
Exercises Directory: C:\Users\Master\exercism
Testing API endpoints reachability
        * GitHub API: https://api.github.com/ [connected] 107.8117ms
        * XAPI: http://x.exercism.io [connected] 206.3846ms
        * API: http://exercism.io [connected] 1.2144576s


```
And below are three methods I have tried, and found confusing:
```
C:\Users\Master\exercism>exercism submit python/hello-world.py
2017/09/01 21:54:45 unable to submit - Bad path to exercise file.

You're trying to submit a solution file from inside your exercises directory,
but it looks like the directory structure is something that exercism doesn't
recognize as a valid file path.

First, make a copy of your solution file and save it outside of
C:\Users\Master\exercism

Then, run "exercism fetch". Move your solution file back to the correct
exercise directory for the problem you're working on. It should be somewhere
inside C:\Users\Master\exercism

If you are having trouble, you can file a GitHub issue at (https://github.com/exercism/exercism.io/issues)
```

```
C:\Users\Master\exercism>exercism submit python/hello-world
2017/09/01 21:54:52 Please specify each file that should be submitted, e.g. `exercism submit file1 file2 file3`.
```

```
C:\Users\Master\exercism>cd/python
The system cannot find the path specified.

```

**Comment by kytrinyx** [comment]
@samuelsincera -- first off, if you got stuck, this is definitely one of those "it's not you, it's us" things! Welcome to Exercism and I'm so sorry you're running into trouble on your first day. That's not a great experience.

From the debug command, it looks like you've configured this correctly.

I'm not super familiar with Windows (cc @exercism/windows if any of you are around your eyes on this would be appreciated!) but I'm going to give it a try.

First—are you using the cmd prompt, or powershell or something else?

I'm not sure what your file name is, but my guess is `hello_world.py`. Notice how in your first example you've got a hyphen in there? I suspect that this might be the problem.

So you could try:

```
C:\Users\Master\exercism>exercism submit python\hello_world.py
```

And see if that helps.

Another thing you could try to change directory into the python dir is

```
C:\Users\Master\exercism>cd python
```

Notice how this doesn't have the backslash between `cd` and `python`. If that works, then you should be able to say `dir` if you're in the cmd prompt. If that doesn't work my other guess would be `ls` (as in _list_), but that's a unix thing and I'm not sure it will work on your machine.

Alright—let me know how that goes. Between the two of us we should be able to get you started.

Also feel free to jump into the gitter chat: https://gitter.im/exercism/support - there are a friendly bunch of folks who tend to hang out there.

**Comment by NobbZ** [comment]
> ```
> C:\Users\Master\exercism>exercism submit python/hello-world.py
> ```

Here you are trying to submit a file that resides in the tracks basedir. So it can't get recognized as an actual exercise. You need to have the file below your exercises folder.

> ```
> C:\Users\Master\exercism>exercism submit python/hello-world
> ```

Here you are trying to submit the entire solutions directory, this is currently not possible, you have to specify on or many files.

```
C:\Users\Master\exercism>exercism submit python/hello-world/hello-world.py
```

Is what probably will finaly work.

> ```
> C:\Users\Master\exercism>cd/python
> The system cannot find the path specified.
> ```

Yupp, because there is probably no `C:\python`. `cd python` (without the slash) will work.

In windows if you preceed a path by a forward or backward slash (they are interchangeable in windows) its treated as "absolute" on the current drive.

**Comment by kytrinyx** [comment]
@NobbZ Thanks so much for jumping in here! I didn't catch the missing exercise directory. (I'm going to blame this on it being way past my bedtime...)

**Comment by NobbZ** [comment]
> (I'm going to blame this on it being way past my bedtime...)

Hehe, I just got woken up by my kids ;) So I'm missing some sleep as well ;)

> I didn't catch the missing exercise directory. 

Yeah, I needed to read twice before realizing it. In general I needed to read it twice to realize this is about the old CLI ;)

**Comment by kytrinyx** [comment]
> In general I needed to read it twice to realize this is about the old CLI ;)

I had to double-check as well. We're going to be confused for the next few weeks, I'm sure!

**Comment by samuelsincera** [comment]
Hey guys! 

After watching an episode of the Defenders and eating a bunch of chocolate cookie dough, I had the problem licked. 

Just kidding. But that did actually happen. Okay, so what happened.. Python wasn't installed in a sensible location, the PATH wasn't enabled, and other such funkiness. So I just uninstalled python and reinstalled it, paying more attention to what went where. Rebooted the computer. Python wasn't working on CMD before, now it is. 

Then I basically just went along more slowly and really followed the error messages that were getting thrown in CMD when I was running the exercism submit commands. I have now succesfuly uploaded `hello_world.py` from my `exercism/python/hello-world. `

I am glad I posted here and thanks for your support.

**Comment by rpottsoh** [comment]
@samuelsincera what ended up being your usage of the CLI to submit your solution?

**Comment by kytrinyx** [comment]
> Okay, so what happened..

Excellent! I'm so glad you got this sorted.

> Then I basically just went along more slowly and really followed the error messages 

Isn't it a great feeling when the brain connects the dots from the error messages to the things you can try?

Congrats 🌻
