### ISSUE TITLE
"Sorry! That's our fault!" on pages related to Common Lisp

### ISSUE THREAD

**Issue by beetleman** [exercism/exercism.io#3620]
I have the same problem as [#3580](https://github.com/exercism/exercism.io/issues/3580) but instead dlang i have problem with Common Lisp.
Submission and fetching wont work to.

**Comment by NobbZ** [comment]
Can you please elaborate what you mean by "common list" and how you try to fetch and submit?

**Comment by beetleman** [comment]
Sorry, I was in hurry so i made typo:  `s/common list/Common Lisp/g`.
Fetch
```bash
$ exercism fetch lisp
2017/09/03 00:03:59 unable to fetch problems (HTTP: 404) - No track 'lisp' 
```
Submit
```bash
$ submit raindrops.lisp
2017/09/03 00:05:01 unable to submit (HTTP: 400) - Unknown language track lisp
```

**Comment by NobbZ** [comment]
There is no track “lisp”, its either “common-lisp” or “elisp”, but I think you want to try the first one…

I'm not sure though, How you managed your submission to fail that way… Did you create a `exercism/lisp/raindrops` folder manually?

But in fact, when I try to access your profile, I do get the usual “its our fault page”…

@kytrinyx will probably have to fix something in the database manually…

**Comment by beetleman** [comment]
because its use to be "lisp" not "common-lisp"
```bash
$  tree -L 2
.
├── common-lisp
│   └── hamming
├── lisp
│   ├── bob
│   ├── gigasecond
│   ├── grains
│   ├── hamming
│   ├── leap
│   ├── raindrops
│   ├── rna-transcription
│   ├── robot-name
│   └── word-count
└── racket
    ├── grains
    └── hello-world
```
I submitted all of CL exercises except "raindrops" which was trigger for this problem for me. In my opinion problem is in migration from "lisp" to "common-lisp". I dont want lose feedback I get from CL guys:(

**Comment by kytrinyx** [comment]
Oh, this is legit my fault. We renamed the track a while back and I bet there's some stray data somewhere with the old name. I'll get this sorted ASAP! So sorry about that.

**Comment by kytrinyx** [comment]
@beetleman Would you give that a try?

**Comment by beetleman** [comment]
Dashboard and rest of page work perfectly now. Command line toll starting working after:
```bash
mv lisp common-lisp
```
Thanks a lot!
