### ISSUE TITLE
Notifications are too ephemeral, need a backlog

### ISSUE THREAD

**Issue by astradamus** [exercism/exercism.io#3621]
I hopped onto Exercism and had several notifications. I clicked the first, and when I went back, the rest were cleared and gone, unable to be reviewed. I don't think I've ever used a social platform like this where notifications just disappear forever, for this reason. Sort of frustrating because I have no clue what the others might have been for.

**Comment by kytrinyx** [comment]
Hi @astradamus - we originally modeled the notifications on how GitHub's notifications work. On GitHub if you click, it's gone.

You will never lose a notification that you haven't seen. If they're gone it means that you clicked on the page that they were for. If you only clicked that one page, then they were all different things for the same page.

I know this is super confusing. That's totally my fault (not a designer) and I apologize for the frustration.

We're fixing it in the new design (with real designers!). That's in beta now if you want a sneak peek: http://v2.exercism.io/

**Comment by astradamus** [comment]
Okay, that makes sense! I think it also clears the notification if you load the page at all, even without clicking there through the notification, because I had an embarrassment of tabs open and when I clicked through them found comments and such that I hadn't been notified for (presumably because they were cleared immediately by the loading page).

**Comment by astradamus** [comment]
Wow, v2 looks fantastic, but I can only assume is only partially functional at the moment? At the top of the page it's warning me of regular data wipes, but it let me log in through my GitHub account and the Scala track is showing me some wacky stuff. A random smattering of the exercises I've done are 'Completed' and many more are 'Locked', where I'd expect everything to simply be blank?

**Comment by kytrinyx** [comment]
> I can only assume is only partially functional at the moment

Yeah, it's early beta days still. 

> the Scala track is showing me some wacky stuff.

We're going to do a new data import in a week with some fixes to some wonky stuff, but I'd love to hear what is whacky right now. Want to open an issue in https://github.com/exercism/v2-feedback/issues with your observations?

This is one of the reasons we're importing real data... everything looks different once you have 500,000 code examples.

**Comment by astradamus** [comment]
Okay, you got it.

**Comment by kytrinyx** [comment]
> I think it also clears the notification if you load the page at all, even without clicking there through the notification

I'm pretty sure this is the case (it's been a while, but I think that's the logic I've used).

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, but will of course discuss further in v2-feedback if necessary. 🌷
