### ISSUE TITLE
.Net Core

### ISSUE THREAD

**Issue by bauerpm7** [exercism/exercism.io#3623]
My computer has .net core 1.0 installed so when I go to run the tests it is looking for a .json file rather than the .csproj file.  Is there a way for me to specify the CLI to use .Net Framework rather than .Net Core?

**Comment by kytrinyx** [comment]
Hi @bauerpm7 if you're asking about the C# exercises, your best bet is to ask in the http://github.com/exercism/csharp repository, which is where the maintainers of those exercises can be found.

**Comment by kytrinyx** [comment]
I'm going to close this. If you need further assistance, please open an issue in the exercism/csharp repository.
