### ISSUE TITLE
Cannot add comments to problem submissions

### ISSUE THREAD

**Issue by chuckwondo** [exercism/exercism.io#3624]
As of a few months ago, I am unable to add comments to problem submissions. On the submission page, I see the Comments heading on the right side of the page, and the Write, Preview, and History tabs below it, but the input box and button for adding a comment are missing. I used to be able to add a comment, but this problem appeared a few months ago.

At first I thought it was a site problem, but after a few days of seeing comments appear from others, I thought it was an issue with my browser. However, this problem appears in all 3 of my browsers on my personal laptop, and also appears in all browsers on my company laptop, both on my home network and my corporate network, so this appears to be a problem related to my exercism account.

Here is a screenshot of the issue: https://www.awesomescreenshot.com/image/2789319/fc4575a7aaa604f9e714535b7c06d893

**Comment by kytrinyx** [comment]
This is so odd! I wonder if we have some wonky data somewhere that is affecting just you (or just a few users). I'll dig into this and see what I can find out.

**Comment by kytrinyx** [comment]
I pulled down the database and logged in as you locally, and I'm getting a javascript error on that page. Not on other pages, and not if I log in as myself.

<img width="553" alt="screen shot 2017-09-08 at 5 47 34 pm" src="https://user-images.githubusercontent.com/276834/30234772-d4e41c12-94bd-11e7-8a2b-04327382f1cf.png">

@mhelmetag @tejasbubane I don't know if either of you have some time to work with @chuckwondo on hunting this one down. I'm about to head out for 10 days away from the project, and I'd like to not leave Chuck stuck like this :/

**Comment by chuckwondo** [comment]
Thanks for looking into this @kytrinyx! I'm seeing the same thing in my browser too. Very strange, especially because I see it both on my personal laptop as well as my work laptop, and on multiple browsers.
Given that, and that you cannot replicate it when logged in as yourself, could it be that something is being injected that is account-specific?

**Comment by kytrinyx** [comment]
> could it be that something is being injected that is account-specific?

Could be. It's so strange. Your GitHub data doesn't seem to have any weird characters in it, so I'm not sure where it would be coming from.

**Comment by chuckwondo** [comment]
If I revoke GitHub access for exercism and then reauthorize, would I lose any of my existing content in exercism? If not, then perhaps I'll try that to see if that clears the problem.

**Comment by kytrinyx** [comment]
Nope—you should be fine even if you change your username—though, obviously I'm not encouraging to do that. You have a great username :-)

**Comment by chuckwondo** [comment]
Hmmm. No luck with revoking and reauthorizing. Any way to debug this on your end?

**Comment by kytrinyx** [comment]
Dang it. I missed this. I have no idea how to debug front-end stuff :(

One thing I'd love to know—are you seeing these problems in v2.exercism.io as well?

@iHiD do you know enough javascript to help me figure this one out?

**Comment by iHiD** [comment]
Sure. Run up an ngrok, ping me on Slack and we'll pair on it :)

**Comment by chuckwondo** [comment]
@kytrinyx No such problems for me on v2.exercism.io. Do you have an ETA v2? If it's pretty soon, then I won't bother trying to debug v1.

@iHiD Thanks so much for the offer. I may take you up on it, even just for the experience of debugging via ngrok.

**Comment by kytrinyx** [comment]
Sorry—the past two weeks have been bananas, and I've made no progress (to the point where it's now 5:40am on a Sunday and I'm catching up on 2 weeks worth of email).

Let me see if I can get this sorted out in the next couple of days!

**Comment by kytrinyx** [comment]
@chuckwondo—I'm so sorry. We are completely not going to be able to sort this out in the next week 😢 

Have you by any chance tried turning off javascript? I've not tried it, and I have no idea if we degrade gracefully.

**Comment by Thorocaine** [comment]
@kytrinyx 
I am also having this problem.
I have tried turning off javascript, and it sort of works how you would expect a site to work without JS.

The Comment box shows, but there is no submit button to post the comment.

The reply button (under a comment) is just an anchor, so pressing it (without JS) just reloads the page.

I think for this to work without JS, all that would be needed is a comment submit button (that can be removed with JS)

---

**Without javascript (textbox but no submit):**
![screenshot-2017-10-23 exercism io crowd-sourced code mentorship](https://user-images.githubusercontent.com/14907576/31884379-2a6ce9f0-b7ed-11e7-8ce4-89499acbf1d8.png)

---

**With javascript (Tabs, that don't work)**
![screenshot-2017-10-23 exercism io crowd-sourced code mentorship 1](https://user-images.githubusercontent.com/14907576/31884435-4afa6896-b7ed-11e7-9d7a-1f75af2aacf8.png)

**Comment by kytrinyx** [comment]
> I think for this to work without JS, all that would be needed is a comment submit button (that can be removed with JS)

I'm all for getting this to work without JavaScript, until I can figure out what the heck is going on with the broken javascript for you all. I'm so sorry about this.

**Comment by Thorocaine** [comment]
Thank you.
Let me know if I can test anything at any time.

**Comment by feinorgh** [comment]
I think this is a case of not escaping characters properly in previous comments.

I have the same problem, and in the Chrome Debugger, I ended up with this:

```
underscore.js:1462 Error: Syntax Error: Token ',' is an unexpected token at column 4 of the expression [913, 993}, {993, 913] starting at [, 993}, {993, 913].
    at f (angular.js:185)
    at Ya (angular.js:7283)
    at angular.js:8058
    at e (angular.js:7740)
    at L (angular.js:7382)
    at D (angular.js:6289)
    at C (angular.js:6155)
    at C (angular.js:6243)
    at C (angular.js:6243)
    at z (angular.js:5977)
(anonymous) @ underscore.js:1462
(anonymous) @ angular.js:7710
$apply @ angular.js:10099
(anonymous) @ angular.js:3696
d @ angular.js:5020
d @ angular.js:3696
X @ angular.js:3699
W @ angular.js:3687
(anonymous) @ angular.js:11959
l @ jquery-1.10.2.js:4648
fireWith @ jquery-1.10.2.js:4805
ready @ jquery-1.10.2.js:3039
xa @ jquery-1.10.2.js:2823
```

I recognized this snippet from one of my Go exercises, http://exercism.io/submissions/9789c92f5c864f68bfafd3b955e7d19c

```go
...
Product{906609, [][2]int{{913, 993}, {993, 913}}},
...
```

Possibly, it might be underscore.js interpreting the brackets and the commas in between? If I remember correctly, it comes from the piece of of the page that suggests using old comments as a starting point for new ones.

Hope this helps.

**Comment by feinorgh** [comment]
Pull request #3657

**Comment by Insti** [comment]
#3657 has been merged, is this problem now fixed?

**Comment by nickborromeo** [comment]
@chuckwondo @Thorocaine I know it has been a while since the reporting of this issue and a possible fix was merged a while back as well. Would either of you be able to confirm that this is no longer an issue so this issue can be closed? 😃

**Comment by chuckwondo** [comment]
@nickborromeo Thanks for following up, and apologies for not indicating earlier that this is indeed fixed for me. Thank you!
