### ISSUE TITLE
Little incentive for review/discussion/participation

### ISSUE THREAD

**Issue by astradamus** [exercism/exercism.io#3628]
In the past couple weeks I've completed several exercises and offered comments on many submissions by others, but it feels like I'm shouting in a void. Not because there are no other people here--the activity stream makes clear there are others around, doing the exercises in my language--but because there doesn't seem to be any real framework to encourage or require such participation.

How to actually go about creating such a framework is obviously a big question, and one that I'm guessing (hoping?) you guys have already been chewing on a lot for v2. The only idea I can think of off the top of my head is derived from a writing-workshop type website, where you can submit [chapters of] novels/short stories/etc. for review. I forget the name of the site (it has been years), but there, you earned points by reviewing/commenting/etc. the submissions of others, and it *cost you points* to submit things yourself.

That seems like it could work in this context, with some adjustments. I really hope you guys have something in the works for v2 that remedies this! You have a really fantastic concept here but it's sort of demoralizing as it stands now.

**Comment by kytrinyx** [comment]
@astradamus we do, indeed, have something in the works to remedy this—both in the design of the site itself, and a plan for training and recruiting mentors.

> You have a really fantastic concept here but it's sort of demoralizing as it stands now.

Agreed, this was one of the big reasons that we have been working on v2

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this one, since it is being addressed in v2. Thanks 🌻
