### ISSUE TITLE
Error 503 first byte timeout

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/exercism.io#3630]
@kytrinyx Accidentally uploaded a dictionary file alongside my `Java/pig-latin` submission. Subsequently can only get 503s when accessing the website.

I am unsure as to if the 503s are related to the upload. Either way, I have been recommended that you can manually remove this from the database. Apologies for any inconvenience.

URL: http://exercism.io/submissions/f63b7813d80946759bae417485baf065

I was pointed here from https://gitter.im/exercism/support

**Comment by endotnick** [comment]
I did not upload any erroneous files, but am receiving this same error when clicking the Login with GitHub link on the homepage. 

```
Error 503 first byte timeout

first byte timeout
Guru Mediation:

Details: cache-sea1034-SEA 1505308638 3248530021

Varnish cache server
```

I am able to fetch new exercises, haven't tried submitting new solutions yet.

**Comment by endotnick** [comment]
I was able to login after all, but now I receive the 503 first byte timeout error about 90% of the time when navigating to any page while logged in.

Attempting to submit a solution results in the following error:

`2017/09/13 14:17:50 unable to submit solution - error parsing API response - invalid character '<' looking for beginning of value`

For the record that char is not present in my solution.
```javascript
var Cipher = function() { };
Cipher.prototype.encode = function(input){ };
module.exports = Cipher;
```

Also maybe worth noting that I receive the same API  parsing error when submitting a solution to the ruby track as well.

**Comment by sjwarner-bp** [comment]
Attempting to fetch a new problem also seems to result in the same error:

`2017/09/13 13:52:27 error parsing API response - invalid character '<' looking for beginning of value`

**Comment by NobbZ** [comment]
Yeah seems to be global problem. I do not think it is related to your
submission and I hope it will self heal.

**Comment by sjwarner-bp** [comment]
@NobbZ Ok good to know. If it is an unrelated problem and it does self heal, I should be able to resolve the dictionary issue (above) myself.

**Comment by pelucky** [comment]
I also get "Error 503 first byte timeout" when I open the web,
And when I use "exercism debug", I get this error:
>  * API: http://exercism.io [Get http://exercism.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)] 20.000144s

**Comment by saks** [comment]
Similar problem on linux:
```
** Debug Information ****
Exercism CLI Version: 2.4.1
2017/09/13 19:56:31 unable to fetch latest release: Get https://api.github.com/repos/exercism/cli/releases/latest: dial tcp: lookup api.github.com on 127.0.1.1:53: read udp 127.0.0.1:51576->127.0.1.1:53: read: connection refused
OS/Architecture: linux/amd64
Build OS/Architecture linux/amd64
Home Dir: /home/...
Config File: /home/.../.exercism.json
Exercises Directory: /home/.../exercism
Testing API endpoints reachability
	* XAPI: http://x.exercism.io [Get http://x.exercism.io: dial tcp: lookup x.exercism.io on 127.0.1.1:53: read udp 127.0.0.1:33159->127.0.1.1:53: read: connection refused] 420.386µs
	* GitHub API: https://api.github.com/ [Get https://api.github.com/: dial tcp: lookup api.github.com on 127.0.1.1:53: read udp 127.0.0.1:49544->127.0.1.1:53: read: connection refused] 411.706µs
	* API: http://exercism.io [Get http://exercism.io: dial tcp: lookup exercism.io on 127.0.1.1:53: read udp 127.0.0.1:48077->127.0.1.1:53: read: connection refused] 455.695µs

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).
```

**Comment by rpottsoh** [comment]
Self healed?  Site is up.

**Comment by sjwarner-bp** [comment]
Seems most parts of the site are up and that the CLI `fetch` and `submit` are again working. However, I am still having trouble accessing the page detailed in my opening comment (503 still).

**Comment by kytrinyx** [comment]
Sorry for the late reply. I've been away for the past 10 days, and since the site seemed to be up when I checked I decided to let this one go until I was back.

I'll take a look at deleting the dictionary. In the new site we're putting in some guards to avoid uploading very large files (this is not the first time, as you can imagine!).
