### ISSUE TITLE
Mark as read for a single entry returns a 404

### ISSUE THREAD

**Issue by Ferengee** [exercism/exercism.io#3633]
For example in http://exercism.io/tracks/javascript/exercises/leap
when click on the 'mark as read' button behind a single entry from another user the page redirects me to:
http://exercism.io/&#x2F;tracks&#x2F;javascript&#x2F;exercises&#x2F;leap
which shows a 'We don't have that!' 404 message.

When I reload http://exercism.io/tracks/javascript/exercises/leap the 'mark as read' button is removed

I copied the post request from my browser as a curl statement (removed the cookie) :

curl 'http://exercism.io/exercises/5404658f820445c18f7a46de5b9a9856/views?redirect=/tracks/javascript/exercises/leap' -H 'Host: exercism.io' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Content-Type: application/x-www-form-urlencoded' -H 'Referer: http://exercism.io/tracks/javascript/exercises/leap'  -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' --data ''

The same occurs on for example the haskell track.
The 'mark all as read' works as expected.

**Comment by kytrinyx** [comment]
Thanks for reporting this, I'll dig in and see what's going on.

**Comment by nellshamrell** [comment]
Digging into this a bit - here is an example of the url it attempts to redirect to when hitting the "mark as read" link - http://exercism.io/exercises/4f256d522d00435a8e0867bda5e7ce6a/views?redirect=/tracks/ruby/exercises

**Comment by kytrinyx** [comment]
This is some explicit escaping gone wrong; added in https://github.com/exercism/exercism.io/commit/878fbda2424a301995af6c707d9aa4fadd68b64e

**Comment by nellshamrell** [comment]
Just submitted a PR with a fix.

**Comment by nellshamrell** [comment]
Just looked into this further - looks like escaping html along the lines of "tracks/ruby/exercises" escapes the forward slashes.  Looking into finding a way around this.

**Comment by nellshamrell** [comment]
I'm wondering if we should consider re-architecting the way the request.path_info is passed from the view to the route?  I don't see a way around html escaping escapes forward slashes, but am wondering if there is a way to pass each separate part of the path and then combine them into one string in a route?

**Comment by kytrinyx** [comment]
A couple of things come to mind.

1. We only need to be worried about data that comes from the user. Presumably if we get the data from `request.path_info` then it's safe.
1. If we know the data is safe, then we don't have to escape it.

Perhaps we can have two different methods for creating the redirect path, one that escapes data coming from users, and one that passes request.path_info unchanged.
