### ISSUE TITLE
Java track doesn't work now?

### ISSUE THREAD

**Issue by eitaccount** [exercism/exercism.io#3635]
I tried to have a look others' solution thur below link:

http://exercism.io/tracks/java/exercises

However, it still doesn't work.  Or, is there any other links for solution?

Thanks

**Comment by Insti** [comment]
Have you solved and submitted any problems yourself on the java track?

What do you see that causes you to say that it doesn't work?

**Comment by tejasbubane** [comment]
Hi @eitaccount, did you figure this one out? The thing is, you can only see solutions to problems you have solved. In case you are stuck with some problem, you can submit an incomplete solution to see other's code and get feedback.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, since we've not heard back. @eitaccount if this is still a problem, please open a new issue with details about what you are observing with enough steps that we can verify on our end. Thanks!
