### ISSUE TITLE
Kindergarten problem. Not clear which functions does what

### ISSUE THREAD

**Issue by rwobben** [exercism/exercism.io#3638]
Hello, 

I try to solve the kindergarten challenge in c#. I see that there are 3 seperate functions given: Garden, GetPlants and DefaultGarden. 

I think GetPlants must give me the answer to this problem.
But what schould the other two do exactly ? 

Roelof

**Comment by NobbZ** [comment]
Since this is a question spoecific to the C# version of the exercise (canonical data only knows about the property `plants`), I'll move you over there.

**Comment by NobbZ** [comment]
Issue moved to [exercism/csharp #436](https://github.com/exercism/csharp/issues/436) via [**ZenHub**](https://www.zenhub.com/)

**Comment by NobbZ** [comment]
No rights to close here, can someone else do it please?
