### ISSUE TITLE
Documentation inconsistency on Elixir problem

### ISSUE THREAD

**Issue by mlopes** [exercism/exercism.io#3639]
Hi, 

The `secret-handshake` exercise on the `elixir` track has a consistency issue where the documentation section `Running tests` is showing how to run the tests for the `bob` exercise instead.

http://exercism.io/exercises/elixir/secret-handshake/readme

**Comment by NobbZ** [comment]
This is a problem throughout most of the tracks that needs to specify a filename to run the tests.

This is still related to the fact that a track maintainer had only a single document where he had to specify how to run the test. Most often the first exercise of that track was taken as an example. The server that distributed the exercises generated the README for the exercise from this single "how to run the tests" file and a bunch of other files. 

Nowadays a tracks maintainer has the ability to create and maintain the README on his own. And some tracks picked this up already some not.

To be sure elixir picks it up quickly, feel free to open up another issue there as well:

https://github.com/exercism/elixir

@kytrinyx should we perhaps open up similar issues in all tracks and on the meta-repo, to make sure all tracks have specific instructions to run the test in each README?

**Comment by kytrinyx** [comment]
> should we perhaps open up similar issues in all tracks and on the meta-repo, to make sure all tracks have specific instructions to run the test in each README?

Yeah, that makes sense, thanks! Our README generator is now smart enough to be able to generate the proper file name so that each README has the correct instructions.

I'll open an issue in the meta repo.

**Comment by kytrinyx** [comment]
Opened: https://github.com/exercism/meta/issues/92

**Comment by kytrinyx** [comment]
I'm going to close this issue, actually, since it's tracked elsewhere. Meanwhile, @mlopes, if you want to help fix the Elixir readme template, that would be pretty great :-)

**Comment by mlopes** [comment]
Sorry, I’m not doing the Elixir track, just did this one with a friend and noticed the inconsistency. I’m doing the Haskell one though, so I’ll try to submit PRs on that one if I notice anything.

**Comment by kytrinyx** [comment]
Thanks @mlopes! No pressure either way. Someone will get to it eventually :-)
