### ISSUE TITLE
submitting and getting feedback

### ISSUE THREAD

**Issue by yasserhassansoliman** [exercism/exercism.io#3641]
Hi,
I have solved C++ exercises but I don not know how to submit the solution to get a feedback
Thank you

**Comment by NobbZ** [comment]
I do assume that you already **fetched** your exercise using the `exercism fetch cpp` command, and after that you implemented it and made the tests pass.

If so, the next step is to `exercism submit hello_world.{cpp,h}` (or `exercism submit hello_world.cpp hello_world.h` if not on a linux like system) to actually submit your solution. This commands have to be run from the exercises folder.

**Comment by Snifter00** [comment]
How do you then obtain feedback on your submission? i.e. not from Rikki.
Secondly, how does one review someone else's code?

**Comment by NobbZ** [comment]
Besides waiting you have the following options:

* invite friends to join exercism and give them a link to your submission for review
* find a team which is active in your language (and wait)
* ask for review in gitter.im/exercism/support or if available in your tracks channel

**Comment by kytrinyx** [comment]
Closing, as there doesn't seem to be any further action to take. 🌷
