### ISSUE TITLE
gems conflicts in Ruby

### ISSUE THREAD

**Issue by fabia88** [exercism/exercism.io#3642]
Hello!
I tried the first exercise of the Ruby section, but I think there is a problem with the dependencies of the gem minitest. I got this error message:
/usr/local/opt/rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate railties-5.0.5, because activesupport-5.1.2 conflicts with activesupport (= 5.0.5) (Gem::ConflictError)

I tried to find a solution online but I don't understand how to solve it. Any idea?

**Comment by Insti** [comment]
Welcome.

It looks like there is something messed up with your local configuration. The Exercism exercises shouldn't require "active-anything".

Fixing it through Github posts might be tricky, so come to: https://gitter.im/exercism/ruby and we can try to help talk you through it.

**Comment by Insti** [comment]
We resolved this in the gitter chatroom.
The solution was to set up a new "clean" rbenv-gemset  https://github.com/jf/rbenv-gemset
