### ISSUE TITLE
Getting an error 500 when submitting

### ISSUE THREAD

**Issue by Gimly** [exercism/exercism.io#3644]
Hi there, I did a few exercises and wanted to send them but I always receive an error 500:

```
2017/10/06 23:03:00 unable to submit (HTTP: 500) - Sorry, something went wrong. We've been notified and will look into it.
```

**Comment by kytrinyx** [comment]
@Gimly So sorry you're running into this! What command are you running when you get this error message? (Which track and exercise?).

**Comment by Gimly** [comment]
It happens when I do `exercism submit`, on all tracks and all exercise. I just tried now on the typescript hello-world exercise.

**Comment by kytrinyx** [comment]
Thanks @Gimly working on reproducing this on my end.

**Comment by kytrinyx** [comment]
I'm unable to reproduce this.

Would you please run `exercism debug` and paste the output here, redacting your API key?

**Comment by kytrinyx** [comment]
> I just tried now on the typescript hello-world exercise.

Just to make sure we're on the same page. The exact command that you typed was the following, right?

```
exercism submit hello-world.ts
```

**Comment by Gimly** [comment]
Here's the output of the `exercism debug command`:

```
**** Debug Information ****
Exercism CLI Version: 1.8.2
OS/Architecture: windows/amd64
Home Dir: C:\Users\Xavier
Config file: C:\Users\Xavier\.exercism.json
API Key: redacted
API: http://exercism.io
Exercises Directory: C:\Users\Xavier\exercism
```

The command I did I used to send the hello-world exercise was indeed

```
exercism submit hello-world.ts
```

Tried sending a few other exercises (using the same command, different files) and get the same error. I also tried to reset my API Key and reconfigure it.

**Comment by kytrinyx** [comment]
Would you upgrade to the most recent CLI, please? 1.x is very, very old. We've probably made some changes in the past couple of years that were not compatible with the 1.x clients.

https://github.com/exercism/cli/releases/latest

**Comment by Gimly** [comment]
Oh, that's really embarassing, sorry about that... I had upgraded with Chocolatey, but somehow it kept the old version and I didn't see that I was using that one instead of the new one. I corrected the installation to use the new version and it works correctly.

Thanks for your help!

**Comment by kytrinyx** [comment]
> Oh, that's really embarassing, sorry about that

Not embarrassing—bad UX on our part! Sorry it took so long to figure this one out, and thanks for your patience throughout 🌷
