### ISSUE TITLE
Search by Language

### ISSUE THREAD

**Issue by aes421** [exercism/exercism.io#3646]
I think it would be nice if on the "Languages" page you could click where it currently says "Languages" and it turns into a search bar.

**Comment by aes421** [comment]
I'd also like to take a look at this if you all are okay with it, but since I've never used ruby I may end up changing my mind and letting someone else do it.

**Comment by Insti** [comment]
Hey @aes421 you're welcome to look into this if you like but you should know that we're currently working on a new version of the site where (almost) everything is changing.

See: https://v2.exercism.io/

**Comment by aes421** [comment]
I did not know.  Thanks for informing me!  I'm not sure how to close the issue, but if you can that'd be great.

**Comment by kytrinyx** [comment]
I'll do that. Thank you @aes421!
