### ISSUE TITLE
solution file

### ISSUE THREAD

**Issue by ian-david** [exercism/exercism.io#3651]
I fetched the JavaScript exercise (rna-transcription) and the solution file wasn't included. Only the .spec file. Does this normally happen? How and where can I get the solution file?

**Comment by NobbZ** [comment]
Well, usually it is expected that the student implements the solution, so if you got ready solutions earlier, I do consider that a bug…

**Comment by ian-david** [comment]
What I meant is that there was a file where I had to generate my solutions in the last exercises but this one wasn't included. Is it normal?

**Comment by NobbZ** [comment]
You mean there wasn't a stub provided? On some tracks they aren't provided at all, some do not provide them from a certain point on and others do provide them from the first to the last exercise.

Perhaps take a look or ask at your tracks repository, if there are stubs for later exercises.

But usually the files you need to create follow an easy naming schema, if the name is not mentioned in the failing tests literally… So creating those files and copying some boilerplate from the previous exercise is just a `touch` or `File | New` away…

**Comment by ian-david** [comment]
Okay. Thank you very much.

**Comment by kytrinyx** [comment]
I hope you got this sorted out. I'm going to close this, but if you get stuck again, go ahead and either ask in the [chat](http://gitter.im/exercism/support), or open an issue in the http://github.com/exercism/javascript repository.
