### ISSUE TITLE
Would you add a Dark Theme?

### ISSUE THREAD

**Issue by DeviatedMind** [exercism/exercism.io#3652]
White websites hurt my eyes.
Give it a Hacker sense, I really like the Hacker air I breathe when I'm in your website.

**Comment by DeviatedMind** [comment]
Thank you guys for such a great experience.

**Comment by kytrinyx** [comment]
Hi @DeviatedMind, we have no plans to provide a dark theme at this time. I'm pretty sure you can provide site-specific custom CSS for your browser, though. Or you could go hard core and use lynx or some other terminal-based browser which would take the theme from your terminal settings.

**Comment by DeviatedMind** [comment]
I wrote a Stylish css theme. A simple one, I can share it if you want.

**Comment by DeviatedMind** [comment]
@-moz-document domain("exercism.io") {
body {
    color: #ddd;
    background: #222;
}
.highlight {
    color: white;
    background: black;
}
span {
    color: #eee;
}
.comment-meta {
    background: #111 !important;
}
nav.navbar.navbar-inverse.navbar-default.navbar-fixed-top,
footer#footer {
    background: #000 !important;
    color: white !important;
}
}

**Comment by kytrinyx** [comment]
Thanks! For anyone who comes looking, they'll be able to find it here. 🌷
