### ISSUE TITLE
trouble submitting solutions - "bad path to exercise file"

### ISSUE THREAD

**Issue by rjphares** [exercism/exercism.io#3654]
I've tried submitting the solution file "hello world.cpp" many times and still can't figure out what the problem is.

**Comment by NobbZ** [comment]
How have you tried to submit it?

**Comment by rpottsoh** [comment]
@rjphares in your initial statement it appears the file name you are trying to submit has a space.  Are you enclosing the filename in quotes?  Perhaps renaming the file to remove or replace the space with a different (legal) character would help.

Answering @NobbZ's questions will help us to help you.

**Comment by rjphares** [comment]
cd c:\exercism -> exercism fetch -> exercism submit "test.cpp". I get "You are trying to submit a test file. If this is really what you want, please pass the --test flag to exercism submit" 

I have windows 8.1.

**Comment by NobbZ** [comment]
This message is different from what you've written in the first post.

Please try to reconstruct the message you are reporting in the op.

The message you've told about in the last post does explain how to solve it
if you read it, but again its not recommended to submit test file only.

Robert Phares <notifications@github.com> schrieb am Fr., 27. Okt. 2017,
18:51:

**Comment by rjphares** [comment]
cd c:\exercism -> exercism fetch -> exercism submit hello-world.cpp = bad path

**Comment by rjphares** [comment]
hello-world.cpp is in c:\exercism

**Comment by NobbZ** [comment]
The full error message is this:

```
Bad path to exercise file.
You're trying to submit a solution file from inside your exercises directory,
but it looks like the directory structure is something that exercism doesn't
recognize as a valid file path.

First, make a copy of your solution file and save it outside of
{{ .Configured }}

Then, run "exercism fetch". Move your solution file back to the correct
exercise directory for the problem you're working on. It should be somewhere
inside {{ .Configured }}
```

Where `{{ .Configured }}` is replaced by your exercism base folder.It tell you, that all solution files have to be in `{{ .Configured }}/language/exercise` to be able to be properly recognized.

For your case this is `C:\exercism\cpp\hello-world`. Also as far as I remember, the required name for the tests to pass is `hello_world.cpp` (snake instead of kebab case).

And in the `C` and `C++` tracks it is common to submit the header files as well.

**Comment by rjphares** [comment]
exercism submit hello_world.cpp .  "... unable to submit. ... The system can not find the file specified."

**Comment by rjphares** [comment]
Problem solved, solution has been submitted.  But now I am having trouble with installing cmake and boost to test my solution? I'm going to create a new ticket

**Comment by rjphares** [comment]
Thanks for help

**Comment by courtweb** [comment]
Hello everyone! I'm using Exercism but I can't understand how I upload my code. What I understood was that I have to open my terminal, is it alright? If so, when I do that open something about windows. I really don't know how to upload it. Could you help me with the step by step to upload my code. Thanks a lot.

**Comment by NobbZ** [comment]
You already downloaded the code using the terminal and the CLI, didn't you? So you know already the very basics.

Also I do assume that you have run the exercises tests through the terminal from within your exercises folder, so you know how to navigate directories in the terminal.

Submitting works by navigating into the folder where the exercise is and then typing `exercism submit filename` where if course `filename` has to get replaced by the actual filename you want to submit. For some languages as C or C++ more than a single file are necessary possible.

If you encounter any problems or error messages throughout this process please share them with full details. What was your working dir when you run the failing command? Which command was it that failed? How did it fail exactly? What was the error message it printed? What is the contents of the folder from where you ran the command (use `dir` to list the contents).
