### ISSUE TITLE
Testing solution for hello-world C++ track. Need help installing boost and cmake. 

### ISSUE THREAD

**Issue by rjphares** [exercism/exercism.io#3655]
Trying to test the solution for hello-world on c++ track.  I installed cmake but having trouble installing boost. Then what is next?

**Comment by rjphares** [comment]
I'm stuck on trying to get "cmake -G .." command to work.

**Comment by NobbZ** [comment]
Please provide more detail, as what have you done already, what is the error you get, your operating system, etc.

Also I think, this question is better asked in the C++ tracks issue tracker:

https://github.com/exercism/cpp/issues

**Comment by rjphares** [comment]
"cmake -G" - 'cmake is not recognized as an internal or external command, operable program, or batch file."

**Comment by NobbZ** [comment]
As I already said in Gitter, you need to add it to your path.

https://www.computerhope.com/issues/ch000549.htm

Robert Phares <notifications@github.com> schrieb am Sa., 28. Okt. 2017,
01:06:

**Comment by NobbZ** [comment]
Also after I said put it in your path you said you were having trouble installing boost. 

So please tell **exactly** where you are stuck and provide **full** error messages.

**Comment by rjphares** [comment]
can: change directory
can: fetch
can: submit
can't: test to see if solution is correct (needs cmake and boost?)

**Comment by NobbZ** [comment]
This is far from beeing **exact**, it does tell nothing about what you have done about `cmake` and `boost`, which you need.

To be honest, after I have took a night of sleep, I think its best when you just use an Ubuntu VM, do `sudo apt install cmake libboost-dev` (assuiming recent ubuntu of 17.04 or 17.10). Then you can use [JetBrains CLion](https://www.jetbrains.com/clion/nextversion/) if you really need an IDE or if a lightweight code editor is sufficient there are plenty:

* [Visual Studio Code](https://code.visualstudio.com/) (has [C++ plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools))
* [Atom](https://atom.io/)
* [Sublime Text](https://www.sublimetext.com/)

As I am not using the second and third option, I'm not sure if there are plugins available, also I am not sure about how good the plugin for VScode is. I've not used it so far.


CC: @exercism/cpp

**Comment by rjphares** [comment]
I installed cmake but I get "error in configuration process, project files may be invalid"

**Comment by gewl** [comment]
@patricksjackson This is incredibly helpful, thank you!

I'm having a related problem to this thread, although I think it's actually more closely related to patricksjackson's post than it is to the OP's problem. I have followed exercism's instructions in setting up the testing environment—I've come to the end of the documentation, and still do not know how to run tests or read the output of those tests. The last piece of information in the exercism documentation that I can see is "Windows with Visual Studio: Select Build / Build Solution from the menu.", but it doesn't say what file I should do this from—the test? The solution file itself?

In hello_world.h itself, the Build menu only allows me to "Run Code Analysis on Solution." Same for hello_world.cpp. If I clean & build from the built solution file, I get the following:
Error	LNK1104	cannot open file 'boost_unit_test_framework-vc141-mt-gd-1_65_1.lib'	

Does anyone have any idea what might be causing this problem?

**Comment by kytrinyx** [comment]
@patricksjackson do you have a chance to look at what might be going on with @gewl's setup?

**Comment by LegalizeAdulthood** [comment]
@gewl When you build the solution, it compiles your implementation, compiles the tests and then runs the tests.  Failed test assertions result in "build" errors under this scenario.  You should see them in the Output pane when Build is selected from the dropdown.  They should also appear in the Errors pane as individual errors that you can double-click on to take you to the failed assertion in the test.

On the [Running the Tests](http://exercism.io/languages/cpp/tests) page, it states this at the top:

> Note: Your code is being tested against the test suite every time you build your project. If your code does not pass the one or more tests but is valid C++ code, it will still be compiled.

You build the solution from the Build menu in Visual Studio's menu bar.  You can also use the context menu on the Solution in the Solution Explorer window, but most folks use the Build menu or the keyboard shortcut.  I believe they also have a toolbar button assigned to this action in the default toolbar setup.

The link error you're getting implies that you don't have the compiled unit test library on your system, or it isn't properly configured to find it.  Did you install a prebuilt binary for Boost, or did you install a source distribution?  Instructions for installing prerequisites are [here](http://exercism.io/languages/cpp/installation).

**Comment by rjphares** [comment]
I have boost and cmake installed now. But, I am still not sure how to run the test suite.

**Comment by NobbZ** [comment]
It depends on the generator you use for cmake.

**Comment by LegalizeAdulthood** [comment]
When you build, it runs the tests after compiling your implementation and your tests.  It doesn't matter what generator you use.  Earlier you said you were using Visual Studio, so when you build the solution, it runs the tests.  You can see this in the Output pane with Build Output selected in the dropdown:

![image](https://user-images.githubusercontent.com/4270863/33456712-6fbd7160-d5dd-11e7-9ca9-d094246c91ce.png)

**Comment by NobbZ** [comment]
Of course it matters. You explained for the MSVS generators, while I'm remembering he mentioned to give a POSIX wrapper a try, where you would use the makefile generator of cmake and run the tests using make.

**Comment by LegalizeAdulthood** [comment]
It doesn't matter in the sense that no matter how you build (Makefiles or VS project), the tests run as part of the build.  If the question is: "not sure how to run the tests", the answer is "build the code".

**Comment by rjphares** [comment]
I built the code for leap.cpp with the wrong code(I only used "cout << "hello world";") and the build said it was correct. So I'm thinking something still isn't correct. 

Also, 
when I try to generate cmake from the default directory:
<img width="960" alt="untitled" src="https://user-images.githubusercontent.com/33136845/33503231-947c85c4-d6a8-11e7-9cce-90c83e1bbb97.png">

when I try to generate cmake from the leap directory:
<img width="960" alt="untitled1" src="https://user-images.githubusercontent.com/33136845/33503432-563fe192-d6a9-11e7-896d-2b92306ee4f1.png">

when I try to generate cmake from the leap\build directory:
<img width="960" alt="untitled2" src="https://user-images.githubusercontent.com/33136845/33503533-b6145d3c-d6a9-11e7-8aab-cef4756585fc.png">

**Comment by LegalizeAdulthood** [comment]
OK, let's back up and proceed through the steps to do this from scratch:

1. [Install the prerequisites](http://exercism.io/languages/cpp/installation)
2. Fetch the exercise
3. [Create empty implementation files to seed the project](http://exercism.io/languages/cpp/tests#creating-the-initial-build-with-cmake)
4. [Create the project build files with CMake](http://exercism.io/languages/cpp/tests#windows-with-visual-studio-2017)
5. Build the code.  From an empty implementation you should have compile errors.  Once you satisfy the syntactical requirements imposed by the first test, then building the solution will build the test executable and run it as part of the build.

From your screen shots above, you are not following the steps outlined in step 4 correctly.  Please look carefully at the command lines shown and try them exactly as they appear on the help page.  You can copy/paste them if you like, just be sure to copy and paste the entire command (omit the command prompt shown as `>` in the help page).

Regarding the boost include directory not found, this is also explained on that page:

> If you installed boost to the default location, CMake may be able to find it for you automatically. If it can't find it, you will need to need to supply additional arguments to tell CMake where to find it by setting the `BOOST_INCLUDEDIR` variable on the command-line.

Please try the solution described on that page, it should work properly.

**Comment by rjphares** [comment]
I followed all the steps but still the get same error when running cmake command:
<img width="960" alt="untitled3" src="https://user-images.githubusercontent.com/33136845/33521005-6e5faf2c-d78b-11e7-9754-6dfb7cd8d5bc.png">

after cmake command:
<img width="960" alt="untitled4" src="https://user-images.githubusercontent.com/33136845/33521023-cc21f728-d78b-11e7-99b4-ee14e9410dd0.png">

**Comment by NobbZ** [comment]
Please copy and paste the transcript. Your screenshots are hard to read on a phone and consume a lot of valuable quota. Especially since only 25% of the image are actual payload.

To your problem: please check the spelling of `Boost_INCLUDE_DIR`. I think you missed an underscore between INCLUDE and DIR.

**Comment by LegalizeAdulthood** [comment]
@NobbZ his command line is correct, but the directory he used doesn't contain the expected contents.

I notice that the directory you gave to CMake is a `.nuget` folder.  I don't know what their directory structure is when you attempt to get Boost from nuget.  Download it directly from sourceforge as described in the help instructions and try using that.

**Comment by rjphares** [comment]
I downloaded boost_1_65_1-msvc-14.0-32.exe from sourceforge and the problem is fixed.  To use the test suite I had to open the solution file from the build folder(not sure if there is a better way).

Thanks to all for the help.

**Comment by LegalizeAdulthood** [comment]
Glad you got it working.  I'll create an issue to explore adding instructions for using boost from nuget.

Opening the solution in the build folder is the expected workflow for the instructions we have given.
