### ISSUE TITLE
Unable to submit - Unable to identify track and problem.

### ISSUE THREAD

**Issue by fisherjames** [exercism/exercism.io#3658]
New to terminal and exercism. I know this is a common issue but I searched others peoples solutions and I still can't figure out what I'm doing wrong. I just really want to start using this site, it seems like better tuition than the University I'm studying at.

Debug output:

**** Debug Information ****
Exercism CLI Version: 2.4.1
Exercism CLI Latest Release: 2.4.1
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/james
Config File: /Users/james/.exercism.json
Exercises Directory: /Users/james/Users/james/exercism
Testing API endpoints reachability
	* GitHub API: https://api.github.com/ [connected] 125.21286ms
	* API: http://exercism.io [connected] 232.117746ms
	* XAPI: http://x.exercism.io [connected] 284.862514ms

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).

how I tried to configure:

Jamess-MacBook-Pro:~ james$ exercism configure --dir=~/exercism

Configuration written to /Users/james/.exercism.json

  --key=17d0e4d2045d41a0b88898**********
  --dir=/Users/james/exercism
  --host=http://exercism.io
  --api=http://x.exercism.io

Thanks to anyone kind enough to help me out. I need to learn JUNIT and TDD so I can get a job after I graduate. 

James :)

**Comment by NobbZ** [comment]
The error message you are quoting is usally printed when the solution you try to submit is not in the correct folder.

Please give **full** output of `pwd` and your `exercism submit` command, including the full command as you have written it out.

Please refer to https://kotp.keybase.pub/messages_in_slack/ and use a fenced code block to submit the output.

----

> Thanks to anyone kind enough to help me out. I need to learn JUNIT and TDD so I can get a job after I graduate.

Junit is just a tool among many, you will have a lot of opportunities to learn even more tools as you use them. Also you will not use it in exercism to write tests on your own. Tests are provided, you won't learn anything about the tool used to create or run them.

The same is for TDD, you won't learn anything about it, as **you** are not writing any tests… But TDD means writing tests on your own before implementing the thing.

**Comment by fisherjames** [comment]
As is typical - the issue has magically resolved itself now I've reached out.

Thanks for the reply though, its nice to know this project has a friendly and responsive community.

Any suggestions for other good projects/resources for learning TDD and other valuable skills to make me more employable would be greatly appreciated!

**Comment by kytrinyx** [comment]
@fisherjames I'm glad this got sorted—magically or not!

For TDD, I think that one thing that Exercism will give you is a _feel_ for what TDD can be like: small steps, incremental tests that expect more behavior, and that sense that the next step is not too big, and probably achievable.

I'm hoping to find good resources about TDD in each language. Philosophically it's not very complicated, but as a practice it can be very challenging to get a hang of.

Depending on what sort of learning materials you like, try searching for conference talks about TDD and [your language of choice], blog posts, or books.
