### ISSUE TITLE
Fetching exercises

### ISSUE THREAD

**Issue by KristySimmons** [exercism/exercism.io#3661]
Hi,

When I use "exercism fetch javascript" in the Command Line, I only get the first "Hello World" exercise. Am I supposed to get all of them? Or do I do this each time and it gives me the next exercise?

If that's not the case, can you please tell me how to fetch all of them?

Thank you in advance,

Kristy

**Comment by NobbZ** [comment]
You can fetch the exercises explicitely with `exercism fetch $language $exercise`, you can see which exercises are available at http://exercism.io/languages/javascript/exercises.

If you do not specifiy an exercise you are supposed to get exactly one, and you will get them in a certain order. You can fetch the next exercise after submitting the current one.
