### ISSUE TITLE
"Pass the test flag to submit" message

### ISSUE THREAD

**Issue by KristySimmons** [exercism/exercism.io#3662]
Hi,

I completed the first exercise, and when I try to submit, I get the message below:

"You're trying to submit a test file. If this is really what you want, please pass the --test flag to exercism submit."

I searched this forum and can't find any information on it. Can you please help me submit my tests for review? I'm submitting the first "Hello World" exercise for JavaScript, and have installed HomeBrew, node.js, and jasmine on my Command Line. 

Thank you in advance,

Kristy

**Comment by NobbZ** [comment]
It seems as if you were trying to submit the testfiles, you can avoid this message by either providing the `--test` flag as described in the message, or by not specifiyng the testfiles on the CLI when submitting.

Usually you do the latter. `exercism submit $solution_filename` should be enough.

**Comment by KristySimmons** [comment]
Thanks. When I add "--test exercism submit hello-world.js" to the Command Line, it says "command not found". Is this the proper syntax? 

However, before I tried the above -- I tried to submit and I didn't get  the "--test" message. Instead I got the error message below:

**You're trying to submit a solution file from inside your exercises directory,
but it looks like the directory structure is something that exercism doesn't
recognize as a valid file path.

First, make a copy of your solution file and save it outside of
/Users/kristysimmons/exercism

Then, run "exercism fetch". Move your solution file back to the correct
exercise directory for the problem you're working on. It should be somewhere
inside /Users/kristysimmons/exercism

If you are having trouble, you can file a GitHub issue at (https://github.com/exercism/exercism.io/issues)**

I followed the instructions, and still get the error that it's outside the directory. When I fetch the directory anew, it adds the javascript folder, but it looks like it's default directory path does not include it. 

It still didn't work when I changed the directory path not to include the javascript folder. Any ideas?

**Comment by NobbZ** [comment]
If you are on linux or mac please enter the following commands in your terminal after you have `cd`d into your exercises folder and show us the output of the commands (delete API key from `debug` output!):

```
exercism debug
pwd
ls -l
exercism submit hello-world.js
```

If you are in windows try the same, but replace `pwd` with `cd` (without any arguments) and the `ls -l` with `dir` (again without any arguments).

----

> `--test exercism submit hello-world.js` […] Is this the proper syntax?

No, correct syntax were `exercism submit --test hello-world.js`. But as I said previously, usually you do not actually want to submit the testfiles. And if you really were, you had to list them as well.

**Comment by KristySimmons** [comment]
Hi, 

Below is the record of your directions above along with the output:

Last login: Mon Nov  6 20:34:53 on ttys000
You have new mail.
Kristy-Simmonss-MacBook-Pro:~ kristysimmons$ cd /Users/kristysimmons/exercism
Kristy-Simmonss-MacBook-Pro:exercism kristysimmons$ exercism debug

**** Debug Information ****
Exercism CLI Version: 2.4.1
Exercism CLI Latest Release: 2.4.1
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/kristysimmons
Config File: /Users/kristysimmons/.exercism.json
API Key: b83c*************************398
Exercises Directory: /Users/kristysimmons/exercism
Testing API endpoints reachability
	* GitHub API: https://api.github.com/ [connected] 50.067687ms
	* API: http://exercism.io [connected] 249.12934ms
	* XAPI: http://x.exercism.io [connected] 558.022517ms

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).
Kristy-Simmonss-MacBook-Pro:exercism kristysimmons$ pwd
/Users/kristysimmons/exercism
Kristy-Simmonss-MacBook-Pro:exercism kristysimmons$ ls -l
total 8
-rw-r--r--  1 kristysimmons  staff  3463 Oct 30 20:07 README.md
drwxr-xr-x  4 kristysimmons  staff   136 Nov  6 20:43 javascript
Kristy-Simmonss-MacBook-Pro:exercism kristysimmons$ exercism submit hello-world.js

Thanks for your help,

Kristy

**Comment by NobbZ** [comment]
You are not in the correct place to submit your exercise. You need to be in `/Users/kristysimmons/exercism/javascript/hello-world` or to specify the correct path to your exercise solution file as in `exercism submit /Users/kristysimmons/exercism/javascript/hello-world/hello-world.js`.

**Comment by KristySimmons** [comment]
I'm using a Mac. 

When I used cd to get to the folder, it said no such folder exists. 

When I used pwd with the path, I was able to get into the directory. 

But I had the same problem. It asked for the --test command. So I used it in the proper order you provided, and then got that it isn't in the proper directory. But it is, attached is a screenshot. 

(Also, when I work in the Command Line, I tried the above with the hello-world.js file open, and then tried it with the hello-world.spec.js file open, does it matter which file is open in my text editor?)

**Kristy-Simmonss-MacBook-Pro:~ kristysimmons$ cd kristysimmons/exercism/javascript/hello-world
-bash: cd: kristysimmons/exercism/javascript/hello-world: No such file or directory
Kristy-Simmonss-MacBook-Pro:~ kristysimmons$ open kristysimmons/exercism/javascript/hello-world
The file /Users/kristysimmons/kristysimmons/exercism/javascript/hello-world does not exist.
Kristy-Simmonss-MacBook-Pro:~ kristysimmons$ pwd kristysimmons/exercism/javascript/hello-world
/Users/kristysimmons
Kristy-Simmonss-MacBook-Pro:~ kristysimmons$ exercism submit hello-world.js, hello-world.spec.js
2017/11/08 18:36:48 You're trying to submit a test file. If this is really what you want, please pass the --test flag to exercism submit.
Kristy-Simmonss-MacBook-Pro:~ kristysimmons$ exercism submit --test hello-world.js, hello-world.spec.js
2017/11/08 18:37:44 unable to submit - Unable to identify track and file.

It seems like you've tried to submit a solution file located outside of your
configured exercises directory.

Current directory:	/Users/kristysimmons
Configured directory:	/Users/kristysimmons/exercism

Try re-running "exercism fetch". Then move your solution file to the correct
exercise directory for the problem you're working on. It should be somewhere
inside /Users/kristysimmons/exercism

For example, to submit the JavaScript "hello-world.js" problem, run
"exercism submit hello-world.js" from this directory:

/Users/kristysimmons/exercism/javascript/hello-world

You can see where exercism is looking for your files with "exercism debug".

Kristy-Simmonss-MacBook-Pro:~ kristysimmons$** 

I ran debug and it appears to be looking in the proper folder:

****** Debug Information ****
Exercism CLI Version: 2.4.1
Exercism CLI Latest Release: 2.4.1
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/kristysimmons
Config File: /Users/kristysimmons/.exercism.json
API Key: b83c*************************398
Exercises Directory: /Users/kristysimmons/exercism
Testing API endpoints reachability
	* GitHub API: https://api.github.com/ [connected] 45.653434ms
	* API: http://exercism.io [connected] 274.375109ms
	* XAPI: http://x.exercism.io [connected] 603.925982ms

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).
Kristy-Simmonss-MacBook-Pro:~ kristysimmons$** 

![screen shot 2017-11-08 at 6 41 04 pm](https://user-images.githubusercontent.com/6496953/32580824-39c94c7a-c4b5-11e7-875d-ad3540573595.png)

**Comment by NobbZ** [comment]
> ```
> risty-Simmonss-MacBook-Pro:~ kristysimmons$ cd kristysimmons/exercism/javascript/hello-world
> -bash: cd: kristysimmons/exercism/javascript/hello-world: No such file or directory
> ```

No, when you are in `~` (thats `/Users/kristysimmons`), then you have to do `cd exercism/javascript/hello-world`.

I suggest to do a small tutorial about how to navigate in the shell. Especially to learn about relative and absolut pathes.

----

> (Also, when I work in the Command Line, I tried the above with the hello-world.js file open, and then tried it with the hello-world.spec.js file open, does it matter which file is open in my text editor?)

It does not matter which file is open in your editor, it does not even matter if you have opened your editor. The editor and the exercism client are 100% unrelated.

**Comment by KristySimmons** [comment]
Thanks for your help! I appreciate your time. Ultimately, I got it working per your earlier recommendation to include the entire folder's path when I submit. 

I do agree I need to learn how to use the Command Line, but for other users who read this ticket this is how it worked for me:

exercism submit /Users/kristysimmons/exercism/javascript/hello-world/hello-world.js

**Comment by NobbZ** [comment]
I have submitted another an issue for the CLI-program to turn the order of checks the other way round. Perhaps this might help to sort out this kind of confusion earlier ;)
