### ISSUE TITLE
Exercism Support on Gitter

### ISSUE THREAD

**Issue by KristySimmons** [exercism/exercism.io#3663]
Hi,

I was excited to learn about the support forum on Gitter, but could not find a way to search for my particular issue. I'm sure my issues have been gone over before by someone. Is there a search function in this forum that I'm missing?

https://gitter.im/exercism/support

Thanks for your help,

Kristy

**Comment by NobbZ** [comment]
Well, it is a chat, not a forum. Messages are only saved for a couple of days or a certain threshold is reached. AFAIK there is no way to actually search the log.

But feel free to ask you question, we are happy to help!
