### ISSUE TITLE
C++ leap exercise missing leap.h header

### ISSUE THREAD

**Issue by john-soklaski** [exercism/exercism.io#3665]
The [leap exercise](http://www.exercism.io/exercises/cpp/leap/readme) appears to be missing a leap.h header file. 

I downloaded the exercise using: `exercism fetch cpp leap`.

But, when I run cmake, I get the error:
```
CMake Error at CMakeLists.txt:37 (add_executable):
  Cannot find source file:

    leap.h
```

This is easy to fix by creating leap.h, but the procedure differs from the prior exercise, hello_world.

**Comment by NobbZ** [comment]
This is on purpose. As a student it is your task to create it and fill in the details. You will also need to add and implement `leap.cpp`.

This will continue in all other exercises.

**Comment by john-soklaski** [comment]
Thanks, I see the intent now. On Windows, I'm using cmake to generate a Visual Studio project. Normally I would be creating the header files from within Visual Studio, but the project generation fails due to the missing header.

For ease of use, what do you think about including a empty header file or changing the CMakeLists.txt so the actual project generation doesn't fail?

**Comment by NobbZ** [comment]
I do not have any opinion, but lets ask @exercism/cpp

**Comment by LegalizeAdulthood** [comment]
There has been discussion on this in the past.  The [current instructions](http://exercism.io/languages/cpp/tests) explain to create the empty files first if you're using Visual Studio.
