### ISSUE TITLE
Leave language track if no longer interested

### ISSUE THREAD

**Issue by genos** [exercism/exercism.io#3666]
First off, thank you _very_ much for `exercism`. It's a great resource, and I really enjoy using it.

Is there a way to lease a language track if one is no longer interested in it? I have a couple language tracks that I started out of curiosity about the languages in question, but no longer wish to pursue. I've looked through the website and the CLI, but so far am unable to find instructions on how to leave a language track.

Thanks again!

**Comment by kytrinyx** [comment]
@genos there currently is no way to do this, but I believe this is planned for the v2 version of Exercism which we are planning to launch in Q1 2018 (beta is up on https://v2.exercism.io).

**Comment by genos** [comment]
Fair enough. Thanks for your time, and again for Exercism!
