### ISSUE TITLE
Rikki: not commenting on hello-world submissions

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism.io#3669]
A recent hello-world [submission](http://exercism.io/submissions/3feb3f035f1648989cfa2fb57b714bc2) to the Delphi track did not trigger a comment from Rikki, as it has in the past.  Not a huge problem, but I thought it worth mentioning.

**Comment by NobbZ** [comment]
This problem exists for quite a long time and covers all tracks I've used so far.

I have mentioned the issue every now and then in hello-world related issues but got never a response into this.

Also I do think, in v2 we can phase out Rikki, as `hello-world` is auto-approved and other submissions will be reviewed by real people (mentors).

**Comment by rpottsoh** [comment]
Thanks @NobbZ.  I too recall this issue coming once before a few months ago and then it was resolved.

**Comment by kytrinyx** [comment]
I don't have monitoring on the rikki- server. I'll see what's up with that.

**Comment by kytrinyx** [comment]
Rikki appears to be running. The last entry in the worker log is:

```
workers: 2017/11/23 12:51:48.827516 analyze JID-cffa4d5e9a1e1dea65697ffd done: 249.5285ms
```

Looking more closely, I realize that you're not saying that rikki isn't commenting at all, just not on hello world. I'm opening an issue on the rikki- codebase.

> Also I do think, in v2 we can phase out Rikki, as hello-world is auto-approved and other submissions will be reviewed by real people (mentors).

Agreed. We may repurpose rikki into being a bot to help mentors by giving a quick list of things you might talk about, but we won't be using rikki for feedback directly to students.

**Comment by kytrinyx** [comment]
Closing in favor of https://github.com/exercism/rikki/issues/36
