### ISSUE TITLE
Website https SSL Cert

### ISSUE THREAD

**Issue by KDCinfo** [exercism/exercism.io#3670]
Hi there, I couldn't find any tickets referencing this, but was wondering if it's normal for the http://exercism.io/ site to not serve up on HTTPS? 

I was going to look into starting this, but even the API Key page is insecure, which has me wondering how my currently logged-in session is even secure? Everything over plain HTTP is suspect, yes?

I'm using latest Chrome 62.0.3202.94 (Official Build) (64-bit).

Thanks,
-Keith

**Comment by andrefreitas** [comment]
O subscribe for configuring SSL. You could even use Letsencrypt to have free SSL. If you need an extra hand, I can help.

**Comment by Insti** [comment]
The decision seems to be to not do anything about this at this stage.
Version 2 will be served via https

See also: 

https://github.com/exercism/exercism.io/issues/2589
https://github.com/exercism/exercism.io/issues/2930
https://github.com/exercism/exercism.io/issues/3587

**Comment by KDCinfo** [comment]
Thank you for the insights and links. Look forward to V2.

**Comment by Insti** [comment]
Thanks for helping out and creating the issue. :heart:
