### ISSUE TITLE
Can't submit feedback anymore

### ISSUE THREAD

**Issue by remcopeereboom** [exercism/exercism.io#3673]
I've been submitting feedback to someone's C# exercisms. I haven't completed any of these myself, but for a while, this has been working fine. However, **for the last two days the submit button isn't working** anymore. The submit button still works fine for Ruby problems.

Note that it is also a bit annoying that I can't access my old feedback through any means but the direct link. I can't go to the persons page and few my old nits. If you want I can open a new issue for this.

**Comment by remcopeereboom** [comment]
I can no longer submit feedback for any solutions.

**Comment by Insti** [comment]
This is probably something @kytrinyx  will need to investigate.

**Comment by kytrinyx** [comment]
Shoot! I completely missed this. Is this still the case?

**Comment by kytrinyx** [comment]
I'm able to submit feedback, so this seems like it's localized to just you, @remcopeereboom? I'm downloading a copy of the production database to see if I can log in as you and figure out what's going on.

**Comment by remcopeereboom** [comment]
Yep, this is still the case. If I had to venture a guess, could it have something to do with me checking out the exercism v2? The problem started after that. Either that, or I finally nitted too much :)

**Comment by kytrinyx** [comment]
I've checked out v2 as well, and am still able to comment, so I'm hoping this doesn't have anything to do with it. And one can *NEVER* nit too much! :)

I'll dig into this and see what's going on!

**Comment by kytrinyx** [comment]
Ok, I've narrowed it down to a specific comment that is throwing the history tab for a loop. It's one of the comments on the C# track.

I'm deploying a change that will let you at least comment on other tracks again, and am going to see if I can figure out exactly why the markdown parser is having trouble with that comment.

**Comment by kytrinyx** [comment]
I've further narrowed this down to the following:

Within the offending comment, there is a code block that contains the following snippet: `<A>`

The full line is:

```
using TypeA = Type<A>
```

In the history tab the `<A>` acts as an HTML anchor tag.

Next I'll see if I can change the history tab to handle this correctly.

**Comment by kytrinyx** [comment]
I've not yet hunted this one down—I'm sure it's simple, I'm just not seeing it.

As a temporary measure, @remcopeereboom, you could edit your comment on the C# binary search exercise to use `Type1 = Type<T1>` and `Type2 = Type<T2>`.

**Comment by remcopeereboom** [comment]
Awesome, I can comment again. Thank you so much! 😄  🎉 🏆

As an aside I think I remember that open source repo maintainers didn't have to work on Christmas! I think you get New Year's even off as well, but maybe you've already spent your two days? Really you don't get enough credit.


> `using TypeA = Type<A>`
>
> In the history tab the `<A>` acts as an HTML anchor tag.
>
>As a temporary measure, @remcopeereboom, you could edit your comment on the C# binary search exercise to use Type1 = Type<T1> and Type2 = Type<T2>.

As for the offending comment, I can't actually change _it_ as I don't have a link to it. It's not in my recently viewed list and I don't actually have access to the C# exercises (which in hind-sight I suppose was a good thing). If you could send me a link that would be great, as the person I was commenting on was rather eager for a response and I wasn't able to give one.

**Comment by kytrinyx** [comment]
> As an aside I think I remember that open source repo maintainers didn't have to work on Christmas!

❤️ ❤️ ❤️ ❤️ ❤️ 

> If you could send me a link that would be great, as the person I was commenting on was rather eager for a response and I wasn't able to give one.

Yes! I'll send it by email.

**Comment by kytrinyx** [comment]
Dang. The email in your git history is not working for me. Would you mind emailing me at katrina.owen@gmail.com @remcopeereboom ?

**Comment by martinfreedman** [comment]
Yup this looks the same as the issue I raised bu was old. I thought it could have been dealt with by now. (Tried logging on/signing on to v2 to keep using the site but that does not work for me  )

**Comment by kytrinyx** [comment]
@martinfreedman this is not solved—I have narrowed it down but haven't fixed it yet.

**Comment by martinfreedman** [comment]
I suspect mine is due to that annoying and useless reuse old comments feature? In some scenarios it was making the page very long, requiring much scrolling to get to the post button and sometimes it was not there. 

When source is expanded and comments are underneath, the page end with the post/review/history tab there is no room for a new comment body etc.

**Comment by martinfreedman** [comment]
Opened a new language track and everything is fine there. I suspect it is that comment history feature, is it possible to clear that without losing the actual comments themselves?

**Comment by kytrinyx** [comment]
Yes, it's the comment history feature. In particular, there's likely a comment that is not being parsed correctly in the markdown which is screwing up the html of the page.

**Comment by kytrinyx** [comment]
@nilbus do you happen to recall if we still have Flipper in the codebase for this?

**Comment by nilbus** [comment]
@kytrinyx We do. http://exercism.io/flipper/features/comment_history

**Comment by nilbus** [comment]
Since this isn't escaping properly, I'll disable this feature for now and investigate a fix.

**Comment by kytrinyx** [comment]
Thanks @nilbus!

**Comment by martinfreedman** [comment]
Not sure I am following, re "Flipper". Anyway whatever feature has been disabled , I still have the issue. Is there any way to switch off this feature per user? And to do so for me? I always hated the comment history feature anyway - it should be an options settable in preferences, IMHO.

**Comment by kytrinyx** [comment]
@martinfreedman flipper is the feature flag library we use. If the comment history has been disabled and you're still experiencing the issue, then I will need to investigate your problem separately.

The comment history was an experiment, I'm not sure that we've made our conclusions. I'm pretty sure that we're not implementing it into [v2](https://github.com/exercism/v2-feedback/blob/master/README.md) (though we are thinking about ways of making it easier to provide feedback).

**Comment by kytrinyx** [comment]
Awesome thanks for reporting back.

**Comment by nilbus** [comment]
> I always hated the comment history feature anyway

@martinfreedman Great feedback. Aside from this bug, which was obviously harmful, what were your reasons for disliking the comment history feature?

**Comment by martinfreedman** [comment]
1.It slowed down loading of the page.

2.The submit/preview button was below all the history text requiring scrolling up and down to preview and post. 

3.any comments were specific not general and there was no option to delete them.

Alternative: A button to drop down/show comment history with filtering per user and/or per exercise would make much more sense.

**Comment by nilbus** [comment]
Makes sense. Let's just leave that feature turned off.
