### ISSUE TITLE
4 Suggestions for improving code quality from a 6/10 into a 9/10

### ISSUE THREAD

**Issue by MichielCuijpers** [exercism/exercism.io#3676]
Hello Maintainers

This is @MichielCuijpers from the [BetterCodeHub](https://bettercodehub.com) team. We are building a new static code analysis tool with benchmarking and compliance scores. The goal is to help developers in writing better code according to 10 guidelines for _Building Maintainable Software_. And it is Free for open source.  

Currently Exercism.io scores a  <img src='https://bettercodehub.com/edge/badge/MichielCuijpers/exercism.io?branch=master'>. 

In order to bump this score BetterCodeHub suggest 'refactor candidates' that violate one or more of the 10 guidelines. 

Solving the **selected** candidates below will even improve the compliance with **3** guidelines. 

Write Short Units of Code:
  — jasmine-fixture.​js:createHTMLBlock
      starts at line 167 in frontend/​spec/​helpers/​jasmine-fixture.​js

Write Simple Units of Code:
  — jasmine-fixture.​js:createHTMLBlock
      starts at line 167 in frontend/​spec/​helpers/​jasmine-fixture.​js

Write Code Once:
  — 41 lines occurring 2 times in multiple files
      starts at line 105 in lib/​exercism/​team_​stream.​rb
      starts at line 71 in lib/​exercism/​track_​stream.​rb
  — 34 lines occurring 2 times in a single file
      starts at line 151 in lib/​exercism/​team_​stream_​filters.​rb
      starts at line 366 in lib/​exercism/​team_​stream_​filters.​rb
  — 16 lines occurring 2 times in multiple files
      starts at line 13 in lib/​exercism/​team_​stream_​filters.​rb
      starts at line 7 in lib/​exercism/​track_​stream_​filters.​rb
  — 6 lines occurring 4 times in a single file
      starts at line 183 in app/​routes/​teams.​rb
      starts at line 104 in app/​routes/​teams.​rb
      starts at line 154 in app/​routes/​teams.​rb
      starts at line 126 in app/​routes/​teams.​rb

BetterCodeHub integrates easily in your GitHub flow. Just you enable the web hook toggle (under the gear icon ⚙) and it will run for every Push & Pull Request. It takes a simple [.bettercodehub.yml](https://github.com/MichielCuijpers/exercism.io/blob/master/.bettercodehub.yml) file to configure.

I think that the above refactor candidates could be converted into nice issues for the [24 Pull Request](http://24pullrequests.exercism.io) campaign.

Thanks, hope you will find this a useful suggestion.

MichielCuijpers
![schermafbeelding 2017-11-30 om 16 30 59](https://user-images.githubusercontent.com/18576001/33438714-e419cb04-d5eb-11e7-81e3-d1bbbe2dbb12.jpg)

**Comment by biinari** [comment]
frontend/​spec/​helpers/​jasmine-fixture.​js seems to be vendored from https://github.com/searls/jasmine-fixture so not a candidate for refactoring here. It is a few versions behind though, if someone thinks it's worth updating.

**Comment by kytrinyx** [comment]
@MichielCuijpers Thank you. The codebase of Exercism.io is not meant to be good, as everything in it is experimental and throw-away—the experiments were not about code, but about features and interactions.

I have no plans to improve the quality of this code base, and would encourage people not to spend time refactoring.

We are, however, developing a completely new version of the site (see http://github.com/exercism/prototype and https://github.com/exercism/v2-feedback/blob/master/README.md) and we will be working to maintain a high quality in the new codebase.

I would not be opposed to running various quality tools against it, however, at the moment we don't have the bandwidth to manage contributions to that repository, so I wouldn't encourage people to submit refactorings there, either at the moment.

I don't mean to discourage code quality, but I'm highly cognizant of the trade-offs that we've made here in various ways.

I'm going to go ahead and close this, but very much appreciate that you jumped in with these suggestions! ❤️
