### ISSUE TITLE
Page not found error

### ISSUE THREAD

**Issue by rushout09** [exercism/exercism.io#3678]
Hi,
I was looking to start contributing to open source and found this repository through the [guide](https://github.com/collections/choosing-projects). While trying to add some language tracks to watchlist through this [page](http://exercism.io/repositories), I found that the link on this page to the documentation of main product on Github is giving a page not found error pointing to this [link](https://github.com/exercism/exercism.io/blob/master/docs/overview-of-exercism.md). I thought I could update the correct link but couldn't find my way to correct source code in various folders hence opened this issue. Hope this helps.

**Comment by Insti** [comment]
The incorrect URL is in this file: https://github.com/exercism/exercism.io/blob/master/app/views/languages/repositories.erb

The new URL will probably be somewhere in the: https://github.com/exercism/docs repository.

I hope those clues can point you in the right direction.
Let us know if you have any more questions, we're here to help :)

**Comment by rushout09** [comment]
Thanks a lot!
I have made my first pull request, yay!
Should I close this issue now or is there any other procedure?

Once again, thanks for the help.

**Comment by Insti** [comment]
Thanks, The issue should remain open until the pull request is merged.
If you put the right 'magic words' into the pull request, github will do this automatically.
(I'll add these for you this time.)
