### ISSUE TITLE
Fetching retrieves only some of the files

### ISSUE THREAD

**Issue by WaygoneWilco** [exercism/exercism.io#3680]
I am working on the Clojure track, and when I fetch the nucleotide-count problem using the CLI, exercism fetches the test folder, projectl.clj and readme.md files, but not the src or target folders. This also happened with the Run Length Encoding problem.

**** Debug Information ****
Exercism CLI Version: 2.4.1
Exercism CLI Latest Release: 2.4.1
OS/Architecture: linux/amd64
Build OS/Architecture linux/amd64
Home Dir: /home/aaron
Config File: /home/aaron/.exercism.json
API Key: ********************************
Exercises Directory: /home/aaron/exercism
Testing API endpoints reachability
	* GitHub API: https://api.github.com/ [connected] 47.739488ms
	* XAPI: http://x.exercism.io [connected] 116.841329ms
	* API: http://exercism.io [connected] 168.4616ms

**Comment by NobbZ** [comment]
Nucleotide counts src folder is empty after removing the example solution,
so it doesn't get downloaded at all, you need to create it on your own.

There should have been a src folder with a stub implementation for run
length encoding though...

Aaron Martz <notifications@github.com> schrieb am Di., 5. Dez. 2017, 20:22:

**Comment by kytrinyx** [comment]
It sounds like this got sorted, so I'm going to go ahead and close the issue. Thanks for raising the issue (and thanks @NobbZ for the quick reply!)
