### ISSUE TITLE
Feature request: RSS feed of team activity

### ISSUE THREAD

**Issue by abeger** [exercism/exercism.io#3682]
Our team has a Slack channel and I'd love to pipe our exercism activity feed into it. That way, everyone's alerted that someone has a new solution that could use some comments. Rather than build up a whole Slack plugin, an RSS feed seems like a nice, simple way to do this.

Thanks!

**Comment by kytrinyx** [comment]
@abeger this is an interesting feature request! It's unlikely to happen in the v1 version of Exercism, but I will add this to the list of things to discuss with the others for [v2](https://github.com/exercism/v2-feedback/blob/master/README.md).

**Comment by kytrinyx** [comment]
Ok, added it to the list. I'm going to close this for now, since we're tracking it in the design TODOs for the v2 teams feature.

Thanks for the suggestion!

**Comment by abeger** [comment]
Thanks!
