### ISSUE TITLE
Passed tests provided on the exercism exercise, but the implementation is actually wrong, the website still accepted the code nonetheless. Should have the ability to redo and remake the the exercise

### ISSUE THREAD

**Issue by OrangeMarmalade** [exercism/exercism.io#3683]
I was working on Java Pangram exercise and I accidentally put in 24 letters instead of 26 letters, I didn't realize that until I passed the test and submited the question, the implementation is technically wrong, but apparently the program test cases didn't catch any of the problems that happened, if there are ways to change it, that would be great.

**Comment by NobbZ** [comment]
1. The website accepts any code, working or not. 
  a) building infrastructure to test any submission in any language would be a lot of work
  b) there is a (half heartedly) implemented feature to request help, this wouldn't work if we denied submission of not working code
2. You can repair your local code and resubmit, the page will pick the changed code as a new iteration and keep track of the history. You can delete single iterations via the menu on the iterations page.
3. For fixing/extending the actuall tests data, please take a look at the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/pangram/canonical-data.json) if it would miss the same cases as your code. If it does, please do a PR or file an issue in the same repository. If it were detecting your code as faulty please file an issue/do a PR in the repository of your language (which you didn't tell us)

**Comment by kytrinyx** [comment]
@OrangeMarmalade it sounds like this is resolved in one of two ways:

1. The tests do catch the error, and we're all good.
1. The tests don't catch the error, in which case we'd need more information, preferably in the form of an issue or pull request to the https://github.com/exercism/problem-specifications/blob/master/exercises/pangram/canonical-data.json file in the github.com/exercism/problem-specifications repository.

I'm going to go ahead and close this. 🌷
