### ISSUE TITLE
Add SSL - https://letsencrypt.org/

### ISSUE THREAD

**Issue by kenaniah** [exercism/exercism.io#3686]
Would love to use this service over HTTPS ;-)

**Comment by tejasbubane** [comment]
Check https://github.com/exercism/exercism.io/issues/3670. Exercism v2 is work in progress and will have SSL.

**Comment by kytrinyx** [comment]
We will not be adding SSL to the v1 of the site, but as mentioned above, v2 already is served over HTTPS.
