### ISSUE TITLE
Why do you only allow login via Github?

### ISSUE THREAD

**Issue by vasudevram** [exercism/exercism.io#3687]
It would be good if you could support an email + password based login too.

**Comment by kytrinyx** [comment]
Yes, agreed.

The [v2](https://github.com/exercism/v2-feedback/blob/master/README.md) redesign (currently in beta) supports login via email and password as well.

**Comment by vasudevram** [comment]
Thanks for the info.

**Comment by Ornataweaver** [comment]
I see it as a feature my friend.
