### ISSUE TITLE
unable to fetch problems (HTTP: 404) - No track '<language>'

### ISSUE THREAD

**Issue by Yeshasvitvs** [exercism/exercism.io#3688]
Hello,

I am having the following error when trying to fetch any language.

unable to fetch problems (HTTP: 404) - No track '<language>'

It works fine with python, but not for many other languages. I tried C, C#, C++, CoffeeScript, LFE, Lua

**Comment by NobbZ** [comment]
How exactly have you tried to fetch the exercises and whats the version of your CLI (`exercism --version`)?

**Comment by Yeshasvitvs** [comment]
@NobbZ My bad, I tried `exercism fetch C++` instead of `exercism fetch cpp`

I also tried for other languages mentioned in the previous comment and everything works fine.

The confusion is because of this page http://exercism.io/languages
It may be useful to put the `name` in paranthesis `e.g., (cpp)` to use with the fetch command

**Comment by NobbZ** [comment]
I do not think this will be changed in the current version, but for the next version (which is a major overhaul) this is solved in a better way, as each exercise tells you how to fetch it explicitely, track-ID included.
