### ISSUE TITLE
Bugs in palindrome_products_test.py (Python 3)

### ISSUE THREAD

**Issue by marcuslxxii** [exercism/exercism.io#3690]
Following lines are incorrect:
    self.assertIn(set(factors), [{1, 9}, {3, 3}])
    self.assertEqual(set(factors), {91, 99})
    self.assertEqual(set(factors), {11})
    self.assertEqual(set(factors), {913, 993})
    self.assertEqual(set(factors), {101, 101})
Must be replaced by the following lines:
    self.assertCountEqual([set(x) for x in factors], [{1, 9}, {3}])
    self.assertEqual([set(x) for x in factors], [{91, 99}])
    self.assertEqual([set(x) for x in factors], [{11}])
    self.assertEqual([set(x) for x in factors], [{913, 993}])
    self.assertEqual([set(x) for x in factors], [{101}])

**Comment by NobbZ** [comment]
I can't move from here, so can you please re-report this issue on the bugtracker for the python track?

https://github.com/exercism/python/issues

It might help though to explain why you think those should be changed.

**Comment by NobbZ** [comment]
Oh, and just to make sure, they will get notified about this issue:

\cc @exercism/python

**Comment by tejasbubane** [comment]
Reported in python track: https://github.com/exercism/python/issues/1136. So I guess this one can be closed.
