### ISSUE TITLE
After authorizing Github access, exercism will still not let me login

### ISSUE THREAD

**Issue by willus10245** [exercism/exercism.io#3691]
The first time I hit the "Log in with Github" button on the home page, it took me to Github, where I authorized access to my account, but now I still only see the "Log in with Github" button on every page, and every time I click any link to go to my account, or log in, it just takes me to the homepage with the "Log in with Github" button.

**Comment by NobbZ** [comment]
First make sure you have cookies allowed for http://exercism.io, also make sure you have JavaScript active and allowed for http://exercism.io.

**Comment by NobbZ** [comment]
Oh, and if you do have this problem in a firewalled or proxy'd network, please try again from a less restricted location.

**Comment by willus10245** [comment]
Ok yeah, I tried it on another computer and it worked fine. It must be the accountability software I have on my browser stopping it for some reason.

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, as I don't think there's anything we can do on our end for this one.
