### ISSUE TITLE
tree_building.go poor explanation

### ISSUE THREAD

**Issue by mpicard** [exercism/exercism.io#3693]
I found the given tree_building.go had poor documentation. For example, as a beginner to go, this signature makes no sense to me `func (m Mismatch) Error() string`, a few docstrings could improve this exercise a lot. I understand that it's a bad implementation but it can still include an explanation of what it's attempting to do

**Comment by kytrinyx** [comment]
Would you please open this in the repository for the Go track? That way you can discuss with the maintainers of the exercise how it could be improved: http://github.com/exercism/go

Thanks!
