### ISSUE TITLE
Please less JavaScript!

### ISSUE THREAD

**Issue by farooqkz** [exercism/exercism.io#3696]
Hi,
Please try to make this website use the least JS.
I mean site should work fine with JS disabled and it should be used just to improve site's functionality.
If that's not possible use it just when it's really necessary.(JavaScript was used even for the title of each page).
Thanks

**Comment by Ornataweaver** [comment]
Yes please. I use ScriptSafe, chrome equivalent of NoScript on FireFox.
It's insecure to allow js on many ZeroNet sites that I cannot trust.

**Comment by farooqkz** [comment]
@Ornataweaver: Exercism is not on ZeroNet.

**Comment by Ornataweaver** [comment]
Sorry, I thought I this was ZeroNet repository. Probably I got lost between my tabs.

**Comment by farooqkz** [comment]
@Ornataweaver: so you should remove your thumb up and heart emojies.

**Comment by kytrinyx** [comment]
The new version of Exercism (in beta now, hopefully launching soon) uses much less javascript.

https://github.com/exercism/v2-feedback/blob/master/README.md

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this, since we will not be making significant changes to v1.
