### ISSUE TITLE
Bug in multi-byte test case for PHP/Bob

### ISSUE THREAD

**Issue by MattLewin** [exercism/exercism.io#3699]
Currently, the test case reads:
```
    public function testOtherWhitespace()
    {
        $this->markTestSkipped();

        $this->assertEquals("Fine. Be that way!", $this->bob->respondTo("\n\r \t\u000b\u00a0\u2002"));
    }

```

The Unicode characters falling the tab (\t), seem to be incorrectly formatted. They should be `\u{000b}\u{00a0}\u{2002}`. Otherwise, they are just text and do not count as multi-byte whitespace.

**Comment by kytrinyx** [comment]
Thanks for reporting this. I've moved the issue into https://github.com/exercism/php/issues/190 so that it can get the attention of the maintainers of the PHP track.
