### ISSUE TITLE
Enhancement suggestion: better visibility of other users' solutions

### ISSUE THREAD

**Issue by vittorius** [exercism/exercism.io#3700]
I suggest making the feed of other users' solutions for a particular exercise (for instance http://exercism.io/tracks/haskell/exercises/leap) to be more readable from the first sight without a need to navigate to every particular solution's page. As it's done at https://codewars.com, for example. More like a Facebook feed if you'd like where you can see the code and all the details (user ID etc.) and are able to Like/Dislike. Thanks.

**Comment by kytrinyx** [comment]
Thanks!

We are currently developing a whole new website, which you can see at [v2](https://github.com/exercism/v2-feedback/blob/master/README.md).

This redesigns the user experience from the ground up. As we're fairly close to launching the v2 site, we won't be making any design changes to the current site.
