### ISSUE TITLE
Swift ISBN Verifier Test Suite Omits Important Edge Case

### ISSUE THREAD

**Issue by p0st0culus** [exercism/exercism.io#3702]
The test suite for the ISBN Verifier problem in the Swift track should test for an empty string ISBN.  This is a an important edge case that @Damlar noted was missing from my solutions which is also omitted from the test suite.

It's something that, in hindsight, I should have known to test for, but I didn't.  That's the whole point of a well thought out test suite though:  Code against assertions of what a valid solution should produce.  I tend to implicitly put trust in the test suites, so that's my lesson learned.  I'll take an active role in the test suites going forward.

I recommend modifying IsbnVerifierTests.swift as follows.  Other content from the test suite omitted with ellipses for clarity:

````swift
class IsbnVerifierTests: XCTestCase {

    //...

    func testEmptyIsbn() {
        XCTAssertFalse(IsbnVerifier.isValid(""))
    }

    //...

    static var allTests: [(String, (IsbnVerifierTests) -> () throws -> Void)] {
        return [
            //...
            ("testEmptyIsbn", testEmptyIsbn),
            //...
        ]
    }
}
````

Thanks.

**Comment by kytrinyx** [comment]
Thanks for raising this.

Is this test case missing from the canonical inputs/outputs listed in https://github.com/exercism/problem-specifications/blob/master/exercises/isbn-verifier/canonical-data.json ?

**Comment by p0st0culus** [comment]
Hi, Katrina.

Glad to help.

Yes, it appears to be missing from there, too.

David

**Comment by kytrinyx** [comment]
Thanks! I've gone ahead and moved this into the problem-specifications repository (https://github.com/exercism/problem-specifications/issues/1052) so that we can address it globally.

**Comment by p0st0culus** [comment]
Cool, thanks! :)
