### ISSUE TITLE
New exercise not deploying on JavaScript track

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/exercism.io#3703]
Maybe new deployments are on pause right now?

Two days ago I [merged a PR](https://github.com/exercism/javascript/pull/417) for the `ReverseString` exercise and it has not appeared as available the exercism.io site.

If this _should_ have deployed, please LMK, maybe there is something wrong with the config for the exercise.

**Comment by kytrinyx** [comment]
I've not deployed for a few days, as we've had visitors and I've not had a moment to myself. I'm catching up today.

**Comment by matthewmorgan** [comment]
No worries!  I wasn't sure if the process was automated.
Happy New Year @kytrinyx

**Comment by kytrinyx** [comment]
Thanks, and to you too.

(also: it should be deployed now)

**Comment by matthewmorgan** [comment]
Awesome.  Thanks again!

**Comment by Adam-Morris** [comment]
Recommend closing this issue now.
