### ISSUE TITLE
Java Track - RNA Transcription Problem Incorrect

### ISSUE THREAD

**Issue by ep3998** [exercism/exercism.io#3705]
Looking through the problem statement found on Exercism vs the problem statement found on ROSALIND (which is linked to as the source in the README.md), the problem on Exercism is incorrect.

The transcription would actually be as follows, according to [http://rosalind.info/problems/rna/](http://rosalind.info/problems/rna/):
* `G` -> `G`
* `C` -> `C`
* `T` -> `U`
* `A` -> `A`

The complements listed on Exercism are as follows: 
* `G` -> `C`
* `C` -> `G`
* `T` -> `A`
* `A` -> `U`

My guess is the source might be [http://rosalind.info/problems/revc/](http://rosalind.info/problems/revc/) instead, which is a related problem which closely matches but still isn't quite the same as the premise here.
  
Additionally, the last few tests testing exception handling isn't included in the README.md as criteria for the final code. Good practice yes, but not part of the problem statement.

**Comment by sjwarner-bp** [comment]
@exercism/java

**Comment by kytrinyx** [comment]
I'm closing this in favor of https://github.com/exercism/problem-specifications/issues/1078 as we need to sort out the basics before getting tracks to update this.
