### ISSUE TITLE
Possible bug or error: "Exercises fetched but not submitted: - sorry, tracking disabled for fetching"

### ISSUE THREAD

**Issue by EduardTsoy** [exercism/exercism.io#3707]
Hi!

Why can't I see the current not-submitted exercise with `exercism status go`?
Here is an excerpt from my terminal:
```
/c/Exercism/go/raindrops $ exercism status go

Your status on the go track:

Most recently submitted exercise:
 - raindrops (submitted on January 8, 2018)

Exercises fetched but not submitted:
 - sorry, tracking disabled for fetching

Exercises skipped:
```

Thanks!

**Comment by kytrinyx** [comment]
Because we're no longer tracking fetches in v1 we're unable to provide show the not-submitted exercise. The status was an experiment that we had a lot of trouble with. I believe we'll be able to provide a much better status view with the v2 site.

**Comment by nickborromeo** [comment]
Looks like this answered 👍 Can somebody with close this issue out? 😃

**Comment by kytrinyx** [comment]
Nick, how have I not given you commit on this repo? 🌷
