### ISSUE TITLE
tests still pending

### ISSUE THREAD

**Issue by webersa** [exercism/exercism.io#3710]
Hi,
if I call sbt test, only the first test is processed. Can someone tell me why the other tests are still pending and not being run?
![bildschirmfoto von 2018-01-12 09-32-40](https://user-images.githubusercontent.com/35361434/34866130-b9f34db2-f77b-11e7-8d7e-8c1b2de1568b.png)

**Comment by NobbZ** [comment]
Which track is this?

Usually all but the first tests are pending such that the student can
enable them one after the other and implement his/her solution in a TDD
like manor.

How you enable the tests depends on the language and test framework but is
usually described in the tracks documentation about how to run tests.

webersa <notifications@github.com> schrieb am Fr., 12. Jan. 2018, 09:34:

**Comment by webersa** [comment]
I see, thank you!
