### ISSUE TITLE
Cannot comment or manage exercises in c# track on windows browsers

### ISSUE THREAD

**Issue by martinfreedman** [exercism/exercism.io#3712]
1) Cannot comment on any of my or others exercises. The Write|Preview||History tabs appear but there is no Comment box nor submit buttons. Neither does my comment history appear either (which, if this were working I would want switched off anyway btw)

2) Pressing Manage on my iterations does nothing.

Run on windows 10  and chrome, firefox, edge all latests release browsers. No change in addons (e.g javascript blockers etc.) 

Been happening since yesterday

**Comment by kytrinyx** [comment]
I think this might be related to https://github.com/exercism/exercism.io/issues/3673 -- I will take a look.

**Comment by martinfreedman** [comment]
Continuing in #3673
