### ISSUE TITLE
Can we reword the Parallel Letter Frequency problem in go?

### ISSUE THREAD

**Issue by PPNC** [exercism/exercism.io#3713]
The [Parallel Letter Frequency](http://exercism.io/exercises/go/parallel-letter-frequency/readme) problem uses parallel in its README, but in the tests it uses concurrent and [both are not the same thing](https://blog.golang.org/concurrency-is-not-parallelism).  
Can it be rewritten to use the word concurrent instead of parallel?

**Comment by kytrinyx** [comment]
This is a great question.

Would you mind opening this issue in the [problem specifications](http://github.com/exercism/problem-specifications/issues) repository so that it will be seen by all the people who follow that repository and participate in these sorts of discussions?

**Comment by Insti** [comment]
Dealt with in https://github.com/exercism/problem-specifications/issues/1132
