### ISSUE TITLE
Would you like to help us? 

### ISSUE THREAD

**Issue by codeboards** [exercism/exercism.io#3716]
Hi guys,

My name is Paweł; I'm a founder of Codeboards.io - simple CV creator for developers that will help you to find job that suits you the best.

How does it work? 
All you need to do is to connect your social profiles to our solution and add some extra data to make your profile complete.  It'll take you less than 1 minute! 
Check it out: https://codeboards.io/profiles/93430 - It's one of our user's profile.

Why we need your help? 
We are pretty sure that this profile is not super attractive. You'll  probably create it and forget about it in less than a week. So, what now? 

We've think that the best way to expand our functionalities will be to add some skill verification. Your community has almost perfect tasks base that we can use in our solution. Do you think that both idea will fit each other? If not, then why? If yes, how we can implement it the smart way? Do you have some advice for us?

Thanks a lot for your attention!

all best,
Paweł

**Comment by kytrinyx** [comment]
Paweł, it is inappropriate to solicit attention for your product on other people's open source projects.
