### ISSUE TITLE
Dead link on Github new contributors page

### ISSUE THREAD

**Issue by leaen** [exercism/exercism.io#3717]
It looks like the link in the description for exercism.io has been dead since about June last year. It links to ```docs/getting-involved-in-a-track.md``` which looks to have been removed in #3526

https://github.com/showcases/great-for-new-contributors

**Comment by nickborromeo** [comment]
👋 @leaen thanks for pointing that out! I have updated the link to point to the document referenced in the following [comment](https://github.com/exercism/exercism.io/pull/3526#issue-122767983)

**Comment by kotp** [comment]
Thanks @leaen and @nickborromeo
