### ISSUE TITLE
fetch go

### ISSUE THREAD

**Issue by chlsmith** [exercism/exercism.io#3720]
Installed CLI on Windows.   Trying to fetch my first Go exercise.   No luck.   I went ahead and configured my API Key, but that didn't help.

2018/02/09 08:48:09 error parsing API response - invalid character '<' looking for beginning of value

**Comment by NobbZ** [comment]
This often occurs when you are behind a proxy or firewall. Please tell us more about your environment.

Also sometimes, this happens because of issues in the internet. So if you are not behind a proxy or firewall and the problem does not fix itself in the next hour or so, please try again from another network.

**Comment by chlsmith** [comment]
Ah.   I am behind a proxy.  I'm stuck with the Forcepoint Web Security endpoint on my machine.   Is there a specific URL that I can whitelist?

**Comment by NobbZ** [comment]
AFAIK you need to be able to connect to `exercism.io` and `x.exercism.io` for the CLI to work. The CLI debug does also check for availability of `api.github.com`, but I'm not sure if this is really necessary for the CLI to work.

Also, if you use a proxy you need to activate it via environment variables, as far as I remember you need to set `HTTP_PROXY` and `HTTPS_PROXY` accordingly.

**Comment by chlsmith** [comment]
I'll start with the whitelist.   In every case with the one we're using, it's come down to a whitelist entry.   Quite annoying.   I'll let ya know.

**Comment by chlsmith** [comment]
Between a whitelist entry and configuring the http_proxy environment variable(s), I'm good to go.   Thanks for your quick responses!!

**Comment by kytrinyx** [comment]
@chlsmith Glad you got it sorted!

**Comment by nickborromeo** [comment]
I think this is good to close out 😁
