### ISSUE TITLE
error parsing API response - invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by tatmanblue** [exercism/exercism.io#3724]
I am using the command:
`exercism fetch python`

and I get the following error:
`error parsing API response - invalid character '<' looking for beginning of value`

this is output from exercism debug
```
**** Debug Information ****
Exercism CLI Version: 2.4.1
Exercism CLI Latest Release: 2.4.1
OS/Architecture: windows/amd64
Build OS/Architecture windows/amd64
Home Dir: C:\Users\mr250210
Config File: C:\Users\mr250210\.exercism.json
API Key: ad66*************************f53
Exercises Directory: d:\projects\ex
Testing API endpoints reachability
        * GitHub API: https://api.github.com/ [connected] 94.1934ms
        * XAPI: http://x.exercism.io [connected] 267.0419ms
        * API: http://exercism.io [connected] 429.1792ms
```

I've found other people have had this problem.  I have tried suggestions in those posts.  None of the other answers have resolved my issue.  I would appreciate any thoughts on how to resolve this problem.

thank you
Matt

**Comment by kytrinyx** [comment]
The error message that you're seeing is a symptom, unfortunately, and many different problems lead to seeing it.

The first thing I would try is

```
exercism --verbose fetch python
```

Would you paste this (redacting the API key that will show up)?

I've tried to fetch "as you" (so to speak) and am not getting an error message.

**Comment by kytrinyx** [comment]
A potentially related thread: https://github.com/exercism/exercism.io/issues/3720

**Comment by tatmanblue** [comment]
I agree.  Could be possibly a firewall proxy issue.  I was able to use the above commands on one computer.  But not the other.  The other is connected to a different network.   

How can I proceed with the broken computer?

**Comment by kytrinyx** [comment]
> How can I proceed with the broken computer?

Can you be more specific about what's not working?

**Comment by tatmanblue** [comment]
Per my original post:
I am using the command:
`exercism fetch python`

and I get the following error:
`error parsing API response - invalid character '<' looking for beginning of value`

If you need more information than in the original post, please help me by providing me which commands to run.

Thank you
Matt

**Comment by kytrinyx** [comment]
@tatmanblue One thing to try is to run the command with verbose debugging:

```
 exercism -verbose fetch python
```

If you paste the output of that here, then please remember to delete your API key.

**Comment by tatmanblue** [comment]
I cannot explain it, other than I no longer have the issue.  I guess it was networking related error that is now resolved.  My apologizes for posting this.  I will close it.

**Comment by kytrinyx** [comment]
Glad it's resolved!

**Comment by mikecoll2017** [comment]
For me, it was as simple as having to update the password associated with my network proxy.

**Comment by knepprath** [comment]
I had same issue. When running with verbose I saw I was getting a 503 with `<title>(firewall) Application Blocked</title>`

Turned off firewall and it ran successfully.

**Comment by WladimirTavares** [comment]
For me, give the following answer:
Request GET http://x.exercism.io/v2/exercises/haskell?key=[removed]
Response StatusCode=404
Response Body
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>

**Comment by iHiD** [comment]
@WladimirTavares Looks like you're on a very old version of the CLI there.
