### ISSUE TITLE
Add possibility to select which github account log in with

### ISSUE THREAD

**Issue by eduardi-earnin** [exercism/exercism.io#3725]
I have several github accounts. The exercism.io always uses account that I've logged with in github. But I would like to be able to select which account use when log in to exercism.io

**Comment by kytrinyx** [comment]
@eduardi-earnin This is the intended behavior. We cannot log you into a different account, because we need to go via GitHub to ensure that it is yours.

In [v2](https://github.com/exercism/v2-feedback/blob/master/README.md) you will have more control, and there will be login via email.

**Comment by eduardi-earnin** [comment]
Thanks for the answer.
But I believe that what I asked doesn't contradict with the described behavior. I meant not any account but another github's account. As I understand you use the one which is stored in cookies. And you asked github to authorize the account. I would like to be able to specify which github's account I need to use. As a workaround I can go to github and login with different account then open exercism.io and it will use the new account.

**Comment by kytrinyx** [comment]
@eduardi-earnin we redirect to GitHub. If you're logged in on GitHub, then it will do the oauth dance. If not, it will ask you to log in.

If you're using Chrome you can create a separate profile. Or you could use a private session. I don't know how other browsers do similar things, but I would imagine something like that would be available as well.
