### ISSUE TITLE
Use TLS

### ISSUE THREAD

**Issue by sysadmiral** [exercism/exercism.io#3726]
Hi,

I've just started using exercism.io but I noticed that a lot of the urls for setting up exercism (bash completion file for example) and the exercism.io urls in the config file are all plain http.

I'm not sure of the underlying hosting but I think it would be better if you moved to https urls. Particularly since the documentation gives  instructions for downloading and sourcing a file. I would hope most people check what they download but you can't guarantee that they will.

If I can help in this I'd be glad to.

Cheers,

Amo

**Comment by sysadmiral** [comment]
Just spotted https://v2.exercism.io so I can see this work is underway.

Closing this issue.

**Comment by kytrinyx** [comment]
Thank you! Yeah, it's been a long road getting this sorted out for reasons that I won't go into here :) Thankfully, with v2 this will no longer be an issue.
