### ISSUE TITLE
Trying to submit a file on windows prompt (choco included)

### ISSUE THREAD

**Issue by Andross2** [exercism/exercism.io#3727]
Hi. I'm getting alot of these errors.

> "You're trying to submit a solution file from inside your exercises directory,
> but it looks like the directory structure is something that exercism doesn't
> recognize as a valid file path."

I try to follow this.

> First, make a copy of your solution file and save it outside of
> C:\Users\"NAME"\store

> "Then, run "exercism fetch". Move your solution file back to the correct
> exercise directory for the problem you're working on. It should be somewhere
> inside C:\Users\"NAME"\store"

But then I get this error.

> "It seems like you've tried to submit a solution file located outside of your
> configured exercises directory."

I'm stuck in a configuration loop.

Any help would be great.

**Comment by kytrinyx** [comment]
Hi @Andross2,

What does `exercism debug` say?
Where on the filesystem are you when you're trying to submit?
What is the exact command that you're running when trying to submit?

**Comment by iHiD** [comment]
Hi. As we're launching the new Exercism site and new CLI, I'm closing this issue. If the issue persists on the new site, please reopen it. Thank you! :)
