### ISSUE TITLE
http://exercism.io/languages/erlang/installation

### ISSUE THREAD

**Issue by okdoomfist** [exercism/exercism.io#3729]
Erlang is available in official Arch repositories. Yaourt is not installed by default and generally ill advised to use. 

http://exercism.io/languages/erlang/installation

Current:
Arch Linux: Erlang is available on AUR via yaourt -S erlang 
Should change to read:
Arch Linux: sudo pacman -S erlang

If someone will link me to webpage on github I will modify and submit PR (I've searched I cannot find it).

**Comment by kytrinyx** [comment]
@okdoomfist Excellent. The right place would be in http://github.com/exercism/erlang (https://github.com/exercism/erlang/blob/master/docs/INSTALLATION.md). I'm going to go ahead and close this one ✨ Thanks!
