### ISSUE TITLE
http://exercism.io/contribute/canonical-data claims "we've extracted canonical data for 1 of the 115 problems"; the 1 is too low

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism.io#3730]
http://exercism.io/contribute/canonical-data says "So far we've extracted canonical data for 1 of the 115 problems". I confirmed that this is present in the HTML being served to me so it isn't because of anything to do with JS.

I can demonstrate that the quoted claim is incorrect by showing at least two canonical data files https://github.com/exercism/problem-specifications/blob/master/exercises/acronym/canonical-data.json and https://github.com/exercism/problem-specifications/blob/master/exercises/all-your-base/canonical-data.json. Since these two files exist, it cannot be true that we've only extracted canonical data for just one problem; in the quoted sentence the 1 should instead be a larger number.

It would be more motivational if the page would show the correct value, and it would better help contributors understand the current progress. Contributors would no longer be required to do the mental math of subtracting the "Just N more to go!" count from the total count.

**Comment by petertseng** [comment]
EBWODP: 

> The page should instead show the correct value.

It would be more motivational if the page would show the correct value, and it would better help contributors understand the current progress. Contributors would no longer be required to do the mental math of subtracting the "Just N more to go!" count from the total count.

**Comment by kytrinyx** [comment]
Yeah, this is a bug. Thanks, @petertseng

**Comment by nickborromeo** [comment]
@kytrinyx @petertseng I proposed a fix for this in #3756
