### ISSUE TITLE
Jasmine will not run 

### ISSUE THREAD

**Issue by AnnahGerletti** [exercism/exercism.io#3731]
I am working on Javascript and on the third exercise "leap" I am trying to run `jasmine leap.spec.js` it will not run. Can't figure out why. I am in the right directory, jasmine has been globally installed, the command is correct. 

Is there a step I am missing after you fetch a new exercise? Do things need to be configured?

**Comment by AnnahGerletti** [comment]
No error when I enter `jasmine leap.spec.js`, perhaps my path is wrong? If i type in just `jasmine` then I get 

`No specs found
Finished in 0.001 seconds
Incomplete: No specs found
Randomized with seed 89034 (jasmine --random=true --seed=89034)`

**Comment by kytrinyx** [comment]
Very odd! It seems like `jasmine` is installed, since it is able to complain about not finding any specs.

What does `which jasmine` say?

Here's what I did, and it worked:

```
$ npm install -g jasmine

$ which jasmine
/usr/local/bin/jasmine

$ exercism fetch javascript leap
Not Submitted:    1 problem
javascript (Leap) /Users/kytrinyx/exercism/javascript/leap

New:              1 problem
javascript (Leap) /Users/kytrinyx/exercism/javascript/leap

$ cd /Users/kytrinyx/exercism/javascript/leap
$ jasmine leap.spec.js

# lots of output from failing tests
```

**Comment by kytrinyx** [comment]
(I'll be heading to bed in a little bit—there might be people hanging out in https://gitter.im/exercism/support though, if we don't figure this out before I'm done for the day)

**Comment by AnnahGerletti** [comment]
All good, 

I will continue to work on it. `which jasmin` gives me `/usr/local/bin/jasmine`  same as what you got. 

So I did `exercism fetch javascript leap` 
i got  `2018/02/27 16:36:27 Get http://x.exercism.io/v2/exercises/javascript/leap?key=7bc06dfe811f425491a85da2fa3ab3c1: dial tcp: lookup x.exercism.io: no such host`

don't know what that all means or what to do next.

**Comment by kytrinyx** [comment]
Oh! That makes sense... I don't think it was able to download the exercise.

If you say `ls` in the `leap` directory does it show the `leap.spec.js` file?

**Comment by AnnahGerletti** [comment]
yes it does.

**Comment by kytrinyx** [comment]
Does it contain anything? (E.g. does `cat leap.spec.js` provide any output?)

**Comment by AnnahGerletti** [comment]
yep!

```➜  leap git:(master) ✗ cat leap.spec.js
var Year = require('./leap');

describe('Leap year', function () {
  it('is not very common', function () {
    var year = new Year(2015);
    expect(year.isLeap()).toBe(false);
  });

  it('is introduced every 4 years to adjust about a day', function () {
    var year = new Year(2016);
    expect(year.isLeap()).toBe(true);
  });

  xit('is skipped every 100 years to remove an extra day', function () {
    var year = new Year(1900);
    expect(year.isLeap()).toBe(false);
  });

  xit('is reintroduced every 400 years to adjust another day', function () {
    var year = new Year(2000);
    expect(year.isLeap()).toBe(true);
  });

  // Feel free to enable the following tests to check some more examples
  describe('Additional example of a leap year that', function () {
    it('is not a leap year', function () {
      var year = new Year(1978);
      expect(year.isLeap()).toBe(false);
    });

    it('is a common leap year', function () {
      var year = new Year(1992);
      expect(year.isLeap()).toBe(true);
    });

    it('is skipped every 100 years', function () {
      var year = new Year(2100);
      expect(year.isLeap()).toBe(false);
    });

    it('is reintroduced every 400 years', function () {
      var year = new Year(2400);
      expect(year.isLeap()).toBe(true);
    });
  });
});
```

**Comment by kytrinyx** [comment]
Now I'm very confused, because that looks exactly right. Let me think for a second. Meanwhile... I've redacted your API key from this discussion, but you're going to want to go to http://exercism.io/account/key and hit "reset key" afterwards (and run the command that is listed afterwords to

**Comment by kytrinyx** [comment]
What does `exercism debug` tell you?

**Comment by AnnahGerletti** [comment]
this is what I get with `exercism debug`

```**** Debug Information ****
Exercism CLI Version: 2.4.1
Exercism CLI Latest Release: 2.4.1
OS/Architecture: darwin/amd64
Build OS/Architecture /
Home Dir: /Users/annahgerletti
Config File: /Users/annahgerletti/.exercism.json
Exercises Directory: /Users/annahgerletti/exercism
Testing API endpoints reachability
	* GitHub API: https://api.github.com/ [connected] 273.581746ms
	* API: http://exercism.io [connected] 816.170312ms
	* XAPI: http://x.exercism.io [connected] 2.046538335s

If you are having trouble and need to file a GitHub issue (https://github.com/exercism/exercism.io/issues) please include this information (except your API key. Keep that private).```

**Comment by kytrinyx** [comment]
> http://x.exercism.io [connected] 2.046538335s

So that connected, but it's incredibly slow.

Would you try `exercism --verbose fetch javascript leap`? Go ahead and paste the output here, but you'll want to redact your API key.

**Comment by AnnahGerletti** [comment]
I got it thank you for staying up with me to figure it out.

**Comment by kytrinyx** [comment]
🍰 Glad you got it sorted! I'm closing this out and heading for 💤
