### ISSUE TITLE
THis is more of a question about Jasmine.

### ISSUE THREAD

**Issue by AnnahGerletti** [exercism/exercism.io#3732]
I am new to using Jasmine, I find when something breaks in the code Jasmine does not always out-put an error to my terminal. Why is this. I just get the same line returned. 

like this:
```
➜  rna-transcription git:(master) jasmine rna-transcription.spec.js
➜  rna-transcription git:(master) jasmine rna-transcription.spec.js
➜  rna-transcription git:(master) jasmine rna-transcription.spec.js
➜  rna-transcription git:(master)
```
The first line is good with a green arrow, but the next three are the responses to running the command. 
Nothing happens.

**Comment by kytrinyx** [comment]
@AnnahGerletti would you mind opening this in the @exercism/javascript repo? That will get it in front of the folks who actually know things (as opposed to, you know, just flailing around, which is what I do)

**Comment by AnnahGerletti** [comment]
Hey,

Wonder if you will get this, But what should I move to the repo
@exercism/javascript??

Kind Regards

Annah Gerletti
027 376 5205

**Comment by AnnahGerletti** [comment]
Lol I am still learning how to use Github and all the marvelous features it has. 

OK. 
SO how do I move an issue to an another repo??

**Comment by AnnahGerletti** [comment]
Ok I manually moved it to exercisum/jS. so all good to close this issue.

**Comment by kytrinyx** [comment]
LOL, yes, sorry! I should have been more specific. I've been wanting a "move this issue" feature since forever, but it doesn't actually exist. So "move" in this context means open an issue manually and copy/paste. So sorry about the confusion! ❤️

**Comment by AnnahGerletti** [comment]
Also fyi - THis is that lady you met at Webstock who got really excited
that you were the creator of exercisum.io.

If you did not know that already. THanks for all the help. :-)

p.s I have given away two of the stickers you gave me.

Kind Regards

Annah Gerletti
027 376 5205

**Comment by kytrinyx** [comment]
Oooooh! I knew your picture looked familiar but I couldn't place you. Thanks for the reminder!!
