### ISSUE TITLE
Inconsistency in Bob testing vs readme

### ISSUE THREAD

**Issue by NJM8** [exercism/exercism.io#3733]
Hello, this test in the Bob challenge does not seem to line up with the requirements in the read me.

Here is the test:
```
  it('forceful questions', function () {
    var result = bob.hey('WHAT THE HELL WERE YOU THINKING?');  
    expect(result).toEqual('Whoa, chill out!');
  });
```
Here is the requirement:

 // He answers 'Calm down, I know what I'm doing!' if you yell a question at him.  

Should the test be changed or the requirements changed?

**Comment by Xavier-J-Ortiz** [comment]
@NJM8 I believe it seems like the language is javascript?

I think it's being addressed here: https://github.com/exercism/javascript/issues/492

**Comment by kytrinyx** [comment]
Thanks @NJM8! @Xavier-J-Ortiz is correct that this is being dealt with in exercism/javascript#492 - I'm going to go ahead and close this as a duplicate. 🌷

**Comment by NJM8** [comment]
Thanks!
