### ISSUE TITLE
Javascript / grains - BigInteger spec

### ISSUE THREAD

**Issue by norricorp** [exercism/exercism.io#3734]
Just for fun, I replaced 42 in BigInteger.spec.js with 9223372036854775808 and that amended the expected results. 
There were many fails when run the test.
So my overall comment is that though 42 may well be the answer to everything, it is not a BigInteger.

**Comment by kytrinyx** [comment]
Thank you!
Please open a new issue in http://github.com/exercism/javascript describing the problem and, if you have any ideas about how you think it could be fixed, include that as well.
