### ISSUE TITLE
Same Website and same workflow for Experienceds and Beginners

### ISSUE THREAD

**Issue by Seenivasanseeni** [exercism/exercism.io#3735]
Current exercism tool has the same kind of training for both beginners and experienced ones, though our homepage has two links for each but point to the same. We can try to get the users input on his experince and then can start giving appropriate tasks.

**Comment by kytrinyx** [comment]
Thank you for your input 💖 

At the moment we're working on a completely new website, [v2](https://github.com/exercism/v2-feedback/blob/master/README.md), and will not be making updates to the design or user experience of the existing one.

As such, I'm going to go ahead and close this.
