### ISSUE TITLE
CSharp Clock IEquatable is not required for tests

### ISSUE THREAD

**Issue by Gander7** [exercism/exercism.io#3736]
Unless I'm doing something wrong or I'm entering this issue in the wrong place,

csharp Clock challenge README.md mentions that implementing IEquatable is required for the challenge.
I was able to complete the csharp Clock challenge without implementing IEquatable or creating any equality functions. 

There are no tests, that I can see, that test Equals(Clock), Equals(Object), GetHasCode(), ==, or !=. 
I can provide solution if needed.

If Equatable is required, then maybe add tests for those overriden methods.
If Equatable isn't required, then remove it from the readme?

**Comment by Gander7** [comment]
as an example, instead of 
```
var sut = new Clock(18, 7);
Assert.Equal(new Clock(-54, -11513), sut); 
```
maybe
```
var sut = new Clock(18,7);
var expected = new Clock(-54,-11513)
Assert.True(sut.Equals(expected));
```

**Comment by kytrinyx** [comment]
Thanks @Gander7! I've moved your issue into the C# track repo so that the right people will see it.

Closing in favor of https://github.com/exercism/csharp/issues/523
