### ISSUE TITLE
Is it okay to allow untested submissions?

### ISSUE THREAD

**Issue by pravic** [exercism/exercism.io#3737]
I have discovered that I can submit an empty, untested or even invalid solution. Is this intended?

**Comment by kytrinyx** [comment]
Yes, if you're stuck, then you can submit the untested solution to ask for help.

**Comment by pravic** [comment]
But doesn't `exercism skip` do that?

**Comment by kytrinyx** [comment]
No, `exercism skip` means that you do not intend to submit a solution for the exercise at all, so that when you next say `exercism fetch` you get the following exercise delivered.

**Comment by pravic** [comment]
I see.
Anyway, I still believe that `exercism submit --untested` or `--force` will be more suitable. I mean, it would be better to allow only valid and tested solutions by default. Because currently it looks like noone cares about what you submit :)

**Comment by kytrinyx** [comment]
Thanks for your feedback. We're working on a complete overhaul of the site in [v2](https://github.com/exercism/v2-feedback/blob/master/README.md), and I think this will become much clearer there.
