### ISSUE TITLE
Cannot submit typescript/armstrong-numbers

### ISSUE THREAD

**Issue by gonghao** [exercism/exercism.io#3739]
When I do submit `exercism submit armstrong-numbers/armstrong-numbers.ts`, an error occurred `2018/03/14 18:03:13 unable to submit (HTTP: 400) - Unknown problem 'armstrong-numbers' in TypeScript trac`

I actually cannot find the armstrong-numbers problems on web for TypeScript, but it appeared in `exercism list typescript`, and also I cannot skip it with `exercism skip typescript armstrong-numbers` , the error showed `2018/03/14 17:53:55 Unknown problem 'armstrong-numbers' in TypeScript track`

I cannot fetch new problem neither, what should I do?

Thanks.

**Comment by kytrinyx** [comment]
@gonghao This sounds frustrating! I'm at work right now, but will look into it tonight if nobody else sees what's wrong before that.

**Comment by kytrinyx** [comment]
First observation while waiting for my turn to deploy :-)

I can reproduce this with the following:

```
$ cd path/to/exercism/typescript
$ exercism fetch typescript armstrong-numbers
$ echo "TESTING: ignore this" >> armstrong-numbers/armstrong-numbers.ts
$ exercism submit armstrong-numbers/armstrong-numbers.ts
2018/03/14 11:42:34 unable to submit (HTTP: 400) - Unknown problem 'armstrong-numbers' in TypeScript track

```

**Comment by kytrinyx** [comment]
I *think* this was the result of a race condition in our last deploy. I redeployed and this now seems fine.

I'm going to close this, but if it is still not working for you please holler, and I'll dig deeper.
