### ISSUE TITLE
HTTPS Support?

### ISSUE THREAD

**Issue by rmetzler** [exercism/exercism.io#3741]
With LetsEncrypt issuing TLS certificates for free it would be nice, if you would support HTTPS.

I personally used acme.sh to setup LetsEncrypt with all my domains for me, but I think every other ACME client could do the same.

**Comment by kytrinyx** [comment]
I did set up LetsEncrypt at one point (see https://github.com/exercism/exercism.io/issues/2589) but ended up stuck on Fastly configuration (cc @Randommood -- the above is the issue I was wrestling with).

We have SSL encryption in [v2](https://github.com/exercism/v2-feedback/blob/master/README.md) which is in beta at the moment. I've decided to not put effort into SSL on v1, and rather focus on getting v2 out the door.

**Comment by iHiD** [comment]
The new website supports https. Thanks for caring about this :)
