### ISSUE TITLE
The Pythagorean Triplets problem is poorly described and inconsistent.

### ISSUE THREAD

**Issue by yawpitch** [exercism/exercism.io#3743]
I'm working on the Python track specifically, but I notice that across many of the language tracks the tests and examples do not reflect the description of the problem:

> Pythagorean Triplet
> A Pythagorean triplet is a set of three natural numbers, {a, b, c}, for which,
> a**2 + b**2 = c**2
> For example,
> 3**2 + 4**2 = 9 + 16 = 25 = 5**2.
> There exists exactly one Pythagorean triplet for which a + b + c = 1000.
> Find the product a * b * c.

In the Python, Rust, and Haskell tracks, for instance, there are no tests whatsoever related to the "find the product a*b*c" statement, and all three require different constructs than what's implied by the problem description and title. The Javascript track, however, does require that the work produced can calculate the product.

**Comment by kytrinyx** [comment]
@yawpitch Thanks! It's observations like yours that help us make the exercises consistently good. (Often they start off as a kind of half-assed idea, and improve in iterations).

I've gone ahead and copied this issue over to the problem specifications repository, where a lot of the maintainers who work on exercises and exercise definitions hang out. https://github.com/exercism/problem-specifications/issues/1211

Would you be willing to suggest improvements to the description that the READMEs are based on there? https://github.com/exercism/problem-specifications/blob/master/exercises/pythagorean-triplet/description.md

Also, if you have ideas about a consistent set of inputs and outputs that would make a good exercise, that would be fantastic. This exercise doesn't have a canonical-data.json file, so there's bound to be all sorts of variation in the various implementations. We've got some docs about canonical data files: https://github.com/exercism/docs/blob/05ee516610d29a6aa79dba2dddbd5ae20e1916a5/you-can-help/improve-exercise-metadata.md

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this issue in favor of the new one (https://github.com/exercism/problem-specifications/issues/1211).
