### ISSUE TITLE
Cannot submit exercism exercise

### ISSUE THREAD

**Issue by michellepetryszyn** [exercism/exercism.io#3744]
I keep getting error messages when trying to submit. Example of error message:
"unable to submit - Bad path to exercise file.

You're trying to submit a solution file from inside your exercises directory,
but it looks like the directory structure is something that exercism doesn't
recognize as a valid file path."

I have the most current version. Not sure what the problem is?

**Comment by NobbZ** [comment]
Well, as the error message states you are trying to submit a file from a position where it is not expected.

Well, or you are trying to submit a file that doesn't exist, as far as I remember there have been some bugs in the order of those checks and I am not sure if they are fixed yet…

Please tell us what operating system you are using, from which directory you are trying to submit and which command you are using to do so. Also please show us the output of `exercism debug` but please remove your API key from that output.

**Comment by michellepetryszyn** [comment]
macOS Sierra Version 10.12.6

I am trying to submit from the directory: "/Users/michellepetryszyn/Desktop/exercism /hamming" 
I have configured this directory in exercism via the command "exercism configure --dir="
I am trying to submit my file through the command "exercism submit hamming.rb"

I have included a screenshot of my terminal with my latest attempt. Thanks in advance for your help!

<img width="563" alt="screen shot 2018-03-22 at 3 09 08 pm" src="https://user-images.githubusercontent.com/18151918/37801415-c6b42942-2de3-11e8-823e-c104eec98c60.png">

**Comment by michellepetryszyn** [comment]
Screenshots without API key
<img width="676" alt="screen shot 2018-03-23 at 11 33 55 am" src="https://user-images.githubusercontent.com/18151918/37847464-25d5a18a-2e8e-11e8-8236-a2dac00e7042.png">
<img width="596" alt="screen shot 2018-03-23 at 11 34 01 am" src="https://user-images.githubusercontent.com/18151918/37847465-25ed1fc2-2e8e-11e8-96f6-8f0cd82e9785.png">

**Comment by NobbZ** [comment]
The apikey is now know to everyone who is subscribed to this repository. Please change it! It has been sent by mail.

Also your path is mangled up, I will write up some solution to your problem when I'm back home and kids are in bed. Will take 2 to 3 hours.

**Comment by michellepetryszyn** [comment]
Just reset it! Thanks!

**Comment by NobbZ** [comment]
Okay, now I have some time to write about my observations.

You set your exercism base dir to `/Users/michellepetryszyn/Desktop/exercism /hamming` (including a space!).

Since this is a basepath, you need to put the solution for rubys hamming exercise to `/Users/michellepetryszyn/Desktop/exercism /hamming/ruby/hamming/hamming.rb`

But what you probably really want, is to change your exercism dir to `/Users/michellepetryszyn/Desktop/exercism` and then put your ruby hamming solution to `/Users/michellepetryszyn/Desktop/exercism/ruby/hamming`.

**Comment by michellepetryszyn** [comment]
It worked! Thank you so much for your help. Really appreciate it!
