### ISSUE TITLE
Layout when submitting a comment that contains a link

### ISSUE THREAD

**Issue by cyborgthefirst** [exercism/exercism.io#3746]
Hey, 

this happened when I submitted a comment that contained a hyperlink.

Browser: Safari Version 11.0.3 (13604.5.6)

<img width="1440" alt="screen shot 2018-03-25 at 21 41 48" src="https://user-images.githubusercontent.com/14994778/37879229-236d90c2-302a-11e8-8a8c-a6abbcabb363.png">

**Comment by kytrinyx** [comment]
Ah, yeah, that's no good! Thanks for the report.
