### ISSUE TITLE
ISBN Verifier Test Suite Omits Test Case

### ISSUE THREAD

**Issue by dnicolaev** [exercism/exercism.io#3747]
Hello, I worked on ISBN verifier in Python - my solutions passed all the tests.
However there is one case that is not covered - it is with a non digit character in the middle.
And the solution I created - will pass this test case also. But it should not.
3598P1581X

**Comment by kytrinyx** [comment]
Thanks for reporting this! We always need help finding those pesky edge cases. I've opened an issue over in the problem-specifications repository so we can get this sorted. If you want to help suggest inputs and outputs over in that issue that would be great. https://github.com/exercism/problem-specifications/issues/1212

Once that gets hashed out we'd love your help updating the Python test suite with the new test case as well! https://github.com/exercism/python/blob/master/exercises/isbn-verifier/isbn_verifier_test.py

I'm closing this issue in favor of the one in problem-specifications.
