### ISSUE TITLE
Include benchmark results in submit

### ISSUE THREAD

**Issue by JoannaGuse** [exercism/exercism.io#3750]
Hi. 
I have a suggestion for the Exercism.io website.

I'm working my way through the go examples. I'm a complete newbie, and while I can write code to pass the tests, I want to learn the most efficient way of performing a tast.

When I submit my code, I look through other people's code a a learning tool, but I find it hard to assess whether other people's code implementations are better than mine. At the moment, I assess based on readability and length of the program. However, it would be good to be able to access benchmarking tools for other people's projects. 

I'm suggesting that in the submissions page, add an online compiler like they have in the golang documentation pages, so that we can run benchmarking on someone else's solution online. 
Is this something that would be possible?

**Comment by kytrinyx** [comment]
> I'm suggesting that in the submissions page, add an online compiler like they have in the golang documentation pages, so that we can run benchmarking on someone else's solution online.
Is this something that would be possible?

While it is technically possible, we do not have the resources to do this.

There has been some discussion about benchmarks here: https://github.com/exercism/discussions/issues/121

I'm going to go ahead and close this issue in favor of the discussion above. If you have any thoughts, ideas, or feedback that have not been included there, please add them!

**Comment by tom-harvey** [comment]
Wait, is it too obvious to mention that you can just grab their submission with a single click and run it on your local machine? You'd need to do that anyway to generate compare-able benchmark results.

**Comment by kytrinyx** [comment]
@tom-harvey not too obvious to mention that :)

It's a good point. Thank you.
