### ISSUE TITLE
suggestion for website

### ISSUE THREAD

**Issue by flatman123** [exercism/exercism.io#3751]
Hello, Good Morning

I don't have any issues, however I do have a suggestion for your website.
I would like to suggest that you add a direct-link back to 'Available-Exercises" page.

For instance:
If i'm already working with a particular language ( JavaScript or Python), I find that I first need to go to Languages-Page to then click my preferred language, to then click Available-exercises. If i'm already working in JavaScript labs, there should probably be a hyperlink up top somewhere that would direct me back to the "Available-Exercises" page for JavaScript so i can choose the next exercise.

-Best Wishes-

**Comment by kytrinyx** [comment]
Hi @flatman123, thank for the suggestion.

We're working on a complete redesign, which I think will make this easier. You can see the work in progress at [v2](https://github.com/exercism/v2-feedback/blob/master/README.md).

**Comment by flatman123** [comment]
awesome, thanks for advising

**Comment by bae-yonghan** [comment]
Issue

**Comment by iHiD** [comment]
Hi. As we're launching the new Exercism site, I'm closing this issue. If the issue persists on the new site, please reopen it. Thank you! :)
