### ISSUE TITLE
Cannot able to see a specific persons profile

### ISSUE THREAD

**Issue by erkantaylan** [exercism/exercism.io#3752]
When I try to visit his profile http://exercism.io/daveyarwood 
I get `Sorry! That's our fault!`. I can perfectly see other people's profile
I tried with
Firefox Quantum 60.0b11 (64-bit)
Google Chrome 65.0.3325.181 (64-bit)

**Comment by NobbZ** [comment]
That user has probably a faulty entry in the database.

@kytrinyx needs to take a look into it and repair in person, AFAIK there is no one else who is able to do that.

**Comment by kytrinyx** [comment]
I'll take a look at this today!

**Comment by kytrinyx** [comment]
This should be sorted now. Sorry for the trouble!
