### ISSUE TITLE
Go just added a logo

### ISSUE THREAD

**Issue by criscola** [exercism/exercism.io#3757]
Hello. This is a minor aesthetic improvement, however, I'd like to be the first to point this out. Go's devs just added a logo (the Gopher is actually a "mascotte" and not a logo). You can read the (short) article about it [here](https://blog.golang.org/go-brand).

I think you should replace the Go mascotte with the new logo everywhere in the website.

**Comment by NobbZ** [comment]
I did not found a license for the logo, but at least the [brand guidelines](https://storage.googleapis.com/golang-assets/go-brand-book-v1.0.pdf) give an example of using it in various colorschemes.

They are giving this examples on page 14.

Also on page 15, they give examples of some no-gos of how to use it.

We need to make sure, that the usage on exercism complies to the terms of using the logo. So we should actually take a closer look if there is a proper terms of use available or only those guidelines.

**Comment by criscola** [comment]
There is. If you look at the footer of the page, it states: "Except as noted, the content of this page is licensed under the Creative Commons Attribution 3.0 License,
and code is licensed under a BSD license.".

**Comment by NobbZ** [comment]
Well, the "noted" is actually a link which brings me to a site which contains this text:

https://developers.google.com/site-policies#restrictions

> Google's trademarks and other brand features are not included in this license. Please see our standard guidelines for third party use of Google brand features for information about this usage.

And I consider the logo as an "other brand feature".

**Comment by d-pollard** [comment]
For the time being, I don't think the image should be changed. If you sat a new (a week) GO developer down and asked them to pick which one they recognize, I would be money they will pick the Gopher.  The gopher has been around for **YEARS**, compared to the new logo.

Changing is viable when the logo becomes more recognized than the gopher.

A google search for "golang" produces:
![selection_125](https://user-images.githubusercontent.com/16292606/39505916-19011fee-4d9b-11e8-9c50-12b4f42cb736.png)

**Comment by kytrinyx** [comment]
I would like to leave the gopher in place. We do not need to match the logos of the languages for the icons that we use, and the gopher is a lot like GitHub's octocat in that the community is allowed to "remix" it to suit their purposes.

FYI @exercism/go @iHiD 

I'm going to go ahead and close this, but if anyone feels strongly that we've not yet had a thorough enough discussion about this, I'm open to hearing more thoughts on the matter.
