### ISSUE TITLE
Link on contribute page is broken

### ISSUE THREAD

**Issue by GrahamLea** [exercism/exercism.io#3758]
> Check out the section about [implementing a new exercise](https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/implementing-a-completely-new-exercise.md)

The link above on the contribute page 404s.

**Comment by nickborromeo** [comment]
@GrahamLea thanks for reporting that. It looks like that page was moved in https://github.com/exercism/docs/pull/71

I have created a PR to fix this.
