### ISSUE TITLE
Prioritize solutions by my team in the list of all solutions

### ISSUE THREAD

**Issue by vassilevsky** [exercism/exercism.io#3759]
Hello :)

I'm a member of a team on Exercism.

When I'm looking at the list of community solutions to the exercise I just solved myself, it would've been awesome to see solutions from my team first.

I glanced at the `TrackStream` class and didn't find anything like that.

I could try adding this if you think it's a good idea.

What do you think?

**Comment by kytrinyx** [comment]
@vassilevsky Thanks for the suggestion!

We are working on a completely new design for the site, which you can see on [v2](https://github.com/exercism/v2-feedback/blob/master/README.md) -- we will also be reworking all of the team-related features.

I don't know how long it will take to get the v2 site launched, so if you feel like it's worth it even in the short term, then go for it. If not, I would hold off!

I'm going to close this issue, but please do feel free to open a pull request with suggested changes if you decide to work on this.

**Comment by vassilevsky** [comment]
Thank you. I've seen the new site. It's awesome! I hope that you consider this case when you design the new team features.
