### ISSUE TITLE
exercism on cloud9.io

### ISSUE THREAD

**Issue by mark-dames** [exercism/exercism.io#3766]
Hello,

Is there an up to date tutorial how to set up exercism on cloud9.io? This tutorial does not work anymore: https://www.youtube.com/watch?v=r0TnwOLxoks&t=342s

**Comment by NobbZ** [comment]
I do not have a cloud9 account, so I can not test it, but what is it you are experiencing problems with?

C9 is just a Linux, so you should be fine following the Linux instructions from the page.

**Comment by mark-dames** [comment]
It works indeed with the Linux instructions. Thanks!
