### ISSUE TITLE
Tagging/filtering system for the purpose of learning

### ISSUE THREAD

**Issue by biox** [exercism/exercism.io#3767]
I've been using exercism for a few months now and it has been unparalleled in getting me interested in writing code every day.

That being said, I have a few suggestions from my very newbie perspective. I know that this has been discussed before, but those conversations are currently closed and I couldn't find a relevant open topic to post this in.

When I finish an exercise, I'm never confident about my solution (being a rather new programmer) - so I scour around other peoples' answers, offering advice where possible. This is great, but I'd like some method to understand what a 'good' solution to the problem at hand might be.

One way I envision this is using a tag system with several pre-defined tags.

The tags would be, for example:

- clever
- performant
- simple
- etc

A user can simply select a tag to 'upvote' the solution at hand for that tag (this does not relate to comments, only solutions). You can only select one tag per submission, and it would be encouraged the way that comments are (but not forced, I would fear a regression in quality).

This way, as a user, I could get a feel for the 'cleverness/performance/etc' of a particular solution compared to mine, and aspire to make my own code better. As it stands, I don't know enough to make this distinction.

The good thing about this is that we already have the 'like' system - the tag system could be an extension of this.

I'd like to start that discussion - or, if that discussion is already happening, I'd like to contribute to it.

Please do let me know if I'm off-base, or if this should be posted elsewhere.

**Comment by kytrinyx** [comment]
@biox You are completely on-base with this! In fact... for [v2](https://github.com/exercism/v2-feedback/blob/master/README.md) which we are actively working on we are making two improvements that I think will help with this:

1. We have built mentoring into the user experience to be a first class concept, and are actively recruiting mentors (see http://mentoring.exercism.io/)
1. We have added tags and filters that you can use on the published solutions.

The data on v2 is a mess right now (I expect to do a new data import in a week or so), and of course none of our historical data uses those tags, so it's going to be tricky to get a feel for the filtering, but I *think* this is going to be addressed in a good way, at least good enough that we can iterate once we're live.

Thank you so much for sharing your thoughts!

**Comment by biox** [comment]
Awesome, that's perfect! Knowing that, I'll go ahead and close this issue and get to testing the v2 site!
