### ISSUE TITLE
javascript - queen attack

### ISSUE THREAD

**Issue by norricorp** [exercism/exercism.io#3770]
The unit test for error 'cannot occupy the same space' will pass when no error is caught and returned.

**Comment by kytrinyx** [comment]
Thank you for reporting this. Would you mind opening the issue in http://github.com/exercism/javascript?

**Comment by nickborromeo** [comment]
It looks like this issue was indeed opened in https://github.com/exercism/javascript/issues/546 and it has been resolved. 🎉
