### ISSUE TITLE
Escaping bug in page redirect after login

### ISSUE THREAD

**Issue by bcc32** [exercism/exercism.io#3771]
While not logged in, accessing a login-required URL like `http://exercism.io/tracks/go/exercises/tree-building` redirects to a GitHub login page like so: `http://exercism.io/please-login?return_path=/tracks/go/exercises/tree-building`.

Pressing on the GitHub login button takes me to `http://exercism.io/dashboard#x2F;tracks&#x2F;go&#x2F;exercises&#x2F;tree-building` rather than `http://exercism.io/tracks/go/exercises/tree-building`.

When hovering over the GitHub login button, the URL displayed is:

```
https://github.com/login/oauth/authorize?client_id=c2bb2902de1cc6ef6902&redirect_uri=http://exercism.io/github/callback&#x2F;tracks&#x2F;go&#x2F;exercises&#x2F;tree-building
```

So I suspect somewhere there is a confusion between HTML escaping and URL escaping, but I don't know the website code so I wouldn't be able to pinpoint where that happens.

**Comment by kytrinyx** [comment]
Ah, yepp. That's no good! Thanks for reporting this. Should be a fairly straight-forward fix (I'll see if I can get to it today).
