### ISSUE TITLE
Improve "Other Implementations" filtering

### ISSUE THREAD

**Issue by jonatascb** [exercism/exercism.io#3772]
Hello, I would like to suggest an improvement in the filtering of the "Other Implementations" session. For example, the results could be ordered by number of iterations, comments, date or a more advanced score (e.g. using a score from Lint).

**Comment by kytrinyx** [comment]
Hi @jonatascb -- We're working on [v2](https://github.com/exercism/v2-feedback/blob/master/README.md) which will hopefully launch in the next couple of months. We have a lot more functionality for filtering in that one.

I'm going to go ahead and close this, and once we launch v2 we can talk about where we might be able to improve further!

Thanks so much for your suggestion 🌷 🌸 🌷
