### ISSUE TITLE
Feature request: List of reviewed iterations

### ISSUE THREAD

**Issue by knatten** [exercism/exercism.io#3777]
On the profile page, we currently report the number of completed problems and the number of reviewed iterations.

There's also a list of completed problems, but no list of reviewed iterations. I suggest we add that.

**Comment by kytrinyx** [comment]
Thanks for the suggestion, @knatten. We've put a feature freeze on the current exercism.io site, in anticipation of [v2](https://github.com/exercism/v2-feedback/blob/master/README.md) which should be available shortly.

We've taken a fundamentally different approach to the entire user interface, so this suggestion doesn't translate directly.

If you want to give the v2 site a try, then we have a repo for feedback here: https://github.com/exercism/v2-feedback/issues

Thanks! 💙
