### ISSUE TITLE
language suggestion: Regex

### ISSUE THREAD

**Issue by mazeto** [exercism/exercism.io#3778]

**Comment by kytrinyx** [comment]
Thanks @mazeto. There are so many cool things to learn, and it's honestly been a bit of a struggle to figure out what falls within the scope of what Exercism is trying to tackle.

While regex _is_ a programming language, it's not a very good fit for the Exercism format. My favorite resource for regex is https://regexcrossword.com/

I've written a bit about how I think about what makes a good Exercism track in [the documentation](https://github.com/exercism/docs/blob/master/about/scope-of-a-track.md
) and also in [the newsletter](https://tinyletter.com/exercism/letters/what-exercism-is-and-isn-t).

You can also see the questions we ask at the start when someone requests a new language track here:
https://github.com/exercism/request-new-language-track/issues/new

Thanks for the suggestion 🌷
