### ISSUE TITLE
Odd styling of new mentors banner

### ISSUE THREAD

**Issue by mgmatola** [exercism/exercism.io#3781]
The mentors banner that got added today doesn't have an explicit z-index set, so when a user scrolls down, the main page content will overlap with the mentors banner.

There a several ways to fix this. One would be to set the z-index in the #mentors-banner style rule to something like 1030 (which would then match the z-index of the navigation bar). Another would be to add the navbar-fixed-top class to the div with id #mentors-banner.

**Comment by nickborromeo** [comment]
https://github.com/exercism/exercism.io/pull/3783 has fixed this! 🎉 Thanks @mgmatola for reporting this!
