### ISSUE TITLE
Ipad nav too long

### ISSUE THREAD

**Issue by plippe** [exercism/exercism.io#3785]
The navigation bar is too wide, and wraps on Ipad. Might need to use the mobile nav instead.

![screen shot 2018-06-14 at 10 03 14](https://user-images.githubusercontent.com/1381691/41402427-2ebe3a6a-6fba-11e8-87ee-26f47d72483b.png)

**Comment by kytrinyx** [comment]
Ah, yes, I think you're right that mobile nav would work better here.
