### ISSUE TITLE
Strange error message if I click on Archive and no exercise is selected

### ISSUE THREAD

**Issue by bdf74** [exercism/exercism.io#3786]
On my profile page, if I click on the Archive button and no exercise is selected, a strange error message appears:

"Sorry! That's our fault!

If you'd like to provide information about this error or request help, please visit our GitHub issues page. You can also get help here."

Using Windows 10 and Firefox 60.0.2.

![cattura](https://user-images.githubusercontent.com/1384899/41404881-a9676c74-6fc8-11e8-81d9-64241c667fb2.JPG)

**Comment by kytrinyx** [comment]
Thanks for the heads up--definitely a bug on our end.

**Comment by kytrinyx** [comment]
I think either approach would be fine, but some validation in the archive button would be really nice, as it would avoid the problem in the first place.

**Comment by NobbZ** [comment]
Good enough for the dying v1 I think, but in my opinion, one shouldn't rely on JS only without having a server seide fallback…

**Comment by nickborromeo** [comment]
@NobbZ I can also add the a flash message when an error is caught to notify the user that something went wrong instead of showing the 500 page.

**Comment by iHiD** [comment]
Hi. As we're launching the new Exercism site, I'm closing this issue. If the issue persists on the new site, please reopen it. Thank you! :)
