### ISSUE TITLE
Ability to fetch a random track would be fun

### ISSUE THREAD

**Issue by lestephane** [exercism/exercism.io#3795]
trying to solve a problem in a programming language i've not used before is quite fun.

Maybe a kind of 'exercism fetch random' capability would be useful to others too?

My current implementation
```bash
$ random_track=$(exercism t | grep problem | tr -s ' ' | sed -e "s/Perl \([56]\)/Perl_\1/g" | cut -d ' ' -f 3 | shuf -n 1); exercism fetch "${random_track}"

```

**Comment by kytrinyx** [comment]
That's pretty neat, @lestephane -- we won't be building this functionality into the site itself. It's pretty cool that you have a bash script to do it.

**Comment by nickborromeo** [comment]
Can we go ahead and close this issue out? I also second that the bash script is cool! 👍

**Comment by lestephane** [comment]
I've switched to the new version of exercism, and i don't see any way to achieve what i used to be able to achieve with my bash script. In particular, one cannot, using the cli, list all tracks, and the exercises currently available to the user in each track.

**Comment by xiegeo** [comment]
@iHiD can we open this issue again?

After doing the Hello Would exercise and the one after. I get stuck on the main path waiting for review. However, there are too many side quests. I want a script that picks one for me.

I can build my own if there is an API for it.

**Comment by iHiD** [comment]
I think your suggestion is different. Listing all avaliable exercises is a nice idea for the CLI. If you open an issue for that, we can discuss adding it to the roadmap. I recommend also adding a comment to https://github.com/exercism/exercism/issues/4087 about the API idea. Thanks :)
