### ISSUE TITLE
exercism.io is down

### ISSUE THREAD

**Issue by henryaj** [exercism/exercism.io#3797]
Seeing this message when I navigate to the site:

```
{
  "error": "\n-------------------------------------------\n\nWe launched a brand new version of Exercism.\n\nUpgrade your client with:\n\n    exercism upgrade\n\nOr delete the old CLI and follow the instructions\non the new site to get the new one.\n\n"
}
```

**Comment by kytrinyx** [comment]
@henryaj We are in the middle of a large migration. When you go to the site you should see a notice about this: https://exercism.io/

The message you are seeing is what we are serving if you call the API, for example with the CLI.

(unfortunately I forgot to consider a different message while we're migrating, and only thought through what the message should be for the CLI if you tried to call the new site with the old CLI).

The long and short of it is: we should be back within the next day.

**Comment by henryaj** [comment]
Cool, thanks. I'm now seeing a migration page (I was seeing the JSON
message in my browser before).

Good luck with the move!

**Comment by seccobit** [comment]
I guess you are still upgrading? 
I have tried to submit solution from OS Terminal and I get the following error: 

----------------------------------------------
We launched a brand new version of Exercism.

Upgrade your client with:

    exercism upgrade

Or delete the old CLI and follow the instructions
on the new site to get the new one.
------------------------------------------------
Upgraded with 'exercism upgrade' but when re-attempting to submit the exercise, it does the same thing...
Currently on: exercism version 2.4.1

**Comment by c-dante** [comment]
Hey guys! @kytrinyx -- how goes the upgrade? The happy block is very cute.

**Comment by kytrinyx** [comment]
>  The happy block is very cute.

I agree :) It makes me happy to see it every time.

The site is back up! https://exercism.io/

**Comment by seccobit** [comment]
I am not a good liar, I preferred the little devil's horns, BUT I think new website, is much much better and very user friendly and very intuitive! Great job!! and thanks for keeping this running...
