### ISSUE TITLE
Error submit a solution

### ISSUE THREAD

**Issue by redhatmk** [exercism/exercism.io#3799]
Hello,

After the new version was online I upgrade my client:
`exercism upgrade`

After that I tried to summit my solution but I got this message:

```
Error: 

    Welcome to Exercism!

    To get started, you need to configure the the tool with your API token.
    Find your token at

        /my/settings

    Then run the configure command:


        exercism configure --token=YOUR_TOKEN
```

I configure my token:

`exercism configure --token=myToken`

but when I tried to resumit my solution I got this message:

```
exercism  submit Isogram.swift 
Error: couldn't find it
```

Do I need to do any changes on my client to make it work?

(By the way I'm using MacOS)

**Comment by NobbZ** [comment]
Have you checked on the site if you have joined the appropriate track and fulfill the preconditions for that exercise?

**Comment by guygastineau** [comment]
Yeah, I am having the same problem submitting beer_song.rb.  I finished it the first day of the migration not realizing that it was happening.

@Nobbz, I went into the new website set myself up and accepted the transfer of all the other non-core exercises I had done.

It still won't submit even though it is unlocked.  The error message says it can't find it.  If I run exercism submit with no arguments I get an error saying that there is no beer_song.json.  Does this mean that we have to re-download the exercise in order for the missing .json to explain things to the cli?

**Comment by robjd81** [comment]
Similar problem here. I configured my token and workspace, which appears to take effect at the time, but when I run the troubleshooting command neither are configured.

**Comment by guygastineau** [comment]
@robjd81 I got the token and workspace to show up after setting the workspace manually with the flag --workspace=/my/dir .  I also noticed that I had to accept all of the core exercises and then publish them.  To be honest that was way more button clicks than I like.  I'm a bit mouse adverse even though ratpoison isn't my wm.

Even after getting all of those through it still can't find the exercise.  I appreciate all the work put into re-imagining exercism but now it is so user-friendly that I can't seem to use it very successfully.

**Comment by guygastineau** [comment]
api reachability says I am connected to 
Exercism:
    * https://api.exercism.io/v1/ping  ## it says v1
    * [connected]
    * 589.773481ms

Should it be connected to V2?

**Comment by nchaffee** [comment]
I had the same issue and for me the answer was to use the new CLI to `exercism download` the exercise I had fetched and solved before the site update but never submitted. That provided a `.solution.json` file in the a new folder that I could move into the old directory with the solution file I wanted to submit and voila, `exercism submit /myfile` worked just fine. Thanks for the tip @guygastineau !

**Comment by guygastineau** [comment]
@nchafee great news. I figured that would work but I had trouble finding documentation for the download command. I suppose I can run exercism download --help though.

**Comment by guygastineau** [comment]
Just wanted to confirm that 
exercism download -t trackname -e exercise
worked.

**Comment by iHiD** [comment]
There are docs here: http://exercism.io/cli-v1-to-v2

If there's anything there that's not clear or working, please leave a pull request on there. Thank you!

**Comment by guygastineau** [comment]
Thanks @iHiD. Those docs seem pretty straight forward.

**Comment by redhatmk** [comment]
@iHiD I follow the instructions [ http://exercism.io/cli-v1-to-v2]( http://exercism.io/cli-v1-to-v2). 

1. `exercism upgrade
Your CLI version is up to date.`

2. `exercism download --exercise=isogram --track=isogram
Error: Track not found`

Can you please let me know if theres anything I can do to fix this error?

**Comment by NobbZ** [comment]
Use a proper track, aka language.

**Comment by redhatmk** [comment]
@NobbZ  you were right the correct syntax is `exercism download --exercise=isogram --track=swift`
