### ISSUE TITLE
next solutions to mentor shows exercises of a language I am not a mentor of

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3807]
I joined the "swift" track yesterday as a student, because I wanted to test something with an empty track. Now I realize, I have swift exercises in the solutions to mentor, also I can use Swift as a filter and it is displayed on my public profile.

Since I do not know anything about swift, I'd prefer to not beeing a mentor.

Is this probably leftover code from the previous betas where joining a track made you a mentor?

I am not a mentor on tracks that have at least one submitted solution.

This also means, that we need to check carefully who of the mentors of a track is a mentor because he wants to and who is a mentor because of this bug…

**Comment by iHiD** [comment]
So the main problem is fixed by https://github.com/exercism/website/pull/166/files

I now need to work out how to clear out the incorrect records from the db.

**Comment by iHiD** [comment]
This *should* now be fixed, so I'm closing it. If you see this same behaviour reoccur please reopen it. Thanks for reporting, @NobbZ 💙
