### ISSUE TITLE
Submit Error: couldn't find it

### ISSUE THREAD

**Issue by janus** [exercism/exercism.io#3808]
I got this message each time I try to submit; 
exercism submit isogram.c
~/exercism/c/isogram/src$ tree
.
├── isogram.c
└── isogram.h

0 directories, 2 files

~/exercism/c/isogram/src$ exercism submit isogram.c Error: couldn't find it

When I tried exercise 1 it worked , this issue started after I upgraded  exercism. What is it that I am doing wrong?

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.2
Latest:  3.0.2

Operating System
----------------
OS:           linux
Architecture: amd64

Configuration
----------------
Home:      
Workspace: /home/eva/exercism
Config:    /home/eva/.config/exercism/user.json
API key:   *****************************

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 468.457524ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 6.07206924s

**Comment by janus** [comment]
@NobbZ 
Solved

**Comment by ayrat555** [comment]
@NobbZ Can you describe please how did you resolved the issue?

**Comment by NobbZ** [comment]
As I never had this issue so far, I have not solved it yet ;)

But the necessary steps are detailed at https://exercism.io/cli-v1-to-v2

**Comment by ayrat555** [comment]
I'm sorry that message was meant for @janus. I've already tried commands from https://exercism.io/cli-v1-to-v2 but they did not work for me.

**Comment by NobbZ** [comment]
When downloading the exercise what output did you get?

**Comment by NobbZ** [comment]
Then you have not fulfilled the requirements. Can you access the exercise from your tracks dashboard?

**Comment by ayrat555** [comment]
thank you, I was confused by new features.

Also, I had to remove my old exercism workspace. I was getting some kind of errors related to json file
