### ISSUE TITLE
A mentor will leave you feedback shortly" and submission status locked in Independent mode

### ISSUE THREAD

**Issue by bdf74** [exercism/exercism.io#3809]
In Independent mode, why do I see the message "Well done on submitting. A mentor will leave you feedback shortly" after submitting a solution? Shouldn't mentoring be disabled in independent mode, as the websites states?
Also, this prevents me for doing anything with my submission: I can't publish it, mark it as completed or archive it. Am I missing something?
![cattura](https://user-images.githubusercontent.com/1384899/42723509-37227010-875f-11e8-94e8-af17ce41205b.jpg)

**Comment by iHiD** [comment]
@bdf74 Thanks for reporting. I've fixed the copy at the top, and also added in the missing "Complete Exercise" button. Will deploy shortly. Please close this if this seems correctly functional for you now, or let me know if something is still wrong. Thanks.

**Comment by bdf74** [comment]
Awesome,  looks perfect now. Thanks!

**Comment by akidhmohamed123** [comment]
I couldn't go further as I see "Well done on submitting. A mentor will leave you feedback as soon as possible." It was there for more than 3 days.
![capture1](https://user-images.githubusercontent.com/28685904/50544863-16f72980-0c29-11e9-8b88-542c2992bbdd.PNG)

**Comment by F3PiX** [comment]
Hi @akidhmohamed123
Mentoring can take a bit longer at the moment, because of the holidays.  
If you don't want to wait for mentoring, consider switching to Independent Mode, maybe even temporarily.

**Comment by akidhmohamed123** [comment]
K thank you for the feedback.
