### ISSUE TITLE
Side exercises section lists deprecated exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism.io#3813]
On the C# track, there are four deprecated issues, which are rendered on the [side-exercises section](https://exercism.io/my/tracks/csharp#side-exercises):

![image](https://user-images.githubusercontent.com/135246/42723590-fcd70ed2-8760-11e8-9443-01616cb4f9ab.png)

**Comment by iHiD** [comment]
@ErikSchierboom Thanks for reporting :)

Two things
1) They only appear for people who have previous submitted iterations to them as we don't want people to lose their work.
2) The styling was broken but should now be fixed.

If (2) is ok for you now and you're happy with (1) could you close this pls? Thanks!

**Comment by ErikSchierboom** [comment]
@iHiD Yep, I'm perfectly happing with the result. Thanks for the quick fix!
