### ISSUE TITLE
Some locked exercises are now unlockable for legacy users

### ISSUE THREAD

**Issue by yawpitch** [exercism/exercism.io#3817]
It appears that if you completed the Core track in a given language > 14 days before migration you may have Extra Exercises that are locked, but in an effectively unlockable state.

Specifically, I'm in the Python track and completed all exercises (except Ledger, which was added recently) months ago. Pre-migration the Ledger exercise was available to me, post-migration it's now locked, but there's no apparent way to unlock it because the only way to do so is by completing the Core exercise tree, which I've automatically already done.

**Comment by iHiD** [comment]
@yawpitch - Thanks for the detailed response. @kytrinyx is looking into this. If anyone else has similar examples, please add them below to help us track this down.

**Comment by mgmatola** [comment]
Sounds like I have the same problem in the JavaScript track.

Prior to data migration/go-live, I had completed all 18 core assignments in the JavaScript track. Post-migration they're all in the status of completed. 

The Extra Exercises -- some I've completed previously, some are unlocked, but the majority of them are locked. I would expected them all to be unlocked.

**Comment by mgmatola** [comment]
If it helps in diagnosing the problem, note that I chose the standard mode (not independent) for this track.

**Comment by NobbZ** [comment]
@mgmatola my assumption is, that locked exercises get unlocked as soon as you brought your submission to a mentors attention by clicking the link in the red box above, the mentor approved it **and** you completed it then.

**Comment by yawpitch** [comment]
@NobbZ so everyone who completed the core exercises before the migration (ie their exercises were never submitted to mentor inspection) needs to manually request mentor approval of 1 (or more, or **all**?) of their core exercises?

**Comment by NobbZ** [comment]
Thats my assumption that has not yet been confirmed yet.

But to do an exercise you have to fulfill its prerequisites if you are on normal mode.

Except for the very first exercise on each track (usually `hello-world`) the prerequisite is to have the preceeding exercise approved by a mentor and completed.

Your current submission lack the bit in the database that flag mentor approval, thats what I base my assumtpion upon.

**Comment by yawpitch** [comment]
That's an oversight in the migration then, and a problematic one for some potentially large number of users / mentors.

For instance I completed the entirety of the Python track -- what is now core as well as all of what are now extra exercises) at least a month before V2 was even announced. Which means that I long ago completed the prerequisites for all my now unlocked and completed Extra Exercises. But at some point after that the Ledger exercise was added. Without looking at the underlying database entry I've no idea what its prerequisites even are, so *which* core exercise needs to be flipped back to needing mentor approval?

If that same issue exists for others, and any exercises added *after* they completed what are now the core track exercises are locked, then there's potentially quite a few people who would need to manually flip an unknown number of unidentified exercises back to requiring mentor approval.

I don't mind doing that, except that I've got up to 100+ exercises to put into the queue then ... at the response rate I've been able to churn up, that could take weeks if not months to clear.

**Comment by NobbZ** [comment]
Yeah, lets just wait until @kytrinyx and @iHiD report back with more information.

**Comment by puffybsd** [comment]
Same with rust. Some completed exercises are locked, and there appears to be fewer exercises showing as completed then I've actually completed (54 vs 60).

**Comment by kytrinyx** [comment]
I'm sorry it's taken so long to get back to you.

This is definitely a missed use case in the migration.

We need to unlock all optional exercises that are unlocked by core exercises that were completed before the launch of the new site.

**Comment by kytrinyx** [comment]
Update--this should be fixed. Closing, but if it's still a problem, please holler.
