### ISSUE TITLE
Scrolling through solution not working (Multi-file solution submission)

### ISSUE THREAD

**Issue by blogscot** [exercism/exercism.io#3819]
I submitted a [solution](https://exercism.io/my/solutions/7108aea302544dde94a92d532140eedf) for the `Poker` challenge in the `Rust` track which contains three files. When the browser (Firefox or Chrome) is maximised, scrolling does not work: the page janks up and down briefly but does not scroll down.

I found by reducing the browser height by ~10%, I was able to scroll through the solution as normal.

**Comment by TravisBumgarner** [comment]
I just experienced the same issue. I think it might have something to do with how much vertical space the contents of the tabs `Instructions` `Test Suite` and `Solution` take up after submitting an answer. Whichever of the the shortest, the other two tabs won't be able to scroll past that point. Also, there's some debugging stuff left in the console it seems.

https://drive.google.com/file/d/18n_yR9Lf5_kBfCtxkZf9rBZ4vwebL2JB/view?usp=sharing

**Comment by NobbZ** [comment]
It does not need to be multifile.

When I look at my singlefile solution to `elixir/bank-account`, I can scroll downwards until about that point which is shown in the screenshot, when I scroll down further, the code flickers, then it jumps back to the position shown in the screenshot. This is only when viewing it under "my solutions", scrolling the same solution in the public area works fine.

Public area link: https://exercism.io/tracks/elixir/exercises/bank-account/solutions/d577c02623e64e0481d6f9e46f044892

![no-scroll](https://user-images.githubusercontent.com/58951/42728680-42898acc-87c0-11e8-8927-dc878d462dce.png)

**Comment by iHiD** [comment]
I believe this is fixed (albeit in a brute force "remove the clever scrolling" approach). If anyone has any further issues, please let me know. Else I'll close it shortly. Thanks for your input everyone :)
