### ISSUE TITLE
Submit - not within workspace

### ISSUE THREAD

**Issue by vulgv** [exercism/exercism.io#3820]
I try to submit my first javascript exercise and I get this error.
I troubleshooted and this is what it showed me

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.2
Latest:  3.0.2

Operating System
----------------
OS:           darwin
Architecture: amd64

Configuration
----------------
Home:
Workspace: /Users/florinenache/Exercism
Config:    /Users/florinenache/.config/exercism/user.json
API key:   0522*****************************269

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 146.232819ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 265.426796ms

**Comment by NobbZ** [comment]
When you try to submit, in which folder are you then and what is the command you are using to submit?

**Comment by vulgv** [comment]
The folder I'm in is /Users/florinenache/exercism/javascript/hello-world-2 and I used `exercism submit` ,  `exercism submit hello-world.js` and `exercism submit /Users/florinenache/exercism/javascript/hello-world-2/hello-world.js`

**Comment by NobbZ** [comment]
`hello-world-2` is not a valid exercise slug. You need to move your code over to `$(exercism workspace)/javascript/hello-world` and submit from there that the CLI can figure out what you are trying to submit.

@exercism/cli the error message is irritating under such circumstances, can you come up with something like “unable to recognize exercise from path”?

**Comment by vulgv** [comment]
the `hello-world-2` was because I re-downloaded the exercise because some people said that if you do that you'll be able to submit
I moved it over, but I get the same error

**Comment by NobbZ** [comment]
Oh, wait…

Are you on a Mac?

Please `if [[ -d $(exercism workspace); then echo "folder exists"; else mv -r ~/exercism $(exercism workspace); echo renamed fi` and show me the output.

If it prints stuff and ends with the line "renamed", try again to submit your solution.

@exercism/cli perhaps we need to normalize pathes on Mac as well, similar to how it is already done for windows (or is planned at least).

**Comment by vulgv** [comment]
now it worked
thanks a lot

**Comment by richflee** [comment]
@NobbZ I'm getting the same issue. MacOS Sierra 10.12.1 (16B2657)

**Comment by richflee** [comment]
@NobbZ nevermind. Solved - renamed workspace directory use capital E

**Comment by NobbZ** [comment]
The file should live at `$(exercism workspace)/java-script/hello-world/...`, or similar. I'm not sure how the tracks slug looks like for JavaScript, nor am I sure about the structure inside the exercises.

**Comment by anyajunior** [comment]
> The file should live at `$(exercism workspace)/java-script/hello-world/...`, or similar. I'm not sure how the tracks slug looks like for JavaScript, nor am I sure about the structure inside the exercises.

Workspace:     (-w, --workspace)  /Users/superfamily/Exercism
exercism version 3.0.9

I moved hello.js into Exercism/java-script/hello-world/
still get Error: not in workspace 
Just in case, I deleted the Exercism, and tried to install and run everything once again, still the same response.

**Comment by nywilken** [comment]
@anyajunior the official track directory name for JavaScript is `javascript`, which is why you are still getting the not in workspace error. The best way to fix this issue is to download the exercise via the exercism command-line client. The following steps assumes you registered for the javascript track at https://exercism.io/my/tracks/javascript

```exercism download --track javascript --exercise hello-world```. 

The above command will create the proper structure for you within your workspace path and download the base hello-world exercise files needed for submission. After downloading move your hello.js file into the directory created by the download command; then submit your files. All should work as expected.

**Comment by anyajunior** [comment]
Finally resolved the issue: it appeared that workspace lived not where I wanted it to be. Instead, it was created right in the root of my /Users folder. Somehow inconvenient, but I can get used to it. Thank you for reaching out!

**Comment by MPalhidai** [comment]
I hit this error all of the time. On a Mac compare the output of `pwd` and `exercism workspace`. If workspace, make sure the case is the same. If not, cd ~/paste the output of exercism workspace

**Comment by sarah27h** [comment]
@anyajunior 
In the first, I wasn't able to submit my solution because I moved the problem folder to E: then I got 'Error: not in workspace' then I moved it back to C: but it didn't have enough space can I delete it after submission.

**Comment by NobbZ** [comment]
@sarah27h yes you can, but you really shouldn't, mentors will probably ask you to improve your submission.

I think an easier solution is to use `exercism configure` to change your workspace directory to somewhere else.

**Comment by sarah27h** [comment]
@NobbZ Thanks for your reply, I found this https://github.com/exercism/exercism/issues/1778#issuecomment-432389983
and I changed workspace directory using *exercism configure --workspace="E:/Exercism/javascript"*
it worked for me but what difference between *exercism configure --workspace="E:/Exercism/javascript"* and **exercism configuration --dir="E:/Exercism/javascript"**?

**Comment by NobbZ** [comment]
The biggest difference is, that there is simply no subcommand `configuration`. It might have existed a year ago with the 2.x client, but I'm not sure as since about the middle of the last year the 2.x reached end of life, as the newly launched website required another protocol.

**Comment by sarah27h** [comment]
Thanks for the info :)

**Comment by SilverBright** [comment]
Thank you. Navigating out of the Exercism directory in Terminal, then going back into the Exercism directory making sure to type "Exercism" instead of "exercism" fixed the 'Not In Workspace' error.  I was able to submit my hello-world challenge successfully.
