### ISSUE TITLE
Setting up exercism CLI for Mac

### ISSUE THREAD

**Issue by zgallagher08** [exercism/exercism.io#3821]
The directions for installation simply say to “put the binary in your path.”

There should be more explicit directions for installing the exercism CLI.

**Comment by guygastineau** [comment]
I agree that those instructions seem vague.
However,

- that is actually all you do to install the cli

- personally I think googling to figure out how to solve problems (like exporting PATH) is an important skill for developers.

**Comment by NobbZ** [comment]
Then let me please ask, why for linux users the prefered and documented way to install is to use `~/bin` and even guiding you to adjust your PATH accordingly, but assume that a MAC user is happy to google on his own?

**Comment by guygastineau** [comment]
I didn't make the documentation so I don't know.  I was going to try linking the file that has this info for Mac users from the repo and suggest that anyone could make more explicit instructions and pr them for the benefit of Mac users but I couldn't find it in the repo.

**Comment by guygastineau** [comment]
@NobbZ. You seem knowledgeable about *nix systems so I linked you to #166
Where are the Bash communities and enthusiasts?
Opened by kytrinyx about 1 month ago

If you want, maybe we can all work together to make a bigger more active community of *nix users on exercism.

 I thought no then it night be easier for things like this to be more consistent.

**Comment by NobbZ** [comment]
I'd still prefer official exercism-staff maintained repositories for major linux distros, a windows installer (or exercism-staff maintained choco package, **not** both) and whatever is appropriate for mac and provide those in the default instructions together with a "if you can't use those, build as described in the contribution guide from source.

**Comment by guygastineau** [comment]
I guess by *nix I meant meant to include Mac even though I know it isn't technically *nix.  I'm sorry if I linked that here inappropriately.  I just wanted to see if you were interested in helping to get a stronger bash community in exercism.

**Comment by zgallagher08** [comment]
I just added a symlink to the binary file to /usr/local/bin to get it to work, but I think it would be a good idea to just have a simple instruction on the site

**Comment by guygastineau** [comment]
@NobbZ I agree that official packages would be ideal.  The autocompletion could maybe be included automagically that way.

At the same time - I use ~/bin for my custom scripts as well as the exercism inary.  I think it is a practice that most bashers should understand.

  Also, for arch to add the package it will have to get enough votes after being in the AUR.   Putting the binary in your path is much simpler than building it from the AUR.

**Comment by NobbZ** [comment]
We are really getting of the track, but I never ever install anything without a `PKGBUILD`.

Besides the `opam` managed ocaml-versions there are no programs on my system that `pacman` isn't aware of. I can be pretty sure to never accidentally remove a `-dev` package from my system and break software installed from source by this.

**Comment by guygastineau** [comment]
@zgallagher08
I'm glad you got it working. I couldn't find the file to edit for the Mac instructions, but I'm sure if you can that the maintainers would appreciate a pull request with edits to make the process clearer for Mac users.
