### ISSUE TITLE
No link to "Community Solutions"

### ISSUE THREAD

**Issue by mgmatola** [exercism/exercism.io#3822]
Prior to data migration/go-live, I had completed all 18 core assignments in the JavaScript track. Post-migration they're all in the status of completed (and @iHiD told me they've been published). In the mentorcism track I had a "community solutions" link/button on each solution to view others' published solutions. I no longer have such a button/link and no way (that I can figure out) to view others' published solutions.

**Comment by guygastineau** [comment]
When you are looking at your completed solution there is a community solutions button to the right under the header.

Let me know if that isn't descriptive enough.

**Comment by mgmatola** [comment]
No. That is the exact problem. I do not have any community solutions buttons.
<img width="1293" alt="screen shot 2018-07-14 at 10 54 44 am" src="https://user-images.githubusercontent.com/15664551/42725619-cd672026-8754-11e8-8ffd-65487f4fb437.png">

**Comment by mgmatola** [comment]
If it helps in diagnosing the problem, note that I chose the standard mode (not independent) for this track.

**Comment by guygastineau** [comment]
Okay, you need to click the  `click here` button after the red text first.  Then it will appear to the right of an updated message saying that your exercise will be reviewed by anebtoe soon. 

Let me know if this works for you.

**Comment by kytrinyx** [comment]
For what it's worth, I don't think you should have to request mentorship in order to see the link to the community solutions.

I'm wondering if we can tweak the banner so that it doesn't take up the full width, and leave the link to the community solutions in place.

**Comment by mgmatola** [comment]
If I'm the only person that this is a an issue for, I would say it's not worth anyone spending any time on it. Once the EcmaScript and JavaScript tracks are merged, I plan to go through and have my solutions mentored, which should make the community solutions available to me using the community solutions link.

(Awhile ago I figured out the URLs for getting to the community solutions, so I can actually see whatever I want that way.)

**Comment by iHiD** [comment]
This is now sorted.
