### ISSUE TITLE
Language filter on my profile does not affect the number of displayed solutions

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3823]
When I visit my profile (exercism.io/my/profile), I see a lot of submissions, and a small text in the upper right “Showing 424 solutions”.

After changing the language filter to "PHP", I can see 3 cards linking my submissions, but the text in the upper right still claims to show 400+ solutions.

**Comment by nickborromeo** [comment]
FWIW I do not see this behavior. I toggled between `Any` and other languages but the number did not change. @NobbZ do you still have this behavior?

**Comment by NobbZ** [comment]
@nickborromeo yes I still see the bahviour.

And I do not understand what you are saying. You say, you don't see what I see, but then you say, that the number doesn't change, which is exactly the bahaviour I describe.

I lost some numbers since the last report though, its only saying 422 now…

**Comment by iHiD** [comment]
Does [this](https://github.com/exercism/website/pull/263) close this issue?

**Comment by NobbZ** [comment]
From the description it looks as if, but from the `diff`s I'm absolutely not sure.

**Comment by nickborromeo** [comment]
@NobbZ oops! I misread your description 😄 When I saw that it was no longer `424` and it was just `400+` my brain parsed that as something changed. And when mine did not change I thought we had different behaviors.

**Comment by iHiD** [comment]
This was fixed.
