### ISSUE TITLE
Leave Track Button doesn't work

### ISSUE THREAD

**Issue by TravisBumgarner** [exercism/exercism.io#3826]
The last error results when clicking on `Leave Track` the other errors show up on page load. 
[
![screen shot 2018-07-14 at 12 15 57 pm](https://user-images.githubusercontent.com/11890057/42726263-a1a921cc-875f-11e8-930a-dccc3b5f49dc.png)
](url)

**Comment by iHiD** [comment]
@TravisBumgarner A change this morning has broken that modal. Sorry. @kntsoriano is fixing now.

**Comment by TravisBumgarner** [comment]
👍 You guys move fast. Thanks!
