### ISSUE TITLE
Provide installation instructions for the CLI that are easily discoverable/accessible

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3827]
The current installation instructions for the CLI are only available as part of the "getting started" guide, which is only accessible from an exercise without a submission after one has joined a track.

Instead the installation instructions should be accessible regardless of a tracks status, as I might reinstall my computer but already have solved and submitted a bunch of exercises, and I can't even remember I need to click through that guide or how I access it.

**Comment by ErikSchierboom** [comment]
I just had the same experience. I looked at the "Getting started" page, which I think should just have a link to download the CLI.

**Comment by kylesnowschwartz** [comment]
Where are the installation instructions? I'm trying to continue using Exercism on another computer but they're very well hidden. Very frustrating.

**Comment by NobbZ** [comment]
As long as you have an exercise that has no submitted solution, you can start the "getting started" guide from that exercises description. This guide is basically the installation instruction for the CLI.

**Comment by kylesnowschwartz** [comment]
thank you @NobbZ. I found the CLI instruction guide by going to a new language track, going to the hello-world exercise, and following the begin walkthrough button on the right hand side of the page.

I was also able to find https://github.com/exercism/website-copy/blob/master/walkthrough/index.html after some searching

The UX has become exceptionally frustrating. Here are a few examples of my user experience trying to continue a track I had already started pre-launch of the new website.
- I left a track, only to find it doesn't clear my exercises, and I can't re-join (i.e., doesn't show up on the language tracks index page as joined).
- I switched to independent mode, only to find I can't go back to whatever the inverse is.
- Once I complete an exercise, I can't find the walkthrough instructions again (and future exercises are 'locked' so it's not obvious that I need to find an uncompleted one to see the walkthrough instructions or even how I would do so).
- The walkthrough branches out into different instructions depending on what you click, so if you don't understand the question (e.g., "Are you comfortable installing and executing programs on terminal?") you may accidentally go down the wrong path and not know how to move forward or back. For example, if you answer 'yes' to that question, but you don't know what it means to move a binary into your PATH, which could leave a user stuck not knowing that they followed the wrong branch.

Sorry for the brain/emotions dump. It's quite unfortunate to be made to feel like an idiot (which is how I felt) when trying to use a learning website.

**Comment by iHiD** [comment]
Sorry you felt like this, @kylesnowschwartz.

There are clearly rough edges we're working through. I believe there are open issues for the first three of your points, and they will all be dealt with soon.

Regarding the walkthrough, we need the community to feed back specific things that they would change (preferably via PRs although issues are helpful too). The community have put a lot of effort into building these instructions and we have tested them on people, but everyone's knowledge and experience is different so if they're not good enough, please tell us.

There are also a lot of links around the site that need to be updated. You referenced one in your previous example. We'll try and get to these but we have some much content (over 1,500 different exercise READMEs) that it's hard to catch them all. Again, any help you can give is valued - that's the only way things like this will get done.

Hopefully now you're over the initial hurdle of the v1 to v2 migration you'll find the next site to be a better learning tool than the previous one would have been and get benefit from it.

Thanks for taking the time to document your thoughts :)

**Comment by kytrinyx** [comment]
Thanks, everyone, for bringing this up.

@iHiD I think it would be worth adding a link in the footer that gives you a page for installing the CLI.

It should have the walkthrough on it, as well as a "just want to download the latest release? Go here" type link.

I've opened a PR adding such a link to the "getting started" page (https://github.com/exercism/website-copy/pull/235) but I think that a CLI-specific page that we could link to would be even better.

**Comment by iHiD** [comment]
I've added these to the footer and we've added info to the relevant FAQ pages.
