### ISSUE TITLE
mentoring: Provide copy/pastable command to download students solution

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3837]
As a mentor I prefer to run tests locally, also in my editor I do not need to scroll the code horizontaly, as it is (usually) wide enough or wraps at least.

Downloading the code has currently a bad user experience (and I will assume exercism/cli#621 did not exist), as I need to copy the ID from the URL of the solution to mentor, then go to my terminal and enter `cd $(exercism d --uuid=`, paste the ID, type `)`, hit enter and then run the tests as necessary.

It would be nice if on the solution to mentor there were a box containing at least the `exercism d --uuid=$UUID` part for easy copy and paste into the terminal.

**Comment by rpottsoh** [comment]
Or possibly a button to copy the students solution so that it may then be pasted into an editor, like in v1?
