### ISSUE TITLE
no syntax highlighting for elisp

### ISSUE THREAD

**Issue by yilkalargaw** [exercism/exercism.io#3840]
exercism v2 does not have syntax highlighting for elisp programs. I am not sure if prism.js provides one specifically designed for elisp but I think it supports lisp. So it may be sensable to use that one unitl someone brave enough to create  emacs-lisp specific syntax highlighting.

**Comment by iHiD** [comment]
Could you PR to website pls? [This PR for common-lisp](https://github.com/exercism/website/pull/75/files) should give you the info you need. Thanks! :)

**Comment by iHiD** [comment]
I believe this should now be fixed. @yilkalargaw Can you confirm and close pls?

**Comment by yilkalargaw** [comment]
late but confirmed as fixed
