### ISSUE TITLE
mentors: can't remove language or exercise filters on the dashboard

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3843]
In the "Solutions you are mentoring" when I select a track or exercise in the filter boxes, I can't remove it after the fact, I have to reload the dashboard to clear those fields.

**Comment by iHiD** [comment]
You should be able to for exercises now. And you should be able to backspace the tracks out. These work ok for you?

**Comment by NobbZ** [comment]
For the track I can delete, yes. But I'm unable to choose a filter for the exercise at all.

It does not work as a drop down, also typing directly does not cause any action in the UI.

**Comment by iHiD** [comment]
>  But I'm unable to choose a filter for the exercise at all.

Does it work if you choose a language first (and possibly waiting for it to load)? 

Just trying to be clear on the issue before I dig in.

**Comment by NobbZ** [comment]
> Does it work if you choose a language first (and possibly waiting for it to load)?

Yes, it works then.

But what if I mentor many tracks and I am searching for a solution to `bob` that had a noteworthy approach but I can not remember which language it was? I want to be able to filter for all bob exercises through all tracks I mentor.
