### ISSUE TITLE
Should track mentors and maintainers appear more than once on Maintainers/Mentors Page?

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism.io#3852]
Track Mentors/Maintainers, who likely maintain/mentor more than one language track, appear multiple times on the [Maintainers Page](https://exercism.io/team/maintainers) and [Mentors Page](https://exercism.io/team/mentors).  Wouldn't it be more useful to list each maintainer / mentor once and indicate which tracks they work with?

**Comment by iHiD** [comment]
Thanks. Will sort it.

**Comment by iHiD** [comment]
Should be fixed by https://github.com/exercism/website/pull/185/commits/be20394e7cbc74beb8325249fe0527f9b79dde05

Please could you confirm and close if you're happy? Thanks!

**Comment by rpottsoh** [comment]
This appears to be fixed.  However, I see another issue on the Volunteer Contributors page.  I will close this issue and open another.

The bubbles that appear next to each Core Team member look good. 👍
