### ISSUE TITLE
Waiting for mentor feedback

### ISSUE THREAD

**Issue by mdechamp** [exercism/exercism.io#3853]
Hi all, 

First of all thanks for making this freely accessible, it looks like a great way to learn and practice my Python skills but... Am I missing something? I completed the second exercise 'Leap' on the Python track 4 days ago and have been waiting for feedback but during that time I don't seem to be able to keep doing exercises on the track, only the extra exercises. 

Is this normal? Will I have to wait 4 days + in between each of the 118 exercises or is there a way I can keep on practicing?

Thanks for your help and your work, it's very appreciated.

**Comment by NobbZ** [comment]
In “normal mode” you have to wait for the mentors feedback before you can advance. We do hope that students do not need to wait that long once we have fought the backlog.

**Comment by nmegrant** [comment]
@mdechamp I came here to see if anyone else was having long wait times. No worries, it's not just you - I've been waiting the same amount of time. Probably taking a while to get through the backlog and adjust to the new system. Hopefully we get some feedback soon, once things are settled down some! Then everyone can get into a groove with it.

**Comment by iHiD** [comment]
This should be better now. We've also made it clearer that you can do extra exercises while you wait, and added the ability to move in and out of Independent Mode if you get too frustrated waiting. I'm going to close this as there's no action we're going to take atm other than us recruiting more mentors and making their lives easier.
