### ISSUE TITLE
Minor issues with "Elsewhere Online" profile section

### ISSUE THREAD

**Issue by devillexio** [exercism/exercism.io#3858]
There are some minor formatting issues on the _Elsewhere Online_ section of your profile.

<img width="397" alt="screenshot 2018-07-16 at 09 39 12" src="https://user-images.githubusercontent.com/11049609/42747414-8c91196a-88dc-11e8-9185-7079e26f6b4c.png">

Issues:

* Inconsistent spacing between Twitter and GitHub profile links
* Too little spacing on Medium profile link
* Medium link requires the inclusion of an `@` character, or the resulting link is broken

**Comment by iHiD** [comment]
This is fixed now :)

**Comment by devillexio** [comment]
Awesome, thanks!
