### ISSUE TITLE
www.exercism.io still says "Please bear with us while we migrate".

### ISSUE THREAD

**Issue by bdf74** [exercism/exercism.io#3861]
I typed www.exercism.io instead of exercism.io, and still got the migration screen. Not an important issue, of course, but you may want to fix this.
![cattura](https://user-images.githubusercontent.com/1384899/42757114-08981ff0-88ff-11e8-8882-ba410e40047d.JPG)

**Comment by budmc29** [comment]
@bdf74 is this still an issue for you?

**Comment by bdf74** [comment]
Not really an issue for me, but perhaps somebody else will enter the wrong address, see that page and think that the site is down.

**Comment by iHiD** [comment]
@ccare This is also true for any 301s we set up.

**Comment by ccare** [comment]
@bdf74 Thanks for reporting this. It should be fixed now.

**Comment by bdf74** [comment]
Great, thanks! :-)
