### ISSUE TITLE
HTML as text-content in walk-through instructions

### ISSUE THREAD

**Issue by jonsilvacodes** [exercism/exercism.io#3862]
In the instructions to add ~/bin to $PATH in linux, a code snippet is displayed as:

&lt;a href="javascript:void(0)" data-passage=" &quot;:$PATH:&quot; == *&quot;:$HOME/bin:&quot;* "&gt; ":$PATH:" == *":$HOME/bin:"* &lt;/a&gt; && echo "~/bin is in PATH" || echo "~/bin is not in PATH"

I'm not sure why the link is there at all, but this should probably read as
":$PATH:" == *":$HOME/bin:"* && echo "~/bin is in PATH" || echo "~/bin is not in PATH"

(This is in Google Chrome 66 if that matters)

**Comment by iHiD** [comment]
This is triaged to https://github.com/exercism/interactive-cli-walkthrough/issues/31

**Comment by iHiD** [comment]
Thanks for reporting. I believe this is a duplicate of https://github.com/exercism/exercism.io/issues/3803
