### ISSUE TITLE
Single ticks break the syntax highlighting in F#

### ISSUE THREAD

**Issue by swatteau** [exercism/exercism.io#3864]
In F# and some other languages, single ticks are allowed in names.

On the website, they seem to be treated as string delimiters, which breaks the syntax highlighting.

[Example in F#](https://exercism.io/my/solutions/de833ef66c50465ba24a524f5baa40a0)

**Comment by NobbZ** [comment]
Double of #3831 and already reported upstream as PrismJS/prism#1480.
