### ISSUE TITLE
Cannot submit 

### ISSUE THREAD

**Issue by teb0ho** [exercism/exercism.io#3865]
`exercism version 3.0.4`
I have upgraded to the new version. And I have downloaded the exercise I have been working on with the new exercism CLI and this is what I am getting when I am trying to submit the completed exercise

`> exercism submit src/main/java/Scrabble.java`
`> Error: not in workspace`

**Comment by NobbZ** [comment]
Please check if the output of `exercism workspace` matches **exactly** with the Path you expect.

Then change the config to match your actual Path to the workspace or rename the path to your workspace accordingly, whatever is easier on your system.

Please be aware of the fact, that the CLI treats pathes case sensitive regardless of the underlying file system.

**Comment by teb0ho** [comment]
Thanks it worked 👊
