### ISSUE TITLE
legacy/independant: limit number of requests for mentorship

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3866]
Legacy solutions or those solved in independent mode can opt in for mentorship.

Some users seem to just bulk-request all they have submitted so far, this creates massive load on the mentors.

In my current "to mentor" list I can only see solutions of a single user, from 8 days to 1 month of displayed age.

I do assume that other users might have done similar on other tracks.

**Comment by kytrinyx** [comment]
I'm seeing the same thing @NobbZ. Also someone mentioned that the people who have done this are often making the same mistakes in all of their exercises, so we'd be much better off just having them submit a small number (I figure 3 should be good) at a time, and then we can encourage them to rework any new submissions based on things they've learned.

**Comment by NobbZ** [comment]
Well, a problem with this is, that you currently can't re-iterate legacy solutions (see also #3830), so that makes transfering very hard…

**Comment by iHiD** [comment]
This is done now.
