### ISSUE TITLE
Some exercises on the C# track are not unlocked correctly

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism.io#3869]
On the C# track, I've completed the core `sum-of-multiples` exercise, which should unlock the `armstrong-numbers` exercise (see the [config file](https://github.com/exercism/csharp/blob/master/config.json#L141)). 

![image](https://user-images.githubusercontent.com/135246/42776845-94f10456-8938-11e8-96fa-83ac25b22044.png)

However, the `armstrong-numbers` exercise is not unlocked:

![image](https://user-images.githubusercontent.com/135246/42776885-b276f814-8938-11e8-8377-3e7eba395f15.png)

**Comment by iHiD** [comment]
@ErikSchierboom Did you complete the originals using "Complete unapproved" mode?

**Comment by ErikSchierboom** [comment]
I'm not sure, I think I didn't as `sum-of-multiples` was an import of the old website, and as such was automatically approved.

**Comment by iHiD** [comment]
@ErikSchierboom I've run a script on your account. Is that fixed for you on the Csharp track now?

**Comment by ErikSchierboom** [comment]
@iHiD Yes, that did the trick! Thanks lot.

**Comment by iHiD** [comment]
OK, great. I'll run this everywhere for everyone. That will take a while :)
