### ISSUE TITLE
Some downloaded user solutions have oddly named files

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism.io#3870]
When downloading some user solutions, I get some oddly named files. For example, when I do `exercism d -u 4e7cceed1d274eb28c3d217e36c3e98e`, it downloads the following files

``` 
drwxr-xr-x  8 erikschierboom  staff   256 Jul 16 21:20 .
drwxr-xr-x  3 erikschierboom  staff    96 Jul 16 21:20 ..
-rw-------  1 erikschierboom  staff   221 Jul 16 21:22 .solution.json
-rw-r--r--  1 erikschierboom  staff   182 Jul 16 21:22 Leap.cs
-rw-r--r--  1 erikschierboom  staff   446 Jul 16 21:22 Leap.csproj
-rw-r--r--  1 erikschierboom  staff   736 Jul 16 21:22 LeapTest.cs
-rw-r--r--  1 erikschierboom  staff  1028 Jul 16 21:22 README.md
-rw-r--r--  1 erikschierboom  staff   143 Jul 16 21:22 \\Leap.cs
```

This happened on a Mac, but I've seen the same issue occur on Windows.

**Comment by kytrinyx** [comment]
I'm pretty sure this has something to do with not cleaning paths properly in the CLI when submitting and/or downloading. Thanks for reporting it!

**Comment by kytrinyx** [comment]
I've opened an issue for this in the CLI repo: https://github.com/exercism/cli/issues/665

**Comment by hilary** [comment]
Issue #4072 gives a second variation in downloaded file configuration, in addition to the one listed above.
