### ISSUE TITLE
Package.json doesn't exist in JavaScript tasks

### ISSUE THREAD

**Issue by JSMonk** [exercism/exercism.io#3871]
package.json doesn't exist.
After `exercism download --exercise=SOME-TASK --track=javascript`

<img width="458" alt="screen shot 2018-07-16 at 10 48 30 pm" src="https://user-images.githubusercontent.com/10776615/42779889-654ebfce-894a-11e8-94b2-61921249e960.png">

macOS High Sierra 10.13.5
Exercism CLI version 3.0.2

**Comment by iHiD** [comment]
@kytrinyx @exercism/javascript Is this a problem in the CLI or a decision/problem in the JS track?

**Comment by matthewmorgan** [comment]
The JavaScript track is being deprecated and replaced by EcmaScript.  We're waiting on three exercises to be ported to be able to do this.  If it's not done today or tomorrow I'll finish it myself by week end, and I expect @kytrinyx @iHiD will be able to finish the deprecation?

In any case, the track does not require per-exercise `package.json` or dependency installation.  Only Jasmine needs to be installed globally to run tests.  This is explained in the installation doc, are users still seeing this in V2?  https://github.com/exercism/javascript/blob/master/docs/INSTALLATION.md

Finally, the EcmaScript track, which will become the new JS track, _does_ require per-exercise installation of dependencies currently, though we're hoping to remove that requirement in favor of a track level install in the future.

@JSMonk does that answer your question?  Please let me know if I can help further.

**Comment by iHiD** [comment]
@nobbz I'm confused about how that issue (cli#458) is the same as this. It seems to me that that is about submitting and this is about downloading. What am I missing?

**Comment by NobbZ** [comment]
You are missing that we need to submit before we can download auxiliary files from a solution.

**Comment by iHiD** [comment]
Isn't `exercism download --exercise=SOME-TASK --track=javascript` just the initial download of a track, and @JSMonk isn't getting a default file downloaded that he expects. What has he submitted first?

**Comment by matthewmorgan** [comment]
There is no package file for exercises in this track.

Let me know if this is unclear for any reason.

**Comment by iHiD** [comment]
Can we close this issue then pls? If there is an opinion that there should be a package.json pls open an issue about that on the ecma script. Thanks :)

**Comment by matthewmorgan** [comment]
@iHiD I can't close it, but that seems like the right thing to do.

**Comment by iHiD** [comment]
Done :)
