### ISSUE TITLE
mentor: approved solutions require action from me after student re-iterated or commented

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3880]
As a mentor I like to give small style nits but approve anyway to give the student the choice to fix those now or in the next exercise only (or not at all), or we had a discussion that simply conitinues after approval.

Those exercises appear as "requires action from you" on my dashboard after the student reiterated or commented, and I can not re-approve them. The only way I can get rid of them is to reply, which again has a high chance of triggering a students reaction, even when I explain to not reply…

Currently I have 4 solutions in this state, and I do need to scroll already to get to the actual mentoring queue. Also the more items get into this state, the higher the chances to actually miss items that really require an action.

---

PS: I am pretty sure this was already posted, but I wasn't able to find it here or on v2-feedback: exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback#69, but that is claimed to be fixed since a year or so, and also involves notfications, which disappear correctly in the current version.

**Comment by NobbZ** [comment]
Added a missing sentence to clarify things, please read in issue tracker, not email!

**Comment by ErikSchierboom** [comment]
I've also ran into this!

**Comment by iHiD** [comment]
@NobbZ @ErikSchierboom What's the right solution here?

Is the correct behaviour you want:
- If a student posts a new iteration on an approved solution:
  - Leave the solution in the "completed state" on the mentor's dashboard?
  - Send a notification to the mentor?

**Comment by ErikSchierboom** [comment]
> If a student posts a new iteration on an approved solution:
> 
> * Leave the solution in the "completed state" on the mentor's dashboard?
> * Send a notification to the mentor?

I think that would greatly help. Currently, I have quite a lot of solutions that I have approved, but for which I have given the student some additional pointers that he can iterate with should he desire. If the user actually does do that, it would indeed require my attention, but it is not in the same category of urgence as the other solutions that require an action of me that haven't yet been approved.

I've also consider if we should add another status, but I'd rather not do that. In this case, I think the notification would be perfectly fine.

**Comment by NobbZ** [comment]
A notification should be enough to gain visibility, but I'm fine with it appearing in requires action to increase chances of feedback where feedback belongs. But as a mentor I need a way to tell the system, nope all what could be done is done, my action is to ignore this until the next event.
