### ISSUE TITLE
Empty lines in comment are rendered differently in preview

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism.io#3884]
If I have a comment with lines separated by an empty line, the preview pane doesn't render them:

Write pane:

![image](https://user-images.githubusercontent.com/135246/42816156-2e5f7456-89ca-11e8-8a10-5f5e8f2fc49c.png)

Preview pane:

![image](https://user-images.githubusercontent.com/135246/42816196-5115d148-89ca-11e8-9faf-44f7b0efc2dd.png)

**Comment by ErikSchierboom** [comment]
Aha, well caught!

**Comment by ErikSchierboom** [comment]
It is thus a styling issue, and as such I've updated the issue's title.

**Comment by iHiD** [comment]
This was fixed.
