### ISSUE TITLE
mentor: Loading the dashboard (without resources) takes a long time

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3888]
Loading the mentors dashboard takes more than 3 seconds for me.

When I take a look at google chromes timing information, and test a couple of times, then I do get values around those:

| | |
|----------|-------:|
| Queueing | 0.4 ms |
| Stallled | 6.4 ms |
| Request sent | 0.1 ms |
| Time to first byte | 3.2 s |
| Download | 17.0 ms |

So it seems as if there is a lot of work done on the server, just to deliver a list containing ~20 items…

**Comment by Cohen-Carlisle** [comment]
In the meantime, some visual indication/spinner while it updates the list would be much appreciated.

**Comment by NobbZ** [comment]
I'm talking about loading the page itself, not about applying a filter.

Visual feedback when applying a filter is covered by #3801

**Comment by iHiD** [comment]
I've sped this up so it's now fast if you have lots of solutions to do. However, when you break through the recent core/side ones it gets slow again. It's under constant improvement :)

For context, this is the SQL that's being run to generate the next solutions right now:
```
SELECT  `solutions`.`id` FROM `solutions` 
INNER JOIN `exercises` ON `exercises`.`id` = `solutions`.`exercise_id` 
INNER JOIN `users` ON `users`.`id` = `solutions`.`user_id` 
INNER JOIN `user_tracks` ON `user_tracks`.`user_id` = `users`.`id` 
WHERE `solutions`.`exercise_id` IN (
  SELECT `exercises`.`id` FROM `exercises` WHERE `exercises`.`track_id` IN (
    SELECT `track_mentorships`.`track_id` FROM `track_mentorships` 
    WHERE `track_mentorships`.`user_id` = 188616 
    AND `track_mentorships`.`track_id` = 50
  ) 
  AND `exercises`.`id` = 2119 
  ORDER BY position ASC, title ASC
) 
AND (user_tracks.track_id = exercises.track_id) 
AND `solutions`.`id` NOT IN (
  SELECT `solution_mentorships`.`solution_id` 
  FROM `solution_mentorships` 
  WHERE `solution_mentorships`.`user_id` = 188616
) 
AND `solutions`.`id` NOT IN (
  SELECT `ignored_solution_mentorships`.`solution_id` 
  FROM `ignored_solution_mentorships` 
  WHERE `ignored_solution_mentorships`.`user_id` = 188616
) 
AND `solutions`.`user_id` != 188616 
AND `solutions`.`id` IN (
  SELECT `iterations`.`solution_id` FROM `iterations`
) 
AND `solutions`.`approved_by_id` IS NULL 
AND `solutions`.`completed_at` IS NULL
AND (num_mentors < 3) 
ORDER BY num_mentors > 0 ASC,
         last_updated_by_user_at > '2018-07-13 10:01:29' DESC,
         (independent_mode IS NULL OR independent_mode = 0) DESC,
         solutions.created_at > '2018-07-13 10:01:29' DESC,
         core DESC,
         num_mentors ASC,
         last_updated_by_user_at ASC LIMIT 20
```

**Comment by iHiD** [comment]
I think this is much better now so I'm going to close it :)
