### ISSUE TITLE
You're told you'll get mentor feedback even after you complete and publish an exercise

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3893]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/214._
_Originally posted by @carolineschnapp._

#

Red underlining is my own below.

When you complete an exercise, you are told you will no longer get mentoring on it:

<img width="261" alt="exercism 2018-07-15 13-51-05" src="https://user-images.githubusercontent.com/143817/42736487-29842e30-8836-11e8-9fe2-054904ad1cb7.png">

Yet, when you visit the completed and published exercise later, you're told you'll get some:

<img width="562" alt="exercism 2018-07-15 13-48-40" src="https://user-images.githubusercontent.com/143817/42736483-109dad60-8836-11e8-9fd3-be4a955b3b5b.png">

**Comment by iHiD** [comment]
This is now fixed. Thanks.
