### ISSUE TITLE
mentorcism: Approved exercise still appears in mentor dashboard...

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3897]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/203._
_Originally posted by @rpottsoh._

#

The following exercise has been approved however it still appears in my mentor dashboard as requiring action from me:
![image](https://user-images.githubusercontent.com/6978003/42453711-93fbfe80-835b-11e8-8de6-e2c0f9e51b8d.png)

I reviewed this exercise by making my way to the exercise via the notification I received of a new comment, via. the bell icon...  While reviewing the comments I accepted the exercise....  I then went to my mentor dashboard to find that the exercise was listed there.  When I click the exercise it indicates that it has been accepted...  I am not sure if this is a bug or if there is just some lag between when an exercise is accepted and when the dash board picks on this.

Again, if I am restating another issue, I apologize in advance.  Ijust wanted to get my findings out as quickly as possible and don't have the time to research open/closed issues right now.

**Comment by iHiD** [comment]
Closing in favour of https://github.com/exercism/exercism.io/issues/3978
