### ISSUE TITLE
Filtering the “next solutions to mentor”

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3901]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/195._
_Originally posted by @NobbZ._

#

There are filters on the mentors dashboard (https://mentors-beta.exercism.io/mentor/dashboard) which do not seem to apply to "Next solutions to mentor".

In my case where I do not have any pending solutions, the do not do anything on a first glance. Only on a second try I realized, that “You currently have no solutions that need mentoring” was replaced by “You have no solutions in this category”.

It would be nice if the filters would also apply to the “next solutions to mentor”.

Especially when doing initial mentoring, I prefer to filter by exercise, such that I can batch-mentor all open `hello-world` in one go instead instead of doing them randomly.

**Comment by iHiD** [comment]
Done.
