### ISSUE TITLE
mentorcism: Walkthrough, installing CLI on Mac manually

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3903]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/192._
_Originally posted by @rpottsoh._

#

@rpottsoh commented on [Fri Jun 22 2018](https://github.com/exercism/interactive-cli-walkthrough/issues/35)

![image](https://user-images.githubusercontent.com/6978003/41796609-3caa39a4-7635-11e8-8d21-01faedb1e3bf.png)

The `releases page` link does not appear to cause a new browser tab to open.  I must qualify my remark by stating that I am testing this with chrome on a Windows computer.  I am assuming the link behaves the same way on a Mac.

It would be better I think if clicking the link would trigger a new browser window to open to the releases page instead of taking the user away from the site in the middle of the walk through. 

This should accomplish the task:
```html
<a href="https://github.com/exercism/cli/releases/latest" target="_blank">https://github.com/exercism/cli/releases/latest</a>
```

---

@rpottsoh commented on [Fri Jun 22 2018](https://github.com/exercism/interactive-cli-walkthrough/issues/35#issuecomment-399572776)

I didn't examine this point on the Linux path.  It likely would also benefit from this improvement.

---

@kytrinyx commented on [Fri Jun 22 2018](https://github.com/exercism/interactive-cli-walkthrough/issues/35#issuecomment-399621504)

Nice, good catch. Thanks!

---

@rpottsoh commented on [Sun Jul 01 2018](https://github.com/exercism/interactive-cli-walkthrough/issues/35#issuecomment-401633194)

@kytrinyx  I'd be happy to open a PR for this, however I have discovered I can no longer get `bundle exec rake compile` to work.  I cannot get libv8 to compile, `therubyracer` is dependent on it.  I know what changes to make to the *.tw2 files, just won't be able to check my changes...

---

@iHiD commented on [Sun Jul 01 2018](https://github.com/exercism/interactive-cli-walkthrough/issues/35#issuecomment-401639609)

@rpottsoh I actually think the best place to make this change is in the website and make a global rule for it for all links. Would you mind creating an issue on v2-feedback that points to this issue and I'll triage and get it sorted before launch from there pls. I'd do it myself but I'm on my way to bed :)

**Comment by iHiD** [comment]
@kntsoriano Did we do this and can this issue be closed?

**Comment by rpottsoh** [comment]
I just clicked the link and it spawned a new browser tab.  Looks safe to close from where I  sit.

**Comment by iHiD** [comment]
Thanks @rpottsoh! I shall close it :)
