### ISSUE TITLE
state of v1 submissions after they got transferred to v2?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3904]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/190._
_Originally posted by @NobbZ._

#

What will be the state of submissions we already did on v1 after they got transfered to v2 in the upcoming and final release?

I do currently see these options:

* Approved and published: This way they have basically the same state as before. Everyone could in theory see and comment on them. But the user isn't able to get mentors feedback. Also those solutions might be below par, such that other students might pick up inidiomatic or even dangerous habits from them.
* Approved and unpublished: This way a user won't get mentors feedback but were allowed to publish his solution at will to other people who could "learn" from them as in the former bullet point.
* In mentors queue: This is what we did August 2017 and produced a year spanning menoring backlog. This would put a lot of burden on the mentors to mentor solutions from people that probably do not even use exercism anymore or never wanted feedback. After mentors got through the backlog to current exercises they might be exhausted and quality of feedback might have decreased massively.
* In independent mode: This way no one could see those exercises, neither would a mentor see them. If we allow students to selectively move solutions from independant mode to mentor mode (at a limited rate), students that want to were able to get valuable feedback. If we do not allow that, then it is as if those submissions never had happened, while they also forbid proper participation in that track forever.

My favorite were the latter with "allow to move to mentor mode".

Based on slack: https://exercism-mentors.slack.com/archives/CAQP7JL3T/p1530199566000487

**Comment by NobbZ** [comment]
I think this can safely be closed as my original questions have been answered by the migration fact ;) and Ali I got the (buggy) possiblity to get my solutions mentored eventually.
