### ISSUE TITLE
request -- Add ability to edit mentor comments

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3906]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/188._
_Originally posted by @aldraco._

#

Having another opportunity to edit comments that you have made to clarify what you mean could be helpful. Sometimes you just need another chance after hitting submit and realizing you weren't very clear about something.

I understand how this could also be a vector for harassment, but it would be a nice feature to have.

**Comment by c-dante** [comment]
I support event sourced comments -- just full edit history reduced down.

**Comment by iHiD** [comment]
Closing in favour of https://github.com/exercism/exercism.io/issues/3974
