### ISSUE TITLE
Ability to stay on the current solution page when clicking on complete

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3907]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/186._
_Originally posted by @MarcosX._

#

![screen shot 2018-06-27 at 07 13 46](https://user-images.githubusercontent.com/856376/41987033-6d4e59dc-7a0e-11e8-989a-86aa8a97403f.png)

As shown in this screenshot, once someone clicks on complete exercise there is really no flow other than going to the next track.

Usually that's the normal flow and not having the option to close that modal works fine, but I happened to click on the complete button by mistake and had no other way to stay on the page.

**Comment by iHiD** [comment]
This is done now.
