### ISSUE TITLE
User reflections do not parse markdown

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3908]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/185._
_Originally posted by @JoelQ._

#

I left some thoughts when publishing a shared solution. However the rendered text does not seem to be processed as markdown. Note the backticks in the image below.

![exercism 2018-06-27 11-28-59](https://user-images.githubusercontent.com/1006966/41983970-750dc97a-79fd-11e8-8adb-7219fe672638.jpg)

**Comment by iHiD** [comment]
Closing in favour of #3972
