### ISSUE TITLE
Comment preview doesn't handle paragraphs

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3909]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/182._
_Originally posted by @JoelQ._

#

![exercism 2018-06-26 23-59-13](https://user-images.githubusercontent.com/1006966/41952289-3408a1a8-799d-11e8-8777-b81d60893527.jpg)

![exercism 2018-06-27 00-01-49](https://user-images.githubusercontent.com/1006966/41952325-4df35220-799d-11e8-8d50-fb9bc5b218f5.jpg)

![exercism 2018-06-27 00-02-39](https://user-images.githubusercontent.com/1006966/41952352-6e4dd9f0-799d-11e8-90b9-52f73f320455.jpg)

**Comment by iHiD** [comment]
Closing in favour of #3884
