### ISSUE TITLE
Add ability to delete comments.

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3911]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/180._
_Originally posted by @tushartyagi._

#

I am not sure if this will be reproducible, but I was trying to submit a comment as part of testing. I entered the comment and clicked on the `Comment` button. Nothing happened, I clicked it multiple times but again did not see my comment. 

Then I reloaded the page and I saw the same comment repeated a lot of times. Now if this happens in real time, I would want a way to delete my comments. Is this possible?

Link to exercise: https://mentors-beta.exercism.io/my/solutions/1b22c73baf8b46c2b4e5a97ba08227c0

![image](https://user-images.githubusercontent.com/1630265/41925817-4f4f3d58-798b-11e8-9c01-04a659c602af.png)

**Comment by iHiD** [comment]
Closing in favour of #3973
