### ISSUE TITLE
Comment button broken and doesn't provide visual feedback

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3916]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/173._
_Originally posted by @melston._

#

I was responding to a comment from a mentor but the comment button appeared to not be enabled.  I pressed the button a few times but got no visual feedback.  When I came back to the exercise later I noticed that I got several copies of my comment in the comment section.

**Comment by iHiD** [comment]
Fixed.
