### ISSUE TITLE
Approving solution does not hide pass button

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3918]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/171._
_Originally posted by @ErikSchierboom._

#

When I approve a solution, the `I'll pass, thanks` button is still displayed. Shouldn't that be hidden after approving?

![image](https://user-images.githubusercontent.com/135246/41845885-52d162f6-7875-11e8-8ca5-0df5c884185e.png)

**Comment by iHiD** [comment]
Fixed.
