### ISSUE TITLE
Inconsistent capitalization on exercise page sidebar headers

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3925]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/159._
_Originally posted by @ErikSchierboom._

#

The headers in the sidebar menu on the right have inconsistent capitalization:

- Get started
- Been here before
- Still Stuck

The third option should probably be `Still stuck` to be consistent with the other headers.

**Comment by iHiD** [comment]
This is being tracked in another issue.
