### ISSUE TITLE
Not all resolutions are handled gracefully

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3927]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/157._
_Originally posted by @ErikSchierboom._

#

If one resizes the browser window, at some resolutions things start looking a bit odd with items being truncated instead of being repositioned:

![image](https://user-images.githubusercontent.com/135246/41808699-b4524620-76e1-11e8-9404-8f6ba5d52f48.png)

**Comment by iHiD** [comment]
This is being handled as part of our responsive update.
