### ISSUE TITLE
Buttons don't resize correctly on mobile

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3929]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/154._
_Originally posted by @ErikSchierboom._

#

When viewing the mentorcism website on a mobile device (iPhone 6S in this case), buttons are not resized correctly (they are too wide):

![image](https://user-images.githubusercontent.com/135246/41808642-d65f03b2-76e0-11e8-9cda-ad2d2d54cdb4.png)

**Comment by iHiD** [comment]
This is being handled as part of our responsive update.
