### ISSUE TITLE
Missing exercise images

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3930]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/153._
_Originally posted by @ErikSchierboom._

#

Some exercises don't yet have an image. On the overview page, this leads to an empty white box, which is not that bad. However, on the exercise details page, it displays are broken link:

See for example, [this page](https://mentors-beta.exercism.io/my/solutions/a23ceaf31cca4e879c7f9ec38be18344):

![image](https://user-images.githubusercontent.com/135246/41808628-a691cc5a-76e0-11e8-9da7-5559fee9dd88.png)

**Comment by iHiD** [comment]
This is being tracked in another issue.

**Comment by Insti** [comment]
> This is being tracked in another issue.

Which one?
