### ISSUE TITLE
Profile field spacing on Firefox/Linux

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3933]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/143._
_Originally posted by @chastell._

#

The label spacing for the Twitter/GitHub/Medium handles in Firefox 60 on Linux is off, looks like due to the width of the (fallback?) font:

![firefox borderised](https://user-images.githubusercontent.com/56633/39955799-b7c9f668-55d5-11e8-85f1-29ca1ed8fcde.png)

This is not the case in Chromium 66, which looks fine:

![chromium borderised](https://user-images.githubusercontent.com/56633/39955803-c9739f54-55d5-11e8-9af6-69b4e97ad663.png)

**Comment by iHiD** [comment]
This is being tracked in another issue.
