### ISSUE TITLE
How can I manage my comments?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3937]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/133._
_Originally posted by @martinfreedman._

#

Pending a positive outcome to #131 and #132, how do I delete or copy comments (editing old comments IMV should not be allowed once responded to but not pursuing that here for now) (See also #130)

**Comment by iHiD** [comment]
Closing in favour of #3973
