### ISSUE TITLE
Mentor queue is never-ending

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3953]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/89._
_Originally posted by @Insti._

#

It would be nice if the mentor queue only gave you N problems to do, so you could get some feeling of completion by doing 1 "page" worth.

As it is they just keep coming.

There could also be a 'give me more' button to refill the queue.

It would be good if N was configurable so you could set it to a sustainable daily rate.

I'm not sure where the bugs stop and feature requests start :)

**Comment by iHiD** [comment]
We've done this as a first step. We will continuously be improving this though :)

<img width="337" alt="screen_shot_2018-07-18_at_01 11 25" src="https://user-images.githubusercontent.com/286476/42878907-9e8d97dc-8a86-11e8-8eb6-63edf32e7264.png">
