### ISSUE TITLE
commenting: edit comments

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3954]
_Imported from https://github.com/exercism/-DEPRECATED-PLEASE-USE-exercism.io-REPO-v2-feedback/issues/72._
_Originally posted by @NobbZ._

#

As a mentor I made a typo in the code-portion of a reply and want to fix it, but there is no option to edit a comment at all.

As a student I realized a typo in a word which makes the hole sentence ununderstandable, I want to fix it, but there is no option to edit a comment at all.

Therefore I think we should enable editing of comments, as we had already on v1, but this time lets keep the history. By keeping the history we still avoid the "make things never had happened" while giving the opportunity to fix things that are necessary to fix.

**Comment by iHiD** [comment]
Closing in favour of https://github.com/exercism/exercism.io/issues/3974
