### ISSUE TITLE
Handle missing exercise image more gracefully

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3964]
https://github.com/exercism/v2-feedback/issues/153

**Comment by tejasbubane** [comment]
Example of this happening for ReasonML right now: (mentors page)

![screen shot 2018-08-01 at 12 45 04 pm](https://user-images.githubusercontent.com/980783/43509466-60b40e90-9590-11e8-95c6-86a69829ee83.png)

**Comment by iHiD** [comment]
@jackhughesweb Could you work out why this is happening on this page pls?

**Comment by jackhughesweb** [comment]
Quick thought: ReasonML was the track which had a missing icon in a few places - I'll have a check later

**Comment by tejasbubane** [comment]
@jackhughesweb Yes reasonml logo is in progress [here](https://github.com/exercism/website-icons/issues/5). We should handle such cases.
