### ISSUE TITLE
Add ability to delete comments

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3973]
Comments should be deletable. This needs to be done twice, once for mentoring and once for my-solutions. We don't want to actually lose the content (as we want to be able to check there's no abuse).

To achieve this we need to:

- [ ] Add a boolean flag to comments in the db for `deleted`
- [ ] Add an delete link next to comments
- [ ] When the delete link is pressed, show a JS confirmation for "Are you sure you want to delete this comment?"
- [ ] The server should then delete set the `deleted?` flag to true.
- [ ] Permissions should be checked to make sure the user is the person that posted the comment.
- [ ] The ui should show `This message has been deleted` instead of the comment if `delete?` is true

**Comment by kntsoriano** [comment]
@iHiD Should we close this?

**Comment by iHiD** [comment]
Yes. Hero. Thanks ;)
