### ISSUE TITLE
Add ability to edit comments

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3974]
Comments should be editable. This needs to be done twice, once for mentoring and once for my-solutions.

To achieve this we need to:
- [ ] Add a boolean flag to comments in the db  for `edited`
- [ ] Add a text box for `previous_content`
- [ ] Add an edit link next to comments
- [ ] When the edit link is pressed, show a comment box (similar to the add comment box).
- [ ] When the comment updated button is pressed, the old comment should be appended to `previous_content`, the comment should be updated, and `editable?` should be set to true
- [ ] The solution should update in place and the box should disappear.
- [ ] Permissions should be checked to make sure the user is the person that posted the comment.
- [ ] The ui should show `(Edited)`if `edited?` is true

Triaged from https://github.com/exercism/v2-feedback/issues/188

**Comment by kntsoriano** [comment]
@iHiD Should we close this?

**Comment by iHiD** [comment]
Yes. Hero. Thanks.
