### ISSUE TITLE
Solutions approved without comment do not change status properly

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3978]
When I go to my mentor dashboard I am currently seeing four solutions under the "Solutions you're mentoring" heading.

Three of these are solutions that I approved without a comment.

**Comment by NobbZ** [comment]
Which filter exactly?

Is it requires action from you? If so has the student iterated since you approved?

If you answered yes, it's probably a duplicate of #3880.

**Comment by junedev** [comment]
I just noticed that leaving a comment makes the entries disappear from the dashboard.
