### ISSUE TITLE
Add flag to the mentor dashboard to show if a solution is to a core exercise

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism.io#3980]
Core exercises are more important than side ones as they block. Things are already ordered to put core at the top, but it would be worth adding a little notation to show that this exercise is blocking others.

For example, in this image, the top three are core and the bottom two are not. It would be nice to know that at a glance :)

<img width="766" alt="screen shot 2018-07-18 at 01 03 21" src="https://user-images.githubusercontent.com/286476/42851989-66667a5a-8a26-11e8-80fd-b664dd311f8a.png">

**Comment by nicolechalmers** [comment]
@iHiD This should be clearer. 

<img width="843" alt="screen shot 2018-07-22 at 21 18 00" src="https://user-images.githubusercontent.com/5421823/43049272-1addfb1c-8df5-11e8-8b3b-e5d75c5ffa49.png">

**Comment by iHiD** [comment]
This is done.
