### ISSUE TITLE
Add a legacy filter to mentor dashboard

### ISSUE THREAD

**Issue by guygastineau** [exercism/exercism.io#3982]
When looking at the exercises with stale status in the dashboard there are some ruby exercises appearing even though I am only a mentor for bash.

**Comment by NobbZ** [comment]
Have you joined the ruby track as a student during the first 2 days after relaunch?

There has been a bug (a regression from the betas) that made you a mentor for every track you joined manually.

If you are affected by this, you will also see a ruby-mentor badge on your profile.

**Comment by NobbZ** [comment]
Oh, wait, stale… Have you commented on those solutions pre-migration?

**Comment by iHiD** [comment]
> Oh, wait, stale… Have you commented on those solutions pre-migration?

This probably.

**Comment by guygastineau** [comment]
Thanks guys. I tried to actively engaged in duscussion in V1, so this seems the most likely reason.

**Comment by guygastineau** [comment]
Should I close this?

**Comment by NobbZ** [comment]
I don't think so, in my opinion this is a bug in legacy migration

**Comment by guygastineau** [comment]
@NobbZ thanks

**Comment by iHiD** [comment]
@nobbz Would a "legacy" filter make you happy?

**Comment by NobbZ** [comment]
Yeah definitely.

But I'm also concerned about migrated users that are students only. How can they discover those old discussions?
