### ISSUE TITLE
notification emails are considered a single huge conversation by google inbox

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#3984]
I haven't checked other means of accessing my mailbox.

Currently all messages with the same subject are collected into a single thread of conversation. I'd prefer if those conversations were per user.

Also I'd like to see iterations of a user and comments of a user in the same thread.

This is currently for mentor emails only. I have not yet received notifications as a student.

I have also checked the headers of some of the emails, and it seems as if they all got the same `Message-ID`.

**Comment by corroded** [comment]
I agree. I think it will become its own thread if notification emails have the actual comment in them. It makes it easier for mentors to see if they can quickly jump in and reply or put it off for later when they have more time and focus to make a proper response.

**Comment by iHiD** [comment]
This should now be done. I've deliberately not put the users name in to the subject line as this is an abuse-vector I want to consider. But I've put the start of the uuid in which should affect the same effect.

Let me know if there are any problems or otherwise pls close this.

**Comment by NobbZ** [comment]
Thank you @iHiD, I'll watch the issue over the course of the next days, but I have to admit that this weekend will be for the family. So it might take until mid of next week before I can give you reasonable feedback on this.

**Comment by iHiD** [comment]
Enjoy your family time and thanks for all you've been doing. Your contribution has been absolutely invaluable.

**Comment by corroded** [comment]
@iHiD The threads are pretty cool now as they are now grouped by UUID as you said. I would still suggest that the emails should contain at least a snippet of the comment if there is one so mentors on the go can see if they can give a quick reply or a longer one that needs more time to think about. 

What do you think?

**Comment by iHiD** [comment]
@corroded Mind adding a new issue for that and closing this one pls? Thanks :)

**Comment by iHiD** [comment]
Thanks :)
