### ISSUE TITLE
Leaving a track should remove all that person's solutions

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism.io#3986]
Atm, when you leave a track it doesn't remove that person's solutions. We should change this so people can wipe their progress. As part of this I want to change the language on the button from "Leave Track" to "Leave and Delete Track".

We also want a second option to "Pause" a track but we'll do that later.

**Comment by guygastineau** [comment]
Would leaving and rejoining a track then become the preferred method for working through a track from scratch again?

**Comment by kylesnowschwartz** [comment]
You should also probably be able to 're-join' the track. Not only are all my solutions still present, but there's no option to join the language track again. I uncovered this bug while trying to find the CLI installation instructions, which seem to be missing from the website...

**Comment by kylesnowschwartz** [comment]
![screen shot 2018-07-19 at 12 48 09 pm](https://user-images.githubusercontent.com/11069001/42915191-79cec304-8b52-11e8-95c5-3789383c591d.png)

and in the section entitled *Getting Started* it says 
`For installation and learning resources, refer to the exercism help page.` with a link that just goes back to the language track index, and contains no further installation instructions I can find.

I think if there was a link to instructions for how to get the CLI downloaded and started, and instructions for the that specific language track, on the index page of the language track, that would have solved my issue.

I left a bit of a brain/emotions dump in @3827 detailing why I felt so pained while trying to get started. For context, I'm a returning user who completed the first 2 exercises of the Haskell language track before the switch to the new website, and I was attempting to continue my track on a different computer today.

**Comment by iHiD** [comment]
I've left a general comment on #3827. 

> I think if there was a link to instructions for how to get the CLI downloaded and started, and instructions for the that specific language track, on the index page of the language track, that would have solved my issue.

If you could open an issue specifically for this it would be helpful and will get addressed.

Thanks again for taking the time to input.

**Comment by Ornataweaver** [comment]
I suggest showing a warning before removing.

**Comment by BradleyJohnson** [comment]
@iHiD Apologies for the dupe and thanks for mentioning this issue. Seems like there's no way to delete an account so I take it there's no workaround at the moment to start any/all track(s) fresh?

**Comment by iHiD** [comment]
@BradleyJohnson That's correct. This is high priority on @kntsoriano's list but he's currently at drumming school in NYC so has limited hours of coding work atm (I imagine drumming for 8hrs per day knackers you pretty hard). But we will get to it soon, I promise :)

**Comment by BradleyJohnson** [comment]
@iHiD Understood, thanks for the info. Good luck at school @kntsoriano !
