### ISSUE TITLE
This URL gives the internet access to all solutions

### ISSUE THREAD

**Issue by mgmatola** [exercism/exercism.io#3996]
Related to another issue, I was playing around with URLs and discovered that this URL (of course edit it out if you want), if you plug in the language and slug you want. gives complete access to all published solutions.

```
https://exercism.io/tracks/<language>/exercises/<slug>/solutions
```

Yes, it gives you the opportunity to log in, but it doesn't require it.

Don't know if anybody cares. Just thought I'd bring it to your attention.

**Comment by NobbZ** [comment]
Thats usually what publish means.

Things get public then…

**Comment by iHiD** [comment]
Yeah - this is a feature, not a bug :)
