### ISSUE TITLE
🆘 Configuring CLI

### ISSUE THREAD

**Issue by duke578** [exercism/exercism.io#4000]
Hello,

I'm trying to configure CLI for the ruby class but its not working, 

I followed the instructions and copied this into the terminal 

**_exercism configure --token=dda54e34-e94c-4806-9007-5b5825ab082e_**  , 

but I get an error saying 
****Error: The base API URL 'https://api.exercism.io/v1' cannot be reached.**

**Get https://api.exercism.io/v1/ping: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)****

Please help

Thank you

**Comment by NobbZ** [comment]
It seems as if you have trouble connecting the API endpoint.

Can you please check if you are able to access https://api.exercism.io/v1/ping in a browser and returns a JSON equivalent to the following?

```json
{
  "status": {
    "website": true,
    "database": true
  }
}
```

If you are on linux, please check from terminal as well using `curl https://api.exercism.io/v1/ping`.

If the browser works but the terminal does not, please check if your `HTTP_PROXY`/`HTTPS_PROXY` environment variables are set correctly on the terminal.

Also check if you have activated some firewall that interferes here.

**Comment by duke578** [comment]
Thank you very much, 

the browser is returning the JSON equivalent. 
I disabled the firewall and seems to be working fine. 

Thank you

**Comment by MohamedHajr** [comment]
I'm having the same issue, gone throw the same steps to reconfigure the CLI and now gets an Error: couldn't find it whenever I submit an exercise, and on the website when I went to the hello world exercise to check the instructions for submitting every time I hit the link I get redirected to the python track page.

**Comment by mbarkhau** [comment]
I'm having the same issue.

```
mbarkhau@L-ManuelBarkhau:/mnt/c/Users/ManuelBarkhau/Dropbox/exercism
$ curl https://api.exercism.io/v1/ping
{"status":{"website":true,"database":true}}mbarkhau@L-ManuelBarkhau:/mnt/c/Users/ManuelBarkhau/Dropbox/exercism
$
mbarkhau@L-ManuelBarkhau:/mnt/c/Users/ManuelBarkhau/Dropbox/exercism
$ exercism configure --token=<redacted>
Error: The base API URL 'https://api.exercism.io/v1' cannot be reached.

Get https://api.exercism.io/v1/ping: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
mbarkhau@L-ManuelBarkhau:/mnt/c/Users/ManuelBarkhau/Dropbox/exercism
$ curl https://api.exercism.io/v1/ping
{"status":{"website":true,"database":true}}
```

I'm running this inside of WSL, which is probably the reason it's failing, but I don't see what I can do about it atm.

**Comment by NobbZ** [comment]
Which version of Linux is running inside of WSL?
Does a windows version work?
Have you tried increasing the timeout? As far as I remember there should be a flag to do so...

**Comment by mbarkhau** [comment]
WRT Linux version:

```
$ exercism troubleshoot

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.11
Latest:  <unknown>

Error: Get https://api.github.com/repos/exercism/cli/releases/latest: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Call 'exercism upgrade' to get the latest version.
See the release notes at https://github.com/exercism/cli/releases/tag/ for details.


Operating System
----------------
OS:           linux
Architecture: amd64


Configuration
----------------
Home:      /home/mbarkhau
Workspace: /home/mbarkhau/exercism (default)
Config:    /home/mbarkhau/.config/exercism
API key:   <not configured>
Find your API key at https://exercism.io/my/settings

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [Get https://api.github.com: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)]
    * 410µs

Exercism:
    * https://api.exercism.io/v1/ping
    * [Get https://api.exercism.io/v1/ping: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)]
    * 676µs
```

WRT. Timeouts:
```
$ exercism configure --timeout 5000 --token=6baa7a12-e7e7-4fbd-9002-cde9faee4e34
Error: The base API URL 'https://api.exercism.io/v1' cannot be reached.

Get https://api.exercism.io/v1/ping: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

I have not tried the windows version yet. I was hoping to do the bash track, so I didn't think that would be a good choice...

**Comment by NobbZ** [comment]
I meant the version of Linux, eg Ubuntu.

If you want to do bash, just doing a windows installation and using a POSIX wrapper like cygwin or msys2 might be easier. Or perhaps a vagrant box?

**Comment by mbarkhau** [comment]
I think before I install vagrant or cygwin, I'll just give up.

**Comment by mbarkhau** [comment]
I restarted my computer and now it appears to work. I hate computers...
