### ISSUE TITLE
Concepts progress not updating on Ruby track

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/exercism.io#4006]
I have completed 7 of 11 exercises on the Ruby track but the all of the items under the 'Concepts' section still read 0%.
![progress](https://user-images.githubusercontent.com/1254212/42949011-cbe1a49a-8b3e-11e8-9fd7-26cc44132ac0.png)

**Comment by iHiD** [comment]
This is an issue specific to the Ruby track.

None of the core exercises have topics - only some of the extra exercises at the bottom: (e.g. https://github.com/exercism/ruby/blob/master/config.json#L22)

The Ruby track really needs some work on both unlocking and topics.

If you would like to open an issue to suggest topics and/or a PR for them on the Ruby track, that would be great.

I will close that here as it's not a bug with the website or product. Thanks for reporting :)

(cc @exercism/ruby)
