### ISSUE TITLE
Bash - 500 error on mentors page

### ISSUE THREAD

**Issue by budmc29** [exercism/exercism.io#4009]
https://exercism.io/tracks/bash/mentors

<img width="781" alt="image" src="https://user-images.githubusercontent.com/7063792/42956154-291de6ea-8b77-11e8-9c88-0b636f497f0b.png">

**Comment by guygastineau** [comment]
I ran into this too.

**Comment by iHiD** [comment]
This should now be fixed via [this commit](https://github.com/exercism/website-copy/commit/85026db71a8723ddfb18771c897816296e49389e).
