### ISSUE TITLE
students: no notifications and emails for solutions approved without a comment

### ISSUE THREAD

**Issue by NobbZ** [exercism/exercism.io#4012]
A student has usually these email settings available:

> ## Usage Emails
> [ ] Email me when a mentor comments on my solution
> ## General Communications
> [ ] Email me about product updates

If he activates “Email me when a mentor comment on my solution", it seems exactly like this. Emails will only be sent on comments.

Also it seems as if there are no notifications in a approve-without-comment as well.

There was a user today in the gitter asking for support since he still waited for approval by a mentor.

Some back and forth between gitter and slack revealed that the solution was already approved, but without any comment.

The student said he got neither an email nor a notification about the approval.

He checked his email settings and said the mentor-comments were activated.

**Comment by iHiD** [comment]
This got fixed. Thanks :)
