### ISSUE TITLE
Perfect numbers exercise icon has less contrast than other icons

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism.io#4018]
Your personal track page now shows underneath each core exercise the extra exercises it unlocks. The exercise icons all look really sharp, except for the perfect-numbers icon, which looks like it has far less contrast than the other icons:

![image](https://user-images.githubusercontent.com/135246/42986069-76c21876-8bf4-11e8-9de4-7295c9bdc209.png)

![image](https://user-images.githubusercontent.com/135246/42986163-df135660-8bf4-11e8-823f-75e5b818d2db.png)

**Comment by iHiD** [comment]
@nicolechalmers Could you generate a new image for this pls? Thanks :)

**Comment by iHiD** [comment]
Closed in favour of https://github.com/exercism/website-icons/issues/6
