### ISSUE TITLE
Check filepaths, not just filenames for tests.

### ISSUE THREAD

**Issue by ZapAnton** [exercism/exercism.io#4022]
It seems like on every submitted Rust exercise page the test suite is not rendered.

![image](https://user-images.githubusercontent.com/8658767/43009398-3db9c978-8c46-11e8-9032-4c1fb58ee57d.png)

**Comment by iHiD** [comment]
So the reason for this is that Rust's tests are in a subdirectory.

In the code:
- We have a `test_pattern` that defaults to `[tT]est`. Any filename (not filepath) that matches this is considered part of the tests. 
- This can be overriden in config.json with the key `test_pattern`
- Rust puts its tests in a folder, but doesn't then suffix the tests wth `_test` or something recognisable.

I see two options:
1) Look at filepaths not filenames when comparing the `test_pattern`
2) Presume any file in a folder called `tests` to be part of the test-suite.

I prefer the second option. Thoughts? (cc @kytrinyx @ccare @kntsoriano)

**Comment by kytrinyx** [comment]
The test pattern is configurable. Historically it applies  to the filepath, not the file name.

**Comment by iHiD** [comment]
> Historically it applies to the filepath, not the file name.

We change change the website to do this. Does the new CLI need anything doing?

**Comment by kytrinyx** [comment]
> Does the new CLI need anything doing?

No, right now it's not bailing/warning on test file submission, which we might want to do (and then add a `--force` flag so people can submit it if they mean to). But we operate on file paths there as well.

**Comment by iHiD** [comment]
@ccare @kntsoriano Can one of you change the test pattern to apply to the filepath, not the file name please. Can you confirm who is doing it? Thanks :)

**Comment by kntsoriano** [comment]
I'll work on this.
