### ISSUE TITLE
A link I am using to Exercism CLI is broken, I need a replacement

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism.io#4024]
In [TESTS.md](https://github.com/exercism/delphi/blob/master/docs/TESTS.md) I have a link to the CLI that is now broken.  I need a replacement.  

md snippet:
```
Exercises that have been fetched using the [Exercism command line client](http://www.exercism.io/cli) are delivered with 
```

**Comment by iHiD** [comment]
[As of about 5mins in the future...]

The link is no-longer broken, but could you change it to `https://exercism.io/cli` pls? (`https` and no `www.`)

**Comment by rpottsoh** [comment]
No problem.  Thanks for the fix.
