### ISSUE TITLE
email notifications doubly wrong

### ISSUE THREAD

**Issue by tom-harvey** [exercism/exercism.io#4025]
A notification email from hello@exercism says:
> A student you are mentoring (xxxxx) has posted a new comment on their solution to Hamming on the Go track. You can view it \<here\>.

Wrong 1: I am not a mentor.
Wrong 2: I cannot view it \<here\>. Instead: "You are being \<redirected\>.
Wrong 2a: I am not redirected.

I can reliably infer that I am receiving this (and others like it) because of V1 comments I made to student xxxxx. I can surmise that if I were to become a mentor, the email may function as intended. I can guess that sending this email to V1-commenting non-mentors is an intentional mentor recruiting strategy. If this guess is right, I even approve of this strategy, except that instead of being wrong twice, and leaving me inferring, surmising, and guessing, I would suggest sending more accurate and explanatory emails.

**Comment by iHiD** [comment]
@tom-harvey Sorry - we're clearly missing a guard to not send emails to non-mentors. Apologises for spamming you and thanks for reporting. I'll fix this now.

**Comment by iHiD** [comment]
This is fixed in exercism/website#201 - just deploying now. Thanks again for the information and sorry for the SPAM :)

**Comment by iHiD** [comment]
>  I can guess that sending this email to V1-commenting non-mentors is an intentional mentor recruiting strategy.
