### ISSUE TITLE
Unable to re-join a track after leaving it

### ISSUE THREAD

**Issue by Ornataweaver** [exercism/exercism.io#4026]

**Comment by Ornataweaver** [comment]
Also https://github.com/exercism/exercism.io/issues/4027

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/222

**Comment by Ornataweaver** [comment]
I'm really sorry about being emphatic. I'm trying to communicate with people, I didn't mean to have a demeaning tone.

**Comment by Ornataweaver** [comment]
Thanks for fixing.
