### ISSUE TITLE
Update prism config to have correct file extensions.

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism.io#4044]
Update [Prism config](https://github.com/exercism/website/blob/master/config/initializers/prism.rb#L180) to have all the correct file extensions in. 

The format is 
`"language" => %w{file_extensions}`

**Comment by tejasbubane** [comment]
We should only keep keys corresponding to track names to reduce the noise there.

**Comment by jackhughesweb** [comment]
Things to do:
- [ ] Find a syntax highlighter option for Factor (.factor)
- [ ] Decide how to handle file extensions used by multiple languages


Current duplicates <extension: languages>
vhost: apacheconf, nginx
b: basic, brainfuck
h: c, cpp, objectivec
d: d, makefile
es: erlang, javascript
fs: fsharp, glsl
frag: glsl, javascript
pro: ini, prolog
fcgi: lua, perl, php, python, ruby
m: matlab, objectivec
inc: pascal, php, sql
pp: pascal, puppet
pl: perl, prolog
cgi: perl, python
spec: python, ruby

**Comment by jackhughesweb** [comment]
> "We should only keep keys corresponding to track names to reduce the noise there." @tejasbubane 

@iHiD any thoughts on this?

**Comment by NobbZ** [comment]
> es: erlang, javascript

I have not yet seen `es` used in erlang projects.
