### ISSUE TITLE
Github account authentication failing since upgrade

### ISSUE THREAD

**Issue by cdpfeetfirst** [exercism/exercism.io#4053]
Since the upgrade I have found I am unable to login with my github account (cdpfeetfirst).
It seems like you have the cdpfeetfirst handle but there is no direct password for it (that I know) so I can’t get in.
![exercism](https://user-images.githubusercontent.com/5482637/43110942-2ffa97b4-8ede-11e8-977b-9d694bf509dc.png)

**Comment by iHiD** [comment]
I can confirm that your account is configured for you to log in with GitHub. What messages do you see within the GitHub authentication process? Can you try authenticating and let me know the exact time (and timezone) that you do it. Could you take some screenshots along the way please. Then I'll look in the logs and see if I can work anything out. Thanks.

**Comment by iHiD** [comment]
@ivan-ochc Could you follow the same instructions pls?

**Comment by ivan-ochc** [comment]
<img width="420" alt="2018-07-24 at 1 20 45 pm" src="https://user-images.githubusercontent.com/6141351/43132491-a876ae4c-8f44-11e8-91aa-a48bf97c6070.png">

UTC time is 10:23

**Comment by iHiD** [comment]
@ivan-ochc What do you see on GitHub when you do that?

**Comment by ivan-ochc** [comment]
@iHiD, 
STR:
1) Click on Log in with Github
2) Redirect to regular github OAuth authorization page
3) Click on "Authorize exercism"
4) Redirect to Exercism Sign up page with authenticate error

**Comment by ivan-ochc** [comment]
@iHiD, i've resolved this issue: i had to verify my github profile email

**Comment by cdpfeetfirst** [comment]
Email verification in github profile worked for me too. Thanks!
