### ISSUE TITLE
Backlog on Mentor Dashboard

### ISSUE THREAD

**Issue by adambuckland** [exercism/exercism.io#4060]
Whilst backlogs have been uploaded to gist by Jeremy [example](https://gist.github.com/iHiD/50f4fc82e63717766ae233f8f3854336), it would be nice to see on our dashboards the current backlog, as we can see how urgent our input is.

For reference, my use case is I tend to do this on lunch hour, but I can push a little bit further if I know we have a backlog to clear 😄

**Comment by pgaspar** [comment]
Hello! This issue may be a duplicate of #4032.

**Comment by adambuckland** [comment]
Yep, so it is!
