### ISSUE TITLE
Unable to leave a track in independent mode

### ISSUE THREAD

**Issue by Ornataweaver** [exercism/exercism.io#4065]
_Editing this for context -kytrinyx_

When in independent mode, it would be useful to be able to leave a track. Right now it is only possible to leave the track when in mentored mode.

**Comment by Ornataweaver** [comment]
@Zialus

**Comment by Ornataweaver** [comment]
https://github.com/exercism/exercism.io/issues/3810

**Comment by kytrinyx** [comment]
Thank you @Ornataweaver, I agree, this is one of the features we need to do in order to complete the functionality of mentored and independent mode.
