### ISSUE TITLE
Change to font awesome 5.1

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism.io#4071]
All existing icons need to go to the variety closest to FA 4.

I have a licence I can add when we do this.

**Comment by tejasbubane** [comment]
Looks like there are some issues here:

![screen shot 2018-08-01 at 1 09 30 am](https://user-images.githubusercontent.com/980783/43482872-97f8f71c-9527-11e8-8c64-9037ebe03b5e.png)

![screen shot 2018-08-01 at 1 08 42 am](https://user-images.githubusercontent.com/980783/43482871-97b13300-9527-11e8-9eb4-e1d88485eb6e.png)

**Comment by iHiD** [comment]
@tejasbubane Thanks. Weirdly, that works fine for me. What OS/Browser are you on?

**Comment by iHiD** [comment]
Closing in favour of https://github.com/exercism/exercism.io/issues/4134
