### ISSUE TITLE
error downloading exercise

### ISSUE THREAD

**Issue by mikewalker** [exercism/exercism.io#4074]
I was trying to download an exercise that I completed on the old site inorder to get the .solution.json file.

exercism download --exercise=anagram --track=cpp

Error: Get https://api.exercism.io/v1/solutions/latest?exercise_id=anagram&track_id=cpp: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Repeated the command and got this error. Note the second anagram which is actually an executable.

Error: open /home/mwalker/exercism/cpp/anagram/anagram/.solution.json: not a directory

**Comment by iHiD** [comment]
I suspect this was a network issue. If it reoccurs pls feel free to reopen :)
