### ISSUE TITLE
Saddle Points Exercise: Clarify it's NxN matrices or add NxM test cases

### ISSUE THREAD

**Issue by Alexhans** [exercism/exercism.io#4077]
In the [saddle_points](https://github.com/exercism/python/tree/master/exercises/saddle-points) exercise definition there's no indication that the saddle point definition should only cover NxN matrices.

That's why I added tests in my solution to cover NxM as well like so:

```python
def test_non_square(self):
    matrix = [[3, 1, 3], [3, 2, 4]]
    self.assertEqual(saddle_points(matrix), set([(0, 2), (0, 0)]))
 ```

It has been suggested to me that I create an issue or PR to address this but I'm not entirely sure what option I should pick.  

I think that specifying it as NxN would probably keep it simple which is what probably would be most beneficial for people who are doing the track.

**Comment by rpottsoh** [comment]
@Alexhans you should reopen this issue in [exercism/problem-specifications](https://github.com/exercism/problem-specifications/issues).

**Comment by Alexhans** [comment]
[Done](https://github.com/exercism/problem-specifications/issues/1276).  Thanks.  I'll close this one
