### ISSUE TITLE
Error: not in workspace

### ISSUE THREAD

**Issue by cruelcoding** [exercism/exercism.io#4081]
Hello! I’m trying to submit a completed exercise (SWIFT track)

exercism submit Leap.swift

But I’m constantly getting an error  

Error: not in workspace. 

What’s wrong?

Previous two exercises was committed with no issues at all.

**Comment by NobbZ** [comment]
You are using Windows or mac, and are in a directory that is with a lowercase ``e`` instead of a capital one. Windows/Mac treats those the same, the CLI does not.

Possibly related:

* #3820
* #2468

as well as others in github.com/exercism/cli

**Comment by cruelcoding** [comment]
Mac-mini-Urij:sources ymirtov$ exercism workspace
/Users/ymirtov/Exercism

Mac-mini-Urij:~ ymirtov$ ls
Applications	Downloads	Movies		Pictures
Desktop		Exercism	Music		Public
Documents	Library		OneDrive	bin
Mac-mini-Urij:~ ymirtov$ 

Exercism - a capital 'E', still can't submit...

**Comment by cruelcoding** [comment]
Thank you very much!

Mac-mini-Urij:~ ymirtov$ cd Exercism
Mac-mini-Urij:Exercism ymirtov$ cd swift
Mac-mini-Urij:swift ymirtov$ cd leap
Mac-mini-Urij:leap ymirtov$ cd sources
Mac-mini-Urij:sources ymirtov$ pwd
/Users/ymirtov/Exercism/swift/leap/sources
Mac-mini-Urij:sources ymirtov$ exercism submit Leap.swift


    Your solution has been submitted successfully.
    View it at:

    
    https://exercism.io/my/solutions/4689ba62f393482aa9dc4d105f3b3ec1

Mac-mini-Urij:sources ymirtov$
