### ISSUE TITLE
Bad link to Linkedin profile

### ISSUE THREAD

**Issue by bkhl** [exercism/exercism.io#4082]
I clicked "Edit public profile" and entered my Linkedin id (in this example "foo"):

If my id is `foo`, the link produced on my profile is: `https://exercism.io/profiles/foo`

It seems it should have been: `https://www.linkedin.com/in/foo/`

**Comment by tejasbubane** [comment]
I think handles might not work for linkedin hence the field expects full URL - ref: https://www.linkedin.com/help/linkedin/answer/49315/finding-your-linkedin-public-profile-url?lang=en

Also the URL for medium has an `@` missing. My PR should fix both these issues.
