### ISSUE TITLE
No maintainers appear at bottom of Delphi page

### ISSUE THREAD

**Issue by rpottsoh** [exercism/exercism.io#4084]
@iHiD or @kytrinyx 
I am assuming I need to add more information to `maintainers.json`, however I have the same amount of information that I have placed [here](https://github.com/exercism/website-copy/blob/master/mentors/delphi/r.json) and I appear on the site as a mentor.  

`"show_on_website"` is `true` in `maintainers.json`.  I am happy to fill in more of the information fields. I've assumed some default (from my GitHub identity) would be picked up by filling fields in with `null`.  My profile appears fine on the list of maintainers page.

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/255 - will deploy shortly.

Thanks @rpottsoh :)

**Comment by rpottsoh** [comment]
Checked it out via my phone a few minutes ago.  Looks good, thanks.
