### ISSUE TITLE
New submission showing that it was imported from independent mode

### ISSUE THREAD

**Issue by mikewalker** [exercism/exercism.io#4085]
A solution that I completed yesterday (scrabble score - c++), is showing the following message now. This solution was also submitted yesterday. I've never been in independent mode so I'm not sure what this is about. 

**This solution has been imported from independent mode. Mentoring will become available when your other solutions have been mentored.** 

Also worth mentioning is that this is the only solution waiting for mentoring too.

**Comment by nicanor** [comment]
Same here. Also, when I complete an exercise and have this sign, I don't see the see-community-solutions button, but I can still access them by typing the URL.

**Comment by pranasas** [comment]
Same here. Looks all messed up.

**Comment by iHiD** [comment]
I believe this should be correct now. Please could you let me know and close this if it's ok. Sorry for the disruption.

**Comment by iHiD** [comment]
@mikewalker Thanks for your patience. This has proved to be pretty tricky to get right. Could you give me the uuid (from the URL) of a solution with this problem pls?

**Comment by mikewalker** [comment]
@iHiD sure no problem, here's one 22a9f2446df24bf9b4db5c7303fae540

Its one of many, it seems that all solutions that were imported from the old site that have since received mentoring have the same problem.

**Comment by mikewalker** [comment]
Just noticed another issue, from a track that had all of the core completed. Its now back to showing the click here to request mentoring thing again. 

**This solution has been imported from independent mode. You may request mentoring to unlock its extra exercises. Request mentoring.** 

A uuid for a exercise with this issue is f7cdd173969241b5b8f342be4fe4b573.

Hope this helps. :)

**Comment by iHiD** [comment]
So.

- `22a9f2446df24bf9b4db5c7303fae540`: In the db, it seems that this hasn't had any mentor comments or been approved by a mentor so I think that's in the correct state.
- `f7cdd173969241b5b8f342be4fe4b573`: This was wrong in the db. I've switched it (and a similar batch) to be correct.

Does that look any better now?

**Comment by mikewalker** [comment]
@iHiD  Looks a lot better. I think we can say that the issue reported is resolved, there may be more edge cases but lets close this one one deal with anything else as a separate issue.

**Comment by iHiD** [comment]
Thanks for helping me through it :+1:
