### ISSUE TITLE
Maintainer: Cannot turn an 'unlocked-by' exercise into a 'bonus' exercise. 

### ISSUE THREAD

**Issue by Insti** [exercism/exercism.io#4090]
I've moved an exercise (beer-song) from the unlock tree to be a bonus exercise by [changing it's unlocked-by value in config.json](https://github.com/exercism/ruby/commit/cd962c6c609172331f748daa981c3969cb32aa41). It shows in the correct position when running `configlet tree .`but it is still showing up as locked on the website.

(Ruby track)

**Comment by kntsoriano** [comment]
@Insti Thank you so much! You're correct. That specific line is why `unlocked_by` isn't updated to `nil`.

**Comment by Insti** [comment]
Thanks @kntsoriano :heart:
