### ISSUE TITLE
Prevent (temporarily) two mentors mentoring the same solution

### ISSUE THREAD

**Issue by F3PiX** [exercism/exercism.io#4107]
_copied from Slack_
As long as we are working on solving the backlog of legacy submissions, would it be possible  to prevent that two mentors are picking up the same submission? 
It happened a few times that another mentor and me both mentored the same solution at the same moment. Without knowing of eachother. I feel that it would be better use of mentoring capacity if we could for instance 'claim' a solution, so that either it is blocked, or that another mentor know that it is taken care of.

@ihid Friendly reminder that you want to tackle this

**Comment by iHiD** [comment]
Fixed by https://github.com/exercism/website/pull/300
