### ISSUE TITLE
Keep download instructions on solution page, too

### ISSUE THREAD

**Issue by renao** [exercism/exercism.io#4114]
Hello everyone,

thanks for this great website. I just received [some feedback on some older solution of mine](https://exercism.io/my/solutions/4cfa1cdd2d5d47d8b66b7499caef311a), which was migrated from the previous website and I just placed it for a new mentor feedback.

It showed, that there are now some tests failing and I wanted to fix my solution. But there were no download instructions, like in the excerises one has not submitted at all.

For my (very own?) user experience it would have been nice, to have them still anywhere in the solution page (below the discussion, inside the instructions area, ...whereever ;)).

To clarify: the "download info box" I am talking about:

![screenshot 11](https://user-images.githubusercontent.com/3899638/43572655-56b4ab10-9640-11e8-9ba9-8e9bbd28b4de.jpg)

Thanks for everything and keep on talking code 👍 🎤

**Comment by NobbZ** [comment]
Possible duplicate of #3838.

**Comment by renao** [comment]
Very possible @NobbZ - thanks.
