### ISSUE TITLE
Issues with Font Awesome rendering.

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism.io#4134]
See: ![image](https://user-images.githubusercontent.com/135246/43625787-1e1579ba-96ef-11e8-9c8d-79d0605b6259.png)

**Comment by jackhughesweb** [comment]
That looks like Font Awesome is having trouble displaying the comments icon. Which browser (OS/browser/version) are you using?

**Comment by iHiD** [comment]
See also https://github.com/exercism/exercism.io/issues/4071#issuecomment-409343316

@jackhughesweb I'm assigning these to you :)

**Comment by ErikSchierboom** [comment]
> That looks like Font Awesome is having trouble displaying the comments icon. Which browser (OS/browser/version) are you using?

- Google Chrome version 68.0.3440.84 (Official Build) (64-bit)
- Windows 10 (17134.81)

I've also tried a Ctrl+F5 to do a hard refresh, but that didn't work.

**Comment by iHiD** [comment]
I believe @jackhughesweb is all over this :)

**Comment by iHiD** [comment]
That better @ErikSchierboom ?

**Comment by ErikSchierboom** [comment]
Yep, fixed!

**Comment by tejasbubane** [comment]
Great. Fixed for me too. 👍
