### ISSUE TITLE
I don't want to be a delinquent  

### ISSUE THREAD

**Issue by F3PiX** [exercism/exercism.io#4141]
As a student, I once switched from mentoring mode to independent mode and back. Now my submissions prior to the independent mode are marked as 'imported from independent' mode, and that makes me a delinquent.  And I am afraid that the punishment is that I don't get any mentoring anymore. Not sure if that's the case.
But if it is, I'd expect that more students should be affected by this. (And mentors, because there was an Slack discussion a while ago that suggested us to switch temporarily to independent mode.) 

Also, I can't tell if there is an queueing issue in the first place, or maybe a UX thing?

1) If possible, I'd say that only solutions that are submitted _during_ independent mode should be marked.
2) I am worried: are my submissions queued for mentoring at all, or am I sentenced for life. (Still pleading not quilty.) 
3) I am not sure if this situation existed before the script (see https://exercism-mentors.slack.com/archives/CARRG4MNC/p1533033409000152) a few days ago.

Thanks so much for looking into this!!

Maud

@Maud on Slack, @F3PiX on Exercism

---

Dit is my current track flow chart:
![schermafbeelding 2018-08-03 om 18 05 59](https://user-images.githubusercontent.com/6314687/43653407-3e60ad80-9748-11e8-99f5-09b4c565eb34.png)
---

(I just found out:) this is my Hello World status:
![schermafbeelding 2018-08-03 om 18 09 11](https://user-images.githubusercontent.com/6314687/43653502-8c1d10c2-9748-11e8-831f-9955bbf98ad8.png)
That doesn't look right, or?

---

This is a recent (July 31th?) submission for a side exercise:
![schermafbeelding 2018-08-03 om 18 14 12](https://user-images.githubusercontent.com/6314687/43653708-283f2bc0-9749-11e8-8b02-6632778fa871.png)

---

And this is my criminal record on Grains:

![schermafbeelding 2018-08-03 om 18 16 14](https://user-images.githubusercontent.com/6314687/43653810-7a77fc96-9749-11e8-9d6f-a853023e995b.png)

 ---
This one is interesting because it is the only one showing 'legacy comments', but that was a comment I made 7 days ago, so that was in the new Exercism. (The comments from V1 are not showing. Should they?)

![schermafbeelding 2018-08-03 om 18 33 40](https://user-images.githubusercontent.com/6314687/43654524-d2c5302e-974b-11e8-91bf-56abf34593ba.png)

**Comment by iHiD** [comment]
Super helpful. Thanks :)

> If possible, I'd say that only solutions that are submitted during independent mode should be marked.

This is the case.

> I am worried: are my submissions queued for mentoring at all, or am I sentenced for life. (Still pleading not guilty.)

There is one queued for mentoring (Series)

> I am not sure if this situation existed before the script (see https://exercism-mentors.slack.com/archives/CARRG4MNC/p1533033409000152) a few days ago.

All of this is new really. Anyone who was in independent mode at the point of this change who had legacy solutions will have suffered, and the system is treating like a delinquent. Everyone else **should** be fine (I no way guarantee this is true though)

> I don't want to be a delinquent 

I've just reset your user_track in the db so that you should no longer be a delinquent. For future me, this is the script I ran. 

```
ut = UserTrack.find_by(user: User.find_by_handle('F3PiX'), track: Track.find_by_slug("ruby"))
ut.solutions.update_all(independent_mode: false)
FixUnlockingInUserTrack.(ut)
```

If anyone else is (incorrectly) being treated as a delinquent, let me know here :)

**Comment by rpottsoh** [comment]
@iHiD is this the same as (or similar to) #4094?

**Comment by iHiD** [comment]
It's similar. 

@F3PiX's problem was that she dropped into independent mode then back, at a bad time (on my advice), which has more strict rules and caused pain. The problem referenced in the other issue is legacy solutions that need to be handled one at a time. 

In both scenarios, if only core exercises are submitted for mentoring, there should be a fast turnaround, but the moment you submit a side exercise for mentoring you'll probably be waiting a long time and be blocked.

**Comment by F3PiX** [comment]
My criminal record is cleared. 🎉
