### ISSUE TITLE
Unable to submit

### ISSUE THREAD

**Issue by JerryFireman** [exercism/exercism.io#4143]
I am having problems trying to submit my first solution file. I moved the file to the exercism directory hoping this would make it easier. Here's what I get ...

C:\Exercism>dir
 Volume in drive C is OS
 Volume Serial Number is 2CD4-6D3A

 Directory of C:\Exercism

08/03/2018  12:53 PM    <DIR>          .
08/03/2018  12:53 PM    <DIR>          ..
08/03/2018  12:53 PM                 0 exercism
07/26/2018  06:29 PM         8,539,648 exercism.exe
08/03/2018  12:29 PM               193 hello_world.go
               3 File(s)      8,539,841 bytes
               2 Dir(s)  247,894,827,008 bytes free

C:\Exercism>exercism submit hello_world.go
Error: not in workspace

I get the same error when I try entering the path. Could you please let me know what I am missing? Thanks for the your help!

Jerry

**Comment by iHiD** [comment]
Hi @JerryFireman. How did you install Exercism locally? Did you use the Installer for windows or go down the manual route?

**Comment by JerryFireman** [comment]
Thanks for responding Jeremy. I used the installer for windows.

**Comment by rpottsoh** [comment]
@JerryFireman you need to be in the folder where hello_world.go exists.  This folder should be within the folder designated by `workspace`.
for example at the CMD prompt execute:
```
C:\Exercism>exercism workspace
```
When you downloaded `hello-world` the CLI should have created a sub-folder for `Go` and a folder beneath that for `hello-world`.  The CLI is expecting your solution file to be there.  If you CD to that folder and then `exercism submit hello_world.go` it should work.  `hello_world.go` needs to be in that folder.

Lets assume your workspace is `c:\exercism`.  The CLI will have created folder `c:\exercism\go\hello-world\` for you.  Place your solution file there.

Also, confirm that you are using the latest version of the CLI.  It should be 3.0.6.  If your version is prior to 3.0.5 you should either manually download and install the latest version or re-run the Windows Installer to get the latest version of the CLI for Windows.  Initial versions of version 3 and versions prior to 3, the `upgrade` feature of the CLI doesn't work in Windows.  If you have 3.0.5 I think `upgrade` works.  If you try and the result is a CLI that doesn't work at all then use one of the other two methods for upgrading.

**Comment by JerryFireman** [comment]
Thanks very much for your help Ryan! I moved my solution file into the Go directory created during the Exercism installation and successfully uploaded it. One issue -- the Go directory created by Exercism is outside my Go workspace so the file does  not run for me when I try to execute it from the Go directory. I assume I can work on and test problem within my Go workspace and then move then move the solution files to the Exercism Go directory when ready to submit. Is that right?

**Comment by rpottsoh** [comment]
Excellent!  I am glad to see you managed to work yourself out of the jam!  :1st_place_medal: 

> then move then move the solution files to the Exercism Go directory

That is an acceptable way to go about it.  There may be a better way that I am not aware of.  I know Go likes its folders to be setup its way...  If there are any Go people monitoring that might have a better suggestion for @JerryFireman I'm sure he would appreciate learning about it.

cc: @exercism/go

**Comment by NobbZ** [comment]
Go exercises on exercism are designed to be usuable and solvable without requiring anything but the stdlib, the last time I did them they were easily runnable from outside the go workspace in the exercism workspace.

And I checked again right now, even though using a SSH connection from a phone is quite clumsy to type on, but this worked:

```plain
$ exercism d --track=go --exercise=hello-world

Downloaded to
/home/nobbz/exercism/go/hello-world
$ cd go/hello-world
$ go test
PASS
ok      _/home/nobbz/exercism/go/hello-world  0.001s
```

**Comment by JerryFireman** [comment]
Thanks very much for your help Ryan and Norbert! Norbert, thanks for the tip on running the exercises outside the go workspace. I will try to figure out why that is not working yet for me.
