### ISSUE TITLE
What is the exercism legal structure?

### ISSUE THREAD

**Issue by masters3d** [exercism/exercism.io#4147]
I'd like to get an idea of community structure for exercism. 

- Who is the current the 'core team'?
- How does somebody become a core team? (Aside from the obvious founders. )
- What role does the core team play in making big decisions?

Essentially I have all the questions the below sample documents answers for me about the swift project.
https://swift.org/community/#community-structure

Thank you

**Comment by nickborromeo** [comment]
@masters3d I am not part of the core team but the exercism website lists the core team members in https://exercism.io/team

A small snippet from that page 
> Our core team manage the strategic and organisational sides of Exercism, the Exercism website and CLI. They are responsible for fulfilling our mission statement and maintaining our values.

and you can find the values listed in https://exercism.io/values

Hope this helps 😄

**Comment by masters3d** [comment]
Thank you @nickborromeo Let me rename my question. 

I am mostly interested in finding out how exercism is organized to function as an non profit org (Is it? I was assuming this but I can't find any reference to it.). 

Here is another example of more of less of an example of what I am looking for. https://llvm.org/foundation/

**Comment by iHiD** [comment]
@masters3d. Until recently Exercism wasn't a legal "thing". Everything was copyrighted to Katrina. Last year we changed that and created Exercism Inc, primarily as a way of protecting Katrina directly from liability. We're currently spending time working out what the best structure is for Exercism and how we build something which we can hire people into and grow properly. We'll have those decisions made and documented by the end of the year :)

**Comment by iHiD** [comment]
@masters3d Is there a particular reason for your interest?

**Comment by masters3d** [comment]
@iHiD Makes sense. I was asking because it feels to me like the project is moving towards a model where it could potentially become some sort of startup, raise capital, charge for things etc. I am not opposed to that if that is the plan but I just want to know where we stand as contributors. I guess this would not much different than HackerRank or similar.  

I'll be looking forward to what your team comes out by the end of the year.

**Comment by iHiD** [comment]
Thanks for the info :)

To colour things in a little more: We have no plans to raise external investment (been there, done that, not a fan) and Exercism - the learning platform - will always be entirely free.

Taking Exercism to where we want it to get to (helping millions of people regardless of their background) is going to involve having money though. We eventually want a full time team working on different aspects and we want to be able to do things like letting people code on the website, not exclusively offline via the CLI. For those things we'll need cash beyond what Katrina and I are able to put in. We're trying to work this out, and see if there are other products around it that we could build that will help fund it moving forward (e.g. maybe something around recruitment) and/or sponsorship and/or government donations, etc. I'm a Director a charity that gets over $1m per year in government funding - it would be nice if we could replicate that for example.

A very strong consideration for us is making sure that we don't unduly benefit from the work of others - that's very much at the forefront of our attitudes and thoughts as we discuss all this, and it's why we're taking our time to make sure we get it right. We're 100% not building Exercism to try and get rich - none of the leadership team is motivated by that - but it would be nice if it was able to be successful self-sufficient :)

I look forward to sharing all our conclusions when we get there and thanks again for the thoughtful question :)
