### ISSUE TITLE
Are email confirmation emails sending?

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism.io#4152]
We've had a few reports of people not getting them. 

@kntsoriano and/or @jackhughesweb (whoever gets here first) - Can you check and/or fix pls?

**Comment by jackhughesweb** [comment]
My local environment is sending email confirmations after signup, but not for re-sending the confirmation emails:
```
rails_1  | Started POST "/users/confirmation" for <IP> at 2018-08-07 09:20:58 +0000
rails_1  | Cannot render console from <IP>! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
rails_1  | Processing by ConfirmationsController#create as HTML
rails_1  |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"<Token>", "user"=>{"email"=>"test@example.local"}, "button"=>""}
rails_1  | No template found for ConfirmationsController#create, rendering head :no_content
rails_1  | Completed 204 No Content in 1526ms (ActiveRecord: 0.0ms)
```
There are a couple of empty methods in the confirmations controller: https://github.com/exercism/website/blob/5f785236ca46cc30534b1875c693c8d899236963/app/controllers/confirmations_controller.rb#L4

Commenting out the `create` and `after_resending_confirmation_instructions_path_for` methods then sends the email and redirects to the log in page with the correct flash message.

I'm not sure why these empty methods exist which neither call super nor have their own logic? @iHiD

**Comment by iHiD** [comment]
@jackhughesweb Me neither. Want to submit a PR with them working? Could you then check the flow for a fake user in production pls to ensure you get both things.
