### ISSUE TITLE
Cannot download hello-world when track in beta - get "solution not found" error? 

### ISSUE THREAD

**Issue by macta** [exercism/exercism.io#4158]
I'm cross referencing this from https://github.com/exercism/cli/issues/694 as its holding us back from testing our language track.

The pharo track has been moved to "beta" mode in V2 exercism, but when you use the command line client you get an error 'solution not found' even though the configlet linter is fine locally and the config.json looks ok?

e.g.
```
$exercism download -t pharo -e hello-world
Error: Solution not found
```
I would expect the configlet to fail if there was no solution - and there appears to be one that matches the config.json solution regex. So I'm stumped.

I've also noticed that the second exercise, also in the config.json file, "two-fer", gives an "exercise not found" error.

Is testing non-live tracks not supported?

**Comment by NobbZ** [comment]
As I'm unable to see the pharo-track in my dashboard, and I've also not heard about beta mode before, I have to ask, have you joined the track?

If I try to fetch `hello-world` for the `d` track (which I have not joined), I do get the very same message.

**Comment by macta** [comment]
Hey thanks - thats exactly what it is.

I think the error message could be better, but this unblocks me - thanks
