### ISSUE TITLE
Allow mentors to see discussions they're not a part of

### ISSUE THREAD

**Issue by pgaspar** [exercism/exercism.io#4166]
With recent changes in https://github.com/exercism/website/pull/300 mentors are no longer able to see discussions in solutions they are not explicitly mentoring.

Instead of seeing what other mentors have said about a solution, mentors now see this:

<img width="533" alt="screen shot 2018-08-05 at 20 28 15" src="https://user-images.githubusercontent.com/31735/43689208-b59361c0-98ee-11e8-8778-d04a038b9810.png">

This isn't great because it prevents mentors from sharing solutions with other mentors and from learning with other mentors:

> One of the ways I improve as a mentor is to see and think about what other mentors point out as issues (as well as _how_ they do it). [...] What I’ve been doing is open a few solutions that I’m not going to mentor for some reason, leave them open and refresh the tabs a few days later, hoping to see what other mentors say, so I can learn from those comments.

Slack context:

<img width="1036" alt="screen shot 2018-08-05 at 20 25 16" src="https://user-images.githubusercontent.com/31735/43689231-1aabe9ba-98ef-11e8-9ef8-a8ddc702749f.png">

**Comment by iHiD** [comment]
Thanks. We'll sort something out. Sorry for the unintended side effect.

**Comment by pgaspar** [comment]
I'm amazed at how quickly you're addressing all this stuff. Thank you!

**Comment by iHiD** [comment]
Thanks! :)
