### ISSUE TITLE
Outdated "Submitting Incomplete Solutions" section in README

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/exercism.io#4185]
I've checked a couple of README files for various tracks, and it appears that multiple track still have this text appended to each README:

> ## Submitting Incomplete Solutions
> It's possible to submit an incomplete solution so you can see how others have completed the exercise.

While it is indeed possible to submit incomplete solutions, I don't believe you then get to see how other have completed the exercise. I believe this should be updated to reflect the current state.

**Comment by rpottsoh** [comment]
I think this is the same as #4076.

**Comment by ErikSchierboom** [comment]
Correct. My search fu was weak.
