### ISSUE TITLE
Trouble submitting solution

### ISSUE THREAD

**Issue by fyi2** [exercism/exercism.io#4196]
I am struggling to submit my answers to Exercism, I am on the Javascript track. I did the hello world challenge ok. Tried Leap year, from the CLI it says my submit was successful but does not show it as done in the system. Any ideas?

**Comment by NobbZ** [comment]
Is it submitted? Can you access the submitted code via the web interface?

If so, there should be a box telling you that you get mentored soon, and as soon as you got mentored and the mentor approved your solution, you can complete it.

If though your solution isn't even accessible via the web interface, please tell us something more:

```
$ cat $(exercism workspace)/javascript/leap/.solution.json
$ exercism troubleshoot
```

Also try submitting again and show us the output.

**Comment by fyi2** [comment]
➜  Exercism git:(master) ✗ cat javascript/leap/.solution.json
{"track":"javascript","exercise":"leap","id":"45ef5bc1935041419d5d8e6a376d687b","url":"https://exercism.io/my/solutions/45ef5bc1935041419d5d8e6a376d687b","handle":"cdrainxv","is_requester":true,"auto_approve":false}%


➜  Exercism git:(master) ✗ exercism troubleshoot             

Troubleshooting Information
===========================

Version
----------------
Current: 3.0.6
Latest:  3.0.6


Operating System
----------------
OS:           darwin
Architecture: amd64


Configuration
----------------
Home:      /Users/fyi2
Workspace: /Users/fyi2/Exercism
Config:    /Users/fyi2/.config/exercism
API key:   4fab*****************************49f

API Reachability
----------------

GitHub:
    * https://api.github.com
    * [connected]
    * 108.940832ms

Exercism:
    * https://api.exercism.io/v1/ping
    * [connected]
    * 446.218367ms


If you are having trouble please file a GitHub issue at
https://github.com/exercism/exercism.io/issues and include
this information.


Exercism git:(master) ✗ exercism submit javascript/leap/leap.js


    Your solution has been submitted successfully.
    View it at:

    
    https://exercism.io/my/solutions/45ef5bc1935041419d5d8e6a376d687b

**Comment by NobbZ** [comment]
And it is really not accessible using the link?

Can you perhaps provide a screenshot of your tracks dashboard and of whatever you see after clicking the `leap`-card?
