### ISSUE TITLE
Position statement: I don't want examples to go in .meta

### ISSUE THREAD

**Issue by petertseng** [exercism/exercism.io#4505]
I am filing this merely to record my current position, and potentially refer back to it later.

Note that:

* There is no Exercism tooling that opposes my position
* There is no proposal in motion that opposes my position

Therefore, I don't need action or discussion on this position. I will be closing this issue immediately.

In https://github.com/exercism/discussions/issues/158 , it was suggested that examples might go in `.meta`.

To me, examples are so important that I oppose the idea that they should go in any directory starting with `.`. That makes them too inconvenient to tab-complete.

I plan to defend this position if there is ever any proposal to make it into a standard that examples should go in `.meta`.

**Comment by iHiD** [comment]
I would like examples to go into the mentor notes setup personally.
