### ISSUE TITLE
CLI Token is Invalid

### ISSUE THREAD

**Issue by a-britt** [exercism/exercism.io#4623]
I am stuck at the "configure exercism" part of setting up the CLI. Every time I try to set up the CLI, it tells me my token is invalid. I am using Windows PowerShell, I don't know if that is causing the problem. I uninstalled the CLI and reinstalled it to see if that would fix it, but that didn't work either! I also changed my CLI token multiple times in the settings menu, and that also did not work. I'm unsure how to fix this, please help! I am very new to all of this, so I'm quite confused. :(

**Comment by iHiD** [comment]
Hello! Could you upload a screenshot please to help us see exactly what you're doing and what's happening? Thanks :)

**Comment by iHiD** [comment]
You want to remove the `<` and `>`. 

The pattern `<something>` is often used to signify something that needs replacing. The angled brackets signify a placeholder of sorts.

**Comment by Mipie** [comment]
Oh okay, thank you very much! I was able to configure the CLI.
