### ISSUE TITLE
Practice Mode queue often only grows and never shrinks

### ISSUE THREAD

**Issue by sshine** [exercism/exercism.io#5105]
@coriolinus wrote (and I have experienced myself):
> I've also had requests for mentorship queued up since day 2 of v2

Currently, requests for feedback in Practice Mode are sorted last.

This means that for some tracks they are literally never reached.

We really should either have only one queue, or not enable "request feedback".

Letting people request feedback and never giving it to them is a false pretense.

**Comment by iHiD** [comment]
I'm going to close this as it'll be addressed in the v3 tracks. To quote [that issue](https://github.com/exercism/exercism/issues/5088).

> Students will be able to ask questions to the community about their exercises, but not directly to mentors.

But thank you for the extra reference point :)
