### ISSUE TITLE
Change associated github username for account

### ISSUE THREAD

**Issue by ghost** [exercism/exercism.io#5677]
Reopening #5555 

@iHiD After the release of the exercism platform v3, I would like to change my Github username that I am using for login. Do you have all the information you need?

(Btw, the new release really looks amazing)

Thank you!

**Comment by iHiD** [comment]
Yay and thank you. I'll mark this is a high-priorty and get to it as soon as the urgent things are out of the way :)

**Comment by rustycat17** [comment]
Thank you very much. Looking forward to working on the new exercises and tracks. :-)

**Comment by rustycat17** [comment]
Hi @iHiD

can you estimate how much longer this will take? I assumed this will just be a small issue, but if it is creating too much effort, I can also just create a new account on exercism, it would just be convenient to use the existing history. Thank you and have a nice weekend.

**Comment by iHiD** [comment]
Done. can you tell me if it's all worked ok pls?

**Comment by iHiD** [comment]
As a reference in case something is broken, your user ids are `[621956, 674307]`

**Comment by rustycat17** [comment]
It still is associated to the old Github username (when I tried the new Github username, it redirected to https://exercism.org/user_onboarding), and now the new Github username created a new exercism account. Interestingly, the handle under https://exercism.org/settings for the old Github handle has now the new of the new Github account. (Oh, I hope this is still understandable)

Thank you for helping me with that. Should I delete the new account?

**Comment by iHiD** [comment]
Are you logging in with email or GitHub here?

**Comment by iHiD** [comment]
I definitely switched the GitHub login's around, but I may not have switched the emails around.

**Comment by rustycat17** [comment]
I used GitHub for logging in. Actually I am not sure if I ever logged in via email. Strange, thank you anyway for your help.
