### ISSUE TITLE
Some caching issue on iterations

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism.io#6052]
https://www.loom.com/share/18ff06e568004fcfa35d32aa8ee185d1

**Comment by SleeplessByte** [comment]
Given that the data for this page is _inlined_ into the HTML, it's unlikely a react issue. Turbo is possible, if you click _back_, but not if it is a redirect. I also don't see cache-control with any positive/active caching, so the thing that's left for me is something on the rails side.

**Comment by iHiD** [comment]
Yeah. So I checked the response coming back from rails (ie the new source) and it has the correct/updated information in it. So that must be being ignored by turbo somehow I think and the cache used instead? Maybe? It's an odd one.
