### ISSUE TITLE
Cannot update published iteration to different iteration

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism.io#6303]
![image](https://user-images.githubusercontent.com/1964376/159975802-bbc56261-6bb4-4373-99e3-307c38c47483.png)

When updating a single-published iteration to a new one, you only see that single published one in the drop down.
After selecting "all", you can select _all_ the iterations in the dropdown.

**Comment by iHiD** [comment]
@ErikSchierboom A bug for you when you fancy solving a React thing.

**Comment by asarkar** [comment]
A workaround is to unpublish the solution and publish again. I’ve made a video in the linked ticket that demonstrates the issue.
