### ISSUE TITLE
convert "exercism.io" to "exercism.org" in repo `homepageUrl`s

### ISSUE THREAD

**Issue by ee7** [exercism/exercism.io#6527]
The `homepageUrl` is the URL that appears in the sidebar on a repo's front page.

There are just a few remaining repos that reference exercism.io there:

```shell
gh repo list exercism --limit 300 --no-archived --visibility public \
    --json name,homepageUrl \
    --jq '.[] | select(.homepageUrl | contains("exercism.io"))'
```

| Repo name                                                                                | `homepageUrl`                     |
| :--------------------------------------------------------------------------------------- | :-------------------------------- |
| [exercism/exercism](https://github.com/exercism/exercism)                                         | https://exercism.io               |
| [exercism/Exercism.jl](https://github.com/exercism/Exercism.jl)                                   | https://exercism.io/tracks/julia/ |
| [exercism/tracks-maintenance-dashboard](https://github.com/exercism/tracks-maintenance-dashboard) | https://tracks.exercism.io        |
| [exercism/v3-dashboard](https://github.com/exercism/v3-dashboard)                                 | https://v3.exercism.io            |
| [exercism/website-icons](https://github.com/exercism/website-icons)                               | https://exercism.io               |

Follow-up to https://github.com/exercism/exercism/issues/6362

**Comment by iHiD** [comment]
These should all bow be done. Thanks.

**Comment by iHiD** [comment]
Ah - that URL was correct: https://tracks.exercism.io/
