### ISSUE TITLE
editor: no syntax highlighting for Zig

### ISSUE THREAD

**Issue by ee7** [exercism/exercism.io#6670]
Zig code is syntax highlighted when viewing an iteration, or when viewing community solutions. However, it is not highlighted in the editor.

I think we can either:

1. Use/create a CodeMirror mode for Zig.
2. Highlight Zig code with the highlighting for another language (it is common to highlight as Rust, TypeScript, or Go). 

I believe the file to modify is [`exercism/website`: `app/javascript/components/misc/CodeMirror/languageCompartment.ts`](https://github.com/exercism/website/blob/5b4506ce6479e79a65a0c76be169e9e5f79aabb3/app/javascript/components/misc/CodeMirror/languageCompartment.ts).

If we cannot immediately do option 1, can we highlight Zig as Rust as a stop-gap solution?

I've made a PR to do that: https://github.com/exercism/website/pull/3558

**Comment by joshgoebel** [comment]
Hot take: I think a stop-gap like #2 makes it less likely that #1 will happen so my vote is do it right or don't do it at all.
