### ISSUE TITLE
consider adding an opt-out of re-testing all submitted solutions

### ISSUE THREAD

**Issue by ee7** [exercism/exercism.io#6678]
For a PR that makes a trivial change to a large number of exercises, but is guaranteed to never change the pass/fail status of a previously submitted solution, a track may want to opt-out of re-running the tests for every submitted solution. This can save a huge amount of needless computation.

There is currently no such opt-out. I can see these ways to implement it:

1. A special string in the commit message.
2. A special label on the PR. There is some precedent for this having an effect at merge time: it's how we configure the amount of reputation awarded.
3. Support both option 1 and option 2.

---

Follow-up from https://github.com/exercism/python/pull/3373#issuecomment-1480853252

**Comment by ErikSchierboom** [comment]
> Another option: via a special label on the PR. But let's discuss in https://github.com/exercism/exercism/issues/6678.

This would require us to call the GitHub API whenever we're syncing a track. Not saying we can't, but that is the downside.
