### ISSUE TITLE
Raku representer

### ISSUE THREAD

**Issue by m-dango** [exercism/exercism.io#6726]
I have taken the initial steps for building a representer for Raku here: https://github.com/m-dango/raku-representer

**Comment by kotp** [comment]
Is this in the forums?  I can't find it.

**Comment by m-dango** [comment]
There is currently no topic in the forums, the documentation states an issue is to be opened here so a repo can be created: https://exercism.org/docs/building/tooling/representers/creating-from-scratch

**Comment by ErikSchierboom** [comment]
@m-dango Repo has been created: https://github.com/exercism/raku-representer You should have permissions for that repo (you'll need me to sign off on PRs).
