### ISSUE TITLE
"Increment pointers approach" in C track for Hamming is broken

### ISSUE THREAD

**Issue by Ashvith10** [exercism/exercism.io#6727]
In the following [link](https://exercism.org/tracks/c/exercises/hamming/dig_deeper) (Hamming exercise in C track), there's a link below that points to [Increment pointers approach](https://exercism.org/tracks/c/exercises/hamming/approaches/increment-pointers). However, that link is broken, and throws a 404.

**Comment by iHiD** [comment]
Posted in the forum: https://forum.exercism.org/t/broken-link-in-c-hamming/10571
