### ISSUE TITLE
White page on site in web editor

### ISSUE THREAD

**Issue by AlexTarasevich** [exercism/exercism.io#6730]
Hi! When I use exercism.org and try to write code in web editor I see only white page. How can fix it?
I clean cash and reboot machine.
My device - Macbook Air, OS - Monterey 12.5.1, Browser - Safari 15.6.1

**Comment by SleeplessByte** [comment]
👋🏽 you are best served on the forum or discord for this support request. As the editor is working for me (and probably most people), without further information it will be hard to debug.

**Comment by AlexTarasevich** [comment]
> 👋🏽 you are best served on the forum or discord for this support request. As the editor is working for me (and probably most people), without further information it will be hard to debug.

Thanks, I found error. Just update Safari 👍
