### ISSUE TITLE
Typo on the ABAP track in test case 'Eve' for Kindergarten Garden exercise

### ISSUE THREAD

**Issue by christian-pustianu** [exercism/exercism.io#6738]
In the Kindergarten Garden exercise on the ABAP track, for the test case of Eve, there are 49 characters in the diagram string, of which there are 24 before the `\n` and 23 after. There should be 50 in total (i.e. 24 before and 24 after). This was probably not picked up by people since, if you divide by 2 the length of the string using `/`, in the case of 49, it probably rounds up to 25 and the test still passes. If instead, the division is done using `DIV`, it returns 24 in the case of 49, which makes the test fail.

```
"for Eve
  METHOD test_eve.
    DATA(expected_values) = VALUE string_table( ( |clover| ) ( |grass| ) ( |radishes| ) ( |grass| ) ).
    cl_abap_unit_assert=>assert_equals(
      act = cut->plants( diagram = 'VRCGVVRVCGGCCGVRGCVCGCGV\nVRCCCGCRRGVCGCRVVCVGCGC' student = 'Eve' )
      exp = expected_values ).
  ENDMETHOD.
```

**Comment by glennj** [comment]
Topic has been opened in forum: http://forum.exercism.org/t/abap-unit-test-bug-kindergarten-garden/12660

**Comment by christian-pustianu** [comment]
Yep, that was me after I opened up this issue! :)
