### ISSUE TITLE
The issue that happen to building for local server.

### ISSUE THREAD

**Issue by Helorius** [exercism/exercism.io#6742]
Hello, everyone! 
I am going build the local environment for this website project.

I had already installed all programs with README.

The issues are following as:
1) Db migrationg error.
2) The error when running the server.

I would like someone who knows how to build a safe environment to give me advice as soon as possible.

Thank you.
Eric
![migration_error](https://github.com/user-attachments/assets/332418d7-9b58-4813-84fa-aff352656955)
![server_error](https://github.com/user-attachments/assets/5ae122a1-ed94-418c-bd2e-327c1e4bf208)
![server_error1](https://github.com/user-attachments/assets/9fc4f66b-1a88-4575-b2f7-cc12c19a100b)

**Comment by glennj** [comment]
Judging by the README on the website repo, you're unlikely to get any help. AFAIK there are maybe 3 people who know how to do it, and I think they're all busy on other projects.
