### ISSUE TITLE
Allow to rename a team, or remove an empty one

### ISSUE THREAD

**Issue by real34** [exercism/exercism.io#915]
My use case was the following:
- I made a typo in a team name
- to "fix it" I had to create a new team with the same members, and dismiss them from the outdated team
- since it is not possible to remove the group there are now 2 distinct groups which look similar but one f them is unused

The best thing would be to allow to rename a team for this use case, however deleting empty groups might also be an option if it is easier.

**Comment by Nandarun** [comment]
Rename the team by following the below steps
- Click the "Teams" at org or repo level.
- The above will show all the teams, click the team that you want to rename/change
- Above will come up with a refreshed screen with the selected team name. In the top left hand side where team name is there click the "Edit" which will allow you to rename/change the team name.
