### ISSUE TITLE
can't seem to log in

### ISSUE THREAD

**Issue by mjhoy** [exercism/exercism.io#999]
I haven't logged in for, oh, probably a month at least. Today I tried and couldn't get it to work. First it re-authenticates with GitHub, that's fine. But then it just seems to refresh the home page when I click "Log in with Github" without doing anything.

**Comment by mjhoy** [comment]
@kytrinyx this seems to be fixed for me now. should i close?

**Comment by kytrinyx** [comment]
Thanks! Yeah, I would love to understand what happened, but I'm very happy to hear that it's not happening anymore :)
